### ISSUE TITLE
操作有点反常，不大习惯

### ISSUE THREAD

**Issue by coooliang** [Snipaste/feedback#1003]
截图后图片找不到，要点贴图不是很不方便吗
截图后想自己调整截图的大小也不行，最最简单的功能都没有，其它的功能用得很少，很不人性化的操作

**Comment by StarryVoid** [comment]
1、截图后图片找不到？你选择的复制(剪贴板)？保存(磁盘)？贴图(屏幕)？
2、要点贴图不是很不方便？？？请问您平时是怎样的"习惯"导致的"不方便"
3、截图后想调整截图大小：Pro版+截全屏+缩略图自定义显示范围
4、最最简单的功能都没有？请仔细看Snipaste使用说明，第一条**这个软件是一个截图和贴图软件**
5、其他功能用的很少，很不人性化的操作？你不用不代表别人不用，不喜欢请自己开发一个轮子然后来PR，Snipaste有接口可以调用。

**Comment by liulex** [comment]
完全不清楚你开这帖的目的是？
如果是想要提改进，请具体一点；如果就是觉得这软件垃圾，那就直接删了呀，世界上软件那么多，不是每一个都为你打造的。
