### ISSUE TITLE
启动一段时间后自动停止工作

### ISSUE THREAD

**Issue by CJyockleornE** [Snipaste/feedback#1004]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

使用了64和32位1.16.2版本，并下载了前一个1.15.3的64位版本，依然有标题所写的问题，启动1-3分钟内跳出停止工作弹窗，系统版本win 10 enterprise 2016 ltsb

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by liulex** [comment]
可能是这种情况？#961

**Comment by CJyockleornE** [comment]
并不是，热机是我自己自定义的，截取目标是vs2017community。崩溃时也没有进行按键操作。学校的电脑，自用的电脑上一切正常。

2018年10月14日(日) 2:00 Le Liu <notifications@github.com>:

**Comment by liulex** [comment]
@CJyockleornE 
不是快捷键，#961 的问题是**需验证的代理**。

**Comment by CJyockleornE** [comment]
这有可能，要下星期验证了，谢谢

2018年10月14日(日) 2:08 Le Liu <notifications@github.com>:
