### ISSUE TITLE
在复制颜色值可以选择复制哪种类型的颜色值

### ISSUE THREAD

**Issue by wjdmxx** [Snipaste/feedback#1005]
在复制颜色值可以选择复制哪种类型的颜色值
现在只能复制一种（RGB/Hex）
希望可以按“C”复制Hex，按“V”复制RGB值，就很方便

**Comment by liulex** [comment]
https://docs.snipaste.com/zh-cn/key-bindings
![default](https://user-images.githubusercontent.com/2010459/46907870-1fa26280-cf4c-11e8-9263-ea7e997109ca.png)
显示的是什么格式，复制的就是什么格式。
