### ISSUE TITLE
保存文件时，有多个历史目录供选择

### ISSUE THREAD

**Issue by ploverinfo** [Snipaste/feedback#1006]
请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它

比如我一个月内内有多项工作，每天都需要在不同的工作中切换，但是截图另存文件的这种方式只能不停的返回、选择目录、再选择。如果有多个历史目录供选择就可以很方便。

**Comment by liulex** [comment]
这个……请借助楼上回复的系统功能或第三方软件如 Listary.

**Comment by Peter-JXL** [comment]
这个软件能结合listary使用吗？ 我保存时试了下listary快捷键 Ctrl + G，但无法响应；
也没出现listary工具栏；


![1](https://user-images.githubusercontent.com/45090349/52174792-1e839280-27d4-11e9-893c-c76c58d389a2.png)

![2](https://user-images.githubusercontent.com/45090349/52174793-217e8300-27d4-11e9-8bcb-40924cdce5a9.png)
