### ISSUE TITLE
输出文件命名乱码

### ISSUE THREAD

**Issue by Tempoit** [Snipaste/feedback#1007]
输出文件命名乱码
![avatar](http://thyrsi.com/t6/387/1539660703x-1566688347.png)

**Comment by Tempoit** [comment]
v 1.16.2(2018.01.22) 64位
OS：win10 pro
版本号：1809
操作系统版本：17763.55

**Comment by Tempoit** [comment]
系统和软件都改成英文后正常
![avatar](http://thyrsi.com/t6/387/1539661947x1822611359.png)

**Comment by stevenzhu25** [comment]
@Tempoit 可能是因为您的系统原语言是外语？（安装默认语言）

**Comment by Tempoit** [comment]
> @Tempoit可能是因为您的系统原语言是外语？（安装默认语言）

应该是区域的问题
![avatar](http://thyrsi.com/t6/387/1539662609x1822611263.png)
![avatar](http://thyrsi.com/t6/387/1539662684x1822611359.png)

**Comment by liulex** [comment]
谢谢截图！原来跟区域和显示语言没关系，是区域格式的设置导致的。
后续我会在 #969 更新进度。
