### ISSUE TITLE
[FEATURE] 高分屏下希望能显示缩放前的大小

### ISSUE THREAD

**Issue by fly2xj** [Snipaste/feedback#1008]
使用高分屏时会有一个缩放值 150%  200%等, 这样有时想用截图工具量一个这个图片的大小时,  就需要自己手动除以这个缩放值才是原始的大小.

例如200x100的图片,   在200%显示的显示器上,  截图量出来的大小是400X200

**Comment by liulex** [comment]
你把这个图片作为贴图贴出来，然后右键菜单就可以查看大小了。

**Comment by DoveAz** [comment]
我也想要这个功能，我是web前端开发，有时候会用截图量一下尺寸，但是win10缩放设置的175%，导致量东西变得很难。我😭了

**Comment by kfuudotcn** [comment]
我也是搞web开发的，急切需要这一改进，已经购买专业版支持了。

**Comment by Normandanny** [comment]
同求这个功能！！！！谢谢！！！

**Comment by liulex** [comment]
Snipaste 2.5 专业版已实现：
![](https://user-images.githubusercontent.com/2010459/90032327-d8748c80-dcf0-11ea-9859-b7b0bd2dcd0a.png)

**Comment by Lemmingh** [comment]
`px` 给我的第一感觉是**物理像素** (physical pixel)，而 `dp` 理解成了**设备无关像素** (device independent pixel)……😅

可以考虑把 `px` 改成 `epx` 吗？
谢谢。@liulex

**Comment by liulex** [comment]
谢谢你的说明。

首先，我们对物理像素和逻辑像素的理解应该是一致的（桌面设备上，逻辑像素 = 物理像素 / (DPI/96)），只是用什么英文缩写有分歧。

主要是 `dp` 的英文说法很多，可以是 `device pixel`/`device independent pixel`/`density pixel`...

我不是搞前端的，也不是搞设计的，不清楚其中的具体规范。最终决定把逻辑像素记为 `px`，主要还是因为它是 css 里面定义图片尺寸的单位（设备无关），以上用户的需求应该也是跟 css 相关。

我也咨询过几个提出此需求的用户，他们只表示有这个功能就好了，怎么叫无所谓，所以我也很无奈啊……你们让我实现我不需要而你们专业需要的功能，又不愿意提供更具体的描述，这让我怎么快速推进呢。

px = physical pixel（物理像素）, dp = device independent pixel（逻辑像素）
px = logical pixel（逻辑像素）, dp =  device pixel（物理像素）

对我来说，这两套说法都能说通，但显然你比我更专业，我很乐意采纳你的提议。不过，我还是再多问一句吧，其他软件上，对这两种单位，是怎么称呼的呢？这个应该是最有参考意义的。

**Comment by Lemmingh** [comment]
## px, pixel

**Pixel** 本身只是“图像的最小单位”，需要放在具体语境中才能确定含义。

在图形和显示这一块，我印象里一般指，物理存在的点 (physical pixel)。

<details open>
<summary>CSS 的 px</summary>

CSS 的 `px` 的定义给我一种像是 `epx` 但又很奇怪的感觉。

**参看**

* <https://www.w3.org/TR/css-values-3/#absolute-lengths>
* <https://developer.mozilla.org/en-US/docs/Web/CSS/length#Absolute_length_units>

</details>

## dp, dip, device-independent pixel

**Device-independent pixel** 大概是最早出现的逻辑像素单位。

* Microsoft 的定义针对桌面平台。`dp = px / (DPI / 96)`
* Google 的定义针对移动平台。`dp = px / (DPI / 160)`

**参看**

* <https://docs.microsoft.com/en-us/windows/win32/learnwin32/dpi-and-device-independent-pixels#converting-physical-pixels-to-dips>
* <https://developer.android.com/training/multiscreen/screendensities>

## epx, effective pixel

**Effective pixel** 是 Microsoft 在 UWP 设计中引入的概念。它考虑了显示器的分辨率、像素密度、观看距离。

```
epx = F(px, DPI, distance)
```

具体算法未公开。传说，在桌面平台上相当于 `dp`。

**参看**

* <https://docs.microsoft.com/en-us/windows/uwp/design/basics/design-and-ui-intro#effective-pixels-and-scaling>

## point

**Point** 是 Apple 使用的逻辑像素单位，应该类似于 `dp` 且算法简单得多。

这个名字容易跟印刷上的 `pt` 混淆。

**参看**

* <https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/image-size-and-resolution/>
* <https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/image-size-and-resolution/>
* <https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/>

---

## 结论

我建议用 `dip` 表示逻辑像素，以减少歧异。

**Comment by liulex** [comment]
@Lemmingh 非常感谢！
下个版本我会使用 `px` 表示物理像素，`dip` 表示逻辑像素。
