### ISSUE TITLE
在 Mac 下贴图不能穿越"桌面"

### ISSUE THREAD

**Issue by onefansofworld** [Snipaste/feedback#1010]
在 Windows 下，多任务"桌面"，如果贴图了换到第二个"桌面"，贴图还在绝对位置上， Mac 下就会停留在截图的"桌面"，想平移到第二块"桌面"，三指在触摸板从上往下滑贴图就消失了。
不是很清楚是系统权限的设定差异还是 Bug，如果是 Mac 权限问题的话就关闭这个 issue 吧，谢谢 :)
找到一个原来的 issue：https://github.com/Snipaste/feedback/issues/934

**Comment by liulex** [comment]
不管是 Mac 还是 Windows，都还没进行多桌面的适配。

**Comment by onefansofworld** [comment]
嗯
