### ISSUE TITLE
WIN10应用商店版，今天，突然，卡巴斯基检测恶意软件；压缩版本没问题，大概是误报？

### ISSUE THREAD

**Issue by aLLeENSmith** [Snipaste/feedback#1011]
WIN10应用商店版；

---------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/31880062/47191453-1107e100-d37a-11e8-87ec-16f7194a2a58.png)

**Comment by liulex** [comment]
Snipaste 2.1.2 x64: [virustotal](https://www.virustotal.com/#/file/438431a824ed1e4de1d02a49f29b22a30447ed25b568f2ca24d40590b5107ef3/detection)
Snipaste 2.1.2 x86: [virustotal](https://www.virustotal.com/#/file/8dbb28a63eb773eaf72d8f14dc510d945025b37a4c0f16591e9dcf609324a1ec/detection)
其次，微软商店版是有微软审核的。

**Comment by aLLeENSmith** [comment]
这个我就是提一提，具体情况我也不懂。

另外，已经换了解压版，没啥问题。

**Comment by aLLeENSmith** [comment]
应该是误报吧，反正换用64位压缩包的版本没有问题；
迷之WIN10应用商店；
