### ISSUE TITLE
【mac】手动选择截图区域后闪退，窗口检测截图时正常

### ISSUE THREAD

**Issue by ningzimu** [Snipaste/feedback#1012]
- mac版本：10.14
- Snipaste版本：1.16.2-beta

复现情景：
只要改变截图区域必复现。

**Comment by ningzimu** [comment]
问题已解决
请查明，造成闪退的原因是“欧陆词典的**划词翻译**功能，关闭这个功能，问题解决，一切恢复正常！

**Comment by singeryoung** [comment]
> 问题已解决
> 请查明，造成闪退的原因是“欧陆词典的**划词翻译**功能，关闭这个功能，问题解决，一切恢复正常！

感谢，问题解决。
补充一下，更准确的原因是欧陆词典的偏好设置里的设置项 **开启划词搜索** 的子级设置项 _强制对所有程序开启划词功能_ 勾选后，会导致Snipaste的截图操作发生闪退。

**Comment by septs** [comment]
已联系欧陆词典的 staff。

**Comment by liulex** [comment]
已找到特征，下次更新修复~

**Comment by Tairraos** [comment]
> 已联系欧陆词典的 staff。

staff是all employees

**Comment by wuhao747003943** [comment]
滚动截图还没有啊，等了三年！
