### ISSUE TITLE
[请求新功能]贴图时识别字体和格式（颜色）

### ISSUE THREAD

**Issue by ZeddG93** [Snipaste/feedback#1014]
请求新功能？
* 贴图时识别文本的字体和格式（颜色）

**Comment by ZeddG93** [comment]
![paste_ 4d6a20](https://user-images.githubusercontent.com/7886856/47542320-78d8a180-d90f-11e8-8ca9-24cb203ffb39.jpg)

**Comment by xianghongai** [comment]
不可能实现，不然就不需要截图了。
