### ISSUE TITLE
有关全屏截图的问题。。。

### ISSUE THREAD

**Issue by i5151** [Snipaste/feedback#1015]
我用的是UWP版本，这也是我安装UWP应用以来，能自动启动并在托盘显示图标的第一个软件。

总体来说，功能很强大，但感觉忽略了最基本的截图功能。

首先，居然不能自动选取全屏截图，不管是截取桌面、全屏视频，都是把任务栏排除了，只能手动选择。截取桌面的话，手动选择除了效率低点还可以接受；但视频就不同了，手动选择会让视频显示播放控件，这是无法忍受的。

第二，不能自动保存。有时截图只是想把内容保存下来，做个资料，不想编辑也不想粘贴，只是想自动保存到指定的目录里，但是现在任何截屏动作都会出现编辑界面，最快的也是点击保存之后才可以。也是相同的情况，普通截图还能接受，但是视频截图，尤其是连续视频截图，就很不方便，而且，视频截图之后会把窗口最小化。

**Comment by linzyjx** [comment]
1. 全屏截图可使用系统的win+PtrSrc键，其会自动保存在图片/屏幕捕获文件夹里
2. Snipaste中的快捷键系统也可以做到，使用snip --full -o quick-save命令并在设置中绑定快捷键，即可一键实现截取全屏并保存到设置好的快速保存文件夹（该功能可能需要专业版支持）
3. 窗口最小化的问题可能是播放软件自身、或是两者见兼容的问题，可以提供播放器的名字和版本以供开发者查找BUG

**Comment by i5151** [comment]
差点忘了，win+PtrSrc快捷键截的图，只有第一个是保存到了文件，其余的都保存到剪贴板里了，看来还是在软件里设置一个新的快捷键更靠谱。

**Comment by i5151** [comment]
我设置了自动保存，并且关闭了 显示通知的选项，为什么我单击工具条上的磁盘保存按钮时，还是弹出保存文件的窗口，实际上就是另存为了。如何不弹出这个窗口？

**Comment by linzyjx** [comment]
> 正在写反馈的时候，看见您的回复，就直接实验了一下。
> 1、win+PtrSrc可以截取，但只截取了一个截图就不动作了，按快捷键还是视频会闪动一下，暗示已经截屏，但是目录里没有文件生成。建议还是软件再内置一个单独的全屏截取快捷键，可能会更可靠一些。
> 
> 我也找到了Ctrl+A可以全屏截取，可能是和一直使用的PicPick初始设置不同，PicPick选择窗口控件，默认是全屏。本软件不是，感觉还是默认初始截屏设置是全屏比较好，之后可以再移动鼠标选取各个相应的窗口控件
> 。
> 2、放命令行里不好，还是放到设置里更好，额外加上一组快捷键，可以跳过编辑窗口，直接保存成文件。这样既能不做大的改动、保留软件原有的习惯，也可以更快捷地截屏。
> 
> 3、我用的是UWP的视频应用，又试了potplayer的确不会最小化，看来还是对UWP的应用有点兼容性的问题。
> 
> 4、刚想起来，好像没有看到滚动截屏。
> 
> 由于一直使用的PicPick不能满足要求了，升级的5.0版用不习惯，正在找替代的软件，今天在网站上看见有人推荐本软件。加上之前试用过，但那时感觉不太好，就没有继续使用，这次想着在试用一下看看，尤其是推出了UWP的版本，感觉比上次好了很多。

1. win+PtrSrc的截图功能我刚刚也实验了一下，是按一次就截一张图，并且都会保存不会在剪贴板。下图中屏幕截图345就是我连续按下三次自动保存下来的（Win10 1809）
![image](https://user-images.githubusercontent.com/8017477/47613310-ee876d80-dac7-11e8-8a62-b249307267e0.png)

2. 这个命令行的意思是再设置快捷键中有提供自定义命令的选项，并且能绑定快捷键。但是这貌似是专业版特性
![image](https://user-images.githubusercontent.com/8017477/47613340-5342c800-dac8-11e8-94f6-ca4e7b81d903.png)

3. 软件兼容性只有等开发者来查看问题了

4. 滚动支持暂不支持，后续是否添加看开发者心情。如果是网页长截图，可以寻找相关扩展

5. 窗口选取问题，我认为几种方案都各有取舍

6. 工具条的保存按钮就是另存为按钮，需要快速保存请在首选项中设置截图时按键行为

**Comment by i5151** [comment]
> > 正在写反馈的时候，看见您的回复，就直接实验了一下。
> > 1、win+PtrSrc可以截取，但只截取了一个截图就不动作了，按快捷键还是视频会闪动一下，暗示已经截屏，但是目录里没有文件生成。建议还是软件再内置一个单独的全屏截取快捷键，可能会更可靠一些。
> > 我也找到了Ctrl+A可以全屏截取，可能是和一直使用的PicPick初始设置不同，PicPick选择窗口控件，默认是全屏。本软件不是，感觉还是默认初始截屏设置是全屏比较好，之后可以再移动鼠标选取各个相应的窗口控件
> > 。
> > 2、放命令行里不好，还是放到设置里更好，额外加上一组快捷键，可以跳过编辑窗口，直接保存成文件。这样既能不做大的改动、保留软件原有的习惯，也可以更快捷地截屏。
> > 3、我用的是UWP的视频应用，又试了potplayer的确不会最小化，看来还是对UWP的应用有点兼容性的问题。
> > 4、刚想起来，好像没有看到滚动截屏。
> > 由于一直使用的PicPick不能满足要求了，升级的5.0版用不习惯，正在找替代的软件，今天在网站上看见有人推荐本软件。加上之前试用过，但那时感觉不太好，就没有继续使用，这次想着在试用一下看看，尤其是推出了UWP的版本，感觉比上次好了很多。
> 
> 1. win+PtrSrc的截图功能我刚刚也实验了一下，是按一次就截一张图，并且都会保存不会在剪贴板。下图中屏幕截图345就是我连续按下三次自动保存下来的（Win10 1809）
>    ![image](https://user-images.githubusercontent.com/8017477/47613310-ee876d80-dac7-11e8-8a62-b249307267e0.png)
> 2. 这个命令行的意思是再设置快捷键中有提供自定义命令的选项，并且能绑定快捷键。但是这貌似是专业版特性
>    ![image](https://user-images.githubusercontent.com/8017477/47613340-5342c800-dac8-11e8-94f6-ca4e7b81d903.png)
> 3. 软件兼容性只有等开发者来查看问题了
> 4. 滚动支持暂不支持，后续是否添加看开发者心情。如果是网页长截图，可以寻找相关扩展
> 5. 窗口选取问题，我认为几种方案都各有取舍
> 6. 工具条的保存按钮就是另存为按钮，需要快速保存请在首选项中设置截图时按键行为

1、我怎么按win+PtrSrc就成功了一次，那之后就再没有保存成文件。
2、就是说它能有自己专用的截图快捷键。如果不是全屏，像第二个快捷键“截屏并自动复制”，可以修改成“截屏并自动保存”吗？也就是说快速保存并不限于全屏。
4、滚动支持的确很重要，PicPick就是对opera浏览器的滚动支持不好了，我才要淘汰它的。普通版不支持的话，至少专业版应该支持。
6、截屏中的按键行为，能自定义的按键很少。而且左键双击也和实际动作不符。
      另外，输出-文件的“快速保存”和“自动保存”是规范哪个按键动作的？勾选不勾选，怎么效果都一样。

**Comment by liulex** [comment]
非常感谢 @linzyjx 的回答，说的都没错，我这里就作一点补充：

@i5151 
> 我怎么按win+PtrSrc就成功了一次，那之后就再没有保存成文件。

> 我特意恢复了一下系统，还是相同的情况。

Win + PtrSrc 是**系统功能**， 在这里讨论毫无意义，你应该向微软反馈。

> 实际上，普通窗口的截屏，想选取整个窗口还是挺难的，一般最大都是范围都排除了标题栏。必须把鼠标放到左右边界上才能选取整个窗口，这时的选取是很难的，标题栏在窗口的截取中是非常重要的部分。

你可以按 <kbd>Tab</kbd> 切换到窗口选取模式，你还可以在首选项里关掉元素选取甚至窗口选取。

> 而且左键双击也和实际动作不符

> 文档解释的和实际还是有差别

这样模糊的表述不会帮你解决任何问题……

> 我设置了自动保存，并且关闭了 显示通知的选项，为什么我单击工具条上的磁盘保存按钮时，还是弹出保存文件的窗口，实际上就是另存为了。如何不弹出这个窗口？

快速保存/自动保存/手动保存 是三个不同的功能，你点工具栏上的保存按钮就是手动保存。

> 但是快速保存并没有保存，两个都勾选了，和没有勾选一样，并不能快速保存。

![default](https://user-images.githubusercontent.com/2010459/47617363-68881880-db01-11e8-8077-fb38a82760ef.png)

**Comment by i5151** [comment]
> 非常感谢 @linzyjx 的回答，说的都没错，我这里就作一点补充：
> 
> @i5151
> 
> > 我怎么按win+PtrSrc就成功了一次，那之后就再没有保存成文件。
> 
> > 我特意恢复了一下系统，还是相同的情况。
> 
> Win + PtrSrc 是**系统功能**， 在这里讨论毫无意义，你应该向微软反馈。
> 
> > 实际上，普通窗口的截屏，想选取整个窗口还是挺难的，一般最大都是范围都排除了标题栏。必须把鼠标放到左右边界上才能选取整个窗口，这时的选取是很难的，标题栏在窗口的截取中是非常重要的部分。
> 
> 你可以按 Tab 切换到窗口选取模式，你还可以在首选项里关掉元素选取甚至窗口选取。
> 
> > 而且左键双击也和实际动作不符
> 
> > 文档解释的和实际还是有差别
> 
> 这样模糊的表述不会帮你解决任何问题……
> 
> > 我设置了自动保存，并且关闭了 显示通知的选项，为什么我单击工具条上的磁盘保存按钮时，还是弹出保存文件的窗口，实际上就是另存为了。如何不弹出这个窗口？
> 
> 快速保存/自动保存/手动保存 是三个不同的功能，你点工具栏上的保存按钮就是手动保存。
> 
> > 但是快速保存并没有保存，两个都勾选了，和没有勾选一样，并不能快速保存。
> 
> ![default](https://user-images.githubusercontent.com/2010459/47617363-68881880-db01-11e8-8077-fb38a82760ef.png)

感谢作者大神的回复。
Win + PtrSrc 虽然是系统功能，但它不是在本软件能产生作用吗？并且之前的@linzyjx让我如此操作，只是我就成功了一次。既然起作用，本软件肯定就有代码是处理这个快捷键的，相当于做了重定向，和本软件产生的关联找不到微软头上。

我想说的是截屏--按键里，左键双击：定义的是复制到剪贴板，实际产生的效果是直接保存到文件了。

其他说明，我试一下。

再次感谢回复。

**Comment by septs** [comment]
@i5151 左键双击 您在哪里使用过这种实现？

**Comment by i5151** [comment]
> @i5151 左键双击 您在哪里使用过这种实现？

我现在点击托盘图标进入截图状态，只要双击左键就自动把截图保存到指定的目录里了。虽然和设置里的描述不符，但这正是我需要的。

**Comment by liulex** [comment]
呃……我既然都让你找微软了，说明 Snipaste 并没有对 Win + PrtSrc 做过任何处理，你关掉 Snipaste 它也一样起效，@linzyjx 的意思是你的需求系统功能就可以实现。

左键双击，如果是设置的是复制到剪贴板，那么你应该检查剪贴板是不是有图像，只要有，那就不存在 "而且左键双击也和实际动作不符"。至于同时保存到了指定目录，那是 `自动保存` 的作用。

**Comment by i5151** [comment]
> 呃……我既然都让你找微软了，就说明 Snipaste 并没有对 Win + PrtSrc 做过任何处理，你关掉 Snipaste 它也一样起效，@linzyjx 的意思是你的需求系统功能就可以实现。
> 
> 左键双击，如果设置的是复制到剪贴板，那么你应该检查剪贴板是不是有图像，只要有，那就不存在 "而且左键双击也和实际动作不符"。至于同时保存到了指定目录，那是 `自动保存` 的作用。

好，你解释的Win + PrtSrc是权威的。

左键双击，剪贴板里的确有我截取的图像。自动保存是说只要剪贴板有图像，它就自动保存到目录吗？如果是这样，那Win + PrtSrc保存到剪贴板里的图像，为什么不自动保存呢？

**Comment by i5151** [comment]
> > 那Win + PrtSrc保存到剪贴板里的图像，为什么不自动保存呢？
> 
> Snipaste 不是监控剪贴板，不是说任何地方复制了图像或者其他程序执行了截图，Snipaste 都会把它放到自动保存目录。只有 Snipaste 自己放到剪贴板里的图像，它会再帮你自动保存。

那你是怎么判断剪贴板里的图像是snipaste截取的？而且@linzyjx居然实验成功了那么多次怎么解释？

**Comment by i5151** [comment]
而且，系统快捷键虽然不能自动保存，但可以粘贴，难道粘贴没有区分是谁截取的？

**Comment by liulex** [comment]
> 那你是怎么判断剪贴板里的图像是snipaste截取的

打个比方，人就是我打的，难道我还要去问一下被打的那人，我才知道没错是我打的他吗……

那图就是我截的，那我放完剪贴板再给你存一下文件就好了啊。

> 而且@linzyjx居然实验成功了那么多次怎么解释？

人家系统功能好用，你的不好用啊。

**Comment by i5151** [comment]
> > 那你是怎么判断剪贴板里的图像是snipaste截取的
> 
> 打个比方，人就是我打的，难道我还要去问一下被打的那人，我才知道没错是我打的他吗……
> 
> 那图就是我截的，那我放完剪贴板再给你存一下文件就好了啊。
> 
> > 而且@linzyjx居然实验成功了那么多次怎么解释？
> 
> 人家系统功能好用，你的不好用啊。

你这两个解释就自相矛盾。

我刚想到了，我按系统快捷键的时候，实际上Snipaste并不是在激活状态，它并没有做好保存剪贴板图像的准备，因为我不激活截图功能，我在其他地方只是复制了一个图像，Snipaste是没有必要都把它保存成图像的，也不该那么做。

如果你在Snipaste没有对系统的快捷键进行设置，@linzyjx能把图像保存是很奇怪的。他得必须让Snipaste一直处在截图之后，保存图像到剪贴板的状态，才能把剪贴板的图像保存，这不知道他是怎么做到的。

我敢肯定绝不是你不负责的一句：我的系统没他好能解释的。

实际上，我的系统是前不久买的win 10专业工作站版的正版。

**Comment by liulex** [comment]
？？？

我强调了千百遍 Win + PrtSrc 保存出来的图片和 Snipaste 无关，所以何来 "我在其他地方只是复制了一个图像，Snipaste是没有必要都把它保存成图像的，也不该那么做"？

![image](https://user-images.githubusercontent.com/8017477/47613310-ee876d80-dac7-11e8-8a62-b249307267e0.png)

这几张图显然跟 Snipaste 没有任何关系啊！没有任何关系！

**Comment by i5151** [comment]
> ？？？
> 
> 我强调了千百遍 Win + PrtScr 保存出来的图片和 Snipaste 无关，所以何来 "我在其他地方只是复制了一个图像，Snipaste是没有必要都把它保存成图像的，也不该那么做"？
> 
> ![image](https://user-images.githubusercontent.com/8017477/47613310-ee876d80-dac7-11e8-8a62-b249307267e0.png)
> 
> 这几张图显然跟 Snipaste 没有任何关系啊！没有任何关系！

那你没有明白我的意思，如果snipaste在激活的截图状态下，能自动保存剪贴板里的图像；snipaste是可以自动保存其它软件复制到剪贴板里的图像。得必须在snipaste里按了保存到剪贴板的动作，和在自动保存产生动作之前替换掉剪贴板里的图像，但这是不太可能做到的。

我并没有仔细看他给我全屏截图，以为就是snipaste在按了系统快捷键之后的截图。

**Comment by i5151** [comment]
> 我提Win + PrtSrc的本意是提供其他工具（系统）中更简单的方式供你参考
> win+ptrsrc这个快捷键在系统层面会直接被捕获，snipaste根本不会收到这个信号。也就是说根本不会和snipaste有影响（除非你以管理员权限运行并且把这个快捷键绑定了snipaste中的行为才有可能）。
> 至于不保存的问题，微软的文档中ptrsrc是截取全屏并保存到剪贴板，win+ptrsrc是保存到图片文件夹的屏幕截图中。至于你描述中的功能不一致，需要问微软（bug10能出什么问题我都不惊讶）。

我当时确实以为你是用系统的快捷键在snipaste里截的图，也不能说它和snipaste完全无关，snipaste还是可以把系统快捷键放到剪贴板里的截图，粘贴到屏幕上。

**Comment by linzyjx** [comment]
snipaste的自动保存的原理是在截图过程完成后，将图像存到剪贴板时，顺带保存到设置中指定的保存目录去

感觉你的意思是snipaste做自动保存的操作时是监控剪贴板里图像，但这确实不是snipaste的逻辑

**Comment by i5151** [comment]
并且也可以像snipaste自己的截图一样保存起来，如果不是连续截图的话，也不失为一个全屏截图的解决办法。

**Comment by linzyjx** [comment]
> snipaste还是可以把系统快捷键放到剪贴板里的截图，粘贴到屏幕上。
这一块是贴图的功能

**Comment by i5151** [comment]
> snipaste的自动保存的原理是在截图过程完成后，将图像存到剪贴板时，顺带保存到设置中指定的保存目录去
> 
> 感觉你的意思是snipaste做自动保存的操作时是监控剪贴板里图像，但这确实不是snipaste的逻辑

实际是一个意思、一个效果。

**Comment by i5151** [comment]
> > snipaste还是可以把系统快捷键放到剪贴板里的截图，粘贴到屏幕上。
> 
> 这一块是贴图的功能

没错，贴了之后，可以编辑，可以保存，和snipaste自己截的图没有区别。

**Comment by linzyjx** [comment]
这两个处理方式效果其实不太一样的

有兴趣的话可以来tg群里交流，更实时。这个issue接下来我不会回复了
https://t.me/joinchat/AAAAAD9ZNqG9ZyLuXc-VgQ

**Comment by i5151** [comment]
> 这两个处理方式效果其实不太一样的
> 
> 有兴趣的话可以来tg群里交流，更实时。这个issue接下来我不会回复了
> https://t.me/joinchat/AAAAAD9ZNqG9ZyLuXc-VgQ

好吧，非常感谢了，学习到不少东西。

最后一个问题，怎么我点击购买专业版没有反应，微软账户的登录界面闪一下就没了。

对国人大神的优秀作品，我是非常愿意支持的。

**Comment by i5151** [comment]
@liulex 再次在这个帖子打扰你，https://t.me/joinchat/AAAAAD9ZNqG9ZyLuXc-VgQ这个网址我无法登录。

我第一次安装Snipaste UWP版本时，点击解锁专业版试过，就是登录微软账号，那时我直接退出了。昨天和你讨论之后，我决定放弃PicPick而只使用Snipaste。但是现在我想购买专业版，再次点击，登录微软账号的窗口只是闪一下就退出了。
