### ISSUE TITLE
窗口控件截图的问题。。。

### ISSUE THREAD

**Issue by i5151** [Snipaste/feedback#1016]
为什么喜欢用窗口控件控制截图的范围呢，因为控制截图的范围精确，不用看着放大区域的十字线慢慢对准，更不用截图完成之后必须要到PS中修改。

但现在窗口控件截图有一个问题，很难或者是不能扩展到整个窗口，这样控件截图的优势就体现不出来了，只想截图单个控件的恐怕不多，更多的还是想截取整个窗口。

我提供一个解决方案供作者参考。就是：把标题栏和状态栏（底边框）的选择变化一下，让选择它们本身的同时，也可以把选择扩展到整个窗口。怎么做到呢？可以让鼠标初次放到标题栏或是状态栏（底边框）空白处的时候，选取的是标题栏或是状态栏（底边框）本身，再向上或向下动一下鼠标，就扩展到整个窗口；也可以在标题栏或是状态栏（底边框）上划分出位置，下部分是选取它们本身，上部分是整个窗口，这是对标题栏来说。状态栏（底边框）则刚好相反。

能用Snipaste的窗口控件快速截取整个窗口，那效率提高可是相当多的。

**Comment by septs** [comment]
欢迎到这个 Snipaste 官方 Telegram 群组进行讨论

https://t.me/joinchat/AAAAAD9ZNqG9ZyLuXc-VgQ

**Comment by i5151** [comment]
> 欢迎到这个 Snipaste 官方 Telegram 群组进行讨论
> 
> https://t.me/joinchat/AAAAAD9ZNqG9ZyLuXc-VgQ

我也想讨论，但无法登录，难道需要翻墙吗？
