### ISSUE TITLE
Mac版截图，无法自动识别窗口了

### ISSUE THREAD

**Issue by aoxu** [Snipaste/feedback#1018]
现象是QQ for Mac点开一张聊天消息里的图片，会调用QQ自带的图片查看器打开，Snipaste for Mac在鼠标移上去之后，无法识别这个窗口，依然是默认截取全屏。

**Comment by septs** [comment]
> 截图时对界面元素的检测需要授予 Snipaste 辅助权限，因此默认未启用。需要该功能的用户请到 Snipaste 的首选项窗口手动勾选，勾选后会有相关操作提示
> 如果只需要检测窗口，则无需辅助权限

https://docs.snipaste.com/zh-cn/mac-beta

**Comment by aoxu** [comment]
明白了谢谢~
