### ISSUE TITLE
请问是否有”运行全屏应用时禁用快捷键“功能？

### ISSUE THREAD

**Issue by Mosney** [Snipaste/feedback#1020]
刚才找了一下设置项和已有issue，似乎没有提到这个问题的  
由于玩WOWS需要用Fx键，每次都需要手动屏蔽快捷键，否则就会跟游戏内操作冲突
现实是很多次进游戏都会忘记禁用快捷键，玩完却忘记启用快捷键导致习惯性F1然后打开了各式各样的帮助

**Comment by Amayadream** [comment]
我也碰到这样的事情, 很多游戏快捷键和默认截图贴图快捷键冲突, 如果能有一个**全屏时禁用快捷键**或者**快速禁用/启用快捷键**就好了

**Comment by StarryVoid** [comment]
任务栏图标 右键点击 禁用快捷键。

**Comment by liulex** [comment]
没有针对全屏的，毕竟视频软件、浏览器等软件也可以全屏，但显然它们不需要屏蔽截屏功能。
[专业版](https://docs.snipaste.com/zh-cn/pro?id=b-%e6%9b%b4%e8%87%aa%e7%94%b1%e7%9a%84%e5%ae%9a%e5%88%b6%e5%8c%96)可以指定在特定程序中屏蔽某个快捷键。

**Comment by Mosney** [comment]
> 没有针对全屏的，毕竟视频软件、浏览器等软件也可以全屏，但显然它们不需要屏蔽截屏功能。
> [专业版](https://docs.snipaste.com/zh-cn/pro?id=b-%e6%9b%b4%e8%87%aa%e7%94%b1%e7%9a%84%e5%ae%9a%e5%88%b6%e5%8c%96)可以指定在特定程序中屏蔽某个快捷键。

好吧 ，我的意思是加一个复选框，默认不开启，由使用者自行决定是否开启全屏禁用快捷键

**Comment by WWNNL** [comment]
是否可以增加一个禁用快捷键的快捷键，这个快捷键不会被禁用，可以由用户更改，按下该快捷键即禁用除本快捷键外的所有快捷键，再次按下可恢复，虽然看起来有点多此一举，但是有时候在游戏中偶尔也需要截图，这时候去找小图标再右键恢复快捷键很不效率。

**Comment by liulex** [comment]
> 是否可以增加一个禁用快捷键的快捷键

专业版有这个。

**Comment by Geeyun-JY3** [comment]
给作者补个：https://github.com/Snipaste/feedback/issues/2015#issuecomment-968065514
