### ISSUE TITLE
$yyyy-MM-dd_HH-mm-ss$识别为了乱码

### ISSUE THREAD

**Issue by ArsenicSS** [Snipaste/feedback#1022]
Snipaste_$yyyy-MM-dd_HH-mm-ss$.png
识别成了乱码
Snipaste_〉〇〈』-〈〈-〇』_〈」-〉』-〇「

![snipaste_ - - _ - -](https://user-images.githubusercontent.com/40692855/48186590-603aa380-e373-11e8-8337-2800d13f9714.png)

**Comment by septs** [comment]
已知，已修复请更新到最新版本。
