### ISSUE TITLE
能否添加一个显示鼠标箭头的选项

### ISSUE THREAD

**Issue by Baason** [Snipaste/feedback#1023]
有时候需要显示鼠标操作，所以能不能增加一个显示鼠标箭头的选项，方便应用。 
另外，是否可以支持截动图？

**Comment by Genteure** [comment]
1. [按 ` 键](https://docs.snipaste.com/zh-cn/key-bindings?id=%E5%8F%AA%E5%AF%B9%E6%88%AA%E5%9B%BE%E6%9C%89%E6%95%88)
2. #19
