### ISSUE TITLE
mac版双屏情况下截副屏幕的

### ISSUE THREAD

**Issue by treblam** [Snipaste/feedback#1026]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* mac 电脑接双屏的情况下，希望能支持对副屏进行截图。

**Comment by liulex** [comment]
Mac 版是不支持跨屏截图，扩展屏截图是支持的，鼠标在那个屏就截哪个屏。

**Comment by treblam** [comment]
并没有哦，我试过了，扩展屏是不支持的。

Le Liu <notifications@github.com>于2018年11月20日 周二下午12:46写道：

**Comment by treblam** [comment]
重新试了一下，的确是鼠标在哪个屏幕就截那个屏。
我觉得有必要再优化一下，鼠标在A屏幕开始按F1，把鼠标移到B屏幕也应该能截图。微信的截图功能就是这么做的。

**Comment by nibocn** [comment]
在 Mac 双屏幕截副屏幕时，屏幕自动缩放了把主屏的内容也显示，不够清晰
![image](https://user-images.githubusercontent.com/10879287/50807594-df2d6780-1335-11e9-9b3c-924ef4bd637c.png)

**Comment by nibocn** [comment]
> 在 Mac 双屏幕截副屏幕时，屏幕自动缩放了把主屏的内容也显示，不够清晰
> ![image](https://user-images.githubusercontent.com/10879287/50807594-df2d6780-1335-11e9-9b3c-924ef4bd637c.png)

补充下新的情况：
我的副屏显示器是一个 4K 显示器，我最开始把主屏设置为默认的 Mac 笔记本显示器时在副屏（也就是 4K 显示器）上启动截图确实会出现上面说的缩放问题。后面我把主屏的设置调整了下改为 4K 显示器作为主屏 Mac 笔记本作为副屏，然后再启动截图不管是在哪个屏幕显示就都正常了，目前我暂时就只能通过这种设置的方式来适应。

**Comment by WangLeto** [comment]
我也来补充一个场景：macBook pro 2018 15.6 版本（作为副屏幕），使用戴尔 1080p 外接屏幕（作为主屏）。在 macBook pro 上截图时变得特别不清晰，Snipaste 版本为 2.2.0-beta2，升级之前没有这个现象。暂时只能把窗口拖到外接屏幕上截图。作者大大加油呀！snipaste 用了3年多了，从学生时代的 windows 版本用到现在工作的 mac，这个软件太棒了。

**Comment by rickyzhangca** [comment]
> 我也来补充一个场景：macBook pro 2018 15.6 版本（作为副屏幕），使用戴尔 1080p 外接屏幕（作为主屏）。在 macBook pro 上截图时变得特别不清晰，Snipaste 版本为 2.2.0-beta2，升级之前没有这个现象。暂时只能把窗口拖到外接屏幕上截图。作者大大加油呀！snipaste 用了3年多了，从学生时代的 windows 版本用到现在工作的 mac，这个软件太棒了。

相同问题：MBP15 2017 + DELL U2417H，截屏模糊

**Comment by WangLeto** [comment]
> 我也来补充一个场景：macBook pro 2018 15.6 版本（作为副屏幕），使用戴尔 1080p 外接屏幕（作为主屏）。在 macBook pro 上截图时变得特别不清晰，Snipaste 版本为 2.2.0-beta2，升级之前没有这个现象。暂时只能把窗口拖到外接屏幕上截图。作者大大加油呀！snipaste 用了3年多了，从学生时代的 windows 版本用到现在工作的 mac，这个软件太棒了。

emmm... Mac 版本升级到 10.14.6 以后没问题了，但是不清楚是不是因为重启就好了

**Comment by jetma** [comment]
> 重新试了一下，的确是鼠标在哪个屏幕就截那个屏。
> 我觉得有必要再优化一下，鼠标在A屏幕开始按F1，把鼠标移到B屏幕也应该能截图。微信的截图功能就是这么做的。

+1

**Comment by frankcbliu** [comment]
> > 重新试了一下，的确是鼠标在哪个屏幕就截那个屏。
> > 我觉得有必要再优化一下，鼠标在A屏幕开始按F1，把鼠标移到B屏幕也应该能截图。微信的截图功能就是这么做的。
> 
> +1

+1

**Comment by liulex** [comment]
> 鼠标在A屏幕开始按F1，把鼠标移到B屏幕也应该能截图

即将发布的 2.8 可以这样操作了。

**Comment by lllzpll** [comment]
macbook air 13英寸 M3
macOS: 14.6.1 (23G93)
snipaste: 2.9.2-Beta(2024.07.02) macOS版

问题：分别使用两个C口分别输出一个2k的显示器，无法跨屏截图
![image](https://github.com/user-attachments/assets/e817e272-fde3-466f-8d13-42daceced24e)
