### ISSUE TITLE
[RESOLVED]Couldn't download 1.16.2 Beta Mac Version

### ISSUE THREAD

**Issue by that1egacy** [Snipaste/feedback#1028]
Hi
I download the Mac Version 1.16.2 Beta via the link from ur site but every time I unarchive the file it end up with error warning.
I've tried more than 3 times still couldn't make it right.
Could u please check the link for the Mac version or could u tell me how to download the file via a mirror site.
Thanks!

**Comment by StarryVoid** [comment]
My English is not good, I used google translation.
The default Snipaste official website download link is forbidden to use directly, you must click the download button through the official website.
If you need a download point, you can temporarily download Snipaste from my website.
[Downloads](https://downloads.starryvoid.com/software/3.Extended%20Systems%20Software/snipaste/Snipaste-Mac-1.16.2-Beta.tar.gz)

**Comment by that1egacy** [comment]
Thanks for the information, I download the file again and Unarchive it without error using MacOS Archive Utility.app. 
I think BetterZip might cause the errors when I used it in the last few attempts.
