### ISSUE TITLE
快捷键呼出反应慢

### ISSUE THREAD

**Issue by foxbaby213** [Snipaste/feedback#1030]
软件版本：1.16.2(2018.01.22)64位
---------------------------------------
操作系统：Win7 专业版sp1
处理器：intel i3-7100 3.90GHz
内存：4.00GB(3.87GB可用)
系统类型：64位操作系统
---------------------------------------
问题：
电脑内存总数3959，常年空闲低于10，每隔一段时间不使用snipaste后使用快捷键呼出会有20s左右的延迟，贴图拖动会有30s左右卡住并变成白色，鼠标变沙漏；短时间内连续使用不会有此问题。
---
邮件：nb77543@gmail.com

**Comment by liulex** [comment]
该问题在 2.x 版本已经解决，目前只有微软商店版，Win 7 请等待桌面版更新~
