### ISSUE TITLE
自动识别边框功能，能否增加手动扩大或者缩小范围

### ISSUE THREAD

**Issue by jsjcjsjc** [Snipaste/feedback#1034]
比如现在Snipaste只能截取下图的样子  
![1](http://share.getpocket.net/image/1.jpg)  
但是我不想要书签和地址栏，貌似不行啊，测试了picpick和FSCapture貌似都可以  
IE和chrome都是一样的情况，即使增加了--force-renderer-accessibility命令  
![2](http://share.getpocket.net/image/2.jpg)

**Comment by liulex** [comment]
部分操作系统环境存在无法选取部分窗口界面元素的问题，我自己也遇到过，没找出原因……
