### ISSUE TITLE
[Feature] "贴图" - "标注" - "文本" ，下一次启动贴图时，引用上次样式

### ISSUE THREAD

**Issue by xianghongai** [Snipaste/feedback#1036]
"贴图" - "标注" - "文本" ，设定文本字体、颜色样式，

下一次启动贴图时，又回到默认样式，

记住上一次设定？

![](https://i.loli.net/2018/11/29/5bff5aa0517eb.gif)

**Comment by jerrywang95** [comment]
@xianghongai 截图时先标注，再贴图，试试？似乎截图的是能存的，贴图的不可以

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/420#issuecomment-294103121
