### ISSUE TITLE
[Feature]-激活机制

### ISSUE THREAD

**Issue by xianghongai** [Snipaste/feedback#1044]
限定 “激活设备数”，

一般用户使用场景：

1. 在家两台(一台式一笔记本)，
2. 在公司(可能会跳槽)一台计算机，
3. Windows 系统不用微软账号登录，不走微软商店版，

用户对于激活的管理：
1. 取消绑定其它占用激活/被窃取激活的计算机，

像 Photoshop 插件 Parker ，采用类似机制，我购买后，只需要我记住激活时的账号，可以保持在一定数量常用计算机上的使用。

**Comment by septs** [comment]
请合并至 #1044 讨论
