### ISSUE TITLE
【Feature request】建议在贴图上右键菜单中加入复制路径功能。

### ISSUE THREAD

**Issue by cooper1x** [Snipaste/feedback#1046]
请求新功能
建议在贴图上右键菜单中加入复制路径功能。

因为现在很多论坛都需要上传截图，而截图每次都只是临时的。通常我的操作是要保存到本地一个路径，然后上传。如果加入这个功能，我在选择文件的时候会非常快捷，这样上传图片也会快很多。

**Comment by septs** [comment]
Duplicate of #60
