### ISSUE TITLE
[Feature Request]文件命名规则中不将“/”（斜杠）视为非法字符而是视为文件夹的分隔符。

### ISSUE THREAD

**Issue by GainSky** [Snipaste/feedback#1047]
能否将文件命名规则中的“/”视为文件夹分隔符，这样在进行“$yyyy-MM-dd$/Snipaste_$HH-mm-ss$.png”这样子的命名规则的时候会自动进行文件夹按日期存放，也可以使用其他参数来按其他参数自动创建文件夹存放。

**Comment by Liam0205** [comment]
听起来很有趣~

不过总感觉这样做会有安全风险。能想到几个常用软件有这个特性的例子吗？
