### ISSUE TITLE
windows休眠唤醒后，按Snipaste快捷键反应迟缓甚至无效

### ISSUE THREAD

**Issue by RattanRockingChair** [Snipaste/feedback#1048]
**[Bug Report]**
在Snipaste开启的情况下休眠windows，再次唤醒系统时按快捷键使用Snipaste时出现反应迟缓，或快捷键无效情况，甚至还会出现右击通知区域中Snipaste图标也无法弹出菜单。

P.S. 本机未装任何 XX卫士，仅有企业版麦咖啡和赛门铁克。

**Comment by stevenzhu25** [comment]
@RattanRockingChair 请您看一下Snipaste是不是被Windows自动休眠了....

**Comment by RattanRockingChair** [comment]
> @RattanRockingChair 请您看一下Snipaste是不是被Windows自动休眠了....

下次唤醒后我留一下

**Comment by git10135405** [comment]
我也遇到了这个问题

**Comment by liulex** [comment]
dup of #498
