### ISSUE TITLE
snipaste  1.16.2截圖時崩潰

### ISSUE THREAD

**Issue by cits2** [Snipaste/feedback#1049]
我是用windows版本是win 7 pro x64
不論使用snipaste(x86) 還是 snipaste(x64) 只要用截圖功能時 snipaste便會崩潰

**Comment by liulex** [comment]
可以关掉 "自动检测界面元素" 功能再试试？

**Comment by StarryVoid** [comment]
没有回复的话这个Issues可以关闭了。

**Comment by hoohyaIII** [comment]
我的也存在这个问题，有好几次了

**Comment by StarryVoid** [comment]
推荐使用新版本 V2.2 如果仍然出现问题，可以重新上报。
