### ISSUE TITLE
Can't match icon color with Mojave switch theme on MacOS mojave

### ISSUE THREAD

**Issue by Tairraos** [Snipaste/feedback#1050]
Bug report?
* run snipaste and switch dark/light theme under system preference, pay attention to icon on top bar
See: the icon color is still showing black/white after it launching, change theme but icon color is fixed.
Expect: show black icon in light theme and show white in dark theme. 

---

发现了 bug？
* 运行snipatse，在设计里切换Dark/Light theme，观察顶端bar上的图标
目前状况：启动的时候是什么颜色就固定为这种颜色，图标颜色不会随着主题变化而变化。
期望结果：浅色主题显示黑色图标，深色主题显示白色图标。（其它的app都已经适配）

**Comment by Tairraos** [comment]
start snipaste in light mode:
![image](https://user-images.githubusercontent.com/185069/50203265-e0551f80-039b-11e9-91ef-df060235660f.png)
![image](https://user-images.githubusercontent.com/185069/50203290-f4008600-039b-11e9-8d6a-2fddd8e1c6f3.png)

start snipaste in dark mode:
![image](https://user-images.githubusercontent.com/185069/50203346-24482480-039c-11e9-8306-587f49d436c2.png)
![image](https://user-images.githubusercontent.com/185069/50203368-34600400-039c-11e9-9eb6-7d03022ed8eb.png)

**Comment by izhengchengjin** [comment]
+1，不过你在切换主题后点击一下他的图标颜色就会变正常。

**Comment by essethon** [comment]
+1, 
我使用 f.lux 在每天日落后自动切换为 dark mode，
menubar 中其他 App 的图标基本都可以立即自动适配 dark mode，但 Snipaste 需要手动点一下，图标颜色才会变过来

**Comment by xsyww** [comment]
+1，
我也是，它的图标不会随着系统主题色的改变而改变。
