### ISSUE TITLE
[Feature]希望增加对Windows 10 19H1浅色模式图标的支持

### ISSUE THREAD

**Issue by wubingchen** [Snipaste/feedback#1052]
应用Windows 10 19H1的“浅色主题”后，系统程序的任务栏图标都会由白色变为黑色以提高辨识度，但Snipaste的浅色图标在该主题下仍为白色，辨识度很低。希望增加图标切换选项，让用户可以选择使用深色图标还是浅色图标。

**Comment by Genteure** [comment]
![image](https://user-images.githubusercontent.com/11240579/50349975-7cd41900-0578-11e9-8055-b985bf64094a.png)

**Comment by wubingchen** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/11240579/50349975-7cd41900-0578-11e9-8055-b985bf64094a.png)

非常感谢！

**Comment by liulex** [comment]
2.2 版会支持托盘图标自动适配浅色/深色任务栏。
