### ISSUE TITLE
擷圖之後，圖片顏色不同

### ISSUE THREAD

**Issue by evanwu-tw** [Snipaste/feedback#1053]
发现了 bug？
* 请描述一下重现的步骤，越详细越好
使用 sinpaste 擷的圖片顏色會跟原始檔案不同。

mac 擷圖
![mac](https://user-images.githubusercontent.com/3216125/50391208-26cfc300-077c-11e9-85fc-bb5a1c6c56f7.png)

snipaste 擷圖
![snipaste](https://user-images.githubusercontent.com/3216125/50391207-26cfc300-077c-11e9-8e68-94a89dae1e69.png)

**Comment by evanwu-tw** [comment]
忘記寫系統，系統是 macOS Mojave 10.14.2

**Comment by evanwu-tw** [comment]
背景的藍色不同，上面 mac 是 #4067D9，下面 sinpaste 是 #4869D2，黃色部分也有些微不同，上面 mac s是 #FEF852，下面 sinpaste 是 #FDF770。

**Comment by liulex** [comment]
dup of #971，已在 2.2 版修复。
