### ISSUE TITLE
建议增加鼠标指针位置显示功能

### ISSUE THREAD

**Issue by sinfee** [Snipaste/feedback#1061]
感谢开发这么优秀的软件，我买了PRO的微软帐号版本。

建议增加像SNAPIT的鼠标指针快速显示定位的功能，通过按某个快捷键，以动画的效果快速把鼠标位置显示出来。
现在经常出来由于高分屏、多屏幕等及其他原因，想截图时一时找不到鼠标在哪里了，这时按某快捷键，以大圈不断变小定位显示鼠标位置，会非常方便。

**Comment by liulex** [comment]
谢谢支持！系统自带这个功能哦：
![default](https://user-images.githubusercontent.com/2010459/50749468-f575ed80-1279-11e9-8918-3d3fd4c28ee8.png)
