### ISSUE TITLE
截图后总是停止响应

### ISSUE THREAD

**Issue by yanxiaodi** [Snipaste/feedback#1062]
发现了 bug？
* 最近截图总是出现停止响应的情况，快捷键后屏幕上只有一个高亮的框，但无法截图，屏幕所有位置都无法点击，也无法ESC退出，但系统并未卡死，鼠标可以动，也可以按Ctrl+Alt+Del，但选任务管理器后无法将任务管理器显示在前台，因此也无法关闭截图进程。没办法只能重启电脑，非常不便。希望能协助修复一下，谢谢。

系统为
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.17134 N/A Build 17134

**Comment by liulex** [comment]
请将日志等级调到`跟踪`，等下次再出现问题后，把日志文件`splog.txt` 发送到 <snipaste.app@gmail.com>.
![default](https://user-images.githubusercontent.com/2010459/50775740-f8043180-12d1-11e9-97f6-94776927185b.png)

在任务管理器里面设置`置于顶层`，可以使其显示在前台。
![default](https://user-images.githubusercontent.com/2010459/50775730-f175ba00-12d1-11e9-8773-5852807da9bf.png)

此外，先点击右边的  <kbd>Win</kbd> 按键，然后点击 Snipaste 的托盘图标，也可以退出 Snipaste.

**Comment by yanxiaodi** [comment]
好的，谢谢，我再观察一下。

**Comment by platinhom** [comment]
Win10, 同样遇到这个问题, 右Win点击Snipaste右下托盘图标仍然无法退出, 无法弹出菜单. 只能重启.
