### ISSUE TITLE
贴图功能进阶建议

### ISSUE THREAD

**Issue by chad-it** [Snipaste/feedback#1063]
首先，贴图是个很棒的功能。

如果可以，希望：
macOS版的贴图可以在所有桌面上显示
（即，贴图后三指触摸板切换桌面，贴图始终显示）
（可参考已有此效果的软件，iina，macOS好用的播放器的画中画功能）
![image](https://user-images.githubusercontent.com/15319340/50818257-6d6b1300-1361-11e9-8071-cf6340dabdac.png)
iina github地址：https://github.com/iina/iina

**Comment by liulex** [comment]
多桌面支持以后会加上的~

**Comment by liulex** [comment]
2.2 Beta 已经支持，专业版会支持对单个贴图设置全桌面/当前桌面显示。
