### ISSUE TITLE
支援 APNG 格式動態圖片貼圖

### ISSUE THREAD

**Issue by brownsugar** [Snipaste/feedback#1064]
目前貼圖僅支援 GIF，不支援 APNG，APNG 是逐漸被廣用的動態圖片格式，LINE 動態貼圖也是使用這種格式，Chrome 也已經於版本 59 起支援。
下面這張就是一張 APNG 圖片（副檔名是 PNG，播放次數 2 次）：
![30506471](https://user-images.githubusercontent.com/2935980/50854666-a090bf00-13c0-11e9-865e-343182ae0178.png)
開源的解析器：[APNG Disassembler](https://sourceforge.net/projects/apngdis/)

* * *

另外這種有設置循環次數的動態圖片，貼圖後動態次數跑完，ESC 掉，再重新貼圖不會重新出現動態效果，
必須先貼另一個 GIF，再回來貼原來的圖才能重新播放，不知道這是屬於特色還是 BUG？
![gif9-min](https://user-images.githubusercontent.com/2935980/50855764-b8b60d80-13c3-11e9-990f-0f3c6d4e51fe.gif)

**Comment by liulex** [comment]
“ESC 掉” 只是隐藏了贴图，所以再次贴出来还是原来的贴图、原来的状态。可以按 <kbd>Shift</kbd> + <kbd>Esc</kbd> 将贴图销毁，然后再贴出来就是新的了。

不过我的确没考虑过限定了循环次数的 GIF，下次更新我加上支持吧，播放结束后按空格键可令其重新播放。

APNG 的支持也会在年内加上~

**Comment by liulex** [comment]
已实现，请等待下个版本更新。
