### ISSUE TITLE
进行截图动作极其容易导致IDEA奔溃

### ISSUE THREAD

**Issue by darknesstm** [Snipaste/feedback#1067]
换成picpick不会出现，但是Snipaste每次截图有30%概率导致 JetBrains的 IDEA奔溃，IDEA版本在2018.3 

截图工程中对有UI的进程有什么特殊处理么

**Comment by liulex** [comment]
会查询窗口的界面元素，对方窗口实现不当会导致自身崩掉或 Snipaste 卡住，应该是检查到特定窗口的时候崩了。

请参考  [高级设置](https://github.com/liulex/Snipaste-Feedback/wiki/%E9%AB%98%E7%BA%A7%E8%AE%BE%E7%BD%AE)，添加 `crashes=xxx.exe`.

**Comment by darknesstm** [comment]
加了 crashes 和 exclude_from_detection 还是容易奔溃

而且是再按下的时候奔溃，全屏的快照中窗口还在，实际已经奔溃退出

**Comment by darknesstm** [comment]
exe没填写错的，关闭元素 关闭窗口 检测后，还是奔溃……
```
Stack: [0x000000001b0c0000,0x000000001b1c0000],  sp=0x000000001b1bf080,  free space=1020k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [jvm.dll+0x129e6d]
C  [awt.dll+0x6a398]
C  [awt.dll+0x8a73f]
C  [awt.dll+0xcec8c]
C  [USER32.dll+0x16d41]
C  [USER32.dll+0x16713]
C  [awt.dll+0xce58c]
C  [awt.dll+0xce82b]
C  0x00000000028489a7

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  sun.awt.windows.WToolkit.eventLoop()V+0
j  sun.awt.windows.WToolkit.run()V+58
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub
```

IDEA是JRE奔溃，地址如上，可能没啥用……

**Comment by septs** [comment]
无有效证明是由 Snipaste 引起 Jetbrains 系列、Java Swing、Java AWT  程序崩溃的原因，因此该 issue 无效。

请提供该问题的稳定复现条件用于修正该可能性缺陷。
