### ISSUE TITLE
标注透明度希望改成百分比滑块的形式

### ISSUE THREAD

**Issue by Dong-JM** [Snipaste/feedback#1069]
![image](https://user-images.githubusercontent.com/28295242/51239291-f57d9800-19b3-11e9-8137-9524d708d97e.png)
希望能用这种
![image](https://user-images.githubusercontent.com/28295242/51239333-134afd00-19b4-11e9-974e-526086098d0c.png)

**Comment by Dong-JM** [comment]
另外线和面的颜色值可以分开记录么，包括透明度

**Comment by StarryVoid** [comment]
暂时没有滑块透明度
鼠标在大颜色块上滚动滚轮可以调整透明度
[Pro]专业版可以将色板颜色自定义（颜色包含alpha）

**Comment by septs** [comment]
Duplicate of #1375
