### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by TroyDanielFZ** [Snipaste/feedback#1071]
在截图绘制标注时给不同的标注定义快捷键，譬如，箭头alt+a，矩形alt+r

**Comment by wf3699** [comment]
希望增加字体阴影功能，像ios 小Q画笔那样，备注的红色字体有白色阴影。
或者用别的方法，能容易区分出截图中后添加的备注。

**Comment by jonathanding** [comment]
顶一下 @TroyDanielFZ 。还可以和很多人喜欢的IrfanView一样，快捷键直接是A, R等。当然这样的话Text标注这里要做额外处理。

**Comment by liulex** [comment]
dup of #664
