### ISSUE TITLE
隐私？

### ISSUE THREAD

**Issue by erick0867** [Snipaste/feedback#1072]
请问这个软件会不会偷偷上传截图和截图？

**Comment by erick0867** [comment]
没有人要回答么？

**Comment by liulex** [comment]
https://zh.snipaste.com/

> Snipaste 是免费软件，它也很安全，没有广告、不会扫描你的硬盘、更不会上传用户数据，它只做它应该做的事。 

https://github.com/Snipaste/feedback/wiki/Privacy-Policy
