### ISSUE TITLE
[新功能请求]

### ISSUE THREAD

**Issue by Mintscandy** [Snipaste/feedback#1074]
希望增加一个在同一个局域网内的远程截屏
例如，通过手机发送一个截图命令，然后，进行截图后返回到手机上
有时候通过snipaste截图以后，发到QQ，什么还要在电脑上打开QQ什么的
直接在手机上操作可能会方便一点~

**Comment by stevenzhu25** [comment]
@Mintscandy 这个已经不是Snipaste的功能了吧.....

**Comment by septs** [comment]
这个已经超过 Snipaste 职能范围
如果您是 macOS 用户 macOS Sierra 已经支持在 iOS 与 macOS 共享剪贴板了。
如果您是 Windows 用户 Windows 1809 已经支持向其他设备发送文件。
