### ISSUE TITLE
調整選取範圍時，無法使用方向鍵移動鼠標位置

### ISSUE THREAD

**Issue by brownsugar** [Snipaste/feedback#1076]
截圖時，可以使用 ↑↓←→ 調整鼠標位置，進而微調選取範圍，
但滑鼠放開後再重新拉動選取範圍時，就無法使用方向鍵微調了。

版本：Windows 商店版 2.1.4

**Comment by StarryVoid** [comment]
首先我没有复现出这个问题，默认"松开鼠标按键后重新按下鼠标按键并拖拽选择框时，可以按WASD微调"
可以提供版本号，复现过程么？

**Comment by brownsugar** [comment]
@StarryVoid 二次調整時，WASD 可以微調，但 ↑↓←→ 不行，首次選取範圍時兩者都行，可以看下面的 GIF。
版本是 Windows 商店版的 2.1.4。
![demo-min](https://user-images.githubusercontent.com/2935980/52643647-6f079800-2f18-11e9-843e-c6f298481d94.gif)

**Comment by liulex** [comment]
@brownsugar ↑↓←→ 和 WASD 的分工是不一样的，WASD 用于移动光标，方向键用户整体移动区域。

[内置快捷键](https://docs.snipaste.com/zh-cn/key-bindings)：

| 按键 | 命令 |
| --- | --- |
| W S A D | 将鼠标指针移动 1 像素 |
|↑ ← ↓ → | 非编辑状态下, 将截屏区域/贴图窗口移动 1 像素 |


只有当方向键在某些状态下，没有任何功能时，也会响应光标移动，比如你上面提到的情况。

不过，你可以添加[选项](https://docs.snipaste.com/advanced-configs?id=hotkey2) `exchange_wasd_and_arrow_keys=true` 调换 ↑↓←→ 和 WASD 的功能。
