### ISSUE TITLE
建议截屏 png 格式改为 RGB24

### ISSUE THREAD

**Issue by Sh1noka** [Snipaste/feedback#1077]
截屏不会截出透明的，alpha 通道应该不需要吧。

RGBA32 格式的 PNG 大小会比 RGB24 大吗？如果会的话建议改成 RGB24

**Comment by StarryVoid** [comment]
截屏会出透明，双屏幕时将屏幕排列为左上角和右下角，非屏幕区域就是透明

**Comment by Sh1noka** [comment]
还有这种情况，学习了。那还是就保留当前这样比较好呢。

**Comment by liulex** [comment]
下个版本会加个自动检测，图像不带半透明像素则保存时移除透明通道。
