### ISSUE TITLE
和护眼应用F.lux有冲突，截图时整个屏幕会变成深红

### ISSUE THREAD

**Issue by Dakai** [Snipaste/feedback#1078]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好
在Windows 10版本1809里，使用软件F.lux v4.96(https://justgetflux.com/)的情况下，截图时屏幕会变成深红色 ，将F.lux软件功能关闭时截图功能正常。如图：
![](https://raw.githubusercontent.com/Dakai/testing/master/20190213201111.png)

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by liulex** [comment]
我装了下最新版 f.lux 4.84，没有复现。
即使有问题，也应该是 f.lux 的问题，你用其他截图工具也是一样的。
建议用 Win 10 自带的夜间模式。

**Comment by scplay** [comment]
我也经常遇到这个问题，有时又没问题，不知道怎么触发的
