### ISSUE TITLE
[FEATURE] 支援输出缩放

### ISSUE THREAD

**Issue by KayLeung** [Snipaste/feedback#1080]
建议输出设定增加输出缩放百分比

现在使用 4K 显示，WINDOWS 175% 缩放，大多数情况下，我想截图跟肉眼看到一样。有时候，我想不少人会想输出非高分屏较果给别人，所以增加百分比设定比自适应支援更弹性。

**Comment by liulex** [comment]
可以在贴图上进行缩放然后复制或保存，得到的图像是缩放后的。

**Comment by KayLeung** [comment]
@liulex 每次缩放 58% 难度太高，几乎没有可能做到

**Comment by liulex** [comment]
有自定义缩放啊……
![default](https://user-images.githubusercontent.com/2010459/52897217-e2592480-320c-11e9-91eb-d91ee9062ee8.png)
![default](https://user-images.githubusercontent.com/2010459/52897230-03ba1080-320d-11e9-90f8-5572fa70a9ac.png)

我也可以在下个版本加入一项根据当前屏幕缩放程度还原到 100% 的缩放等级。

**Comment by KayLeung** [comment]
@liulex PRO 版特有吗? 我是最新 2.14 (2018.12.03)

**Comment by StarryVoid** [comment]
右键贴图，缩放，自定义。

**Comment by KayLeung** [comment]
![c20190216_172227](https://user-images.githubusercontent.com/32264/52897453-9e1b5380-320f-11e9-95dd-f393995d6d2e.png)

@liulex 我试下 v1 也没有

**Comment by liulex** [comment]
看了下代码，确实是 PRO 功能…… 😅

**Comment by liulex** [comment]
> 我也可以在下个版本加入一项根据当前屏幕缩放程度还原到 100% 的缩放等级。

这个我加到免费版吧。
