### ISSUE TITLE
Mac 截图后，图片饱和度明显降低

### ISSUE THREAD

**Issue by JonyDT** [Snipaste/feedback#1082]
截图后，图片的饱和度明显下降，如下和企业微信截图的对比
版本：1.16.2 Beta
系统：iMac，macOS Mojave 10.14.2
<img width="2088" alt="wx20190218-101220 2x" src="https://user-images.githubusercontent.com/47728946/52924030-bbfacc80-3365-11e9-8014-c9d8a3b03ce3.png">

贾晓杰

**Comment by liulex** [comment]
dup of #971，已在 2.2 版修复。
