### ISSUE TITLE
软件可以正常设置开机启动，但实际效果未开机启动

### ISSUE THREAD

**Issue by enswing** [Snipaste/feedback#1083]
软件可以正常设置开机启动，但实际效果未开机启动
![image](https://user-images.githubusercontent.com/25969536/52985786-4445a400-3430-11e9-93a9-431860e72064.png)
![image](https://user-images.githubusercontent.com/25969536/52985793-490a5800-3430-11e9-91dd-3996b46e8b2d.png)
不清楚原因
就是开机很久后，点击F1没用，sinpaste也没有运行，一定要自行打开软件才可以正常操作

**Comment by liulex** [comment]
[开机启动失效](https://docs.snipaste.com/zh-cn/troubleshooting?id=%E5%BC%80%E6%9C%BA%E5%90%AF%E5%8A%A8%E5%A4%B1%E6%95%88)
