### ISSUE TITLE
超级截屏增加一个单纯进入截屏界面的选项

### ISSUE THREAD

**Issue by jonathanding** [Snipaste/feedback#1085]
现在超级截屏以后只能贴图或者自动复制后退出。但我更加希望的方式是超级截屏后进入传统的截屏界面（标注工具条也显示），这样我有机会做各种调整，例如大小，标注等。
之后我希望贴图或者复制的话，可以自己Ctrl+T或者左键双击复制退出等。也只是比现在的方式多了一次快捷键操作。还可以Ctrl+S或者Ctrl+Shift+S选择保存，总之非常灵活，截屏后的各种决策由自己做，而非只有强制二选一的贴图和复制。
没有这个选项的话（只有贴图和自动复制），很多时候想再做调整的时候麻烦不少，有时甚至索性使用F3再来一遍。
强烈建议多加这个选项

**Comment by septs** [comment]
这个已经改变超级截图的初衷和功能性质。

如果您还有一些对于截图的修改，
建议您暂停使用超级截图功能。

**Comment by jonathanding** [comment]
> 这个已经改变超级截图的初衷和功能性质。
不是很明白为什么改变了超级截图的初衷和功能性质。既然叫超级”截屏”，那完成后就停留在“截”好了屏的“截屏”界面不是很自然吗？为什么一定要自动追加后续动作呢？
另外，它并不要求去掉已有的自动贴图和复制选项，只是希望增加一个选项。谈不上上纲上线的“改变”，我不觉得从功能角度会对已有会未来用户有任何干扰或困扰。
是因为还是说当前的代码实现里面添加这个会比较麻烦？会导致比较大的代码改动？
> 如果您还有一些对于截图的修改，
> 建议您暂停使用超级截图功能。
问题在于：1) 后续动作不仅仅限于修改，还包括保存等 2) 再截屏的那一瞬间，很可能也每想好后续动作是什么。很多时候是截好了发现大小不合适，要做一些小的调整；或者发现需要一些信息不太明确，需要追加一些标注等等。特别是平常已经习惯了Windows + Mouse来截屏（Windows比F3方便很多），更加希望以这个方式进入截屏。
Again，如果是由于实现难度或工作量的话，我可以理解。但是从用户使用的角度，我不觉得这是一个伪需求，刚刚搜了一下，#943也早就指出了这个

**Comment by StarryVoid** [comment]
可以直接使用自定义截图
超级截屏就是为了最快的速度抓一个东西并显示出来（无论给别人还是给自己），而不是去上面改改。

你想有修改为什么不走正常截图操作？

**Comment by jonathanding** [comment]
1) 如前所述：很多时候截图的时候并没有想好要修改，截好了（给了自己或别人）以后才发现有不满意的地方，需要调整大小或标注。我已经多次碰到先Windows + Mouse后，又反悔了只好去F3
2) 既然如此，为什么我不索性就总是F3，而是一定要Windows + Mouse来截屏。主要原因就是因为Windows + Mouse是一个便捷和自然很多的方式（不止我一个人的想法）。不怎么需要思考，同时左手不需要离开主键盘区去够F3。如果有可能的话，我甚至愿意把正常截屏快捷键设成Windows + Mouse，而超级截屏设成F3
3) 这是一个功能的增加，多了一个选择而已，并不改变现有的功能，我也不觉得多了这个选项会给用户带来困扰。所以如果实现代价不大的话，我还是觉得值得拥有

**Comment by jonathanding** [comment]
补充一下，F3本身是一个很重要的键，例如在大多数编辑器和IDE里，它与Find (例如Find Next）等常用操作密切相关，所以在我这里实际上是重新分配了其他键以避免冲突。我这里用的是PrintScreen键，沿袭了GreenShot的习惯。
从这个角度讲，Windows + Mouse作为更加方便自然的截屏入口点（例如我这里希望的通过超级截屏进入）是一个非常有吸引力的选项，且不会占用其他功能键例如F3
不打扰的话，也想听听作者 @liulex 的想法

**Comment by GregAMO** [comment]
@jonathanding GregAMO Lestrade:
喜欢鼠标触发的可以左转 WGestures 之类的「鼠标手势」软件进行绑定。
Snipaste 在文档内给出命令行的，直接绑；
没命令行的，在 Snipaste 里面指定一个偏僻的快捷键作为桥梁。

**Comment by jonathanding** [comment]
@GregAMO 体验是差很多的。对于这个动作：先按住Windows键，然后按住鼠标左键。

* 超级截屏的话：我们是先把鼠标移到截屏想要的起始位置后才按左键的，按键立刻触发截屏操作，当前所在位置已经作为截屏矩形的一个角，放大镜开始显示（如果配置了的话），后面的鼠标移动（左键一直没有松）也是在定义截屏区域并且显示为截屏矩形

* 鼠标手势的话，这个时候还没有进入截屏，还要先鼠标滑动一个手势出来，才启动snipaste截屏。而这个手势操作导致鼠标的位置并不是在自己想要的截屏起始位置，需要再次移位过去。和按快捷键一样不自然。

其实，问题的关键并不是除了Windows + Mouse外我们就没有别的方式启动截屏，而是没有一个和它等价的如此直接自然不要过大脑的方法。如果没有这个，日子是照过的。但是有了它之后，截屏体验会爽很多。因为平常鼠标左键拖拽动作就是拉矩形用的，现在拉的时候按住Windows键就变成截图拉矩形，Windows键在这里就像CTRL, SHIFT, ALT一样，使用方式多么自然，根本就不要去想什么启动的事情。

现在感觉（对我个人而言）是，这是snipaste里最自然和符合思维方式的一个操作方式。这么有价值的一个入口，不应该只可以绑定给贴图或拷贝二选一。它们当然也是高频操作，但单纯截屏也是啊（而且截屏后贴图和拷贝也就一步的事）。。。

说到设计初衷，不也包括让用户觉得更加自然，体验更顺滑吗？我看到随着版本更新，添加了很多很好的配置选项让用户定制化，特别的，有触控角等新的入口绑定。那么Windows + Mouse这个最有价值的入口操作（个人不觉得要加“之一”），和截屏这个最高频的操作之一，却无法连接绑定。从用户体验角度我不是非常理解。除非实现角度有相当代价，不值得短期内提供。

**Comment by ulpyuxa** [comment]
顶你上去，既然是键盘加鼠标的截屏，比按快捷键的误操作会提升许多，但与按快捷键相比，现在的功能就比较鸡肋，

**Comment by jonathanding** [comment]
> 顶你上去，既然是键盘加鼠标的截屏，比按快捷键的误操作会提升许多，但与按快捷键相比，现在的功能就比较鸡肋，

多谢。只是这个issue刚开出来，在有进一步沟通交流之前就被直接Close了。。。所以不会有他人看到了，说不定过了这个周末就被忘了:(

其实截屏相对贴图，绝对是更加高频得多的操作，这也是为什么之前别的很多截图工具都没有发掘出贴图这个需求。所以相比贴图，截屏的体验怎么优化都不过分，如果贴图都有这样一个最有价值的入口的话，截屏也至少值得同样成为一个选项。这样的话，作为Pro版本宣传的第一个功能也才会无愧Super之名。看看官网是怎么说的？不需要Global Hotkey! 说明官网也意识到了Win + Mouse这个入口的价值。只是现在的功能和里面claim的"take screenshot"不完全一致。它的体验和按F1的“正宗截屏”不一样，截好屏幕就没了（进贴图或clipboard了）。。。


![image](https://user-images.githubusercontent.com/1069667/53245759-9c5aff80-36e9-11e9-9460-a1a14d150f6d.png)



下面是我自己最高频的使用场景以及**理想**（或官网claim的Intuitive）的使用方式，我相信很多需要和别人交流的程序员或办公室人员也是这样的，例如报bug，review设计稿，提需求等。比如贴上面的官网截屏进这个评论我就需要这么干。

* 工作中突然发现需要截个屏
* Super-snip: 鼠标移到起始点，按下Windows键，按下左键拖拽，初步完成截屏。非常自然不要动脑不会误操作。
* **假设有选项就停在截屏页面，而非贴图或拷贝退出** ，我可以立刻瞄一下效果，看截的大小是否需要调整，是否需要标注，是否有敏感信息需要马赛克，是否想把这个图保存下来。而不需要等后面用的时候再反悔
* 双击鼠标左键（这个设计的非常方便）从而拷贝退出，再paste到邮件或word或ppt等地方。如果是想贴图的话，Ctrl+T也不麻烦

为了省掉最后的一个鼠标双击或Ctrl+T，从而牺牲掉“瞄”的那一步所提供的确定性（可以检查和再思考一下）和灵活性（可以拥有截图界面所有的后续操作可能），至少对我个人而言意义很小（ @ulpyuxa 应该也是类似感觉）。进一步“求快”带来的边际收益很小。我更加需要的中间可编辑的便利性。而如果有用户和我们这个群体的想法不一样，他们也不受任何影响，仍然可以用现有的两个选项之一。

事实上，我觉得如果列举几个最常用的场景（例如上面说的这个），录个gif放在官网或推广网站上，告诉大家有了snipaste后这些场景变得多么Intuitive，自然和方便，可能比单纯的功能罗列更吸引人。个人之见

希望 @liulex  @septs  @GregAMO 能够考虑一下，而非简单一句话close就结束了。当然实在不赞同我也可以理解，有可能确实涉及较多代码实现或改动。

另：我之前说错了，默认截屏键是F1而不是F3。但和F3类似，F1这个是大家约定俗成的帮助系统的默认键，和F3一样，把它变成截屏的全局快捷键真的很伤。所以我改成了不怎么方便的PrintScreen

**Comment by liulex** [comment]
Hi, @jonathanding :

@septs @StarryVoid @GregAMO 他们说的没错，把超级截屏变成普通截屏确实违背我设计的初衷，谢谢你们帮忙回复。

超级截图的定位是**快速**截图，快速意味着不要求精准度，意味着用户很明确自己想要截图的区域，所以**鼠标松开之后就确定了截图区域**。我希望在这种情况下，用户就会想到用超级截图；在其他情况下需要细调截图的，就使用普通快捷键的方式，毕竟都要细调了，不差这一下按快捷键的功夫。

此外，快速截图只是限制了你不能再调整截图大小，并没有限制你进行标注。超级截图完成`截图并贴图`后，再按下**空格键**，就可以开始标注了，之后想要复制还是保存，也很方便。

不过，我也确实说过，只要不影响现有的功能，实现不太费力，我很愿意给用户加一些选项，**只要你能说清楚使用场景并且说服我**。所以，感谢你的用心、耐心的描述，说服我了，并且我实现了一下，体验也还行，你的需求我会在下个版本加上的。

**Comment by liulex** [comment]
最后还有一些话，不针对谁哈，但常常有一些人过来**提醒**我不该默认占用  F1, F2, F3，我没有回应过，这里统一做个回应，方便我以后直接抛个链接。

1. 这些按键是什么功能，我知道，不需要你们提醒我……
2. 它们的功能是很重要没错，但**我觉得**远没有截图和贴图重要。看帮助的频率，能和截图的频率比么？**我**贴图的频率，也是远远高于给文件重命名的频率。那请问为什么要把这么好的按键让给低频操作呢？要看帮助，从菜单点；要重命名，鼠标左键慢点两下；查找下一个，Ctrl+F 输入单词后不停按回车就好了。长期以来我并不觉得有任何不便。
3. 很多**普通用户**其实从来也不会按 F1 看帮助，按 F2 重命名，按 F3 查找下一个……那为什么不让他们知道这些闲置的按键可以用给截图用呢？
4. 当然，作为高级用户，你完全可以认为它们的原生功能更重要，但既然你连 F1, F2, F3 的功能都知道了，那在 Snipaste 的选项窗口里改掉默认快捷键应该不费事吧？
5. 那你觉得什么按键合适呢？是截不到菜单的 Ctrl+Alt+A，还是要松开右手鼠标去按、然后再拿回鼠标拖截图区域的 PrtScr？如你所愿换完默认按键之后，跟新老用户用两套按键进行交流的沟通成本你来承担吗？ :confused:

简单点说，日常依赖 F1, F2, F3 的人，有能力自己改设置；日常都不用那些按键的人，呃，那为什么不让他们用 F1 截图？

**Comment by jonathanding** [comment]
首先谢谢 @liulex 。万分期待下一个版本的发布以及早体验上这个功能。顺祝这个软件越来越好，周末愉快！:)

其次最后的题外话非常有见解，其实正好说明了为什么我会这么执着于这个功能的添加—即使在开始收到各种反对的情况下仍然耐心的打了这么多字。

你说的很对，当前方案对不依赖F1等功能键的人是没有影响的。对依赖功能键的人如我等，可以自己设置。可是正如你第5条所言，我有能力设置，可想了半天，找不到合适的键。
有需求去设置，有能力设置又愿意折腾这些设置的目标人群中，应该有很多是追求效率和顺滑体验的程序员（VIM用户为一个极端）。对他们而言，快捷键位是非常紧张的，特别是涉及到大量编程IDE。以我为例，F1关联到了调取Dash/Zeal中当前VSCode 中token的帮助，F2关联到了symbol的refactor，F3在不同context下涉及隔离查找，F4与navigation紧密关联(next location, next message等）。F5之后就和Debug与Build相关了。

所以想来想去，我只能定义到PrintScreen，甚至练成了左手PrintScreen的功夫。所以，可想而知突然发现有另外一个Windows + Mouse这么自然不占用global hotkey的方式，我当然希望能促成它的出现。而且这个功能是一个add而非modify，不会影响到主要的人群，可能只有我这类人比较关注吧。

最后，你提到的贴图加空格键的方案，之前我也当成workaround用过一阵子。我的主要使用方式都是截屏拷贝发送出去，所以超级截屏自动贴图后，我往往要多按一个Ctrl+C，然后Esc或Double Click（和截屏不一样，贴图下double click只退出不copy）。另外就是你提到的它不支持调整截屏大小和区域

**Comment by ulpyuxa** [comment]
感谢作者不厌其烦的回答，也期待新功能的加入，不忘初衷
