### ISSUE TITLE
焦点在 TIM 打开的图片窗口中时，截图框选范围错位

### ISSUE THREAD

**Issue by DemoJameson** [Snipaste/feedback#1087]
Snipaste 微软商店 2.1.4 版本
在 TIM 打开的图片中使用截图功能，框选范围会错位。
假如鼠标焦点不在图片上则无此问题。

演示，第一次焦点在图片上出 Bug 了，第二次焦点在其他地方则正常。
![ezgif-5-0e66ed2c17a4](https://user-images.githubusercontent.com/181192/53692112-33e4e000-3dc5-11e9-8590-e9f408aa33bc.gif)

**Comment by StarryVoid** [comment]
方便用其他的窗口扫描软件查看一下出问题时的句柄么？（复现失败）

**Comment by liulex** [comment]
看起来确实有 bug，但我也无法复现……
