### ISSUE TITLE
希望可以隐藏状态栏的托盘图标

### ISSUE THREAD

**Issue by shaonianruntu** [Snipaste/feedback#1089]
您好，我希望你们的Mac版本的软件可以增加对状态栏上的托盘图标的隐藏功能。状态栏的空间还是挺好贵的，而snipaste作为常驻后台的软件，且可以使用全局快捷键进行唤醒，没有必要一直在状态栏上显示，点击状态栏上该托盘图标的使用频率很少。
希望可以支持对其的隐藏选项。

![image](https://user-images.githubusercontent.com/16336682/53943422-074c0380-40f8-11e9-97e9-d4c18ebed341.png)

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/1002#issuecomment-428807816
