### ISSUE TITLE
怎么用命令行画一个固定大小的圆

### ISSUE THREAD

**Issue by CloserI** [Snipaste/feedback#1090]
嗨，我注意到这软件有个非常实用的命令行功能，我的工作需要截取400*400的图并在里面画上一个固定大小的圆，但我不知道怎么用命令行画一个固定大小的圆，方便告知我一下吗？衷心感谢！

**Comment by liulex** [comment]
没有这个功能……但专业版可以用 Ctrl+Shift+C 复制选中的标注，然后在贴图或者下一次截图进入标注模式后按 Ctrl+Shift+V 粘贴。
