### ISSUE TITLE
功能建议：设置截图个性化框架

### ISSUE THREAD

**Issue by butjia** [Snipaste/feedback#1092]
比如个人设置每张截图自动生成一个黑色边框。
习惯截图文字的人应该深有感触，如果边缘也是白色背景，不方便让截图和自己的备注分开。

**Comment by septs** [comment]
这个问题我认为不属于 Snipaste 的范畴。
图文混排情况的内容区分等处理属于编辑者的后期工作。
Snipaste 的设计目标是贴图与截图，因此该需求无效。
