### ISSUE TITLE
官网下载链接失效

### ISSUE THREAD

**Issue by moenn** [Snipaste/feedback#1093]
点击官网的 windows 版下载链接后，弹出下面的提示框，然后下载失败。
![image](https://user-images.githubusercontent.com/17309322/54082939-03b6b780-4358-11e9-984d-af3756eaa871.png)

![image](https://user-images.githubusercontent.com/17309322/54082932-e255cb80-4357-11e9-80e3-54ca601022fd.png)

**Comment by KazamaSion** [comment]
已重新在后台刷新资源链接。
如果还是遇到下载问题，能否提供一下您的 IP 所在地区（具体到省级）和运营商？

**Comment by moenn** [comment]
所在地理位置：浙江省电信
新资源链接
```
https://assets.sayori-static.com/snipaste-dl/archives/Snipaste-1.16.2-x64.zip
```
Firefox 报错
![image](https://user-images.githubusercontent.com/17309322/54084953-e511ea00-4372-11e9-8347-833fe3e53e0e.png)

**Comment by moenn** [comment]
`https://www.snipaste.com/` 的下载链接可以用。`https://zh.snipaste.com/download.html` 还是不行。
用同一个局域网的其他电脑测试过了。

**Comment by moenn** [comment]
都可以了，谢谢！
