### ISSUE TITLE
经常推送消息，内容大概是，看到红点了吗，点击会得到有用的提示

### ISSUE THREAD

**Issue by menghuiliux** [Snipaste/feedback#1094]
然后点该推送消息无任何交互
打开托盘，程序图标上也没有红点
总之就是经常打扰用户却根本没有什么有用的tips

Win 10用Microsoft store安装的

**Comment by septs** [comment]
Snipaste 作为工具不应当打搅用户使用
请认真思考这个问题

**Comment by dddd-zdf** [comment]
i second this. its extremely annoying
