### ISSUE TITLE
发现一个缺陷——复制某些文字的时候会变成透明底，难以操作

### ISSUE THREAD

**Issue by Fxiao1** [Snipaste/feedback#1095]
发现了 bug？
* 请描述一下重现的步骤，越详细越好
在复制某些文字的时候会出现仅仅文字可以点击，而文字背景透明无法点击的情况，此时如果想拖动文字的话，除非鼠标精确的放在文字上面，否则无法移动。这点不是很方便。
这个在有些地方会出现。我举一个刚刚发现的地址：[workflowy](https://www.workflowy.com/)的页面中，编辑笔记后，导出的时候选中Formatted，此时复制的文字就是透明底的。
![10](https://user-images.githubusercontent.com/40653617/54404413-4d175600-470e-11e9-8502-5e15a8e3affe.png)

**Comment by Fxiao1** [comment]
我的联系方式是：fx309@qq.com

**Comment by StarryVoid** [comment]
透明等同于鼠标穿透。
你可以修改贴图显示方式，默认背景模式改成其他模式
或者在对应的贴图上右键，背景模式，伪透明（Pro）

**Comment by Fxiao1** [comment]
你好，为什么我的这个界面没有“伪透明”的选项呢？我拥有的是win10uwd版的snipaste。这是高级版独有的功能吗？
![11](https://user-images.githubusercontent.com/40653617/54484986-0b241680-48ac-11e9-8e28-147456d92924.png)

**Comment by stevenzhu25** [comment]
@Fxiao1 您想得没错… 
详见：
https://docs.snipaste.com/zh-cn/pro
