### ISSUE TITLE
画笔工具顺/逆时针快速旋转后线会变得不圆润

### ISSUE THREAD

**Issue by vonhezhou** [Snipaste/feedback#1097]
Windows 10下，版本2.1.4(2018.12.03)

1. 随便截图
2. 使用画笔工具
3. 顺时针快速旋转画圆（是不是正圆无所谓）。可以看到时间越长，线就变得越棱角分明

之前我也碰到类似的问题，建议看一下这2篇：
How do I get mouse messages faster than WM_MOUSEMOVE? (Raymond Chen)
Why do I get spurious WM_MOUSEMOVE messages? (Raymond Chen)
简单说就是，在Windows下（Mac下也会，只不过是别的机制），多个鼠标物理移动的事件只会有一个WM_MOUSEMOVE窗口消息，需要手动调用Get­Mouse­Move­Points­Ex()获取没有来得及处理的鼠标坐标。Qt这边不确定有没有暴露足够的数据来让你调用,很久没有关注Qt了

**Comment by StarryVoid** [comment]
做了一下简单测试，，不圆润前提是鼠标移动速度过快。
鼠标消息不懂，等作者看吧

**Comment by liulex** [comment]
@vonhezhou 请问“不圆润”具体是？可否提供动图/截图说明一下？

**Comment by StarryVoid** [comment]
![2](https://user-images.githubusercontent.com/20756365/54655459-eef5c480-4ab9-11e9-88a0-5566ecaa1558.png)
我猜他说的是这个

**Comment by vonhezhou** [comment]
[image: image.png]这个样子，跟上面差不多

**Comment by vonhezhou** [comment]
> 这样看确实不圆润，欠盘😂（不过我自己试了下，是真的高速，要画的超快才能出现图中这么明显的转折效果，难道是电脑配置影响）

应该是的。这个bug就看程序的读取WM_MOUSEMOVE的速度，读得快了，丢的点少，相对会圆润一些。如果机器配置高，自然难出现一些。
