### ISSUE TITLE
现在应用商店里的snipatse更新后最小缩放是10%

### ISSUE THREAD

**Issue by chenyue314** [Snipaste/feedback#1098]
记得之前可以无限缩小比例的，那样就可以有些大图也可以缩得很小，希望恢复这样(❤´艸｀❤)

**Comment by septs** [comment]
限制是因为当您缩放到 1x1 时是无法操作的。

**Comment by liulex** [comment]
@chenyue314 
限制贴图的最小缩放是很早的版本就加入的，并非商店版新加的。
对于超大贴图，或许应该考虑使用缩略图功能？

**Comment by chenyue314** [comment]
感觉之前那样会方便些，有时候贴好几个参考图，可以把一些暂时不用的缩得很小就可以忽略它，10%的限制，如果长宽1000的一张图话，缩到最小也有100x100，遮挡效果还是比较明显的，更大的原图也会造成遮挡更多地方，或者做成最小大小的限制这样5x5
