### ISSUE TITLE
[bug] 记号笔有个颜色无法正片叠底

### ISSUE THREAD

**Issue by lethefrost** [Snipaste/feedback#1099]
RGB（239，228，176）这个颜色会直接如纯色般显示
![image](https://user-images.githubusercontent.com/47198693/54649109-49bdfa80-4a7f-11e9-8d04-b097ceab38b8.png)

什么问题会导致这样的bug呢？
看更新日志说1.16.2修复了不能用中文输入法的bug，可我还是不能用……
此外，mac是否无法用shift让贴图自动对齐啊，功能差异里好像没写这一点

**Comment by septs** [comment]
请确认与您的显示器色准无关。

**Comment by Genteure** [comment]
你这个描述让人很难理解你想表达的是什么意思。。

alpha 通道设置成 255 了吧？

![image](https://user-images.githubusercontent.com/11240579/54649610-f0d57d00-4ae5-11e9-944a-ca6dab693502.png)

**Comment by lethefrost** [comment]
咦，您的电脑上能透过吗？好奇怪啊，这张图在我手机上也还是看不到后面的字啊。
不好意思啊我不太懂(･_･;
机型是MacBook Pro 2017，显示器参数应该买回来之后没有调过……

**Comment by lethefrost** [comment]
嗯，是255，但是您看其他两块颜色，也都是不透明度100%的。记号笔的特性不是把色块正片叠底吗？应该能透出下面的黑字啊。

**Comment by lethefrost** [comment]
![image](https://user-images.githubusercontent.com/47198693/54649939-96ef9b80-4a82-11e9-82a8-9cde5f08b923.png)
您看，这是一个正片叠底的图层正常的显示
也就是主楼截图中，（255，201，14）这个自带的黄色在snipaste里表现如常，而（239，228，176）则显示不出正片叠底的特性

**Comment by lethefrost** [comment]
> 你这个描述让人很难理解你想表达的是什么意思。。
> 
> alpha 通道设置成 255 了吧？
> 
> ![image](https://user-images.githubusercontent.com/11240579/54649610-f0d57d00-4ae5-11e9-944a-ca6dab693502.png)

![Image Copied on 2019-03-19 at 20 07 10 PM](https://user-images.githubusercontent.com/47198693/54650024-e635cc00-4a82-11e9-8cb9-2257873a9219.png)

您看，这是一个正片叠底的图层正常的显示
也就是主楼截图中，（255，201，14）这个自带的黄色在snipaste里表现如常，而（239，228，176）则显示不出正片叠底的特性

**Comment by Genteure** [comment]
> 记号笔的特性不是把色块正片叠底吗？

不是。记号笔这个工具和其他的工具没有功能上的区别，不是 Photoshop 里的正片叠底效果。只是单纯的默认了 Alpha 通道为 105 而不是 255 而已。把其他工具使用的颜色 Alpha 值调下来就一样了。

不过好像可以作为一个 feature request （（

![image](https://user-images.githubusercontent.com/11240579/54650382-1adc6e80-4ae9-11e9-97e0-c7b642fb6c53.png)
![image](https://user-images.githubusercontent.com/11240579/54650465-a48c3c00-4ae9-11e9-9c91-56c9cf11e2f3.png)

**Comment by lethefrost** [comment]
> > 记号笔的特性不是把色块正片叠底吗？
> 
> 不是。记号笔这个工具和其他的工具没有功能上的区别，不是 Photoshop 里的正片叠底效果。只是单纯的默认了 Alpha 通道为 105 而不是 255 而已。把其他工具使用的颜色 Alpha 值调下来就一样了。
> 
> 不过好像可以作为一个 feature request （（
> 
> ![image](https://user-images.githubusercontent.com/11240579/54650382-1adc6e80-4ae9-11e9-97e0-c7b642fb6c53.png)
> ![image](https://user-images.githubusercontent.com/11240579/54650465-a48c3c00-4ae9-11e9-9c91-56c9cf11e2f3.png)

咦，可是橘黄色那个在csp里正片叠底后和snipaste记号笔之后都是#F7C947啊。而且，恕我冒昧一下，我真的认为是正片叠底，因为如果只是单纯降低不透明度，下图可作比较：
![image](https://user-images.githubusercontent.com/47198693/54650768-627dde80-4a86-11e9-8207-d65accc0d34f.png)
如图，左边是记号笔，累加很多层之后还是可以清晰透出下方黑色，而且颜色叠到一个高饱和度的深色之后不再叠加。

右边是普通的、降低了不透明度的方块功能，可见叠的层数多了，下方的黑字就看不见了，而且逐渐趋于它自身的固有色。

**Comment by lethefrost** [comment]
> > 记号笔的特性不是把色块正片叠底吗？
> 
> 不是。记号笔这个工具和其他的工具没有功能上的区别，不是 Photoshop 里的正片叠底效果。只是单纯的默认了 Alpha 通道为 105 而不是 255 而已。把其他工具使用的颜色 Alpha 值调下来就一样了。
> 
> 不过好像可以作为一个 feature request （（
> 
> ![image](https://user-images.githubusercontent.com/11240579/54650382-1adc6e80-4ae9-11e9-97e0-c7b642fb6c53.png)
> ![image](https://user-images.githubusercontent.com/11240579/54650465-a48c3c00-4ae9-11e9-9c91-56c9cf11e2f3.png)

您之所以出现颜色不同于原本颜色，应该是因为默认不透明度为105，如果拉到255，会发现和普通的方形色块还是不一样的，能够透过下层内容，比如主楼的蓝色和橘黄色记号笔。好像目前我试过的所有颜色里只有239，228，176不能正片叠底？

**Comment by Genteure** [comment]
是我理解错了。。。确实是有这个 bug 。。。。
我用了这么长时间，因为记号笔一直是默认 105 Alpha 我就一直以为是透明度的区别了。
确实是有一段高亮度低饱和度的颜色有这个问题。
尴尬了哈哈哈。。。

**Comment by lethefrost** [comment]
> 是我理解错了。。。确实是有这个 bug 。。。。
> 我用了这么长时间，因为记号笔一直是默认 105 Alpha 我就一直以为是透明度的区别了。
> 确实是有一段高亮度低饱和度的颜色有这个问题。
> 尴尬了哈哈哈。。。
> 
> 既然不是单纯的透明效果，为啥记号笔要 105 而不是 255 呢（小声

啊，居然有一整段，连白色也是，这我都没发现，我也尴尬了(･_･;
win上也有这个问题嘛？大大好久没更新了，催催mac呀，还在公测版1551

**Comment by lethefrost** [comment]
输入法输入法！(´；ω；`)we need Chinese!

**Comment by StarryVoid** [comment]
以上，两位
1、不是BUG，笔为无视原有颜色直接覆写，记号笔为修改颜色通道（一个贴纸一个贴膜）
2、其他颜色不会覆盖原有内容的，是你覆盖次数不够多
3、下图中只有红色左侧是笔，其他都是记号笔
![Snipaste_2019-03-20_09-13-26](https://user-images.githubusercontent.com/20756365/54652101-80126e80-4aad-11e9-9f5a-50fe6626f7c4.png)
![Snipaste_2019-03-20_09-14-08](https://user-images.githubusercontent.com/20756365/54652102-80126e80-4aad-11e9-9094-22afdac3517a.png)

**Comment by lethefrost** [comment]
> 以上，两位
> 1、不是BUG，笔为无视原有颜色直接覆写，记号笔为修改颜色通道（一个贴纸一个贴膜）
> 2、其他颜色不会覆盖原有内容的，是你覆盖次数不够多
> 3、下图中只有红色左侧是笔，其他都是记号笔
> ![Snipaste_2019-03-20_09-13-26](https://user-images.githubusercontent.com/20756365/54652101-80126e80-4aad-11e9-9f5a-50fe6626f7c4.png)
> ![Snipaste_2019-03-20_09-14-08](https://user-images.githubusercontent.com/20756365/54652102-80126e80-4aad-11e9-9094-22afdac3517a.png)
> ![3](https://user-images.githubusercontent.com/20756365/54652259-278fa100-4aae-11e9-8d2b-46a49fa831d1.png)

![image](https://user-images.githubusercontent.com/47198693/54652318-e3d86f80-4a8c-11e9-9068-8aa55e83e21a.png)


好像不会啊，比如FFF200这个黄色，在叠加了几百次之后，变化速度变缓，但是最终也终止在FF0C00不动了，不再变得更深了。但如果用的是更深的红色，确实是会逐渐趋于黑色。
您说的覆写是什么意思啊？

**Comment by StarryVoid** [comment]
> > 以上，两位
> > 1、不是BUG，笔为无视原有颜色直接覆写，记号笔为修改颜色通道（一个贴纸一个贴膜）
> > 2、其他颜色不会覆盖原有内容的，是你覆盖次数不够多
> > 3、下图中只有红色左侧是笔，其他都是记号笔
> > ![Snipaste_2019-03-20_09-13-26](https://user-images.githubusercontent.com/20756365/54652101-80126e80-4aad-11e9-9f5a-50fe6626f7c4.png)
> > ![Snipaste_2019-03-20_09-14-08](https://user-images.githubusercontent.com/20756365/54652102-80126e80-4aad-11e9-9094-22afdac3517a.png)
> > ![3](https://user-images.githubusercontent.com/20756365/54652259-278fa100-4aae-11e9-8d2b-46a49fa831d1.png)
> 
> ![image](https://user-images.githubusercontent.com/47198693/54652318-e3d86f80-4a8c-11e9-9068-8aa55e83e21a.png)
> 
> 好像不会啊，比如FFF200这个黄色，在叠加了几百次之后，变化速度变缓，但是最终也终止在FF0C00不动了，不再变得更深了。但如果用的是更深的红色，确实是会逐渐趋于黑色。
> 您说的覆写是什么意思啊？

你选择了FFF200
即你会写入红色通道，绿色通道，但是蓝色通道不会有任何写入
即无限次数叠加后，红色通道信息被填满，绿色通道信心被填满，蓝色通道信息不变
即你仍然可获得原图片的蓝色通道，你仍然能获取到原图信息。

**Comment by liulex** [comment]
@lethefrost 表现上来看确实是不对的，我回头查一下。
Mac 的输入法问题在 1.16.2 没有完全解决，在下个月更新的 2.2 版本会修复的。

**Comment by lethefrost** [comment]
> > > 以上，两位
> > > 1、不是BUG，笔为无视原有颜色直接覆写，记号笔为修改颜色通道（一个贴纸一个贴膜）
> > > 2、其他颜色不会覆盖原有内容的，是你覆盖次数不够多
> > > 3、下图中只有红色左侧是笔，其他都是记号笔
> > > ![Snipaste_2019-03-20_09-13-26](https://user-images.githubusercontent.com/20756365/54652101-80126e80-4aad-11e9-9f5a-50fe6626f7c4.png)
> > > ![Snipaste_2019-03-20_09-14-08](https://user-images.githubusercontent.com/20756365/54652102-80126e80-4aad-11e9-9094-22afdac3517a.png)
> > > ![3](https://user-images.githubusercontent.com/20756365/54652259-278fa100-4aae-11e9-8d2b-46a49fa831d1.png)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/47198693/54652318-e3d86f80-4a8c-11e9-9068-8aa55e83e21a.png)
> > 好像不会啊，比如FFF200这个黄色，在叠加了几百次之后，变化速度变缓，但是最终也终止在FF0C00不动了，不再变得更深了。但如果用的是更深的红色，确实是会逐渐趋于黑色。
> > 您说的覆写是什么意思啊？
> 
> 你选择了FFF200
> 即你会写入红色通道，绿色通道，但是蓝色通道不会有任何写入
> 即无限次数叠加后，红色通道信息被填满，绿色通道信息被填满，蓝色通道信息不变
> 即你仍然可获得原图片的蓝色通道，你仍然能获取到原图信息。
> 
> 现在你的颜色为FF F2 00
> 你修改颜色通道时，红色向FF靠拢，绿色向F2靠拢，蓝色由于无写入则不会有变化
> 覆写时，红色向FF靠拢，绿色向F2靠拢，蓝色向00靠拢

哇，长知识了，原来规则是这样的。
可是试了一下，您说笔是覆写，记号笔是修改是吗？
![image](https://user-images.githubusercontent.com/47198693/54655532-ada0ed00-4a98-11e9-8814-cfe6dbfe60aa.png)
（FF0C00记号笔）蓝色通道变0了，并不是无变化啊。绿色也并不是向F2靠拢，通道稳定在9，而这些无论原来是白色、蓝色还是浅紫色的区域，最终都只有红色通道在变化，所以还能看出明暗区分，而绿蓝稳定在9和0。

*（咦！图截完再看，好像就有色差了，和截图过程中看的取色器不一样。可能是压缩了？我说的数字是取色过程中哒，你可以试试）*

![image](https://user-images.githubusercontent.com/47198693/54655361-13d94000-4a98-11e9-8d81-42e90542d3dd.png)
用FFC90E（另一个黄色，也是自带的）记号笔试了下，绿蓝稳定在2和0。

---

![image](https://user-images.githubusercontent.com/47198693/54655791-97476100-4a99-11e9-9218-928a3f622c74.png)

我觉得正相反，如图所示，没有任何变化的应该是红色通道才对——如图左边红色通道为255，右侧四个色块红色通道都是189，记号笔多层之后各自的其他通道都变了，红色保持没变。
