### ISSUE TITLE
win10重装系统后微软商店下载的版本是1.15,1,之前购买了专业版的

### ISSUE THREAD

**Issue by WitMiao** [Snipaste/feedback#1100]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

卸载重下还是1.15.1,不知道怎么解决

**Comment by liulex** [comment]
2.x 版本的最低系统版本要求是 10.0.15063.0.

**Comment by WitMiao** [comment]
> 2.x 版本的最低系统版本要求是 10.0.15063.0.

系统升到最新后软件更新成功喽,Thanks♪(･ω･)ﾉ
