### ISSUE TITLE
[功能建议]：支持保存成.snip格式，能够二次编辑

### ISSUE THREAD

**Issue by chiyiw** [Snipaste/feedback#1101]
+ **场景**
用Snipaste截图后做了标注，当作笔记或者分享给别人，但是后面想修改，只能重做一份（试过在原截图上再截图，但是里面的标注已经无法修改，比如箭头无法擦除）。所以希望可以保存修改，下次打开可以继续编辑或者修改。
+ **需求**
截图可以支持二次修改。
+ **实现**（猜测）
将添加的标注保存下来，存为*.snip格式，程序关联 *.snip 文件后缀，打开时读取标注。（肯定比想象中的要复杂的多~）

**最后，感谢作者开发这么优秀的软件，用起来真的很棒！**

**Comment by septs** [comment]
与 #16

**Comment by chiyiw** [comment]
不好意思，楼太高了，没看到~

**Comment by liulex** [comment]
跟 #16 不是一回事。
@chiyiw 提到的需求，“截图标注保存后，还想修改”，在进入截图后按 <kbd>,</kbd> <kbd>.</kbd> 即可。

**Comment by chiyiw** [comment]
感谢你们关注这个帖子！ 我本意是在保存成 png 后， 下次开机打开电脑， 还可以修改 那个png（包括上面的标注）， 下次开机应该不能再进入到之前的截图了，就像ps输出文件 psd 和 最终文件 png 的区别。

**Comment by liulex** [comment]
> 下次开机应该不能再进入到之前的截图了

为什么不能？

**Comment by chiyiw** [comment]
无法进入截图，截图编辑后，窗口关闭了。这个“进入”指的是 使用 Snipaste 打开 png ? 还是 F3 贴图？还是我没用熟~~

**Comment by StarryVoid** [comment]
贴图未被关闭或销毁，里面会保存你的操作，可以撤销/重做
一旦你关闭或销毁成功了，就没了。
snipaste现在没有专有格式储存这些操作，只有缓存文件。
最后png格式没有通道能储存编辑信息，储存编辑信息就涉及到 [Snipaste 图层] 的设计了

**Comment by chiyiw** [comment]
> 贴图未被关闭或销毁，里面会保存你的操作，可以撤销/重做
> 一旦你关闭或销毁成功了，就没了。
> snipaste现在没有专有格式储存这些操作，只有缓存文件。
> 最后png格式没有通道能储存编辑信息，储存编辑信息就涉及到 [Snipaste 图层] 的设计了

对对，这个才是我所说的二次编辑，保存“通道编辑信息”或者说“图层”，我将这样的文件称为 *.snip 文件。

**Comment by liulex** [comment]
> 这个“进入”指的是 使用 Snipaste 打开 png ? 还是 F3 贴图？还是我没用熟~~
F1 进入截图状态。
