### ISSUE TITLE
snipaste.exe-损坏的映像

### ISSUE THREAD

**Issue by Paul-Time** [Snipaste/feedback#1102]
运行环境
操作系统：Windows 10 64bit 1803
Snipaste 版本： windows商店版本
无法打开snipaste后，且会出现两个弹窗

snipaste.exe-损坏的映像
C:\Program
Files\WindowsApps\Microsoft.vclibs.140.00.UWPDesktop 14.0.27323.0 x64 8wekyb3d8bbwe\VCRUNTIME 140.dlI没有被指定在Windows上运行，或者它包含错误。请尝试使用原始安装介质重新安装程序，或联系你的系统管理员或软件供应商以获取支持。错误状态0xc0000020

snipaste.exe-损坏的映像

C:\Program
Files\WindowsApps\Microsoft.vclibs.140.00.UWPDesktop 14.0.27323.0 x64 8wekyb3d8bbwe\MSVCP 140.dlI没有被指定在Windows上运行，或者它包含错误。请尝试使用原始安装介质重新安装程序，或联系你的系统管理员或软件供应商以获取支持。错误状态0xc0000020

已采取措施：
1 按照在网上搜索 在cmd中输入for %1 in (%windir%\system32\*.dll) do regsvr32.exe /s %1 命令 没有用
2 按照snipaste官网上的说明的故障排除，安装Microsoft Visual C++ Redistributable 2015，因有另一版本（2017版）的原因我无法安装，对应的压缩包我已无法下载 
我已有2013与2017版本的Microsoft Visual C++ Redistributable
3  在windows的应用卸载中我修复了Microsoft Visual C++ Redistributable 2017 但并没有用

故寻求帮助

**Comment by septs** [comment]
请卸载 Microsoft Store 版本后重新安装。

**Comment by liulex** [comment]
@Paul-Time 
安装这个试试：https://www.microsoft.com/en-us/download/details.aspx?id=53175

**Comment by Paul-Time** [comment]
1@septs   多谢提出的建议 但卸载 Microsoft Store 版本后重新安装并没有用。
2@liulex  感谢提供的程序 但安装后也没有用。
3 另外 我卸载了微软 Visual C++ 2017 ，以此用来安装微软 Visual C++ 2015 也没有用
4 另外 在Microsoft.vclibs.140.00.UWPDesktop 14.0.27323.0 x64 8wekyb3d8bbwe这个文件夹里，我哪怕得到了最高权限进入安全模式， 也无法在里面粘贴覆盖旧的dll文件
折腾了好久 。。。。。

**Comment by liulex** [comment]
@Paul-Time 请问你是否有找到解决办法？

**Comment by Paul-Time** [comment]
@liulex 并没有 我现在用的是软件snipaste  没有用UWP。。。。

**Comment by zwt-ss** [comment]
同样遇到了这个问题，通过重置微软商店后重新安装解决了这个问题。操作是在应用中点击微软商店，点击高级选项，重置。
或者在启动中输入wsreset
我同时进行了以上两个操作，不知道是哪一个生效了。

**Comment by Paul-Time** [comment]
@zwt-ss  多谢 根据你的指导  问题已解决 太感谢啦！  
@liulex @septs 仍然要多谢两位的帮助与跟进！
好久没登github了 现在才看到 抱歉哈
