### ISSUE TITLE
希望考虑下历史记录浏览与管理功能

### ISSUE THREAD

**Issue by kerhbal** [Snipaste/feedback#1104]
原因：虽然别的软件可以达到此效果，但是无法联通到snipaste中来，尤其无法读取snipaste截图的过程。因snipaste的历史记录并不只是一张图片，而是截图范围内外的原始图像以及当初编辑的可撤销操作。

举例：我认为在截图方面snipaste最好的一点是用`,` `.` 可以看到以前的记录，并且可以撤销某些编辑操作然后重新编辑。因为我经常会对截图进行很多标注，用别的软件如果标注结束保存关闭后发现有一点标错了就得重来，而用snipaste完全可以读取到这个历史记录然后撤销到错误的那步重新来过。

现在我想要看到以前的历史记录需要的是一直按 `,` 直到它出现为止，实在效率有些低。而如果只是在自动保存目录中翻找文件又无法还原以及重做当初的标注过程。

希望能考虑一下，谢谢！

**Comment by liulex** [comment]
找回截图历史记录属于低频操作，我认为能用就够了。

**Comment by kerhbal** [comment]
@liulex 好吧，希望未来有空的时候考虑考虑吧。毕竟从另一方面看，能纵览使用此软件以来的截图历史也是挺有感触的 😂

**Comment by StarryVoid** [comment]
以前倒是提过这个需求，因为很多ios的软件喜欢支持这个功能。但是这个没有被考虑，原因也如上。

**Comment by kerhbal** [comment]
@liulex 想再提一点，不知snipaste的主流用户都是在哪些情景下用，我用到它是在写论文时，非常好用，谢谢开发！
想要纵览历史的原因是论文的写作周期都比较长，尤其是改动周期。而图片也往往需要多次修改来达到最好的指示效果。在此时间段内截图功能必然也会用在其他非论文的方面，导致想要改动之前一个图的标记就需要`,` `.`很多次才能找到当初的可重编辑的截图。

我的想法是既然这种能够记录编辑历史的功能在截图软件里是比较独特的，那如果将其优点充分开发出来应该会吸引更多类似工作周期比较长的用户。

或者另外一个想法是保持现有的历史记录，无需开发历史记录的新浏览交互，而是将截图环境也像贴图那样能够按预先的选择来分组，不同组的`,``.`所激活的历史记录不同，类似于浏览器的多用户。
这样在需要工作时我将“工作”选定，所有历史记录/自动保存记录都会归为“工作”组别，未来回溯的时候也能避免其他项的干扰。
小小建议，希望考虑，谢谢！

**Comment by septs** [comment]
@kerhbal 
如同您的陈述的一样您所设想的诉求，
在逻辑上可能只能覆盖您的单方面需求。

我认为不同的用户在不同的应用场景下对于 history 理解和诉求都是不太相同的。
因此我认为不实现对于 历史的管理，
由使用者自行进行资源管理是更好的选择。

**Comment by kerhbal** [comment]
@septs 
多谢回复！
第一个方面是稍长历史的定位与搜寻
我只能代表我自己阐述一下需求，但我猜想从事设计工作的用户可能也会遇到无限改稿的问题。。。
第二个方面是工作生活等不同情景下的分离
这个我想应该是有些需求的，当然我无法代表其他人，但是多工作情景多用户模式似乎也是现在许多软件的趋势

其次因为snipaste历史记录的独特性，使用者其实无法自行进行资源管理，因为比较关键的一点是snipaste能记录可重复编辑的编辑历史，这点只有依靠snipaste内置的功能才行。

**Comment by septs** [comment]
关于这个功能诉求目前仅有两个 issue，
当有更多人提出时作者应会予以考虑的。

就目前的设计目标来说，Snipaste 的标注历史是用于在截图时立即标记的对于后期编辑并未予以设计。

我目前认为您可能在超出 Snipaste 的设计目标使用。

**Comment by miaozilong** [comment]
设置为每次截图和贴图都保存就可以了,每次想看历史的时候,去文件夹里翻一翻就是了

**Comment by miaozilong** [comment]
![image](https://user-images.githubusercontent.com/3994941/196088064-f2660280-ec5b-4be8-96c1-1eebaa03a6a9.png)

**Comment by miaozilong** [comment]
按下截图快捷键后,按","和"."键也可以翻看历史贴图

**Comment by miaozilong** [comment]
> ![image](https://user-images.githubusercontent.com/3994941/196088064-f2660280-ec5b-4be8-96c1-1eebaa03a6a9.png)

![image](https://user-images.githubusercontent.com/3994941/196088287-4fa43075-9a55-4483-bd40-df2d63b4492c.png)
重新表述下
