### ISSUE TITLE
切换组别再切换回来后原组中被关闭的贴图无法被恢复

### ISSUE THREAD

**Issue by kerhbal** [Snipaste/feedback#1105]
如题，不知道是feature还是bug，微软商店版本。
按照文档中说法感觉应该是bug： `被关闭的贴图，可再次被贴出，除非超过“可被恢复的已关闭贴图数”`
复现过程如下：
![69bbca83ly1fx0t0vmuyvg20](https://user-images.githubusercontent.com/11629684/55279915-f9536200-52f4-11e9-83f3-408a818e9b57.gif)

我的贴图设置：
![image](https://user-images.githubusercontent.com/11629684/55279945-446d7500-52f5-11e9-8bb5-84dc877043cf.png)

**Comment by liulex** [comment]
因为实现逻辑是被关闭的贴图属于当前组，所以切到其他组/之后被关闭的贴图就被清掉了。
经你提醒，这种绑定关系确实没有必要，我会在下次更新修正。

**Comment by kerhbal** [comment]
@liulex 多谢回复！建议一个更加清楚的逻辑：
1. 各组内图片如不手动转移则一直处于原组内，无论打开或关闭
2. 组内操作不会对别组有任何影响
