### ISSUE TITLE
Mac  alpha-2019-03-09_15-13 内测版截图后闪退

### ISSUE THREAD

**Issue by whatone** [Snipaste/feedback#1107]
第一次截图后，软件闪退，截图也消失，今天才出现的状况。
2015 款 MacBook Pro 15寸 标配，系统版本 10.14.3

**Comment by liulex** [comment]
这是因为内测版到期了……

**Comment by whatone** [comment]
哪里可以获取到最新的内测版呢

**Comment by liulex** [comment]
请问你目前的内测版是从哪里获取的呢？

**Comment by whatone** [comment]
我目前的内测版主要是和作者发邮件来的

**Comment by liulex** [comment]
那直接邮件反馈即可，内测版的问题不用发在这里哈。
