### ISSUE TITLE
鼠标指针真实情况

### ISSUE THREAD

**Issue by xbsaying** [Snipaste/feedback#1109]
想要显示鼠标指针的真实状态，而不是单纯地补充一个鼠标箭头，不同情况下鼠标指针能显示不同的内容。

**Comment by StarryVoid** [comment]
现在版本是可以抓到动态鼠标指针的，所以你那边是改动什么设置了么？

**Comment by liulex** [comment]
目前的指针捕捉是可以反映大部分鼠标指针的真实图案的，至于更特殊的情况，不打算进行适配了。
