### ISSUE TITLE
拉了第二个箭头后第一个箭头不能被调整了

### ISSUE THREAD

**Issue by DingRingDR** [Snipaste/feedback#1110]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by DingRingDR** [comment]
应该是还没增加的一个功能吧

**Comment by StarryVoid** [comment]
能简单做个gif或者说明复线步骤么？
调整第一个箭头首先保证当前贴图不关闭清掉元素记录。以及你需要点击到第一个箭头的位置。
最后如果你是截图时做的动作，按下贴图按钮视同留下显示内容而不会记录元素位置

**Comment by liulex** [comment]
该功能需要专业版。
