### ISSUE TITLE
剪贴板上出现别人的贴图。你们是不是把截图上传到服务器了

### ISSUE THREAD

**Issue by youhappyisok** [Snipaste/feedback#1114]
电脑睡眠唤醒以后，出现一张别人的截图，F3还贴图成功了。所以确认是你们的软件弄到剪贴板上的。请尽快联系我并查明原因

**Comment by septs** [comment]
请验证本问题是由 Snipaste 引发的。

**Comment by liulex** [comment]
“F3还贴图成功了” -> "所以确认是你们的软件弄到剪贴板上"，其中的逻辑是？
你打开 Word 还能把截图粘贴进去呢？怎么不说是 Word 弄的？

**Comment by youhappyisok** [comment]
首先我对上午语气不好道歉，对不起。
但是出现这种问题带给我的只有恐慌，思索半晌最大可能在我们软件上，所以来反馈，我也是Snipaste的多年忠实用户，情绪不好望理解。然后我做一下解释。
1.首先我电脑上没有任何别的截图软件。而且QQ截图已关闭。唯一另一个用到截屏的软件的是天若OCR。我与软件开发者取得联系，OCR只会识别文字，不会对剪贴板进行操作。
2.其次莫名出现的这张图片明显是一张会计报销表格，和我完全没有任何联系，一万杆子都打不着的那种，绝对不是来自我的电脑和我的操作。
3.F1/F3快捷键是Snipaste独有。F3能贴出来确实只能说明剪贴板上有。但是能对剪贴板进行操作的软件真的没有其他的了。
希望你们能够帮我排查原因。
再次为上午态度不好道歉。

**Comment by liulex** [comment]
> 但是能对剪贴板进行操作的软件真的没有其他的了。

所有软件都可以操作剪贴板。

> 绝对不是来自我的电脑和我的操作。

虽然所有软件都可以复制，但几乎没有软件会在用户不知情的情况下往剪贴板放东西，所以这 99% 是你自己的操作。

---

Snipaste 从来都没有上传文件的代码，所以这件事 100% 跟 Snipaste 无关，我们没有义务帮你排查你个人电脑的问题。
