### ISSUE TITLE
功能建议：统一截图与贴图两个状态下对图片保存相关的快捷操作

### ISSUE THREAD

**Issue by kerhbal** [Snipaste/feedback#1116]
背景：
有时需要将已有图片作为底图在上面进行标注，此时我会复制图片到剪贴板然后贴到屏幕上，再使用标注功能。

遇到的问题：
此时标注成功后对图片结果的保存/复制不支持截图状态下的特性：
1. 复制后不会自动保存
2. 左键双击/回车/中键单击 的动作无法在此时使用

建议的功能：
1. 将自动保存功能拓展到贴图上
2. 将截图后的快捷动作拓展到贴图上

谢谢！

**Comment by liulex** [comment]
你提的两个操作，在贴图上都是不现实的，贴图已经有自己的一套操作逻辑，并且提供了自定义功能。
