### ISSUE TITLE
将输出设置为100但是截的图片还是不清晰，出现截图的字消失

### ISSUE THREAD

**Issue by FlyOser** [Snipaste/feedback#1117]
在我使用截图的时候将图片保存然后将图片打开，发现所截的图中字消失了部分，且画质不是很清晰

**Comment by StarryVoid** [comment]
有具体图例么？以及你的字是多大的字

**Comment by FlyOser** [comment]
发自我的华为手机-------- 原始邮件 --------主题：Re: [Snipaste/feedback] 将输出设置为100但是截的图片还是不清晰，出现截图的字消失 (#1117)发件人：StarryVoid 收件人：Snipaste/feedback 抄送：FlyOser ,Author 有具体图例么？以及你的字是多大的字
