### ISSUE TITLE
截图编辑很好用，希望贴图也可以右键编辑

### ISSUE THREAD

**Issue by hoginwang** [Snipaste/feedback#1118]
想要：对贴图进行编辑。

具体：快捷键 F3 贴图后，可以通过对贴图右键菜单->编辑然后跟截图时一样可以编辑。

为什么需要：手机截图想遮盖部分信息，强迫症想要选定矩形区域进行模糊，然而手机装的应用都不能满足这一需求，但如果把截图传到电脑、可以用贴图编辑的话，就不用开 Photoshop 了.............

**Comment by Genteure** [comment]
@hoginwang 贴图右键也可以编辑啊？
菜单名称是 标注
