### ISSUE TITLE
压缩的功能不够强，已经开启最大压缩。

### ISSUE THREAD

**Issue by jin6220** [Snipaste/feedback#1119]
截图之后，图片大小是76k
然后去tinypng这个网站压缩了下，https://tinypng.com/
大小变成了28k。

因为是印象笔记一个月60m流量，所以不是珍贵的照片希望在保持清晰的情况下能最大化压缩。
---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by jin6220** [comment]
![image](https://user-images.githubusercontent.com/22074843/56662132-e35b7600-66d5-11e9-8acb-df327be70262.png)

**Comment by septs** [comment]
您可以自行保存图片使用任意第三方工具获得最佳大小
