### ISSUE TITLE
启动项丢失

### ISSUE THREAD

**Issue by FlyOser** [Snipaste/feedback#1121]
不清楚什么原因下，snipaste的开机启动项丢失，我重新设置开机启动后出现了任务计划配置工具这个启动项，并没有出现软件的启动项

![image](https://user-images.githubusercontent.com/47632335/56798902-5980e980-684a-11e9-9c1a-b8462074b344.png)

**Comment by liulex** [comment]
勾选“以管理员身份”后，确实是通过 任务计划 进行自启动的，没有问题。
