### ISSUE TITLE
截图时用WASD微调后需要点击鼠标两次才可以正常进入截图选择框

### ISSUE THREAD

**Issue by StarryVoid** [Snipaste/feedback#1122]
发现了 bug？

截图时用WASD微调后需要点击鼠标两次才可以正常进入截图选择框
按下截图键
鼠标移动到区域
WASD调节鼠标指针位置
按下鼠标左键，拖拽（无效）
重新wasd对准
按下鼠标左键，按下鼠标左键，拖拽（无效）
重新wasd对准
按下鼠标左键，按下鼠标左键，按下鼠标左键，拖拽（有效）

**Comment by liulex** [comment]
无法重现。

**Comment by StarryVoid** [comment]
新版本已经修复了，疏忽了
