### ISSUE TITLE
微软商店版 2.1.4 贴图无法新建分组

### ISSUE THREAD

**Issue by tuinstein** [Snipaste/feedback#1124]
Windows商店2.1.4版本的snipaste无法新建分组，菜单中的贴图一行后没有下拉三角可以新建分组

**Comment by liulex** [comment]
贴图组功能需启用“自动备份”:
![image](https://user-images.githubusercontent.com/2010459/57088546-1a183880-6d35-11e9-9463-d8ffef4d94e0.png)
