### ISSUE TITLE
建议增加图床支持

### ISSUE THREAD

**Issue by sky31even** [Snipaste/feedback#1125]
初步想法是加到截图后的工具栏上，多一个按钮叫上传至图床。

在设置界面内可以
1. 设置绑定的图床，如 Imgur 等；
2. 选择上传成功后的动作，如复制图片地址到剪贴板，打开图床链接等等。

[参考了这个chrome工具（可以很容易的把网上的图片摘到自己的图床）](https://chrome.google.com/webstore/detail/imgur-uploader/lcpkicdemehhmkjolekhlglljnkggfcf)

使用场景：
写博客的时候就不用截图 - 保存本地 - 上传图床这么麻烦了= =
如能采纳，万分感谢~~相信也有其他很多媒体人和我一样有这个需求

**Comment by septs** [comment]
请合并至 #60 继续讨论。
