### ISSUE TITLE
能否填加一个标注二次修改的选项

### ISSUE THREAD

**Issue by owenplum** [Snipaste/feedback#1126]
在截图进行标注的时候，怎么设置才能可以标注一次就成功，不修改呢， 比方说，我想在截完图以后进行连续的标注箭头，但是因为可以二次修改，所以无法连续的操作，很容易就把之前的标注移动了，如何设置才能不进行二次修改呢
如果可以话，可以填加一个可以二级修改的标注的选项，那样snipaste完全就可以当做屏幕画笔来使用，那样进行演示什么会非常方便，希望能采那我的建议
感谢作者做出这么好的软件，感恩!

**Comment by septs** [comment]
该需求与 Snipaste 的设计目标相违背。

**Comment by owenplum** [comment]
你说的很有道理，但是应该是很轻易就可以实现的，而且也不影响snipaste的使用和设计目标吧，只是提出一个建议而矣
真心希望能可以改进这个功能，也真心喜欢这个软件，已经用了好几年了，刚开始有了就一直在用，如果专业版的可以单独实现，我会去够买专业版

**Comment by Genteure** [comment]
> 我想在截完图以后进行连续的标注箭头，但是因为可以二次修改，所以无法连续的操作，很容易就把之前的标注移动了

试一下按鼠标右键？
![image](https://user-images.githubusercontent.com/11240579/57177640-a2631e80-6e98-11e9-99a8-07f5febee445.png)

**Comment by owenplum** [comment]
鼠标右键是可以再次标注，但是连续性很差， 使得我有的时候不得不用qq截图，如果可以用鼠标左键连续的标注那就完美了

**Comment by StarryVoid** [comment]
Snipaste现在没有图层的概念，所以你可以理解标注是额外的一张图附在原图上，所以所有的标注都在一起也不会锁定单独一个。
如果你觉得修改上一次的麻烦，你可以直接将图片恢复到100%然后重新贴一张一摸一样的，之前所有额度标注都变成一张图然后在这张图上修改。

**Comment by owenplum** [comment]
楼上可能没有理解我要表达的意思，我没有说图层的概念，我指的是在单张图上做标注的时候，每次都要确定一下之前的标注，比方说我要在图上画一个箭头，这个箭头是可以修改和移动的，但是我不想那样做，我想连续的画很多箭头，不想再修改，不知道我的表达是不是很清晰，说白了我就是想作为演示的目的，现在的情况是无法连续标注

**Comment by StarryVoid** [comment]
也许你没理解我说的，假如你想让你相同方式做好的标注以两种状态存在（一种可修改的A,一种不可修改的B）
那么此时必然要分层，A一层锁定，B一层提供修改。
我想表达的意思是这个意思，Snipaste现在只会让AB都在一层，不同方式（线段，文字）能分开。

**Comment by liulex** [comment]
应该是这样的效果？
![](https://user-images.githubusercontent.com/2010459/57196343-b426ed80-6f8e-11e9-929e-1f91302d88f3.gif)

**Comment by owenplum** [comment]
是的，每次标注完不可以再次修改上一次的标注，那样的话就可以连续的标注了！当然，有些人还是须要再次修改的，所以我的意思是可以加一个再次修改的选项开关，不知道作者大人可否给实现呢
另外在截的时候双击鼠标左键就是退出截图了，在连续的标注的时候很容双击在一个点啊，那样之前做的标注一下都没有了，可否填加一个选项，就是双击不退出截图状态，那样就完美了

**Comment by owenplum** [comment]
我知道怎么发gif的动态图片，如果方便可以加我的qq.17545420

**Comment by owenplum** [comment]
您上面的动图，是每次标注完要点一下鼠标的右键，有一个确认的过程对吧，我的意思是想把这个确认的过程去掉，那样就可以连续的标注了，希望作者能明白我要表达的意思！

**Comment by owenplum** [comment]
我在网上找了很多截图标注的软件，没有一个功能和实用性比的过snipaste的，只有连续标注这一点，使我不得不找其它的软件代替，qq截图做的很不错，但是也因为双击同一点时候会退出截图而不完美，所以我想方设法联系snipaste的作者，希望能满足我的愿望，感恩！

**Comment by liulex** [comment]
1. 我上面的动图，没有点鼠标右键这个操作。是加了一个选项，使得添加标注之后不会自动选中它。该选项会在下次专业版更新加上，如果反馈良好会考虑默认开启。
2. 专业版有选项可以自定义鼠标左键双击的功能。

**Comment by owenplum** [comment]
1.可以加上一个选项，标注以后不可修改，如果还是可以修改的话，那么鼠标回到之前标注的地方还是会移动之前的标注，那样还是会影响连续性
2.双击鼠标左键可以自定义成换标注的种类吗，例如，我现在是画箭头，双击以后可以切换成画方框吗？
当然我的需要是双击鼠标左键不退出截图就行，如果有能快捷切换标注工具的方式就更好了
感谢作者大人的回复，谢谢

**Comment by owenplum** [comment]
我暂时找到了用snipaste解决的办法，就是在标注直线的时候，可以点画笔，然后同时按住shift键，就可以暂时实现我想要的效果。只是没有箭头了

**Comment by owenplum** [comment]
> 1. 我上面的动图，没有点鼠标右键这个操作。是加了一个选项，使得添加标注之后不会自动选中它。该选项会在下次专业版更新加上，如果反馈良好会考虑默认开启。
> 2. 专业版有选项可以自定义鼠标左键双击的功能。

我仔细看了你的上在的动图，那个不是自动选定的项选如要开启的话，我那后面是如何修改的标注的，我看到你修改了两次，那是通过什么操作重新选定的，如果是用鼠标左键选定，还是会出现标注不连续的可能，另外新版什么时候出呢，我想够买

**Comment by KazamaSion** [comment]
该特性已添加至最新版，详见官网更新日志。

**Comment by owenplum** [comment]
> 该特性已添加至最新版，详见官网更新日志。

非常感谢您意见的采纳！

**Comment by owenplum** [comment]
> 该特性已添加至最新版，详见官网更新日志。

您好，我提到的功能是只有在专业版才中以使用的功能吗，我应该如何购专业版呢，是下载商店版，还是windows版呢？我下载了7月2日更新的版本，没有找到如何升级成专业版的地方，选项是灰色的

**Comment by owenplum** [comment]
刚才仔细看了专业的更新日志，貌似仍然没有实现我想连续标注的功能，我是想可以连续画箭头，而不托动之前的标注，然后如果双击了左键，不会退出截图功能，不知道如何试用和购买，如果实现了我说的功能，请告知我，我会第一时间购买专业版。

**Comment by liulex** [comment]
@owenplum 

2.2 增加的功能是这个：
> 高级设置：
>   * Annotate/auto_select_on_creation #1126

设成 false 可以在话箭头的时候不自动选中箭头，该功能不需要专业版。但对专业版来说，如果鼠标**重新**放到箭头上，还是会选中它的，这是二次编辑的功能。

双击左键不退出截图，这个特效需要专业版。

专业版目前只能从商店版内购，桌面版在 Beta 阶段暂不提供专业版购买功能。

**Comment by owenplum** [comment]
![image](https://user-images.githubusercontent.com/31396018/60644036-80b9ef80-9e67-11e9-934f-444d92eca1f0.png)
看了您的回复，我是这么修改的，不知是否正确，软件重启后，并没有你说的效果，画完箭头也后，仍然是选中状态，鼠标放在这个选中状态上，还是可以修改这个标注

双击左键，我在设置中选择无，已经可以不退出截图功能了

请问大大，我哪里设置有误吗，还是说现在仍然无法实现我想要的连续标注的功能呢？

**Comment by loguu** [comment]
@owenplum 查看一下软件版本？

**Comment by owenplum** [comment]
![image](https://user-images.githubusercontent.com/31396018/60644754-9f20ea80-9e69-11e9-8078-34379aed73cc.png)

**Comment by owenplum** [comment]
> @owenplum 查看一下软件版本？

![image](https://user-images.githubusercontent.com/31396018/60644801-b8c23200-9e69-11e9-80e3-58de45e4e5df.png)
版本是最新的2.2

**Comment by owenplum** [comment]
> @owenplum
> 
> 2.2 增加的功能是这个：
> 
> > 高级设置：
> > 
> > * Annotate/auto_select_on_creation #1126
> 
> 设成 false 可以在画箭头的时候不自动选中箭头，该功能不需要专业版。但对专业版来说，如果鼠标**重新**放到箭头上，还是会选中它的，这是二次编辑的功能。
> 
> 双击左键不退出截图，这个特性需要专业版。
> 
> 专业版目前只能从商店版内购，桌面版在 Beta 阶段暂不提供专业版购买功能。

![image](https://user-images.githubusercontent.com/31396018/60645099-60d7fb00-9e6a-11e9-9baf-6152951be68c.png)

我的设置文件是这样的，无论auto_select_on_creation=false或者true，都是一样的效果，标注后没有任何的改变，仍然是选中的状态

**Comment by owenplum** [comment]
> @owenplum
> 
> 2.2 增加的功能是这个：
> 
> > 高级设置：
> > 
> > * Annotate/auto_select_on_creation #1126
> 
> 设成 false 可以在画箭头的时候不自动选中箭头，该功能不需要专业版。但对专业版来说，如果鼠标**重新**放到箭头上，还是会选中它的，这是二次编辑的功能。
> 
> 双击左键不退出截图，这个特性需要专业版。
> 
> 专业版目前只能从商店版内购，桌面版在 Beta 阶段暂不提供专业版购买功能。

我不知道是不是我的设置问题，还是我们的软件目前还是处于调试阶段
我也不知道我的表达您是否理解，无论怎样，都要感谢作者大大的无私分享和辛勤的付出，我相信如果实现我的需求，会增加一大部分用户。

**Comment by liulex** [comment]
@owenplum 
呃抱歉。。是我记反了
`Annotate/auto_select_on_creation`  这个是需要专业版的
双击左键不退出截图 这个不需要专业版

**Comment by liulex** [comment]
想了一下，`Annotate/auto_select_on_creation`还是开放给免费版好了，等下个版本。

**Comment by owenplum** [comment]
> 想了一下，`Annotate/auto_select_on_creation`还是开放给免费版好了，等下个版本。

抱谦，我今天下午测试的时候双击是可以不退出的，但是晚上怎么测试都是失败的，不知道为何？哈哈
请问下个版本大概多久能更新呢，是否能实现我说的连续标注，双击左键不退呢？

**Comment by liulex** [comment]
现在！

**Comment by owenplum** [comment]
> 现在！

作者大人，我简直是太爱你了！
我对你的敬仰之情有如涛涛江水连绵不绝，黄河泛滥一发不可收拾啊。。。
比心！
此时我激动的心情无以言表，向你致敬！

**Comment by owenplum** [comment]
> 现在！

作者大人，目前软件已经很完美了，再次感谢！
不过仍然要请教一个问题，每次截图的时候，都要点击一下箭头，才可以进行标注操作，
那么如何设置才可以进入截图就可以默认是箭头标注的状态呢？这样可以减去一个每次在截图的时候的点击箭头的动作，那样可快捷，当然如果需要画框或者其它操作的时候，仍然可以选择其它的选项。
忘回复，谢谢！

**Comment by alnhny** [comment]
> 应该是这样的效果？ ![](https://user-images.githubusercontent.com/2010459/57196343-b426ed80-6f8e-11e9-929e-1f91302d88f3.gif)

请问这个箭头标注的二次编辑功能是怎么操作的，我现在用的2.7.3 beta，好像只有文字标注能二次编辑。

**Comment by ugirc** [comment]
> > 应该是这样的效果？ ![](https://user-images.githubusercontent.com/2010459/57196343-b426ed80-6f8e-11e9-929e-1f91302d88f3.gif)
> >       
> >         [
> >           
> >             ![57196343-b426ed80-6f8e-11e9-929e-1f91302d88f3.gif](https://user-images.githubusercontent.com/2010459/57196343-b426ed80-6f8e-11e9-929e-1f91302d88f3.gif)
> >           
> >         ](https://user-images.githubusercontent.com/2010459/57196343-b426ed80-6f8e-11e9-929e-1f91302d88f3.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/2010459/57196343-b426ed80-6f8e-11e9-929e-1f91302d88f3.gif)
> 
> 请问这个箭头标注的二次编辑功能是怎么操作的，我现在用的2.7.3 beta，好像只有文字标注能二次编辑。

同问

**Comment by Geeyun-JY3** [comment]
@alnhny @ugirc 这事作者说得很清楚了：https://github.com/Snipaste/feedback/issues/1126#issuecomment-508339369
> 但对专业版来说，如果鼠标重新放到箭头上，还是会选中它的，这是二次编辑的功能。

文档里也写得很清楚，二次编辑标注形状需要 Pro：https://docs.snipaste.com/zh-cn/pro?id=%e6%a0%87%e6%b3%a8%e7%9b%b8%e5%85%b3
