### ISSUE TITLE
CANNOT RUN SNIPASTE ON MAC

### ISSUE THREAD

**Issue by wanyeruan** [Snipaste/feedback#1127]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好
下载解压后无法打开软件 一直没有反应 系统10.9.5

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by StarryVoid** [comment]
LOGFILE ？

**Comment by liulex** [comment]
Cannot reproduce. More infor is required.

**Comment by wanyeruan** [comment]
SORRY just check my mails.
[image: image.png]
system version OS X 10.9.5
Snipaste version: 2.2.0 beta
cannot run the app without any notification.
Just totally has no responses.

Le Liu <notifications@github.com> 於 2019年6月15日 週六 下午11:17寫道：

**Comment by septs** [comment]
@wanyeruan Email reply not supported image.

**Comment by wanyeruan** [comment]
system version OS X 10.9.5
Snipaste version: 2.2.0 beta
cannot run the app without any notification.
Just totally has no responses.

Septs Biscuit <notifications@github.com> 於 2019年7月14日 週日 下午3:01寫道：

**Comment by jy1989** [comment]
相同的问题
v2.3.5 Beta (2020.04.12)
macos 10.15.4 (19E287)
