### ISSUE TITLE
在 Mac 上使用 Snipaste 截全屏图后，从 Mac 版本的微信上发到手机端，手机端微信显示不全图片。

### ISSUE THREAD

**Issue by feeltens** [Snipaste/feedback#1128]
如题，在 Mac 上使用 Snipaste 截全屏图后，从 Mac 版本的微信上发到手机端，手机端微信显示不全图片。
在手机端微信保存图片到本地后，查看图片两侧还是被切掉了。
如果使用微信自带的截全屏图后，将图片保存到本地，是可以查看全屏图片的。

**Comment by liulex** [comment]
手机端使用 Android 微信无法重现。

**Comment by Emrys365** [comment]
+1，有同样的问题，是不是可能因为图片截得太宽了？

**Comment by alexluoli** [comment]
近日发现截图发微信，图片size都很大，去到10几M。怀疑升级了10.14.5引起。

**Comment by daoluan** [comment]
同样的问题

**Comment by alexluoli** [comment]
同样问题，对方是安卓微信就看不全，只看到中间。

**Comment by feeltens** [comment]
Snipaste v2.2 Beta (Mac) 已修复这个问题啦。
