### ISSUE TITLE
v1.16.2 Beta for Mac版本 Mac OS 下无法打来

### ISSUE THREAD

**Issue by lijiayan2015** [Snipaste/feedback#1131]
第一次在官网下载了v1.16.2 Beta for Mac版本的Snipaste,下载后解压,得到一个如下的应用程序文件:
<img width="929" alt="image" src="https://user-images.githubusercontent.com/16370666/57352101-e0ad5600-7196-11e9-899a-238ce01877fd.png">
点击这个文件,没有在桌面顶部生成Snipaste图标按钮,我理解成没法打开.
我的系统版本如下:
<img width="280" alt="image" src="https://user-images.githubusercontent.com/16370666/57352188-33870d80-7197-11e9-91e6-72a363d7e890.png">
寻求解决方案.

**Comment by liulex** [comment]
无法重现，等下个版本更新后再试试。

**Comment by septs** [comment]
请尝试最新 2.2.0 Beta 后报告
https://dl.snipaste.com/mac-beta
