### ISSUE TITLE
【新功能】mac：截图固定贴在所有桌面

### ISSUE THREAD

**Issue by foamzou** [Snipaste/feedback#1132]
请求新功能

系统：mac

需求描述：截图固定贴在所有桌面。即切换桌面时，图也能跟着过来

建议配置入口：
1. 全局配置：贴图【开启/取消固定在所有桌面】
2. 单个贴图配置：在某个贴图右击，弹出菜单，点击“√ 固定在所有桌面”，可为该贴图开启/取消固定在所有桌面的功能。

**Comment by liulex** [comment]
2.2 版会先实现贴图固定在所有桌面，配置项后续会加上。

**Comment by woshizoufeng** [comment]
> 2.2 版会先实现贴图固定在所有桌面，配置项后续会加上。

好的，谢谢大佬

**Comment by qq148376839** [comment]
配置项什么时候加哦，用习惯了不固定，突然固定了好难受

**Comment by bingcheng1998** [comment]
有办法现在就取消这个功能吗？很没用而且影响日常使用。很糟糕的新功能。
