### ISSUE TITLE
Windows 10 贴图上点击无效，鼠标穿透已关闭

### ISSUE THREAD

**Issue by vaxt** [Snipaste/feedback#1133]
系统信息：
版本：Win10 专业版
版本号 1809
操作系统版本 17763.475

今天贴图的时候鼠标无法移动贴图，贴图右键菜单也出不来。
但鼠标滚轮缩放贴图以及透明度修改有效.

只能通过(esc)关闭贴图，空格键可以显示编辑框。

另外，编辑完贴图后鼠标在贴图上显示为禁用状态
![图片](https://user-images.githubusercontent.com/14368387/57576798-14d88d80-749b-11e9-8c06-fcafde44ab2e.png)

日志文件：
[splog.txt](https://github.com/Snipaste/feedback/files/3169634/splog.txt)

**Comment by liulex** [comment]
谢谢反馈！请问是否有重现步骤呢？我自己尝试了一些操作无法复现。
看 log 是 1.16.2 版本，也可以等桌面版 2.x 更新后再看看是否还会出错。

**Comment by vaxt** [comment]
抱歉，我也不清楚如何复现，因为自那以后我都无法正常使用snipaste了。
更换老版本Snipaste-1.15.3-x64情况也是依旧。
微软应用商店上的版本好像是2.x版本的，我安装了结果也是一样。
除了重装系统，我不知道是否有别的办法能让它恢复正常，但我近期没有重装系统的打算。
另外，在发生这种情况前后的时间里，我往电脑上安装了VS2019 Community，不知道是否跟这个有关？

**Comment by liulex** [comment]
意思是每次打开 Snipaste，贴图都无法移动，无法唤出右键菜单吗？
另外，截图功能正常吗？

**Comment by vaxt** [comment]
是的，鼠标无法移动贴图，但贴图后通过键盘方向键可以缓慢移动。
截图功能是正常的

**Comment by StarryVoid** [comment]
新版本 V2.2 方便测试一下是否仍然存在这个问题么？
的确可能是因为系统支持库的差异导致这个问题，建议将snipaste所需的文件放入软件根目录
（https://docs.snipaste.com/zh-cn/troubleshooting）

**Comment by vaxt** [comment]
我从官网重新下载了 Snipaste-2.2.1-Beta2-x64版本，然后手动下载了Visual C++ 2015的dll,运行后问题依然存在
![Snipaste_2019-07-14_08-56-41](https://user-images.githubusercontent.com/14368387/61178014-bc964700-a615-11e9-8296-ef90bf61660e.png)
![Snipaste_2019-07-14_09-02-10](https://user-images.githubusercontent.com/14368387/61178031-1d258400-a616-11e9-9083-cb43e6a00e59.png)

**Comment by liulex** [comment]
录个动图展示一下完整过程？

**Comment by vaxt** [comment]
![3](https://user-images.githubusercontent.com/14368387/62177725-90e6c100-b378-11e9-8fe6-6600fb5aaad4.gif)
如上图，贴图后无法点击，图中的轻微移动是用方向键移动的，编辑工具栏是按空格键打开的

**Comment by liulex** [comment]
应该是系统或系统设置问题了，有么有改过什么特别的系统设置或做过什么优化？

**Comment by ylkkdy** [comment]
为什么我无法使用鼠标穿过快捷键呢。。我想把贴图固定在屏幕上并在其下工作
