### ISSUE TITLE
有可能加上 “截图里保留鼠标光标” 的功能吗？

### ISSUE THREAD

**Issue by Tairraos** [Snipaste/feedback#1135]
有可能加上 “截图里保留鼠标光标” 的功能吗？ 我用的是MAC版本。谢谢

**Comment by septs** [comment]
您可在“首选项”中找到该项设置

**Comment by liulex** [comment]
Mac 版暂未加入该功能，以后会尝试。

**Comment by alanhg** [comment]
期待Mac版尽快加入，刚需

**Comment by alanhg** [comment]
这个以后已经半年多了，我觉得时间浪费不起了，换

**Comment by JackieAnxis** [comment]
为啥我是一直存在鼠标光标，没有禁用项...

**Comment by liulex** [comment]
Snipaste 2.6 Beta for Mac 已支持。

**Comment by alanhg** [comment]
## 设置

![image](https://user-images.githubusercontent.com/9245110/127772292-a50dc847-dfc9-459f-8777-a040da7ee7ef.png)
