### ISSUE TITLE
是否会考虑增加OCR功能？

### ISSUE THREAD

**Issue by FanXiangTM** [Snipaste/feedback#1136]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by stevenzhu25** [comment]
@FanXiangTM OCR貌似已经不是截图软件的范围了吧………

**Comment by FanXiangTM** [comment]
> @FanXiangTM OCR貌似已经不是截图软件的范围了吧.........
贴图功能也不在截图软件的范围，但作者开发了这个功能，并且成为了该软件的最大亮点。截取屏幕，然后把截图贴到桌面上，然后识别图上的文字，这是一个流畅的操作，这是一个必然的流程

**Comment by scruel** [comment]
https://github.com/scruel/ClipIt

**Comment by wangjiati** [comment]
自写 截图转字
https://github.com/wangjiati/ClipboardImageOCR/releases/download/V1.0/ClipboardImageOCR.zip

**Comment by LeeSunBowen** [comment]
> 自写 截图转字
> https://github.com/wangjiati/ClipboardImageOCR/releases/download/V1.0/ClipboardImageOCR.zip

建议能再加上自动搜索功能，转文字之后直接进入浏览器搜索

**Comment by Fxiao1** [comment]
主要是使用snipaste识别文字就很顺畅：
1. 截图
2. 贴图
2. 选择区域
3. 识别为文字并复制

如果用第三方工具的话就变成了：
1. 截图
2. 保存到本地的一个目录
3. 打开第三方软件
4. 根据目录打开刚才保存的截图
5. 识别文字并复制
6. 关闭ocr软件
7. 到刚才的目录中删除截的那张图

所以十分期待snipaste能整合ocr的功能

**Comment by godwinnnnn** [comment]
> > @FanXiangTM OCR貌似已经不是截图软件的范围了吧.........
> > 贴图功能也不在截图软件的范围，但作者开发了这个功能，并且成为了该软件的最大亮点。截取屏幕，然后把截图贴到桌面上，然后识别图上的文字，这是一个流畅的操作，这是一个必然的流程

添加一个功能，不是考虑这个功能是不是这个软件的范围吧，而是这个功能有没有这种需求，符不符合大众需求

**Comment by FanXiangTM** [comment]
> > > @FanXiangTM OCR貌似已经不是截图软件的范围了吧......... 
> > > 贴图功能也不在截图软件的范围，但作者开发了这个功能，并且成为了该软件的最大亮点。截取屏幕，然后把截图贴到桌面上，然后识别图上的文字，这是一个流畅的操作，这是一个必然的流程
> 
> 添加一个功能，不是考虑这个功能是不是这个软件的范围吧，而是这个功能有没有这种需求，符不符合大众需求

首先，你@错对象了。"OCR貌似已经不是截图软件的范围了吧......... "这观点不是我说的，我只是在回复这个观点。
其次，添加一个功能是必须要考虑功能范围的，然后才考虑用户需求的问题。如果把大众需求放在第一位，那么添加一个直播功能你觉得合适吗？添加一个聊天功能可以吗？

**Comment by godwinnnnn** [comment]
> > > > @FanXiangTM OCR貌似已经不是截图软件的范围了吧.........
> > > > 贴图功能也不在截图软件的范围，但作者开发了这个功能，并且成为了该软件的最大亮点。截取屏幕，然后把截图贴到桌面上，然后识别图上的文字，这是一个流畅的操作，这是一个必然的流程
> > 
> > 
> > 添加一个功能，不是考虑这个功能是不是这个软件的范围吧，而是这个功能有没有这种需求，符不符合大众需求
> 
> 首先，你@错对象了。"OCR貌似已经不是截图软件的范围了吧......... "这观点不是我说的，我只是在回复这个观点。 其次，添加一个功能是必须要考虑功能范围的，然后才考虑用户需求的问题。如果把大众需求放在第一位，那么添加一个直播功能你觉得合适吗？添加一个聊天功能可以吗？

也不是，这个功能是否有需求，然后再看这个功能能解决什么问题，再做决定吧
