### ISSUE TITLE
按F1截图时，能否设置默认选中箭头或其它选项

### ISSUE THREAD

**Issue by wskia161** [Snipaste/feedback#1137]
按F1截图时，能否设置默认选中箭头或其它选项，这个需求应该有很多人需要这个设置选项的。有时做教程要截N张图，每张都要箭头指明教程步骤。每次都要点一下，速度不够快。

![11](https://user-images.githubusercontent.com/4724317/57669299-f8745680-763c-11e9-9865-d9d37ef8b805.JPG)

**Comment by wskia161** [comment]
或者弄一个快捷键设置选中箭头或其它选项

**Comment by liulex** [comment]
下个版本会有选项的（需要专业版）。
