### ISSUE TITLE
几点建议：

### ISSUE THREAD

**Issue by ntgeralt** [Snipaste/feedback#1139]
你好，我反馈几个问题：
1.16.2的首选项-关于-反馈，点击那个网址会无法用浏览器跳转（不知道我电脑问题还是bug）。
另外快捷键截图，建议一键截全屏并自动保存，完全后台操作，无需反馈给用户。类似于nvidia experience那个功能。他那个只能截游戏，有的游戏还无法截。如果你能一键截全屏并自动保存，就完全替代掉nvidia experience了

**Comment by StarryVoid** [comment]
点不开的问题，建议检查一下浏览器关联情况。

自动保存的方式建议使用命令行方式调用snipaste截图。

**Comment by ntgeralt** [comment]
好的~
