### ISSUE TITLE
微软应用商店版，快捷方式图标问题

### ISSUE THREAD

**Issue by XZPQNBV5** [Snipaste/feedback#1141]
我win10安装应用商店版之后,开始菜单图标不显示，固定到“开始”屏幕之后也一样，请问怎么处理呀？

![image](https://user-images.githubusercontent.com/50760834/57968184-b54a1880-7999-11e9-927e-c666505790f2.png)
我重新配色了一款，哈哈

**Comment by XZPQNBV5** [comment]
![image](https://user-images.githubusercontent.com/50760834/57968411-d95b2900-799c-11e9-8b3b-fb4aba6bfafa.png)自我感觉上面那款比这款洋气。

**Comment by scruel** [comment]
close 吧...您的配色亮瞎了 有点丑?

**Comment by XZPQNBV5** [comment]
> 关闭吧...你的配色亮瞎了有点丑？

这不是重点，关键是问题怎么解决啊？？？

**Comment by scruel** [comment]
store 启动, 查看右下角托盘

**Comment by XZPQNBV5** [comment]
> store启动，查看右下角托盘

![image](https://user-images.githubusercontent.com/50760834/58032225-be331980-7b54-11e9-8292-59a1707ecc34.png)
这样子的

**Comment by XZPQNBV5** [comment]
就开始菜单程序栏图标问题，其他都没问题

**Comment by linzyjx** [comment]
请尝试删除这个文件（系统文件，隐藏的）
C:\用户（Users）\用户名\AppData\Local\IconCache.db
然后重启试试

**Comment by liulex** [comment]
![Snipaste](https://user-images.githubusercontent.com/2010459/58384375-b6232000-8013-11e9-81d7-77328292b117.png)
