### ISSUE TITLE
截图，快捷键 ctrl+方向键，shift+方向键

### ISSUE THREAD

**Issue by ztg-zlu** [Snipaste/feedback#1142]
我觉得，，ctrl+方向键，是对左上角的操作，也就是说，ctrl+↑，是左上角向上扩大，ctrl+←，是左上角向左扩大，ctrl+↓，是左上角向下缩小，ctrl+→，是左上角向右缩小，shift+方向键是一样的，是对右下角的操作，以前的操作，觉得好别扭

**Comment by StarryVoid** [comment]
Snipaste的Ctrl和Shift分别对照为修改选择框的四条边，上下左右选择一条对应的选择框的四条边
Ctrl是增加对应边缘1px，Shift反之减少1px

**Comment by ztg-zlu** [comment]
@StarryVoid 这样用着，很不舒服呀，我要改变左上角的大小，我还要记住是按ctrl还是shift，可能是我个人不太习惯吧

**Comment by liulex** [comment]
用左上角/右上角来区分更加不直观啊，例如比较常见的一个操作是，上下左右都扩大一个像素，用你的按键就很难按了。
