### ISSUE TITLE
超级截图能否增加自动复制到剪贴板功能？

### ISSUE THREAD

**Issue by lfsatan** [Snipaste/feedback#1143]
截图完自动在剪贴板 双击关闭就可以了。当前似乎只有普通截图可以实现 超级截图后出来贴图 还得按ctrl+C 再双击关闭 比较繁琐

**Comment by liulex** [comment]
![Snipaste](https://user-images.githubusercontent.com/2010459/58384328-12d20b00-8013-11e9-8882-93cd2c3f21ec.png)
