### ISSUE TITLE
画框,拆线,记号笔,画笔 ,模糊, 文字添加 都没有快捷键, 每次都要用鼠标去选, 好烦人呐

### ISSUE THREAD

**Issue by LonelyTear** [Snipaste/feedback#1144]
请求新功能？
* 画框,拆线,记号笔,画笔 ,模糊, 文字添加 都没有快捷键, 每次都要用鼠标去选, 好烦人呐, 太浪费像我这种高端adc , apc的炫技操作了.

**Comment by liulex** [comment]
dup of #664
