### ISSUE TITLE
和 golden dict 冲突

### ISSUE THREAD

**Issue by finalfail** [Snipaste/feedback#1145]
稍微搜了下 G 和之前的 issue,没看到重复的
系统版本 win10 2016 LTSB
运行 golden dict
版本 1.5.0-RC2--372-gc3ff15f (基于 Qt 5.12.3)
截图选定界面大概率会卡住,任务管理器也调不出来
这个问题,在版本号相同(基于 Qt 4.8.6)的版本上不会出现

golden dict 来自
https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Windows

**Comment by liulex** [comment]
这个应该是 Qt 5.12.3 的问题…… Accessiblity 接口实现有问题。

**Comment by LeoQtue** [comment]
> 截图选定界面大概率会卡住，任务管理器也调不出来

将「任务管理器」设置为「置为顶层」可调出杀掉 GoldenDict，不然中招只能注销、关机或重启，太蛋疼。

**Comment by borpubi** [comment]
目前我的方法是：win + R -- cmd --  taskkill /im goldendict.exe /f

**Comment by EsuRt** [comment]
这种方法可以解决：
Snipaste关闭“行为”中的“自动检测窗口”，同时将goldendict.exe添加到配置中的crashes部分。
config.ini 的修改如下：

```
[Snip]
crashes=goldendict.exe
detect_windows=false
```

**Comment by liulex** [comment]
`config.ini` 增加两行：
```
[Snip]
crashes=goldendict.exe
```
保存，重启 Snipaste.
