### ISSUE TITLE
chrome 全屏状态看直播/视频，或者f11。操作截图f1+单击，大小为1920*1079，少了一排像素

### ISSUE THREAD

**Issue by tingjiangcao** [Snipaste/feedback#1146]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by liulex** [comment]
请问版本是？
2.1.4 无法重现。

**Comment by tingjiangcao** [comment]
------------------ 原始邮件 ------------------
发件人: "Le Liu"<notifications@github.com>;
发送时间: 2019年6月16日(星期天) 凌晨0:48
收件人: "Snipaste/feedback"<feedback@noreply.github.com>;
抄送: "319231660"<319231660@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Snipaste/feedback] chrome 全屏状态看直播/视频，或者f11。操作截图f1+单击，大小为1920*1079，少了一排像素 (#1146)




请问版本是？
 2.1.4 无法重现。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


从QQ邮箱发来的超大附件

重现录屏.zip (57.23M, 2019年07月16日 01:53 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=776130332f065dc49a77372015630317010702040555090c1b560950564e055a50511d0b04000315540753030451020a01515504336f31eeeeaee6f18fa5f0164c0840330e&code=6a033c18

**Comment by KazamaSion** [comment]
Backup the attachment for future consultation only.

https://www.mediafire.com/file/x17tm9jhrf9q2fo/

**Comment by StarryVoid** [comment]
我这边复现成功。
抓取窗口丢失的1px必须为bilibili全屏播放页面置顶同时使用截图
不在置顶状态时不存在抓取窗口丢失1px问题

**Comment by StarryVoid** [comment]
经测试得到以下结果
1、Firefox 开启获取窗口内元素，未复现
2、Chrome 开启F12开发者模式，查看CSS元素大小
2.1、在播放窗口点击左右键时，无变化
2.2、此时使用snipaste截图，获取1079高度。
2.3、取消1079截图，此时查看到css有1秒钟变为1079宽度。
2.4、如果浏览器内活动窗口不在对应视频上时，比如在F12开发者工具，此时不存在以上现象
