### ISSUE TITLE
[Feature Request] - Hide Menu bar icon (macOS)

### ISSUE THREAD

**Issue by tddschn** [Snipaste/feedback#1148]
Thank you for the great app you made!

but it would be better if the menu bar icon can be hidden (macOS), as there are already too much icons on the menu bar that I seldom click on.

users can still toggle Snipaste settings through launcher apps like Spotlight or Alfred.

**Comment by liulex** [comment]
Please check [here](https://docs.snipaste.com/advanced-configs) on how to hide the tray icon.
