### ISSUE TITLE
【新功能请求】增加滚动截图&&隐藏托盘图标开关

### ISSUE THREAD

**Issue by ZhongJinMing** [Snipaste/feedback#1152]
首先感谢作者提供了这么好的一款截图软件，真的是**高颜值，功能多**的难得的产品。‘
1. 在实际的使用过程中发现很多场景都需要滚动截图，所以希望能添加一个滚动截图的功能；
2. 希望能增加一个隐藏托盘图标的开关，因为托盘图标实在是有点多。

再次感谢开发者！

**Comment by septs** [comment]
滚动截图 #19
隐藏托盘图标请详细看文档

**Comment by liulex** [comment]
@ZhongJinMing 隐藏托盘图标的设置在[这里](https://docs.snipaste.com/zh-cn/advanced-configs)。

**Comment by ZhongJinMing** [comment]
> 滚动截图 #19
> 隐藏托盘图标请详细看文档

感谢！找到了

**Comment by ZhongJinMing** [comment]
> @ZhongJinMing 隐藏托盘图标的设置在[这里](https://docs.snipaste.com/zh-cn/advanced-configs)。

感谢！找到了
