### ISSUE TITLE
win10系统设置开机启动会报毒

### ISSUE THREAD

**Issue by liby** [Snipaste/feedback#1153]
发现了 bug？
* 请描述一下重现的步骤，越详细越好
1. 打开Snipaste
2. 右键打开设置菜单
3. 打勾开机启动或者以管理员身份启动
4. 报毒
请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282
- 之前没遇到过这个问题,而且一直是自动启动的,现在突然无法自启了,但是看确实是打勾了
![捕获](https://user-images.githubusercontent.com/38807139/59548022-59b08200-8f7b-11e9-99ae-a9cfac3a182a.PNG)

**Comment by littlecxm** [comment]
今天发现同样的错误
简单的分析一下可能是调用了C:\Windows\System32\schtasks.exe，从而触发了误报

**Comment by liby** [comment]
@littlecxm 
之前没遇到过,现在删了用的win10商店版本,没发现报错了

**Comment by baobao1270** [comment]
遇到了同样的错误，是昨天更新了 1.295.751.0 的病毒库定义之后才报毒的

**Comment by xiatianna** [comment]
我病毒库的版本为  1.295.806.0

关闭snipaste，然后双击启动，就会自动报毒了

**Comment by xiatianna** [comment]
我病毒库的版本为 1.295.806.0

关闭snipaste，然后双击启动，就会自动报毒了。
在snipaste首选项中，关闭开机启动就不会报毒

**Comment by liulex** [comment]
奇怪，我更到 1.295.806.0 依然没问题……
始终有问题的同学，取消“以管理员身份”就好了。
![图片](https://user-images.githubusercontent.com/2010459/59558808-6d1c2580-902d-11e9-80f7-dc3d377c81b6.png)
![图片](https://user-images.githubusercontent.com/2010459/59558811-7907e780-902d-11e9-850d-ad7975f0ffff.png)

**Comment by liulex** [comment]
我已创建一个反馈，请大家帮忙投票：https://aka.ms/AA5c1jv

**Comment by liby** [comment]
@liulex 
![demo](https://user-images.githubusercontent.com/38807139/59572270-a365ad80-90de-11e9-99b6-9a2afcf50883.png)

**Comment by liulex** [comment]
@liby 测试了下，还需要参加 Windows Insider 才可以访问。。

**Comment by tan-wei** [comment]
The same problem. Keep watching until the issue is closed.

**Comment by taskmgr** [comment]
复现+1，报毒：Trojan:Script/Foretype.A!ml

**Comment by liulex** [comment]
不用等微软了，下载 2.2.1 Beta2 版本吧。
