### ISSUE TITLE
请求新功能-增加一个双击退出的复选框

### ISSUE THREAD

**Issue by currencyporter** [Snipaste/feedback#1154]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282
___________________________________________________________________________________
____________________________________________________________________________________
很多时候频繁画图,然后图没画好,就退出了.原因就是左键双击复制并退出.希望作者能改良下,增加一个复选框,选择是否 启用鼠标左键双击复制,或者改用右键双击复制也挺好.

**Comment by liulex** [comment]
专业版提供更多的定制项，包括你提的左键双击的自定义功能：
![图片](https://user-images.githubusercontent.com/2010459/59612334-7c938f80-914f-11e9-8f08-6e6fef64176b.png)
