### ISSUE TITLE
关于Snipaste的一点改进意见

### ISSUE THREAD

**Issue by fistnine** [Snipaste/feedback#1155]
你好！
Snipaste非常好用，我一直以来都在使用它来工作。

我非常希望这款小软件中加入一个小功能：屏幕画笔。
就像贴图中的“标注”功能一样。
因为有时候在实时演示中需要这项功能，最好能做到在绘制的过程中网页或工作中的画面在正常播放。

**Comment by StarryVoid** [comment]
请按照如下方法操作（Snipaste Pro）

1、用Photoshop等软件制作一个与屏幕分辨率等同的，全透明通道图片
2、给图片放一个标志，提醒此图片已添加到贴图
3、用snipaste贴出此图片，背景模式选择伪透明

即可达成效果。

**Comment by liulex** [comment]
@StarryVoid 略麻烦了。。

如果不需要保持画面的正常播放，Snipaste 已经有白板模式，可以在免费版中通过[命令行](https://docs.snipaste.com/zh-cn/command-line-options)调用，或者在专业版中给白板模式绑定快捷键。

如果需要保持画面正在播放，我刚刚加上了透明白板模式，会在下次更新放出（需要专业版）：
![Snipaste_transparent_whiteboard](https://user-images.githubusercontent.com/2010459/59617287-a4d3bc00-9158-11e9-9aac-d83cae1ebc92.gif)

**Comment by fistnine** [comment]
nice

**Comment by jonathanding** [comment]
不好意思，我在Windows 10  Snipaste PRO, v2.2.1.0 (2019.07.04) 里面没有找到哪儿可以开启透明白板

**Comment by liulex** [comment]
@jonathanding 首选项 - 控制 - 全局快捷键 - 添加新命令 - 如图填写：
![图片](https://user-images.githubusercontent.com/2010459/61298817-7a395980-a811-11e9-8037-6b109b7ab680.png)

**Comment by jonathanding** [comment]
收到。超好用！赞
