### ISSUE TITLE
BUG 程序停止

### ISSUE THREAD

**Issue by LeoNull101** [Snipaste/feedback#1156]
在使用自动选择对话框的截图操作中，出现选中后卡顿，无法进入任务管理器，无法进入桌面，无法关闭snipaste或者待截图的程序，选择只有重启。

**Comment by StarryVoid** [comment]
Version？复现操作？

**Comment by LeoNull101** [comment]
Version:1.16.2,操作就是在ArcGIS10.5中进行空间分析过程，设置参数，选择截图后，贴合窗口后，无法进行截图，也无法返回桌面，无法关闭程序。

**Comment by StarryVoid** [comment]
新版本V2.2.1 出了，你测试一下V2.2.1是否仍然出现这个情况
V1.16.2的这个问题的确存在，用excel拖拽列宽也可以复现。
