### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by WinnieX** [Snipaste/feedback#1157]
已经使用了一年多了，体验很好，同时也建议添加以下两个功能：
1、每个屏幕贴图能独立修改透明度。
2、每个屏幕贴图可以独立选择是否置顶。

**Comment by mjyspace** [comment]
每个屏幕贴图本来就能独立修改透明度啊。

**Comment by StarryVoid** [comment]
新版本 V2.2.1 支持你需要的两个功能。
（建议关闭issues）
