### ISSUE TITLE
Windows商店内2.1.4版 4K显示器上截图后下方的工具条图标很小，累眼睛

### ISSUE THREAD

**Issue by yetangye** [Snipaste/feedback#1161]
Windows商店内2.1.4版 4K显示器上截图后下方的工具条图标很小，累眼睛，望解决，谢谢。

**Comment by StarryVoid** [comment]
高分屏相关的确存在这个问题。 等待作者回复

**Comment by liulex** [comment]
没有 4K 屏，没法进行测试和适配……

**Comment by yetangye** [comment]
今天Windows商店给自动更新到2.2.0版，这个版本没问题了 👍
