### ISSUE TITLE
[Feature Request] support older OSX version: 10.10.5

### ISSUE THREAD

**Issue by revintec** [Snipaste/feedback#1164]
Hi

I'm updating to Mac 2.2Beta only to find out that it no longer supports OSX 10.10.5
If none of the features rely on higher OSX version, could you please compile it targeting OSX 10.10?
Based on my experience, it should be trivial to do so, and may help reaching more users

Thx in advance

**Comment by septs** [comment]
Support older is not cost-effective.

**Comment by revintec** [comment]
@septs If we target an older OS, the resulting binary should be fine running in newer OSes, provided that no feature(like touchBar support) relies on the newer OS. Why that's not cost-effective?
