### ISSUE TITLE
商店版默认的托盘图标变成了纯白图标

### ISSUE THREAD

**Issue by Vixb1122** [Snipaste/feedback#1165]
记得之前商店版默认的托盘图标是彩色图标。
今天更新新版本后，默认的托盘图标变成了纯白色图标。
这个是feature还是bug

**Comment by liulex** [comment]
feature. 从 Win 10 开始的默认图标都是纯色的，但“首选项”中选择“默认”图标是彩色。
2.2 开始，“默认”代表纯色，以便适配任务栏主题。如果需要彩色图标，图标颜色选“自定义”，然后 `Alpha 通道` 设 0 就好了。

**Comment by Vixb1122** [comment]
好，成功了
