### ISSUE TITLE
[Feature Request] 滚轮扩选悬浮时的选择框到父控件

### ISSUE THREAD

**Issue by ts8zs** [Snipaste/feedback#1166]
在滚轮向上滚动时寻找当前悬浮选择控件的父控件 类似ublock orgin的元素屏蔽。

比如目前我想要选取整个窗口除非找到没有控件的窗口位置否则很难选到整个窗口

**Comment by liulex** [comment]
专业版很早就有这个功能了噢。
要选整个窗口按 <kbd>Tab</kbd> 就好了，不需要专业版。

**Comment by ts8zs** [comment]
感谢解答。
