### ISSUE TITLE
[Feature Request] 添加plugin/extension系统

### ISSUE THREAD

**Issue by vonhezhou** [Snipaste/feedback#1167]
类似与chrome的扩展功能，或者添加一个插件系统。让用户可以加一下功能。比如截图识别二维码的功能，可能其它人觉得没有什么用处。但是对于我来说却比较有用。总是先截图再开浏览器识别/开另一个软件识别会比较麻烦。这种的话，我可以自己做个plugin/extension来实现。

**Comment by StarryVoid** [comment]
Snipaste 存在命令行选项。 可以开发其他软件然后反向调用snipaste
https://docs.snipaste.com/zh-cn/command-line-options

**Comment by vonhezhou** [comment]
这种用法的话，要再启动一个应用在后台监听。plugin/extension系统的话，则是以snipaste为主体，扩展功能，不大一样了

**Comment by septs** [comment]
duplicate of #327
