### ISSUE TITLE
希望增加一个复选框,取消双击完成截图

### ISSUE THREAD

**Issue by currencyporter** [Snipaste/feedback#1168]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

有时候画图频繁,就不小心会双击,然后图没有画完,就已经完成截图了,好尴尬呀,又得重新画.所以如果能有个复选框,可以选择 是否 双击完成截图,那就非常好了.谢谢!

**Comment by owenplum** [comment]
这个问题已经可以设置了，在首选项里可以设置的
![image](https://user-images.githubusercontent.com/31396018/60737066-ee5f3c00-9f8b-11e9-9dd1-a2a17383c23c.png)

**Comment by StarryVoid** [comment]
Snipaste “设置” “鼠标” “关闭贴图” 默认是左键双击
旧版本  “设置” “鼠标” 左键双击 默认是 关闭贴图
编辑这个选项即可
