### ISSUE TITLE
希望能够增加gif录制和隐藏任务栏图标 

### ISSUE THREAD

**Issue by eachann1026** [Snipaste/feedback#1169]
RT
而且隐藏任务栏图标真的是刚需啊!!!! 强迫症

**Comment by eachann1026** [comment]
GIF 录制能够控制大小最好

**Comment by chsbuffer** [comment]
@eachann1026 https://docs.snipaste.com/zh-cn/advanced-configs?id=general
hide_tray_icon=true
启用后在贴图上按Ctrl+Shift+P打开设置菜单

**Comment by eachann1026** [comment]
> @eachann1026 https://docs.snipaste.com/zh-cn/advanced-configs?id=general
> hide_tray_icon=true
> 启用后在贴图上按Ctrl+Shift+P打开设置菜单

6666 牛逼牛逼  忠实粉丝了

**Comment by septs** [comment]
GIF 录制，暂无计划。
https://github.com/Snipaste/feedback/issues/282#issuecomment-268239323
