### ISSUE TITLE
Mac版在线升级到2.2.0 beta无法打开

### ISSUE THREAD

**Issue by liutf** [Snipaste/feedback#1170]
* 问题
1. Mac通过在线升级到2.2.0 beta后无法打开。
2. 卸载2.2.0，通过brew cask install Snipaste-Mac-1.16.2-Beta 装回 1.x版本，也无法打开了。

* 系统版本： 
![image](https://user-images.githubusercontent.com/14069370/60754650-be10af80-a016-11e9-9487-2670ce97e8ec.png)

* 期望
有劳作者尽快给出解决方案，临时用着QQ的截图工具很难受。辛苦！

**Comment by suyanhanx** [comment]
10.14.5 同，安装都无法实现

**Comment by devanz** [comment]
是的都无法安装，看起来是被gate keeper挡住了？

This software needs to be updated. Contact the developer for more information.
Chrome downloaded this file yesterday at 11:29 PM from docs.snipaste.com.

**Comment by liulex** [comment]
@liutf 试试官网下载安装。
@devanz 右键打开。

**Comment by liutf** [comment]
> @liutf 试试官网下载安装。
> @devanz 右键打开。

![image](https://user-images.githubusercontent.com/14069370/60768430-74979180-a0f6-11e9-9a21-9798517d849c.png)

试了官网下载重新安装，还是打不开。

**Comment by suyanhanx** [comment]
> 是的都无法安装，看起来是被gate keeper挡住了？
> 
> This software needs to be updated. Contact the developer for more information.
> Chrome downloaded this file yesterday at 11:29 PM from docs.snipaste.com.

是的，我这边也这个提示

**Comment by dangger** [comment]
重启了一下电脑解决了此问题.
10.14.4 (18E226)

**Comment by liutf** [comment]
> 重启了一下电脑解决了此问题.
> 10.14.4 (18E226)

 我重启后也可以了。。重启大法好。😁

版本：10.13.6 (17G2307)

**Comment by liutf** [comment]
解决方案：重启解决。🤣🤣
