### ISSUE TITLE
macos取色不正确

### ISSUE THREAD

**Issue by ronnywr** [Snipaste/feedback#1173]
mac os10.14.5

<img width="524" alt="屏幕快照 2019-07-09 上午9 46 19" src="https://user-images.githubusercontent.com/38126770/60853538-14583b00-a22f-11e9-82b6-afc3fee90db9.png">

**Comment by liulex** [comment]
Snipaste 显示的 RGB 值是对应于显示器当前所使用的颜色描述文件，其值与系统自带的“数码测色计”的“显示原生值”一致。

**Comment by troy351** [comment]
能否增加一个选项和 srgb 一致，因为取色很多时候是用来作图和前端开发用的，这时候 srgb 比较有用 @liulex

**Comment by Adonis0123** [comment]
可以尝试修改浏览器的颜色描述文件
<img width="991" alt="image" src="https://github.com/Snipaste/feedback/assets/46788304/19291501-0ed4-4179-959e-979199738c54">
