### ISSUE TITLE
如果我想在公司的电脑上使用，是否有版权问题

### ISSUE THREAD

**Issue by jingyulong** [Snipaste/feedback#1176]
自己个人使用，在公司的电脑上，不知道涉及到版权问题吗？还是需要购买Licence一类的？

**Comment by stevenzhu25** [comment]
@jingyulong 您可能需要购买专业版授权…

**Comment by jingyulong** [comment]
好的，感谢！

**Comment by dofine** [comment]
抱歉在已关闭问题下回复……
公司电脑是 Win 7，个人购买的是在 Win 10 商店。
但 Win 7 目前没有途径购买。

**Comment by septs** [comment]
@dofine 就目前公开的渠道仅支持 Microsoft Store 购买
关于 Steam 上架问题请关注 #1162
