### ISSUE TITLE
截图后的编辑功能里面的大小选择不了

### ISSUE THREAD

**Issue by jaryn-fang** [Snipaste/feedback#1179]
像这样，本来应该是有3个大小的边框可以选择的。
![image](https://user-images.githubusercontent.com/17583713/61107645-0286ca00-a4b3-11e9-91e4-23e4b29ef021.png)

**Comment by StarryVoid** [comment]
请检查 Snipaste设置 界面 工具条 笔尖数量

**Comment by jaryn-fang** [comment]
> 请检查 Snipaste设置 界面 工具条 笔尖数量

![image](https://user-images.githubusercontent.com/17583713/61424054-c933db80-a944-11e9-8d0a-60f8a885c9c5.png)
你好，为什么我的【界面】tab上没有【工具条】这个选项

**Comment by liulex** [comment]
免费版通过滚轮调整笔尖大小，专业版可放置多个笔尖。
