### ISSUE TITLE
在贴图上使用橡皮擦会导致进程CPU占用高

### ISSUE THREAD

**Issue by chsbuffer** [Snipaste/feedback#1181]
### [还原步骤]
在贴图上使用橡皮擦

### [现象]
用橡皮擦擦画笔时 CPU占用很高,
擦东西有延迟
会擦不干净

### [环境]
Windows10 x64
桌面版2.2.1 Beta2

**Comment by StarryVoid** [comment]
实际测试 6核12线程3.4G
CPU占用 画笔使用时 2% 最高 橡皮擦使用时 5%最高
都不满足占用极高的情况，除非你是双核双线程2G的CPU，折算会是出现高占用60%。
还请提供CPU配置与占用截图（单核，多核，CPU时间）

**Comment by chsbuffer** [comment]
i7-8550U 4核 8逻辑处理器
使用过程中占用如下
![image](https://user-images.githubusercontent.com/33744752/61181117-246b8280-a654-11e9-9610-1673c167d841.png)

![image](https://user-images.githubusercontent.com/33744752/61181108-fdad4c00-a653-11e9-8625-d07921389f4c.png)
