### ISSUE TITLE
Microsoft Store 微软商店无法安装 snipaste 新版

### ISSUE THREAD

**Issue by dddd1007** [Snipaste/feedback#1183]
过去曾正常安装各版本 snipaste 。本次更新版本无法安装，并报错，代码: 0x80246019。
其他商店内软件均可正常更新或安装，未出现相同问题。
尝试卸载Snipaste并重新安装（无法安装上），清除 Microsoft Store 缓存，重新安装 Store 。更换网络环境（办公室、星巴克、手机热点），更改系统DNS解析服务器设置等，均无效。

系统：Windows 10 19H2 Insider Slow Ring

**Comment by septs** [comment]
麻烦参照如下两个第一方论坛的讨论结果尝试解决此问题

https://answers.microsoft.com/en-us/windows/forum/windows_10-windows_store/error-code-0x80246019-when-download-in-microsoft/df9782e8-58e3-4f31-b13a-be1a6af0c810
https://answers.microsoft.com/en-us/windows/forum/all/microsoft-store-error-code-0x80246019/ce1b785a-3b1d-4f74-9cf1-bc4c0f785b84

**Comment by dddd1007** [comment]
> 麻烦参照如下两个第一方论坛的讨论结果尝试解决此问题
> 
> https://answers.microsoft.com/en-us/windows/forum/windows_10-windows_store/error-code-0x80246019-when-download-in-microsoft/df9782e8-58e3-4f31-b13a-be1a6af0c810
> https://answers.microsoft.com/en-us/windows/forum/all/microsoft-store-error-code-0x80246019/ce1b785a-3b1d-4f74-9cf1-bc4c0f785b84

您好，如上两个讨论结果在之前已经检索到，并除重新安装系统外，已经全部尝试，包含在我的问题描述”已尝试清除缓存，重新安装 Microsoft Store 应用，更换网络环境……”当中。这些解决方案均无效果。

未考虑重装系统的原因，在于问题仅出现在 Snipaste 一个程序无法安装上。且之前在 Telegram 讨论群中看到 Windows Defender 对前一个版本的 Snipaste 之间可能存在冲突，故考虑可能是 Windows 的安全机制与本版本的 Snipaste 之间不兼容导致的，故报告此 bug 。

**Comment by septs** [comment]
![image](https://user-images.githubusercontent.com/3842474/61347418-7ea45780-a88f-11e9-877b-17414a22173f.png)
我无法验证阁下的问题。

**Comment by dddd1007** [comment]
> ![image](https://user-images.githubusercontent.com/3842474/61347418-7ea45780-a88f-11e9-877b-17414a22173f.png)
> 我无法验证阁下的问题。

感谢您的及时回复。

我考虑可能是我计算机系统的问题，我将尝试重新安装系统来解决。

谢谢！

**Comment by liulex** [comment]
Windows Defender 的误报是关于 Snipaste 桌面版的，和商店版无关。
商店 2.2.1 版本已几乎全量推送，目前并没有其他用户报告过类似问题，因此可以排除是 Snipaste 方面的原因。

可以再参考一下这个[方案](https://answers.microsoft.com/en-us/windows/forum/all/error-0x80246019-using-microsoft-store/45df5fa5-ae3c-49bc-a674-4cb7dc0a11a7)，应该不至于需要重装系统：

> Method 1: I suggest you to make sure if the following service is started in Services. msc
    * Press Windows+ R keys to open Run Window.
    * Type services.msc and hit enter
    * Make sure the following service is set to Start and Automatic.
    * Background Intelligence transfer
Made the change and the apps installed straight away.

**Comment by dddd1007** [comment]
> Windows Defender 的误报是关于 Snipaste 桌面版的，和商店版无关。
> 商店 2.2.1 版本已几乎全量推送，目前并没有其他用户报告过类似问题，因此可以排除是 Snipaste 方面的原因。
> 
> 可以再参考一下这个[方案](https://answers.microsoft.com/en-us/windows/forum/all/error-0x80246019-using-microsoft-store/45df5fa5-ae3c-49bc-a674-4cb7dc0a11a7)，应该不至于需要重装系统：
> 
> > Method 1: I suggest you to make sure if the following service is started in Services. msc
> > * Press Windows+ R keys to open Run Window.
> > * Type services.msc and hit enter
> > * Make sure the following service is set to Start and Automatic.
> > * Background Intelligence transfer
> > Made the change and the apps installed straight away.

感谢您的回复！
您提供的方案仍然无效。考虑到我之前使用powershell删除了xbox等服务，且曾使用过cclean这样的软件，我猜想可能是我对系统的不正当操作导致了该问题。
因此我使用镜像对系统进行了重新安装，问题得以解决，非常感谢！
