### ISSUE TITLE
能否加入“带背景文字”和“数字序号”

### ISSUE THREAD

**Issue by sevelee** [Snipaste/feedback#1184]
![image](https://user-images.githubusercontent.com/8036235/61344659-9c1ff400-a884-11e9-9cbe-db4a9ec960eb.png)
如图，带背景的文字，以及数字序号
![image](https://user-images.githubusercontent.com/8036235/61347538-f07ca100-a88f-11e9-9b94-ba4eb56243ab.png)

**Comment by septs** [comment]
数字序号方面的讨论请合并至 #227 继续讨论。

**Comment by septs** [comment]
不太能理解阁下“带背景的文字”是什么意义？

**Comment by sevelee** [comment]
> 不太能理解阁下“带背景的文字”是什么意义？

操作失误…… 更新了图片了

**Comment by septs** [comment]
“带背景的文字”是否可以理解为 **框选区域**（矩形、圆形、椭圆形、等） 的背景为不透明吗？

**Comment by septs** [comment]
您想说为 **文本输入区域** 设置 **不透明背景** ？

**Comment by sevelee** [comment]
> 您想说为 **文本输入区域** 设置 **不透明背景** ？

对的😀

**Comment by septs** [comment]
那么这个 feature 将带来如下问题，阁下或会需要与作者进行深度讨论

1. 需要一个算法计算出 **底色**（即被截图区域的颜色）与 **文本字体颜色**
得到与两者均呈现为 **高对比度** 的颜色作为该文本区域的 **高对比度**
2. 如果用户 **自选该颜色** ，那么如果构成 **低对比度** 那么就如同阁下的第一张附图所示的结果

CC @liulex

**Comment by sevelee** [comment]
自选颜色比较科学

**Comment by liulex** [comment]
2.4 已实现。
