### ISSUE TITLE
能否增加“圆角矩形”

### ISSUE THREAD

**Issue by sevelee** [Snipaste/feedback#1185]
![image](https://user-images.githubusercontent.com/8036235/61345233-e2765280-a886-11e9-884e-db7910d89186.png)
如图，现在只有方角的矩形
![image](https://user-images.githubusercontent.com/8036235/61345270-ffab2100-a886-11e9-990e-031cb1b169c6.png)

**Comment by owenplum** [comment]
这个功能可以有

**Comment by liulex** [comment]
2.4 已支持~
