### ISSUE TITLE
Could you add a feature to invert the picture color?

### ISSUE THREAD

**Issue by WinterL** [Snipaste/feedback#1186]
Could you add a feature to invert the picture color, due to my job(programmer), 
I basically write my code with dark background, but the dark background is very blur in the slide with projector.
So I need to invert the picture color from dark to light to make the slide easy to read.

The snipaste is the awesome utility for me, if you could implement the feature, it will be very helpful for me.

Thanks!

**Comment by liulex** [comment]
Now available in the Pro version:
![](https://user-images.githubusercontent.com/2010459/79759256-07857d80-8351-11ea-8d27-024c8e24b6da.png)
Or press <kbd>6</kbd> on the image window.

**Comment by WinterL** [comment]
So unbelievably awesome, is there any way to donate? 
I had bought the Pro version, but the new feature is over-expected useful so that I would like to pay more for your great job and express my appreciation.

**Comment by liulex** [comment]
Great to hear you love it!
For the moment I don't have a plan for accepting donations, but I will be more than glad if you would introduce Snipaste to your friends and colleges. 😉
