### ISSUE TITLE
建议增加 白板教鞭功能 ,请进来细细了解,谢谢

### ISSUE THREAD

**Issue by currencyporter** [Snipaste/feedback#1187]
请求的功能是  增加 白板教学 功能. 这个功能类似于 pointofix,可以添加一个白板,用于演示画各种图形.  但现在有了snipaste,  pointofix 可以忽略不计了. 

建议可以用复选框增加这种模式,来确定启动snipaste时 是截图模式还是白板模式, 模式里面有个截图模式和白板的无缝切换.

这样snipaste就不仅仅是截图神器了!还是教学神器!

**Comment by septs** [comment]
我认为这个诉求超过了 Snipaste 原本的定位。
建议使用其他工具代替，其他意见请等待作者的回复。

**Comment by septs** [comment]
see https://github.com/Snipaste/feedback/issues/1155#issuecomment-502735182
