### ISSUE TITLE
macOS Mojave 10.14.4下点击无任何响应

### ISSUE THREAD

**Issue by itinytree** [Snipaste/feedback#1190]
通过command+空格键 输入 snipaste 回车无任何反应，软件打不开
通过启动台找到软件点击，也无任何反应，打不开
通过应用程序找到Snipaste右键选择打开，也无任何反应，打不开

**Comment by oneflyingsun** [comment]
我也是

**Comment by septs** [comment]
@oneflyingsun 进入 `/Applications` 选择到 `Snipaste` 使用 `Control + 单击` 选择 `打开` 试试？

**Comment by leiyuanyi** [comment]
mac os 10.14.5 遇到同样

> @oneflyingsun 进入 `/Applications` 选择到 `Snipaste` 使用 Control + 单击 选择 `打开` 试试？

不行 mac os 10.14.5 遇到同样

**Comment by leiyuanyi** [comment]
> mac os 10.14.5 遇到同样
> 
> > @oneflyingsun 进入 `/Applications` 选择到 `Snipaste` 使用 Control + 单击 选择 `打开` 试试？
> 
> 不行 mac os 10.14.5 遇到同样

重启可以解决
