### ISSUE TITLE
请求在编辑工具栏里增加 清空标注  功能

### ISSUE THREAD

**Issue by currencyporter** [Snipaste/feedback#1191]
请求在编辑工具栏里增加 清空标注  功能:  截图之后,当编辑和标注比较多的时候,如果想重新开始,就有两个方式,一个是疯狂的点撤销;另一个是关掉重新截图. 如果增加一个清空当前截图所有标注的按钮, 那么一键就可以清空了,然后就不需要重新慢慢选择截图范围了.

**Comment by StarryVoid** [comment]
使用 Ctrl + Shift 并点击撤回即可。

**Comment by septs** [comment]
see https://docs.snipaste.com/zh-cn/key-bindings?id=%e9%80%9a%e7%94%a8
