### ISSUE TITLE
在iMac上使用，用妙控鼠标滚轮的时候改变的不是大小，是透明度

### ISSUE THREAD

**Issue by Goodou** [Snipaste/feedback#1193]
首先，配置是iMac（21.5-inch，Late 2015）
系统是macOS Mojave 版本10.14.3
下载的snipasteSnipaste-2.2.0-Beta.dmg，于2019年7月25日
安装过程没有问题，问题在于之后的使用过程中，明明在首选项里面设置了鼠标滚轮放大缩小图片，但是实际操作过程中滚轮改变的是透明度。这个情况怎么解决？

**Comment by liulex** [comment]
触摸设备请使用捏合手势进行缩放。

**Comment by David2k13** [comment]
我也是这个情况

**Comment by liulex** [comment]
比较多人反馈这个问题，下个版本我把“触摸设备滑动手势触发透明度调整”这个设定去掉吧。。

**Comment by Goodou** [comment]
谢谢！

Le Liu <notifications@github.com> 于2019年8月3日周六 下午3:36写道：

**Comment by qq148376839** [comment]
截屏的鼠标按键配置，是否可以加入鼠标右键的配置，现在鼠标右键默认配置的是取消截屏，是否可以像QQ截屏一样，右键可以是弹出功能框【直接右键，可以选择框选、文字、箭头……功能】，因为如果截大图，每次都要移动到角落去找功能按钮，会浪费很多时间，如果右键跟随弹出，会超级方便。【尤其大图很多时候，功能框会根据截图范围，显示在不同角落，鼠标移动的线路很长】

**Comment by qq148376839** [comment]
老版本的mac截图的时候，F3贴图可以在每一个窗口中单独停留，新版本现在是跟随到你当前显示的窗口，这个有没有设置，能选择是否跟随或者停留在贴图界面中。这样会满足不同的场景。
