### ISSUE TITLE
两个小bug

### ISSUE THREAD

**Issue by fwzuw** [Snipaste/feedback#1194]
一、管理员身份运行时无法内购专业版
2333333

二、在首选项面板的
![image](https://user-images.githubusercontent.com/48246272/62006978-8959c900-b17a-11e9-8539-027dd1c10008.png)
鼠标悬浮片刻会在**鼠标下方**出现白底黑字的详细提示
![image](https://user-images.githubusercontent.com/48246272/62006986-9ecef300-b17a-11e9-95e5-50a9f4a1936e.png)
鼠标点击则在**图标右侧**立即出现黑底白字的详细提示
![image](https://user-images.githubusercontent.com/48246272/62007335-ddff4300-b17e-11e9-8480-43d6fe73fd05.png)
问题就出现在这里，如果面板位置偏右，提示信息则会出现在左侧：
![1](https://user-images.githubusercontent.com/48246272/62007012-e8b7d900-b17a-11e9-8394-24b428b9d4b2.gif)
提示信息出现在鼠标下，于是一闪而逝。

**Comment by liulex** [comment]
> 管理员身份运行时无法内购专业版

2.2.1 版本应该已经修复，剩下的无法内购的应该属于非管理员身份都无法购买的，原因未知，见 #1059.

文字提示的颜色其实是有意的……

一闪而逝应该是 Qt 的 bug，无关痛痒，忽略吧。。 😅 

赞细心 👍
