### ISSUE TITLE
希望加入贴图功能可区分多桌面独立显示

### ISSUE THREAD

**Issue by evafeng** [Snipaste/feedback#1196]
有很多场景我需要贴好多张图来回对比，他们会占用大量桌面面积，那么当我再需要访问浏览器或者看其他东西的时候，会造成阻挡，而我并不想销毁这些贴图。可以增加功能让贴图分组显示在win10的某一个多桌面中吗？这样我切换到一个其他桌面去执行其他任务时候就不会遮挡我的工作了。

**Comment by septs** [comment]
see #930
