### ISSUE TITLE
请问能否加入全局快捷键的启停快捷键？

### ISSUE THREAD

**Issue by planningall** [Snipaste/feedback#1198]
目前全局快捷键会用到F1\F2\F3+Shift-Ctrl-Alt

我当然知道可以自定义快捷键，但实际上默认的这几个就很方便，也不想改其他的。但是如果同时使用Total Commander的话，问题就比较大了，F1-F12+Shift-Ctrl-Alt都设置了功能，而且绑定在F1-F8的几个功能都是最常用的，也不想改。

所以能不能提供一个启停全局快捷键的快捷键，比如连按两次Alt，就会启停Snipaste的全局快捷键（连按两次Ctrl已经给Listary了），当然也不局限两次Alt，最好可以自己设置。

**Comment by septs** [comment]
快捷键冲突且用户不想作出相应的修改，
改要求软件修改其设计我觉得不可理喻。

**Comment by planningall** [comment]
这不是快捷键冲突修改的问题，而是更灵活，适应性更强，甚至是谦逊的问题。
大部分监视剪贴板或者浏览器的下载工具，都有很方便的启停设置（比如按alt点击，不使用下载器），这就是很人性化的设计。

Total Commander中的快捷键都是局部的，出了TC不会起作用，但是Snipaste是全局性的，如果启动了Snipaste，又在使用其他程序的时候，Snipaste会和所有使用了F2/F3的程序冲突，这时候是去修改所有其他程序的局部快捷键，还是修改Snipaste的全局快捷键？而且Snipaste的全局快捷键无论怎样设置，总会和其他程序冲突。

既然是全局性的，那应该有一个更谦逊的态度——可以启停。

**Comment by liulex** [comment]
专业版：
![Snipaste](https://user-images.githubusercontent.com/2010459/62138712-af1dd400-b31a-11e9-85c6-14c05567ec5f.png)

**Comment by planningall** [comment]
> 
> 
> 快捷键冲突且用户不想作出相应的修改，
> 改要求软件修改其设计我觉得不可理喻。

“不可理喻”的功能原来在专业版的收费特性里，请问是否打脸？
