### ISSUE TITLE
使用WASD无法微调截图区域

### ISSUE THREAD

**Issue by simon-shaw** [Snipaste/feedback#1199]
使用快捷键F1开始截图，拉取一定范围后，将鼠标移动到任意边缘或者边角，使用WASD任意按键想按像素微调截图范围时，无任何响应，无法微调。
版本：2.2.0-Beta(2019.07.02)

**Comment by liulex** [comment]
WASD 只是移动鼠标位置，如需调整截图区域，请先在截图区域外按住鼠标左键再按 WASD.

**Comment by simon-shaw** [comment]
我是如此操作的，此前一个版本可以用，但更新了这个版本后就无效了

**Comment by liulex** [comment]
2.2 Beta Mac 版好像确实有这个问题，刚更了个版本，应该没问题了。

**Comment by simon-shaw** [comment]
刚更新了2.2.0-Beta2，但问题仍然存在。

**Comment by septs** [comment]
@simon-shaw 请问阁下，在 Windows 还是 macOS 平台使用？

**Comment by simon-shaw** [comment]
@septs macOS Mojave 版本 10.14.5

**Comment by liulex** [comment]
噢，想起来了，跟软件版本没关系，是 macOS 某版本开始，移动鼠标也需要辅助功能权限了。
请到 `系统偏好设置` - `安全性与隐私` - `隐私` - `辅助功能` 移除 Snipaste（如存在）并重新添加。

**Comment by simon-shaw** [comment]
我刚刚找到问题所在了，应该就是你说的这个问题，把勾去掉再勾上就可以了。
