### ISSUE TITLE
[Mac] 无法自动检测界面元素

### ISSUE THREAD

**Issue by Emrys365** [Snipaste/feedback#1200]
* 复现步骤
  * 打开「自动检测窗口」和「自动检测界面元素」选项
  * 并在系统偏好设置到Accessibility中添加Snipaste.app，然后进行截图
* Bug
  * 按下截图快捷键后，会有一段时间无响应，过几秒之后才出现截图界面，如下图所示；并且无法检测到窗口元素
  * 关闭「自动检测窗口」选项之后无响应的问题不再出现
* 其他信息
  * 系统版本：OS X 10.14.6
  * Snipaste版本：2.2.0-Beta (2019.07.02)

![etH3g1.gif](https://s2.ax1x.com/2019/07/31/etH3g1.gif)

**Comment by liulex** [comment]
取消勾选“自动检测元素”再重新勾选，是否还提示需要权限？
可能需要将 Snipast 从辅助权限里移除再重新添加。

**Comment by Emrys365** [comment]
> 取消勾选“自动检测元素”再重新勾选，是否还提示需要权限？

取消勾选再重新勾选的话，并没有再提示需要权限

> 可能需要将 Snipaste 从辅助权限里移除再重新添加。

这个也试过了，还是会出现无响应的问题

**Comment by xem1987** [comment]
* 系统版本：OS X 10.14.6
* Snipaste版本：2.3.3-Beta (2020.04.07)

自动检测窗口设置无效，重新安全辅助授权依然无效

**Comment by brownsugar** [comment]
我也遇到這問題，主螢幕上除了頭部的系統工具列、底部 Dock 列和 Snipaste 配置窗口可以偵測到
外，永遠都只會偵測到中間大塊的螢幕，外接螢幕則可以正常檢測到窗口和窗口內的元素。
OS X 10.15.4、Snipaste 最新版（但前幾個版本就有出現了）

**Comment by liulex** [comment]
@brownsugar 
根据你的描述，应该是主屏上有某个透明的大窗口挡在了最前面。
可以将日志级别调至”追踪“，然后截图使其检测到主屏中间的大窗口，然后打开日志文件查找 `Cursor in window:` ，看检测到是什么窗口。

**Comment by brownsugar** [comment]
@liulex 的確是有個隱藏視窗 `QRect`
```
[2020-04-15 09:33:30.149] [T] Cursor in window: 
[2020-04-15 09:33:30.149] [T]                   QRect(0, 23, 2048 x 1232)
[2020-04-15 09:33:30.149] [T] Go deeper...
[2020-04-15 09:33:30.150] [T] Detected: QRect(0, 23, 2048 x 1232)
```
經過排查後發現是 `LyricsX` 產生的，關閉後就正常了，感謝協助

**Comment by septs** [comment]
> 下个版本会改善窗口检测与其他 app 的兼容性问题。

from #1721

**Comment by liulex** [comment]
Fixed in 2.6.4 Beta.
