### ISSUE TITLE
Mac 截图漂移

### ISSUE THREAD

**Issue by michensy** [Snipaste/feedback#1201]
## 设备

* 操作系统 10.14.3 (18D42)
* 使用鼠标截图（罗技G502 Wireless）
* 显示器（U2718QM DELL 4K）使用缩放HDPI 1080P分辨率

## 问题重现

间歇性出现按下截图键（command + f1）并使用鼠标选取截图区域
截图选择区域动作速度异常缓慢，明显和鼠标速度不符合
具体表现为：鼠标已经停止选择区域，屏幕中的选择框仍在持续选择区域，期间窗口已经锁死在截图界面什么都做不了，只能等待截图结束。

## 期望

能够同步鼠标速度进行截图

**Comment by michensy** [comment]
Snipaste版本：2.2.0-Beta(2019.07.02)

**Comment by liulex** [comment]
只是间歇性的话，可能需要找到重现条件才好排查……
