### ISSUE TITLE
关于 homebrew-cask 版本问题

### ISSUE THREAD

**Issue by iiiuo** [Snipaste/feedback#1206]
目前 brew cask 中版本停留在 1.16.2-Beta，请问什么时候会提交新版本？

**Comment by septs** [comment]
关于 Homebrew cask 中的 Snipaste 并不是又第一方维护的
https://github.com/Homebrew/homebrew-cask/pulls?q=is%3Apr+snipaste+is%3Aclosed

**Comment by liulex** [comment]
brew cask 上已更新。
