### ISSUE TITLE
Mac无法安装

### ISSUE THREAD

**Issue by JohnJobs0822** [Snipaste/feedback#1208]
Mac无法安装Snipaste-2.2.0-Beta2版本，打开之后会告知“此软件需要更新。请联系开发者来了解更多信息。”

**Comment by JohnJobs0822** [comment]
> Mac无法安装Snipaste-2.2.0-Beta2版本，打开之后会告知“此软件需要更新。请联系开发者来了解更多信息。”

**Comment by wondervendor** [comment]
同样的问题这里
Mac mojava 10.14.5

**Comment by Dev-Wiki** [comment]
无法打开了
