### ISSUE TITLE
在不同DPI的屏幕之间切换时，界面缩放不正确

### ISSUE THREAD

**Issue by MapleRecall** [Snipaste/feedback#1212]
当有两个不同DPI的显示器时，大部分界面元素会按照启动时所在的屏幕DPI进行渲染，如果这时候切换到另一个缩放设置不同的显示器，界面元素不能自适应。比较常见的场景是，4K高分辨率笔记本外接1080P或2K的显示器，或者台式机同时接1080P和4K的显示器。

![image](https://user-images.githubusercontent.com/18360825/62654884-6b1e7500-b993-11e9-98d6-37f8f8146a52.png)

如图所示，设置窗、截图的控制点，工具条都是按照高DPI进行渲染的，在另一个屏幕上十分巨大……

![image](https://user-images.githubusercontent.com/18360825/62655623-f4827700-b994-11e9-8480-6554b149a02c.png)

这是一个相反的例子，我在低分辨率的屏幕上重新打开了Snipaste，在高分辨率屏幕上截图，这些东西都变的十分小~~巧可爱~~。

不过取色的悬浮窗是正常的，在两个屏幕之间切换的时候会按照正确的DPI进行渲染。文字也会正常自适应，但配上不会自适应的其它元素造成了更糟糕的结果……

**Comment by septs** [comment]
Windows 本身对于多 DPI 的处理和实现，这是已知问题
包括微软自家很多软件也无法处理多 DPI 下的使用

**Comment by liulex** [comment]
@MapleRecall 观察很细致 👍 
确实取色窗口做过特别处理，会自动适配当前屏幕的 DPI，因为这个窗口比较简单……
其他窗口的大小问题就不好解决了，但下个版本会修复跨 DPI 移动选项窗口后界面元素挤在一起的问题。

**Comment by liulex** [comment]
@MapleRecall 
之前一些版本已经针对不同 DPI 的屏幕做了不少适配，请问现在是否还有界面缩放不正确的窗口？
