### ISSUE TITLE
为什么箭头的那么细，完全看不出哪里是头

### ISSUE THREAD

**Issue by 812865052** [Snipaste/feedback#1216]
mac Snipaste-2.2.0-Beta2 为什么箭头那么细呢 应该是某个版本更新后变成这样，以前我记得是自己可以调整粗细的
![image](https://user-images.githubusercontent.com/12646048/62777014-cb6dfd80-bade-11e9-9ead-09be11fd53d6.png)

**Comment by ShaneQi** [comment]
请问你尝试过使用数字键 1 和 2 来调整大小吗？
