### ISSUE TITLE
贴图默认格式是png,无法修改为jpg,造成笔记很大

### ISSUE THREAD

**Issue by king0205** [Snipaste/feedback#1218]
截图后粘贴到笔记本word文档，贴图都是png，很小一张都500k，其实这些图片也是展示一下，不过份追求质量，这样造成粘贴到印象笔记的文件都特别大，有些笔记要整理200张图，就80多M，常常笔记本假死，同步也花时间。希望可以贴图，可以控制贴图大小，谢谢！

**Comment by septs** [comment]
在 Microsoft Office 中缩减图片的文件大小
<https://support.office.com/zh-cn/article/8db7211c-d958-457c-babd-194109eb9535>

另外 Microsoft Word 支持在保存时选择压缩图片的方法
![image](https://user-images.githubusercontent.com/3842474/62815914-3c023200-bb52-11e9-955b-f8905c324ef0.png)

**Comment by king0205** [comment]
那印象笔记还是不可以

**Comment by septs** [comment]
这是上游的问题，阁下不应当吧上游的实现不当给下游通过降低质量的方法来处置。

**Comment by king0205** [comment]
好的，谢谢回复

**Comment by septs** [comment]
关于 Evernote 官方对于压缩方面的话题只字未提
https://www.google.com/search?q=%22compress%22+site%3Ahelp.evernote.com

关于 Evernote 大笔记本的压缩/优化方法第一方也未作出表态
https://discussion.evernote.com/topic/89461-database-approaching-10gb-any-way-to-compressoptimize-this/
