### ISSUE TITLE
希望增加图片停靠功能，类似QQ自动缩回

### ISSUE THREAD

**Issue by ryegalaxy** [Snipaste/feedback#1219]
我用Snipaste来看文章，做好的贴图只是偶尔需要看一眼，所以能否增加图片停靠功能，类似QQ的自动隐藏，右键贴图可以选择勾上 停靠 ，这样图片放在屏幕边缘能自动缩进去，鼠标放过去的时候能自动伸出来，不需要手动拉来拉去。

**Comment by liulex** [comment]
专业版有触发角功能，我认为已经可以解决贴图档桌面的问题，不需要屏幕边缘的停靠功能。
