### ISSUE TITLE
大BUG：贴图功能只能保存最后一张截图

### ISSUE THREAD

**Issue by indomalex** [Snipaste/feedback#1220]
1. 连续截图两张或以上，比如按顺序依次截图A，截图B，截图C
2. 多次按F3贴图出来，发现只有C。截图AB无法贴出来
————除非截图A，按F3贴图一次；再截图B，按F3贴图一次；再截图C，按F3贴图一次，才会ABC都保存到贴图

**Comment by StarryVoid** [comment]
截图A，确认截图，默认自动将截图复制到剪贴板
截图B，确认截图，默认自动将截图复制到剪贴板，覆盖A
截图C，确认截图，默认自动将截图复制到剪贴板，覆盖B
贴图，从剪贴板获取图片，得到图片C，贴出。

现象符合操作

提出issues前建议自行检查操作逻辑并确认此逻辑是否正确

**Comment by Riajyuu** [comment]
这可能是一个 feature request
从截图历史记录当中贴出贴图
（确信

**Comment by septs** [comment]
根据陈述，本问题只是于题主期望不符

题主陈述的逻辑在整体逻辑上不成立且存在缺陷
此缺陷指对于剪贴板中的外部修改行为造成的逻辑应当如何处置
