### ISSUE TITLE
这个软件为什么越来越卡了

### ISSUE THREAD

**Issue by shen-lan** [Snipaste/feedback#1221]
两年前用的时候，截图几乎是秒截。
现在很多时候，快捷键按下到响应，大概2秒左右。（PS: 现在的电脑比两年前配置高不少）
贴图的时候有时巨卡，基本没法用。
有时宁愿打开聊天工具截图，也不用这个了。

这是个别案例还是怎么回事，大家有遇到吗😭
个人使用的核心功能就是截图+贴图。
![indexxxx9](https://user-images.githubusercontent.com/21122615/63084567-0c05c500-bf7e-11e9-8264-7208df091779.png)

**Comment by septs** [comment]
请合并至 #498 进一步讨论
并附上阁下当前的

- Snipaste 版本信息
- Snipaste 日志文件（`splog.txt`）
- 被截图的目标软件名字
- 受截图区域

等信息其他，以方便作者对于阁下的问题进行分析

**Comment by septs** [comment]
如果阁下 Snipaste 不是 2.2.0 请升级后验证并报告
历史版本问题一般不会予以处置
