### ISSUE TITLE
建议增加任务栏快捷图标

### ISSUE THREAD

**Issue by lucifersun** [Snipaste/feedback#1224]
一般情况下，都是通过任务栏通知区域图标来调用snipaste，但Win10在双显示屏环境下就会碰到一些操作问题。
由于通知区域仅在主显示器上显示，如果当时鼠标正好在次显示器区域内，就必须移回主显示，如果双屏布局为右主左辅，那鼠标的移动距离就会非常大。
暂时只能自建一个调用Snipaste.exe snip的快捷图标，吸附于任务栏上，如此就能在双屏范围内任意操作。但Snipaste.exe snip的调用一直不太顺利，经常要点击多次才能正常激发。而且只能实现一种操作，无法通过右键菜单实现更多功能。
如果能原生提供一个可自定义的快捷图标，直接吸附于任务栏，那就会非常便利了。

**Comment by septs** [comment]
既有方法已经可以使得您 workaround 了，
那么我认为第一方无需提供原生实现。

即使第一方提供，也请耐心等待其他用户的共同诉求推进。

**Comment by liulex** [comment]
`Snipaste.exe show-tray-menu`

**Comment by Saafo** [comment]
为什么不把快捷键替换成printscreen呢.....

**Comment by lucifersun** [comment]
> 
> 
> 为什么不把快捷键替换成printscreen呢.....

笔记本键盘，print screen键是通过组合键实现的，而且两个按键分别在左下和右上，跨度将近25cm……

**Comment by septs** [comment]
@lucifersun 请使用 专业版 提供的 超级截图 功能
https://docs.snipaste.com/zh-cn/pro
