### ISSUE TITLE
为什么snipaste不增添一个打开本地图片然后编辑的功能？

### ISSUE THREAD

**Issue by waybing** [Snipaste/feedback#1229]
snipaste这个良心软件真的惊艳到我了。
大家都知道他的截图和贴图都爽得不行，
然后我想说的是他的简易编辑功能我也超级喜欢啊，可以截图图片马上进行一些简单的编辑，增加注释或者标识重点区域（我就最爱这种轻便）。并不喜欢那种重量级
但是有时候日常在操作的时候，一个手欠点了保存，那么这时候这个截图就成了本地的图片了，大哥，我还没编辑完，于是我们想重新永snipaste来进行编辑的时候，我竟发现snipaste没有打开本地图片的功能啊。
我们要怎样才能用sinpaste来编辑本地图片呢？

**Comment by septs** [comment]
see #16

**Comment by KazamaSion** [comment]
Ctrl+C 图片文件。
然后按下贴图快捷键。
完毕。
