### ISSUE TITLE
添加功能

### ISSUE THREAD

**Issue by leaves1996** [Snipaste/feedback#1230]
对于开发人员，这款软件真是太实用了，但是我希望作者能否对这款软件添加一项功能，能够对屏幕中的任意颜色取色，使用快捷键快速取色，取色成功后，弹出各项数据的颜色数据界面，如下，这只是我个人的建议，谢谢！
![image](https://user-images.githubusercontent.com/53463205/63734783-30cc3780-c8b0-11e9-8c9a-5f6bdd389410.png)

**Comment by septs** [comment]
根据您的陈述，您需要不处于 **截图** 状态下取色并呈现。
因此我认为您的诉求与 Snipaste 设计目标（**截图** 并 **贴图**）不符。

**Comment by liulex** [comment]
截图时按 <kbd>C</kbd> 取色，是 `能够对屏幕中的任意颜色取色`；再按贴图键，是 `各项数据的颜色数据界面`：

![Snipastse_color_card](https://user-images.githubusercontent.com/2010459/64924210-9018ca00-d814-11e9-8981-375976bd75d4.png)

**Comment by septs** [comment]
Duplicate of #419
