### ISSUE TITLE
IntelliJ IDEA复制的代码贴图后{()}等括号字体为斜体,代码字体正常

### ISSUE THREAD

**Issue by xy-ly** [Snipaste/feedback#1232]
希望可以得到解决,字体尝试了Microsoft YaHei UI等常见字体, 括号问题也没能解决,英文字体也不行, 希望可以推荐一个能正常括号显示的字体或者解决一下这个问题
系统:win10专业版1903
Snipaste:2.2.1-Beta2(2019.07.05)(以前版本好像也不可以, 但是以前没注意过这个问题)

**Comment by StarryVoid** [comment]
建议检查 IntelliJ IDEA 复制的代码格式是否为 html 格式 或者其他特殊格式，而不是纯文本格式。
snipaste会根据剪贴板中的文字数据格式而处理显示不同的效果。

**Comment by liulex** [comment]
Out of scope.
