### ISSUE TITLE
建议增加对图片进行二值化的操作功能

### ISSUE THREAD

**Issue by XHuang304** [Snipaste/feedback#1233]
建议可以对截取的贴图增加二值化（或选色）的功能；
具体思路可以是选完区域之后，通过快捷键启动功能，二值化阈值可以在图中取色设定，也可以通过唤出RGB输入窗口进行设置，最终保存成为二值化之后的黑白图；
应用背景：复杂背景下的文字截取/优化

**Comment by StarryVoid** [comment]
使用条件为特殊场景的需求不建议增加，更建议使用snipaste命令行配合其他程序接口处理。
