### ISSUE TITLE
发现一个很奇葩的问题

### ISSUE THREAD

**Issue by artoostark** [Snipaste/feedback#1234]
打开软件后，我键盘的 m 键就失效了，换键盘也没用。

**Comment by loguu** [comment]
看一下你是不是奇葩地把 m 键设到全局快捷键了？

**Comment by artoostark** [comment]
> 看一下你是不是奇葩地把 m 键设到全局快捷键了？

日，还真是。我为此专门买了个 IKBC 的新键盘。
