### ISSUE TITLE
贴图的标注工具配置与截图的标注工具配置不同步

### ISSUE THREAD

**Issue by Delete56** [Snipaste/feedback#1235]
截图下的标注工具配置好标注颜色及粗细后，在贴图中继续进行标注时标注工具的颜色及规格总是默认配置，希望能够改进。
系统：Windows 10 1903    
版本：微软商店 专业版 V2.2.1

**Comment by StarryVoid** [comment]
截图 和 贴图组 之间不共享同样的工具条参数配置。这是一个特性。

**Comment by Delete56** [comment]
> 截图 和 贴图组 之间不共享同样的工具条参数配置。这是一个特性。

可是每次在贴图中修改了标注工具的特性之后都不会保存配置，下次再标注时还会恢复默认设置，这点感觉可以改进一下。

**Comment by liulex** [comment]
那现在这个贴图用蓝色画笔，那个贴图用绿色画笔，下次新贴图的标注我不用默认配置用哪个呢？
