### ISSUE TITLE
截图会自动开启win10的夜光选项

### ISSUE THREAD

**Issue by zhangqi-chen** [Snipaste/feedback#1239]
按截图键会开启win10的夜光再进行截图，是bug还是我哪里设置出错了？
![image](https://user-images.githubusercontent.com/11281159/64483334-9dd9b880-d232-11e9-9eaf-a2d961afff6b.png)

**Comment by liulex** [comment]
win10 的夜间模式不会影响截图，你这是开了哪个第三方软件的护眼模式。。

**Comment by zhangqi-chen** [comment]
> win10 的夜间模式不会影响截图，你这是开了哪个第三方软件的护眼模式。。

谢谢，发现了是lenovo的管理软件作的妖。已解决

**Comment by fayeyuan** [comment]
#1240 所以有可能是什么造成的呢？

**Comment by Jinding-X** [comment]
想请教一下，怎么解决的呢？我也有同样的情况

**Comment by zhangqi-chen** [comment]
Lenovo Vantage 这个页面把护眼功能关掉，色温拉到最大。snipaste截图时的色温对应的就是这个色温，不知道snipaste启动时为什么会启动这个护眼功能，即使已经关掉了。
![image](https://user-images.githubusercontent.com/11281159/64579313-0f417480-d3b5-11e9-921f-6a298439143c.png)

**Comment by Jinding-X** [comment]
感恩！！！已经解决问题了。谢谢！！！

**Comment by liulex** [comment]
> 不知道snipaste启动时为什么会启动这个护眼功能，即使已经关掉了

请不要下这样的结论，我说过这个跟 Snipaste 无关，你用其他工具截图也是一样的。

**Comment by lkccccc5** [comment]
找不到在哪儿设置呀
![image](https://user-images.githubusercontent.com/46130406/77247963-e6a60b80-6c70-11ea-9c2f-e1d449db153d.png)
我的只有这个

**Comment by lkccccc5** [comment]
> 找不到在哪儿设置呀 我的只有这个
> ![图片](https://user-images.githubusercontent.com/46130406/77247963-e6a60b80-6c70-11ea-9c2f-e1d449db153d.png)

![image](https://user-images.githubusercontent.com/46130406/77336693-dc643a00-6d62-11ea-956d-72107799f20a.png)
这样可以解决

**Comment by gao5** [comment]
解决了，确实是护眼软件的问题，开启了IRIS

**Comment by koppor** [comment]
For the googlers not being fluent in Chinese - and googling for "f.lux snipaste", this is the option to active:

![grafik](https://user-images.githubusercontent.com/1366654/140176089-493b0467-682a-4769-8aae-4c247817f442.png)

**Comment by CharlesSong** [comment]
我是联想zone选择了独显导致的，关闭独显就没事了。
