### ISSUE TITLE
截屏时一直有#ffdbba颜色的半透明红色遮罩效果

### ISSUE THREAD

**Issue by fayeyuan** [Snipaste/feedback#1240]
截屏时一直有#ffdbba颜色的半透明遮罩效果，如下所示。
https://user-images.githubusercontent.com/14072862/64484039-3b3ae980-d23f-11e9-8682-aec5467b296a.png
![image](https://user-images.githubusercontent.com/14072862/64484039-3b3ae980-d23f-11e9-8682-aec5467b296a.png)

保存图片，或者贴图均有。
尝试卸载，或者重启，依旧有透红色效果。
应如何恢复成原色？

**Comment by liulex** [comment]
跟 Snipaste 无关，#1239

**Comment by Jinding-X** [comment]
请教一下怎么解决的呀？研究了好久都没有搞定。
