### ISSUE TITLE
剑网叁网游截图闪屏、黑屏、缺少游戏内UI

### ISSUE THREAD

**Issue by ChuHuaiJin** [Snipaste/feedback#1241]
在剑网叁网游内使用常规的截图功能时会频繁出现以下问题
1.频繁出现截图游戏画面的出现黑屏现象，截图出来的图片也是黑色图片。
2.频繁出现截图游戏画面的屏幕闪烁一次的现象
3.频繁出现截图游戏画面的时候只截取到3D场景和人物，游戏的UI界面缺失，截图出来的图片也是缺少游戏的UI界面。

游戏以窗口模式最大化运行

想要正常截图，需要多次尝试截图才可以完成。

**Comment by StarryVoid** [comment]
Snipaste 不能在 DX9/DX11等游戏界面中截图。
你实际截图的是，Windows对窗口的预览

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/282#issuecomment-268239624
