### ISSUE TITLE
MAC 版截图时闪屏

### ISSUE THREAD

**Issue by suyanhanx** [Snipaste/feedback#1242]
macOS 上拖动截屏时，不在截屏范围内的遮罩层闪得厉害。此前版本没有这种情况。

**Comment by liulex** [comment]
录屏说明一下？

**Comment by suyanhanx** [comment]
https://b23.tv/av68137349
视频已上传。好像双屏的时候会发生这个情况，但一个时段里只会在一个屏上发生，换个屏重新截图就不会闪。

**Comment by suyanhanx** [comment]
版本号：2.2.0-Beta2(2019.08.03)
系统：macOS 10.14.5

**Comment by liulex** [comment]
谢谢，我了解是怎样的情况了，请问有确定的重现步骤吗？

**Comment by suyanhanx** [comment]
好像没有特定的重现步骤，基本上一截图就会这样

**Comment by zhangzq644** [comment]
有进一步的解决办法了吗，我有遇到同样的问题，截图时会一直闪屏，除非换截图工具
