### ISSUE TITLE
MAC 版在 keynote 全屏播放下截图屏幕会卡住

### ISSUE THREAD

**Issue by pdsuwwz** [Snipaste/feedback#1244]
* MAC 版 在使用 keynote 幻灯片全屏播放后，按组合键「fn + F1」截图时，鼠标和整个页面会卡住，只有再点击一下鼠标或触摸板后才会出现截图的十字线，望修复。

**Comment by liulex** [comment]
谢谢反馈，确实有这个问题，我想想办法。
