### ISSUE TITLE
针对Mac版，什么时候能添加windows中的这个功能--对图像标记时的线条粗细可以选择

### ISSUE THREAD

**Issue by marginqm** [Snipaste/feedback#1245]
截图对图像进行标记时的线条粗细是可以自信选择的，在windows中可以选择三种不一样粗细的线条进行标记，而在Mac中只存在一种默认的细线条进行标记，如果说在Mac中也同样的功能，那么将会更人性化。

现在Mac版中是不存在该功能的，所以很多时候截图还是用的微信的截图功能。

**Comment by liulex** [comment]
那个“默认的细线条”上应该有个小红点，点一下试试呢？

**Comment by guoshuai93** [comment]
控制画笔粗细的功能早就有啦。1 减小，2 增加或鼠标滚轮控制
