### ISSUE TITLE
能否提供屏幕取色器功能？在截图的界面提供取色按钮。

### ISSUE THREAD

**Issue by waihoyu** [Snipaste/feedback#1248]

**Comment by waihoyu** [comment]
1）是否可以提供屏幕取色器功能？
2）Snipaste设置自动开机后，360杀毒软件的清理功能会把Snipaste的随系统启动关闭掉。是否可以把Snipaste设为window后台服务呢？

**Comment by diauweb** [comment]
什么是*取色器*功能？如果说要获取并复制屏幕上任意像素点的颜色请按C键。

**Comment by caiwanxi** [comment]
### 按住shift 切换色值RGB/HEX
**和截图时一样，放大镜可见时按 C 可复制当前像素点的颜色值**
官方基本操作链接：[](https://docs.snipaste.com/zh-cn/getting-started)

**Comment by linzyjx** [comment]
@waihoyu 关于自启问题，请寻找下360是否有提供相关功能的白名单。若没有建议卸载360。

**Comment by waihoyu** [comment]
好的，感谢回复，我已经明白了，非常感谢。

**Comment by caiwanxi** [comment]
### 你可以使用**[火绒](https://www.huorong.cn/)**
@waihoyu 
360安全防卫，过时了，而且笨重。
火绒很多人用，安静好用。很多人用的。评价可以自己搜索

**Comment by waihoyu** [comment]
> ### 你可以使用**[火绒](https://www.huorong.cn/)**
> @waihoyu
> 360安全防卫，过时了，而且笨重。
> 火绒很多人用，安静好用。很多人用的。评价可以自己搜索

好的，非常感谢。
