### ISSUE TITLE
回放模式下重新截图总显示边框

### ISSUE THREAD

**Issue by YueLengM** [Snipaste/feedback#1249]
在`回放模式`下，重新截图时不论有没有选区总是会显示边框（会导致遮挡，看不清光标周围）。
![Snipaste_2019-09-14_21-06-43](https://user-images.githubusercontent.com/11801894/64908519-e104c180-d733-11e9-8afc-dad0447e28a4.jpg)

应该是产生了一个 `1 x 1` 大小的截图选区，并且跟随鼠标导致的。

**Comment by StarryVoid** [comment]
选项设置，截屏，在放大镜中 显示， 取消勾选三个选项即可。

**Comment by YueLengM** [comment]
> 选项设置，截屏，在放大镜中 显示， 取消勾选三个选项即可。

虽然这个确实解决了遮挡问题。但仔细想了下，产生这个问题的不是放大镜本身，而是边框，抱歉没说清楚。

**Comment by liulex** [comment]
回放模式下的 "1x1" 确实没有考虑到，下个版本会修复，谢谢！
