### ISSUE TITLE
[功能需求]二维码识别

### ISSUE THREAD

**Issue by KaminoDice** [Snipaste/feedback#1251]
能不能添加对截图内的二维码解码的功能？
有些情况下不方便用移动设备扫码，截图后再上传的在线解码网站也很麻烦。
如果Snipaste能直接对截图区域里的二维码解码就好了

**Comment by jjeejj** [comment]
@KaminoDice  那我就想截带有二维码的图怎么办呢？ 比如微信公众号登录的时候，需要截取登录的二维码让管理员是扫描的，还有一种二维码识别一次就会失效的

截图功能我感觉还是做得纯粹点好些
