### ISSUE TITLE
马赛克的功能可以给选定区域外的部分打马

### ISSUE THREAD

**Issue by leigegeok** [Snipaste/feedback#1253]
马赛克的功能可以给**选定区域外**的部分打马
如下图**红色标记区域**所示
![报错](https://user-images.githubusercontent.com/22673254/65009758-6bba0c00-d940-11e9-8a64-b0d430e604d7.png)
我不知道这是不是一个BUG，或许是你们故意这么设计的。
本人使用的是win10系统

**Comment by liulex** [comment]
是这么设计的。

**Comment by leigegeok** [comment]
好的，谢谢 
------------------
 
 Thanks and best regards 
  TSL  
 Email：TSL_LIULEI@QQ.COM 
 
 

 




------------------ 原始邮件 ------------------
发件人: "Le Liu"<notifications@github.com>; 
发送时间: 2019年9月25日(星期三) 晚上11:06
收件人: "Snipaste/feedback"<feedback@noreply.github.com>; 
抄送: "刘  磊"<1399217364@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Snipaste/feedback] 马赛克的功能可以给选定区域外的部分打马 (#1253)




是这么设计的。
 
&mdash;
