### ISSUE TITLE
Mac 版的 悬浮工具条太小了 操作起来不方便

### ISSUE THREAD

**Issue by zl939144892** [Snipaste/feedback#1254]
Mac 版的 悬浮工具条太小了 操作起来不方便

**Comment by liulex** [comment]
那么期望多大呢？

**Comment by zl939144892** [comment]
27*27看起来不错, 仅供参考...
![image](https://user-images.githubusercontent.com/18364560/65651074-d9042600-e03f-11e9-8d98-064f5b5341ef.png)

**Comment by zl939144892** [comment]
比现在稍微大一些就很好
