### ISSUE TITLE
窗口隐藏问题

### ISSUE THREAD

**Issue by VaguelyCloud** [Snipaste/feedback#1256]
mac 版本（开启 qq 之后会），唤起截屏会出现 所有窗口隐藏问题，只能截取到桌面，后来发现在安全与隐私里面，屏幕录授权开启后正常。

**Comment by liulex** [comment]
[截图时只显示了桌面](https://docs.snipaste.com/zh-cn/troubleshooting?id=%E6%88%AA%E5%9B%BE%E6%97%B6%E5%8F%AA%E6%98%BE%E7%A4%BA%E4%BA%86%E6%A1%8C%E9%9D%A2)
