### ISSUE TITLE
开机自启动之后第一次超级截图会卡屏闪退

### ISSUE THREAD

**Issue by Delete56** [Snipaste/feedback#1260]
最新微软商店2.2.2.0专业版，windows10 1903系统。
每次开机后第一次截图时使用超级截图会卡屏闪退，采用常规截图方式截图之后再采用超级截图可以正常使用。
[splog.txt](https://tinyurl.com/y5vy4ryx)

**Comment by liulex** [comment]
感谢反馈，已修复，近日会更新。
