### ISSUE TITLE
希望增加类似hypersnap的徒手捕捉

### ISSUE THREAD

**Issue by sscanfer** [Snipaste/feedback#1265]
希望增加类似hypersnap的徒手捕捉，有时候截屏的形状并不一定规则，有些内容不想截进去，打马赛克又影响美观。所以希望增加徒手捕捉，通过鼠标点击确定区域
![IMG_20190930_103030](https://user-images.githubusercontent.com/26719026/65845626-8d1ded80-e36d-11e9-8411-5d00b7f18e34.jpg)

**Comment by Geeyun-JY3** [comment]
重复：#1066

**Comment by Geeyun-JY3** [comment]
Duplicate of #1066
