### ISSUE TITLE
如果能增加OCR截屏翻译那就更棒了

### ISSUE THREAD

**Issue by Fist9** [Snipaste/feedback#1269]
这个功能经常会用到，只有有道词典的OCR截屏翻译比较好用。
如果说Snipaste有这项功能那就太棒了！
OCR截屏，使用谷歌翻译接口在屏幕上实时翻译文字，想想都兴奋。

**Comment by kofmj** [comment]
我也支持...最好可以自定义翻译接口，然后支持翻译后贴图。完美了！

**Comment by qq148376839** [comment]
qq的OCR很棒

**Comment by T-Curiosity** [comment]
+1 希望能出这个功能

**Comment by m4XEp1** [comment]
这到底是截图工具还是翻译工具？

**Comment by valuex** [comment]
最近用上天若OCR了，这个软件就是截图+OCR的功能。
@liulex 希望考虑下软件的接口功能，提供一些二次开发接口，包含输入和输出两方面。
输入：个人之前提到的截图带标题，这个本质上就是截图+输入的文本信息
输出：类似于这个issue提到的，截图内容往后流转的处理

**Comment by liulex** [comment]
@valuex 下个版本会提供命令行接口，将截图文件传到第三方程序。
至于截图标题，实际也是输出接口，第三方程序拿到截图之后另存为指定名字就好了。

**Comment by leigegeok** [comment]
虽然没有翻译的需求，但是文字提取功能的需求还是有

**Comment by bigtaotao2** [comment]
附议，截图ocr这个功能很多时候用到

**Comment by septs** [comment]
Duplicate of #188

**Comment by jiaobi2334** [comment]
2024年了，希望能接入OCR和翻译的功能，在Windows下使用Snipaste全面替代Mac的Bob

**Comment by joeljhou** [comment]
> 2024年了，希望能接入OCR和翻译的功能，在Windows下使用Snipaste全面替代Mac的Bob

是呀，提供一些入门的文档，让开发者二次开发就行

**Comment by you-hengh** [comment]
@jiaobi2334 @joeljhou 已经不强求了, 用专门的软件 比如 [pot](https://github.com/pot-app/pot-desktop) 或者ttime什么的 截图软件就干点截图软件的事情吧

**Comment by YICHENG-A** [comment]
微信的截图翻译和文字提取确实很方便，但是我还是喜欢snipaste这款工具，工作上为我提升不少效率！希望开发者能集成这两个功能！支持！！

**Comment by mofengcangyue** [comment]
参考天若ocr
