### ISSUE TITLE
希望增加条形码，二维码识别以及输出功能

### ISSUE THREAD

**Issue by DancingDolphins** [Snipaste/feedback#1270]
应该不是非常麻烦的功能，三方的开源代码也很多。
1具体的操作逻辑也是圈选，然后识别。并且放置到剪贴板或者图库中。
2在图片编辑模式。可以输出一张条形码或者二维码的图片。

**Comment by imliaojincheng** [comment]
在电脑上识别二维码一直都很麻烦，截图工具正好可以快速的获取图片，真心希望能加入识别二维码的功能。

**Comment by leigegeok** [comment]
虽然我有一个精简的软件可以识别二维码，但是我更希望你们能把这个功能加进来，建议参考http://www.psytec.co.jp/

**Comment by septs** [comment]
Duplicate of #23
