### ISSUE TITLE
Pressing Ctrl-C in Snip does nothing

### ISSUE THREAD

**Issue by bilogic** [Snipaste/feedback#1271]
您好

当我Snip过候，按Ctrl-C要复制到clipboard时，Snipaste没反应，保留在Snip里头。
可是，右下角明明有个```Copy to clipboard (Ctrl-C)```。

不知和 #689 有没有关系。

请麻烦解决，谢谢！

**Comment by liulex** [comment]
正如 #689 所描述的一样，由于键盘布局问题导致 <kbd>Ctrl-C</kbd> 未响应的问题早在 1.16 就解决了。
请问你的 Snipaste 软件版本以及所使用的键盘布局？

**Comment by bilogic** [comment]
Snipaste软件版本是2.2.1-Beta2
我用的是英文键盘
![image](https://user-images.githubusercontent.com/946010/66283890-d9ca7100-e8f7-11e9-8472-bc67bb7aafe8.png)

**Comment by bilogic** [comment]
刚式了Snipaset 1.16.2也一样

**Comment by liulex** [comment]
应该是使用了什么模拟鼠标按键的软件？Snipaste 默认会屏蔽这类按键，相关讨论：#210

**Comment by bilogic** [comment]
我是有用AHK，但关了耶不行。Snipaste之前用的是Lightshot，<kbd>Ctrl</kbd>+<kbd>C</kbd>，没问题。其实在我所有的软件里都能<kbd>Ctrl</kbd>+<kbd>C</kbd>

**Comment by bilogic** [comment]
奇怪的是，Snip时，<kbd>Ctrl</kbd>+<kbd>S</kbd>，能操作哦。

**Comment by liulex** [comment]
不一定是 AHK. #210 有说怎么关闭 Snipaste 的这个行为。

**Comment by bilogic** [comment]
Yes, now <kbd>Ctrl</kbd>+<kbd>C</kbd> is working fine! Added ```do_not_omit_synthesized_c=true``` to ```config.ini```. Thank you!
