### ISSUE TITLE
快捷键保存后无法手动退出

### ISSUE THREAD

**Issue by luanzun** [Snipaste/feedback#1272]
系统：win10 190921
版本：商店版，2.2.2.0
操作顺序：F1 → R → ctrl+s 
问题：保存文件后，不管是按 esc，还是双击，还是任何操作，都没有任何反应。反复测试后，保存文件后，无论是否有其它操作，只要等待差不多4秒左右会，会自动退出。
日志：[splog.txt](https://github.com/Snipaste/feedback/files/3702611/splog.txt)

这是bug，还是软件本身的设置就如此？或者是我电脑问题？

**Comment by liulex** [comment]
从日志来看，Ctrl+S 之后，你从托盘图标右键菜单选择了“重新启动”。
