### ISSUE TITLE
严重bug，Mac升级到Catalina版本后，截屏之后保存在桌面时，系统卡死。

### ISSUE THREAD

**Issue by z2215590117** [Snipaste/feedback#1273]
严重bug，Mac升级到Catalina版本后，使用snipaste截屏 -> 将截图保存在桌面时，系统卡死。

**Comment by oott123** [comment]
试试在设置->安全性与隐私->完全磁盘访问权限这里加入 Snipaste，会不会好呢？我猜的（

**Comment by z2215590117** [comment]
> 试试在设置->安全性与隐私->完全磁盘访问权限这里加入 Snipaste，会不会好呢？我猜的（
不敢再试了，昨天调试了2，3次，都是这样，]第一次在Mac上碰到这种问题。想直接杀死进程，终端都打不开。只能强制关机。实在无奈，又重新下载了snip.

**Comment by taolive** [comment]
> 试试在设置->安全性与隐私->完全磁盘访问权限这里加入 Snipaste，会不会好呢？我猜的（

尝试过了，还是无法启动

**Comment by z2215590117** [comment]
> 要赋予Snipaste 桌面的访问权限，卡死是因为有个弹窗导致的

您升级到Catalina版本了吗？问题有解决吗？我这边还不行，用Xnip了。

**Comment by kookxiang** [comment]
Catalina 在每个程序第一次访问特殊目录（桌面、文稿、下载等）的时候会要求用户手动确认，只是这个对话框被挡住了
你可以在另一个虚拟桌面点下允许或者在 系统设置 -> 安全性和隐私 -> 隐私 -> 完全磁盘访问权限 添加 Snipaste 全部放开
当然更简单的办法是不要存到这些特殊目录

**Comment by oott123** [comment]
既然只是弹窗被挡住，也请遇到这个问题的人试试先贴图，再保存吧

**Comment by HuberyHuV1** [comment]
> > 要赋予Snipaste 桌面的访问权限，卡死是因为有个弹窗导致的
> 
> 您升级到Catalina版本了吗？问题有解决吗？我这边还不行，用Xnip了。

楼下已经做了说明，试一下吧，，或者进安全模式看看弹窗是否能看到，这个弹窗只是被挡住了，或者在桌面截图看看能不能看到这个弹框

**Comment by Teemwu** [comment]
安装前来issues看了下，留意到这条，但没点进来，用了之后果然奔溃了。。。按照 @kookxiang 的方法设置，可以正常保存了，不过还有点小问题，保存时点击选择保存文件路径时，文件夹路径选择弹窗经常闪一下又消失了

**Comment by m4XEp1** [comment]
在完全磁盘访问权限里把 Snipaste 添加进去，即可解决

**Comment by huaikitty** [comment]
同样死机了.....添加完全磁盘访问可以解决.但是不想这么放权.
建议新版更新个权限校检

**Comment by liulex** [comment]
下个版本解决此问题，同时无需完全磁盘访问权限。
