### ISSUE TITLE
截图看不到任何app, 只看到桌面背景和菜单栏。

### ISSUE THREAD

**Issue by jymr92** [Snipaste/feedback#1274]
macos 10.15 (19A583)
软件版本2.2.3-beta 2019.10.06

截图看不到任何app, 只看到桌面背景和菜单栏。

**Comment by kookxiang** [comment]
系统设置 -> 安全性和隐私 -> 隐私 -> 屏幕录制
勾选 Snipaste

**Comment by jymr92** [comment]
嗯, 重启电脑后提示设置权限.可以截屏了.

> 系统设置 -> 安全性和隐私 -> 隐私 -> 屏幕录制
> 勾选 Snipaste

**Comment by laishulu** [comment]
不行。我重启电脑也不行，重启过很多遍了。
系统设置 -> 安全性和隐私 -> 隐私 -> 屏幕录制
里面没有snipaste

**Comment by laishulu** [comment]
我把 ~/.snipaste文件夹删了也不行。
