### ISSUE TITLE
使用 Ctrl + 鼠标滚轮缩放放大镜倍数

### ISSUE THREAD

**Issue by Riajyuu** [Snipaste/feedback#1275]
就目前来说，似乎只能使用预先设置好的放大镜倍数。

不过，似乎需要调整一下UI来明确告知用户当前的倍数？

**Comment by liulex** [comment]
我认为随时调整放大镜倍数没有什么实用意义。

**Comment by chensjiu** [comment]
我是个教师，在授课演示时用到这个软件，一直想方设法要调整这个放大镜倍数啊，最后找到这里来了。希望能提供一个选项，或者能在config.ini里自己设定？谢谢

**Comment by liulex** [comment]
@chensjiu 专业版有这个选项的：
![](https://user-images.githubusercontent.com/2010459/79074018-8577d200-7d1c-11ea-98d5-e7a584cc343c.png)
