### ISSUE TITLE
gif 贴图缺乏播放速度重置的快捷键

### ISSUE THREAD

**Issue by Riajyuu** [Snipaste/feedback#1276]
目前我能想到比较好的有小键盘数字 0 跟 enter ？

~（当然不排除我昨天星际又玩多了没看到）~

**Comment by liulex** [comment]
![Snipaste_reset_paster](https://user-images.githubusercontent.com/2010459/66661908-64a1c780-ec7a-11e9-9c73-f54114265378.png)
