### ISSUE TITLE
关于v2.2.3beta版本设置Esc快捷键注册失败的问题

### ISSUE THREAD

**Issue by llxinhui** [Snipaste/feedback#1277]
首先，在此表达一下对作者的感谢，我使用这个软件很久了，这个软件真的很方便
下面是对这次更新版本的一个问题或者说疑虑的说明

这两天Microsoft sore自动帮我更新了软件，再此之前我一直使用v1.16.2的版本，我习惯设置Esc为”隐藏/显示所有贴图“的快捷键，这样看某些东西时能通过Esc键迅速浏览对照内容，也不会明显遮挡当前屏幕的内容，这个贴图功能真的很方便。在6号更新了最新的版本之后，就开始提示Esc快捷键注册失败，这导致后面只能按下Esc键只能隐藏贴图，而无法再次显示贴图。

以上的问题，我详细对比过官网的beta版本和Microsoft store的版本，只有v1.16.2的版本是能正常使用的，推测是更新之后才出现这样的情况。

不知道是bug还是作者更新的时候有考量然后改变了设置，不管怎么样，希望作者能看看哈。
下面是一些截图，包括快捷键注册失败的和v1.16.2能正常使用的截图。
最后，再次感谢作者，软件真的很好用。

esc快捷键注册失败的反馈信息
![esc快捷键注册失败的反馈信息](https://user-images.githubusercontent.com/35327851/66502216-6a22d480-eaf7-11e9-954f-fd09a92affdc.png)

Microsoft store-v2.2.3beta版本快捷键问题截图
![Microsoft store-v2 2 3beta版本快捷键问题截图](https://user-images.githubusercontent.com/35327851/66502218-6a22d480-eaf7-11e9-93df-7aa9a18dbd0f.png)

v2.2.3beta-官网免装版esc快捷键问题截图
![v2 2 3beta-官网免装版esc快捷键问题截图](https://user-images.githubusercontent.com/35327851/66502219-6abb6b00-eaf7-11e9-9853-0baaa3ab6e6f.png)

正常版本的情况，v1.16.2版本
![正常版本的情况，v1 16 2版本](https://user-images.githubusercontent.com/35327851/66502221-6abb6b00-eaf7-11e9-9333-ff1c9ee6ef61.png)

**Comment by liulex** [comment]
v2.2.3 的更新日志有这一条：
> 防止一些简单按键被设为全局快捷键

所谓简单按键，指的就是单独的字母键、标点符号键、<kbd>Esc</kbd>、<kbd>Enter</kbd> 等常用按键，以及 <kbd>Shift</kbd> + 字母键、标点符号键。**这些按键都是不应该被设为全局快捷键的**，因为一旦设上，你是没办法在其他软件里使用这些按键的。

本来设不设这些按键是用户的自由，但很多用户并不知道设上去之后会影响原来按键的功能，或者就是不小心设上去的，如 #1234，https://www.v2ex.com/t/597438 ，所以这次更新加了限制，避免部分用户继续遇到类似问题而浪费宝贵的时间去排查。

**Comment by llxinhui** [comment]
晚上回复得也太快了。
实在不好意思，没注意到更新日志，我使用过程中也的确遇到你说的情况，可能是我隐藏/显示贴图这个太明显了，我一下就知道是快捷键冲突。

或许有没有另外的解决办法而让软件能继续使用简单按键，我想可能也有一部分人也习惯使用单个按键的，就像我。使用小键盘的真的不想设置Fx之类的快捷键，我也不知道会和什么冲突不，而且按个f1还要先按fn，这就变成了shift+fn+F1,单手挺难受的。

或者能不能运行时给出提示信息注意全局快捷键冲突或者设置单按键时再三提示警告等等。

以上个人愚见，浅短之处请见谅。

**Comment by GregAMO** [comment]
@llxinhui

**Comment by llxinhui** [comment]
> ![图片](https://user-images.githubusercontent.com/2010459/66577452-ff7fa080-ebab-11e9-9c90-7aaf4b412e8a.png)
> 试试以 PrtScr 为核心的快捷键? @llxinhui

好的，我看了一下，貌似要双手操作，可能有点不适应，我试几天看看，谢了。

**Comment by llxinhui** [comment]
> 可以在下个版本给个[高级设置](https://github.com/Snipaste/feedback/wiki/%E9%AB%98%E7%BA%A7%E8%AE%BE%E7%BD%AE)。

这个高级设置在本版本中能使用单按键吗，我看了下帮助，没有头绪，不会使用😂
如果下个版本能这样做就太好了，感谢照顾。
