### ISSUE TITLE
Mac 版贴图异常：不可以对从 Paste 复制的图片进行贴图

### ISSUE THREAD

**Issue by Mr-San** [Snipaste/feedback#1279]
1、开启 Paste（ https://pasteapp.me/ ）
2、复制图片1、图片2、图片3
3、打开 Paste 复制图片1
4、贴图图片1（ 贴图失败 ，但是复制的图片却可以在其他软件中粘贴，如 Word ）

**Comment by liulex** [comment]
无法重现哦。

**Comment by Mr-San** [comment]
不好意思。进一步发现是从 WeChat 复制图片不能贴图 的问题，上述第二步修改如下：

2、从 WeChat 聊天记录中 复制图片1、图片2、图片3
