### ISSUE TITLE
mac-2.23beta（2019.10.06）截图时，使用文字工具无法录入汉字

### ISSUE THREAD

**Issue by qq148376839** [Snipaste/feedback#1280]
mac-2.23beta（2019.10.06）截图时，使用文字工具无法录入汉字
用截图，选择文字工具，之后字母数字都可以录入，但是切换输入法到中文（mac自带的）无法录入汉字

**Comment by taolive** [comment]
mac 10.15系统，下载安装mac-2.2.3beta版本后，无法启动app，之前的版本是正常的

**Comment by taolive** [comment]
卸载、再重启安装app，可以正常使用，但是无法输入中文

**Comment by HuberyHuV1** [comment]
mac 10.15 文字工具无法输入中文，光标不闪烁，搜狗和自带输入法无法录入，搜狗输入法任务栏隐藏光标情况下会失焦，不知道这个是不是也是因为遮罩层隐藏导致失焦

**Comment by liulex** [comment]
谢谢大家的反馈，2.2.3 Beta2 已修复~
