### ISSUE TITLE
Mac版复制Excel表格转贴图的时候，格式丢失

### ISSUE THREAD

**Issue by chingxuds** [Snipaste/feedback#1282]
如下图所示
![image](https://user-images.githubusercontent.com/3142486/66694410-7a98a200-ece5-11e9-9eff-87e85b4544d4.png)

**Comment by qq148376839** [comment]
我直接空白

**Comment by liulex** [comment]
从 Excel 复制表格的时候，Excel 本身会提供一张相应的渲染图像。但 Mac 版 Office 提供的这张图像是模糊的，所以 Snipaste 选择自行从表格数据生成一张清晰的图像，只是这样的渲染结果就无法跟 Excel 的渲染结果一致了。
至于 @qq148376839 提到的空白问题，应该是字体颜色问题，会在下版本修复。
