### ISSUE TITLE
MacOS 10.15 Catalina 正式版中，snipaste beta2 不主动请求录屏权限

### ISSUE THREAD

**Issue by laishulu** [Snipaste/feedback#1287]
MacOS 10.15 Catalina 正式版中，
snipaste beta2 不主动请求录屏权限
也没有办法手工将snipaste加到系统的录屏权限中
最终结果：snipaste无法正确截屏。

尝试过以下步骤：
1. 用CleanMyMac X删除snipaste及相关配置文件
2. 删除~/.snipaste
3. 重启系统
4. 重新安装snipaste
5. 打开snipaste开始截屏。

但是，问题还是没有得到解决。

**Comment by vanxining** [comment]
同，现在完全用不了了。

**Comment by sxd1140** [comment]
same same

**Comment by liulex** [comment]
开始截屏，取消，就会看到录屏权限请求了，这个请求是系统检测触发的。

**Comment by sxd1140** [comment]
安装后重启了一次 再截图就有了.

**Comment by laishulu** [comment]
> 开始截屏，取消，就会看到录屏权限请求了，这个请求是系统检测触发的。

不行的，没有触发。
应该还是有哪个地方有问题。
我这里有其它几个软件，都正常触发了。

>安装后重启了一次 再截图就有了.

重启很多次了，
彻底卸载，并删除配置文件都很多次了
（见主贴的重置步骤）
还是不行

**Comment by laishulu** [comment]
> 开始截屏，取消，就会看到录屏权限请求了，这个请求是系统检测触发的。

你救了我！搞定了。
取消之后，再expose所有窗口，就能看到触发界面！

**Comment by laishulu** [comment]
但是我觉得：
截屏时，如果没有这个权限，就自动触发这个权限，不是更好么？
为什么要取消后才能触发？

**Comment by liulex** [comment]
……不是取消才触发，开始截屏那一刻就触发了，取消只是让你看到那个权限窗口。
