### ISSUE TITLE
直接截图和已截图再次方框标记的粗细不同

### ISSUE THREAD

**Issue by BentleyBlanks** [Snipaste/feedback#1290]
直接截图中，进行「方块/椭圆」标记，边框大约1px。
但在调出的已双击或者已确认得到的历史截图中，右键标记，边框粗细大约有3px

**Comment by liulex** [comment]
这是因为**新贴图**的工具栏都是默认设置，与截图的工具栏状态是独立的。
或许你是需要 `新贴图继承当前截图工具栏的状态`？
