### ISSUE TITLE
长贴图（超出屏幕宽高）的标注只能位于贴图边缘

### ISSUE THREAD

**Issue by SimonRiley-343** [Snipaste/feedback#1291]
### 问题

如果调出了一个超出屏幕高度的贴图（例如代码贴图），想使用标注功能精确的模糊掉一部分图片中的文本，标注功能浮动工具栏被固定在贴图的上或下边缘

### 建议的解决方案

设置浮动工具栏移动位置阈值为屏幕宽高

### 附件

1. 贴图顶部位于屏幕内时能正常显示浮动工具栏

![](https://www.leviatan.cn/chevereto/images/2019/10/16/snipaste-issue-191016-01.png)

2. 贴图顶部位于屏幕外时无法使用浮动工具栏

![](https://www.leviatan.cn/chevereto/images/2019/10/16/snipaste-issue-191016-02.png)

**Comment by liulex** [comment]
感谢反馈，已修复，请等待下版本更新。
