### ISSUE TITLE
应用弹窗广告，火绒显示为 snipaste

### ISSUE THREAD

**Issue by inkss** [Snipaste/feedback#1293]
![image](https://user-images.githubusercontent.com/31947043/67171010-9851bf80-f3e7-11e9-8c42-2534fc71c26d.png)

**Comment by liulex** [comment]
能不能有点判断力呢？桌面版几十万免费用户，这么多年我都从来没加过广告，并且连网站都没有广告，我为什么要在专业版放广告呢？

**Comment by inkss** [comment]
这个弹窗是 snipaste.exe 弹出来的，还能有谁，这个软件我是应用商店下的

**Comment by ZeddG93** [comment]
你说是snipaste.exe就是么，谁知道你有没有注入。

**Comment by linzyjx** [comment]
可以大致描述下发生的过程吗
是突然跳出，还是按下贴图键后才出现的
另外注入也不是没可能，我也pro用户，没有发现这个问题

**Comment by liulex** [comment]
你好，

请问你这么确定的根据是什么呢？在我看来，不过是某个检测工具检测到一个广告窗口是 `snipaste.exe` 弹出的，是不足以构成证据的：
1. 这个检测工具的检测方法是不是有问题？
2. 用户使用这个检测工具的方法是不是有问题？
3. 用户使用环境是不是有问题？（如上面回复说的注入问题）

那为什么我可以确定说不是我干的呢？因为我就是从来没放过广告啊。唯一可能是微软帮我放的，万一是这样，我想那会是个大新闻。

对普通用户来说，较为靠谱的判别方法是，在广告出现的时候，你把 Snipaste 关掉，再看看广告还在不在：
* 如果还在，那么显然是跟 Snipaste 无关的，请你收回上面的话
* 如果不在了，抱歉，那仍然不能确定是 Snipaste 干的。例如，广告程序可以做到在你关掉指定程序或任意程序后就自动关掉广告，误导普通用户的判断（虽然应该没有这么无聊）。

那应该怎么 100% 确定是谁放的广告呢？
这类广告总是要返利的，所以点一下那个广告，访问的网址应该有跟踪代码，拿那个代码或者整个网址到搜索引擎一搜，应该就会有相关结果了。

**Comment by bxb100** [comment]
这个广告大概率是搜狗输入法的

**Comment by inkss** [comment]
> 可以大致描述下发生的过程吗？

 @linzyjx ：突然跳出，没有点过贴图键，应用是微软应用商店下载的，能不能注入不太清楚。

> 这个检测工具的检测方法是不是有问题？

@liulex 检测软件为火绒的弹窗拦截。

**Comment by ziofat** [comment]
这个是 QQ 拼音的广告

**Comment by Genteure** [comment]
![image](https://user-images.githubusercontent.com/11240579/67198022-a677fe00-f430-11e9-9936-7509abb76824.png)

**Comment by linzyjx** [comment]
确实挺匪夷所思的
楼主能不能尽量回想一下，鼠标如果有移动到广告上的话，光标光标有没有变化成点击样式的（手指形状）
另外楼主的Snipaste是运行在普通模式还是管理员模式下的？

**Comment by inkss** [comment]
看来是我误判了，当时看到这个弹窗，再加上平时很反感这类东西，电脑里也没装什么乱七八糟的软壳，忘记了还有个QQ拼音了，在看到广告之后，言语上可能激烈了些。

@liulex 向之前的怀疑道歉了，是我缺少合理的判断了。现在想来有可能是弹出了截图，鼠标中按左倾斜设置成了截图快捷键，于是火绒的弹窗在判断时就显示成了这样子。
