### ISSUE TITLE
与GOLDENDICT 程序冲突，导致对 GOLDENDICT 窗口截图时卡死。

### ISSUE THREAD

**Issue by borpubi** [Snipaste/feedback#1294]
打开goldendict 查询单词后，想对查询结果截图，结果在截图界面卡死，两个程序都没响应也无法切换到其他程序中操作（等待很长时间，goldendict 会报错后自动退出，然后截图界面就正常了）（windows 10 X64家庭版（买电脑带的正版，已升级到最新版1903 18362.356）goldendict 版本：1.5.0-RC2-372-gc3ff15f qt5.12.3 ）。
尝试过换goldendict 版本，发现使用goldendict 1.5.0-RC2-372-gc3ff15f qt4.8.6 版本无影响。

此issue 同步在goldendict 提出。烦请双方都检查一下是啥问题。
如有需要沟通的，可随时联系。谢谢。

**Comment by loguu** [comment]
#1145
