### ISSUE TITLE
在mac上，截图色差莫名严重，会淡很多，泛灰

### ISSUE THREAD

**Issue by terainte** [Snipaste/feedback#1301]
在mac上，截图色差莫名严重，会淡很多，质量已经选到最好了。

snip截图：
![image](https://user-images.githubusercontent.com/56992924/67551440-7f287600-f73b-11e9-8500-5893a6e2931e.png)

微信截图：
![image](https://user-images.githubusercontent.com/56992924/67551617-f100bf80-f73b-11e9-94ff-96998204833b.png)

原图：
![卡牛-进件弹窗二-道理我都懂](https://user-images.githubusercontent.com/56992924/67551527-be56c700-f73b-11e9-871f-667568aa7131.jpg)

**Comment by loguu** [comment]
旧版？

**Comment by terainte** [comment]
> 旧版？

在软件内更的原来不是最新的，在官网下了最新的，解决了，谢谢
