### ISSUE TITLE
编辑截图时，画出的直线能否自动贴齐水平或垂直线，或者显示直线角度

### ISSUE THREAD

**Issue by chenwcmam** [Snipaste/feedback#1302]
有时候想在文字底下划线，但是画出来的直线没法显示是否水平，强迫症很难受，所以能否显示水平线或者垂直线，亦或者显示当前所画直线的角度，这样可以保证画出来的线是水平或者垂直的。

**Comment by liulex** [comment]
<kbd>Shift</kbd>
