### ISSUE TITLE
多屏使用发现的问题 和一点建议

### ISSUE THREAD

**Issue by Fist9** [Snipaste/feedback#1307]
在多屏幕下对贴图进行顺时针旋转和逆时针旋转（快捷键1和2），如果贴图在非主屏幕下，该操作的贴图会自动跳转到主屏幕。
还有一个小问题，算是设计上的问题：
  在贴图操作下，按空格键显示/隐藏标注工具条。选中工具后，再次按空格隐藏工具条，当前使用的工具并没有退出，如果使用者需要退出就必须使用ESC键，这样容易造成逻辑混乱。
  建议按空格显示工具条，无论对贴图进行修改操作或没有，再次按空格隐藏后工具栏逻辑属于关闭，并保留用户修改后的贴图，并可以用Ctrl+Z撤销。
  :-)   
  还有，个人希望该软件登陆steam（买爆和+1）

**Comment by liulex** [comment]
你应该是竖着排列屏幕了，这个问题会在下个版本修复。

按空格键隐藏工具条，就是设计成不退出当前工具的，这样在工具条造成遮挡的时候，可以隐藏工具条而继续标注。

**Comment by Fist9** [comment]
所以说能登陆steam么？
 :)  我想+1
