### ISSUE TITLE
macOS画笔大小的变动无法实时预览

### ISSUE THREAD

**Issue by WANGJIEKE** [Snipaste/feedback#1310]
![Screenflick Movie 2019-10-29 09_13_08](https://user-images.githubusercontent.com/21030118/67786926-f0627480-fa2c-11e9-851a-654e154f9aa3.gif)

macOS Catalina 10.15
Snipaste 2.2.5-Beta

（Windows版里这个功能是正常的）

**Comment by liulex** [comment]
但 macOS 版在我这里也是正常的。。

**Comment by WANGJIEKE** [comment]
我又试了试……用触控板的时候是正常的，如果用鼠标滚轮就会出现这个 bug _(:3 ｣∠ )_

**Comment by liulex** [comment]
@WANGJIEKE 会在下个版本修复。
