### ISSUE TITLE
什么出mac的Pro版

### ISSUE THREAD

**Issue by Jomesin** [Snipaste/feedback#1312]
亲爱的Snipaste开发人员,我知道我这么说可能不太友好,但是我依然想说,请尽快让这mac版的Snipaste公测吧,我要欠你们一个付费

**Comment by liulex** [comment]
谢谢支持，抱歉暂时无法确定时间哈，但会尽快。

**Comment by Jomesin** [comment]
老板大大加油啊，一定要坐噢，这个软件真的很棒


 
---原始邮件---
发件人: "Le Liu"<notifications@github.com&gt;
发送时间: 2019年11月17日 11:21:51
收件人: "Snipaste/feedback"<feedback@noreply.github.com&gt;;
抄送: "Days_Vinson"<747142549@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Snipaste/feedback] 什么出mac的Pro版 (#1312)



谢谢支持，抱歉暂时无法确定时间哈，但会尽快。
