### ISSUE TITLE
希望能设定二次启动时的行为

### ISSUE THREAD

**Issue by the1812** [Snipaste/feedback#1314]
例如在Snipaste已经运行的时候, 再次启动Snipaste能够触发截图操作, 现有的行为貌似只是检测到已在运行就退出了.
![image](https://user-images.githubusercontent.com/26504152/68379410-bf024b00-0188-11ea-87fe-bb98894b757f.png)

我希望能用Snipaste替换掉Windows Ink工作区的截图, 实现双击Surface Pen调用Snipaste截图:
![image](https://user-images.githubusercontent.com/26504152/68379432-c75a8600-0188-11ea-95b8-993879b96212.png)

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/940#issuecomment-506969718

**Comment by the1812** [comment]
非常感谢！想不到启动经典应用那里还可以指定快捷方式
