### ISSUE TITLE
定时截图

### ISSUE THREAD

**Issue by jimingshuo** [Snipaste/feedback#1316]
如果能够设定定时自动截图，比如每3秒，或者每30秒自动按之前的窗口大小截屏，然后立即保存到指定目录下并关闭当前截图，这样就方便许多了。这是不是也是实现滚动截图的一种方式呢？图截下来了之后随便怎么处理都好办。

**Comment by liulex** [comment]
![](https://user-images.githubusercontent.com/2010459/69002500-7d616500-092b-11ea-9ded-a7fbc5f9bfae.png)
