### ISSUE TITLE
全屏截图 快捷键

### ISSUE THREAD

**Issue by galaxygh** [Snipaste/feedback#1317]
能否在快捷键中增加全屏截图的设置项？
有时截图不需选择区域了，就想把屏幕显示内容保存下来，这时有个全屏截图的快捷键就会方便不少，不然还要找空白位置点击一下
谢谢🤩

**Comment by MooWantFree** [comment]
@galaxygh 直接按PrtSc啊

**Comment by liulex** [comment]
[专业版](https://docs.snipaste.com/zh-cn/pro)可为任意功能设置全局快捷键。

**Comment by bbscom2008** [comment]
启动截图功能以后，Ctrl + A 就可以全屏截图了。
