### ISSUE TITLE
BUG：Mac上多屏分辨率的调整问题

### ISSUE THREAD

**Issue by Saafo** [Snipaste/feedback#1318]
版本：Mac 2.2.5 Beta  
硬件情况： Macbook Pro 2018 13寸，内建显示器分辨率2560 * 1600，外接了一个显示器，分辨率为1920 * 1080  
情况出现：用Snipaste在内建显示器上截图模糊：  
![image](https://user-images.githubusercontent.com/46736350/68529580-2233df00-033b-11ea-80b5-1511e1b8cf5e.png)  
(Snipaste)  
![image](https://user-images.githubusercontent.com/46736350/68529586-311a9180-033b-11ea-9ad1-c8c336ff25d7.png)  
（QQ)

**Comment by Saafo** [comment]
我重启了一遍，问题消失了。应该只是偶发性问题，浮现率不是100%

**Comment by liulex** [comment]
连接/断开不同 DPI 的屏幕后，需要重启 Snipaste.
