### ISSUE TITLE
AVG报漏洞，exe文件被隔离了

### ISSUE THREAD

**Issue by hgb97001** [Snipaste/feedback#1326]
首先这个软件很好用，比系统自带的强多了！
然后说问题：
AVG报漏洞
![图片](https://user-images.githubusercontent.com/11813019/68916452-f41e2700-07a0-11ea-9e50-f5bc20ce8cff.png)
说明：win10自带杀毒没有报这个，笔电的AVG报漏洞，exe文件直接被放置到隔离区了。

**Comment by loguu** [comment]
这不是应该报给 AVG 吗？

**Comment by liulex** [comment]
请向 AVG 反馈，这不叫 Snipaste 的漏洞，这是 AVG 的误报。
