### ISSUE TITLE
关于多虚拟桌面的建议

### ISSUE THREAD

**Issue by AzazelX5** [Snipaste/feedback#1327]
测试操作系统：mac

问题1： 现在多桌面贴图只在设置里面有一个选项，更改起来及不方便。因为平时工作两种场景都有用到，所以希望把设置加到菜单栏图标的右键设置中

问题2： 如果截图和贴图之前没有选中多虚拟桌面贴图，截图并贴图后再勾选是没有效果的。建议在贴图后，对图片右键中可以添加一个多桌面贴图的开关。这样在贴图后也能控制是否多桌面贴图了。

因为平时工作会遇到两种场景：
> 第一种：先截一张图放在一个桌面，后续再处理；这种场景就希望不要多桌面贴图。 

> 第二种：有两个桌面，第一个桌面打开的是网页，第二个桌面是代码。调试过程中希望在网页桌面截一张出错图，到代码界面对照错误图找到相应代码的位置；这种场景就希望能多桌面贴图了。   

实际上，平时这两种场景都是交替使用的，现在的设置及不方便。  理想中最好就是能在贴图后对所贴图的右键中加一个是否多桌面贴图的开关，这样就能在两种场景中随意切换了，或者能设置一个快捷键。

希望能采纳此建议，感谢。

**Comment by liulex** [comment]
专业版（Mac 版暂未出）可以针对每个贴图进行设置的，参见 Windows 版。
实际上，`多桌面贴图只在设置里面有一个选项` 这个选项在 Windows 版也是专业版才提供的，Mac 版因较多用户抱怨该问题，才开放给了免费版。

**Comment by AzazelX5** [comment]
mac 专业版什么时候出？   如果买了windows专业版，到时候出了mac 专业版 能通用吗？

**Comment by liulex** [comment]
桌面版是通用的，日期未知。
