### ISSUE TITLE
mac 假死 保存图片

### ISSUE THREAD

**Issue by uniquepengpeng** [Snipaste/feedback#1332]
F1截图，然后保存文件的时候，比较容易“假死”，但是不在系统的“强制退出程序”清单中。界面无法操作。怀疑是文件目录处理时间过长，有几次过了很久才弹出“snipaste需要**目录的权限”等。碰到这种情况，也无法通过活动监视器杀死进程，只能看运气等待或重启了。
snipaste 2.2.5-Beta,没更新到beta版之前也会有此问题。
mac 10.15.1
建议：最好碰到此种情况，能有个快捷键强制退出等。

**Comment by liulex** [comment]
见 #1273 ，切换桌面就可以看到授权窗口。
