### ISSUE TITLE
功能需求——保存文件的同时复制到粘贴板

### ISSUE THREAD

**Issue by Mofisto** [Snipaste/feedback#1334]
我有这样一个场景，我经常用Snipaste截图写文档，然后粘贴图片到markdown编辑器中，但是直接截图Ctrl+C然后Ctrl+V的文件是命名为时间格式，而我希望保存设置文件名后再粘贴文件，这样图片的文件名对于我来说直接含义，便于管理。
 简单来说，我希望能Snipaste截图设置文件名之后，还能够粘贴到其他场景中。
我不知道这个功能需求有没有普适性，但他对我来说很重要。win10已入正，感谢开发组。

**Comment by liulex** [comment]
Ctrl+C 是复制图片到剪贴板，剪贴板的图片粘贴到  markdown 编辑器中如何命名，是 markdown 编辑器自己决定的。

你提到已经入正，专业版有个选项是 “同时复制为文件" （`首选项` - `输出` - `剪贴板`），不清楚你是否已经勾选，如果已经勾选了这个选项，那么你看到的时间格式的命名是由于 Snipaste 产生的临时文件，其命名遵循首选项中的 `手动保存` 的文件名规则。由于临时文件的复制需要做到用户无感知，所以不可能弹出一个窗口让用户输入名字的。

对于你的需求，我觉得比较合理的是由 markdown 编辑器去实现，即每次插入图片时，让你可以重命名该图片。
如果由 Snipaste 为你实现，比较合理的方式是当你手动保存截图后， Snipaste 给个带按钮的通知气泡，用户可以选择复制图像/复制图片文件。

**Comment by valuex** [comment]
> 我有这样一个场景，我经常用Snipaste截图写文档，然后粘贴图片到markdown编辑器中，但是直接截图Ctrl+C然后Ctrl+V的文件是命名为时间格式，而我希望保存设置文件名后再粘贴文件，这样图片的文件名对于我来说直接含义，便于管理。
> 简单来说，我希望能Snipaste截图设置文件名之后，还能够粘贴到其他场景中。
> 我不知道这个功能需求有没有普适性，但他对我来说很重要。win10已入正，感谢开发组。

用autohotkey 配合snipaste ，比较简单就可以实现的
