### ISSUE TITLE
关于隐藏/显示全部贴图的焦点占用

### ISSUE THREAD

**Issue by Greesea** [Snipaste/feedback#1337]
由于经常会pin一些片段在屏幕上，屏幕上贴图就会变的很多很占地方，所以一直在频繁使用切换显示全部贴图功能，但是最近发现这个功能会在切换到显示时由最后一张贴图占用焦点，希望增加一个开关能关闭掉这里的焦点占用。

**Comment by liulex** [comment]
赞，下个版本会实现。
我觉得不需要加选项，这种操作确实不需要激活贴图焦点。
