### ISSUE TITLE
[new feature]保存图片时自动周围阴影的功能。

### ISSUE THREAD

**Issue by kasusa** [Snipaste/feedback#1340]
我在这之前一直用的**winsnap**，它的一个很有特色的功能就是可以自动给图片加上一圈的阴影。

阴影的效果和pin住的图片效果一样，但是有一圈可以设置调整颜色和大小的阴影。

想要这个功能的主要原因是，截图如果是白色的，在word里面粘贴上有阴影的图片会很好看。如果是没有阴影的话，和背景混起来的不好看。

如果开发者可以给snipaste也加上这个功能，那么肯定会有很多人喜欢！

**Comment by liulex** [comment]
专业版已经有这个功能了，免费版不会再添加任何功能~

**Comment by zlanzip** [comment]
mac保存图片加上周围阴影功能应该还没有吧
