### ISSUE TITLE
能否为标注图像添加快捷键，非常感谢！

### ISSUE THREAD

**Issue by bbscom2008** [Snipaste/feedback#1342]
这款软件非常好用，我经常介绍同事使用这款软件。

如果能在标注图像的时候，给矩形、箭头、文字、铅笔几个功能添加快捷键，就更好了。
我是一名老师，我使用 snipaste 当做桌面画笔使用，通常操作是选择一块区域，更多是全屏区域，然后在图像上做一些标注，最后保存图片用起来非常方便。

再次感谢你们。

**Comment by liulex** [comment]
有的：
![](https://user-images.githubusercontent.com/2010459/69915931-94f22f00-148f-11ea-8c36-8cd0e0eb4510.png)

**Comment by linwan623910** [comment]
我刚也想问作者是否能添加这个功能，每次截图都要手动去点，非常不方便。希望添加“箭头”、“画笔”、“马赛克”、“橡皮”……等那些的快捷键。。。
