### ISSUE TITLE
【新功能建议】截图带来源

### ISSUE THREAD

**Issue by valuex** [Snipaste/feedback#1344]
新功能描述：
 在截图粘贴到笔记系统（比如OneNote）中时，时常需要记录截图的来源。这个来源可能是窗口或者文档的标题，或者是网页的地址。  在现在的条件下，往往是粘贴图片后，再回到截图来源，去复制文档标题或者网页地址，需要来回切换。
因此，希望能够实现在截图的同时，获取窗口标题/网页地址/文档标题等信息作为截图的来源，一并放入clipboard中，粘贴图片时，一键就完成了图片和source的粘贴。

目前：
个人已经通过autohotkey实现了类似功能。
总体逻辑：将截图保存到临时文件，在剪贴板中写入html
`<html><body><img src="local_temp_file"><a href="">source:XXX</a></body></html>`
基本够用，但觉得需要创建临时文件，效率不高。
请@liulex 看看，能否在snipaste中直接集成类似的功能。
可能路径：将剪贴版中的图片转成base64，然后再生成跟上面类似的html信息放入剪贴版。
个人觉得，这样直接在内存中操作效率会高很多（不需要将内存中的图片存到本地）

**Comment by liulex** [comment]
把图像换成 html 格式放进剪贴板中，还是比较罕见的需求，你能自己实现就好啦。
至于转 base64，ahk 也可以调用外部工具做到的~

**Comment by jinboowu** [comment]
附带截图的文档来源还是一个比较普遍的需求，希望能够提供，尤其是pdf文件的截图，如果能够提供截图的文件名和页码，那是非常好的

**Comment by valuex** [comment]
> 附带截图的文档来源还是一个比较普遍的需求，希望能够提供，尤其是pdf文件的截图，如果能够提供截图的文件名和页码，那是非常好的

pdf 文件的名称不容易获取，不同阅读器的策略都不一样。这个可能超过Snippaste的”业务“范围了。
你个人用的话，可以用autohotkey试试。
