### ISSUE TITLE
截图后双击再使用快捷键贴图，却是上一张图

### ISSUE THREAD

**Issue by refine706** [Snipaste/feedback#1345]
以下是我的配置文件

[General]
enhanced_tray_menu=true
start_on_boot=true
startup_fix=2
first_run=false
read_tips=2
last_save_suffix=JPG
font_dialog_size=@Size(500 435)
as_admin=true

[Hotkey]
paste="100663382, 86"
snip="67108933, 69"
snip_and_copy=
custom_snip=

[Snip]
max_records=100
ask_for_confirm_on_esc=false
max_areas=20

[Misc]
preload_dlls_last_interval=22.5

[Output]
auto_save_path=E:/Program Files/Snipaste/data/Snipaste_$yyyy-MM-dd_HH-mm-ss$.png
quick_save_notification=false

[Paste2]
max_hidden=100

[Interface]
uppercase_hex=true

[Paste]
mnemonics_on_context_menu=true

**Comment by refine706** [comment]
还需要什么东西，辅助排查，请与我联系。
这么多年一直使用Snipaste，有这样的问题有些影响工作

**Comment by refine706** [comment]
[splog.txt](https://github.com/Snipaste/feedback/files/3907927/splog.txt)
日志，见附件， @liulex

**Comment by liulex** [comment]
这个问题你不是报告过了么？#548
是你电脑上其他软件的干扰，跟 Snipaste 无关的……

**Comment by refine706** [comment]
我以前是报告过，当时开启了管理员权限就好了
但是现在，Snipaste默认就是管理员权限启动，并且关掉快速保存也试过了，问题依然还在。
就在刚刚，为了验证是否其他软件问题，我把360关掉了，问题就解决了。。。
多谢你的提醒，这个结果供你参考

**Comment by refine706** [comment]
如果哪天这方面有进展，还请这里通知我下，多谢！

**Comment by refine706** [comment]
今天发现退出360，还是存在快捷键贴不上图的问题
我试了截屏时中键单击直接贴到屏幕，不存在贴上的问题
先复制到剪贴板，再使用快捷键贴出就不行

供你参考
