### ISSUE TITLE
「反馈建议」新版工具栏太大，且无法使用系统指针

### ISSUE THREAD

**Issue by gongyoyo** [Snipaste/feedback#1347]
1.新版本的工具栏不好用，已经使用一年多1.6版本，已经适应了小的工具栏，新版不好用
2.无法自己适应系统更改后的鼠标指针，一直是自带的白色，不好看，系统我自己美化过
希望作者可以在下个版本给予解决😊

**Comment by liulex** [comment]
1. 可继续使用旧版，新版已做的改动不会改回去
2. 抱歉不支持
