### ISSUE TITLE
希望支持OCR功能

### ISSUE THREAD

**Issue by ahumoon7421** [Snipaste/feedback#1349]
截图文字识别应用场景非常多，OCR软件带截图的也很多，snipaste如果能支持OCR那就太棒了~

**Comment by qnxbwlyj** [comment]
加上去感觉就是天若OCR文字识别了

**Comment by MooWantFree** [comment]
@qnxbwlyj

**Comment by MooWantFree** [comment]
![image](https://user-images.githubusercontent.com/46401523/70996482-d0d2f880-210d-11ea-9691-910dfba9fe89.png)
我用的snipaste配合u tools, 个人感觉和天若使用体验差不多

**Comment by ifuner** [comment]
你不觉得这个很没有隐私吗? 太可怕
