### ISSUE TITLE
希望贴图储存的图片有额外备份储存或者定期额外备份方案。

### ISSUE THREAD

**Issue by mzspeedwolf** [Snipaste/feedback#1350]
UWP版，不明原因崩溃之后启动软件瞬间自动结束进程，重置了软件，查看记录无法读取之前的配置文件，导致所有分组及图片丢失。

[2019-12-11 10:00:02.585] [I] History dir: C:/Users/XXXXX/AppData/Local/Packages/45479liulios.17062D84F7C46_p7pnf6hceqser/LocalState/history
[2019-12-11 10:00:02.587] [W] Failed to open history file "C:/Users/XXXXX/AppData/Local/Packages/45479liulios.17062D84F7C46_p7pnf6hceqser/LocalState/history/.sp0" for reading

顺带提供几次崩溃重启的dump供参考。

所以希望能为贴图及贴图组提供额外备份的途径，以供意外情况的恢复。
感谢
[dump.zip](https://github.com/Snipaste/feedback/files/3948070/dump.zip)

**Comment by liulex** [comment]
重置应该是不影响应用数据的。请问你现在可以正常启动吗？
从 dump 来看，是贴图上有一个异常的标注导致了崩溃，如果能提供上面日志中的 history 文件夹就最好了。

**Comment by mzspeedwolf** [comment]
重置之后就正常了。崩溃的时候确实是在使用标注功能。
请问是需要提供AppData\Local\Packages\45479liulios.17062D84F7C46_p7pnf6hceqser\LocalState\history
这整个文件夹么？
我看里面的储存内容已经是我重置之后的内容了

**Comment by liulex** [comment]
原来是有两种重置，一种保留应用数据，一种清除应用数据。
既然有问题的已经清除掉了，就不用再提供正常的数据了。
不过，请问你还能记得当时是使用哪种标注吗？是文字标注？这个问题应该可以复现的。

**Comment by mzspeedwolf** [comment]
使用的是系统设置里 应用和功能-snipaste-高级选项-重置。使用修复之后并没有成功，才使用的重置。
当时在使用马赛克/模糊选项下的功能，当时记得在来回切换调整圆圈和旁边两个值以及面积选中的时候崩溃的。

**Comment by liulex** [comment]
非常感谢！我已经复现了，我会在下个版本修复的。
关于应用数据，其实全部都在 `AppData\Local\Packages\45479liulios.17062D84F7C46_p7pnf6hceqser\LocalState` 这个文件夹里，只要没有使用重置功能以及不重装 App，数据是不会丢的。当然可以自行备份到其他地方，将来也会提供数据的备份和导入功能。
如果是历史数据导致了崩溃，可以将数据以邮件发送给我，我会帮忙恢复。

**Comment by mzspeedwolf** [comment]
感谢
