### ISSUE TITLE
mac版切图后点击工具栏上的保存图标按钮就卡死了

### ISSUE THREAD

**Issue by gomobig** [Snipaste/feedback#1352]
发现了什么 bug？
* 请描述一下重现的步骤，越详细越好。

使用快捷键截图，然后点击工具栏上的保存，系统就卡死了，一直转圈，只能强行重启电脑。但是双击鼠标左键保存到剪切板没有问题

**Comment by loguu** [comment]
https://github.com/Snipaste/feedback/issues/1273#issuecomment-541302612

**Comment by coldfall** [comment]
我也遇到同样的问题，工具栏里的保存会导致一直转圈，然后也无法切换或者退出，只能重启Mac

**Comment by YouZhengChuan** [comment]
你不需要重启，只需要在命令行中，用kill命令，找到这个进程，把这个进程杀死即可。

进入命令行：

- 通过`ps aux`查看所有正在运行的进程，通过`grep Snipaste`过滤出Snipaste进程，输出的第二列是该进程的`pid`。
>  ps aux|grep Snipaste|grep -v grep

```shell
MacUser    90819   0.0  0.7  5660440  57216   ??  S    11:09上午   0:02.65 /Applications/Snipaste.app/Contents/MacOS/Snipaste
```

- 通过`kill` 命令，杀死该进程。
> kill -9 90819

然后重复第一个步骤，看该进程是否还能查找到，如果找不到了，说明该程序的进程已经杀死了。

**Comment by liulex** [comment]
怎么回事？二楼不是解答过了？
