### ISSUE TITLE
截图另存为重命名时出现卡死现象，整个电脑都死机

### ISSUE THREAD

**Issue by inthink** [Snipaste/feedback#1357]
OS：macOS 10.15.2 
snipaste：2.2.5 beta
在截图重命名是出现卡死现象，整个电脑都死机，20191217早上出现两次

**Comment by CyberKoo** [comment]
有遇到过类似问题，最后发现是因为保存到iCloud要授权，那是截屏下那个授权的窗口弹不出来导致的softlock。

**Comment by inthink** [comment]
> 有遇到过类似问题，最后发现是因为保存到iCloud要授权，那是截屏下那个授权的窗口弹不出来导致的softlock。

我是保存在本地，没有保存到iCloud，以前用的好好的， 今天突然就这样了 。我试了卸载重装也不行

**Comment by loguu** [comment]
https://github.com/Snipaste/feedback/issues/1273#issuecomment-541302612
