### ISSUE TITLE
关于PNG 贴图透明部分无法移动和处理的问题

### ISSUE THREAD

**Issue by qnxbwlyj** [Snipaste/feedback#1359]
复制包含了透明通道的PNG图片后进行贴图，如果鼠标放在透明通道部分，则无法移动或者处理贴图，如果鼠标放在非透明通道部分，则可以移动或者处理贴图。测试图片地址：https://www.psjia.com/uploads/soft/180321/1-1P321225054.zip
请问这怎么解决？

**Comment by loguu** [comment]
充值变强

**Comment by liulex** [comment]
专业版支持。
