### ISSUE TITLE
MacBook Pro上面无法自由截图

### ISSUE THREAD

**Issue by crazyfinger** [Snipaste/feedback#1360]
在MacBook Pro上面自由选定区域截屏，一松开鼠标截的图就消失了，无法悬浮选择贴图或者复制等其他操作，就像按esc退出截图一样，无法截图。如果是截自动检测到的窗口是正常的，就是自由选定截图区域时一松开鼠标就退出了。

**Comment by liulex** [comment]
版本太旧了吧？
