### ISSUE TITLE
Win10系统，软件2019.12.20已更新保存时卡住，报错退出

### ISSUE THREAD

**Issue by AnimatorBullet** [Snipaste/feedback#1361]
![image](https://user-images.githubusercontent.com/45991057/71226506-03037680-2317-11ea-9740-29d719631f49.png)

重启依然不行，已勾选管理员

**Comment by liulex** [comment]
请问以前正常使用过吗？还是更新才出了问题？

**Comment by AnimatorBullet** [comment]
> 请问以前正常使用过吗？还是更新才出了问题？

正常使用过，某次更新后突然，公司保存出问题，家里面正常，
但是家里自启有问题公司正常，比较迷，但是自己通过改动计划任务搞定了自启，
现在只剩公司这边无法保存图片，看了下之前的类似问题，是因为保存权限吗？
不太知道该如何解决只好来求助了~

**Comment by liulex** [comment]
其他 issue 说到的保存问题是 macOS 的，跟你这个问题没有关系。
如果是更新导致的，可能是因为我升级过 Windows SDK 版本……下次更新我换个版本试试。
请问你现在公司电脑的操作系统版本是？
另外，可以分享一下家里电脑的自启是怎么解决的吗？

**Comment by AnimatorBullet** [comment]
> 其他 issue 说到的保存问题是 macOS 的，跟你这个问题没有关系。
> 如果是更新导致的，可能是因为我升级过 Windows SDK 版本……下次更新我换个版本试试。
> 请问你现在公司电脑的操作系统版本是？
> 另外，可以分享一下家里电脑的自启是怎么解决的吗？

恩我看到了，那些问题都是macOS，公司是 win10 专业版 1709，

自启我是改了windows自带的计划任务，因为看到里面有个Snipaste相关的，
我看其他自启比如sougou啥的触发器有个当任何用户登录时，好像是改了下触发器，
记不清了，回家了我再确认下。

**Comment by AnimatorBullet** [comment]
> 其他 issue 说到的保存问题是 macOS 的，跟你这个问题没有关系。
> 如果是更新导致的，可能是因为我升级过 Windows SDK 版本……下次更新我换个版本试试。
> 请问你现在公司电脑的操作系统版本是？
> 另外，可以分享一下家里电脑的自启是怎么解决的吗？

系统更新了 1909 还是一样保存就报错重启软件

**Comment by MiroKaku** [comment]
同, UWP 版本 2.2.8.0, 保存就会崩溃. 系统:  Windows 10 [1809 (17763.973)]

**Comment by loguu** [comment]
今天更到了 2.3，请问该问题是否还存在？ @AnimatorBullet @MiroKaku

**Comment by AnimatorBullet** [comment]
@liulex 2.3.1 版本还是会保存退出。。有啥解救办法吗

**Comment by liulex** [comment]
#1399

**Comment by AnimatorBullet** [comment]
> #1399

搞定了，没注意微盘，我把Snipaste卸载重装就好了，可能最近企业微信更新了
