### ISSUE TITLE
v2.2.4 Beta (2019.10.24) win10 64位 LTSC 无法启动？

### ISSUE THREAD

**Issue by Cloudprogram** [Snipaste/feedback#1363]
1：下载v2.2.4 Beta (2019.10.24) 从https://www.snipaste.com/index.html#
2：解压缩
3：在win10 LTSC 64位无法运行Snipaste-2.2.4-Beta-x64.zip
4：而32位Snipaste-2.2.4-Beta-x86.zip 可以成功运行

**Comment by liulex** [comment]
单凭这些信息我无法做任何诊断。
