### ISSUE TITLE
2.2.5版本开启截屏功能后，自动从当前窗口切换到桌面

### ISSUE THREAD

**Issue by miscomputer** [Snipaste/feedback#1365]
MACOS 10.15.2
开启截屏功能后，自动从当前窗口切换到桌面，还换切换不回来

**Comment by SnallQiu** [comment]
+++++++ 我也是 系统一更新就炸

**Comment by liulex** [comment]
#1171 #1202 #1273 #1274 #1297 #1338
https://docs.snipaste.com/zh-cn/troubleshooting?id=macos
