### ISSUE TITLE
记号笔颜色设置在切换时被覆盖

### ISSUE THREAD

**Issue by Riajyuu** [Snipaste/feedback#1369]
我不确定这是不是bug（
Windows 10 1909
Snipaste 2.2.8 x64 Pro

如果是feature 那么 如何在切换工具时让记号笔颜色不变呢

![recording](https://user-images.githubusercontent.com/16912240/71713839-44aa1c00-2e03-11ea-9a51-4a16e7aa342e.gif)

**Comment by liulex** [comment]
是 bug，感谢反馈，会在下版本修复。
