### ISSUE TITLE
macOS 版本无法正常使用

### ISSUE THREAD

**Issue by plutopaner** [Snipaste/feedback#1373]
启动电脑后，打开snipaste，无法正常使用。
进入活动监视器，显示snipaste已经运行。
但是按F1无法截图，屏幕上方任务栏也没有snipaste的图标。
系统版本10.15.2 (19C57)
snipaste安装最新版重装后也不可以。
后续，目前安装了1.16.2beta版本
可以正常使用

**Comment by lecion** [comment]
同样的问题
系统版本：`10.14.6 (18G103)`

**Comment by mengyaoss77** [comment]
10.15.2 (19C57)  同样， 偶尔会自动退出，然后今天发现应用无法打开，没有报错，活动监视器里也没有相关进程。

**Comment by liulex** [comment]
请验证 Snipaste 2.6 Beta 是否还有问题。如有请 Reopen issue.
