### ISSUE TITLE
希望能有一个标号的功能

### ISSUE THREAD

**Issue by L00189920** [Snipaste/feedback#1376]
感谢作者及团队做出这么强大的截图软件并且很好用，个人希望能有这么一个标号的功能，虽然能通过添加字体实现，但是没有这个方便来得更快捷。谢谢

![image](https://user-images.githubusercontent.com/50358600/72318500-6646b580-36d7-11ea-85e9-f294487ef3c3.png)

**Comment by wdhwg001** [comment]
![image](https://user-images.githubusercontent.com/8943519/73859545-2b1e4900-4875-11ea-91a2-76ac131d54a1.png)
![image](https://user-images.githubusercontent.com/8943519/73859829-a08a1980-4875-11ea-9b6f-e1265ed049bb.png)

该功能已被QQ截图实现，同时OCR、截长图、贴图、贴图再编辑也已经被支持。

**Comment by liulex** [comment]
2.4 已实现。
