### ISSUE TITLE
屏幕取色取出来的色不准确

### ISSUE THREAD

**Issue by takmartian** [Snipaste/feedback#1378]
<img width="621" alt="Snipaste_2020-01-16_14-44-00" src="https://user-images.githubusercontent.com/59951019/72500138-c15ee080-386e-11ea-9eef-a75e2b0619f0.png">

**Comment by lumanegi233** [comment]
请问你是使用的广色域显示器吗？
在windows的非SRGB显示环境下，不光取色不准，截图的颜色也是不准确的。
我也希望以后snipaste能够解决这个问题，但是QT库本身貌似对色彩管理的支持就比较差，所以大概是希望渺茫。
另外在使用photoshop时，可以用取色工具在photoshop内按住左键，再拖动到photoshop窗口外取色。

**Comment by liulex** [comment]
Mac 版升级到最新版本即可。
Windows 版确实没处理 color profile.

**Comment by takmartian** [comment]
收到，谢谢两位。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Le Liu <notifications@github.com&gt;
发送时间: 2020年1月18日 22:57
收件人: Snipaste/feedback <feedback@noreply.github.com&gt;
抄送: takmartian <takmartian@vip.qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Snipaste/feedback] 屏幕取色取出来的色不准确 (#1378)




Mac 版升级到最新版本即可。
Windows 版确实没处理 color profile.
