### ISSUE TITLE
建议增加一个贴图在屏幕边缘时，自动缩小的功能

### ISSUE THREAD

**Issue by bsqgm** [Snipaste/feedback#1379]
当屏幕上有很多贴图时，我个人是习惯将贴图缩到最小10%，然后放在屏幕某一角。但是这样无论是看起来还是操作都有一点影响。因此建议增加一个功能，类似QQ，当把贴图移到屏幕边缘处时，贴图能够自动缩小，并在此边缘处留下一个小标记。在鼠标移到标记处时，再将贴图显示出来。

**Comment by liulex** [comment]
#1219
