### ISSUE TITLE
关于在 Windows 下添加 Ctrl+W 快捷键关闭贴图的功能请求

### ISSUE THREAD

**Issue by lumanegi233** [Snipaste/feedback#1384]
Windows 下的 Ctrl+W 和 MacOS 下的 Cmd+W 常被各种 App 用作关闭窗口快捷键。
Snipaste 在 MacOS 下也默认可以使用 Cmd+W 来关闭贴图。
希望 Windows 版的 Snipaste 也可以加入使用 Ctrl+W 快捷键关闭贴图的功能。

**Comment by liulex** [comment]
好的，下个版本加入，感谢建议。
