### ISSUE TITLE
移动贴图时吸附距离增加及贴图同步建议

### ISSUE THREAD

**Issue by mzspeedwolf** [Snipaste/feedback#1386]
1、目前的吸附距离比较近，要贴得很近才会吸上。
希望增加吸附像素距离调整选项，或者干脆直接增加吸附距离。高分辨屏下微调贴图距离难度相对比较大。

2、尝试使用其他软件同步AppData\Local\Packages\45479liulios.17062D84F7C46_p7pnf6hceqser\LocalState\history文件夹
到别的系统的相应目录，即使重启软件也并没有实现贴图及贴图组的同步。
由于config.ini记录了不同主机的目录，遂没有同步。
希望能通过设定/指定一个储存目录，用户使用第三方软件进行跨设备同步文件/文件夹来达到跨设备同步贴图/贴图组的想法。第三方同步软件/网盘内含的历史记录（或者版本控制）功能，也能更好地保证软件出错时的数据恢复。

感谢。

**Comment by liulex** [comment]
1. 下版本会增加一个高级选项：`Paste/magnetic_attach_threshold`
2. 首选项里可以设置配置文件的存放目录，history 目录也可以在[高级选项](https://docs.snipaste.com/zh-cn/advanced-configs)中设置。但目前只会在程序启动时读取一次配置，其他时候都是由程序覆盖当前配置的，所以放在网盘目录也只能用于备份，无法做跨设备同步。

**Comment by mzspeedwolf** [comment]
了解了。感谢回复。
