### ISSUE TITLE
不能对左下角开始按钮的右键菜单进行截图

### ISSUE THREAD

**Issue by BenjiaH** [Snipaste/feedback#1387]
不能对左下角开始按钮的右键菜单进行截图
系统：Win10 版本1909（OS内部版本18363.592）

**Comment by liulex** [comment]
截图快捷键不要包含 <kbd>Alt</kbd>

**Comment by BenjiaH** [comment]
> 截图快捷键不要包含 Alt

截图快捷键均无 Alt

**Comment by liulex** [comment]
![图片](https://user-images.githubusercontent.com/2010459/73540774-c1b0cb80-446b-11ea-9d42-5872af9daa4d.png)

**Comment by BenjiaH** [comment]
谢谢！
