### ISSUE TITLE
Mac 2.2.5 Beta截图选择保存后即卡死

### ISSUE THREAD

**Issue by John-Ralph** [Snipaste/feedback#1388]
MacBook Pro (Retina, 13-inch, Early 2015)
10.15.2 (19C57)
选择保存后出现一个不断旋转的彩虹圈,无法操作,尝试使用强制关闭无效,只能强制关机,望修复!

**Comment by Ryushane** [comment]
同遇到，是申请保存权限与截图冲突了，无法进入到给权限的界面

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/1273#issuecomment-541302612
