### ISSUE TITLE
win10无法启动Snipaste

### ISSUE THREAD

**Issue by Tenorab** [Snipaste/feedback#1390]
win10，系统版本号1903，操作系统版本18362.592。
过去一直使用官网的免安装版，从今日（2020.1.31）起突然无法启动软件。双击程序图标无法启动软件，**无任何提示窗口，任务管理器无相应进程**。
已尝试以下操作：
1.更改程序兼容性为windows7（无效）
2.右键以管理员身份运行（无效）
3.安装32位版本（无效）
4.安装微软商店版本（无效）
5.安装 VC2015（安装失败）
6.下载故障排除页dll压缩包，将所有 dll 放到 Snipaste 目录下（无效）
7.打开任务管理器，切换到 启动 标签页，找到 Snipaste 看是否被禁用了（显示已启用）

另，此电脑前日遇到了无法启动Photoshop的情况，表现同样为双击程序图标无法启动软件，**无任何提示窗口，任务管理器无相应进程**。后通过重新安装最新版本Photoshop解决，但覆盖安装最新版本Snipaste无法解决。

恳请开发者帮忙看看如何解决，感谢。

**Comment by liulex** [comment]
1. 免安装版的程序目录下的 `crashes` 文件夹是否有 `.dmp` 文件？
2. 新建一个本地账户，重新运行商店版/免安装版 Snipaste，能否启动？

**Comment by Tenorab** [comment]
非常感谢开发者如此迅速的回复！！！
1.免安装版的程序目录下的 crashes 文件夹是否有 .dmp 文件？
没有 crashes 文件夹
2.新建一个本地账户，重新运行商店版/免安装版 Snipaste，能否启动？
可以了！！！请问要如何在原本地账户上继续使用Snipaste呢？

**Comment by Tenorab** [comment]
补充一下，原本地账户，在windows**安全模式**下也是可以正常启动Snipaste的，目前只有这个软件受影响无法正常使用。想知道如何在**普通模式**下，用**原账户**继续使用软件。劳烦开发者分析解惑，感恩。

**Comment by liulex** [comment]
那么是其他程序导致 Snipaste 无法运行。
可以在**普通模式下**逐个关掉后台程序，直到 Snipaste 可以正常运行为止。

**Comment by wangyunhao993** [comment]
根据上面回答的第二个我也解决了同样的问题

**Comment by septs** [comment]
Replaced by #1391

**Comment by AndersonHJB** [comment]
推荐使用 32位的就可以直接解决.

**Comment by nowayfree** [comment]
> 那么是其他程序导致 Snipaste 无法运行。 可以在**普通模式下**逐个关掉后台程序，直到 Snipaste 可以正常运行为止。

win10 ，版本号21H2，操作系统版本19044.1645
初次安装snipaste，官网版本和微软商店版本均不能启动，类似楼主情况，无提示窗口；
管理员身份运行不能；
crashes 文件夹无 .dmp 文件；
新建本地账户，重新运行不能启动；
逐个关掉后台，不能正常运行
请开发者帮忙看看如何解决，谢谢！
