### ISSUE TITLE
Win10最近一次更新后，使用flu.x时截图颜色变色

### ISSUE THREAD

**Issue by Freddd13** [Snipaste/feedback#1392]
flux为护眼软件，win10更新前截图正常
![image](https://user-images.githubusercontent.com/50367552/73703830-3f0a6380-472c-11ea-9e88-eef6610566b7.png)
![image](https://user-images.githubusercontent.com/50367552/73703840-49c4f880-472c-11ea-897e-7f3e4f14031e.png)
![image](https://user-images.githubusercontent.com/50367552/73703865-5ea18c00-472c-11ea-89d2-992dc311d73c.png)

**Comment by Riajyuu** [comment]
这是正常的。。。。也是预料之中的结果。。

**Comment by liulex** [comment]
#1239
