### ISSUE TITLE
可否对贴图进行标注

### ISSUE THREAD

**Issue by juzi214032** [Snipaste/feedback#1393]
例如我从其他地方复制一张图标，想要对该图片进行标注，有没有什么办法，因为我觉得Snipaste的标注功能挺好用的

**Comment by liulex** [comment]
![](https://user-images.githubusercontent.com/2010459/73904242-571de680-48d6-11ea-8b66-60df3dfbf64a.png)

**Comment by juzi214032** [comment]
感谢
