### ISSUE TITLE
截图后，c键不可用，包括文字框和保存对话框。

### ISSUE THREAD

**Issue by yyk21** [Snipaste/feedback#1397]
截图后，c键不可用，包括文字框和保存对话框。

**Comment by liulex** [comment]
虚拟机？

**Comment by solymr** [comment]
我也遇到了这个问题。win10专业版1909，snipaste pro 2.3.5。其实这个问题在最早的1.x版本中就存在，我升级到pro也没有解决。

就表现在截图后的编辑页面，点文字框，输入文字的时候没法输入字母c，无论大小写，无论中英文输入法。其他字母貌似都正常。

不是虚拟机。

**Comment by liulex** [comment]
@solymr 这里提供了解决方法：https://github.com/Snipaste/feedback/issues/640#issuecomment-346732910

同时相应的文档页面也说明了原因，一般只出现在虚拟机/远程链接等有第三方软件合成了键盘消息的情况下。

**Comment by solymr** [comment]
搞定了，非常感谢
