### ISSUE TITLE
开启屏幕触发角后,解锁和UAC操作会自动触发截图

### ISSUE THREAD

**Issue by Hsnico** [Snipaste/feedback#1398]
当我将右下角设置为snip时,每次解锁电脑以及UAC操作,都会触发截图
已尝试过重置应用,版本为Windows 商店版
![20200209_125947](https://user-images.githubusercontent.com/59398077/74096624-31921680-4b3c-11ea-8ce2-07e6e9ad56c3.jpg)

**Comment by liulex** [comment]
谢谢反馈，下个版本会修复。
