### ISSUE TITLE
win10系统，微软商店下载的2.28版本。保存截图时图像另存为窗口会退出，无法保存图片

### ISSUE THREAD

**Issue by doubidan666** [Snipaste/feedback#1399]
保存截图时图像另存为窗口会退出，无法保存图片，但是复制图片功能正常。图像另存为窗口退出后，程序还在运行没有退出，但是点击状态栏小箭头显示隐藏的图标后发现程序会马上退出。
尝试过卸载重装没有作用，估计是电脑环境有问题，但是找不到。不知道作者大大根据描述能不能发现问题。谢谢！

**Comment by liulex** [comment]
#1361
遇到这种情况的用户应该不多，可能跟系统版本/系统设置相关，我暂时没啥头绪。
你们可以自己通过升级系统版本/新建本地账户等方式自己排查一下，不然就等我下次更新再试试。

**Comment by Dang-h** [comment]
> #1361
> 遇到这种情况的用户应该不多，可能跟系统版本/系统设置相关，我暂时没啥头绪。
> 你们可以自己通过升级系统版本/新建本地账户等方式自己排查一下，不然就等我下次更新再试试。

请问微软商店内购的专业版如何升级到v2.3

**Comment by liulex** [comment]
@Dang-h 过几天就发布了。

**Comment by BOSDGM** [comment]
win10系统, 最近更新版本后一直都会闪退, 当前版本2.3.1.   只要点击保存图片就会卡死退出

**Comment by liulex** [comment]
和一位用户测试了下，一路回退了几个版本，直到 2.0 都还是有问题，所以应该不是 Snipaste 更新的问题，应该是某个系统设置/系统更新补丁/其他程序 造成的。。

**Comment by liulex** [comment]
破案了，是企业微信里的微盘导致的，但似乎最新版微盘的没事。
出问题的 dll 是 `WeDrivePlugin64_xx.dll`，其中 xx 是版本号，我测试过 29 没事。
所以……要么卸载微盘（重启系统，并确保 `WeDrivePlugin64_xx.dll` 已经删除），要么想办法更新微盘。

**Comment by doubidan666** [comment]
> 破案了，是企业微信里的微盘导致的，但似乎最新版微盘的没事。
> 出问题的 dll 是 `WeDrivePlugin64_xx.dll`，其中 xx 是版本号，我测试过 29 没事。
> 所以……要么卸载微盘（重启系统，并确保 `WeDrivePlugin64_xx.dll` 已经删除），要么想办法更新微盘。

果然是，把微盘卸载掉以后就恢复正常了。这个问题困扰了我好久终于解决了，作者大大给力！

**Comment by solidsnake1743** [comment]
目前企业微信3.0.13.1203。没有单独装过微盘。
企业微信目录下面 X:\Program Files (x86)\WXDrive\extensions\x64下面
WeDrivePlugin64_27.dll 和 WeDrivePlugin64_29.dll 都有。
怎么破？

**Comment by solidsnake1743** [comment]
解决。我把企业微信卸载、重启后，X:\Program Files (x86)\WXDrive\extensions\x64\WeDrivePlugin64_29.dll 还是残留删不掉。
于是重新安装企业微信。到X:\Program Files (x86)\WXDrive\  下面单独运行Uninstall，问题解决。又可以愉快的使用snipaste了。
