### ISSUE TITLE
关闭贴到桌面上的截图的时候出现别的截图被一并关闭的情况/Other pinned screenshot get closed when trying to close a pinned screenshot

### ISSUE THREAD

**Issue by ccchan49** [Snipaste/feedback#1400]
使用右键菜单关闭一张贴到桌面上的截图A的时候会导致在A之后最后贴上的贴图一并被关闭，而使用双击关闭功能则不受影响
举例：
截图A并贴到桌面->截图B并贴到桌面->截图C并贴到桌面->右键贴图A，在弹出的菜单栏选择关闭贴图->A与C被一并关闭
-双击贴图A的话没有这种情况
-关闭贴图B不会导致A被关闭
-关闭贴图C不会导致B被关闭

Version: 2.24-Beta
用snipaste很久了。。最近没动过设置，检查过没有相关选项，不知道是不是bug

**Comment by liulex** [comment]
2.2.4 确实存在这个 bug，但商店版 2.2.8 已经没有这个问题，近期会更新桌面版。
