### ISSUE TITLE
[Feature] 移植并免费开放QQ9.2.x中内嵌截图新增的功能。

### ISSUE THREAD

**Issue by wdhwg001** [Snipaste/feedback#1401]
> This time, it's personal.

在Snipaste借鉴QQ截图，并在功能性上大幅超越QQ截图多年后，QQ进行了充满腾讯味道的反向借鉴，并针对性——甚至可以说颇具敌意的开放了某些Snipaste的收费版本中才有的功能。

新QQ截图：
![image](https://user-images.githubusercontent.com/8943519/74303966-8761fb00-4d96-11ea-9374-0ef5ea837d69.png)

新QQ贴图（钉在桌面上）：
![image](https://user-images.githubusercontent.com/8943519/74304035-c85a0f80-4d96-11ea-952d-cdc36c18b194.png)

所以，或许是时候将这场攀比之战继续打起来了。

截至Snipaste 2.2.8，与QQ 9.2.x相比，Snipaste暂缺以下内容：

* 【免费开放了Snipaste的Pro功能】二次编辑标注形状
* 序号笔工具
   ![image](https://user-images.githubusercontent.com/8943519/74304526-35ba7000-4d98-11ea-93bc-49f1ef7bc5fd.png)
* 长截图工具（轮询截图，鼠标滚轮穿透）
   ![image](https://user-images.githubusercontent.com/8943519/74304651-98137080-4d98-11ea-9d98-7728e3122d75.png)
* 屏幕识图（较难移植）
   ![image](https://user-images.githubusercontent.com/8943519/74304483-17ed0b00-4d98-11ea-89a1-027866997b9e.png)
* 直接使用QQ发至手机（难以移植）
   ![image](https://user-images.githubusercontent.com/8943519/74304744-e4f74700-4d98-11ea-8b7d-a1446b8efe01.png)
* 直接使用QQ收藏（可通过支持第三方笔记类软件以支持）
   ![image](https://user-images.githubusercontent.com/8943519/74304887-3d2e4900-4d99-11ea-8f41-af62fab94ab6.png)

而QQ 9.2.x借鉴Snipaste的功能项较多，且列出它意义不大，所以暂不列出。

希望Snipaste可以重新领跑这次攀比性竞争事件。

**Comment by Vstory** [comment]
序号笔功能，强烈需求啊

**Comment by kmahyyg** [comment]
序号笔功能 ++

**Comment by septs** [comment]
Duplicate of #1476
