### ISSUE TITLE
#MacOS 中可以将截图发送到应有程序中（QQ，微信，编辑器等）

### ISSUE THREAD

**Issue by wjwei-handsome** [Snipaste/feedback#1402]
##如题，是否可以将截图或者存在的贴图发送到应用程序，比如可以拖动发送给QQ好友或者微信好友，比如可以把贴图发送到编辑器
PS：虽然可以通过复制粘贴的方式来完成如上操作，但是拖动的话更符合macOS的设计理念

**Comment by septs** [comment]
Duplicate of #159
