### ISSUE TITLE
有没有可能增加一个HEX代码识别功能？放大镜显示HEX值的相反功能

### ISSUE THREAD

**Issue by dainchyin** [Snipaste/feedback#1403]
就是像放大镜里的鼠标下颜色的HEX值自动显示功能的反向实现，在鼠标放在16进制的HEX编码上能识别HEX代码并显示其代表的颜色的图像（一个纯色小方块）？或者单独一个快捷键功能。
在编辑一些带有HEX值的代码时，不能立刻感知其真实颜色，需要来回复制粘贴有点麻烦，有这个功能的话就更方便快捷了。
可能有其他软件有这个功能，但如果snipaste能带一个就更方便了！
软件编程小(×N)白，如此功能在理论上就无可能实现，望见谅哈。谢谢

**Comment by septs** [comment]
Duplicate of #957
