### ISSUE TITLE
增加选项：1使截图能够置于其他窗口之下。 2.开机启动以后，上一次截图能够恢复显示在桌面上

### ISSUE THREAD

**Issue by A1bertY** [Snipaste/feedback#1404]
请增加以下选项：
1使截图能够置于其他窗口之下。 
2.开机启动以后，上一次截图能够恢复显示在桌面上

**Comment by linzyjx** [comment]
1：可以，但会在任务栏多一个窗口项
![image](https://user-images.githubusercontent.com/8017477/74544625-6a8a1b00-4f82-11ea-9d9c-69d5ccedbf92.png)
2：亲测可行
版本：2.2.8（Windows Store Pro）
