### ISSUE TITLE
贴图缩放功能改进

### ISSUE THREAD

**Issue by chenwei0930** [Snipaste/feedback#1405]
需要一个智能判断缩放方向的功能。目前贴图放大都是向右下角延伸，缩小向左上角。但是如果贴图位于屏幕右下角的位置时，缩放时内容会超出边缘，只能手动拖上去，操作多了很麻烦。如果能自动判断到达边缘，则继续放大则向左上方向放大，会友好很多。

那为什么不把贴图放屏幕左上角呢？因为顶部一半都是菜单栏，地址栏，标签栏，不能被遮挡。

**Comment by liulex** [comment]
![](https://user-images.githubusercontent.com/2010459/75036974-10430a00-54ee-11ea-8086-a970f2caa7d7.png)

**Comment by septs** [comment]
Duplicate of #1222
