### ISSUE TITLE
希望能对文本贴图进行文本编辑

### ISSUE THREAD

**Issue by shishirong** [Snipaste/feedback#1409]
比如在很多网站复制出来的文本都会带一些转载说明之类的小尾巴，这样直接贴图出来的文本文字并不是自己想要的，要是能文本编辑的话，就能更方便地使用了。而不是再打开文本编辑器、粘贴、编辑、再复制、再粘贴

**Comment by wade0564** [comment]
赞，也一直期待这个功能。

**Comment by septs** [comment]
Duplicate of #1068
