### ISSUE TITLE
远程桌面下，截图时不暗淡屏幕提高性能

### ISSUE THREAD

**Issue by kingron** [Snipaste/feedback#1411]
当在远程桌面下使用的时候，如果远程桌面连接网络速度不太好，那么会严重影响性能。
当开始截图的时候，屏幕会暗淡，并高亮选择的方框或者对象，因为整个屏幕刷新，会导致整个桌面画面数据重传，从而严重影响性能。

可否检测或者提供设置，就是说截屏的时候，不暗淡屏幕，只是给截图对象或者方框绘制边框即可？

**Comment by liulex** [comment]
![](https://user-images.githubusercontent.com/2010459/75109741-5371ba00-5661-11ea-9276-67de94303bd9.png)

**Comment by kingron** [comment]
这个隐藏比较深，一般人没想到，需要设置Alpha通道为0就可以了。
