### ISSUE TITLE
建议增加修改截图后快捷键的功能

### ISSUE THREAD

**Issue by yslhzj** [Snipaste/feedback#1412]
建议增加修改截图后快捷捷键功能,如下图所示:
![image](https://user-images.githubusercontent.com/29890756/75093538-84001800-55bd-11ea-85c9-7b2b0ec3a3cc.png)

虽然已ctrl+8的快捷键,在使用过程中,很有难用左手去按ctrl和 1,2,3,4,5等数字键, (右手正忙着操作鼠标,在截图上进行定位.) 如果能把ctrl 换成ALT  或增加自定义这几项的快捷键 就更好了.

**Comment by Geeyun-JY3** [comment]
Duplicate of #1859
