### ISSUE TITLE
【功能优化】使用自定义命令启动带阴影截图后，快捷键复制的并非带阴影截图

### ISSUE THREAD

**Issue by YongJie-Xie** [Snipaste/feedback#1413]
使用自定义命令【snip --shadow】启动截图后，使用内置快捷键【Ctrl+C】复制截图，复制的并不是带阴影的图片，建议根据参数优化该内置快捷键。

![image](https://user-images.githubusercontent.com/29311669/75099982-ef200d80-5602-11ea-9cca-98235632ea9a.png)

![image](https://user-images.githubusercontent.com/29311669/75099961-90f32a80-5602-11ea-95ba-860ee7f574f7.png)

**Comment by liulex** [comment]
感谢反馈，是我疏忽了，下周修复。
