### ISSUE TITLE
安装包下载速度过慢

### ISSUE THREAD

**Issue by Vstory** [Snipaste/feedback#1418]
下载速度，好慢。
官网点击下载，下载十几kb的跑，好慢。
![Snipaste_2020-02-26_15-45-50](https://user-images.githubusercontent.com/20795557/75323214-68dc2380-58af-11ea-95c4-ca42490896fd.png)

不好意思，刚才发错位置了。

**Comment by liulex** [comment]
现在应该有所改善了。

**Comment by Vstory** [comment]
> 现在应该有所改善了。


没有任何变化。
![Snipaste_2020-03-01_21-33-37](https://user-images.githubusercontent.com/20795557/75626678-6dcd0a00-5c04-11ea-9b46-2faaa81b1efc.png)

**Comment by Iridescent292** [comment]
有相同情况，之前在微博上留言了，官网就是404

**Comment by KazamaSion** [comment]
> 有相同情况，之前在微博上留言了，官网就是404

请问是访问官网 404，还是下载链接 404。下载链接是从英文还是中文网站进去的呢？

**Comment by Iridescent292** [comment]
> > 有相同情况，之前在微博上留言了，官网就是404
> 
> 请问是访问官网 404，还是下载链接 404。下载链接是从英文还是中文网站进去的呢？

docs.snipaste.com 这个页面一直404，然后下载桌面版一直没速度

**Comment by KazamaSion** [comment]
> > > 有相同情况，之前在微博上留言了，官网就是404
> > 
> > 
> > 请问是访问官网 404，还是下载链接 404。下载链接是从英文还是中文网站进去的呢？
> 
> docs.snipaste.com 这个页面一直404，然后下载桌面版一直没速度，中英文网站都一样

此前 404 是因为 raw.githubusercontent.com 局部地区被墙的缘故，现在已经替换好了，应该不会再有 404 的问题了。
下载速度也可能有所提升了。
