### ISSUE TITLE
可不可以实现QQ最新更新的功能:文字识别

### ISSUE THREAD

**Issue by carlsonlau** [Snipaste/feedback#1424]
最新的QQ版本，截图功能增加识别功能，方便了不少

**Comment by ZMacchiato** [comment]
+1

**Comment by sockbook** [comment]
+1，同求，或者放入专业版，这个功能花钱也值的

**Comment by Glume-9345** [comment]
+1，有一个文字识别会方便很多。

**Comment by herandingyi** [comment]
v2.3 (2020.02.20)
[PRO] Command Line Options now support multiple destinations, which means you can send the screenshot to another program (e.g. OCR programs)
这个在 2月20日已经 "实现"

**Comment by septs** [comment]
Duplicate of #188
