### ISSUE TITLE
mac os 安装 v2.3.1 Beta (2020.02.27) 之后程序打不开

### ISSUE THREAD

**Issue by zhuzhenting** [Snipaste/feedback#1426]
系统版本：mac os 10.15.3 
软件版本：v2.3.1 Beta (2020.02.27)
安装之后程序不能正常打开，卸载之后继续安装v1.16.2 Beta版本，依然不能打开

**Comment by xdxiaodong** [comment]
遇到同样的问题

**Comment by leotpp** [comment]
遇到同样问题+1
Mac OS:10.15.3
Snipaste Ver:v2.3.1 Beta
问题描述：
1、首次安装正常运行，赋予安全权限，功能正常。
2、重启后进去桌面后，活动监视器显示进程启动但任务栏并无图标出现。使用快捷键无法激活截屏功能。
3、活动监视器强制退出snipaste进程，再次拖拽dmg程序包到application文件夹执行「覆盖」动作，活动监视器显示进程开始运行，但任务栏图标依旧不出现。快捷键无法激活截图功能。

**Comment by zhuzhenting** [comment]
> 重启Mac后恢复正常

我重启后重装无效

**Comment by leotpp** [comment]
> 重启Mac后恢复正常

我今天关机一次，重启一次，现在正常了 😂

**Comment by liulex** [comment]
已更新到 2.4 Beta，问题应该已经干掉了。
