### ISSUE TITLE
【功能建议】：是否可以增加[将原始大小图像另存为]选项

### ISSUE THREAD

**Issue by Iridescent292** [Snipaste/feedback#1430]
如标题所示
使用场景：截图时不能马上判断是否需要保存（如看视频时），须在屏幕上贴图较多，所以会缩小贴图，但[图像另存为]选项默认是以当前图像大小保存的，须重新还原图像大小再保存。
希望可以如[复制原始大小图像]功能一样，增加一个[将原始大小图像另存为]选项。
![Snipaste_功能建议](https://user-images.githubusercontent.com/35626216/76157325-5a5cfa00-6142-11ea-8fdc-daa435fdb1cc.png)

**Comment by liulex** [comment]
好的，下个版本加上~
