### ISSUE TITLE
优化透明功能,白板功能

### ISSUE THREAD

**Issue by dyliu02** [Snipaste/feedback#1433]
增加功能: 透明白板模式下可以不开鼠标穿透而使用鼠标执行其他任务,
可以像截图一样创建一块大小合适的透明白板,从而可以直接在屏幕上贴出 箭头 图形(矩形,椭圆,直线)文字,可以不依赖于白板模式,
贴图可以部分透明,调节单个贴图中元素的透明度,增加像马赛克一样的透明块

**Comment by septs** [comment]
Duplicate of #1375
