### ISSUE TITLE
Snipaste does not contain any version number on macOS

### ISSUE THREAD

**Issue by core-code** [Snipaste/feedback#1434]
Snipaste does not contain any version number information on macOS. each apps is supposed to contain numeric version number information.

<img width="258" alt="Screenshot 2020-03-10 at 21 39 04" src="https://user-images.githubusercontent.com/1261954/76357265-a8772680-6317-11ea-998a-0e7b4a696e1a.png">

the problem is that the CFBundleVersion and CFBundleShortVersionString entries in your Info.plist file are missing.

**Comment by liulex** [comment]
Thanks for pointing this out. I will fix it in the next update :)
