### ISSUE TITLE
v2.3正式版 截屏选中区域后，按快捷键crtl+c 复制选中区域无效，按复制到剪贴板那个小按钮有效。

### ISSUE THREAD

**Issue by woxinbuji** [Snipaste/feedback#1437]
如题。
如下图：
![1](https://user-images.githubusercontent.com/21358414/76587075-beeecf00-651d-11ea-884e-9b1ba1ee9de5.png)

**Comment by woxinbuji** [comment]
已解决~ 软件冲突，本bug可以忽略了~谢谢！

**Comment by liulex** [comment]
@woxinbuji 请问下是哪个软件？

**Comment by woxinbuji** [comment]
是一个win10 五笔助手（http://wubi.aardio.com/），该软件已经通过升级版本解决了本冲突~

**Comment by woxinbuji** [comment]
是一个win10 五笔助手（http://wubi.aardio.com/），该软件已经通过升级版本解决了本冲突~

 

发件人: Le Liu <notifications@github.com> 
发送时间: 2020年3月20日 星期五 19:25
收件人: Snipaste/feedback <feedback@noreply.github.com>
抄送: woxinbuji <woxinbuji@sina.com>; Mention <mention@noreply.github.com>
主题: Re: [Snipaste/feedback] v2.3正式版 截屏选中区域后，按快捷键crtl+c 复制选中区域无效，按复制到剪贴板那个小按钮有效。 (#1437)

 

@woxinbuji <https://github.com/woxinbuji>  请问下是哪个软件？

**Comment by liulex** [comment]
谢谢！
