### ISSUE TITLE
请求开源

### ISSUE THREAD

**Issue by LeoWang2007** [Snipaste/feedback#1438]
请问可以放开源代码吗，我很想将你的程序移植在自己的程序中

**Comment by 911061873** [comment]
感觉你可以自己close了。

**Comment by LeoWang2007** [comment]
> 感觉你可以自己关闭了。

什么意思？

**Comment by stevenzhu25** [comment]
建议您去和QQ商量一下把他的截图模组开源......

**Comment by ChuHuaiJin** [comment]
哈哈哈哈，你是来秀智商的嘛？

**Comment by hengdai** [comment]
请求开源

**Comment by ChuHuaiJin** [comment]
> 
> 
> 请求开源

建议您去和QQ商量一下把他的截图模组开源......

**Comment by hengdai** [comment]
> > 请求开源
> 
> 建议您去和QQ商量一下把他的截图模组开源......

为啥？
