### ISSUE TITLE
macOS版Snipaste截图保存时，保存格式的控件层级过高，导致遮挡了保存位置控件的下拉选项

### ISSUE THREAD

**Issue by fkeway** [Snipaste/feedback#1439]
macOS版Snipaste截图保存时，保存格式的控件层级过高，导致遮挡了保存位置控件的下拉选项。
如下图：
![Snipaste截图保存的bug](https://user-images.githubusercontent.com/12114653/76620971-59c0cb00-6569-11ea-9977-5ede1b402925.png)

**Comment by liulex** [comment]
谢谢反馈，会在下个版本修复~
