### ISSUE TITLE
Right-click Snipaste systray icon does not open menu

### ISSUE THREAD

**Issue by Stephan-P** [Snipaste/feedback#1441]
- Snipaste is loaded in the systray
- Right touchpad-click the systray icon
- In the past this used to open the menu providing access to the settings
- Now it just starts the Snip action as if I've hit F1 or the Left touchpad-click
- And there's no way to get to the settings

Could it be that some laptop touchpads are not handled correctly?

**Comment by liulex** [comment]
The action for right-click is configurable in the Preferences for the PRO version:
![](https://user-images.githubusercontent.com/2010459/76822622-9e3fb580-684c-11ea-86d7-ffceba184c59.png)

Maybe you just had it mistakenly set.
You can press Ctrl + Shift + P on the image window to show the Preferences Dialog.

**Comment by Stephan-P** [comment]
Ctrl-Shift-P does not do anything.
Is there a way to access the settings file and manually reset it?

**Comment by liulex** [comment]
@Stephan-P 
I would not recommand resetting the app sicne it deletes not only the settings but also the image windows and snipping history.

To show the Preferences Dialog, you are to press Ctrl + Shift + P **on the floating image window of Snipaste**.

**Comment by Stephan-P** [comment]
> To show the Preferences Dialog, you are to press Ctrl + Shift + P on the floating image window of Snipaste.
I'm sorry. I cannot reproduce this. Not during snip and also not while having a snip pinned to the screen.

Reset app worked perfectly fine for me.

**Comment by liulex** [comment]
Click the pinned screenshot (to make it active), then Ctrl + Shift + P.

**Comment by Stephan-P** [comment]
I've tried again and I'm afraid I have to insist: not on my Windows 10 PC.
(Windows Store version)
