### ISSUE TITLE
希望增加一键截全屏并快速保存到文件夹的功能

### ISSUE THREAD

**Issue by XZMK** [Snipaste/feedback#1442]
比起系统自带的prtscr键，多了一个自动保存的功能
例如按下F2键，会截取当前全屏并且自动保存到之前设定的文件夹，同时屏幕右下角出现缩略图。除了按F2键之外不需要其他任何操作。
有时候工作需要面对快速变化的表，如果正常截图，截图后需要按crtl+a  shift+ctrl+s,后面的变化可能会错过

**Comment by Geeyun-JY3** [comment]
利用专业版的将命令行参数与全局快捷键绑定应该是能做出你想要的这功能的，参考文档：https://docs.snipaste.com/zh-cn/command-line-options

**Comment by Geeyun-JY3** [comment]
实测以下参数即可实现全屏并快速保存到文件夹：

```
snipaste.exe snip --full -o quick-save
```

因为专业版才支持将命令行参数与全局快捷键绑定，所以要想实现你想要的「一键截全屏并快速保存到文件夹」需要专业版
https://docs.snipaste.com/zh-cn/pro?id=b-%e6%9b%b4%e8%87%aa%e7%94%b1%e7%9a%84%e5%ae%9a%e5%88%b6%e5%8c%96
