### ISSUE TITLE
侧边暂放栏

### ISSUE THREAD

**Issue by kasusa** [Snipaste/feedback#1445]
我很喜欢用这个贴图的功能.
但是有的时候图会挡住想要用的东西.这时候想要把它暂时放起来
但是马上又会有用.
所以我设计了如下的方案.
* 把图片托向桌面右侧更外面就会开启侧边暂时放置栏
* 暂时放置栏可以放多张图片.列表缩略图显示
* 随时可以点击右侧的小图标把暂时放置栏的东西拿出来
* 暂时放置栏如果没有东西,他就不会显示了.

下面是我设计的图:(如果打不开请复制链接打开)
![1.png](http://ww1.sinaimg.cn/large/0083vuQJly1gd07mw76hvj31hc0u0u0y.jpg)
![2.png](http://ww1.sinaimg.cn/large/0083vuQJly1gd07n2lzn3j31hc0u04qr.jpg)
![3.png](http://ww1.sinaimg.cn/large/0083vuQJly1gd07n89jcaj31hc0u07wj.jpg)
![4.png](http://ww1.sinaimg.cn/large/0083vuQJly1gd07ncr44jj31hc0u04qr.jpg)

**Comment by liulex** [comment]
谢谢你画的设计图！

对于 `想要把它暂时放起来，但是马上又会有用` 这个场景，我觉得专业版的触发角功能是可以胜任的，把鼠标放到屏幕一角就隐藏/显示所有贴图。
