### ISSUE TITLE
Mac截图锯齿严重

### ISSUE THREAD

**Issue by w4o** [Snipaste/feedback#1446]
系统及硬件信息：
![image](https://user-images.githubusercontent.com/13061300/77221057-183fa980-6b81-11ea-8d49-7f504f78e29e.png)
软件设置：除快捷键以外均为软件默认配置
第一张图为Snipaste，第二张图为系统自带截图工具
![image](https://user-images.githubusercontent.com/13061300/77221005-9f405200-6b80-11ea-8c3e-6bd5f16d3593.png)
![image](https://user-images.githubusercontent.com/13061300/77221024-c72fb580-6b80-11ea-9c5f-2551b0c1a939.png)

**Comment by liulex** [comment]
应该是 [文档](https://docs.snipaste.com/zh-cn/troubleshooting?id=%e6%88%aa%e5%9b%be%e6%a8%a1%e7%b3%8a) 提到的情况。
