### ISSUE TITLE
mac下勾选选项后 按ESC依然无确认提示直接关闭截图

### ISSUE THREAD

**Issue by relin1226** [Snipaste/feedback#1448]
mac勾选了设置里的Ask for confirmation when Esc is pressed.
但是还是会直接关闭截图，甚至会直接关闭设置窗口

**Comment by relin1226** [comment]
###

**Comment by relin1226** [comment]
前面看到有人问过了重复提问

**Comment by liulex** [comment]
你描述得清楚一些，请问软件版本是？我 2.3.1 Beta 没有问题。

**Comment by relin1226** [comment]
> 你描述得清楚一些，请问软件版本是？我 2.3.1 Beta 没有问题。

也是2.3.1-Beta
系统版本是Catalina 10.15.3

**Comment by liulex** [comment]
那我这边确实无法重现，需要提供可供重现的更多信息…

**Comment by relin1226** [comment]
> 那我这边确实无法重现，需要提供可供重现的更多信息…

我要怎么提供信息呢？

**Comment by liulex** [comment]
1. 贴出配置文件（首选项-常规-配置文件存储位置-打开-另存为）
2. 将全过程（确认选项已勾选-截图-按 Esc）录屏
如以上文件不方便公开，可发送到 <snipaste.app@gmail.com>。

**Comment by relin1226** [comment]
已发送

**Comment by liulex** [comment]
你录屏展示的是对贴图按 <kbd>Esc</kbd>，请注意区分 **截图** 和 **贴图**。
这个选项是在 **截屏** 下面的，因此只控制截屏时按 <kbd>Esc</kbd> 的行为，对贴图按  <kbd>Esc</kbd> 是不会有提示的。

**Comment by relin1226** [comment]
好的了解了 谢谢！ 这个稍微有点不方便，有时候习惯性操作连按ESC的时候会把我所有贴图都退出了，希望之后有望改进，打扰了
