### ISSUE TITLE
添加文字会溢出截图区域

### ISSUE THREAD

**Issue by fance95** [Snipaste/feedback#1450]
1.添加文字时候，文字会溢出截图区域，希望可以像QQ那样，检测到文字溢出时候自动换行。
2.文字大小不用鼠标拖拽边角放大缩小，可以像QQ那样，选择文字之后可以改变字体大小，或者选择文字之后，按住“Ctrl”键，滑动鼠标滑轮来放大缩小文字。

**Comment by liulex** [comment]
1. 我认为 QQ 的自动换行虽然在一些情况下会有用，但在文字比较多的时候是非常不利于排版的，弊大于利。
2. 以后可能增加下拉框。

**Comment by fance95** [comment]
感谢您的回复，我觉得可以做一个选项，让用户自己选择。还有就是我感觉 QQ现在截图的功能挺好的 功能多样化。可以长截图，录屏，文字识别 还可以添加序号，如果可以 可以做成他们这样。
希望snipaste 越做越好！

发自我的iPhone

**Comment by liulex** [comment]
做另一个 QQ 截图，意义何在呢？我觉得您可以直接使用 QQ 截图的~

**Comment by fance95** [comment]
但是你们的添加马赛克是可以用矩形框选的，还有添加高光部分，添加线段，滚轮就可以改变粗细，这些功能 是QQ没有的。😂 这就是我选择snipaste的原因 这个功能比QQ强大。

发自我的iPhone
