### ISSUE TITLE
请求增加延时截图功能

### ISSUE THREAD

**Issue by cchenga** [Snipaste/feedback#1451]
场景：需要截图一个弹出提示框，这个提示框只有在鼠标指针指在某个地方的时候才能出来，按任何键这个框都消失了，不能截到这个。
期望行为：先按下截图快捷键，然后延时几秒触发截图，比如五秒，在这个五秒的时间里我就可以把鼠标指向那个地方准备好

**Comment by liulex** [comment]
![](https://user-images.githubusercontent.com/2010459/77503602-f869f780-6e98-11ea-83ce-d2fd2033187a.png)

**Comment by cchenga** [comment]
找到了，非常感谢！
一点疑惑，这个选项是在勾选了 "增强版托盘菜单" 之后出现的，然鹅这些在首选项设置里面并没有找到，有种游戏中隐藏关卡的感觉。
我个人理解： 托盘菜单选项的设置应该是所有设置的一个子集，增强/快捷 设置选项 应该都可以在首选项里找到。 
FYI

**Comment by liulex** [comment]
在 首选项 - 控制 - 全局快捷键 里面有啊..

**Comment by cchenga** [comment]
👌， 我理解你的设计了。
你的设计是： 按快捷键 -> 出现自定义截图设置 -> 然后 设置 + 截图
我之前的预期是：设置好自定义 -> 按快捷键 -> 直接按照自定义设置截图 
这样就不用每次都出现自定义设置，所以我一直在首选项中找自定义设置。

**Comment by LinTeX9527** [comment]
> 👌， 我理解你的设计了。
> 你的设计是： 按快捷键 -> 出现自定义截图设置 -> 然后 设置 + 截图
> 我之前的预期是：设置好自定义 -> 按快捷键 -> 直接按照自定义设置截图
> 这样就不用每次都出现自定义设置，所以我一直在首选项中找自定义设置。

+1
