### ISSUE TITLE
请求增加截取长图-增加截图文件命名规则-增加截图库管理显示功能

### ISSUE THREAD

**Issue by sinfee** [Snipaste/feedback#1452]
请求增加长图功能，对于有些网站或是文档较长的情况下，多次截图进行拼接太累了
请求增加截图文件命名规则，支持按应用程序名称、窗口名称命名
请求增加截图的库管理和显示功能，类似snapit

**Comment by Geeyun-JY3** [comment]
- 长截图重复：#19
- 目前支持按窗口名称命名：#1589
- 截图的库管理和显示功能（说的是 Snagit 吧）：#695、#1029、#1060（开过就别再开了吧……）、#486、#1104
