### ISSUE TITLE
linux版本何时上线啊：）

### ISSUE THREAD

**Issue by pch9520** [Snipaste/feedback#1454]
急需一个linux版本的贴图软件，加油啊！

**Comment by Pinnsvin** [comment]
我觉得可以关注下flameshot https://github.com/lupoDharkael/flameshot 这个项目，基本上能在linux上替代snipaste

**Comment by pch9520** [comment]
我尝试这个了，但是这个截图工具不能让截图直接贴在屏幕上啊

**Comment by lsyxin** [comment]
同样期待一个linux版本  深度截图没这个好用

**Comment by Pinnsvin** [comment]
> 我尝试这个了，但是这个截图工具不能让截图直接贴在屏幕上啊

能啊，小钉子图标

**Comment by pch9520** [comment]
> > 我尝试这个了，但是这个截图工具不能让截图直接贴在屏幕上啊
> 
> 能啊，小钉子图标

我每个图标都按过去了，都不可以啊

**Comment by Pinnsvin** [comment]
> 
> 
> > > 我尝试这个了，但是这个截图工具不能让截图直接贴在屏幕上啊
> > 
> > 
> > 能啊，小钉子图标
> 
> 我每个图标都按过去了，都不可以啊

我使用的桌面环境是gnome3，其他环境没有尝试过

**Comment by pch9520** [comment]
继续蹲一个linux版

**Comment by wyg1997** [comment]
> 我尝试这个了，但是这个截图工具不能让截图直接贴在屏幕上啊

@pch9520 那个钉子功能可能没有打开，在软件配置中打开就行了。我也是刚刚才试用了一下，发现确实还不错。

**Comment by septs** [comment]
Duplicate of #711
