### ISSUE TITLE
长截图

### ISSUE THREAD

**Issue by Xuxing2019** [Snipaste/feedback#1456]
希望添加一个长截图功能，否则还没有QQ自带的截图工具强！

**Comment by lingxd** [comment]
我也是希望增加这个功能

**Comment by HaleShaw** [comment]
如果这个功能添加上了，就可以干掉一大片其他截图软件了。
大家就都可以放心转移到Snipaste上了。

**Comment by Xuxing2019** [comment]
确实如此!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"HaleShaw"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月10日(星期五) 下午3:46
收件人:&nbsp;"Snipaste/feedback"<feedback@noreply.github.com&gt;;
抄送:&nbsp;"Mc"<104206034@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Snipaste/feedback] 长截图 (#1456)





 
如果这个功能添加上了，就可以干掉一大片其他截图软件了。
 大家就都可以放心转移到Snipaste上了。

**Comment by septs** [comment]
Duplicate of #19
