### ISSUE TITLE
贴图多选功能

### ISSUE THREAD

**Issue by Trzeth** [Snipaste/feedback#1461]
当使用鼠标选中一个贴图后，按住Ctrl去选择另一个贴图时，之前选中的贴图并没有保持选中状态。
感觉不是很符合使用习惯，应该是个bug吧...？

![GIF](https://user-images.githubusercontent.com/17211844/78417097-58af2500-7661-11ea-9a10-52d50ee860a9.gif)

如图

App version:
Platform: Microsoft Store PRO 2.3.2

**Comment by liulex** [comment]
的确是 bug，感谢反馈，会在下次更新修复。

**Comment by Trzeth** [comment]
感谢这么快就解决了 但是好像触发了新的bug
![GIF](https://user-images.githubusercontent.com/17211844/78742288-27e72c80-798e-11ea-8929-c097a7f5242a.gif)
如图 
第一次选中了三个贴图 但是当右键后 变成仅选中最后一个贴图
第二次在选中三个贴图后按住Ctrl键拖动最后一个贴图移动后 三个贴图都变成选中状态后 再右键不触发bug

另外想建议当按住Ctrl键选择贴图后可以将三个贴图都在左上角进行标记 而不是前两个贴图 最后一个仅仅加了阴影（见第一次操作）。

**Comment by liulex** [comment]
确实现在多选操作出现了一些问题，我晚上看看，尽快修复。

**Comment by liulex** [comment]
已更新修复。

**Comment by liulex** [comment]
@Trzeth 根据其他用户的反馈（如 #1563）以及我自己的使用体验，似乎这个"特性"还是移除掉比较自然？
因为当前激活的贴图并不像已被多选的贴图一样明显，进行多选操作时其实并不期望它会被选中。

**Comment by Trzeth** [comment]
@liulex  确实当前激活的贴图显示不是很明显
其余的就看个人使用喜好了吧
