### ISSUE TITLE
按住shift仍无法绘制正方形和圆形图案

### ISSUE THREAD

**Issue by Pih1989** [Snipaste/feedback#1462]
截图绘制图形，按住shift,仍无法锁定绘制正方形和圆形。绘制水平、竖直和45°的直线的功能按住shift可正常使用。

软件版本：2.3.0 beta
运行平台：Windows 10

**Comment by liulex** [comment]
感谢反馈，2.3.0 Beta 版本在处理一些逻辑的时候，不小心把 Shift 的逻辑从免费版去除了，会在下次更新修复的。
