### ISSUE TITLE
请求增加动态图缩放设置

### ISSUE THREAD

**Issue by xiaobocai13** [Snipaste/feedback#1463]
大佬您好，请问是否可以在snipaste的设置里增加“鼠标滑轮缩放动态图”和“鼠标滑轮调整动态图播放速度”两个选项？
这样使用者可以在“只要缩放动态图功能”和“只要保存到本地的原图质量”这两个中取舍。
毕竟snipaste贴出的动态图不能缩放感觉有点难受

**Comment by liulex** [comment]
如果加了动态图缩放，在另存贴图的时候用户会期望保存的 GIF 也是缩放过的，但 Snipaste 目前还无法写 GIF 文件。

**Comment by chenyue314** [comment]
今天突然发现，也没法缩放，求增加缩放

**Comment by septs** [comment]
Duplicate of #1222
