### ISSUE TITLE
微软商店2.3.3贴图多选问题

### ISSUE THREAD

**Issue by L-Trump** [Snipaste/feedback#1468]
软件版本：微软商店2.3.3
新版本更新后，ctrl多选无法选中点击的贴图，在选择其他贴图时会被选上，感觉是[#1461](https://github.com/Snipaste/feedback/issues/1461)的锅。在选择第一个时蓝色角标会一闪而过，GIF里没表现出来，感觉是鼠标单击当前和单击下一个贴图重复判断了。
![bug](https://user-images.githubusercontent.com/37738631/78845284-bfa25480-7a3a-11ea-9d23-524ebdc68b75.gif)

**Comment by liulex** [comment]
已更新修复。
