### ISSUE TITLE
希望能在贴图增加类似PPT中的透明色功能

### ISSUE THREAD

**Issue by Delete56** [Snipaste/feedback#1471]
希望能在贴图中增加对单一颜色设为透明的功能，平时贴图单纯的改变整体透明度效果很不理想，如果能借鉴一下Powerpoint中对图片的“设置透明色”进行处理会方便图片主要信息的阅读。
![image](https://user-images.githubusercontent.com/31091702/78881352-44b45a80-7a89-11ea-8787-fe343358e3ab.png)
谢谢！希望能被采纳！

**Comment by septs** [comment]
Duplicate of #1375
