### ISSUE TITLE
截图自带边框

### ISSUE THREAD

**Issue by GitACzero** [Snipaste/feedback#1474]
利用截图做笔记时候，粘贴到word中又要再次给图片加上边框，不然有些白色区域的就显得很空。也不美观。这个边框的功能在贴图上有，但是直接截图粘贴没有。

**Comment by xsgteamx** [comment]
个人感觉不是刚需,你的word可以自己加

**Comment by liulex** [comment]
专业版可以加阴影：
![](https://user-images.githubusercontent.com/2010459/79590348-783a5900-8109-11ea-9451-ce7c27f88cda.png)

**Comment by xucongli1989** [comment]
我使用截图软件很多年了，从国产的红**截图（广告多），到 GreenShot（标注不方便），再到 PicPick（繁琐） ，直到现在发现这个软件（很方便）。于是把 PicPick 卸载掉了。强烈建议加上默认边框的功能，可以参考 PicPick 中的特效，并且应该可以快速设置带边框与不带边框。

我个人的使用场景是经常邮件回复带有截图的内容，粘贴后的截图白色区域与邮件背景相同导致不协调。并且，无法从肉眼上区分图片的占用面积。

我看了一下专业版，也没有这个功能。相反，这个软件的很多设置我觉得并不是刚需，希望项目组能把这个功能考虑一下。感谢！

**Comment by liulex** [comment]
@xucongli1989 上一条回复不是说了专业版可以加截图阴影么..
[专业版的[介绍页面](https://docs.snipaste.com/zh-cn/pro)目前没有更到最新，需要加上[更新日志](https://docs.snipaste.com/zh-cn/changelog)里带 `[专业版]` 的条目。

**Comment by xucongli1989** [comment]
阴影和边框是一个东西吗？

**Comment by liulex** [comment]
阴影是边框的一种吧？况且你也说需要解决的是

> 粘贴后的截图白色区域与邮件背景相同导致不协调。并且，无法从肉眼上区分图片的占用面积。

阴影不能胜任么？也比边框更美观啊。
单纯加纯色边框，你在贴图上用矩形工具右键点一下贴图就可以了。
