### ISSUE TITLE
新版QQ里的截图有很多不错的功能可以借鉴

### ISSUE THREAD

**Issue by hooray** [Snipaste/feedback#1476]
比如：
- 长截图，通过滚动鼠标可以截取某个区域的长图，这个很实用（很希望开发者能增加这个）
- 序号笔，我的理解是可以快速给图片上加步骤提示和注释
- 识别文字，这个虽然有其它工具可以代替，但如果有自带，可以解决一些轻量级用户的需求

**Comment by kannad** [comment]
序号笔+

**Comment by chensjiu** [comment]
snipaste的很多功能，新版qq的截图都有了

**Comment by flugel-Jibril** [comment]
序号笔+
截长图+

**Comment by hooray** [comment]
@chenrylee 看了你在几个 issue 里的回复，但凡大家提点功能需求上的建议和诉求，你都是在劝退，不知道你在这里想干什么。
既然你在 #1495 里提到 `Snipaste就是个单纯的截图+标注软件` ，那我想问什么叫单纯的截图和标注？长截图不算单纯的截图？序号笔不算标注？
不想和你杠，加不加是作者考虑的事，如果是担心软件太臃肿，可以考虑非核心功能以插件的形式集成，或者增加开关。何况我提的功能从 issus 里看，也不见得只是我个人的诉求。如果很多人都有这诉求，是不是可以考虑做为核心功能开发。

**Comment by xsgteamx** [comment]
如果QQ截图能够独立出来我就考虑一下,但是我更希望用Snipaste,也希望他能有这样先进的功能,谢谢!请跟进一下!

**Comment by xsgteamx** [comment]
讲真的 长截图太方便了!!!,哪怕不能GIF录制,能够长截图也很棒呀,序号笔也是,就算收费也愿意用

**Comment by xsgteamx** [comment]
GIF的话可以考虑别的工具

**Comment by septs** [comment]
Duplicate of #19 
Duplicate of #188 
序号标记已实现

**Comment by septs** [comment]
> > 序号标记已实现
> 
> 这个是专业版的功能吗？我并没有在 Pc 版上看到。

Duplicate of #227
