### ISSUE TITLE
V2.3.4版本超级截图在AUTOCAD中失效

### ISSUE THREAD

**Issue by Delete56** [Snipaste/feedback#1477]
在AUTOCAD 2017界面上无法使用超级截图（在AUTOCAD 2019版中正常使用），之前版本可以正常使用，超级截图按键改为组合键后问题依然存在，不知道是不是这个版本的BUG。望修复，谢谢了！

软件版本：
运行平台：微软商店 / Windows 10 1909
软件版本：微软商店版 V2.3.4 专业版

**Comment by liulex** [comment]
2.3.4 商店版有个 bug，开机重启后 Snipaste 没有管理员权限，你先手动以管理员权限运行即可。
我会在下个版本修复，谢谢反馈。
