### ISSUE TITLE
macos 10.15.2 bug

### ISSUE THREAD

**Issue by llg38456** [Snipaste/feedback#1478]
软件版本：
运行平台：微软商店 / Windows 桌面 / macOS
某一天，我在设置快捷键的时候，按了Command+q 导致退出应用之后。
发现无法再启动应用（在应用程序里双击图标，并没有反应）

于是我卸载之后重装，应用可以打开了，但是当我想进入首选项设置的时候，发现点击无反应。

目前菜单里除了贴图-创建组有反应（跳出窗口提示填入组名）以外，其他都没有反应，包括退出。

而我使用截图的快捷键，是可以正常截图的。

macos 没法对应用做彻底的卸载，每次重装都保留了之前的应用设置，所以目前我找不到方法可以修复。

**Comment by llg38456** [comment]
应用版本为官网最新版

**Comment by liulex** [comment]
非常感谢你的详细描述，刚刚已发布 2.3.5 Beta，应已修复该问题。
