### ISSUE TITLE
macOS Mojave 14.6 无响应

### ISSUE THREAD

**Issue by NoirJ0e** [Snipaste/feedback#1481]
应用程序提醒升级， 升级后启动时状态栏图标没有出现， 活动监视器里面显示snipaste无响应， 重新安装官网下载的0.2.3.5后可以打开， 10分钟后再次不行， 且重新安装无效
App version:
Platform: Microsoft Store / Windows Desktop / macOS

**Comment by liulex** [comment]
重启系统？

**Comment by sxd1140** [comment]
10.15.3一样 重启系统后正常
