### ISSUE TITLE
多图组合编辑

### ISSUE THREAD

**Issue by fastfading** [Snipaste/feedback#1482]
一般的截图，qq截图就够了。
能搜到这个工具，因为其具备一个其他截图工具不具备功能：组合多张截图。
但目前这个功能还不完善，有以下几点
1. 多张图片层级结构，先后顺序无法设置。大图盖住小图后，小图无法选中。
2. 没有跨图的标注，例如图1中A点到图2中B点的箭头
3. 当多张图编辑完成后，没发作为一个整体导出剪切板。

我的建议是，搞一个粘贴窗口，多个截图可以放进去一起编辑。
里面所有截图和标注元素可以调整结构层级，先后顺序。
类似一个画图PS
PS工具当然可以做这个，但是PS 太重了。
用户需要轻量级的应用。

**Comment by fastfading** [comment]
其实 PPT 也能做到以上这些，

**Comment by liulex** [comment]
加了这个，会让 Snipaste 太重了……

**Comment by fastfading** [comment]
> 加了这个，会让 Snipaste 太重了……

不加这个我觉得微信截图就够用了。

**Comment by liulex** [comment]
那挺好的，就用微信截图吧～
