### ISSUE TITLE
放大镜能不能默认打开？Mac下没有打开放大镜的快捷键

### ISSUE THREAD

**Issue by ymyz1229** [Snipaste/feedback#1483]
作为一个设计师，用来取色比用来截图的次数还多，但现在更新后，放大镜不见了。说明文档里面写到，放大镜的快捷键是alt，但mac没有alt键，按了control、option、command均无反应。希望默认打开放大镜，或者给一个自定义开关。谢谢~

软件版本：2.3.5-Beta（2020.04.12）
运行平台：macOS

**Comment by liulex** [comment]
放大镜是默认打开的。
alt 对应 option 键，如果按 alt 键都没反应，说明放大镜由于某种原因出不来。
在贴图上按 alt 键也没有反应么？

**Comment by ymyz1229** [comment]
@liulex 在设置里取消勾选“自动检测窗口”和“自动检测界面元素”后，重新勾选，放大镜就正常了。估计之前遇到BUG了。但是我刚试了下在贴图上按ALT，放大镜显示在贴图下方了，这个正常吗？

**Comment by liulex** [comment]
> 在贴图上按ALT，放大镜显示在贴图下方了，这个正常吗？

不正常。
看起来你的窗口层级有点问题，请问是不是用了什么窗口管理软件？
