### ISSUE TITLE
快捷键F1及超级截图在新版IDEA中失效

### ISSUE THREAD

**Issue by oo0oo2015** [Snipaste/feedback#1487]
在 IntelliJ IDEA 2020.1 版本中，F1快捷键截图及超级截图均失效。已清理 IDEA 的 F1 快捷键映射，仍无法使用。

软件版本：PRO 2.3.4
运行平台：微软商店

**Comment by liulex** [comment]
见  #1477，2.3.5 应已修复。

**Comment by minilunas** [comment]
最新版又出这个问题了

**Comment by minilunas** [comment]
idead的2023.1.2，快捷键F1及超级截图失效

**Comment by Stephen-AC** [comment]
> idead的2023.1.2，快捷键F1及超级截图失效

可能是因为你的idea是以管理者身份运行的，而snipaste是普通用户运行的，所以snipaste的f1快捷键失效了

**Comment by algo-spec** [comment]
> > idead的2023.1.2，快捷键F1及超级截图失效
> 
> 可能是因为你的idea是以管理者身份运行的，而snipaste是普通用户运行的，所以snipaste的f1快捷键失效了

的确是这个导致的
