### ISSUE TITLE
双屏幕贴图bug

### ISSUE THREAD

**Issue by thefujunjie** [Snipaste/feedback#1489]
双显示器，当贴图横跨两个屏幕时，鼠标滚轮调节图片大小或鼠标双击关闭图片，会停止响应。已出现多次该问题。

两个显示器分辨率不一样，不知道是不是因为这个引起的bug

**Comment by liulex** [comment]
我这边没有问题，能不能录个屏看一下？

**Comment by thefujunjie** [comment]
> 我这边没有问题，能不能录个屏看一下？

也不是每次都会出现这个bug
所以我也没法录屏

**Comment by liulex** [comment]
重现了一个类似的 bug，会在 2.4.1 修复。
