### ISSUE TITLE
Linux版本的更长时间是多久？

### ISSUE THREAD

**Issue by zwjdujin** [Snipaste/feedback#1490]
16年的时候说：
Linux 版
Mac 版之后我会出一个 Linux 版，但要等上更长的一段时间，因为还未尝试过在 Linux 上编译它。
请问这个更长的一段时间有多长，等了4年了！

**Comment by liulex** [comment]
我猜……是明年（

**Comment by violetu** [comment]
我也想问 linux 版本这么久了，还在开发吗？

**Comment by lunzilunzi** [comment]
4年，你知道我这4年是怎么过的吗！！希望不是有生之年系列。付费我也很愿意啊！

**Comment by septs** [comment]
Duplicate of #711
