### ISSUE TITLE
Mac 版本更新失败，在官网无法下载

### ISSUE THREAD

**Issue by onlyacat** [Snipaste/feedback#1492]
1. 本地旧版本检查更新，提示连接失败
Retrying...
QNetworkReply::NetworkError: 2

Download errors occurred! HTTP Error Code: 0

2. 手动打开官网，导向下载地址的网址打不开，换了浏览器也不行。

**Comment by liulex** [comment]
浏览器打不开的报错信息是什么呢？

**Comment by onlyacat** [comment]
> 浏览器打不开的报错信息是什么呢？

刚刚试了下可以正常下载了谢谢。
