### ISSUE TITLE
关于截图添加文字，文字的描边功能无效。

### ISSUE THREAD

**Issue by asnfohsdgfbkxcv** [Snipaste/feedback#1493]
关于截图添加文字，文字的描边功能无效。
App version:
Platform: Microsoft Store / Windows Desktop / macOS
![image](https://user-images.githubusercontent.com/8177108/79816981-02f3b000-83b7-11ea-85c4-fc14e56e8f57.png)

**Comment by asnfohsdgfbkxcv** [comment]
Platform: Microsoft Store

**Comment by liulex** [comment]
更新版本。#1475 #1486
