### ISSUE TITLE
Read QR code ! 截图识读二维码功能！

### ISSUE THREAD

**Issue by gdgzwqz** [Snipaste/feedback#1495]
目前，二维码到处横行，可没有一款好用的二维码识读软件带有截图识读功能，或没有 一款带有识读二维码功能的截图软件，建议增加此功能，方便截图后立即识读!

**Comment by gdgzwqz** [comment]
先截图，然后直接识读解析二维码！

**Comment by chenrylee** [comment]
Snipaste就是个单纯的截图+标注软件，如果搞成大融合，就废了，这个issue建议关掉吧。 @liulex

**Comment by xsgteamx** [comment]
使用PandaOCR即可达到你要的目标, @chenrylee

**Comment by Gae-Blog** [comment]
同意！
现在网上有很多网址都用二维码给出，电脑浏览起来很不方便，希望Snipaste能推出类似的功能

**Comment by l5oo00** [comment]
二维码这个绝对是刚需啊

**Comment by septs** [comment]
Duplicate of #23
