### ISSUE TITLE
希望添加一个全局快捷键，这样就不会跟别的软件起冲突很麻烦了，谢谢你。

### ISSUE THREAD

**Issue by aureliano-tm** [Snipaste/feedback#1496]

**Comment by liulex** [comment]
不明白你是什么意思……

**Comment by aureliano-tm** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    大佬你好，膜拜就是比如我开了一个软件，它自定义F1是打开帮助菜单，并且这个快捷键不可修改我用这个软件的时候，想截图，F1就按不出来所以我想请问可以定义成全局快捷键，只让Snipaste的F1起作用可以么？感谢大佬回信
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                xunzhaotm
                            
                    
                        
                            
                                    xunzhaotm@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2020年04月24日 19:43，Le Liu<notifications@github.com> 写道： 




不明白你是什么意思……



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by chenrylee** [comment]
@aureliano-tm 在**选项**中， `控制` -> `全局热键` 界面可以修改成不冲突的快捷键。

**Comment by aureliano-tm** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    好的，谢谢大佬
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                xunzhaotm
                            
                    
                        
                            
                                    xunzhaotm@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2020年04月25日 00:19，Chenry Lee<notifications@github.com> 写道： 




@aureliano-tm 在选项中， 控制 -> 全局热键 界面可以修改成不冲突的快捷键。



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
