### ISSUE TITLE
我习惯用shift+x来作为截屏键,我希望snipaste可以支持这个方式截屏

### ISSUE THREAD

**Issue by you-hengh** [Snipaste/feedback#1497]
安装snipaste后,我设置shift+x 作为截屏键,但是右边的状态一直是红色,右键snipaste图标重启程序后,会提示shift+x注册失败,
![image](https://user-images.githubusercontent.com/34816426/80031731-b1fdcc00-851c-11ea-9cac-98efc8f29a78.png)
![image](https://user-images.githubusercontent.com/34816426/80031785-c5a93280-851c-11ea-8a24-37d53576090f.png)
软件版本：2.3.5-Beta
运行平台：Windows 桌面  win10 64 1909
**我使用shift+x的原因是 有些时候,我需要截屏鼠标右键菜单,
而使用alt 快捷键后 在截图的一瞬间,右键菜单会因为按下alt键消失,
这不是我所需要的,而且我的F1,F2,F3,F4等等都设置了其他快捷键,这让人很苦恼,
因为我认为shift+x这个快捷键是天生的截屏快捷键,使用它会很顺手,一只手可以很顺利的呼唤它**

**Comment by liulex** [comment]
https://docs.snipaste.com/zh-cn/advanced-configs?id=hotkey2
```
[Hotkey2]
allow_simple_hotkeys=true
```

**Comment by you-hengh** [comment]
> https://docs.snipaste.com/zh-cn/advanced-configs?id=hotkey2
> 
> ```
> [Hotkey2]
> allow_simple_hotkeys=true
> ```
我按照提示设置成功了
非常感谢!
