### ISSUE TITLE
增加截屏并自动保存到指定目录功能，并支持设定快捷键

### ISSUE THREAD

**Issue by abelsu12** [Snipaste/feedback#1498]
类似steam游戏截图F12自动截图全屏并保存到预设目录的功能。

并且可以在 首选项 控制 中设定快捷键。感谢

**Comment by liulex** [comment]
`snip --full -o D:\Snipaste_$yyyy-MM-dd_HH-mm-ss$.png`
需要将命令绑定到快捷键，请使用专业版。
