### ISSUE TITLE
请求添加截图也可以输出固定宽度的设置

### ISSUE THREAD

**Issue by leaderz5201** [Snipaste/feedback#1502]
目前贴图功能里有输出固定宽度的设置，但截图里面没有，导致制作文档的时候，每次粘贴出来的图还要再一次进行大小的调整，希望有可以输出固定宽度的设置，可以更加便利。

**Comment by liulex** [comment]
![](https://user-images.githubusercontent.com/2010459/80796736-8fca1500-8bd2-11ea-95f0-ba89afc44e0b.png)

专业版点击这里可以设定截图大小。
