### ISSUE TITLE
0xc000007b error on Ms-windows 7 while clicking tor un Snipaste-2.3.5-Beta-64

### ISSUE THREAD

**Issue by sumihikot** [Snipaste/feedback#1504]
It came up with 0xc000007b error on Ms-windows 7 while clicking to run Snipaste-2.3.5-Beta-x64

App version: Snipaste-2.3.5-Beta-x64
Platform: Ms-Windows 7 Ultimate (Visual Basic C++ Redistributable 2019 x64 and x86 are installed)

https://i.imgur.com/MRukkWs.png
https://i.imgur.com/bR4B0CX.png

**Comment by liulex** [comment]
You may try installing Visual C++ Redistributable 2015.

**Comment by sumihikot** [comment]
Visual C++ Redistributable 2015-2019 is installed yet Snipaste still has 0xc000007b error (see the attached picture)

    在 2020年5月10日 星期日 上午12:08:53 [GMT+8]， Le Liu<notifications@github.com> 寫道：  
 
 


You may try installing Visual C++ Redistributable 2015.

**Comment by liulex** [comment]
Is your OS x64? Have you tried the x86 version of Snipaste?

**Comment by sumihikot** [comment]
My O/S is Windows 7 Ultimate 64bit

    在 2020年5月12日 星期二 下午10:40:23 [GMT+8]， Le Liu<notifications@github.com> 寫道：  
 
 


Is your OS x64? Have you tried the x86 version of Snipaste?

**Comment by sumihikot** [comment]
My O/S is Windows 7 Ultimate 64 bit.  Check the attached picture.  I have installed both 32/64 x86/x64 version of Visual C++ 2015-2019 Redist.
    在 2020年5月12日 星期二 下午10:40:23 [GMT+8]， Le Liu<notifications@github.com> 寫道：  
 
 


Is your OS x64? Have you tried the x86 version of Snipaste?

**Comment by liulex** [comment]
Attached pictures cannot be shown if replying from email.
Even if you are using 64-bit OS, you may try the Snipaste x86 and see if problem solves.

**Comment by sumihikot** [comment]
I have both x86 and x64 Visual Basic Redis. 2015-2019 installed
Here's the link for the picture Imgur

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Imgur

Imgur

Post with 0 votes and 2 views.
 |

 |

 |


and the picture link for the error 0xc000007b message of Snipaste Imgur

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Imgur

Imgur

Post with 0 votes and 2 views.
 |

 |

 |





    在 2020年5月12日 星期二 下午11:48:12 [GMT+8]， Le Liu<notifications@github.com> 寫道：  
 
 


Attached pictures cannot be shown if replying from email.
Even if you are using 64-bit OS, you may try the Snipaste x86 and see if problem solves.

**Comment by liulex** [comment]
Still, I cannot see you image. Please check this [issue link](https://github.com/Snipaste/feedback/issues/1504) to understand what I mean.

I know you have both x86 and x64 Visual Basic Redis. 2015-2019 installed, but maybe you should try downloading the **32-bit version of Snipaste**.
