### ISSUE TITLE
请求增加可以更改剪贴板中的图像质量的功能

### ISSUE THREAD

**Issue by dannyforever** [Snipaste/feedback#1505]
我通常将Snipaste 配合图床一起使用，图床工具需要从剪贴板获取图片上传，剪贴板中的图像质量过大经常导致图片上传过慢或者失败。
I usually use snipaste with the drawing bed. The drawing bed tool needs to get pictures from the clipboard and upload them. The image quality in the clipboard is too high, which often leads to the picture upload too slow or fail.

**Comment by liulex** [comment]
从逻辑上来说，该功能应该由图床工具提供吧。
不是所有截图都是为了上传，而你的需求是压缩准备上传的截图。

**Comment by dannyforever** [comment]
> 从逻辑上来说，该功能应该由图床工具提供吧。
> 不是所有截图都是为了上传，而你的需求是压缩准备上传的截图。

是这么个道理，谢谢
