### ISSUE TITLE
贴图多选复制缺陷

### ISSUE THREAD

**Issue by Trzeth** [Snipaste/feedback#1507]
贴图多选后复制仅复制一张图片。

希望右键另存为时也可一次保存多张图片。

软件版本：
运行平台：微软商店 2.3.5 PRO

**Comment by liulex** [comment]
一次保存多张图片是怎样的操作呢？

**Comment by Trzeth** [comment]
多选之后保存 应该希望是弹出一个对话框选择一个文件夹 将所有选中的贴图保存。
这样？

**Comment by liulex** [comment]
那要怎么命名？

**Comment by Trzeth** [comment]
时间后面加序号？

**Comment by liulex** [comment]
Snipaste 2.5 已支持多选贴图后批量导出。
