### ISSUE TITLE
[BUG]正确操作但图片并没有被截取

### ISSUE THREAD

**Issue by chthub** [Snipaste/feedback#1508]
App version:
Platform: 从官网下载的2.3.0-Beta版，win10 64位。
之前一直都很正常，但现在截图之后图片并没有在我的粘贴板里面，粘贴板里面啥都没有。尝试清空截图记录无效果。之后我重启软件出现了一个更奇怪的bug，截图之后图片出现在我的粘贴板里面了，但不是我想要的图片，而是得到了粘贴板里面之前已经截取的一张图片的copy。然后多次截取不同的内容，但我粘贴板里面图片数量虽然增加了，但都是之前那张图片的copy.粘贴板是通过win+v查看的。

之后不得不重启电脑，虽然问题解决，但每次再次遇到bug还要重启，太麻烦了。

**Comment by liulex** [comment]
我不认为这些问题跟 Snipaste 有关，请排查你安装的其他软件。

**Comment by chthub** [comment]
@liulex 经过排查之后发现和网易有道词典的划词翻译有关，把网易有道词典关闭就正常了。感谢！

**Comment by Flsahkong** [comment]
> @liulex 经过排查之后发现和网易有道词典的划词翻译有关，把网易有道词典关闭就正常了。感谢！

有效，谢谢！

**Comment by Flsahkong** [comment]
> @liulex 经过排查之后发现和网易有道词典的划词翻译有关，把网易有道词典关闭就正常了。感谢！

刚刚查阅，在网上看到了解决办法：
将snipaste设置为  **以管理员方式** 运行即可。
