### ISSUE TITLE
请求一键快速全屏截图并保存

### ISSUE THREAD

**Issue by Azvuk** [Snipaste/feedback#1509]
因为经常需要在显示动态内容的时候截图，每次操作都来不及错过了内容，相信有很多小伙伴都有这个需求，恳请加入一键快速全屏截图并保存。

另外Win7用户无法购买专业版，恳请桌面版早日提供专业版。

感谢开发组！

**Comment by liulex** [comment]
通过命令行可以全屏截图并自动保存：https://github.com/Snipaste/feedback/issues/1498#issuecomment-618960920

如需绑定到快捷键，是需要专业版的，桌面版正在开发中哈。
