### ISSUE TITLE
首次双击销毁固定在屏幕上的截图前请求用户确认

### ISSUE THREAD

**Issue by rickyzhangca** [Snipaste/feedback#1514]
想要什么: 双击固定在屏幕上的截图会销毁截图，第一次销毁前请求用户确认
它具体是怎样的: 双击固定在屏幕上的截图会销毁截图，第一次执行销毁操作前请求用户确认，用户可以取消操作
你为什么需要它: 由于没有确认请求，导致无意间发现该功能的用户发现截图已经销毁并无法找回

**Comment by liulex** [comment]
谢谢建议，下个版本就会加上。

**Comment by YanAnHuaZai** [comment]
哈哈哈这个提示好阔耐
