### ISSUE TITLE
希望增加序号笔功能（新版QQ截图的功能）

### ISSUE THREAD

**Issue by LanceMoe** [Snipaste/feedback#1515]
新版 QQ 截图里有一个序号笔功能非常方便，请求加入。
![Snipaste_2020-05-06_05-16-38](https://user-images.githubusercontent.com/18505474/81112026-fa73ab80-8f58-11ea-824b-281c46c737db.png)

**Comment by YehowahLiu** [comment]
#227 
Snipaste 2.4 专业版即支持序号标注.
