### ISSUE TITLE
与2345看图王冲突？贴图消失，程序崩溃

### ISSUE THREAD

**Issue by kfuudotcn** [Snipaste/feedback#1517]
看图软件用的是**2345看图王**
屏幕已存在贴图时，打开电脑上的任意图片，贴图消失，再打开一个图片，贴图又出来了。这时如果双击任务栏的snipaste，snipaste没有任何提示，就退出了。（正常操作，双击应该是截图）
并不是每次都会产生这种问题，但是经常出现。

2345看图片：version:9.2
App version:2.3.5
Platform: Microsoft Store 专业版

**Comment by liulex** [comment]
我猜你只是触发了“屏幕触发角”功能：
![](https://user-images.githubusercontent.com/2010459/81706853-d5c08c00-94a2-11ea-8767-36d6e29526d5.png)
