### ISSUE TITLE
无法将截图复制到剪贴板

### ISSUE THREAD

**Issue by Awetic** [Snipaste/feedback#1518]
无法将截图复制到剪贴板
*按F1截图后，无论点击右下角的复制到剪切板，还是按ctrl+c快捷键，或还是ctrl+F1,截图似乎都没有复制到剪贴板，单击鼠标右键粘贴项为灰色，ctrl+V也无济于事。
软件版本：snipaste 2.3.5Beta #
运行平台： Windows 桌面

**Comment by liulex** [comment]
#1508

**Comment by Flsahkong** [comment]
刚刚查阅，在网上看到了解决办法：
将snipaste设置为 **以管理员方式** 运行即可。
这样有道词典的划词翻译和snipaste就不会冲突了。
