### ISSUE TITLE
using group name as the history folder name

### ISSUE THREAD

**Issue by gshmu** [Snipaste/feedback#1519]
I want using the meaningful folder name, so that I can find image quick 
<img width="550" alt="image" src="https://user-images.githubusercontent.com/1797676/81466090-5d876b80-9201-11ea-8de6-58ab6bacb969.png">

**Comment by liulex** [comment]
1. Group names can be identical, but folder names cannot.
2. Random folder names indicates that the folders are handled by the program. Users are not advised to access them directly, because it could lead to app crash or image lost.

**Comment by gshmu** [comment]
I want using the same name.

I usually pinned some images, and then I close it but not destroy it. 

I think using the random folder name by default, but user can change the config will be better

**Comment by gshmu** [comment]
@liulex where the group and folder name mapping? can I change it by some shell.
