### ISSUE TITLE
关于Snipaste长截图的需求

### ISSUE THREAD

**Issue by demosu** [Snipaste/feedback#1521]
作为一个Snipaste的重度用户，对Snipaste的依赖已经高过QQ了。。。。电脑上可以没有QQ但是不能没有Snipaste，不过最近发现很多人再用的QQ长截图我觉得非常好，不知道 作者大大是否可以纳入开发项目？毕竟这也算是截图的一种需求类型。

**Comment by liulex** [comment]
谢谢支持，该功能我有空会支持的。
