### ISSUE TITLE
Ability to resize the captured image

### ISSUE THREAD

**Issue by e4rthdog** [Snipaste/feedback#1523]
I saw a feature request but i did not find any way to vote for it or add some info.

I use snipaste to paste images in emails and other pages. But my pc has a large resolution and the images are huge when i paste them in normal emails.

It would be extremely useful if you could add a resize function in both clipboard and save in file functions.

I mean i would like to capture annotate a pic and before pressing copy to clipboard to be able to say for example resize to 50% of original size.

**Comment by YehowahLiu** [comment]
You can simply resize the image by the following steps:

1. pin the image on your screen;
2. scroll the mouse wheel to resize the pinned image;
3. try one of the following steps:
   - press ctrl+c to copy the resized image
   - right click the resized image and choose 'copy image'
   - Snip the resized image and copy it

then there will be a resized image in your clipboard.

By the way, you can change the Image quanlity in Preferences->Output

**Comment by e4rthdog** [comment]
That's amazing...Exactly what i wanted.

Thank you very much!

*Elias Stassinos*

**Comment by e4rthdog** [comment]
Feature already included
