### ISSUE TITLE
通过远程软件控制电脑时, 文字输入始终打不出c字母开头的文字 

### ISSUE THREAD

**Issue by alvinyangyang** [Snipaste/feedback#1524]
是不是和什么快捷键冲突了

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/1397#issuecomment-616003839

**Comment by alvinyangyang** [comment]
解决了 谢谢😘😚😗😙



---原始邮件---
发件人: "Le Liu"<notifications@github.com&gt;
发送时间: 2020年5月17日(周日) 中午1:35
收件人: "Snipaste/feedback"<feedback@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"alvinyangyang"<imagine.alvin.yang@qq.com&gt;;
主题: Re: [Snipaste/feedback] 通过远程软件控制电脑时, 文字输入始终打不出c字母开头的文字  (#1524)




 
#1397 (comment)
