### ISSUE TITLE
其它 UWP 应用鼠标无响应

### ISSUE THREAD

**Issue by View12138** [Snipaste/feedback#1525]
### 问题描述
- 微软商店版 可能导致部分 UWP 应用的部分或全部无法响应鼠标，包括鼠标移动，滚轮滚动，鼠标点击等等。
- 鼠标不响应问题大概出现了一两个月，今天才发现是 Snipaste 商店版导致的。
- 关闭此应用，UWP 的其它应用可以正常使用。打开此应用，运行1s左右之后，UWP 的部分应用不可响应鼠标。  
- 重启此应用，重启期间其它 UWP 应用可以正常响应，约1s左右之后就出现上诉问题。
- 事件查看器中没有相关的错误信息。

### 出现不响应的 UWP 应用：
1. IT之家，列表页面没有问题，详情页面无法点击滚动。
2. SupportAssist：程序标题栏(关闭、最大化等按钮)均以外无法响应鼠标的任何操作。
3. Microsoft Store：应用程序详情页无法响应鼠标任何操作。但可以使用tab键操作。
4. 便签(Windows 自带的 Notes)：整个应用无法响应，包括关闭按钮。可以使用键盘操作。

### 出现问题时的环境
- 发现是 Snipaste 影响时的版本：`微软商店版 2.3.4`。
- Windows版本：1909 专业版、2004 专业版。

### 可能的解决方案
遂下载 `桌面版 2.3.5 Beta` 版，其它 UWP 应用也正常使用，未出现商店版导致的问题。

**Comment by liulex** [comment]
无法重现。
如果存在 `Snipaste 打开后 Microsoft Store 应用程序详情页无法响应鼠标任何操作`，应该早就有很多用户报告了。建议再排查一下其他程序的影响。

**Comment by View12138** [comment]
6个小时前我卸载了商店版的应用，在此之前从未卸载过。刚才看到您的回复之后我又重新下载了商城版，也无法重现了。
