### ISSUE TITLE
希望添加对 Surface Pen 按钮的支持

### ISSUE THREAD

**Issue by Cleverambo** [Snipaste/feedback#1526]
![image](https://user-images.githubusercontent.com/36615067/82411972-54ba5380-9aa5-11ea-8798-b1e2e9124421.png)
如图所示。我不太清楚微软是否开放了权限。
如果没有，可以通过“打开应用”的方式来变相实现这一功能，但是目前打开 Snipaste 的默认动作仅仅是打开，或许可以改为直接启动截图？
谢谢。

**Comment by liulex** [comment]
这里有方法：https://github.com/Snipaste/feedback/issues/940#issuecomment-506969718
