### ISSUE TITLE
Macbook Pro 16in 系统版本10.15.4 无法启动

### ISSUE THREAD

**Issue by kiss82053917** [Snipaste/feedback#1527]
软件版本：Snipaste-2.3.5-Beta
运行平台：macOS

**Comment by loguu** [comment]
![](https://user-images.githubusercontent.com/50081984/82426161-18452280-9aba-11ea-991a-80d5c53d2402.png)
可能今晚会发布。

**Comment by liulex** [comment]
@kiss82053917 已更新到 2.4 Beta，麻烦测试一下问题是否已解决。
