### ISSUE TITLE
如何取消贴图在 alt+tab 中占用位置？

### ISSUE THREAD

**Issue by miaowm5** [Snipaste/feedback#1528]
win7 的系统，之前一直使用两年前的旧版，今天更新到最新版后发现 alt+tab 里面出现了一堆贴图的位置，请问这个应该如何取消？

![image](https://user-images.githubusercontent.com/7985604/82439841-eccc3300-9acd-11ea-99ad-5ff35d002f62.png)

**Comment by liulex** [comment]
刚测试了下，Win7 确实存在这个问题，但 Win 10 没问题，我看看~

**Comment by heartacker** [comment]
@liulex 我反而希望能够出现在任务视图，这样我就可以用快捷键回到贴图了，之前只能用鼠标。

**Comment by miaowm5** [comment]
> @liulex 我反而希望能够出现在任务视图，这样我就可以用快捷键回到贴图了，之前只能用鼠标。

贴图少的时候还好，贴图十来个的时候，alt+tab直接废了……

**Comment by TwinkleSharp** [comment]
我在Win10碰到了这个现象，请问是特性还是BUG？
我使用的版本是：Snipaste 专业版 64位 2.7.3(2022.01.30)
<img width="639" alt="Snipaste" src="https://user-images.githubusercontent.com/47250884/159023700-e5a43fd9-d0c9-4c22-bf4b-08af790b22ee.png">

**Comment by heartacker** [comment]
> > @liulex 我反而希望能够出现在任务视图，这样我就可以用快捷键回到贴图了，之前只能用鼠标。
> 
> 贴图少的时候还好，贴图十来个的时候，alt+tab直接废了……

最终，我还是觉得，
1. 只要有贴图的时候，不管有多少个贴图，都在windows 最近任务中显示一个。而不是多个。
2. 当用户切换到snippet 贴图后，显示最近的一个贴图，然后用户可以按 tab键 进行不同贴图的切换。
https://github.com/Snipaste/feedback/issues/556#issuecomment-646909083
