### ISSUE TITLE
新增的文字底色，只有黑底么？

### ISSUE THREAD

**Issue by hpulc** [Snipaste/feedback#1529]
如题，希望能增加文字底色颜色修改功能。
商店2.4版，Win10X64

**Comment by sevelee** [comment]
同，似乎没法更改背景颜色
![image](https://user-images.githubusercontent.com/8036235/82892607-5ba00500-9f82-11ea-8871-429b13c8f2c0.png)

**Comment by Asnxthaony** [comment]
可以更改
![image](https://user-images.githubusercontent.com/12845643/82894763-acfdc380-9f85-11ea-91a0-3d72311d6dbf.png)

**Comment by liulex** [comment]
下个版本就支持自定义底色了：
![](https://user-images.githubusercontent.com/2010459/82909528-fa852b00-9f9b-11ea-885a-340e99b4952b.png)
