### ISSUE TITLE
可以将截图数据放到云端

### ISSUE THREAD

**Issue by Razorro** [Snipaste/feedback#1530]
感觉snipaste不仅仅可以当作快捷截图工具，我越来越喜欢把一些速记内容以截图方式保留下来，方便忘记的时候切回来看看。如果加入云端保存这些分组截图，那无论切换到哪台设备都可以立马回复，会感觉特别舒爽！

**Comment by stevenzhu25** [comment]
其实你现在就可以通过把截图保存文件夹设置到OneDrive/Google Drive/Dropbox 甚至是WebDAV内达成此效果…
个人感觉如果让作者维持云端储存花费不是一般的高

**Comment by StarryVoid** [comment]
目前软件的配置文件和自动保存目录都可以修改
如果需要可以将配置文件和贴图组上传到网盘，新设备上重新关联配置文件即可。
windows store 目前无法将贴图组移动位置，因为store的软件数据都默认指到了一个文件夹中。

**Comment by septs** [comment]
Duplicate of #60
