### ISSUE TITLE
在2.2上「Command」+「C」实现截图行为的功能，如何在后续版本上实现？

### ISSUE THREAD

**Issue by sgricky** [Snipaste/feedback#1531]
如题：

在2.2上「Command」+「C」实现截图行为的功能，如何在后续版本上实现？

我是2.2.5之后，按「Command」+「C」（我把这设置为Logitech鼠标上的某个快捷键了）无法完成”截图“的动作了。
![Snipaste_2020-05-23_16-36-15](https://user-images.githubusercontent.com/10599751/82726019-d9aaa480-9d13-11ea-83b8-9644da83767d.jpg)

我原来绑定的G4键在选择截图区域之后轻轻一按就复制成功了，但在2.2.5之后的版本基本都失效了。

就是这个操作：
![Snipaste_2020-05-23_16-44-12](https://user-images.githubusercontent.com/10599751/82726204-03180000-9d15-11ea-937d-6545a92571eb.jpg)

**Comment by liulex** [comment]
查了一下，这个是 2.2 开始就这样了，原因是为了兼容欧陆词典的划词搜索，只有屏蔽掉模拟按钮的 Cmd+C，见 #1012.

**Comment by liulex** [comment]
这两种模拟按键似乎无法区分，下个版本我提供个选项吧，是否屏蔽来自模拟按键的 Cmd+C。

**Comment by liulex** [comment]
2.5 Beta 加上设置项。

**Comment by sgricky** [comment]
看到修复了很高兴，我立马下载了最新2.5.1……等等，相关的设置项是哪个？选项太多了~

**Comment by sgricky** [comment]
![Snipaste_2020-09-14_01-43-18](https://user-images.githubusercontent.com/10599751/93024818-be99d280-f62b-11ea-9b7e-b1c6e09a0c59.jpg)
如果说的是这个选项的话……至少暂时我不管是否选它，鼠标快捷键都不生效（和之前一样）。
是我的设置有什么问题么？
