### ISSUE TITLE
有没有可以截整个网页的功能

### ISSUE THREAD

**Issue by MelancholyAstronaut** [Snipaste/feedback#1533]
有没有可以截整个网页的功能

**Comment by StarryVoid** [comment]
建议使用浏览器自带的全屏截图功能
Chrome ：打开你想截图的网页，然后按下 F12（macOS 是 option + command + i）调出开发者工具，接着按「Ctrl + Shift + P」（macOS 是 command + Shift + P）。紧接着输入指令 capture，它会提示有三个选项，分别是截取元素、全屏、node 模式以及当前显示范围。
