### ISSUE TITLE
[请求新功能]降低截图分辨率的功能

### ISSUE THREAD

**Issue by eret9616** [Snipaste/feedback#1535]
macOS自带截图工具截出来的图片清晰度太高，粘贴到到网络博客或者word里面尺寸很大，非常麻烦，需要手动拉小，耗时耗力，

Snipaste非常好用，希望在"输出"选项卡中能增加类似分辨率倍数调整的功能,使图片分辨率降低

**Comment by sevelee** [comment]
+1，希望能够提供输出百分比调节。

**Comment by libukai** [comment]
有同样需求，比如发帖到什么值得买，系统会自动压缩至640px宽，任何大图被压缩后效果都很差，如果能直接截标准分辨率的图片效果会好很多

**Comment by septs** [comment]
Duplicate of #201
