### ISSUE TITLE
文字转图片功能反馈

### ISSUE THREAD

**Issue by lishige** [Snipaste/feedback#1536]
我发现在编程语言编辑器里面使用把文字变成图片的功能时，把字体的颜色都变成了黑色，而不是原来的彩色，希望作者可以实现将代码的格式保持不变的功能

**Comment by sevelee** [comment]
![image](https://user-images.githubusercontent.com/8036235/82895134-4d53e800-9f86-11ea-85a7-9b611e180c29.png)
rider 文字直接F3出图片没有问题，带颜色及字体。应该是IDE不支持。

**Comment by liulex** [comment]
[代码编辑器里带语法高亮的代码，复制后贴出来并没有语法高亮](https://docs.snipaste.com/zh-cn/troubleshooting?id=%E4%BB%A3%E7%A0%81%E7%BC%96%E8%BE%91%E5%99%A8%E9%87%8C%E5%B8%A6%E8%AF%AD%E6%B3%95%E9%AB%98%E4%BA%AE%E7%9A%84%E4%BB%A3%E7%A0%81%EF%BC%8C%E5%A4%8D%E5%88%B6%E5%90%8E%E8%B4%B4%E5%87%BA%E6%9D%A5%E5%B9%B6%E6%B2%A1%E6%9C%89%E8%AF%AD%E6%B3%95%E9%AB%98%E4%BA%AE)
