### ISSUE TITLE
Is there a way to disable the popup toolbar?

### ISSUE THREAD

**Issue by BGMcoder** [Snipaste/feedback#1537]
I want to be able to hit the snip hotkey and simply select the area and have the area snipped to the screen - and without having to navigate the popup toolbar.

Is there a way to turn it off and just have it snip?

**Comment by StarryVoid** [comment]
Support custom commands in snipaste pro, you can use custom commands to complete the operation of screenshots and stickers
-- Use Google Translate

**Comment by liulex** [comment]
Just use this:
![](https://user-images.githubusercontent.com/2010459/82898383-cdc91780-9f8b-11ea-8fe8-4be4c4c3cfa4.png)
