### ISSUE TITLE
请求新的截图功能，扩展截图的区域

### ISSUE THREAD

**Issue by lishige** [Snipaste/feedback#1539]
请求可以增加截图的区域（第一个区域进行编辑的同时，也可以选择其他的区域进行编辑）而不是单一的一个截图的区域，在不同的区域可以分别进行不同的操作。
我的想法是如果实现了这个功能，就不用来回展开新的截图区域。如果要对全屏不同的区域进行操作的时候，这样做可以大大提高截图的效率。

**Comment by liulex** [comment]
无法想象那是怎样一种交互。。
