### ISSUE TITLE
快捷键使用问题

### ISSUE THREAD

**Issue by ibrett-io** [Snipaste/feedback#1541]
# 环境

| 参数 | 值 |
| :----:|:---- |
| 系统版本 | Windwo 10 专业版 2004 (19041.264) |
| 平台平台 | Microsoft Store |
| Snipaste版本 | 2.4.0 专业版 |

# 问题描述
1. 快键键设置问题
>  不能通过按键的方式指定快捷键为F1到12,组件键中包含F1到F12也不行,设置其他快捷键时正常,其他程序设置F1等快捷键时一切正常

2. 快捷键使用问题
> 使用默认F1快捷键截屏时,完成一次截屏后,不能立刻进行第二次截屏,需要进行其他按键操作后,才能再次使用F1截屏

**Comment by liulex** [comment]
加 <kbd>Fn</kbd>？

**Comment by ibrett-io** [comment]
> 加 Fn？

没有Fn,默认键位可以触发截图,

**Comment by liulex** [comment]
那你排查一下后台其他程序的影响？目前没有收到过类似的问题报告，应该是本地环境问题。

**Comment by ibrett-io** [comment]
应该是我运行过太多版本的Snipaste问题导致的,
