### ISSUE TITLE
发现一个缺陷：贴图的标注功能不会记忆样式（字体、大小、粗细）

### ISSUE THREAD

**Issue by SimoLin** [Snipaste/feedback#1544]
如题，发现一个细节问题，使用贴图功能，进行标注，修改了方框、文字的样式（字体、大小、粗细）功能，下一次打开贴图进行标注，上一次修改的样式没有记忆进行保存。同样的操作，使用截图功能，修改样式后，下一次截图进行标注，会记忆上一次修改的样式。希望修复一下，Thanks♪(･ω･)ﾉ

![image](https://user-images.githubusercontent.com/24656521/82969468-4e2a5f80-a002-11ea-9350-a48b47ddd1fd.png)

软件版本：专业版
运行平台：微软商店 v2.4 (2020.05.20)
发现时间：20200527

**Comment by liulex** [comment]
每个贴图自己的工具栏会记忆的，只是新贴图会用默认的。
#1235 #420

**Comment by SimoLin** [comment]
> 每个贴图自己的工具栏会记忆的，只是新贴图会用默认的。
> #1235 #420

了解，那这个是特性咯？只是我记得好像原本是会统一记忆样式，是我记错了么

**Comment by liulex** [comment]
也不叫特性，只是就这么设计的，一直都是这样。
