### ISSUE TITLE
The Snipaste Cannot Save Pictures to Local

### ISSUE THREAD

**Issue by WEI4D** [Snipaste/feedback#1555]
- **Steps**
**1.Pressing F1 to screenshoot somewhere**
**2.Pressing Ctrl+S  to save**
**3.Windows pop-up dialog for saving file but the Snipaste is freezd and windows' diaog is quit**
**4.Nothing is saved**

- **Version:**  2.4.0

- **Platform:** Windows 10

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/1399#issuecomment-596512807
