### ISSUE TITLE
配置文件config.ini中的preload_dlls_last_interval频繁变动

### ISSUE THREAD

**Issue by Erimus-Koo** [Snipaste/feedback#1556]
我写了一个自动备份各个软件配置文件的小工具，发现snipaste的config文件频繁变动。  
每次变动的都是`preload_dlls_last_interval`。
```
[Misc]
preload_dlls_last_interval=28.13
```
请问这个项是什么意思？
它的性质是配置，还是状态记录？能否从配置文件中分离出去，静态/动态部分分离？

**Comment by godefy** [comment]
这个问题我已经问过了
https://github.com/Snipaste/feedback/issues/1552
