### ISSUE TITLE
粘贴到excel或者jabber发图片造成死机重启excel或者jabber

### ISSUE THREAD

**Issue by Bryan-Liaw** [Snipaste/feedback#1557]
当使用snipaste截图完粘贴到excel或者word 还有聊天软件的时候造成假死机，会自动重启粘贴到目的应用
软件版本：2.4.0
运行平台：微软商店 / Windows 桌面 /

**Comment by liulex** [comment]
无法重现，请提供确定的重现步骤以及录屏。
