### ISSUE TITLE
"不把截图文件转换为贴图"设置项未生效

### ISSUE THREAD

**Issue by godefy** [Snipaste/feedback#1559]
专业版,设置中未勾选"不把截图文件转换为贴图"
当剪贴版存在图片路径时(比如刚才测试这个功能时用的"D:\1.png",图片是用snipaste刚截出来的),
按下 贴图 快捷键,期望的效果是 直接把 对应图片贴出来,但实际上还是会将路径作为文本贴出来。
软件版本:2.3.5

**Comment by liulex** [comment]
请区分“复制文件”和“复制文件路径”。
