### ISSUE TITLE
贴图多选

### ISSUE THREAD

**Issue by lishige** [Snipaste/feedback#1563]
为什么我选中一个贴图的时候，有的时候，会同时选中多个?这是本身的bug，还是功能就是这样的呢?
我觉得贴图一个一个地选中、一个一个地取消选中比较符合大多数人的习惯。

**Comment by lishige** [comment]
建议每次选中一个就是选中一个，而不和上次最后一次取消选中的贴图，形成关联
版本：微软商店

**Comment by liulex** [comment]
#1461
