### ISSUE TITLE
动态图贴图

### ISSUE THREAD

**Issue by lishige** [Snipaste/feedback#1564]
已经保存在电脑的动态图贴出来的是动态图。
而如果网页上的动态图再贴出来，它提出来的是静态图。
在网页上进行复制图像，贴出来的只能是静态图吗?
希望在网页上也可以支持贴动态图。

**Comment by liulex** [comment]
`在网页上进行复制图像` -> 你复制得到的就是静态图，要 Snipaste 怎么把它变动态呢？
