### ISSUE TITLE
Win10 “幽灵”贴图

### ISSUE THREAD

**Issue by houxinli** [Snipaste/feedback#1565]
一张幽灵贴图

产生原因忘记了
[![QQ-20200608175425.jpg](https://i.postimg.cc/HkvC4Xdb/QQ-20200608175425.jpg)](https://postimg.cc/qNKYptt7)
情况：鼠标放在上面时显示圆圈，类似加载中，无法双击关掉，尝试退出或强制结束snipaste，再次启动后仍会出现。clear snip records也无效

软件版本：2.4.0
运行平台：Windows 桌面

**Comment by houxinli** [comment]
补充，鼠标放在图片边缘时会变成“禁止”样式

**Comment by houxinli** [comment]
![0B7E765664C01FC05C79DAB381872F47](https://user-images.githubusercontent.com/23057640/84017802-c35a4500-a9b1-11ea-9907-ffdc30b71949.jpg)

**Comment by liulex** [comment]
这是编辑模式，那个圈是橡皮擦的光标图案。
按空格显示工具条。

**Comment by houxinli** [comment]
> 这是编辑模式，那个圈是橡皮擦的光标图案。
> 按空格显示工具条。

谢谢！
