### ISSUE TITLE
希望能支持动图gif

### ISSUE THREAD

**Issue by 1050035126** [Snipaste/feedback#1571]
希望能支持动图的显示，目前复制动图后，贴图只是一张图片

**Comment by lishige** [comment]
ScreentoGif足够使用

**Comment by lishige** [comment]
我也遇到了，在网页上复制并贴出来，动图显示的是静态图。
而一旦下载到电脑上复制再贴出来，显示的是动态图。

**Comment by dnknn** [comment]
是因为❖Windows原生没有这个接口, 不过也有成功率的, 贴图Webgif,要稍等一下,有几率成功的.

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/1564#issuecomment-647627460
