### ISSUE TITLE
V2.4 （2020 0520）for Mac开机启动功能失效

### ISSUE THREAD

**Issue by stevenzdg** [Snipaste/feedback#1573]
V2.4 （2020 0520）for Mac / Mac OS10.15.2
开机启动功能失效，删除重装后问题仍旧。app有用就希望开机启动，因为天天必须。谢谢

**Comment by imarkofu** [comment]
v2.4 (2020.05.20)
win10 同开机启动失效

**Comment by offlineface** [comment]
v2.4.0(2020.05.20)
windows 10 insider Preview
build 20161.rs_prerelease.200627-1754
以及多个之前的windows版本，开机启动失效。

**Comment by septs** [comment]
Duplicate of #1056
