### ISSUE TITLE
工具条的idea

### ISSUE THREAD

**Issue by dnknn** [Snipaste/feedback#1575]
想到一个工具条的设计idea, 
![0615215745](https://user-images.githubusercontent.com/10995302/84666703-fd988900-af53-11ea-8f5f-4f208ad74fe1.png)

❶ 增加副工具栏
❷ 用户可自定义按钮, 把用不到的放入副工具栏里(实在不愿放入 ⠇的菜单里也行)
我个人会把 `橡皮擦` `撤销` `重做` `保存` 这四个按钮给收纳起来, 因为他们有快捷键.

⚠即使放入副工具栏里,也可使用快捷键. 例如即使橡皮擦不在主工具条里,也能按下🅴键来使用.

**Comment by liulex** [comment]
抱歉，不会考虑。
