### ISSUE TITLE
贴图编辑后关闭了再重新贴图出来, 请支持编辑的可逆回溯❣

### ISSUE THREAD

**Issue by dnknn** [Snipaste/feedback#1577]
如题,就像截屏那样, 是个完整的可逆回溯.
重新贴图出来, 你没法重新回溯编辑了.
而很多时并不是直接在截屏编辑,而是先贴图出来编辑,
编辑好了后关闭贴图, 可能过后又想改改编辑下, 
此时就无法回溯了.
如果是截屏的编辑,可以完美回溯(截屏回溯目前支持)
![Pic-200616-234](https://user-images.githubusercontent.com/10995302/84693661-6d216f00-af7a-11ea-8d65-2b9816a9b5db.png)

**Comment by liulex** [comment]
什么叫“重新贴图出来”？只要贴图被恢复了，它的标注记录就好在，销毁了那自然就没办法啊。

**Comment by dnknn** [comment]
> 销毁了那自然就没办法啊。

### 不是贴图销毁, 是贴图`关闭` , 能否恢复标记过程的历史记录.
