### ISSUE TITLE
贴图拖放时显示的边框并非是贴图的边框

### ISSUE THREAD

**Issue by WXL570CN** [Snipaste/feedback#1579]
拖动贴图的时候，有一个黑色框，这个黑色框却并不是贴图的边框，而是贴图的一个外边距框。这就有个问题，我想将贴图的一条边刚好和屏幕里的某条线重合，但却不能利用拖动时这个黑色框来判定，而是只能一点一点靠感觉把贴图放对位置。
我不知道开发团队搞的这个黑色框是要满足什么样的需求，反正在我这一无是处。我需要的，就只是拖动的是贴图就好，也别搞啥外边距，将贴图拖放在什么位置，松开鼠标之后贴图就应该在什么位置就好。
软件版本：
运行平台：微软商店 / Windows 桌面 / macOS
Windows桌面

**Comment by WXL570CN** [comment]
我注意到设置里有个  拖放操作时保留原贴图  这个勾选项，去掉之后却只对第一次贴图拖放有效，关闭贴图再次打开进行拖放时，还是会有原贴图。

**Comment by liulex** [comment]
你没发现那个黑框是系统的黑框？每个窗口拖动都会有？
按照如下设置即可移除黑框：
![](https://i.v2ex.co/96N4D4hJ.png)
