### ISSUE TITLE
拖拽贴图

### ISSUE THREAD

**Issue by lishige** [Snipaste/feedback#1580]
①拖拽贴图似乎并不支持新版的Edge
有希望实现在Edge上拖拽贴图的功能吗?
因为我个人比较习惯用新版的Edge
如果不支持的话，也并不影响我的使用

②另外，把一张贴图使用拖拽贴图的功能覆盖原有的一张贴图，为什么会出现贴出来的是网页的连接而不是图片的情况?这个具体应该如何设置呢?
2020.6.16

**Comment by liulex** [comment]
这个功能确实是跟网页和浏览器有关的，如果拖拽的信息里包含图片的网络地址，就会下载图片，否则就只是显示网址文字。对于不支持的页面/浏览器并没有什么办法。
