### ISSUE TITLE
期望可以设置销毁单张截图、销毁该组所有截图的快捷键

### ISSUE THREAD

**Issue by indomalex** [Snipaste/feedback#1582]
常常需要销毁当前组的部分截图，或清空当前组的所有截图。

但目前的shift+esc销毁单张截图、以及在右下角去关闭分组来达到销毁该组所有截图的方式，太不方便。

不知可否考虑一下增加可自由设置单张销毁，组内销毁的快捷键？貌似之前有人也有类似需求，但没有采取，实在期望加上这一点，让snipaste更完善适应更多人的需求

**Comment by liulex** [comment]
专业版可以多选/全选贴图，然后批量销毁/关闭。
