### ISSUE TITLE
截图界面进行矩形和圆形绘图时，希望可以去掉锚点和边框

### ISSUE THREAD

**Issue by tojohnonly** [Snipaste/feedback#1583]
![1592379280(1)](https://user-images.githubusercontent.com/4359375/84869028-174ee300-b0b0-11ea-9159-bb6af8003409.jpg)

如上图的圆形外面的锚点和边框，感觉有点多余，是否可以设置一个选项开启关闭的，麻烦了…

**Comment by liulex** [comment]
下个版本会尽可能减少边框的出现。
