### ISSUE TITLE
截图颜色不太准

### ISSUE THREAD

**Issue by blackux** [Snipaste/feedback#1584]
上面是 snipaste 的，下面是微信截图的，可以看出标签页的绿色有明显不同。
<img width="577" alt="WX20200618-153351@2x" src="https://user-images.githubusercontent.com/29528771/84991512-31a0c380-b179-11ea-8752-2dfb69bc90fe.png">

**Comment by liulex** [comment]
1. 请确认你用的是最新版。
2. Snipaste 对颜色的处理跟系统截图一致。
