### ISSUE TITLE
运行一段时候后无法截取外接显示屏桌面

### ISSUE THREAD

**Issue by wuxingchi** [Snipaste/feedback#1586]
发现了什么缺陷？
1、软件运行一段时间后，笔记本连接外接显示屏时，截图无法截到外接显示屏的桌面
2、软件重启后该问题可解决（但运行不超过一天内，该问题还会再次出现）

软件版本：
运行平台：Windows 桌面  V2.4 Beta

**Comment by liulex** [comment]
程序启动后，Qt 对**部分**屏幕连接/断开的处理有点问题，目前没有什么办法，猜测可能跟连接屏幕的线缆类型有关。
临时解决办法是，尝试更换屏幕连接线 或 总是先连屏幕再启动程序 或 屏幕连接有变化后重启程序。
