### ISSUE TITLE
Mac电脑截屏后，贴图到屏幕后卡死了。图片关不掉。

### ISSUE THREAD

**Issue by moxinnai** [Snipaste/feedback#1587]
Mac电脑截屏后，贴图到屏幕后卡死了。图片关不掉。而且我把snipaste卸载了重新装，只要点击   
 隐藏/显示所有贴图 ，之前的那张截屏的贴图就还在那个位置，卡死在那里，关也关不掉。求支援～～

**Comment by moxinnai** [comment]
系统是10.15.5

**Comment by liulex** [comment]
“卡死”是怎样的表现呢？

**Comment by moxinnai** [comment]
> “卡死”是怎样的表现呢？
就是我只要点击显示贴图，贴图就一直在我的电脑右下方显示，关也关不掉。卸载了snipast也不行

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/1565#issuecomment-640743640

**Comment by Jquarker** [comment]
遇到了同样的问题，楼主现在解决了没
