### ISSUE TITLE
Add option to save window or browser tab title in file name

### ISSUE THREAD

**Issue by rudolphos** [Snipaste/feedback#1589]
Feature request to add option to save active window title in file name. Currently it only saves date and time '`Screenshot_$yyyy-MM-dd_HH-mm-ss$.png`'

![image](https://user-images.githubusercontent.com/4366810/85492167-6e3b4780-b5dd-11ea-9299-31ac00cf2f6c.png)

**Comment by mahomedh** [comment]
Greenshot does this very well, but snipaste is much better and this is the only "missing" feature for me.

**Comment by liulex** [comment]
Sorry for forgetting about this. I will add `%title%` in the next version for free.
