### ISSUE TITLE
可以添加像素级贴图移动功能吗？

### ISSUE THREAD

**Issue by Xiar4119** [Snipaste/feedback#1590]
设想是添加一个以屏幕为中心的坐标系，每个贴图可以自定义贴图原点（左上角，右下角，右上角，左下角，中心），每个贴图可以更改贴图原点在屏幕中心坐标系上的位置（x-100,y-200,#1), [在贴图右键菜单增加一项修改坐标值]。
这样就可以做到像素级贴图移动，主要是鼠标拖拽有时候不准，命令行也不会用。。。。

**Comment by liulex** [comment]
![](https://user-images.githubusercontent.com/2010459/85816764-ccfbef00-b79e-11ea-8681-48306c59724a.png)
