### ISSUE TITLE
能禁止剪切板的文字自动变成贴图吗？

### ISSUE THREAD

**Issue by cxhttt233** [Snipaste/feedback#1595]
经常用到复制粘贴，但是每次复制之后，想要F3贴出来之前截的图就会把剪切板的也弄出来，看了一下没找到关闭的选项，想问一下能关闭吗，剪切板我用ditto管理了，因此这个功能对我来说不实用，增加了麻烦

**Comment by liulex** [comment]
你用 Snipaste 的贴图键贴出来，自然就要转成贴图啊。你剪贴板里还是文字，Snipaste 又没动你的……
