### ISSUE TITLE
切换贴图组快捷键无法使用

### ISSUE THREAD

**Issue by mickeystone** [Snipaste/feedback#1599]
操作系统：win10 [版本 10.0.17763.1217]
snipaste版本：
![图片](https://user-images.githubusercontent.com/11926694/86711054-280acd00-c04e-11ea-97b0-ea90f1b36b26.png)

首选项-- 控制-- 快捷键中， 切换到另一贴图组，显示为灰色，不可用，不知是什么原因？

![图片](https://user-images.githubusercontent.com/11926694/86710965-0f9ab280-c04e-11ea-8738-0b3ba7b293d3.png)

**Comment by liulex** [comment]
你关了自动备份，贴图就不写入硬盘，也就没有贴图组，也就无法切换贴图组。
