### ISSUE TITLE
Pinned snip won't close

### ISSUE THREAD

**Issue by soundneedle** [Snipaste/feedback#1601]
Not able to close a pinned image on Mac. Cannot move the image. When clicking on the pinned image, cursor changes to a circle.

App version:
Platform: macOS

**Comment by soundneedle** [comment]
Also, because the image is permanently pinned on the Mac screen, I'm unable to use snipaste as it blocks whatever it's floating on top of. Tried uninstalling and reinstalling---image remains.

**Comment by liulex** [comment]
It's in edit mode with toolbar hidden. Press <kbd>Space</kbd> on the image window to show the toolbar.
