### ISSUE TITLE
增加 复制图片地址

### ISSUE THREAD

**Issue by w422417869** [Snipaste/feedback#1602]
建议右键图片增加，复制图片地址，那样很多时候可以快速粘贴到地址栏。

如下图

![2020-07-09_10-03-11](https://user-images.githubusercontent.com/36833177/86988744-87421c00-c1cb-11ea-8c41-481712110b04.png)

![2020-07-09_10-03-49](https://user-images.githubusercontent.com/36833177/86988736-84dfc200-c1cb-11ea-94b6-23d5c2fdcee7.png)

**Comment by septs** [comment]
由于此时图片并未被持久化储存下来，因此获得图片路径属于不合理需求。
