### ISSUE TITLE
希望增加多张贴图勾选合并成一张图的功能

### ISSUE THREAD

**Issue by hemeiyu** [Snipaste/feedback#1605]
需求：多张贴图，通过调整摆放的位置，在勾选需要合并的贴图后，单击鼠标右键菜单可合并成一张图。

问题描述：目前无法滚动截屏，导致浏览器页面内容（如表格数据量大显示滚动条时）截屏不全，也有其他方面需要合并多个小贴图的功能。

**Comment by septs** [comment]
Duplicate of #19
