### ISSUE TITLE
macOS（10.15.5）无法关闭贴图

### ISSUE THREAD

**Issue by baymaxbowen** [Snipaste/feedback#1607]
![Snipaste_2020-07-15_19-38-43.png](https://i.loli.net/2020/07/15/1AR8sBJ9Mvxge35.png)

鼠标移到贴图上面后鼠标变成圆圈，并且双击不可以取消贴图，清空截图记录继续贴图还是会出现，再进行截图并贴图，新的贴图会出现，双击可以取消贴图，但是之前的贴图也还会出现，不可双击取消

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/1565
