### ISSUE TITLE
望增加以Snipaste打开方式开启图片，并且打开图片是以PIN的功能模块形式

### ISSUE THREAD

**Issue by hoochanlon** [Snipaste/feedback#1610]
Windows默认看图软件打开图片过慢，窗体过大不方便查看图片，而Snipaste打开图片以pin的方式就很简洁，不占屏幕空间，也有助于边看知识图边学习。

**Comment by thianda91** [comment]
1. 鼠标单击选择图片文件
2. Ctrl + C 复制
3. F3 贴图

🤪

**Comment by hoochanlon** [comment]
![image](https://user-images.githubusercontent.com/35732922/88459608-3e77ac00-cec9-11ea-9285-677f4274c92e.png)
