### ISSUE TITLE
change the quality of images copied to the clipboard

### ISSUE THREAD

**Issue by zcysxy** [Snipaste/feedback#1612]
Thanks for the splendid app!

I often use Snipaste to snip and copy images to the clipboard and then paste them to Word, Markdown, etc. However, the default quality for images copied to the clipboard is too low for me. Sorry that I've no idea if this feature is too hard to implement. Or are you working on this? Thanks in advance.

**Comment by liulex** [comment]
I think the quality is at the best level. If you find it poor, it could be the size of the image is too large and the app where you paste the image scales it.

**Comment by zcysxy** [comment]
![image from clipboard](https://user-images.githubusercontent.com/48207708/90212640-761da800-de26-11ea-9938-007d119d29da.png)
![Snipaste_2020-08-14_12-07-39](https://user-images.githubusercontent.com/48207708/90212839-e75d5b00-de26-11ea-8047-d2d43bf52b5e.png)
I paste a image right here

**Comment by DingXiangYuanZhiXing** [comment]
@liulex On macOS, that seems not true.
### Snipaste (The image blurs when I toggle the shortcut immediately)
<img width="305" alt="image" src="https://user-images.githubusercontent.com/28868457/93714192-a11cb980-fb93-11ea-83cd-162b42c14e9e.png">
### Original
<img width="266" alt="image" src="https://user-images.githubusercontent.com/28868457/93714221-d0cbc180-fb93-11ea-9032-b549be62a54a.png">
And I'm pretty sure that has nothing to do with the Image Quality in the setting.
This happens IMMEDIATELY when starting snip(F1),

**Comment by Krknv** [comment]
Same issue. Poor quality on macOS with retina or external QHD display 😵

**Comment by liulex** [comment]
@dxyzx0 Could you try Snipaste 2.8 Beta2?

**Comment by Krknv** [comment]
I think the problem is with the high res display. The image is much larger at the output. And then, telegram compresses it.

Is there a functionality to compress the image in before pasting?
