### ISSUE TITLE
win10下可能有内存问题

### ISSUE THREAD

**Issue by jackydi** [Snipaste/feedback#1616]
App version: windows桌面版 2.4 64位
系统：win10

现象：我的win10一般开机都是好几天不关机的那种，如果不打开snipaste，啥事儿都没有，但是如果打开了snipaste，并且抓过几张图片之后（snipaste不退出，一直在后台运行），再运行个1天左右，就会出现各种各样的问题，比如任务栏任务缩略图重影，应用的右键菜单无法打开，托盘图标不能显示等等。

为啥怀疑是snipaste呢？

因为我的电脑之前也发生过上面的问题，也不知道到底啥原因，一直怀疑是win10系统的问题。这几天一直用几个软件办公（一个浏览器，一个是vnote，用来写笔记的，微信等），就没打开过别的，当然企业微信之类的都是正常用的，跑了几天一直用的挺好，没关机。昨天把snipaste打开，抓了几个图，然后就没退出，一直在后台呆着，今天发现vnote中的右键突然打不开了，而且复制粘贴非常的慢，打开个任务管理器也慢的不行，再打开notepad++，复制粘贴几次后，连菜单都打不开了。只能重启。

现在想想，之前遇到类似问题的时候，好像都是打开snipaste后，抓过图，然后就一直在后台放着没退出。当然这也只是怀疑，没有明确的证据，作者有时间的话，可以查一下。

**Comment by liulex** [comment]
我经常十几天也没关过，没遇到过问题。

**Comment by jackydi** [comment]
> 我经常十几天也没关过，没遇到过问题。

我经常遇到这个问题，说不上是不是snipaste的问题，因为经常开着它，如果你没有这样的问题，那估计可能是其他软件的问题，也没准就是win10本身的问题呢
