### ISSUE TITLE
【建议】截图时，增加长宽等比例放大选区的功能

### ISSUE THREAD

**Issue by iamfeiyu** [Snipaste/feedback#1617]
**使用场景**
举个栗子：有一个尺寸375px*200px，在截图时，希望能等比例放大选取，这样便可以在保证截图比例不变情况下，截取到合适的图片内容。

**操作方式设想**
方案一：截图时，按住辅助功能键+鼠标左键选中选取边角实现拉缩选取。

**现状**
目前拉缩选区边角是自由变换，暂时没有其它替代方案。即时将比例尺寸计算好添加到自定义截图预设中，也一仍然无法面对网络图片内容的多变，这只能通过截取时随机等比例调整尺寸来完成。

**Comment by chenrylee** [comment]
感觉这个需求像是专业版的某个功能：
![](https://i.v2ex.co/44a2hSwx.png)

**Comment by iamfeiyu** [comment]
你截图所示功能界面，普通版可以使用

**Comment by liulex** [comment]
专业版：
![](https://user-images.githubusercontent.com/2010459/89919649-1fe61480-dc2e-11ea-8f89-12781a9ca165.png)
