### ISSUE TITLE
Snipaste更新错误，希望网站速度优化

### ISSUE THREAD

**Issue by ZetaoYang** [Snipaste/feedback#162]
项目的首页国内访问速度太慢，希望作者优化网站访问速度。 (ps.目前我访问项目首页是挂的美国代理)  

![image](https://cloud.githubusercontent.com/assets/10769951/19026580/2761b19a-895a-11e6-84d1-4f4c75937380.png)  

http://www.17ce.com/site/http/201608_d053ec0f76bf4c1732ae30bba81ca5eb.html  

更新出现这样的错误  
![image](https://cloud.githubusercontent.com/assets/10769951/19026457/b92ad91e-8958-11e6-8464-107ab8ba8665.png)  
其次，希望添加“设置更新代理服务器”的功能，毕竟使用系统代理设置不方便。  
还有一个小小的建议：项目首页可以加上更新日志。

**Comment by liulex** [comment]
1. 网页文件放在美国服务器，国内访问确实慢，但至少没被墙，以后再寻求优化吧。下载是国内外链接都有的，速度应该 ok，所以建议通过内置的在线更新来更新软件。
2. 网络错误 99 通常是由于你程序目录下没有 libeay32.dll 和 ssleay32.dll，请下载完整包并完整解压覆盖。

**Comment by ZetaoYang** [comment]
我说的更新日志是指，比如发行了一个新版本1.8.3，那么在这个版本中修复了哪些bug,带来了哪些新功能能。这个在https://zh.snipaste.com/和https://www.snipaste.com/的页面中都没有写出来。更新日志只是在检查更新后有新版，才在弹框中有体现。

**Comment by ZetaoYang** [comment]
@liulex 没问题了。

**Comment by ZetaoYang** [comment]
![image](https://cloud.githubusercontent.com/assets/10769951/19028095/9d5c4fb2-896a-11e6-82b6-01aca577a8a6.png)
有这两个文件，依然还是有小概率出现 错误99

**Comment by GregAMO** [comment]
补充：更新日志在此，也相当于新功能教学
https://github.com/liulex/Snipaste-Feedback/wiki/更新日志

**Comment by nottellyou** [comment]
个人感觉可以放置一台在linode，或者阿里云国际云上面。流量1T，价格10刀左右。

**Comment by KazamaSion** [comment]
目前 zh 官网(zh.snipaste.com)已经启用了日本节点。对国内速度如图所示（17ce 结果）：  
![](https://i.loli.net/2017/12/11/5a2e821e9af3e.png)    
http://www.17ce.com/site/http/201712_9a331bd36438bdec55f371fb45aea4c3.html  
  
大陆用户可用性相比原来应已大幅提升。海外用户使用位于美国的 www 站即可。
