### ISSUE TITLE
设置数据从 `%LocalAppData%`  转到 `%AppData%`

### ISSUE THREAD

**Issue by b4imetu** [Snipaste/feedback#1621]
版本：Windows Store 免费版

小建议：希望将 `%LocalAppData%\Packages\45479liulios.17062D84F7C46_p7pnf6hceqser\LocalState` 中的设置数据从 `%LocalAppData%`  转到 `%AppData%` 中

不算是实质性的更新，但是大多数应用的配置文件都是保存在 `AppData\Roaming` 目录的，而更多缓存数据可能保存在 `AppData\Local` 中，如此一来就只需要备份这  `Roaming` 这1个文件夹就行了

同时希望 #1552 的问题可以解决

**Comment by liulex** [comment]
这个是微软商店的限制，无法写入 %AppData% 的。
