### ISSUE TITLE
🡴光标指针大小 不能被Snipaste捕获

### ISSUE THREAD

**Issue by dnknn** [Snipaste/feedback#1625]
![bug](https://user-images.githubusercontent.com/10995302/90082019-51033980-dd41-11ea-93a3-96b392d0dc9a.gif)

⛨🐞Debug测试(颜色被捕获,但光标大小不会被捕获), 直达Win¹⁰的自定义光标设置去的🏃捷径:
### 　 `ms-settings:easeofaccess-cursorandpointersize`
　　👆直接在浏览器Alt+D地址栏打开, 或Win+R→粘贴👆Enter打开,直达!
或 `Win+U` 不能直达, 但额外再点击一次即可.

---
ScreenToGif 用 🔌DirectX🔌 就能捕获自定义光标了.
![208_13084417](https://user-images.githubusercontent.com/10995302/90081958-316c1100-dd41-11ea-9004-678674b4692c.png)

所以Snipaste是不是用的🔌API🔌不支持, 还是bug呢

**Comment by liulex** [comment]
谢谢指出，下个版本会修复。
