### ISSUE TITLE
2.5.0版本，默认的为什么是DP，以前默认的是px啊

### ISSUE THREAD

**Issue by donghui1993** [Snipaste/feedback#1626]
![image](https://user-images.githubusercontent.com/15115374/90142468-fbfe0c80-ddae-11ea-82de-55f4ae8e18c5.png)
之前用的是px，希望恢复px的设定，除非购买专业版
软件版本：
运行平台：微软商店

**Comment by liulex** [comment]
一直都是 dp，以前只是没显示单位。

**Comment by donghui1993** [comment]
> 一直都是 dp，以前只是没显示单位。

好吧，我还以为是我用错了，可能我是常规1080的屏幕，没看出来差别
