### ISSUE TITLE
长图贴图

### ISSUE THREAD

**Issue by lishige** [Snipaste/feedback#1627]
如果将很长的图片贴出来的话，会不兼容。
希望可以很好地支持长图地贴图。

**Comment by liulex** [comment]
什么叫 _不兼容_？

**Comment by septs** [comment]
Duplicate of #19

**Comment by liulex** [comment]
[贴图无法拖动超过屏幕上边界](https://docs.snipaste.com/zh-cn/troubleshooting?id=%e8%b4%b4%e5%9b%be%e6%97%a0%e6%b3%95%e6%8b%96%e5%8a%a8%e8%b6%85%e8%bf%87%e5%b1%8f%e5%b9%95%e4%b8%8a%e8%be%b9%e7%95%8c)
