### ISSUE TITLE
snipaste 触发系统全屏模式导致 UWP 最小化/最大化/关闭按钮无法点击

### ISSUE THREAD

**Issue by ikesnowy** [Snipaste/feedback#1628]
打开 snipaste，系统提示「专注助手」已启动，UWP 的标题栏（例如 Windows Terminal 和微软商店）无法点击。

任务栏自动隐藏后，在其他窗口打开时无法呼出，只有 Win+D 返回桌面后才可以呼出。

![image](https://user-images.githubusercontent.com/17109152/90203950-ad835900-de14-11ea-8fe1-0345a7f3460a.png)

日志
[splog.txt](https://github.com/Snipaste/feedback/files/5072340/splog.txt)

软件版本：2.5.0 专业版
运行平台：微软商店

**Comment by liulex** [comment]
似乎和 #1525 类似。可以试试备份 Snipaste 配置后重装 Snipaste.
