### ISSUE TITLE
mac上snipaste无法启动

### ISSUE THREAD

**Issue by meisuTJU** [Snipaste/feedback#1629]
之前安装了snipaste，用了一段时间之后突然有一天没法用了，卸载了重装，snipaste再也没启动起来过，双击运行或者在Application中右键运行都不行，mac顶部状态栏图标里就是不出现snipaste图标，不知道为啥，现在已经被迫用回了钉钉的截图，麻烦看一下什么问题~

软件版本：Mac公测版 v2.5 Beta(2020.08.12)
运行平台：macOS Catalina 10.15.6

**Comment by liulex** [comment]
麻烦贴一下文件 `~/.snipaste/config.ini` 的内容。

**Comment by meisuTJU** [comment]
您好文件~/.snipaste/config.ini 在哪儿可以看到？
















在 2020-08-17 20:19:24，"Le Liu" <notifications@github.com> 写道：

麻烦贴一下文件 ~/.snipaste/config.ini 的内容。

**Comment by MrQiu920702** [comment]
[General]
auto_backup=false
config=~/.snipaste/config.ini
first_run=false
startup_fix=true

[Hotkey]
custom_snip=
hide=
paste=
snip=
snip_and_copy=
switch=

[Interface]
color_mode=2
hide_tray_icon=true
tray_color=#ff00aa00

[Log]
level=6

[Output]
file_name_pattern=emobile\x622a\x56fe$yyyyMMddHHmmss$.png
image_quality=100
quick_save_notification=false
quick_save_path=/emobile\x622a\x56fe$yyyyMMddHHmmss$.png

[Snip]
ask_for_confirm_on_esc=false
border_width=1
copy_as_windows_bitmap=false
show_border_in_magnifier=false

[Update]
check_every=false
check_on_start=false
fake_version=100.100.100

**Comment by MrQiu920702** [comment]
> 麻烦贴一下文件 `~/.snipaste/config.ini` 的内容。

[General]
auto_backup=false
config=~/.snipaste/config.ini
first_run=false
startup_fix=true

[Hotkey]
custom_snip=
hide=
paste=
snip=
snip_and_copy=
switch=

[Interface]
color_mode=2
hide_tray_icon=true
tray_color=#ff00aa00

[Log]
level=6

[Output]
file_name_pattern=emobile\x622a\x56fe$yyyyMMddHHmmss$.png
image_quality=100
quick_save_notification=false
quick_save_path=/emobile\x622a\x56fe$yyyyMMddHHmmss$.png

[Snip]
ask_for_confirm_on_esc=false
border_width=1
copy_as_windows_bitmap=false
show_border_in_magnifier=false

[Update]
check_every=false
check_on_start=false
fake_version=100.100.100

**Comment by septs** [comment]
Duplicate of #1373
