### ISSUE TITLE
关于2.5版本默认路径的问题

### ISSUE THREAD

**Issue by huxim** [Snipaste/feedback#1632]
2.4及之前的版本, 保存截图的默认路径为上一次使用的目录, 如果此目录不存在, 则会使用上一级目录作为默认路径, 这个特性对我来说很有用. 而到了2.5版本, 如果上一次使用的目录不存在, 则会使用桌面作为默认路径, 每次都要重新指定目录, 就很麻烦. 能否回归之前的逻辑?

**Comment by liulex** [comment]
……之前的行为是个 bug，现在修复了。

> 如果此目录不存在, 则会使用上一级目录作为默认路径, 这个特性对我来说很有用. 

什么情况下这样会很有用？

**Comment by huxim** [comment]
> ……之前的行为是个 bug，现在修复了。
> 
> > 如果此目录不存在, 则会使用上一级目录作为默认路径, 这个特性对我来说很有用.
> 
> 什么情况下这样会很有用？

我有一个基本固定的工作目录, 会临时建立若干子目录, 然后在子目录中保存截图, 然后这些子目录会被删除, 再新建一批子目录重复动作. 以2.5版本的逻辑,每次这些子目录被删除之后我都需要重新定位到工作目录, 很麻烦, 所以目前退回了2.4

**Comment by zpr1g** [comment]
哈哈哈，还挺有趣的，又是一个 bug 变 feature 的例子
