### ISSUE TITLE
2.5.0版本无法使用自动保存

### ISSUE THREAD

**Issue by yoyokirby** [Snipaste/feedback#1633]
更新到2.5.0版本后，无法使用截图自动保存功能，无论设置什么路径都没有效果
，截图后不会自动保存到该路径。在首选项-输出页中，自动保存部分，路径一直显示为红色，且打开文件夹按钮不可用。已确认设置的路径是存在的。

使用旧的1.16.2版本可以正常使用自动保存功能，且首选项页中路径不显示为红色，打开文件夹按钮可以正常使用。

软件版本：2.5.0
运行平台：微软商店

**Comment by liulex** [comment]
自动保存那里要设置完整的文件名的，旧版本是只设置文件夹名，正常情况下旧版升级到新版会自动处理的，应该是你自己又改回去了。
你点一下"恢复默认"就知道怎么设置了。

**Comment by yoyokirby** [comment]
可以了，感谢
