### ISSUE TITLE
使用特定鼠标，snippaste无法捕捉鼠标中键事件

### ISSUE THREAD

**Issue by ZengJingtao** [Snipaste/feedback#1634]
使用罗技 Master 3鼠标，Snippaste无法捕捉到鼠标中键事件（导致无法快速贴图、重复贴图）。鼠标事件在其他应用中均可捕捉（例如chrome）。

尝试过使用管理员身份运行，仍无法解决

软件版本：2.5.0（旧版本也如此） 专业版
运行平台：微软商店 / Windows 桌面 / macOS

**Comment by liulex** [comment]
请将日志等级调到“调试”，然后进行截图的中键操作后，将日志文件 `splog.txt` 另存后发到 <snipaste.app@gmail.com>.

**Comment by ZengJingtao** [comment]
> 到

已提交日志，请查收

**Comment by chaohershi** [comment]
戴尔鼠标也不行，应该和品牌无关。
