### ISSUE TITLE
能不能保存最后选择的箭头类型、颜色等？

### ISSUE THREAD

**Issue by blue8228** [Snipaste/feedback#1635]
如题，但不限于箭头，
比如字体，方框等的设置参数，否则下次截图又得重新选一次比如箭头之类的形状，很不方便

**Comment by liulex** [comment]
目前是字体大小的设置有 bug，无法记忆，其他标注的设置都是正常记忆的。
如果有问题，请录屏说明。

**Comment by blue8228** [comment]
1、按快捷键开始截图，先选一个非默认的箭头并截图
2、接着按快捷键继续截图，这次选择一个矩形并截图
3、再次截图，这个时候上次选的箭头就回归默认了

用的是 专业版 2.5.0

**Comment by blue8228** [comment]
经过简单测试已经解决问题，感谢作者！及时修复问题，赞一个！
