### ISSUE TITLE
关于"序号"这个功能优化

### ISSUE THREAD

**Issue by qianc123** [Snipaste/feedback#1636]
有时候在给不同的代码段进行贴图显示，为了排代码流程顺序，就给每张图片上添加序号。
**问题是**：<font color="red">序号不能随意的更改，只能添加多个时才能更改序号，但是我想在第一张图上标注序号为①，在第二张图上标注为②(但是无法更改此序号，除非增加两个序号)</font>

**Comment by liulex** [comment]
![number_start_from_3](https://user-images.githubusercontent.com/2010459/90789871-fa49c100-e339-11ea-8193-04dd8ce1245f.gif)

**Comment by liulex** [comment]
新版已支持调整第一个序号了。
