### ISSUE TITLE
启动后提示【未能正常加载“InlineReviewsPackage”包】

### ISSUE THREAD

**Issue by 215339530** [Snipaste/feedback#1639]
![image](https://user-images.githubusercontent.com/49053190/91011678-53a24080-e617-11ea-9a79-d48c9ad58408.png)

软件版本：1.16.2（2018.01.22）
运行平台：Windows 桌面

**Comment by liulex** [comment]
这跟 Snipaste 无关，并且 1.x 版本也不在维护了。
