### ISSUE TITLE
Changing the color used for text/arrows/rectangles does not change corresponding alpha value

### ISSUE THREAD

**Issue by Paputto0** [Snipaste/feedback#1641]
How to reproduce:
1. Open color picker
2. Change the alpha channel to i.e. 128
3. Add the color to the library
4. Change the active color to anything else <- you will see, that the alpha did not change - it's stuck to the value you put in the box.

App version:
Platform: Microsoft Store

**Comment by liulex** [comment]
Yes, this is by design. Alpha value is separated from RGB.

**Comment by Paputto0** [comment]
Thank you for the reply. This does not fit in my usage scenarios, but I guess I'll just have to change the way I use the app a little bit.

Cheers!
