### ISSUE TITLE
希望在特定程序中不工作

### ISSUE THREAD

**Issue by Shuxu001** [Snipaste/feedback#1643]
搜了下没找到，就是我截图是F1，魔兽里选角色是F1，希望可以加一个在特定程序里snipaste快捷键优先级向后靠靠的功能，或者加个”禁用快捷键“的快捷键，因为每次去点好不方便。最后希望snipaste越来越好！

**Comment by liulex** [comment]
[专业版](https://docs.snipaste.com/zh-cn/pro?id=b-%e6%9b%b4%e8%87%aa%e7%94%b1%e7%9a%84%e5%ae%9a%e5%88%b6%e5%8c%96)可以的。
