### ISSUE TITLE
几点微小的建议

### ISSUE THREAD

**Issue by Geeyun-JY3** [Snipaste/feedback#1644]
1. 请求增加对 [更新日志页](https://docs.snipaste.com/zh-cn/changelog) 的 RSS 支持；
2. 主页、文档、本 repo README 等地的 badge 和其他指向 Microsoft Store 的链接建议统一换成 `https://www.microsoft.com/store/apps/<app's Store ID>` 格式链接（[官方文档](https://docs.microsoft.com/windows/uwp/publish/link-to-your-app)？）；
3. 在应用内 `帮助` 查看相应页面时，点击右上角 `在线查看` 后打开对应页面，如在下图情况下点击 `在线查看` 打开：https://docs.snipaste.com/changelog
![image](https://user-images.githubusercontent.com/49396421/91628640-4c52ac80-e9f4-11ea-81ba-81c644854f4f.png)

**Comment by liulex** [comment]
1. 文档站点是使用 [docsify](https://docsify.js.org/) 生成的，而它[不支持 RSS](https://github.com/docsifyjs/docsify/issues/456)，所以没有办法。你可以关注 [Telegram](https://t.me/snipaste)/[微博](https://weibo.com/snipaste)/[Twitter](https://twitter.com/Snipaste) 获取更新通知。
2. 之前因为微软的问题，导致标准的商店链接在国内打开有问题，所以换了链接。现在似已修复，已更新所有链接。
3. 很棒的建议，我会在下个版本实现的。

非常感谢你用心的建议 ❤️

**Comment by Geeyun-JY3** [comment]
想要 RSS 就是嫌 Telegram/微博/Twitter 搞起 RSS 来有些麻烦🤦‍♂️（虽然 RSSHub 都有方案）。
可不可以在这个 repo 的 release 中放上更新日志？也能附上每个版本的安装包。

**Comment by liulex** [comment]
抱歉，我觉得没有必要，现在发一个版本已经要花我很多时间了。

**Comment by Geeyun-JY3** [comment]
好的吧，可以理解，我自己用 RSSHub 为 Telegram 频道生成 RSS 吧。

**Comment by stevenzhu25** [comment]
@Geeyun-JY3 可以用我的RSSHub这个： https://rss.stevenz.net/telegram/channel/snipaste?code=a1f87770da2d5ff902e200efc93fcb02

**Comment by Geeyun-JY3** [comment]
@stevenzhu25 谢谢，我用官方演示的就可以了。

**Comment by dnknn** [comment]
@liulex  @Geeyun-JY3 关于新版更新内容的推送获知, 参考以下方案, 非常简单, 完全不影响作者时间.

🐈github只有这两种订阅方式是针对特定类型的订阅推送 👇

   　 |  🛰🆕订阅类型  | 示例演示
:---: | :---: |  :---: 
**releases** | 📡RSS　   `https://github.com/{repo}/{repositorie}/releases.atom`       <br><br>![image](https://user-images.githubusercontent.com/10995302/90071805-d0384380-dd28-11ea-93ad-3d13c5ad4b7c.png) | [releases⭜](https://github.com/NickeManarin/ScreenToGif/releases)
**issue** | ![image](https://user-images.githubusercontent.com/10995302/90071522-4daf8400-dd28-11ea-8654-8045599dca78.png) | [issues/1137⭜](https://github.com/sindresorhus/refined-github/issues/1137)


其中issue邮箱订阅是作者单独开设一个专用于更新发布的issue, 用户可自行订阅, 当有新版发布,能够自行主动推送到邮箱, releases也支持邮箱,额外多支持RSS.

关于更新日志, 如有必要的, 最好是附带简短图文并茂的解说, 便于清晰获知, 因为单纯文字描述有时很难说清.
