### ISSUE TITLE
mac版设置了随系统自启动，但实际并不会自启动。

### ISSUE THREAD

**Issue by rockingfire888** [Snipaste/feedback#1645]
mac版，系统为10.15.6，安装的也是最新的测试版，但是即使设置了随系统自启动，却无效。只能每次手动再打开。
软件为 2020.8.26这个版本。

软件版本：
运行平台：macOS

**Comment by liulex** [comment]
我特意试了一下，自启动没有问题。
Snipaste 自启动用的就是最普通的在 `/Library/LaunchAgents` 添加 `plist` 的方式，如有问题请检查系统/其他软件。

**Comment by septs** [comment]
Duplicate of #1056
