### ISSUE TITLE
mac版本无法启动

### ISSUE THREAD

**Issue by plutopaner** [Snipaste/feedback#1646]
升级安装了v2.5.1 Beta (2020.08.26)后，snipaste无法启动。

卸载的时候显示后台正在运行，但是command+option+esc后，进程中没有snipaste。

原来使用的是1.16.2 Beta，macOS升级后也无法使用。

软件版本：v2.5.1 Beta
运行平台：mac  10.15.6

**Comment by liulex** [comment]
#1629
请贴一下文件 `~/.snipaste/config.ini` 的内容。

**Comment by septs** [comment]
Duplicate of #1373
