### ISSUE TITLE
Windows10缩放调到125 snipaste的截图指针也放大了

### ISSUE THREAD

**Issue by 3TUF1VE** [Snipaste/feedback#1649]
截图时候的移动指针 调整截图范围的指针也跟着放大了，系统调回100%缩放指针恢复默认大小，但是我必须要用125%的缩放，但这个snipaste的大指针看着很不协调，有没有办法在125%缩放下调整回正常大小呀？我试过兼容性里面设置DPI都不行。

**Comment by liulex** [comment]
鼠标指针跟随系统缩放，很正常啊……
