### ISSUE TITLE
window版本支持滚动截图

### ISSUE THREAD

**Issue by chenqiaole** [Snipaste/feedback#1655]
能不能尽快支持滚动截图？比如要在ide截图代码有时候，那么长的一个类，还得分多次截图，比较麻烦，做备注标记也很麻烦

**Comment by liulex** [comment]
代码截图根本不需要滚动截图。
![](http://ww2.sinaimg.cn/large/840a8430jw1f68ofsdw0ug20qv0hi1kx.jpg)
