### ISSUE TITLE
请求增添聚光灯功能

### ISSUE THREAD

**Issue by YooKing** [Snipaste/feedback#1656]
先框选一个大范围区域，后使用聚光灯选择小区域，选择之后，给小区域以外的区域加低亮度遮罩，同时小区域也有一个显眼的轮廓。

**Comment by dnknn** [comment]
### 　　　　　　　　　　 Is it this effect ❔ 

　　　　![209_19094808](https://user-images.githubusercontent.com/10995302/93656459-441ee780-fa5d-11ea-98b2-9982459c456b.png)

　　　　　　![00](https://user-images.githubusercontent.com/10995302/93656456-3cf7d980-fa5d-11ea-97e5-82fa3bd300bc.gif)

**Comment by YooKing** [comment]
Yes, it would be better if the shape can be changed

**Comment by dnknn** [comment]
来, 都是关于阴影特效的, 互相链接一下 https://github.com/Snipaste/feedback/issues/1624#issue-678059153

**Comment by Geeyun-JY3** [comment]
重复：#1075

**Comment by Geeyun-JY3** [comment]
Duplicate of #1075
