### ISSUE TITLE
图片边框

### ISSUE THREAD

**Issue by hubginger** [Snipaste/feedback#1658]
这是一款超级好用的截屏软件.
在使用过程中,我发现一个小小的需求,希望能够被采纳:
        目前截屏的图片是没有边框的,
        没有边框放在白色底色的文本中,看起来会不好看,
        希望可以在设置中,新增截图边框设置,这样图片放到文稿会好看很多.

望采纳
        祝好

**Comment by liulex** [comment]
专业版支持的。
