### ISSUE TITLE
窗口置顶

### ISSUE THREAD

**Issue by FrontendStack** [Snipaste/feedback#1661]
使用场景：
前端开发，在IDE全屏的情况下，又需要通过Chrome实时预览效果，或查看控制台日志。

**Comment by liulex** [comment]
其他程序的窗口不归 Snipaste 管。

**Comment by chaohershi** [comment]
这题我会，[CClose](https://chaohershi.github.io/cclose/)可以实现你要的窗口置顶。

**Comment by FrontendStack** [comment]
> 这题我会，[CClose](https://chaohershi.github.io/cclose/)可以实现你要的窗口置顶。

谢谢 找了很久
