### ISSUE TITLE
建议增加截屏后“跳过点击确认 自动保存”的功能

### ISSUE THREAD

**Issue by huihui278** [Snipaste/feedback#1662]
建议增加截屏后跳过双击确认自动保存的功能。因为有很多时候是需要快速地截屏保存的，而不是去编辑，这时候截屏后再去确认保存，现在snipaste打开自动保存也需要双击确认后才能保存，这样就浪费了时间和使工作变得更加繁琐，如果截屏后直接自动保存就可以大幅度提高工作效率。

**Comment by liulex** [comment]
专业版里将这个命令绑定到快捷键就可以了：
![image](https://user-images.githubusercontent.com/2010459/93777358-3cc32e00-fc57-11ea-9363-d654d97e0029.png)
