### ISSUE TITLE
#1531 后续问题

### ISSUE THREAD

**Issue by sgricky** [Snipaste/feedback#1664]
如题（#1531已关闭）
https://github.com/Snipaste/feedback/issues/1531#issuecomment-691701752

软件版本：2.5.1
运行平台：macOS 10.15.6 (19G2021)

**Comment by liulex** [comment]
谢谢反馈，确实还有问题，请等待下个版本修复。

**Comment by liulex** [comment]
新版已发布，麻烦你再试一下~

**Comment by sgricky** [comment]
> 新版已发布，麻烦你再试一下~

试了一下，貌似可以正常用鼠标快捷键截图了。
设置图如下：
![Snipaste_2020-10-23_00-32-34](https://user-images.githubusercontent.com/10599751/96902584-47c3e500-14c7-11eb-97f1-853662273e18.jpg)

**Comment by liulex** [comment]
嗯嗯，谢谢反馈！

**Comment by sgricky** [comment]
> 新版已发布，麻烦你再试一下~

另外，能不能在这里请教下“滚动截图”是怎么操作的（如果有）？

**Comment by liulex** [comment]
没有的。
