### ISSUE TITLE
Mac最新版本一截图就转风火轮

### ISSUE THREAD

**Issue by BlinVin** [Snipaste/feedback#1665]
Mac最新版本一截图就转风火轮卡个几秒，如果系统不支持窗口检测那就别强行加入了吧，反正鼠标划取得更精确一些，目前Snipaste需要发挥自己的强项———贴图功能，以及加入滚动截屏功能。一截图就卡真的伤不起  🤣🤣

App version:2.5.1 Beta
Platform: macOS

**Comment by liulex** [comment]
请验证 Snipaste 2.6 Beta 是否还有问题。如有请 Reopen issue.
