### ISSUE TITLE
希望可以提供安全截图功能

### ISSUE THREAD

**Issue by ArriettyQAQ** [Snipaste/feedback#1666]
如下图，希望可以提供类似的安全截图功能，能对图片上的文字部分自动打马赛克，或者允许用户自定义多个自动打马赛克的范围，并仅对文字打马赛克。
下图来自Directory Opus提供的安全截图功能

![QQ图片20200926150049.png](https://i.loli.net/2020/09/26/SIRJqc8GL4fAl5h.png)

**Comment by septs** [comment]
软件无法预测你需要打码区域，因此我认为该需求无效。
