### ISSUE TITLE
软件截屏时屏幕变暗黄色

### ISSUE THREAD

**Issue by lcyan** [Snipaste/feedback#1667]
电脑安装了护眼软件Iris.软件截屏时屏幕变暗黄色，退出Iris软件后截图正常

软件版本：2.5.1-Beta
运行平台：Windows 桌面
![微信图片_20200927161844](https://user-images.githubusercontent.com/3824082/94360037-23016b00-00dd-11eb-85f5-7b268c5b1166.png)

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/1239#issuecomment-602695713
