### ISSUE TITLE
希望官方能够推出Linux版本

### ISSUE THREAD

**Issue by Mintonmu** [Snipaste/feedback#1668]
我觉得Snipate比隔壁FlamesHot要好，所以希望官方能够加速推出Linux版本的Snipaste。
同样作为C++ 开发者，也可以帮忙做测试模块。
希望官方能够开发Linux版本，谢谢！

**Comment by leslielg** [comment]
同希望

**Comment by zhangshengping** [comment]
非常期待呀！
现在切到LINUX环境下工作，一直没有找到可以匹敌Snipaste的截图软件！

**Comment by Aoi-hosizora** [comment]
+1，期待

**Comment by JACKCHEN99** [comment]
最近换工作, 公司是使用ubuntu系统的, 实在没找到合适的截图贴图软件. 试用了FlamesHot, 还是和snipaste差了不少...不知道linux版本什么时候能推出阿

**Comment by jinnzy** [comment]
+1啊，希望可以使用Linux版本的

**Comment by lunzilunzi** [comment]
持悲观态度.毕竟5年前就说要开发linux版本,结果...

**Comment by Geeyun-JY3** [comment]
https://github.com/Snipaste/feedback/issues/282#issuecomment-268238395

**Comment by lynnYoun** [comment]
同样期待，现在主要还在用win10办公很大一个原因是这个截图软件带来的好处。

**Comment by septs** [comment]
Duplicate of #711

**Comment by chen462488588** [comment]
+1 hoped

**Comment by WBG-boot** [comment]
+1

**Comment by Mora1n** [comment]
+1
