### ISSUE TITLE
截的图全是黑色的的图片

### ISSUE THREAD

**Issue by SkyLake777** [Snipaste/feedback#1674]
软件版本：
运行平台：微软商店 / Windows 桌面 / macOS

**Comment by stevenzhu25** [comment]
@SkyLake777 你什么系统啊？
Mac的话给截图（屏幕录制）权限了么？

**Comment by liulex** [comment]
Windows 上截图黑色是没有截图权限，请检查安全软件或系统权限设置。

**Comment by small-rose** [comment]
> Windows 上截图黑色是没有截图权限，请检查安全软件或系统权限设置。

可是防火墙，杀毒，电脑管家各种乱七八糟的都关了，使用管理员运行，截图还是黑屏

**Comment by stevenzhu25** [comment]
> > Windows 上截图黑色是没有截图权限，请检查安全软件或系统权限设置。
> 
> 可是防火墙，杀毒，电脑管家各种乱七八糟的都关了，使用管理员运行，截图还是黑屏

你用Win + Shift + S截图有反应么？
