### ISSUE TITLE
第三方程序触发的截图命令导致无法编辑截图

### ISSUE THREAD

**Issue by xuxingqiang** [Snipaste/feedback#1675]
正常来说：使用快捷键F1，截图后在截图下方存在工具栏(可以添加条形框、箭头、文字等等的那个工具框)

异常情况：我同时使用了其他软件MultiTouch(触摸板软件)，然后在该软件中设置了“单击左上角”事件触发了snipaste截图软件的的F1快捷键，这时能够调出截图程序，直接就截图成功并复制到剪切板了，但是截图后不能编辑(没显示工具栏就直接复制到剪切板了)
复现率：100%

软件版本：2.5.1-Beta(20200826)
运行平台：macOS

**Comment by liulex** [comment]
检查 Snipaste 的快捷键设置，默认的快捷键除了普通截图以外，还有截图并自动复制。
