### ISSUE TITLE
win10  打开任务管理器界面 按 F1 没反应

### ISSUE THREAD

**Issue by zero-52** [Snipaste/feedback#1676]
在任务管理器界面按 F1 没反应，不知道是否为热键冲突，关闭任务管理器或者切换到其它界面恢复正常。

**Comment by liulex** [comment]
[https://docs.snipaste.com/zh-cn/troubleshooting?id=有时候快捷键不响应](https://docs.snipaste.com/zh-cn/troubleshooting?id=%e6%9c%89%e6%97%b6%e5%80%99%e5%bf%ab%e6%8d%b7%e9%94%ae%e4%b8%8d%e5%93%8d%e5%ba%94)
