### ISSUE TITLE
关于保存截图时遮罩存在导致的不便

### ISSUE THREAD

**Issue by huxim** [Snipaste/feedback#1677]
我经常会使用ditto/copyq来保存剪贴板历史, 现在遇到的一个问题就是, Snipaste在保存截图时, 由于遮罩依然存在, 导致其他程序无法显示, 我也就无法调出ditto来调用之前的记录, 能否在保存对话框出现的时候去掉遮罩?

**Comment by liulex** [comment]
![image](https://user-images.githubusercontent.com/2010459/95682922-b2993480-0c1a-11eb-84df-91def98ce349.png)
