### ISSUE TITLE
Excel 复制单元格,框线显示不完整

### ISSUE THREAD

**Issue by 4-SR** [Snipaste/feedback#1678]
复制Excel 单元格,贴图时框线显示不完整
软件版本：
![Snipaste_2020-10-11_11-44-41](https://user-images.githubusercontent.com/47027407/95669839-71bc0400-0bb7-11eb-8e43-308729f95dcd.png)
![Snipaste_2020-10-11_11-45-45](https://user-images.githubusercontent.com/47027407/95669854-9912d100-0bb7-11eb-8ce6-8f9dfae5d8c6.png)

运行平台：微软商店

**Comment by liulex** [comment]
这个图像是 Excel 生成的，跟 Snipaste 无关。你在 Excel 复制，在画图程序粘贴，也是一样的效果。
