### ISSUE TITLE
[求助] 如何去掉截图提示框?

### ISSUE THREAD

**Issue by yslhzj** [Snipaste/feedback#1679]
如下图所示:
![image](https://user-images.githubusercontent.com/29890756/95696231-e56c1880-0c6c-11eb-97de-95c9276a12b8.png)

**Comment by liulex** [comment]
![image](https://user-images.githubusercontent.com/2010459/96884857-91ef9b00-14b4-11eb-950f-3e7a8fbf977f.png)
需要专业版。
