### ISSUE TITLE
会留一张贴图无法销毁

### ISSUE THREAD

**Issue by azhenge** [Snipaste/feedback#1681]
截图多张, 然后销毁贴图, 会留一张图无法销毁
显示所有贴图, 有一张图销毁不了

软件版本：
运行平台： macOS

![image](https://user-images.githubusercontent.com/1941717/95806902-77425700-0d3b-11eb-9a3d-4c8ee5ce3a1b.png)

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/673#issuecomment-354467994
