### ISSUE TITLE
希望能够有添加一个水印功能

### ISSUE THREAD

**Issue by KPWorkspace** [Snipaste/feedback#1682]
你好，希望能够添加一个截图自带水印功能。
我常用的是贴图功能，有些时候，我希望能够在我截图后，记录下当前截图时间，以便在后续展示给别人看时，能够让别人知道这张图是什么时候截取的。
当前我解决这个问题的办法是：在截图的时候自己标注出当前时间，不过觉得有点麻烦，所有有了这个issue，
希望作者能够在空闲的时候添加一下这个功能，谢谢，🙏
，最后多谢作者开发的这个工具，真的很nice

**Comment by chenrylee** [comment]
这个需求可以通过截图的时候同时保存文件实现，命名根据日期和时间就可以了。

至于图片上加水印，很难确定水印的位置，以避免关键信息被覆盖。
如果一定要在图片上加，可以截图之后自己添加文字就可以了。

**Comment by hoohyaIII** [comment]
我也觉得有必要加一个这个功能，而且最好是可以加入某张图片作为水印。截图的时候，可以移动这个图片，这样就不会挡住重要的信息了

**Comment by septs** [comment]
Duplicate of #454

**Comment by gilliantguo** [comment]
我也想要，能自动加logo就更好了

**Comment by gilliantguo** [comment]
这是来自本邮箱的自动回复邮件：我已收到您的邮件！谢谢！
