### ISSUE TITLE
希望标注的矩形能增加圆角调节功能，还有蒙版/高亮的标注形式

### ISSUE THREAD

**Issue by Amor-Ye** [Snipaste/feedback#1683]
1. 希望标注的矩形能够调节圆角；

2. 希望增加蒙版/高亮的标注形式，即要强调的部分为高亮或正常显示，其余部分是半透明暗色遮罩。

**Comment by chenrylee** [comment]
1.  #1185

**Comment by Geeyun-JY3** [comment]
2. #1075

**Comment by Geeyun-JY3** [comment]
Duplicate of #1075

Duplicate of #1185

**Comment by Geeyun-JY3** [comment]
Duplicate of #1185
