### ISSUE TITLE
设置界面字体后，更改不完全

### ISSUE THREAD

**Issue by chaohershi** [Snipaste/feedback#1684]
在 界面 -> 常规 -> 界面字体 做修改后，控制 -> 全局快捷键 左侧的命令文字字体没有被更改。
![Snipaste_2020-10-22_12-23-14](https://user-images.githubusercontent.com/22566267/96901992-f6cdd580-1461-11eb-91d5-386cb9d6bed2.png)

此时添加新的命令，字体正确显示。
![Snipaste_2020-10-22_12-24-36](https://user-images.githubusercontent.com/22566267/96902027-00efd400-1462-11eb-81a1-18ed36501568.png)

再将界面恢复默认，新添加的命令字体不会恢复。
![Snipaste_2020-10-22_12-26-01](https://user-images.githubusercontent.com/22566267/96902048-04835b00-1462-11eb-8430-d91d73335656.png)

软件版本：2.5.12-Alpha2 (2020.10.11)
运行平台：微软商店

**Comment by liulex** [comment]
收到，谢谢反馈。
