### ISSUE TITLE
win10贴图到桌面后，移出屏幕顶端会自动缩小尺寸

### ISSUE THREAD

**Issue by 15d23** [Snipaste/feedback#1685]
App version: v2.5.2 (2020.10.18)
Platform:Windows Desktop 10
![bug](https://user-images.githubusercontent.com/3524489/96946190-39e78180-1512-11eb-8abd-c2765e0c3611.gif)

**Comment by 15d23** [comment]
windows store 版测试后也是同样的问题

**Comment by liulex** [comment]
这个好像是某个系统设置的问题，印象中有用户跟我分享过，但聊天记录丢了，所以记不起来是什么设置了。。

**Comment by chaohershi** [comment]
Settings -> System -> Multitasking -> Snap windows，打开后问题解决，关闭后复现。

![Snipaste_2020-10-22_21-54-36](https://user-images.githubusercontent.com/22566267/96947489-51dae900-14b1-11eb-89c4-fb2f6d4a8c6b.png)

**Comment by liulex** [comment]
@chaohershi 非常感谢提供重现条件。
虽然这是系统设置导致的，不过 Snipaste 还是能够兼容一下的，会在下个版本修复。

**Comment by 15d23** [comment]
哦~~原来是这样！难受了快1年了，原来是win10的锅~~因为我不喜欢windows自动贴边功能，所以一直是关闭的.

**Comment by 15d23** [comment]
![bug](https://user-images.githubusercontent.com/3524489/98184264-e844eb00-1f44-11eb-8a3e-12c9d334b51b.gif)
移动到边缘已经没问题了，拖动大小后，比例会变。

**Comment by liulex** [comment]
\_(:з」∠)\_ 等下次更新吧。
