### ISSUE TITLE
更新地址无法以普通方式访问

### ISSUE THREAD

**Issue by 15d23** [Snipaste/feedback#1686]
App version:  Version2.52-Beta(2020.10.18)
Platform: Windows Desktop 10 v2004(sBud19041.572)

第一次点击后，出现网络权限错误：
![image](https://user-images.githubusercontent.com/3524489/97085370-9b613a80-164f-11eb-8ce2-58d5b5310fe5.png)

再次点击后，提示错误操作取消：
![image](https://user-images.githubusercontent.com/3524489/97085408-e54a2080-164f-11eb-9dcd-aea876d90aa5.png)

添加fq代理后，以通知的形式反馈已经是最新，界面无反馈。

**Comment by KazamaSion** [comment]
您好，在经过自身排查后并未能成功复现。
请问能否加入 Telegram 群组以便后续联系，或者留下您的联系方式？

**Comment by liulex** [comment]
这个错误的含义是 `The socket operation failed because the application lacked the required privileges.`
看来是你禁用了 Snipaste 的网络权限，或者是你的本地网络问题。

**Comment by 15d23** [comment]
> 您好，在经过自身排查后并未能成功复现。个人推测可能的原因是：纯 IPv4 网络下尝试连接 IPv6 地址导致。
> 请问能否加入 Telegram 群组以便后续联系，或者留下您的联系方式？

您好，己加群，直接在群里反馈么？

**Comment by 15d23** [comment]
> 这个错误的含义是 `The socket operation failed because the application lacked the required privileges.`
> 看来是你禁用了 Snipaste 的网络权限，或者是你的本地网络问题。

的确是火绒拦下了，当时查看日志并无记录，昨天添加代理后正常，以为是更新地址出错。今天退出火绒后，一切正常。
