### ISSUE TITLE
alpha png mouse drag failed on transparent area

### ISSUE THREAD

**Issue by redrug** [Snipaste/feedback#1690]
App version:
Platform:  Windows Desktop v2.5.1-beta

OSVersion:
Windows 7 sp1 x64

Description:
mouse drag failed on a pasted png file where transparent pixel under the mouse.

**Comment by liulex** [comment]
You can solve it by using the pseudo transparent mode. (PRO version required)
![image](https://user-images.githubusercontent.com/2010459/98430781-0ba99a80-20eb-11eb-9824-db3ce7d03d22.png)
