### ISSUE TITLE
mac 2.5.2-beta 版 自动检测窗口bug

### ISSUE THREAD

**Issue by VINSERTAN** [Snipaste/feedback#1692]
你好，我用的是snipaste 2.5.2 beta 的mac版
自动检测窗口的功能在我的主屏幕上不能用，但是在副屏上就可以用
我把外接显示器拔了之后，自动检测窗口的功能在macbookpro的屏幕上也是不可用的状态
请帮助解决一下，谢谢～

**Comment by septs** [comment]
Duplicate of #1200
