### ISSUE TITLE
双屏截图时卡死

### ISSUE THREAD

**Issue by cwup** [Snipaste/feedback#1696]
两个显示器，一个是横着的，一个是竖着的，截图时隔一两天会出现卡死的问题，按下快捷键没反应，过了几秒或者十几秒弹出来截图界面也无法正常截图，ESC键无法退出，只能调出任务管理器强制关闭。偶发Bug，所以没法录屏。

https://ftp.bmp.ovh/imgs/2020/11/cf43acaca8d2a22f.png

https://ftp.bmp.ovh/imgs/2020/11/51161bd488446059.png

软件版本：截止到2.5.1-Beta已经换了好几个版本了，包括稳定版都有这个Bug。
运行平台：Win7

**Comment by liulex** [comment]
应该跟双屏没关系，只是对特定窗口进行元素检测的时候卡住了，参考 #116 #290.
