### ISSUE TITLE
win10双屏不同分辨率截图异常

### ISSUE THREAD

**Issue by Magnix00** [Snipaste/feedback#1698]
win10系统笔记本外接显示屏，如果两个屏幕设置的分辨率不同，在1屏上截图，再切换到2屏上截图，那么第一次截图区域会异常。反之，再从2屏切换到1屏截图，也会异常。测试必现，两台笔记本都测试复现，对比测试了微信截图和win10自带截图正常。
希望帮忙解决这个问题呀，因为这个问题，为了正常使用，牺牲了显示效果，换成相同分辨率。

**Comment by Magnix00** [comment]
纠正一下，设置的不同的缩放会到导致这个问题！

**Comment by liulex** [comment]
谢谢反馈，会很快修复的。

**Comment by vt-rli** [comment]
效率真高！
正准备提交双屏截图的issue发现竟然已经修复了，谢谢作者！
