### ISSUE TITLE
请问可否是用更加通用化的截图编辑工具快捷键?

### ISSUE THREAD

**Issue by ghost** [Snipaste/feedback#1699]
在使用snipaste的时候经常会用到编辑图像的功能,而为了更快捷我一般会选择使用快捷键.
但是snipaste的工具快捷键都是ctrl+1,ctrl+2这种按照顺序排列的并不是很方便使用(对于很多已经用惯了ps等工具的人来说)
可不可以让编辑工具的快捷键变成这样呢?

- p : pen 笔工具
- a : arrow 箭头
- t : text 文字输入
- e : eraser 橡皮
- l : line 折线

这样真的可以提高一些使用效率呢!

软件版本：2.5.2
运行平台：微软商店

**Comment by dnknn** [comment]
`A`  arrow 箭头, 非常不错! 因为处在左手黄金按键, 其它你提到的 `P` `L` 都是左手难以按到的, 实用性欠佳, 截图编辑操作一般离不开右手拿鼠标操作, 因此标注快捷键必须也处在左手按键区位才高效.

![Pic-200611_250](https://user-images.githubusercontent.com/10995302/84306690-65368900-ab8e-11ea-9713-28946bd39c3b.png)

把文字标注 ⌨快捷键 设为 `T` 非常完美,  只因文字标注的icon图标是 `T` 字 刚好象形呼应, 有时潜意识里就会想按下 `T` 键.

---
另外、给你补充下, Snipaste早就支持 `E`  橡皮擦快捷键. 另外除了`Ctrl+1/2/3/... ` 也还能用`Ctrl+Tab/Ctrl+Shift+Tab`	顺序切换标注.

**Comment by kasusa** [comment]
原来早就有`E` (eraser)了啊..
但是另外的 Ctrl+Tab/Ctrl+Shift+Tab 快捷键不是很好用哦...
最常用的快捷键是(我希望能有的):
1. 笔工具 B (我记得ps里面好像就是b)
2. 方框工具 R (rectangle , 在adobeXD里面是这样的)
3. 箭头 A 
如果能有真的可以方便很多呢!

**Comment by dnknn** [comment]
> 但是另外的 Ctrl+Tab/Ctrl+Shift+Tab 快捷键不是很好用哦...

不是好不好用问题, 而是可以不用但不能没有, 因为它本来就是全球通用的顺序切换的标准快捷键.

**Comment by chenrylee** [comment]
快捷键这东西，各人有各人的习惯，最好的方法就是支持自定义。
当然，如果不支持，Windows上装个PowerToys自己mapping就好了，想怎么按都可以。

**Comment by Geeyun-JY3** [comment]
合并至 #1859
