### ISSUE TITLE
建议：在 ‘版本历史’ 这一栏中添加各个旧版对应的下载链接

### ISSUE THREAD

**Issue by ZetaoYang** [Snipaste/feedback#170]
希望在此页面上  https://zh.snipaste.com/download.html#  ‘版本历史’ 这一栏中添加各个旧版对应的下载链接。这个做的好处：
1.可以保证用户可以回滚到更稳定的版本。
2.可以给用户更多的自由度去选择版本。

**Comment by liulex** [comment]
嗯，目前没有实现这个，因为有些版本是我不建议用户再继续使用的。
这样筛选下来，可供长期稳定使用的版本并不多，我也不希望用户拿着某个旧版来跟我报 bug……
等产品整体成熟了之后再考虑提供吧。
