### ISSUE TITLE
日文语言下设置界面显示问题

### ISSUE THREAD

**Issue by fatefree24** [Snipaste/feedback#1700]
贴图选项卡中最后一选项显示不正常
![image](https://user-images.githubusercontent.com/35786431/98193359-f819fa80-1f57-11eb-9970-ca20c19b2a11.jpeg)

软件版本：2.5.4-beta(2020.11.05)
运行平台：Windows 桌面

**Comment by liulex** [comment]
翻译的问题，谢谢反馈，已修复：https://github.com/Snipaste/translations/commit/acc9d2fa8f1678406f11741c0187c18e91344965
