### ISSUE TITLE
贴图无法选中和清除

### ISSUE THREAD

**Issue by Jinming-D** [Snipaste/feedback#1702]
![image](https://user-images.githubusercontent.com/46744086/98241148-7d77cc00-1fa5-11eb-846b-bffb2dfa8923.png)
Mac版 离线断网环境下使用
一打开软件这张贴图就在，一直置顶，但是没有办法选中，也没办法清除
只能选择隐藏所有贴图，但是一贴其他图这个又出来了
卸载了软件重新安装也不行
该如何解决？

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/1565#issuecomment-640743640

**Comment by Jinming-D** [comment]
看了一下已关闭案例，贴图都可以选中
我的光标移动到贴图范围内的时候贴图依旧在最顶层，鼠标点击只能点到贴图下方的网页

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/980#issuecomment-429560371

**Comment by Jinming-D** [comment]
已解决，多谢~
