### ISSUE TITLE
贴图放大的问题

### ISSUE THREAD

**Issue by ygyhub** [Snipaste/feedback#1703]
贴图放大似乎没有上限限制。
尝试放大到10000%以上后，内存CPU高占用，销毁之后内存回复正常，不过除了误操作一般也不会放到那么大

![image](https://user-images.githubusercontent.com/35786431/98253084-92f4f200-1fb5-11eb-9093-9557d9f90d3e.gif)
软件版本：2.5.4-Beta
运行平台：Windows 桌面

**Comment by liulex** [comment]
我认为没有必要做限制。
