### ISSUE TITLE
关闭把文本转成图片贴出的功能

### ISSUE THREAD

**Issue by metthewzy** [Snipaste/feedback#1704]
请问可以增加一个选项，关闭把剪贴板里的文本转成图片贴出的功能吗？
目前就算用贴图功能专门把图贴到桌面，暂时关闭后如果想要再把图片贴出来，也会先把剪贴板里的文本先贴出来然后才是图片
我希望可以关闭文本转贴图，这样贴图片的时候就可以不受文本的影响

或者说是不是我贴图的方法有问题，有什么正确的方法可以保证我用snipaste贴图键的时候只会贴截图？

**Comment by chenrylee** [comment]
有开关的：  
![image](https://user-images.githubusercontent.com/10664121/98313953-f449af00-200f-11eb-990c-1c93652c2dc2.png)

**Comment by metthewzy** [comment]
谢谢！
