### ISSUE TITLE
应用内帮助快捷保存的快捷键说明多了个 `Shift`

### ISSUE THREAD

**Issue by Geeyun-JY3** [Snipaste/feedback#1705]
软件版本：v2.5.4
运行平台：微软商店
![image](https://user-images.githubusercontent.com/49396421/98367795-35be7680-2071-11eb-9fa1-1e93cf548cb0.png)
应该是 <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>S</kbd>

**Comment by liulex** [comment]
谢谢反馈，下次更新会把图标显示上：
![image](https://user-images.githubusercontent.com/2010459/98430481-8c1acc00-20e8-11eb-8779-7c04fcf1e11f.png)
