### ISSUE TITLE
命令行使用 -o 参数后没有标注工具

### ISSUE THREAD

**Issue by CapZhang** [Snipaste/feedback#1707]
使用`Snipaste.exe snip -o FILE_NAME`命令后，框选后直接截图保存了，没有出现标注工具库，这是为什么呢

**Comment by liulex** [comment]
`-o` 就是截图区域确定后自动输出截图的意思，如果还让你标注，那我什么时候自动输出截图呢？

**Comment by CapZhang** [comment]
我明白了，我理解的是标注后输出，看重的是截图标注，而作者的意图是希望能够截图输出一气呵成。。
