### ISSUE TITLE
需求：暂停热键功能

### ISSUE THREAD

**Issue by crashstars** [Snipaste/feedback#171]
我自己习惯每个程式都添加了一堆热键的
所以有时开启几个程式时热键会有冲突

希望能有一键暂停其他热键，等使用完某程序关了後，再按回可恢复使用

**Comment by GregAMO** [comment]
@crashstars

**Comment by crashstars** [comment]
差不是这样，可以的话希望在键盘上操作
在键盘上按下某一设置的快捷键後就能暂停，其间只有这一快捷键生效(按回恢复)

**Comment by liulex** [comment]
相关讨论：#84 #160 
但黑名单机制会遭遇权限问题，所以或许还是提供热键进行禁用比较好。

**Comment by fangzister** [comment]
建议：
1.为贴图右键菜单中的菜单项增加accesskey。
![snipaste_20170607_094652](https://user-images.githubusercontent.com/19897143/26858885-ac41f964-4b66-11e7-9e66-4d6fc595e884.png)

2.截图添加文字时可以设置字号。
![snipaste_20170607_094906](https://user-images.githubusercontent.com/19897143/26858892-b27e5034-4b66-11e7-86b9-5ab14de5aaca.png)

**Comment by EMLVIRUS** [comment]
> 设置字号

@fangzister 放大文本框即可

**Comment by liulex** [comment]
@fangzister 
![snipaste_20170607_103408](https://user-images.githubusercontent.com/2010459/26859798-c752bdf0-4b6c-11e7-8278-312b11856bc9.png)

**Comment by kiiali** [comment]
1.为贴图右键菜单中的菜单项增加accesskey。

相當贊同。

**Comment by trevim99** [comment]
>希望能有一键暂停其他热键，等使用完某程序关了後，再按回可恢复使用
一鍵暫停其他熱鍵是老議題了，希望開發者能加入這個功能
謝謝
