### ISSUE TITLE
mac 版 2.5.2 beta 截图尺寸大小希望默认@1x

### ISSUE THREAD

**Issue by blackux** [Snipaste/feedback#1711]
mac 版2.5.2 beta
截图尺寸的大小 建议可以设置，以前都是@1x 的大小，现在截图都是@2x 的大小，还要自己换算下。
![image](https://user-images.githubusercontent.com/29528771/98777729-39b11680-242c-11eb-9441-cbee0d769574.png)

**Comment by wzw828** [comment]
顶下这个问题！确实每次都要算，有点麻烦！

**Comment by liulex** [comment]
好的，下版本改回去。。
