### ISSUE TITLE
希望学习

### ISSUE THREAD

**Issue by LeoWang2007** [Snipaste/feedback#1712]
希望可以将以前的版本开源，可以让新手学习一下，谢谢

**Comment by chenrylee** [comment]
人家吃饭的东西，让人家放出来，貌似不太合适。。。
虽然现在版本迭代很久了，但是感觉大体上还是基于之前的基本功能修修补补加加减减……
不过，这完全是作者的意愿了，开源会感谢分享，不开源也完全理解。
