### ISSUE TITLE
复制纯文本后贴图字体允许自由选择

### ISSUE THREAD

**Issue by dc3ea9f** [Snipaste/feedback#1713]
### 现在的情况
复制纯文本后贴图后，贴图中字体非等宽字体

如复制如下**纯文本**：
```
To-do List A:
[ ] a
[*] b
[x] c

To-do List B:
[ ] d
[*] e
[x] f
```
贴图结果为：
![image](https://user-images.githubusercontent.com/32273662/98845702-0e104980-2489-11eb-936a-a99ce8710abd.png)

### 想要什么
复制后字体是等宽的，如（忽略背景颜色）：
![image](https://user-images.githubusercontent.com/32273662/98845769-26806400-2489-11eb-9db2-3b70e9ae28ba.png)

### 具体是什么样的
在【首选项-贴图】中新设置一个选项，该选项可以设置复制纯文本后贴图的字体，如`Consolas`。

### 为什么需要它
对于某些特定文本（如To-do List）等宽字体更好看。

**Comment by chenrylee** [comment]
既然需要保持原来的样子，为什么不直接截图呢？ 😄

**Comment by dc3ea9f** [comment]
> 既然需要保持原来的样子，为什么不直接截图呢？ 😄

因为源文本可能是非等宽的，我可能只是临时记录以后续贴图方便查看，并没有用等宽字体的编辑器。

在我的使用场景中，是用Sublime Text 3记录的，截图后背景颜色是编辑器颜色，而我想要白色/无色的。

**Comment by liulex** [comment]
???
![image](https://user-images.githubusercontent.com/2010459/98951514-4f5e3300-2535-11eb-9855-903a5704752a.png)

**Comment by dc3ea9f** [comment]
> ???
> ![image](https://user-images.githubusercontent.com/2010459/98951514-4f5e3300-2535-11eb-9855-903a5704752a.png)

抱歉，是我智障了。
感谢！
