### ISSUE TITLE
关于快捷键冲突的问题

### ISSUE THREAD

**Issue by XiaoSongZhuo** [Snipaste/feedback#1714]
最近升级到了最新版本，并且买了专业版，发现这个专业版的功能就是确实很多。但是设置快捷键不能覆盖自带的内置快捷键，确实不太友好，以前的版本好像是可以的。自己没有办法，只好写了个按键映射的脚本，才勉强的使用自己心仪的快捷键。
    我在设置快捷键的时候，遇到了一个问题，就是以前的快捷键可以设置纯数字键截图，贴图。然后并且这个截图贴图的快捷键可以覆盖这个内置数字快捷键的功能。
    但是现在好像不行了，不能覆盖内置快捷键，而且专业版数字快捷键增加到了1-6，但是有些快捷键不是太常使用。希望能够考虑在设置快捷键的时候，能不能覆盖内置快捷键。
    谢谢了！！！

**Comment by liulex** [comment]
现在版本不允许纯数字/字母**全局**快捷键的原因是，如果设置了，你就无法在其他程序上正常输入数字/字母了。
内置快捷键的自定义逻辑比较复杂，暂时不会支持，以后会有的。
