### ISSUE TITLE
严重bug-截图置顶清除不了

### ISSUE THREAD

**Issue by aNewContent** [Snipaste/feedback#1715]
Bug report
截图后的一张图片被置顶无法清除，重启软件、关掉所有snipaste进程重启后这张截图仍然存在并置顶。试过清空截屏记录还是清除不了。Ctrl+F3可以隐藏全部，但是再次使用F1截图后这张截图又显示出来了。
其它特征，在这张截图上鼠标指针会变成线条圆圈，右击无任何响应，双击左键无响应，点击无法穿透该图片。

App version:2.4.0-Beta
Platform: Windows Desktop

**Comment by aNewContent** [comment]
https://github.com/aNewContent/puremvcstudy/blob/master/Snipaste_2020-11-13_10-12-10.png
附上截图。
另外，这张截图无法拖动，意思不能用鼠标对改截图做任何操作。不影响这软件的后续使用。

**Comment by chenrylee** [comment]
现在都2.5.40了。。。怎么还停留在2.4呢。。。
关于这个问题，见： #980

**Comment by aNewContent** [comment]
https://github.com/aNewContent/puremvcstudy/blob/master/Snipaste_2020-11-13_10-36-15.png
设置了全局鼠标穿透，关闭穿透后现在成这样子啦。excel底—snipaste截图—右击excel展示。
所以我现在如何才能恢复正常使用呢。怎么清理掉这个截图。一定要更新么。

**Comment by fendaabc** [comment]
我可能遇到的和你相似的问题,就是没开鼠标穿透,但有一张贴图始终无法选中和操作,只要一按F1它就会自己置顶显示,然后只能用隐藏来暂时屏蔽,我的解决办法是打开snipaste的首选项,打开配置文件存储位置的文件夹,然后打开history文件夹,在下面的几个分组里找哪个里面有你无法操作的图片,删除了就好了,,,,,,,,你可以试试有用吗

**Comment by aNewContent** [comment]
我重启电脑，这个图还在。然后我重新解压缩了安装包，重装完美解决。history文件夹删除感觉也可行。

**Comment by liulex** [comment]
#1565

**Comment by iwanghc** [comment]
找到这个文件下面 “\history\G1LCQ6“ 把那张图片删了就好了
