### ISSUE TITLE
[macOS] Big Sur 菜单栏图标过大

### ISSUE THREAD

**Issue by idiotWu** [Snipaste/feedback#1716]
Big Sur 上菜单栏图标过大，导致在第二屏幕上被折叠：

主屏幕：
![image](https://user-images.githubusercontent.com/6022672/99036574-43ba4d00-25c5-11eb-9cc1-22defffd4a67.png)
第二屏幕：
![image](https://user-images.githubusercontent.com/6022672/99036584-49179780-25c5-11eb-9a07-9df83327d937.png)

App version: 2.5.2-Beta
Platform: macOS 11.0.1

**Comment by sbfkcel** [comment]
![Uploading image.png…]()
同样的问题。图标过大。不协调

**Comment by chenrylee** [comment]
这个不只是主屏幕，是Active screen和inactive screen。
如果第二屏幕active的话，主屏幕的图标也会挤成这种样子。

**Comment by tingjiangcao** [comment]
![image](https://user-images.githubusercontent.com/51285674/99189688-5ab39780-279d-11eb-99bd-4529b7b5b4f0.png)

**Comment by tingjiangcao** [comment]
我也觉得有点不协调，顺便说一下，这个首选项好像也有点小问题

**Comment by zhangatle** [comment]
相对其它图标，有点大，不整齐

**Comment by liulex** [comment]
Big Sur 相关的问题正在解决了，因为还需要同时兼顾旧系统，所以需要花点时间。
