### ISSUE TITLE
OCR

### ISSUE THREAD

**Issue by imyyq-star** [Snipaste/feedback#1718]
目的：复制电脑软件上的文字
希望：有时候需要复制某软件的英文，拿去翻译软件中翻译，但是该软件不支持复制软件上的文字，所以希望通过截图软件截取指定区域后自动提取截图中的文字，功能就好像是http://hanxinyumeng.cn/中的。

**Comment by chenrylee** [comment]
#188

**Comment by Geeyun-JY3** [comment]
看置顶：https://github.com/Snipaste/feedback/issues/282#issuecomment-268242387
