### ISSUE TITLE
macos big sur 无法正常截图，只能截图桌面

### ISSUE THREAD

**Issue by wcc526** [Snipaste/feedback#1719]
macos big sur 无法正常截图，只能截图桌面

**Comment by chenrylee** [comment]
检查安全和隐私设置中是否允许Snipaste录制桌面。
某些加密文件也不允许截图。

**Comment by wcc526** [comment]
更新到最新版后可以了

**Comment by BestVish** [comment]
> 更新到最新版后可以了

我就是更新的最新版的，但是不行呢

**Comment by liulex** [comment]
到系统设置里面给录屏权限，如果已经给了就先删掉。
