### ISSUE TITLE
Big Sur无法检测窗口元素

### ISSUE THREAD

**Issue by shanehou** [Snipaste/feedback#1721]
2.5.2-Beta，授予了辅助功能权限（在列表里没找到，手工添加的），但是仍然无法检测窗口元素

**Comment by liulex** [comment]
这个跟系统没关系，我测试是没问题的。无法检测应该是有其他（透明）窗口阻挡了。

**Comment by septs** [comment]
Duplicate of #1200

**Comment by liulex** [comment]
下个版本会改善窗口检测与其他 app 的兼容性问题。
