### ISSUE TITLE
Remeber the color per drawing tool

### ISSUE THREAD

**Issue by koppor** [Snipaste/feedback#1722]
My usual workflow is to draw highlight elements and to draw arrows between them.

Example:

![image](https://user-images.githubusercontent.com/1366654/99361770-e834db80-28b2-11eb-83a7-85d7e0c3552b.png)

For the box, I'd like to have a transparent yellow (alpha=150), but for the arrow, I'd like to have blue without any transparency (alpha=255). In the current workflow, I always have to reconfigure the color after each tool change.

It would be very nice if the color would be stored per drawing element.

Alternatively, there should be a configuration option to enable (and disable) this behavior.

**Comment by liulex** [comment]
The colors are actually independent for each shape, except for the alpha:
![image](https://user-images.githubusercontent.com/2010459/99399659-ed307400-2920-11eb-8dd3-30ca8ca19640.png)

The alpha are shared between shapes for historical reasons. However, judging from what the option says, the alpha should also be separate for each shape. I will change the behavior in the next version.

**Comment by koppor** [comment]
Note that this is a premium feature. Three free version is as follows:

![image](https://user-images.githubusercontent.com/1366654/100097738-43d80980-2e5d-11eb-8117-f37b3b2ea313.png)

**Comment by liulex** [comment]
Implemented in v2.5.5.

Yes, I know the feature is premium only. Since v2.0, almost all new features are available to the PRO version only, but I remember you have activated PRO as donator?
