### ISSUE TITLE
无法通过windows搜索， 或者是utools 打开软件

### ISSUE THREAD

**Issue by chaochao214** [Snipaste/feedback#1725]
软件版本：2.5.2-beta
运行平： Windows 桌面 /
 windows下：
![image](https://user-images.githubusercontent.com/30425369/99619791-28d15800-2a5f-11eb-94f5-eea543f3e4d4.png)
 
utools 下：
 
![image](https://user-images.githubusercontent.com/30425369/99619931-75b52e80-2a5f-11eb-9536-ef5315c550f0.png)

 但其他软件可以正常打开： 
 
![image](https://user-images.githubusercontent.com/30425369/99619972-85347780-2a5f-11eb-9525-41b8a7e20b04.png)

**Comment by chenrylee** [comment]
这是你的Windows索引问题，和Snipaste没关系。

**Comment by liulex** [comment]
桌面版是绿色软件，相关问题请自行解决。
