### ISSUE TITLE
win7打开snipaste一闪而过

### ISSUE THREAD

**Issue by Nearby36** [Snipaste/feedback#1726]
win7 64位，之前官网下载的win 64位的版本，用了一年多没出现什么问题。最近打开，想F1截图，一直没反应，鼠标放右下角snipaste图标上，图标就消失。（或者鼠标不放图标，也消失）
重新以管理员身份点击运行，依然是这样的情况。
电脑重启过还是这样，官网上想按文档说明下载个32位的试试，链接失效，求助！

**Comment by liulex** [comment]
链接已修复。
我虚拟机 Win7 64 位测试没有问题。
请问软件目录下的 crashes 文件夹内是否有文件呢？

**Comment by Nearby36** [comment]
@liulex 谢谢答复，我刚下了32 和64位都运行了，也是第一次有图标能截图，但过几秒消失，生成的crashes文件夹下没有文件，是空的，我也不知道是我电脑自动删除了还是什么原因？

**Comment by liulex** [comment]
crashes 下没有文件说明不是 Snipsate 自己崩了，可能是被安全软件之类的杀掉了。

**Comment by Nearby36** [comment]
再反馈下：下载了官网更新的最新版，win7 + Snipaste-2.3.5-Beta-x64，用了几天没有问题，不过crashes下依然没文件（应该是被强制安装的安全软件给清除了）
