### ISSUE TITLE
增加自动识别图片中文字的功能

### ISSUE THREAD

**Issue by zqqkl** [Snipaste/feedback#1734]
截取图片后，提供文字识别功能，可以获取文字

![image](https://user-images.githubusercontent.com/75346262/100817768-a778bd00-3483-11eb-93fa-2d745814470c.png)
![image](https://user-images.githubusercontent.com/75346262/100817793-b495ac00-3483-11eb-9d73-ea42ceeaf4ce.png)

**Comment by Geeyun-JY3** [comment]
请看置顶：https://github.com/Snipaste/feedback/issues/282#issuecomment-268242387
另外重复的 issue 也非常多：#188，#1718
https://github.com/Snipaste/feedback/issues?q=ocr

**Comment by septs** [comment]
Duplicate of #188
