### ISSUE TITLE
切换语言后GUI重绘有小问题

### ISSUE THREAD

**Issue by chaohershi** [Snipaste/feedback#1736]
贴图 -> 转换 tab 上的文字会在另两个 tab 中显现。
![GIF 12-3-2020 12-06-46 AM](https://user-images.githubusercontent.com/22566267/100966683-7e940e80-34fb-11eb-80b2-7351f4a4d5b8.gif)

其他 tab 正常，Version 2.5.5 (2020.11.28)

**Comment by liulex** [comment]
谢谢反馈！
