### ISSUE TITLE
missing Version number in macOS 2.5.5-Beta2

### ISSUE THREAD

**Issue by suschizu** [Snipaste/feedback#1738]
Hello! I think you forgot to update the version number in the latest Beta release for 2.5.5 (just a placeholder instead of a version number)
Platform: macOS

![image](https://user-images.githubusercontent.com/16004333/101152774-d4fc6c80-3623-11eb-9896-d8f4425fac63.png)

**Comment by liulex** [comment]
Thanks for reporting. I will fix it soon.
