### ISSUE TITLE
使用一台电脑远程另一台电脑截图另存为和插入文本时无法输入C，个人觉得可能和取色的C快捷键有关

### ISSUE THREAD

**Issue by tianyulouzhu** [Snipaste/feedback#1739]
环境：Win7 64位下使用Snipaste 32位版
问题：通过VNC或Teamviewer远程另一台电脑将截图另存为或插入文本时无法输入“C”，C按键如同失灵一样
           取色器快捷键是C，所以怀疑是远程时存在冲突导致

**Comment by liulex** [comment]
#1397

**Comment by tianyulouzhu** [comment]
> #1397

感谢，问题解决了 ^_^
