### ISSUE TITLE
打开snipaste首选项，点击右上角关闭按钮关闭不了窗口

### ISSUE THREAD

**Issue by freemagnet** [Snipaste/feedback#1740]
snipaste 32位 V2.5.2-Beta(2020.10.18)版本在WINDOWS 7 旗舰版 32位系统 SP1，在打开软件首选项后，点击右上角关闭按钮，点击没有反应，关闭不了首选项窗口

**Comment by liulex** [comment]
这个问题收到过几个 Win7 用户的反馈，但应该跟系统有关，我虚拟机就无法重现。
