### ISSUE TITLE
标注工具的溢出菜单抖动

### ISSUE THREAD

**Issue by wenmin92** [Snipaste/feedback#1745]
软件版本：2.5.6
运行平台：微软商店

移入移出时，溢出菜单的位置会变化，产生抖动效果，如下所示：
![demo](https://user-images.githubusercontent.com/6901815/102040972-303f1380-3e09-11eb-8ad3-350f4dbb8ebe.gif)

**Comment by liulex** [comment]
是说那三个点的图标？明显就是有意这么设计的……

**Comment by wenmin92** [comment]
> 是说那三个点的图标？明显就是有意这么设计的……

如果是故意设计，那么我强烈反对这么做，看着十分别扭。此外，希望不要鼠标移入就触发，点击触发比较好。

**Comment by liulex** [comment]
只能说我个人更偏向现在这种交互，没办法让所有人满意的。
