### ISSUE TITLE
工具栏提示闪烁

### ISSUE THREAD

**Issue by wenmin92** [Snipaste/feedback#1746]
软件版本：2.5.6
运行平台：微软商店

鼠标移入工具栏时, 提示短时间重复闪现, 如下所示:
![test](https://user-images.githubusercontent.com/6901815/102045402-ef003100-3e13-11eb-9ac8-97ecfc0bb87c.gif)

**Comment by liulex** [comment]
没看出这样有什么问题。。

**Comment by wenmin92** [comment]
> 没看出这样有什么问题。。

可能是码率不够，gif图不怎么明显。但看最后“撤销”和“重做”还是能看出来的。

**Comment by chenrylee** [comment]
我看到了鼠标指针的移动。。。此“bug”换鼠标可解😅
我试了Windows和Mac，鼠标放过去完全没你说的问题。

**Comment by liulex** [comment]
明白你意思了。。这个像是 Qt 的问题，但我这里没有重现，我觉得无关紧要吧。
