### ISSUE TITLE
更新完成之后，复制代码再贴图，没有高亮代码了

### ISSUE THREAD

**Issue by ChangeHow** [Snipaste/feedback#1747]
## 复现步骤
1. VSCode 中复制任意数量的代码
2. 在桌面点击F3贴图

## 预期效果&实际效果
在原先版本中，贴图是带有代码高亮的，现在没有了

## AppVersion
MacOS BigSur 11.1beta
Snipaste v2.5.6

**Comment by liulex** [comment]
"原先版本"，指的是 Snipaste 更新了还是 VSCode 更新了呢？

**Comment by liulex** [comment]
VSCode 1.53.2 + Snipaste 2.5.6 没有问题。
