### ISSUE TITLE
请求添加文字识别功能

### ISSUE THREAD

**Issue by xiufu666** [Snipaste/feedback#1749]
可以在截图完成添加一个按钮用于文字识别
设置里最好可以自己设置文字识别的API接口

**Comment by Geeyun-JY3** [comment]
请看置顶：https://github.com/Snipaste/feedback/issues/282#issuecomment-268242387
另外重复的 issue 也非常多：#188，#1718，#1734
https://github.com/Snipaste/feedback/issues?q=ocr

**Comment by septs** [comment]
Duplicate of #188
