### ISSUE TITLE
Mac更到最新系统后，截图直接跳回桌面。

### ISSUE THREAD

**Issue by GarboSun** [Snipaste/feedback#1750]
1:
Mac系统更新到11.1后，按fn+F1后，
明明要截图当前页面，
https://tva1.sinaimg.cn/large/0081Kckwly1glom0pzpbpj31c00u0kev.jpg
结果直接跳回到桌面
https://tva1.sinaimg.cn/large/0081Kckwly1glom1quzjzj31c00u0x6r.jpg
当前页面根本截不到。
请问是更新系统的原因么，还是别的，怎么操作一下。

2:
另外，点按菜单选项，点一个菜单栏上的字白一个。（这个顺便反馈的）
https://tva1.sinaimg.cn/large/0081Kckwly1glom3v9z2dj30zo0u0wi0.jpg

**Comment by liulex** [comment]
该更新 Snipaste 版本了。

**Comment by GarboSun** [comment]
> 该更新 Snipaste 版本了。

不好意思。
https://tva1.sinaimg.cn/large/0081Kckwly1gm2tfjgitvj30xc0nsq4m.jpg
