### ISSUE TITLE
建议增加更加方便的一步

### ISSUE THREAD

**Issue by futrueface** [Snipaste/feedback#1752]
用户在选定欲截图区域后，大概率都是要选择区域标注画框，建议自动选择方框，省了用户先选定区域，再去选择方框

**Comment by liulex** [comment]
![image](https://user-images.githubusercontent.com/2010459/102499618-5e954b00-40b6-11eb-815f-67a39e894af0.png)

**Comment by futrueface** [comment]
你好，根据你 的截图，我这里的版本好像跟你的不一样哦
我的是：



按照你的路径“截屏--&gt;行为”，我这里的页面是这样的：







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Snipaste/feedback"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 晚上10:23
收件人:&nbsp;"Snipaste/feedback"<feedback@noreply.github.com&gt;;
抄送:&nbsp;"滒滒"<381781732@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Snipaste/feedback] 建议增加更加方便的一步 (#1752)

**Comment by liulex** [comment]
@futrueface 需要专业版。
