### ISSUE TITLE
MAC版本关于增强版托盘菜单问题

### ISSUE THREAD

**Issue by 35598253** [Snipaste/feedback#1753]
Mac 有按住option点击菜单显示详细信息功能，比如option+Wifi，展示更多信息，这个和增强版托盘菜单功能非常像，完全可以合并啊，点击option+菜单 显示的是增强版菜单，没必要单独设置一个菜单的；

软件版本：2.5.6
运行平台：macOS

**Comment by liulex** [comment]
好的，下个版本会加入。

**Comment by Geeyun-JY3** [comment]
建议往增强版托盘菜单的 tooltip 加入相关描述。
