### ISSUE TITLE
【疑问】在贴图上点击右键进行裁剪时快捷键冲突

### ISSUE THREAD

**Issue by Caodaping** [Snipaste/feedback#1756]
我正在使用鼠标手势软件，按住右键滑动鼠标是绘制手势。
而Snipaste在贴图上点击右键是选择裁剪的区域。由于手势软件是全局软件，优先级高，导致Snipaste的贴图上执行操作无效。

请问:是否可以自定义Snipaste的快捷键，比如按住辅助键的情况下用右键进行裁剪，我没找到这个功能，现在是否有这个功能呢？谢谢！

**Comment by liulex** [comment]
将 Snipaste 加入鼠标手势软件的黑名单里。

**Comment by Caodaping** [comment]
非常感谢，问题已经解决！！
