### ISSUE TITLE
多显示器拓展竖屏显示导致白板模式无法用空格调出画图工具栏

### ISSUE THREAD

**Issue by wakaka6** [Snipaste/feedback#1758]
当我进入白板模式后，无法用空格调出画图工具栏，按空格没反应

我的快捷键配置：
![image](https://user-images.githubusercontent.com/48764488/103135656-b1918280-46f4-11eb-9660-0beffb3f42d8.png)

软件版本：2.5.6（2020.12.10）x64 Pro版本
运行平台：微软商店
操作系统：windows10 1909专业版 x64

**Comment by liulex** [comment]
我测试是没问题的。
那非白板模式下，空格键有效果吗？

**Comment by wakaka6** [comment]
有 正常截图可以

**Comment by wakaka6** [comment]
我好像找到问题所在了，我是双屏显示，我第二个屏幕是竖屏显示
![image](https://user-images.githubusercontent.com/48764488/103307622-7fad5280-4a4b-11eb-9b4f-05683dc99a94.png)
当我单屏幕的时候就可以调出工具栏，但是我开启双屏幕并且第二个屏幕是竖屏的时候(横屏幕可以正常调出)就调不出工具栏了
我的竖屏显示器设置
![image](https://user-images.githubusercontent.com/48764488/103308046-7cff2d00-4a4c-11eb-8b7e-69535df07704.png)
这应该是竖屏定位到屏幕外导致的

**Comment by liulex** [comment]
谢谢描述，确实会出现这种情况，会在下一版本修复。
