### ISSUE TITLE
图片复制到剪贴板后，其他软件从剪贴板获取该图片失败

### ISSUE THREAD

**Issue by zhongfly** [Snipaste/feedback#1764]
软件版本：2.5.6
运行平台：微软商店

# 问题说明：
## 背景介绍：
[img2latex-mathpix](https://github.com/blaisewang/img2latex-mathpix) 可以将剪贴板中的图片进行公式识别
## 复现步骤
1. 打开`img2latex-mathpix`软件，不需要设置，因为仅测试能否成功读取到Snipaste复制到剪贴板的图片
2. 使用Snipaste任意截图，复制到剪贴板
3. 切换到`img2latex-mathpix`软件中，按下 空格 键读取剪贴板中的截图，理应出现刚才的截图，但无截图出现。

## 对比
使用win10 自带截图 或 shareX 截图工具 复制到剪贴板后，`img2latex-mathpix`软件均可正常读取截图，参考 https://github.com/blaisewang/img2latex-mathpix/issues/96 中后面的讨论，qq截图以及Lightshot都与该软件配合无问题。故怀疑是由于Snipaste复制到剪贴板的问题

**Comment by liulex** [comment]
Snipaste 有跟剪贴板相关的选项：
![image](https://user-images.githubusercontent.com/2010459/103479621-ed6dcb80-4e09-11eb-8bc8-c939dc1e7494.png)

如果调整这些选项还无法解决，还请提供可供测试使用的 API Key. (<snipaste.app@gmail.com>)

**Comment by zhongfly** [comment]
已测试过勾选或不勾选“以……格式复制图片”，均无效。
已发送与issue同名的邮件，包含可供测试使用API Key

**Comment by amefs** [comment]
勾选或不勾选 "同时复制为文件" 也不能解决该问题

**Comment by liulex** [comment]
@zhongfly 谢谢！
测试了下，我认为这是 `img2latex-mathpix` 使用 JavaFX 读取剪贴板图像导致的问题。
除了从 Snipaste 复制的图片会显示成空白，从系统自带的画图工具、Word 以及 MassiGra、Telegram 等软件复制的图片都是空白的。
这里也描述了同样的情况：https://stackoverflow.com/questions/48932575/getting-image-from-clipboard-awt-vs-fx

**Comment by zhongfly** [comment]
> @zhongfly 谢谢！
> 测试了下，我认为这是 `img2latex-mathpix` 使用 JavaFX 读取剪贴板图像导致的问题。
> 除了从 Snipaste 复制的图片会显示成空白，从系统自带的画图工具、Word 以及 MassiGra、Telegram 等软件复制的图片都是空白的。
> 这里也描述了同样的情况：https://stackoverflow.com/questions/48932575/getting-image-from-clipboard-awt-vs-fx

谢谢您的帮助
