### ISSUE TITLE
请问是否有便携版本的专业版

### ISSUE THREAD

**Issue by soarliny** [Snipaste/feedback#1765]
公司的电脑锁定了微软商店，不能安装专业版，请问是否有便携版本的专业版可以提供，已在荔枝数码购买了专业版，我的邮箱是：soarlin@163.com，期待你的回复。

**Comment by liulex** [comment]
抱歉，目前没有桌面版，而且商店版的授权跟桌面版的授权是独立的。
Snipaste [网站](https://docs.snipaste.com/zh-cn/pro)以及数码荔枝的页面应该都说明了现在的专业版只能用于微软商店。

**Comment by soarliny** [comment]
好的，非常感谢你的回复。发自我的华为手机-------- 原始邮件 --------发件人： Le Liu <notifications@github.com>日期： 2021年1月4日周一 23:26收件人： Snipaste/feedback <feedback@noreply.github.com>抄送： soarliny <soarlin@163.com>, Author <author@noreply.github.com>主    题： Re: [Snipaste/feedback] 请问是否有便携版本的专业版 (#1765)

抱歉，目前没有桌面版，而且商店版的授权跟桌面版的授权是独立的。

Snipaste 网站以及数码荔枝的页面应该都说明了现在的专业版只能用于微软商店。

**Comment by septs** [comment]
Duplicate of #1162
