### ISSUE TITLE
ARM 支持

### ISSUE THREAD

**Issue by aimuch** [Snipaste/feedback#1766]
Macbook ARM 版出了有一段时间了, 后续是否会支持呢?

**Comment by liulex** [comment]
https://bugreports.qt.io/browse/QTBUG-85279

**Comment by aimuch** [comment]
> https://bugreports.qt.io/browse/QTBUG-85279

收到

**Comment by septs** [comment]
https://bugreports.qt.io/browse/QTBUG-85820

Windows 10 and ARM64 支持应与 macOS on Apple Silicon 同理

@TGSAN 请耐心等待上游完成支持

**Comment by aimuch** [comment]
有进展吗？:smiley:

**Comment by septs** [comment]
> 有进展吗？😃

上游不积极，别想太多

**Comment by yyfn** [comment]
qt出预览版了~
https://www.qt.io/blog/qt-on-apple-silicon

https://www.ithome.com/0/558/621.htm

**Comment by aimuch** [comment]
👀

**Comment by liulex** [comment]
2.6 Beta 版已经支持 Mac M1.

**Comment by septs** [comment]
@liulex 对于 Windows ARM64 支持
建议另外建立新的 issue

**Comment by liulex** [comment]
@septs https://github.com/Snipaste/feedback/issues/1588

**Comment by Mryuelaiyuehao** [comment]
在windows上用习惯了这个截图工具，mac上等了好久，终于适配M1了😊
