### ISSUE TITLE
F3贴图经常自动消失，消失后有时又会自动出来

### ISSUE THREAD

**Issue by kfuudotcn** [Snipaste/feedback#1767]
两个电脑都是，都是win10系统，高级版的。 正在操作别的程序呢，贴图突然就消失了，随便再贴个图，消失的贴图又一起出来了。
有时候不管他，消失的贴图又会自动出来了。这个问题持续很久了，之前也提过这个问题

**Comment by liulex** [comment]
贴图全部消失/显示只有 全局快捷键/触发角 这两种触发方式，请到 首选项 - 控制 检查相关设置。

**Comment by kfuudotcn** [comment]
感谢回复，似乎真的是因为这个导致的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Snipaste/feedback"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月8日(星期五) 晚上11:34
收件人:&nbsp;"Snipaste/feedback"<feedback@noreply.github.com&gt;;
抄送:&nbsp;"花晨月夕"<59005022@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Snipaste/feedback] F3贴图经常自动消失，消失后有时又会自动出来 (#1767)





 
贴图全部消失/显示只有 全局快捷键/触发角 这两种触发方式，请到 首选项 - 控制 检查相关设置。
