### ISSUE TITLE
Windows 4k屏建议参考Mac版QQ截图工具提供简易设置标清和高清两种选项

### ISSUE THREAD

**Issue by rynetang** [Snipaste/feedback#1768]
我使用Mac也使用Windows（27寸4k屏200%缩放），屏幕截图总是画布尺寸比较大的，不仅文件体积大、对方在96px屏幕上看也显得十分巨大。
Mac截图工具通常设置有“截屏图片质量”，有2个选项
- 标准（1x），即转化为96px
- 高清（2x），其实即不做缩小处理

希望Snipaste能够增加这种简单的易理解的选项，这个功能在Mac版本各类截图工具中普遍存在，在Windows版本中基本没有……即使有也只能使用画布缩放功能，每次截图都要现算现调，不能保存为默认值。

![5a79f05153a54920](https://user-images.githubusercontent.com/19310764/103764490-855ff500-5056-11eb-9a71-076725b36f3e.png)

**Comment by liulex** [comment]
我再考虑下……

**Comment by septs** [comment]
Duplicate of #357
