### ISSUE TITLE
关于win10下截图保存时待选文字框不显示的问题

### ISSUE THREAD

**Issue by Ziffer-yan** [Snipaste/feedback#1770]
我截图保存文件的时候，在文件的明明栏中打出中文的输入法的时候，不显示文字的待选框（使用的是微软的新版输入法），但是切换回微软的旧版输入法之后就能够成功显示中文文字的待选框。经测试，微软的日语输入法的文字待选框是可以成功显示的。因为是截图保存的界面所以没有截图作为说明（汗）。不知道是新版微软输入法的问题，还是snipaste的兼容性的问题，所以submit a issue记录一下。

**Comment by liulex** [comment]
不知道你说的新版是具体什么办法，我这里没问题的。
这种问题你在其他软件/截图软件的保存对话框测试一下，就可以知道是哪边的问题了。
