### ISSUE TITLE
[Feature Request] Set Snipaste theme colour to Windows 10 theme colour

### ISSUE THREAD

**Issue by Glodigit** [Snipaste/feedback#1771]
To make snipaste blend in with the Windows 10 UI, I think it would be a great idea to have a checkbox beside "Theme color:" to get the option to use the Windows 10 colour instead of a fixed user selected colour. This is useful for those like me that change the background, and subsequently the windows theme colour, very often.

**Comment by liulex** [comment]
Good idea! I will implement it in the next release.
