### ISSUE TITLE
建议新功能

### ISSUE THREAD

**Issue by ApolloRioo** [Snipaste/feedback#1772]
<!--
每次软件窗口图片各种取色，都要打开QQ截图，
 1 按住 Ctrl 键，光标处会显示光标位置对应RGB的6位十六进制颜色码；（如：C0EAF7）
 2 松开 Ctrl 键，光标处会显示光标位置对应RGB的3串RGB颜色值。（如：192,234,247）
虽然是偶尔很久才用的到的功能，这种受众吧，而又不经常使用QQ，而贵软件长期后台替代浏览器截图的用户，
心血来潮的上来建议这个小功能。

**Comment by ApolloRioo** [comment]
截图软件用户，取色却要打开一年都用不了一次的QQ截图。
② 按住 Ctrl 键，光标处会显示光标位置对应RGB的6位十六进制颜色码；（如：C0EAF7）

③ 松开 Ctrl 键，光标处会显示光标位置对应RGB的3串RGB颜色值。（如：192,234,247）
希望加入这个小功能

**Comment by LuohuaRain** [comment]
直接截图的时候不是对应有取色吗？

**Comment by Greesea** [comment]
![Snipaste_2021-01-11_09-56-49](https://user-images.githubusercontent.com/9460513/104141787-6fa25500-53f3-11eb-9ea6-8cb923800502.png)

**Comment by Geeyun-JY3** [comment]
直接截图就有这功能。按 <kbd>Shift</kbd> 切换 RGB/HEX
![gif](https://user-images.githubusercontent.com/49396421/104403905-87650f00-5594-11eb-853c-a264a8a93193.gif)

**Comment by liulex** [comment]
取色器上这么大个字。。按 Shift 切换啊！
