### ISSUE TITLE
建议保存图片到本地的时候，不要独占系统，会导致无法使用listary软件快捷选择保存路径

### ISSUE THREAD

**Issue by talkingbeast** [Snipaste/feedback#1776]
F1截图保存文件snipaste会强制用户在文件保存窗口选择路径，使用非常不变
建议保存图片到本地的时候，不要独占系统，否则会导致无法使用listary软件快捷选择保存路径，建议使用系统自带保存对话框，这样可以进行其他操作

**Comment by liulex** [comment]
![image](https://user-images.githubusercontent.com/2010459/104619069-6d2c4d80-56c8-11eb-8530-8aaa998473b0.png)
需要专业版。
