### ISSUE TITLE
请提供一个非微软商店的专业版付费渠道

### ISSUE THREAD

**Issue by valuex** [Snipaste/feedback#1779]
请提供一个非微软商店的专业版付费渠道
* 需求来源：公司电脑，不能访问微软商店

**Comment by Geeyun-JY3** [comment]
见 #1162 

> 此外，专业版不久也会提供桌面版及 Steam 版，它们的区别是：
> - 微软商店版是与你的微软账号绑定
> - 桌面版限制激活设备数，但可以在不同平台的设备上激活
> - Steam 版（待定）
>
> 请注意它们是相互独立的，并不互通，请选择适合自己的版本。
>
> 另，Snipaste 2.x 只对个人用户免费，公司使用请购买专业版或使用 Snipaste 1.x。

https://docs.snipaste.com/zh-cn/pro

**Comment by liulex** [comment]
努力中～

**Comment by septs** [comment]
Duplicate of #1162

**Comment by Eduprsw** [comment]
2022年7月28日 插眼
