### ISSUE TITLE
请求增加：类似Typora自定义命令上传到云端，返回Markdown链接

### ISSUE THREAD

**Issue by leonyff** [Snipaste/feedback#1781]
**请求增加类似Typora可以自定义上传截图到云端，返回图片Markdown链接！**

![image](https://user-images.githubusercontent.com/38803732/104988244-7f332680-5a0f-11eb-9c31-2e4035d4633d.png)

> 我在使用Obsidian笔记软件记录记笔记，上传图片不是很方便，如果截图可以自定义上传的功能，截图后使用快捷键自动上传到云端，就可以直接再Obsidian中编辑软件，不用来回切换！

**Comment by septs** [comment]
Duplicate of #60
