### ISSUE TITLE
add another arrow style 

### ISSUE THREAD

**Issue by wolvesong** [Snipaste/feedback#1782]
add another arrow style  ,like this I─I    ,it is very helpful when i explain a goods height or wide or length .

**Comment by liulex** [comment]
OK. I will think about it.

**Comment by liulex** [comment]
You can now use it in Snipaste 2.6 PRO:
![image](https://user-images.githubusercontent.com/2010459/127765624-9644d9d0-cf0d-4c46-b1ee-e9622510d086.png)
