### ISSUE TITLE
多显示器上下布局只能在一个屏幕截图

### ISSUE THREAD

**Issue by Tambura** [Snipaste/feedback#1783]
采用左右布局两个显示器时，正常。
采用上下布局两个显示器时，只能在主显示器内截图。鼠标移动到另一个显示器，截图框仍然停留在主显示器。如果想截图，只好先把副显示器的窗口移动到主显示器，然后再截。

软件版本：1.16.2
运行平台： Windows 桌面

**Comment by Tambura** [comment]
应该是windows的bug。在任务栏设置里，设置了“在所有显示器上显示任务栏”之后，这个问题消失。

**Comment by liulex** [comment]
我觉得你应该先升级下 Snipaste...
