### ISSUE TITLE
您好，我使用的是Microsoft Store的版本，它最新版本启动时直接报出参数错误

### ISSUE THREAD

**Issue by StormAlexZhang** [Snipaste/feedback#1784]
App version:
Platform: Microsoft Store
参数错误如下：
C:\Program Files\WindowsApps\45479liulios.17062D84F7C46_2.5.60.0_×64_p7pnf6h..× ×C\Program Files\WindowsApps\45479liulios.17062D84F7C46_2.5.60.0_×64_p7pnf6..\Snipaste.exe 参数错误。

**Comment by liulex** [comment]
这个是微软商店方面的问题，只能网上搜索一下了。

**Comment by septs** [comment]
Duplicate of #1391

请合并至 #1391 继续讨论
