### ISSUE TITLE
1.x版本，是不是针对个人和企业都是免费的

### ISSUE THREAD

**Issue by wpt191** [Snipaste/feedback#1787]

**Comment by Geeyun-JY3** [comment]
文档写得挺清楚的：https://docs.snipaste.com/zh-cn/pro?id=专业版
> Snipaste 2.x 只对个人用户免费，公司使用请购买专业版或使用 Snipaste 1.x

**Comment by liulex** [comment]
1.x 个人和公司使用都免费，但不能未经授权与其他软件绑定后进行二次分发。
