### ISSUE TITLE
什么时候支持滚动截图

### ISSUE THREAD

**Issue by jymr92** [Snipaste/feedback#1788]
1选择一块区域，
2点击滚改截图
2拖动横向或者纵向滚动条
3点击结束
4保存为一个图片文件

**Comment by jymr92** [comment]
重点是，不能限制某个软件。是任意软件都可以

**Comment by Brainbg** [comment]
我也需要这个功能才想上issues @

**Comment by ymyz1229** [comment]
+1，如果有这个功能的话，其他截图工具都可以卸载了

**Comment by hgaogao** [comment]
加一，有时候截图网页的时候每次都要截好多张很麻烦

**Comment by septs** [comment]
Duplicate of #19
