### ISSUE TITLE
Feature request - Output _ Clipboard - Resize image scale in percent

### ISSUE THREAD

**Issue by norman003** [Snipaste/feedback#1789]
Feature request?
I need to paste in Microsoft Word with resize image scaling.

Propose request?
1. The scale will affect the width and height of the image
2. I propose the percent could configure in Output - Clipboard  with option Resize %.
3. Then maybe could configure in option output of the snip editor.

Why request?
I need it because I do tutorials in Microsoft Word then I have resize image scaling in two steps.

**Comment by liulex** [comment]
You can scale the image by wheel scroll after you pin it to the screen. Custom % is available for the PRO version:
![image](https://user-images.githubusercontent.com/2010459/106780797-52c01100-6683-11eb-9270-856316baab73.png)

**Comment by norman003** [comment]
You're right, but there would be the possibility of direct copying at a pre-configured scale.
