### ISSUE TITLE
对贴图进行标注后，贴图粘贴会出现奇怪边框

### ISSUE THREAD

**Issue by ousugo** [Snipaste/feedback#1793]
直接截图后不进行标注，粘贴一切正常：

![image](https://user-images.githubusercontent.com/43401755/106777238-c52ef200-667f-11eb-8558-79164b17c63d.png)

但在进行**任意标注**后，预览时正常，但复制后粘贴到其他地方，贴图就变成下面这样了，会带上莫名其妙的边框

![image](https://user-images.githubusercontent.com/43401755/106777281-cf50f080-667f-11eb-8761-c1b9078ea111.png)

软件版本：2.5.6
运行平台：微软商店

**Comment by liulex** [comment]
你是在贴图上进行标注和复制的吧。下图是带透明通道的图像，粘贴到部分程序会不支持。
你可以把这里勾上，这样就总是不带透明通道了：
![image](https://user-images.githubusercontent.com/2010459/106779692-353e7780-6682-11eb-8876-3b1a5ea62db1.png)

**Comment by ousugo** [comment]
非常感谢，勾上以后问题就解决了。我之前是粘贴到 Typora、Chrome(语雀、Github)都不行。

「你是在贴图上进行标注和复制的吧」，看到这句话回去看了下，发现自己原来从来没单独用过截图功能，都是直接快捷键调用的「截屏并复制」。

**Comment by ousugo** [comment]
非常感谢，勾上以后问题就解决了。我之前是粘贴到 Typora、Chrome(语雀、Github)都不行。

「你是在贴图上进行标注和复制的吧」，看到这句话回去看了下，发现自己原来从来没d用过截图功能，直接都是快捷键调用的「截屏并复制」
