### ISSUE TITLE
内存占用巨大并且无法使用

### ISSUE THREAD

**Issue by UgOrange** [Snipaste/feedback#1794]
启动snipaste后，会不断占用内存，并且无响应
![捕获](https://user-images.githubusercontent.com/28263639/107191421-198ef480-6a27-11eb-909c-c19eba678224.PNG)
但是贴图数量会不断增加，我没有做什么修改，就会这样
![image](https://user-images.githubusercontent.com/28263639/107191607-5ce96300-6a27-11eb-99a1-b3d85ea31b67.png)

软件版本：2.5.1
运行平台：Windows 桌面

**Comment by liulex** [comment]
请打开 `%LOCALAPPDATA%\Packages\45479liulios.17062D84F7C46_p7pnf6hceqser\LocalState` 这个文件夹，删除 history 文件夹里面的 snip 子文件夹，然后将 history 文件夹打包后发送到 <snipaste.app@gmail.com>，我查一下怎么回事。
