### ISSUE TITLE
请求新功能：自定义压缩比例截图

### ISSUE THREAD

**Issue by kevin889988** [Snipaste/feedback#1795]

**Comment by Jieqi1** [comment]
![image](https://user-images.githubusercontent.com/46947698/107868563-411b0c80-6ec0-11eb-91a4-a9001604d949.png)
不知道这个行不行

**Comment by Jieqi1** [comment]
> _No description provided._

![image](https://user-images.githubusercontent.com/46947698/107868578-69a30680-6ec0-11eb-9ff2-f65727b5c7f1.png)
不知道这个行不行 : )

**Comment by kevin889988** [comment]
不行了，我使用了F1快捷截图，然后图像质量尝试了0,50,80，但是截图（复制+粘贴）和截图（保存下载）都是原本的文件大小，没有丝毫变化。


如果可以，还是希望你们可以添加这个功能的呀。会非常多人需要高清，另外反向的压缩的人，也应该有相当一部分吧。


添加功能呗~






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Snipaste/feedback"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月14日(星期天) 中午12:31
收件人:&nbsp;"Snipaste/feedback"<feedback@noreply.github.com&gt;;
抄送:&nbsp;"~.~"<280840779@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Snipaste/feedback] 请求新功能：自定义压缩比例截图 (#1795)





  
No description provided.
  

 不知道这个行不行 : )

**Comment by stevenzhu25** [comment]
@Jieqi1 这个设置的是文件， 不是剪贴板啊…
我觉得他说的是截图直接Ctrl + V粘到Excel里面

**Comment by septs** [comment]
Duplicate of #201
