### ISSUE TITLE
Truncate long %title% in filename

### ISSUE THREAD

**Issue by rudolphos** [Snipaste/feedback#1796]
Sometimes when saving a screenshot with `%title%` in the file name it generates too long filenames (which can't be saved) and I have to manually reduce the length of it. Would be better if there was a limit to how long a file name can be and it would automatically truncate it to ~130 characters and add something like [...] at the end.

**Comment by liulex** [comment]
It has been documented in "Naming rules":

> %title%  - The title of the active window before snipping
> %title:50%  - Same as the above, but the number of characters is limited to 50
