### ISSUE TITLE
贴图窗口增加边框选项

### ISSUE THREAD

**Issue by LuoDiKaiHua** [Snipaste/feedback#1798]
目前贴图窗口可以设置是否显示阴影，希望能增加设置窗口边框的功能，因为窗口阴影太难看了。。。🌹

**Comment by snsnsjsn** [comment]
我用sharex解决，你看看效果
![image](https://user-images.githubusercontent.com/11435527/113254973-d7cd4c80-92f9-11eb-858a-523954a350fd.png)

sharex 没有贴图功能和取色，以及记忆历史位置功能，我一般两者同时使用，sharex截图标注非常丰富

**Comment by Geeyun-JY3** [comment]
Duplicate of #1717
