### ISSUE TITLE
超级快捷键无法正常截图

### ISSUE THREAD

**Issue by ouligei6666** [Snipaste/feedback#1799]
超级快捷键,  无法正常截图,  截图自动停止, 最大只能截出123乘117的图片, 更多的时候只能出现截出1乘1截图的无效操作
超级快捷键win+鼠标左键, 更改快捷键依然出现问题, 卸载重装snipaste, 问题依旧

软件版本：pro版本
运行平台：微软商店

**Comment by liulex** [comment]
下个版本会改进超级截图，你也可以提供微软帐号邮箱到 <snipaste.app@gmail.com> 提前体验测试版。

**Comment by liulex** [comment]
2.6 版本应该不再会出现 1x1 大小的超级截图了。如有问题欢迎继续反馈。
