### ISSUE TITLE
使用Iris护眼程序时截图背景色严重偏暗

### ISSUE THREAD

**Issue by Sun-Pengcheng** [Snipaste/feedback#1800]
在 使用Iris时截图示意（肉眼所见没有这么暗）
![image](https://user-images.githubusercontent.com/62691819/108631902-3a375f80-74a7-11eb-9144-1d56a3893843.png)

附上Iris官网下载链接供参考

[Iris下载链接](https://iristech.co/iris/)

软件版本：2.5.6
运行平台：微软商店

**Comment by septs** [comment]
您应该与 Iris 报告问题

**Comment by Sun-Pengcheng** [comment]
> 您应该与 Iris 报告问题

好的，有道理

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/1239#issuecomment-602695713

**Comment by HAILANGDENG** [comment]
dssd
