### ISSUE TITLE
请求新功能 - 自定义截图框尺寸

### ISSUE THREAD

**Issue by Noctsyndrome** [Snipaste/feedback#1802]
功能请求：截图框尺寸标识提供编辑功能，可通过直接编辑数字调整框体大小。
功能场景：出于截图展示效果和个人习惯，在截图框出现  599 * 417 px 类似数值的时候，只能拖拽边框调来整到 600 * 420 px 这种更适合展示的尺寸，并且在 1 像素级别的调整通过拖拽操作起来也相当困难。希望能够提供编辑功能。

**Comment by Noctsyndrome** [comment]
update:
检索后发现专业版已提供此功能，request 关闭。感谢

**Comment by Datamore** [comment]
这个功能确实不错。另外类似的，能否编辑后再调整截图的大小，只要调小就行，不要调大。
实际中不可能一次性将图的大小截取到位的。
