### ISSUE TITLE
请求:选中贴图之后。通过右键或者菜单可以取消图片置顶。

### ISSUE THREAD

**Issue by heartacker** [Snipaste/feedback#1805]
当选中贴图之后，可以点击右键却换吃这个图片是否置顶。

我为什么需要。
经常截图并贴图。对比之后，不想置顶了因为他置顶挡住了屏幕。，但是又不想关闭它，因为只是暂时想操作其他图片。

**Comment by liulex** [comment]
专业版：
![](https://user-images.githubusercontent.com/2010459/109679751-d56eba00-7bb6-11eb-9074-2b618f174138.png)

**Comment by heartacker** [comment]
桌面高级版什么时候可以购买呢？我的电脑没有windows store ，所以没办法使用这个高级的功能。感觉很需要。
