### ISSUE TITLE
输入文字和复制贴图失败

### ISSUE THREAD

**Issue by mengweiya** [Snipaste/feedback#1806]
在编辑截图的时候,输入文字,在修改大小和字体之后,中文输入失败,“delete”失败,英文可以输入,快捷键“ctrl+c”也不能用
软件版本：2.5.6-Beta(2020.12.10)
运行平台：macOS

**Comment by liulex** [comment]
输入文字的时候，ctrl-c 属于文字编辑框，不会复制贴图。
至于其他问题，我无法重现。
