### ISSUE TITLE
\history\snip文件夹里的是什么文件

### ISSUE THREAD

**Issue by oneindexhuoyue** [Snipaste/feedback#1807]
\Snipaste-2.5\history\snip  这个文件夹里总共七八百兆，是什么文件？可以删除吗？

**Comment by liulex** [comment]
截图历史，可以手动删除，也可以在选项里永久关闭。

**Comment by hausen1012** [comment]
> 截图历史，可以手动删除，也可以在选项里永久关闭。

是这里关闭吗？
![image](https://github.com/Snipaste/feedback/assets/50026605/b8a16bf1-2bda-4fbd-9588-3b027294d93e)
