### ISSUE TITLE
能否添加识别二维码的功能

### ISSUE THREAD

**Issue by walkxspace** [Snipaste/feedback#1808]
Chrome上有类似插件，但仅限于在Chrome内识别网页上的二维码，如果遇到不在Chrome中的其他应用，如某个文档中有二维码，能否在Snipaste框选中一个二维码后进行识别的操作，免去在电脑上遇到有二维码的情况需使用手机扫描再发送扫描的内容到电脑。

**Comment by septs** [comment]
Duplicate of #23
