### ISSUE TITLE
打开自制播放器加密视频，会让Snipaste后台程序关闭（管理员启动也没用）

### ISSUE THREAD

**Issue by 863411103** [Snipaste/feedback#1809]
打开这种加密视频观看以后，后台的开启程序会自动关闭（但是别的程序没事）
![Snipaste_2021-03-05_09-32-53](https://user-images.githubusercontent.com/52234949/110054278-c85bf180-7d95-11eb-9a4c-7e2cc587ab5d.png)

**Comment by septs** [comment]
> 涉及版权的问题，Snipaste 不该做针对性的破解。

from https://github.com/Snipaste/feedback/issues/330#issuecomment-277406582
