### ISSUE TITLE
French Keyboard

### ISSUE THREAD

**Issue by Xtian78** [Snipaste/feedback#1810]
Not a big deal, but when moving the cursor using A, W, S and D, it sees that those keys are fixed and not keyboard/langage dependant. For exemple, on a french keyboard,  you would use Z (up) and W (down), Q (left) S (right).
Rgds

**Comment by liulex** [comment]
I think it's Z (up), S (down), Q (left) D (right)?

**Comment by liulex** [comment]
Implentented in Snipaste 2.6. Welcome to provide more feedback if it does not meet your expectation.
