### ISSUE TITLE
可否增加CLI功能以支持工作流处理

### ISSUE THREAD

**Issue by ferstar** [Snipaste/feedback#1815]
大概期望是:

```shell
snipaste-cli --some-options | other-cli-bin --options
```

`other-cli`可以是任意支持标准输入输出流的工具, 可以实现一些比如: 有损压缩/DPI修改/或者别的自定义的CLI组合

PS: 该功能可以作为`Pro`版本的`feature`

**Comment by septs** [comment]
see https://docs.snipaste.com/command-line-options

目前尚未支持通过 stdio 操作，建议另外新开一个 issue 陈述
您对于使用 stdio 操纵 Snipaste 的具体想法
