### ISSUE TITLE
命令行：提供一个关闭win10通知的选项

### ISSUE THREAD

**Issue by valuex** [Snipaste/feedback#1818]
Win10系统，每次通过命令行执行完Snipaste后都会弹出一个通知。
批量执行的话还是挺烦人的。
请看看，能否提供一个关闭通知运行的选项，类似 -notraytip这样。

**Comment by liulex** [comment]
![](https://user-images.githubusercontent.com/2010459/111489261-edc50400-8774-11eb-8ca4-204cdcb8b5f6.png)

**Comment by valuex** [comment]
感谢答复！
