### ISSUE TITLE
内置快捷键无法覆盖

### ISSUE THREAD

**Issue by wangxing-wq** [Snipaste/feedback#1819]
snipaste确实非常好用,但是用这个的时候是为了配置typora 截图使用,但是内置快捷键  `  会和使用typora 使用 ``` 开启代码块有所冲突,每次都需要手动关闭快捷键使用...

软件版本：2.5.6
运行平台： Windows 桌面

**Comment by wangxing-wq** [comment]
希望能够提供一个其他快捷键使用的快捷键,或者可以使用部分快捷键的功能..谢谢

**Comment by liulex** [comment]
内置快捷键又不是全局的，怎么会跟其他程序有冲突？

**Comment by wangxing-wq** [comment]
> 内置快捷键又不是全局的，怎么会跟其他程序有冲突？

可能是我从windows下载的原因吧,当时确实是有冲突的, 从github又下载的这个无问题
