### ISSUE TITLE
希望能够提供关闭一个其他快捷键使用的快捷键,或者可以使用部分快捷键的功能.

### ISSUE THREAD

**Issue by wangxing-wq** [Snipaste/feedback#1820]
希望能够提供一个其他快捷键使用的快捷键,或者可以使用部分快捷键的功能..谢谢

_Originally posted by @wangxing-wq in https://github.com/Snipaste/feedback/issues/1819#issuecomment-798823648_

**Comment by liulex** [comment]
专业版可以：
![image](https://user-images.githubusercontent.com/2010459/127765497-1ded16b4-58dc-4849-88b2-d42a022de5b4.png)
