### ISSUE TITLE
增加画笔及其它简单标记功能

### ISSUE THREAD

**Issue by lqdjdy** [Snipaste/feedback#1821]
如下图QQ截图工具栏功能，但这个只能在截图时才能使用。
往往载完图后，可能还需要对图片进一步处理，如画线，添加注释等，这个能加上，Snipaste就更好用了。

期待早日实现。

![image](https://user-images.githubusercontent.com/4065951/111063359-015c3a80-84e9-11eb-9335-51dddcd8be94.png)

**Comment by septs** [comment]
请重新阅读文档后重新评价。

**Comment by lqdjdy** [comment]
en, 已经有了，谢谢！
