### ISSUE TITLE
🌟功能请求:  贴图拼接|缝合

### ISSUE THREAD

**Issue by dnknn** [Snipaste/feedback#1822]
> 功能类似于 https://www.qtool.net/picstitching

![image](https://user-images.githubusercontent.com/10995302/111081385-12836680-853e-11eb-9949-8760925200eb.png)

	是的, 若是小尺寸贴图, Snipaste贴图直接截屏即可拼接, 
	但若是大尺寸的贴图, 此时Snipaste无法类似于变相实现, 可以贴图拼接尺寸超出了显示器范围外,
	是的, 也有N种方式能实现图片拼接, 但是若Snipaste原生支持贴图拼接, 那就能一键生成贴图拼接!
	即, 2张或多张贴图拼接为一张大尺寸的

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/45
