### ISSUE TITLE
截图闪退

### ISSUE THREAD

**Issue by li1062** [Snipaste/feedback#1826]
打开软件之后按F1截图之后直接闪退，32/64版本都是一样的问题

软件版本：32/64两个版本
运行平台：微软商店 / Windows 桌面 / macOS

**Comment by liulex** [comment]
这种情况是被其他软件杀掉了吧……

**Comment by li1062** [comment]
已解决，对不起麻烦您了，谢谢您的回信！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Le ***@***.***&gt;; 
发送时间: 2021年3月30日(星期二) 凌晨0:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Snipaste/feedback] 截图闪退 (#1826)






这种情况是被其他软件杀掉了吧......

—
您正在接收此消息，因为您编写了线程。
直接回复此邮件，在GitHub上查看，或取消订阅.
