### ISSUE TITLE
绘图颜色可设置

### ISSUE THREAD

**Issue by traddo** [Snipaste/feedback#1827]
在截图中使用的绘图、文字工具的颜色是否可以改为可设定？ ini文件设置或界面设置均可。

**Comment by Geeyun-JY3** [comment]
https://docs.snipaste.com/zh-cn/getting-started?id=画板里没有我想要的颜色

**Comment by liulex** [comment]
![image](https://user-images.githubusercontent.com/2010459/112314918-895df380-8ce4-11eb-8897-0af2b917a31a.png)
