### ISSUE TITLE
贴图标注工具条不自动显示

### ISSUE THREAD

**Issue by Hinlavic** [Snipaste/feedback#1829]
问题：再次打开贴图标注工具条（已勾选）不能自动显示，需要移动贴图一下才会再出现。
复现：
1. 复制任意内容到系统剪切板；
2. 快捷键F3打开贴图，并右键贴图->勾选“标注”，标注工具条正常出现，关闭贴图；
3. 快捷键F3再次打开贴图，此时标注工具条不出现，右键贴图确认“标注”仍然是选中状态的；
4. 任意移动贴图位置，标注工具条再次出现。

 
软件版本：2.5.6
运行平台：微软商店

**Comment by liulex** [comment]
谢谢反馈！会在下个版本修复。
