### ISSUE TITLE
Pop-up windows are on 2nd screen

### ISSUE THREAD

**Issue by milkiSK** [Snipaste/feedback#1831]
Hi, when I snip and want to change color, or quit snipping, the popup window gets open on the second screen. It would be very convenient to have these windows open next to, or on top of the snipped area. Or if the app could remember the position of the last known opened pop-up.
Thank you very much.

Love this app!

App version:
Platform: Microsoft Store

**Comment by liulex** [comment]
I do meant to pop up the color dialog next to the toolbar, but it got broken after an update six months ago. I will fix it in the next release, as well as adjusting the position of "Esc confirm" dialog.

Thanks for reporting!
