### ISSUE TITLE
求一个二维码解析功能就那么难么？

### ISSUE THREAD

**Issue by nickolboy** [Snipaste/feedback#1834]
我搜了，已经很多人提了，几年过去了也没做。这么常见的功能，实现下这么难么？

**Comment by clatteringmarion** [comment]
@nickolboy 作为Snipaste用户说一句
https://github.com/Snipaste/feedback/issues/1495#issuecomment-617219176
如果截图的用户里面99%都用二维码解析并且提出要求， 那估计作者会很快在软件内加入...
另外， 这东西是截图软件 不是二维码软件 
如果你对这个有想法， 在 https://github.com/Snipaste/feedback/issues/23 表示支持， 而不是另开一个贴子不是更好嘛？

**Comment by clatteringmarion** [comment]
重复：#23、#591、#917、#932、#1251、#1270、#1495、#1808、 #1830 
建议关闭 @septs

**Comment by septs** [comment]
Duplicate of #23
