### ISSUE TITLE
Windows 10 ARM 支持

### ISSUE THREAD

**Issue by TGSAN** [Snipaste/feedback#1836]
您好，请问是否有支持 ARM（32/64）版 Windows 10 的计划呢？目前在用基于 ARM64 的 Surface Pro X，在安装 Snipaste 时发现还尚未支持 ARM 架构。

**Comment by septs** [comment]
Windows 的 arm32 支持仅限于 Surface RT 无支持的意义。
至于 arm64 请等待作者的回复

**Comment by septs** [comment]
请合并至 https://github.com/Snipaste/feedback/issues/1766#issuecomment-755318284 继续讨论
