### ISSUE TITLE
HTML元素無法自動判定問題

### ISSUE THREAD

**Issue by dabinn** [Snipaste/feedback#1839]
我在四、五台電腦上安裝了win store版的Snipate
環境都是window10+chrome瀏覽器
發現其中一台可以抓取網頁上的html元素 (例如DIV的框)，使用起來非常方便
但其它的電腦卻都不行，頂多只能抓到視窗內部
已確認每一台選項中"Auto detect UI elements"都是勾選的，但就是只有那一台有辦法抓html元素
不知造成這種差別的原因為何？

**Comment by leliu-pony** [comment]
[截图时无法自动选取浏览器窗口的页面元素](https://docs.snipaste.com/zh-cn/troubleshooting?id=%e6%88%aa%e5%9b%be%e6%97%b6%e6%97%a0%e6%b3%95%e8%87%aa%e5%8a%a8%e9%80%89%e5%8f%96%e6%b5%8f%e8%a7%88%e5%99%a8%e7%aa%97%e5%8f%a3%e7%9a%84%e9%a1%b5%e9%9d%a2%e5%85%83%e7%b4%a0)

**Comment by liulex** [comment]
[截图时无法自动选取浏览器窗口的页面元素](https://docs.snipaste.com/zh-cn/troubleshooting?id=%e6%88%aa%e5%9b%be%e6%97%b6%e6%97%a0%e6%b3%95%e8%87%aa%e5%8a%a8%e9%80%89%e5%8f%96%e6%b5%8f%e8%a7%88%e5%99%a8%e7%aa%97%e5%8f%a3%e7%9a%84%e9%a1%b5%e9%9d%a2%e5%85%83%e7%b4%a0)
