### ISSUE TITLE
希望能加入贴图快捷键能识别当前选中文本直接贴图，免去复制操作

### ISSUE THREAD

**Issue by olunju** [Snipaste/feedback#1842]
在日常工作中，贴出文本也是使用频率很高的功能之一，特别是在多个窗口操作或文本对比的时候，但是当调试次数多的时候，复制这一步操作显得很多余，希望能加入【贴出选中内容】选项

**Comment by septs** [comment]
鉴于大部分软件对于 a11y (accessibility) 支持等同于没有

因此该建议在技术层面不具备可行性
