### ISSUE TITLE
副屏上无法对齐贴图 bug

### ISSUE THREAD

**Issue by wengh** [Snipaste/feedback#1843]
重现步骤
1. 在主屏上贴出两个贴图
2. 按住 `Shift`，左键拖动一个贴图，靠近另外一个时松开左键
3. 两个贴图会自动对齐
4. 在副屏上重复步骤 1-2
5. 可以观察到自动对齐功能失效

软件版本：
运行平台：微软商店

**Comment by liulex** [comment]
感谢反馈！会在下个版本修复。
