### ISSUE TITLE
建议加入截图文字OCR功能

### ISSUE THREAD

**Issue by slipingblue** [Snipaste/feedback#1846]
如题，建议加入对截图中文字进行OCR的选项，这样对与一些工作的帮助非常大，尤其是当前由于微信公众号的泛滥，很多文字都是通过图片的方式来传递，如果有截图OCR的功能，会大大方便相关的工作进行。

**Comment by slipingblue** [comment]
抱歉，没有查看以前的issue，我会关闭这个issue。

**Comment by septs** [comment]
Duplicate of #188
