### ISSUE TITLE
Chrome 无法自动检测到「网页内容」和「DevTools」

### ISSUE THREAD

**Issue by wenfangdu** [Snipaste/feedback#1849]
App version: 2.5.6-Beta
Platform: Windows Desktop

用 Chrome 进行截图，会把「地址栏」和「标签栏」包含在范围内，无法只检测「网页内容」：

![image](https://user-images.githubusercontent.com/28700378/115393171-fb5a2780-a213-11eb-9d6c-a70c8e1309ed.png)

也无法只检测「DevTools」：

![image](https://user-images.githubusercontent.com/28700378/115393498-5a1fa100-a214-11eb-8a46-84543a335e90.png)

**Comment by chenrylee** [comment]
https://docs.snipaste.com/zh-cn/troubleshooting?id=%e6%88%aa%e5%9b%be%e6%97%b6%e6%97%a0%e6%b3%95%e8%87%aa%e5%8a%a8%e9%80%89%e5%8f%96%e6%b5%8f%e8%a7%88%e5%99%a8%e7%aa%97%e5%8f%a3%e7%9a%84%e9%a1%b5%e9%9d%a2%e5%85%83%e7%b4%a0

**Comment by wenfangdu** [comment]
@chenrylee 不过微信自带的截图不需这些配置，也能自动识别网页内容，是为啥呢
