### ISSUE TITLE
【功能】首选项取消置顶

### ISSUE THREAD

**Issue by wenfangdu** [Snipaste/feedback#1850]
目前首选项始终是置顶的状态，这在切换窗口进行截图的时候非常不便，希望可以新增一个选项「取消置顶」。

**Comment by liulex** [comment]
那为什么截图的时候要开着首选项窗口呢。。

**Comment by wenfangdu** [comment]
@liulex 
> 这在「切换窗口」进行截图的时候非常不便

我也不想开着，一般的窗口都不是置顶的，一切换就看不见了。但 Snipaste 的首选项是一直置顶的，除非手动关闭，否则一直开着，所以被动开着首选项窗口截图。

**Comment by liulex** [comment]
首选项置顶是为了不会被贴图挡住。
根据你描述的场景，只是想测试选项的效果，既然只是测试，截图中是否包含首选项窗口无关紧要吧。
我觉得没有必要为此添加一个选项。

**Comment by wenfangdu** [comment]
@liulex 经测试，贴图可以覆盖首选项：

![image](https://user-images.githubusercontent.com/28700378/118057854-5d472080-b3bf-11eb-94da-0190fbe6af60.png)

**Comment by liulex** [comment]
同样是置顶的窗口，点了哪个哪个就在上面。
