### ISSUE TITLE
拾色功能

### ISSUE THREAD

**Issue by xianzhiding** [Snipaste/feedback#1851]
拾色功能如果能单独提取出来就完美了，或者开放快捷键也行，我想在不截图的情况下去拾取屏幕上的任意颜色，现在这个功能太深了需要截图才能操作，我想这对前端开发或设计来说最爽的功能了，我现在用的是FSCapture，他的拾色功能很直接，望借鉴。

**Comment by liulex** [comment]
专业版是可以给取色一个快捷键的：
![image](https://user-images.githubusercontent.com/2010459/115881148-07492200-a47e-11eb-9c29-423231da11bc.png)
