### ISSUE TITLE
保存自己喜欢的设置

### ISSUE THREAD

**Issue by darmier** [Snipaste/feedback#1856]
想要一个保存自己设置的功能，比如划线箭头的颜色，字体的颜色大小等
每次开机或者关闭软件后，都会回到默认设置，有些麻烦，希望能有所改进

**Comment by jackple** [comment]
@darmier 可以自己备份配置文件, https://docs.snipaste.com/zh-cn/command-line-options?id=%e5%85%b6%e4%bb%96%e5%91%bd%e4%bb%a4

**Comment by liulex** [comment]
你应该是关闭了首选项里的“自动备份”功能。
