### ISSUE TITLE
滚动截图和贴图裁剪

### ISSUE THREAD

**Issue by Ruo-bin** [Snipaste/feedback#1857]
希望可以增加滚动截图和贴图裁剪功能，谢谢

**Comment by Geeyun-JY3** [comment]
滚动截图：#19
贴图裁剪需要专业版：https://docs.snipaste.com/zh-cn/pro?id=%e8%b4%b4%e5%9b%be%e7%9b%b8%e5%85%b3

**Comment by jbxiaoyu** [comment]
滚动截图是不是不准备添加了呢？2016年提到现在好像都没添加，是这个功能不大好实现吗？有点好奇
