### ISSUE TITLE
中止截图的操作问题

### ISSUE THREAD

**Issue by wjxjmj** [Snipaste/feedback#1858]
文档中提到的中止截屏的方式是按下esc按键，但实际操作中双击鼠标左键也会中止截屏。
由于我的鼠标偶尔会单击变双击，在修改截屏（例如使用画笔）时可能会意外地触发中止截屏。
请问如何禁用鼠标左键双击中止截屏的行为？谢谢

**Comment by chenrylee** [comment]
单击变双击说明鼠标坏了，干吗不换/修鼠标呢？😉
据我所知没这设置，毕竟开发者的鼠标一直是好的。😆

**Comment by wjxjmj** [comment]
> 单击变双击说明鼠标坏了，干吗不换/修鼠标呢？😉
> 据我所知没这设置，毕竟开发者的鼠标一直是好的。😆

即便试用好的鼠标，也依然存在以外中止截屏的问题，例如我需要画虚线，点啊带突然就中止截屏了

**Comment by liulex** [comment]
![Uploading image.png…]()
