### ISSUE TITLE
关闭`拖动时显示窗口内容`时, 无法拖动边缘来缩放贴图

### ISSUE THREAD

**Issue by the1812** [Snipaste/feedback#1862]
在 Windows 的高级系统设置中, 关闭性能选项里的`拖动时显示窗口内容`后, 拖动贴图的边缘没有实际效果, 只能用滚轮来缩放了.
我记得以前只是不能将贴图移出屏幕上方, 倒还可以接受, 现在连大小都不能调了有点难受, 滚轮又很容易滚过头.
或许跟系统更新了有关系?

软件版本：2.5.6 (2020.12.10)
运行平台：微软商店 / Windows 10 20H2

<img width="400" src="https://user-images.githubusercontent.com/26504152/117535067-a34e5e00-b026-11eb-90ac-c44eae4ea305.png">

**Comment by liulex** [comment]
确实有这个问题，我查一下。
