### ISSUE TITLE
截图能够自动标注

### ISSUE THREAD

**Issue by meixuhong** [Snipaste/feedback#1865]

**Comment by meixuhong** [comment]
自动按照你标注的顺序在图上依次打上 1 - 2 - 3……的序号，像sniptool一样。
![sniptool](https://user-images.githubusercontent.com/18494589/117575424-39d75980-b0d1-11eb-8df7-520b832e9151.gif)

**Comment by liulex** [comment]
https://weibo.com/5991159918/J2PLlCxKt
