### ISSUE TITLE
最大歷史紀錄數的「限制」---> 能新增「時間」及「容量」嗎

### ISSUE THREAD

**Issue by hunandy14** [Snipaste/feedback#1866]
在設定裡面的「最大歷史紀錄數」目前限制只有數量，比如說設置10超過10就砍掉最後面那張新的補進去
不知道這個數的部分能不能有「時間」和「容量」的限制器選項

希望的功能是超過一年的砍掉+超過512M後開始循環砍掉

主要是希望的功能是容量，每張截圖的容量並不是完全相同的用數量一刀切有點不好掌握
不希望設太高以至於耗費硬碟容量，另一方便設太低如果都擷取小圖那就是瞎擔心了

感謝你的付出，這是我用過最好的軟體，覺得不可能再有人可以超過了XD

**Comment by hunandy14** [comment]
剛剛仔細測了一下發現有個地方弄錯了，不是我想的那樣
不管擷大擷小都是保存全螢幕截圖(有壓縮的話可能因為畫面複雜度稍微影響大小)

這樣剛剛想的問題其實就其實沒那麼重要了
不過如果有的話還是希望可以用容量精準控制

**Comment by liulex** [comment]
是的，截图历史保存的始终都是全屏截图，存储大小是差不多的。
既然如此，那要控制总容量也很容易换算了。
截图历史的设计是为了拿回以前的某个截图，只能通过 Snipaste 顺序查看，所以设置太大的数量限制其实没多大意义。
将来有计划加强截图历史的功能，但就目前而言，我认为没有必要再加选项了。
