### ISSUE TITLE
打开首选项open-preferences: 无效的命令行参数

### ISSUE THREAD

**Issue by jackple** [Snipaste/feedback#1867]
```bash
./snipaste/Snipaste.exe open-preferences
```

![image](https://user-images.githubusercontent.com/6183232/117768736-5c9a7700-b265-11eb-841f-087acd4d4079.png)

App version: 2.5.6
Platform: Windows Desktop

**Comment by liulex** [comment]
![image](https://user-images.githubusercontent.com/2010459/118012206-631f1080-b383-11eb-82a3-3c161e6b8e95.png)
