### ISSUE TITLE
这款软件对于gif和apng的支持很好，但可以做到更多

### ISSUE THREAD

**Issue by olunju** [Snipaste/feedback#1869]
专业版的复制图片文件直接贴图帮了我很多，比如其他格式的复制、贴图，然后另存为就转换为png了，

目前web编辑器粘贴上传图片时不支持文件的，所有我都是使用此软件贴图然后复制图像，再直接粘贴到web的富文本编辑器中

可是目前我遇到了问题，gif和apng复制图像复制到的是单帧的png格式图像，我认为应该是可以直接复制gif图像格式的，毕竟都能解析出来了

希望在播放情况下复制gif之类的动图是复制的原图像，而在暂停状态下复制图像是单帧图像

**Comment by septs** [comment]
您的诉求改变原有的行为

对于其他的用户来说，是反既定使用习惯的请重新考虑

**Comment by liulex** [comment]
剪贴板里是不支持放动态图像的，所以不存在复制 gif 图像格式这种说法，要放也只能放 gif 图片文件。

**Comment by olunju** [comment]
谢谢，可能是其他软件适配了粘贴的功能吧
