### ISSUE TITLE
[功能请求] 在截图完后自动粘贴

### ISSUE THREAD

**Issue by Cyl18** [Snipaste/feedback#1870]
QQ的截图在截图完后会自动把截图的内容粘贴到聊天框
而Snapaste需要手动Ctrl V一下 有些不方便

就希望可以加入一个在截图完后自动粘贴(比如模拟 Ctrl V)的可选功能 或者对autohotkey之类的适配
视频演示:
https://user-images.githubusercontent.com/14993992/118521928-12862980-b76e-11eb-9cd7-428d3b85b373.mp4

**Comment by septs** [comment]
建议客户携带甲方与 Snipaste 洽谈深度集成事宜。

**Comment by liulex** [comment]
专业版可以自定义截图指令，使截图后执行指定程序，配合 autohotkey 是可以实现你的需求的。
