### ISSUE TITLE
希望提供安装包

### ISSUE THREAD

**Issue by shenzhiming88** [Snipaste/feedback#1871]
您好！
其实之前已经有人有类似需求，但是没有打上 `feature` 的标签
https://github.com/Snipaste/feedback/issues/831
希望能提供安装包，因为我个人比较喜欢安装版，认为应该会更加稳定
需要长期做也没关系，但是希望将来能够实现
谢谢！
顺带问一下桌面版有专业版吗？

**Comment by StarryVoid** [comment]
因为软件本身就是绿色版的，安装的稳定角度而言，只有 c++要安装2015，以及 配置文件。

**Comment by septs** [comment]
Duplicate of #831

**Comment by shenzhiming88** [comment]
> Duplicate of #831

您好！
我知道该问题重复了，但是在问题中提到了：
其实之前已经有人有类似需求，但是没有打上 feature 的标签
#831
所以请问有这个计划吗？

**Comment by septs** [comment]
显然是没有的
