### ISSUE TITLE
希望下个版本可以提供截图后，ORC文字识别功能。

### ISSUE THREAD

**Issue by xxxxha** [Snipaste/feedback#1872]
如题，希望在专业版中提供ORC文字识别功能。截图后，可以选择ORC识别文字。这个ORC识别可以调用其他开放平台的接口，比如，百度或者阿里的ORC识别api。当然，这些接口也不是免费的，可以提供一些付费的方式。目前，其实有一些ORC识别软件已经做到了，我上述说到的实现方式。但是，他们的截图功能不够强大。所以，我目前是两种软件都开着。要是这个软件也能做ORC识别，我就不用多开一个软件了。

**Comment by Geeyun-JY3** [comment]
关了一个又开一个：#1868

#188

**Comment by septs** [comment]
Duplicate of #188
