### ISSUE TITLE
Share Button?

### ISSUE THREAD

**Issue by knchmpgn** [Snipaste/feedback#1875]
I have been using Snipaste for years now and most of the time I take a screenshot it's with the intention of sending it to another person. It would be really great to see Snipaste incorporate Windows 10's "Share" feature as a toolbar button. I usually save the image, then use the "Share" button from Windows or insert the file directly into whatever app I am using, then delete the image. It would be really awesome if we could skip all that with a button directly from Snipaste. Since the Your Phone Companion app came around I find myself using this program a LOT more for sending quick things from my computer to a friend through a text message.

**Comment by septs** [comment]
Duplicate of #188

**Comment by liulex** [comment]
@septs Share button is not the same as image upload.

@knchmpgn I may add it in the next version, but it would require Snipaste Pro.

**Comment by liulex** [comment]
@knchmpgn Implemented in Snipaste 2.6 PRO.
