### ISSUE TITLE
能否增加集成一下鼠标手势功能

### ISSUE THREAD

**Issue by qtvbwfn** [Snipaste/feedback#1877]
增加集成鼠标手势功能，通过鼠标手势实现对浏览器、文件夹等相关操作

就是这个软件的功能：https://github.com/yingDev/WGestures
部分手势的说明
![image](https://user-images.githubusercontent.com/5848026/119621638-f1da6580-be38-11eb-8280-5ce4f7d6930b.png)

**Comment by Geeyun-JY3** [comment]
直接用这个应用不就好了。为什么要 Snipaste 集成？和截图贴图有什么较紧密的联系吗？

**Comment by septs** [comment]
Duplicate of #556
