### ISSUE TITLE
截图粘贴时异常

### ISSUE THREAD

**Issue by imxuejin** [Snipaste/feedback#1879]
截屏后，粘贴时频繁偶现异常，例如：
1. 粘贴时，提示无内容
2. 截图A，然后再截图B，此时粘贴却发现是图A

软件版本：2.5.6-Beta（2020.12.10）
运行平台：Windows 10

**Comment by septs** [comment]
请提供 屏录 和 日志 以便于分析

**Comment by liulex** [comment]
一般是因为第三方软件在异常占用剪贴板，请自行排查。
