### ISSUE TITLE
使用 Chrome Remote Desktop 遠端到另一台電腦，截圖時要新增文字時，C這個按鍵無法正常打字

### ISSUE THREAD

**Issue by SyaoranChang** [Snipaste/feedback#1884]
Hi,

無法重現的版本: 
Snipaste-2.4-Beta-x64

可重現的版本: 
Snipaste-2.5.2-Beta-x64
Snipaste-2.5.6-Beta-x64

使用 Chrome Remote Desktop 遠端到另一台電腦，
使用遠端的電腦截圖時要新增文字時，C這個按鍵無法正常打字
使用本地自己的電腦時，功能是都正常的

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/1397
