### ISSUE TITLE
命令行截图采用$MM$变量时，生成的文件名月份不正确

### ISSUE THREAD

**Issue by Pual397** [Snipaste/feedback#1890]
Snipaste.exe snip --last -o d:\测试_$MM$.png
$MM$不是正确的月份
![image](https://raw.githubusercontent.com/Pual397/else/main/bug1.gif)

而且命令行偶有不响应的现象

软件版本：2.5.6beta 2020.12.10 免费版
运行平台：Windows 桌面

**Comment by chenrylee** [comment]
可复现，M和m大小写不敏感，都以分钟处理了。

**Comment by liulex** [comment]
谢谢反馈，会在下个版本修复。
