### ISSUE TITLE
macos下截图使用文本框组件，修改字号大小后无法输入或修改文本

### ISSUE THREAD

**Issue by storyxc** [Snipaste/feedback#1895]
截图后使用文本框输入文本时一切正常，但是如果调整字号大小，将无法继续使用文本框输入或修改之前输入的文本内容。

软件版本：2.5.6-Beta(2020.12.10)
运行平台：macOS

**Comment by liulex** [comment]
无法重现，请录屏描述一下。

**Comment by storyxc** [comment]
> 无法重现，请录屏描述一下。

https://www.storyxc.com/doc/screen.mp4

**Comment by liulex** [comment]
非常感谢，会在下个版本修复。
