### ISSUE TITLE
The letter "c" does not work when add text annotation to a snip. 

### ISSUE THREAD

**Issue by jt3432** [Snipaste/feedback#1898]
Not able to type the letter "c" when Snipaste is active or adding annotation text to an image. I suspect that since "C" is a short cut the app is always listening even when the magnifier is not visible and trying to triggering the "Copy the color value if the magnifier is visible" feature.

App version:
Windows 10  Home Desktop 64bit
Language: English
Snipaste Version: 2.5.6-Beta (2020.12.10) 64bit

**Comment by liulex** [comment]
By default Snipaste ignores simulated "C" key. Unchecking this option would solve your issue:
![image](https://user-images.githubusercontent.com/2010459/122577966-fedc2480-d085-11eb-8671-85fe7781d91f.png)

**Comment by jt3432** [comment]
Thanks for the help! That did the trick and "C" works :-)

**Comment by jt3432** [comment]
User error.
