### ISSUE TITLE
mac可以增加删除贴图组功能吗？windows有这个功能mac却没有

### ISSUE THREAD

**Issue by catlzn** [Snipaste/feedback#1903]
mac可以增加删除贴图组功能吗？
windows有这个功能mac却没有，mac的还得一个个图关掉再删除空组才能删掉，截图一多就很崩溃

**Comment by catlzn** [comment]
是否可以增加一个快捷键删除贴图组？

**Comment by Geeyun-JY3** [comment]
Duplicate of #1440
