### ISSUE TITLE
希望工具栏可拖动解决“极端”情况下的遮挡问题

### ISSUE THREAD

**Issue by jamesfancy** [Snipaste/feedback#1907]
> 搜了一下，#238 提到了类似的问题，与本请求与之不同。

如果截图区域全屏（或类似），工具栏位置无法闪避，会遮挡右下角区域。而右下角区域往往是软件窗口的状态栏，有时候需要画点框、箭头啥的指示一下，这就很难办了。

虽然 @liulex 提出可以先贴出来再编辑的方案（实现我现在也是这么干的），但总觉得要多一步。

本来以为工具栏右边的三个点 ( `┇` ) 是可以用来拖动的，试了才发现是个扩展菜单。那么 —— 这东西可不可以做成拖动柄，同时保留原来的作用呢？或者干脆给工具栏添加拖动柄区域，有如下三个方案可选：

- 上面说的，现在的 `┇` 同时成为拖动柄
- 在左侧或右侧添加专门的拖动柄
- 给工具栏一个 2~3px 的边框，作为拖动柄

另，考虑到强迫症，拖动到截图边框附近（比如 5px）的时候自动吸附。

**Comment by liulex** [comment]
可以按空格键隐藏。

**Comment by jamesfancy** [comment]
> 可以按空格键隐藏。

虽然不是原本期望的结果，但是可以解决问题。多谢！

**Comment by LaniakeaS** [comment]
还是希望加入一下这个功能
