### ISSUE TITLE
能否增加文件夹内图片浏览功能

### ISSUE THREAD

**Issue by justjump** [Snipaste/feedback#1910]
比如现在截取了一张图并且置顶了。
想通过滚轮或者键盘在这个置顶的窗口上浏览截图文件夹内的其它图片（或者上一张置顶的截图）。

**Comment by StarryVoid** [comment]
听起来的意思是 制造一个框选区域，在这个区域内浏览贴图组的所有图片，同时调整缩放以适应图片大小，和相关的贴图标记

**Comment by liulex** [comment]
抱歉，没有此计划，这不是一个图片浏览器。
