### ISSUE TITLE
Change to "Start on Logged In"

### ISSUE THREAD

**Issue by devAstr** [Snipaste/feedback#1912]
Chagne start behavior
form Start on boot
to Start on logged in

cause
windows 11 have dwm bug (?) will appear a empty windows and it can't close
I will logged out to close all window
and I noticed that Snipaste will not start when I logged in again
----

請求將 開機時啟動 更改為 登入時啟動

起因
Windows 11 有一個視窗Bug會顯示一個無法關閉的空白視窗
以致於我必須登出再登入來關閉視窗
此時Snipaste並不會隨登入一同啟動

**Comment by liulex** [comment]
既然这是 Windows 的 bug，没理由让其他应用为此提供偏门方法。
