### ISSUE TITLE
滚动截屏可以添加么

### ISSUE THREAD

**Issue by zxh451200** [Snipaste/feedback#1918]
长截图甚至gif动图

**Comment by StarryVoid** [comment]
参考 #19

**Comment by Geeyun-JY3** [comment]
两个置顶能先看看么：#19、https://github.com/Snipaste/feedback/issues/282#issuecomment-268239323

**Comment by zhouxx2018** [comment]
> 参考 #19

2016年的回复了啊

**Comment by Geeyun-JY3** [comment]
> > 参考 #19
> 
> 2016年的回复了啊

看打的 tag，看一下整个讨论串，看一下开发者的回复，自行评估。

**Comment by septs** [comment]
Duplicate of #19
