### ISSUE TITLE
可以增加截图后直接添加边框功能吗？

### ISSUE THREAD

**Issue by scorpion19961007** [Snipaste/feedback#1919]
<!--
        可以增加截图后直接添加边框功能吗？现在市面上那些可以添加边框的截图软件都没有snipaste方便，毫无疑问snipaste是目前为止非常强大的截图软件，但是缺少一个截图后增加边框的功能，例如sharex，faststone Capture等等，他们的截图增加边框功能非常实用。希望snipaste也可以增加这个功能。还望多考虑考虑，谢谢。

_**以下为Google翻译，可能会与原文有所出入：**_
        **Can I add a border function directly after adding a screenshot? Now that the screenshot software that can add borders on the market is not as convenient as snipaste, there is no doubt that snipaste is a very powerful screenshot software so far, but it lacks the function of adding a border after a screenshot, such as sharex, faststone Capture, etc., and their screenshots are increased. The border function is very practical. Hope that snipaste can also increase this function. I hope to think about it, thank you.**

**Comment by scorpion19961007** [comment]
可以增加截图后直接添加边框功能吗？现在市面上那些可以添加边框的截图软件都没有snipaste方便，毫无疑问snipaste是目前为止非常强大的截图软件，但是缺少一个截图后增加边框的功能，例如sharex，faststone Capture等等，他们的截图增加边框功能非常实用。希望snipaste也可以增加这个功能。还望多考虑考虑，谢谢。

**Comment by Geeyun-JY3** [comment]
[v2.5](https://docs.snipaste.com/zh-cn/changelog?id=v25) 专业版已支持
