### ISSUE TITLE
Color picker in snipaste is giving darkened color reading

### ISSUE THREAD

**Issue by escottalexander** [Snipaste/feedback#1925]
When using Snipaste to select the color, the RGB or HEX color showed by snipaste is not the same as the actual color on the screen. Here is a video to demonstrate:
https://www.loom.com/share/3d319b1370474143a2ebe256e9b41194

App version:
Platform: Microsoft Store / Windows Desktop / macOS
Windows Desktop
![image](https://user-images.githubusercontent.com/22101475/126806179-d4e2f350-0580-4c6e-a412-6a3394fd0eea.png)

**Comment by liulex** [comment]
It's related to the ICC Profile of your monitor: https://pcmonitors.info/articles/using-icc-profiles-in-windows/
For the moment Snipaste uses sRGB, so if your monitor's color profile is not sRGB, the color values would not match.

**Comment by escottalexander** [comment]
You are correct. Thank you.
