### ISSUE TITLE
图片标注功能中添加放大镜的功能

### ISSUE THREAD

**Issue by ltd920678778** [Snipaste/feedback#193]
希望能添加在截图后的截图标注中加入一个放大镜的功能, 能指定放大局部. 
想问一下Mac版......
谢谢!

**Comment by GregAMO** [comment]
@ltd920678778 放大哪里呢，
目前 按 ALT 可以在
截图或者贴图区域内呈现放大镜
（内置快捷键列表第一条……）

**Comment by ltd920678778** [comment]
就是类似某些手机图片标注app中的局部放大的一个功能

________________________________


发件人： GregAMO<mailto:notifications@github.com>
发送时间： 2016-10-24 19:43
收件人： liulex/Snipaste-Feedback<mailto:Snipaste-Feedback@noreply.github.com>
抄送： lee<mailto:ltd111118@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题： Re: [liulex/Snipaste-Feedback] 图片标注功能中添加放大镜的功能 (#193)

@ltd920678778<https://github.com/ltd920678778> 放大哪里呢，
目前 按 ALT 可以在
截图或者贴图区域内呈现放大镜
（内置快捷键列表第一条……）
