### ISSUE TITLE
请求把这个功能【[专业版] 支持带边框输出图像，并可以指定边框颜色和宽度 #197】增加扩展到免费版本，谢谢 

### ISSUE THREAD

**Issue by HeliusHao** [Snipaste/feedback#1930]
请求把这个功能【[专业版] 支持带边框输出图像，并可以指定边框颜色和宽度 #197】增加扩展到免费版本，谢谢

**Comment by Geeyun-JY3** [comment]
至少有言在先……：https://docs.snipaste.com/zh-cn/pro?id=专业版
> 从 2.0 开始，Snipaste 免费版将只提供缺陷修复，基本不再提供新功能，后续开发的新功能都只加入到专业版

**Comment by HeliusHao** [comment]
我在等 桌面版，也想花钱购买，但是您这边不出桌面版啊
桌面版限制激活三台设备，但可以在不同平台的设备上激活，支持反激活



***@***.***
 
发件人： Geeyun-JY3
发送时间： 2021-07-30 15:35
收件人： Snipaste/feedback
抄送： Helius; Author
主题： Re: [Snipaste/feedback] 请求把这个功能【[专业版] 支持带边框输出图像，并可以指定边框颜色和宽度 #197】增加扩展到免费版本，谢谢 (#1930)
至少有言在先……：https://docs.snipaste.com/zh-cn/pro?id=专业版
从 2.0 开始，Snipaste 免费版将只提供缺陷修复，基本不再提供新功能，后续开发的新功能都只加入到专业版

**Comment by liulex** [comment]
抱歉，目前没有计划把任何专业版功能放到免费版。
