### ISSUE TITLE
打不开，完全启动不了软件

### ISSUE THREAD

**Issue by Kepler2020** [Snipaste/feedback#1931]
之前一直在用，昨天突然发现打不开了。具体就是，点图标/启动/快捷方式，就只会光标旁边转个圈，状态栏没有任何反应，软件启动失败，按快捷键也没有用。

软件是从微软商店下载的，重新卸载安装了没有用。试过官网下载，32位和64位都下载试了，也都打开没反应，完全没东西出来。

软件版本：2.6
运行平台：微软商店 和 Windows 桌面

**Comment by liulex** [comment]
请问官网下载的版本，软件目录下的 crashes 文件夹里面有文件吗？

**Comment by liulex** [comment]
请问能否发个邮件到 <snipaste.app@gmail..com>，帮忙测试一下修复版？

**Comment by liulex** [comment]
已在 Snipaste 2.6.4 Beta 修复，商店版还需等两天。

**Comment by Kepler2020** [comment]
> 请问能否发个邮件到 [snipaste.app@gmail.com](mailto:snipaste.app@gmail.com)，帮忙测试一下修复版？

太惊喜了，这么快就给了回应。已经发了邮件了~

**Comment by Kepler2020** [comment]
> 请问官网下载的版本，软件目录下的 crashes 文件夹里面有文件吗？

没有这个

> 请问官网下载的版本，软件目录下的 crashes 文件夹里面有文件吗？

刚刚看了一下，没有这个文件夹

**Comment by Kepler2020** [comment]
> 请问官网下载的版本，软件目录下的 crashes 文件夹里面有文件吗？

刚刚官网重新下载了一下，可以用了。这个文件夹里没有文件

**Comment by Kepler2020** [comment]
> 已在 Snipaste 2.6.4 Beta 修复，商店版还需等两天。

收到更新了，可以用了，感谢！
