### ISSUE TITLE
自定义颜色选择框无法聚焦 & Lyrics致使窗口侦测功能失效

### ISSUE THREAD

**Issue by Haleclipse** [Snipaste/feedback#1932]
第一个问题，系统版本macOS10.15.7 选择自定义颜色的时候，颜色选择框一闪而过，确实是打开状态，但无法选择颜色，只能按esc退出颜色选择状态
![image](https://user-images.githubusercontent.com/15519695/127739223-b7d8b4a4-c736-4a05-9d1c-d18368e3a546.png)
第二个问题，系统版本macOS10.15.7 一直记得像关于本机窗口是可以自动侦测到窗口的，但是最近发现突然不行了，以为是新版本的问题回退去年的2.5.5Beta发现也不行，一顿折腾之后发现是LyricsX这个软件打开导致的问题，关掉以后窗口侦测就正常了，搜索了一下在Lyrics的issue下有人提过同样的问题 https://github.com/ddddxxx/LyricsX/issues/362

软件版本：2.6.0-Beta / 2.5.5 Beta
运行平台： / macOS

**Comment by liulex** [comment]
谢谢反馈，2.6.4. Beta 应已修复。
