### ISSUE TITLE
贴图消失

### ISSUE THREAD

**Issue by olunju** [Snipaste/feedback#1936]
偶然事件，返回桌面，再贴一张图都无法使其显示，但当我关闭某个软件后它又神奇的出现了

**Comment by olunju** [comment]
多次出现，最新的专业版，在工作时贴图变为不可见，返回桌面，按 Win + E 打开资源管理器就会重新出现

**Comment by liulex** [comment]
专业版有触发角功能，请了解一下：
![image](https://user-images.githubusercontent.com/2010459/133635206-923c1254-1606-4c1a-9394-fb395ff666c9.png)
