### ISSUE TITLE
什么时候能出长截图 这个功能？

### ISSUE THREAD

**Issue by muzili1** [Snipaste/feedback#1938]

**Comment by kuangtengfei** [comment]
同求，现在截长图只能通过其他软件，很不方便

**Comment by kuangtengfei** [comment]
同问，现在截长图得通过其他软件，很不方便

**Comment by rc9vw1** [comment]
同问，现在截长图得通过其他软件，很不方便

**Comment by timk-lalala** [comment]
同有需求

**Comment by du-MMY** [comment]
很需要，已+1

**Comment by Tensor1024** [comment]
@timk-lalala chrome自带截图工具
F12 左半边屏幕的三个纵排的点（更多选项）里面有获取网页完整截屏的功能

**Comment by Geeyun-JY3** [comment]
#19

**Comment by JohnCanny52** [comment]
@Geeyun-JY3 又看到这个需求了😂

**Comment by JohnCanny52** [comment]
@Geeyun-JY3 还记得上次看到这个issue的时候，还是在上次

**Comment by kmcbest** [comment]
dup #19

**Comment by stevenzhu25** [comment]
Duplicate of #19

**Comment by kzhiquan** [comment]
推荐Mac上的支持长截图的软件Picsee，https://picsee.chitaner.com/ 
实测强于Xnip，有需要的小伙伴可自行下载。

**Comment by Joker-jiajiahui** [comment]
希望增加长截图的功能，每次都要去qq截图
Hope to increase the function of long screenshots, every time to QQ screenshots
