### ISSUE TITLE
macOS 2.6.5 版本尖头和折线合并有必要嘛?

### ISSUE THREAD

**Issue by comesoon** [Snipaste/feedback#1939]
RT, 新版本里把尖头和折线合并到一起, 感觉反倒不便于使用了, 可否恢复单用, 或者增加个合并设置选项?

**Comment by Cocopala** [comment]
同求, 能不能在设置里自定义设置一个选项把这两个分开, 使用场景是不同的, 经常有组合使用的需求
请给一个选项让用户能够分开它们吧

**Comment by liulex** [comment]
按 <kbd>Tab</kbd> 就可以切换了，不比原来更方便？

**Comment by Cocopala** [comment]
> 按 Tab 就可以切换了，不比原来更方便？

ok, 解决了, 没有说明确实不知道.
谢谢

**Comment by comesoon** [comment]
> 按 Tab 就可以切换了，不比原来更方便？

纯鼠标使用场景下, 直接可选尖头和需要使用快捷键进行切换, 到底哪个更方便?🤔️

**Comment by zxr615** [comment]
合并起来很不方便

**Comment by liulex** [comment]
已成定局，不会撤销，如有需要请停留在旧版不再更新。

**Comment by hhstore** [comment]
- 为何固执的一定要合并这2个按钮哇? 
- 既然有这么多用户跑过来留言, 说明有更多人, 没有上来反馈. 
- 一个 app 的交互变动, 好的设计, 不会有人来讨论, 坏的设计, 才会. 

> ps: 

- 苹果出了 touchbar, 出过蝴蝶键盘, 弃用过 磁吸充电头.
- 但是, 苹果, 也知道`知错就改`, 重新恢复旧的设计哇. 
- 改动不合理, 恢复就好哇. 或者保留2个设计.
- 为何要跟用户对抗? 收益是什么?
