### ISSUE TITLE
New annotate tool: arrow with text

### ISSUE THREAD

**Issue by andrzejolszak** [Snipaste/feedback#1943]
I often need to annotate an element on a screenshot with an arrow pointing to it and a short text at the beginning of the arrow (see the attached screenshot for an example of what I mean).

It would be great if there was a single tool to do this. This could work by placing the arrow first, and as soon as it is placed a text box is created and the mouse focus is moved to it automatically so that you can start typing. 

![image](https://user-images.githubusercontent.com/27814974/128515026-7ccc4c05-c3cb-4cd3-a52d-3241533e9279.png)

**Comment by liulex** [comment]
Thanks for your suggestion, but I would prefer separate different types of annoations for flexibility and simplication.
