### ISSUE TITLE
[bug] Windows 11 商店版频繁自己退出

### ISSUE THREAD

**Issue by northword** [Snipaste/feedback#1945]
Windows11下，snipaste频繁自己退出，手动运行他后一段时间他自己又没了（确定没有手动退出过，应该没有其他软件会导致他退出，因为升级Windows11前后无新加软件）
且在win11下，手动运行后无法立即使用快捷键截图，必须点开snipaste托盘右键菜单一次后，才能使用快捷键。

App version:
Platform: Microsoft Store 2.6.5 2021.08.04
中间升级过一次，现在是商店的最新版本，都有同样情况

日志：
见下附件，7月30日升级Windows11 beta 通道build22000.100，目前是build22000.120

[splog.txt](https://github.com/Snipaste/feedback/files/6949205/splog.txt)

**Comment by liulex** [comment]
谢谢反馈，可否联系 snipaste.app@gmail.com 帮忙测试一下？

**Comment by northword** [comment]
切换为桌面版后，未出现过上述情况。
同时发现，Windows 商店中的 `EarTrumpet` 软件也存在类似的自己退出的情况，因此我推测这是 Windows 11 的问题而非 Snipaste 的问题。
