### ISSUE TITLE
无法选择以管理员身份开机自动启动

### ISSUE THREAD

**Issue by Xdynix** [Snipaste/feedback#1946]
之前一直设置为开机后以管理员身份自动启动。但是前几天Snipaste（可能是Snipaste自动更新后）突然提示无法设置开机自动启动，并退出。重新手动打开后，`开机启动`可以正常勾选并有效，但是`以管理员身份`无法勾选。即使手动以管理员身份启动Snipaste后也是。

软件版本：Snipaste专业版 2.6.5
运行平台：微软商店

[splog.txt](https://github.com/Snipaste/feedback/files/6950456/splog.txt)

**Comment by liulex** [comment]
检查这里 Snipaste 的状态：
![image](https://user-images.githubusercontent.com/2010459/128626443-4fa29134-6df6-48fe-b736-55729367b411.png)

**Comment by Xdynix** [comment]
![Snipaste_2021-08-08_01-47-55](https://user-images.githubusercontent.com/14145832/128626489-6e8b05eb-6011-4b39-b66b-42df93d6f1a9.png)

**Comment by liulex** [comment]
@Xdynix 那里关掉再重新打开，再试试勾选 `以管理员身份`。

**Comment by Xdynix** [comment]
@liulex 确实就能成功勾选了，非常感谢帮忙！

**Comment by Xdynix** [comment]
刚才发送的log里其实漏了一行，应该是相关的：

```
[2021-08-08 01:48:56.978] [W] AppExecutionAlias is invalid.
```

**Comment by liulex** [comment]
已更新到 [故障排除](https://docs.snipaste.com/zh-cn/troubleshooting)。
