### ISSUE TITLE
如何下载历史版本，现在想回退到2.6  版本 最近两个新版本都有问题

### ISSUE THREAD

**Issue by wgyfyzz** [Snipaste/feedback#1952]

**Comment by liulex** [comment]
https://bitbucket.org/liule/snipaste/downloads/

**Comment by FieldRobot5** [comment]
https://bitbucket.org/liule/snipaste/downloads/
There is nothing in this download address!

**Comment by Geeyun-JY3** [comment]
@FieldRobot5 https://github.com/Snipaste/feedback/issues/3364#issuecomment-3044795376
