### ISSUE TITLE
Mac端外接显示器后，只能截取笔记本屏幕的内容

### ISSUE THREAD

**Issue by Jinming-D** [Snipaste/feedback#1953]
软件版本：2.6.5 beta
运行平台：MacOS Big Sur
问题：更新到最新版本后经常出现无法截取外接屏内容的问题，遇到问题后重启就可以了，但是出现频率有点高

**Comment by Git-kanata** [comment]
复议，更新到最新后，只要是先运行了app，后插副屏，就无法在副屏上截图，需要手动重启。

**Comment by dixdiydiz** [comment]
+1，每次都要重启app才行，一锁屏，就不行了。
