### ISSUE TITLE
贴图后右键旋转等功能不能用，但快捷键可以用

### ISSUE THREAD

**Issue by git10135405** [Snipaste/feedback#1956]
贴图后右键旋转等功能不能用，但快捷键可以用
![image](https://user-images.githubusercontent.com/35558611/129144207-e006d324-9434-40f0-8255-255e65151f30.png)

软件版本：1.16.2
运行平台：Windows 桌面

**Comment by Geeyun-JY3** [comment]
v1 不更新了鸭

**Comment by git10135405** [comment]
> v1 不更新了鸭：https://docs.snipaste.com/zh-cn/pro

新版，个人版bate也是不行呀！！

**Comment by Geeyun-JY3** [comment]
等等，你截图这是旋转的功能的入口吗？

**Comment by git10135405** [comment]
> 等等，你截图展示的是旋转等功能的入口吗？

截图后，贴图，右击贴图菜单后面有个分辨率好像是，里面有旋转…

**Comment by Geeyun-JY3** [comment]
> 截图后，贴图，右击贴图菜单后面有个分辨率好像是，里面有旋转…

你确定这里以前可以旋转贴图吗？旋转的入口在上面。
![image](https://user-images.githubusercontent.com/49396421/130341363-8ececcb6-ad53-4c43-89e7-c268a6c98bde.png)

**Comment by git10135405** [comment]
> > 截图后，贴图，右击贴图菜单后面有个分辨率好像是，里面有旋转…
> 
> 你确定这里以前可以旋转贴图吗？旋转的入口在上面。
> ![image](https://user-images.githubusercontent.com/49396421/130341363-8ececcb6-ad53-4c43-89e7-c268a6c98bde.png)

是我搞错了 抱歉！
