### ISSUE TITLE
卸载后存在残留

### ISSUE THREAD

**Issue by Riessarius** [Snipaste/feedback#1957]
在卸载了 Snipaste 之后，在 Windows 设置里“任务栏角溢出”处仍然能看到 snipaste.exe 条目。

软件版本：
运行平台：Windows 11 / 微软商店

**Comment by stevenzhu25** [comment]
@Riessarius 重启试一试？

**Comment by liulex** [comment]
那是系统管理的，没任何方式可以手动清除。
