### ISSUE TITLE
截图马赛克

### ISSUE THREAD

**Issue by rom1c77** [Snipaste/feedback#1959]
截图为什么不能出一马赛克功能&顺序标记功能
1. 马赛克 
2. 截图标记顺序 不然只能手写1  2 3

**Comment by Geeyun-JY3** [comment]
不是都有吗：
1. 截完图进入编辑状态弹出的工具栏就有：
![image](https://user-images.githubusercontent.com/49396421/130006641-88a95dd5-bf72-47ed-8cc6-57545160a76e.png)
2. 序号标注需要专业版：https://github.com/Snipaste/feedback/issues/227#issuecomment-628125908

**Comment by rom1c77** [comment]
好吧，序号原来是专业版的功能 太可惜了 😭
