### ISSUE TITLE
贴图无法使用鼠标进行操作（非穿透原因）

### ISSUE THREAD

**Issue by zychen** [Snipaste/feedback#1960]
在贴完图后，鼠标不能对贴图进行操作，如：移动贴图位置、在贴图上右键唤出菜单进行对应操作，但并非是穿透的原因，因为鼠标点击贴图，贴图本身是获得了窗口焦点的（贴图四周有淡蓝色阴影，如果是穿透模式，是无法获得焦点的），如下图：
![image](https://user-images.githubusercontent.com/5674514/129899940-61175906-22d5-4557-9846-c12f7180efe3.png)

如果鼠标点击非贴图的其他区域，贴图的贴图的窗口焦点会失去（贴图四周窗口阴影会变成灰色），如下图：
![image](https://user-images.githubusercontent.com/5674514/129900196-a700b3e4-b128-4aed-9ab4-2b03ab0b63ee.png)

虽然无法通过鼠标右键点击贴出唤出右键菜单，但可以通过鼠标点击贴图，使贴图处在选中的状态，然后使用键盘上菜单键，唤出贴图的菜单，如下图，然后鼠标选择菜单上对应的功能进行操作，而且使用键盘上的上下左右键进行贴图的移动。
![image](https://user-images.githubusercontent.com/5674514/129900398-449cec69-1082-4af5-b727-6cf60336a975.png)

重新下载版本，解压，还是有同样的问题。

软件版本：
运行平台：windows 7 专业版 64位，Snipaste：v2.6.6-Beta 64位，32位，v2.5.6-Beta 64位，32位，还有其他历史版本。都是有同样的问题。

**Comment by liulex** [comment]
这是系统问题，某个系统设置相关。我没有重现环境，没办法处理。
