### ISSUE TITLE
没有圆形填充，只有矩形填充，需要重启软件才会出现。

### ISSUE THREAD

**Issue by kofzhanganguo** [Snipaste/feedback#1961]
没有圆形填充，只有矩形填充，软件需要定时重新启动后才会有圆形填充工具。
![image](https://user-images.githubusercontent.com/32073931/130222504-23b18665-794c-41f6-9656-23e8667a86e0.png)

软件版本：
运行平台： Windows 10 桌面版

![image](https://user-images.githubusercontent.com/32073931/130222674-a699efef-d78b-46f7-9def-a2ae8f098fe9.png)
这是重启之后才会出现圆形填充工具，而过一会儿这个工具就会消失，截图时没有这个选项了。

**Comment by liulex** [comment]
嗯，这是个 bug...
![image](https://user-images.githubusercontent.com/2010459/130229401-dae49097-2254-4da6-85f5-9d7c305e2195.png)

**Comment by kofzhanganguo** [comment]
那出现这种情况，请下个版本取消支持椭圆形的形状的填充，不然引起免费用户的误解，还以为是软件有BUG，原来是专业版才有此功能。
