### ISSUE TITLE
windows在snipaste没启动的情况下，命令行执行Snipaste.exe snip只是启动程序，不会进入截图，需要再执行一次才能进入截图

### ISSUE THREAD

**Issue by i7guokui** [Snipaste/feedback#1962]
windows在snipaste没启动的情况下，命令行执行Snipaste.exe snip只是启动程序，不会进入截图，需要再执行一次才能进入截图

软件版本：
运行平台：Windows 桌面

**Comment by liulex** [comment]
预期行为，snipaste 启动就需要一段时间，等启动完再执行命令行参数没什么意义，所以建议保持后台运行。
