### ISSUE TITLE
放大镜功能请求允许自定义快捷键

### ISSUE THREAD

**Issue by miyouzi** [Snipaste/feedback#1963]
当截图快捷键包含 Alt 时，会与放大镜冲突（把放大镜截进来）。

单键快捷键容易和其他软件冲突，Alt 组合键个人觉得是个比较舒服的键位，放大镜的键位冲突问题希望能让用户自行定夺。

**Comment by liulex** [comment]
下个版本会防止放大镜出现在截图中。
