### ISSUE TITLE
建议将按住Ctrl拖拽识别为连续折线，画单条线段的操作并不需要按Ctrl

### ISSUE THREAD

**Issue by mtcw** [Snipaste/feedback#1964]
按住CTRL原地单击极易因为鼠标轻微移动而被识别成画单条线段的操作，而单条线段的操作并不需要按Ctrl，所以建议将按住Ctrl的拖拽操作识别为连续折线操作，统一操作&避免错误操作，一举两得♂

软件版本：PRO x64 2.6.6 (2021.08.14)
运行平台：微软商店

我真可爱!

**Comment by liulex** [comment]
画折线也不需要按 Ctrl 啊。

**Comment by mtcw** [comment]
> 画折线也不需要按 Ctrl 啊。

哦! 我果然真可爱!
