### ISSUE TITLE
在一些窗口无法调用截图功能，例如任务管理器

### ISSUE THREAD

**Issue by Git0503** [Snipaste/feedback#1966]
在某些窗口处于激活状态时，无法调用截图功能，例如打开任务管理器时，无法调用截图功能

软件版本：
运行平台：Windows 桌面

**Comment by Git0503** [comment]
没开置顶，但用管理员权限运行就OK了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Snipaste/feedback"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月26日(星期四) 凌晨0:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Snipaste/feedback] 在一些窗口无法调用截图功能，例如任务管理器 (#1966)





 
Snipaste的截屏画面本质也是一个窗口, 该窗口会被部分其他窗口遮挡, 例如开起置顶功能的任务管理器窗口, 这些置顶窗口画面通常可以正常捕获, 但覆盖在Snipaste之上的窗口会影响到截图操作, 可尝试将这些遮盖住截图画面的窗口移开或最小化。
 另外UAC机制限制没有管理员权限的程序无法获得部分窗口的图像, 遇到这种情况可以尝试使用管理员权限运行Snipaste或降低UAC级别(不推荐)。也可能会有些特殊的窗口受API限制无法捕获 (这个可以有, 但是我没见过, 也不确定是否存在)
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liulex** [comment]
https://docs.snipaste.com/zh-cn/troubleshooting
