### ISSUE TITLE
截屏时加入比例快速选择

### ISSUE THREAD

**Issue by crestin** [Snipaste/feedback#1967]
截屏时可以选择比例，比如 1:1  3:2 4:3
很多时候需要符合比例的图形作为缩略图，手动拖拽截屏无法准确完成，还得二次处理。

![image](https://user-images.githubusercontent.com/5337065/131209484-a2e96fd1-ad48-44cd-a9a5-f89f5aaebeb7.png)

**Comment by liulex** [comment]
专业版有。
