### ISSUE TITLE
增加放大镜的触发区域

### ISSUE THREAD

**Issue by metthewzy** [Snipaste/feedback#1969]
因为经常需要精细调节截图的位置，一直需要用放大镜。问题是放大镜只有在鼠标非常接近截图边缘的像素的时候才会自动触发，而且一旦鼠标移出现有范围就会消失。
希望能适当增加放大镜自动触发的距离，在当前截图框外也能一定距离触发，如果能自定义触发的像素距离就更好了，谢谢！

**Comment by liulex** [comment]
截图时按住 <kbd>Alt</kbd> 可以始终显示放大镜。
