### ISSUE TITLE
【需求】可以添加截图时生成一个带颜色的边吗？比如1个像素红色

### ISSUE THREAD

**Issue by snsnsjsn** [Snipaste/feedback#197]
像 snagit里面有个设置border

这样截图后自带 边框 ，粘贴到其它地方非常醒目

![image](https://cloud.githubusercontent.com/assets/11435527/19757570/39ac4c48-9c56-11e6-9682-0adbf4e40482.png)
像这样截图后就自带边框

![image](https://cloud.githubusercontent.com/assets/11435527/19757629/7a1e37d2-9c56-11e6-980a-c6f0ca938846.png)

**Comment by EMLVIRUS** [comment]
支持这个请求 @liulex

**Comment by liulex** [comment]
以后交给插件系统，包括添加外围阴影。

**Comment by snsnsjsn** [comment]
感谢回复。

我的意思不是截完图后，再打开一个编辑器，再应用一个边框样式，这样就失去截图的效率了。

我的意思是想 snagit 那样，开启一个开关，截图，粘贴。

粘贴到空白文档或编辑器里面，就自带醒目边框。

**Comment by gongway** [comment]
支持，尤其是白色底色的文字类截图粘贴到白色背景的文档中，看不出截图边界。如果能够设置让截图自动添加边框阴影就很方便。

**Comment by yghj0413** [comment]
除了可以设置带颜色的边框外，可以考虑增加带“撕边”的选择。

**Comment by neilsustc** [comment]
软件很好用 👍 
插件系统有什么进展吗，期待外围阴影

**Comment by printempw** [comment]
是啊，我也希望有像 macOS 那样带阴影的窗口截图

**Comment by gongway** [comment]
不太稳定，第一次启动时间比较久，长时间不退出的话，会莫名其妙的崩溃。

2017-03-28 15:31 GMT+08:00 Yu Zhang <notifications@github.com>:

**Comment by GregAMO** [comment]
@gongway 
1 「反应时间过长」可参见 #373 尝试调高进程优先级以解决
2 「长时间不退出后崩溃」 相关讨论参见 #288 ，欢迎补充说明
3 请不要在无关主题下添加评论
4 如果一定要使用邮件快捷回复，请删去无关引用内容

**Comment by greyli** [comment]
+1

**Comment by copriwolf** [comment]
原生截图的边缘阴影 +1

**Comment by fuxkak** [comment]
原生截图的边缘阴影 +2

**Comment by PentiumRabbit** [comment]
原生截图的边缘阴影 是个挺好的功能,期望可以有

**Comment by luantu** [comment]
原生截图的边缘阴影 +3

**Comment by snsnsjsn** [comment]
我现在只用snipaste做贴图用了。
截图应该用sharex神器。
截图后可以自动加边框，编辑，添加文本，符号序号，甚至自动上传到七牛网或者又拍云图床，把链接贴到剪切板里面。再结合clipcache就可以方便从粘贴板里面拷出来。
我截个图给大家参考

![image](https://user-images.githubusercontent.com/11435527/46601825-fa16f280-cb20-11e8-9259-1cb3769b2c2f.png)

**Comment by neilsustc** [comment]
![image](https://user-images.githubusercontent.com/7588612/46611774-a5667e00-cb06-11e8-8f45-c629b8de29a0.png)

亲测效果不错，就是需要稍微设置下，截图完加效果（image effects），然后是 Add>Filter>Shadow

**Comment by liulex** [comment]
Snipaste 2.5 专业版已支持。

**Comment by HeliusHao** [comment]
请求把这个功能增加扩展到免费版本，谢谢  【[专业版] 支持带边框输出图像，并可以指定边框颜色和宽度 #197】
