### ISSUE TITLE
常常用截图的方式给新人作教程用，能否像ps一般保存新后缀方便时候打开重新编辑文本等元素

### ISSUE THREAD

**Issue by yimingriyue** [Snipaste/feedback#1971]
矩形、折线、画笔、文本等这些元素各自预存在一个文件格式里，加个编辑器的功能方便重新修改截图。个人而言，不习惯用xmind这类思维导图，大纲罢了。

**Comment by kasusa** [comment]
我也希望有这个功能。（把图片保存成可再次编辑的格式）
不过实际上不需要加编辑器呀。
只要作为贴图打开，按一下空格就可以编辑了。

**Comment by Geeyun-JY3** [comment]
重复：#1654

不知 [回放截图记录（回溯截屏历史）](https://docs.snipaste.com/zh-cn/getting-started?id=%e5%9b%9e%e6%94%be%e6%88%aa%e5%9b%be%e8%ae%b0%e5%bd%95) 能否暂时解决相关需求。

**Comment by Geeyun-JY3** [comment]
Duplicate of #1654
