### ISSUE TITLE
如何双击贴图复制到剪贴板

### ISSUE THREAD

**Issue by kevin2fly** [Snipaste/feedback#1973]
使用的是pro版本，每次都要手工复制，才能把屏幕上的贴图复制到剪贴板。双击这个贴图，贴图会关闭但不会被复制到剪切板。
请问怎么设置，才能双击贴图就能复制到剪贴板然后贴图还能关闭呢。

**Comment by liulex** [comment]
抱歉，没有“复制并关闭贴图”这个动作，目前也没有收到其他用户有此需求，所以暂不考虑添加。
