### ISSUE TITLE
希望可以增加便笺功能

### ISSUE THREAD

**Issue by lsl6958** [Snipaste/feedback#1975]
# 便笺功能
1. 以截图的方式产生便笺，随时在任何界面都可以生成便笺
2. 便笺的背景需要是纯色的背景，当然可以调整背景颜色就更好了
3. 便笺的大小希望可以通过右键进行重新调整，这样当时新开的便笺记不下内容时就可以调整大小
4. 便笺的顶部可以有一个小的悬浮框让用户自己指定便笺的名称，用户没有自己定义便笺名称时就使用当天的日期自动命名
5. 每个用户一天也不需要很多的便笺，所以如何将以前的便笺调出贴到屏幕上，并且还可以继续增加和修改也是一个问题
6. 便笺的编辑功能里面基础的功能，比如复选框之类的

以上是我个人的一些想法，希望开发者有时间，有精力可以实现。我想这个功能可以为这款软件增加更多的市场竞争力，赢得更多的用户

**Comment by liulex** [comment]
为什么不用专门的便笺软件呢？
