### ISSUE TITLE
您必须先启用 UAC 才能购买

### ISSUE THREAD

**Issue by yhxsome** [Snipaste/feedback#1977]
解锁专业版-->购买-->windows 提示：
![image](https://user-images.githubusercontent.com/72911235/133410917-8adc9d29-04c3-4963-900e-15506a751a32.png)

软件版本：2.6.6
运行平台：微软商店
系统：win10 家庭版

**Comment by yhxsome** [comment]
实际 uac 是启用的
![image](https://user-images.githubusercontent.com/72911235/133411472-5460aed1-9e87-419c-9cd8-7f38885b4773.png)

**Comment by liulex** [comment]
这个通知的含义是购买时不能以管理员身份运行 Snipaste. 如果你是登录的管理员账户，即使开启了 UAC 也依然无法以非管理员身份运行 Snipaste 的。

请登录普通权限的系统账户进行购买，或通过[经销商](https://zh.snipaste.com/resellers.html)购买。
