### ISSUE TITLE
开发出来截取才图的功能

### ISSUE THREAD

**Issue by condorshawn** [Snipaste/feedback#1978]
很喜欢这软件，自己发现自己有一些截取长图片的需求
然后搜了下其他软件，发现竟然还真有
这个软已经用了四年了，win和mac都在用
希望可以开发出来更好用的“截取长图片”功能

**Comment by liulex** [comment]
#19

**Comment by condorshawn** [comment]
大佬你的回答在16年这都几年了还没有开发出来长截图吗
