### ISSUE TITLE
请求截图的边缘检测

### ISSUE THREAD

**Issue by Csrayz** [Snipaste/feedback#1979]
截屏时的自动检测界面元素很好用，但是对于web页面就无能为力了，大部分时候都需要对预览框进行第二次修正。
能否支持画面的边缘检测功能（类似文档扫描自动框选文档一样）。如图：

![Snipaste_2021-09-16_19-45-49](https://user-images.githubusercontent.com/33659823/133606448-5d376d39-7afb-4fc1-af74-d6c6f49b89f6.png)

使得web中能够自动框选部分方正的表格、边框等，最终效果就类似于自动检测界面元素：

![Snipaste_2021-09-16_19-47-43](https://user-images.githubusercontent.com/33659823/133606782-50df0579-d630-4f2f-b22f-02bae745cd58.png)

**Comment by liulex** [comment]
[截图时无法自动选取浏览器窗口的页面元素](https://docs.snipaste.com/zh-cn/troubleshooting?id=%e6%88%aa%e5%9b%be%e6%97%b6%e6%97%a0%e6%b3%95%e8%87%aa%e5%8a%a8%e9%80%89%e5%8f%96%e6%b5%8f%e8%a7%88%e5%99%a8%e7%aa%97%e5%8f%a3%e7%9a%84%e9%a1%b5%e9%9d%a2%e5%85%83%e7%b4%a0)
