### ISSUE TITLE
【需求】可以在截图时锁定图片比例吗？

### ISSUE THREAD

**Issue by gaollg** [Snipaste/feedback#198]
### 使用场景如下：
- 微信公众号选配图时，图片比例为 900*500
- 在其它工作中，经常需要截取一些正方形图片

**Comment by GregAMO** [comment]
See #28 是一样的吗
> 1.截图时拖出一个区域后， 以100*200格式输入数字 可以将区域大小设置为100*200

目前呢，可以：
1 一张指定大小的贴图，截图 - 界面元素自动选中 - 移动选框
2 有一些 [像素级控制截取区域](https://github.com/liulex/Snipaste-Feedback/wiki/%E5%9F%BA%E7%A1%80%E6%93%8D%E4%BD%9C#%E5%83%8F%E7%B4%A0%E7%BA%A7%E6%8E%A7%E5%88%B6%E6%88%AA%E5%8F%96%E5%8C%BA%E5%9F%9F)
