### ISSUE TITLE
快速的序号标注

### ISSUE THREAD

**Issue by Coming98** [Snipaste/feedback#1989]
在教程中不少截图都是指示性的动作，因此快速好看的序号标注样式应当是需要的，比如我先后点击三个地方，需要有序号（1,2,3），再比如我要先后介绍截图中的三块内容，不仅需要序号，还需要序号+注释的组件

**Comment by Geeyun-JY3** [comment]
为什么不先用一下神奇的搜索呢：#1761

序号标注需要专业版：https://github.com/Snipaste/feedback/issues/227#issuecomment-628125908
