### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Ahuiforever** [Snipaste/feedback#1996]
希望添加新的功能：
1. 可以设置屏蔽该快捷键的程序，比如说正在进行Dota 2游戏中，需要使用F1来定位自己的英雄，这时通常会触发截屏，而这是玩家所不希望的。希望可以指定某个程序内不触发该功能。
2. 希望增加OCR文字识别功能，具体可以参考天若OCR, 使用体验非常舒适。

**Comment by Geeyun-JY3** [comment]
OCR 的事请先善用搜索，提了又提：#188
