### ISSUE TITLE
历史截图回顾功能能复制图片或者保存图片不退出吗，

### ISSUE THREAD

**Issue by Achuan-2** [Snipaste/feedback#1997]
不然要回到上次的浏览位置很麻烦。或者历史截图能自动导出为png图片放在一个文件夹吗，这样更方便回顾

**Comment by liulex** [comment]
这里可以设置复制/保存截图而不退出截屏：
![image](https://user-images.githubusercontent.com/2010459/141688091-21c5c518-7b12-452c-9f16-8209c7648fee.png)
