### ISSUE TITLE
Super brightness/contrast on some pages during capture

### ISSUE THREAD

**Issue by bebotette** [Snipaste/feedback#2001]
Some sites (not all sites) that I've come across have this issue that when I'm about the start capturing, the focus area becomes too bright and washed out and too strong contrast. For example, slack web app, or try this website: http://timlai.org. I couldn't remember other websites that have the same issue.

Other notes:
-so far, I've only seen this on websites. My browser is vivaldi. But I also tried on chrome and opera and same issue on these specific sites.
-when the page is still in loading progress, this issue doesn't happen. This only happens when the site is almost or fully loaded already.
-I haven't encountered this issue in other apps like explorer.
-my version of windows 10 is 21H2 10944.1288 64bit
-see attached screenshots (one is using snipaste, one is using other screenshot tool)

App version: 2.6.6 (2021.08.14)
Platform: Microsoft Store
![other screenshot tool](https://user-images.githubusercontent.com/5653117/138014853-ffb5977b-1a91-4466-8707-bc19c7cdd68a.png)
![snipaste](https://user-images.githubusercontent.com/5653117/138014857-914a7ca5-273f-478e-902a-825ef15a1145.png)

**Comment by liulex** [comment]
I think you have turn on HDR on your display. Taking HDR screenshot is not supported yet. https://github.com/Snipaste/feedback/issues/1112
