### ISSUE TITLE
macOS上取色器取值有色差

### ISSUE THREAD

**Issue by cooper1x** [Snipaste/feedback#2002]
软件版本：
运行平台 macOS 2.66-Beta2

在微信开发者工具，截图的时候，发现标题栏取色的色值，跟我设置的背景色不一致。
![image](https://user-images.githubusercontent.com/9080789/138040221-559d1c68-82ba-45e6-824b-69d3b6da577b.png)
我设置的是
```CSS
    background: #e34138 !important;
```
但实际取到的颜色是#d24e41。
虽然都是红色，但实际色值有偏差。
另外截图后的图片标题栏背景，跟我实际取色的背景颜色也不一样。
我是MacBook Pro 16寸，外接了一台创维27寸显示器。
我把显示器接口拔掉取色，也是有偏差的。

**Comment by liulex** [comment]
macOS 版 Snipaste 的色值是跟显示器的显示描述文件保持一致的，而你 CSS 和 PS 给出的色值是 sRGB 颜色空间的。

**Comment by cooper1x** [comment]
@liulex liu 能否设置指定Snipaste色值与sRGB保持一致呢？如果是这样的话，取色就不会有问题了。

**Comment by hassanwong** [comment]
我也遇到这个问题了，我们一般取色都是要画图、前端开发之类的，所以肯定不希望有色差。我看作者提问时间是21年，咋23年还有这个问题，难道是我自己需要设置什么吗？

**Comment by GrinZero** [comment]
同样有这个问题，我认为这个issue不应该关闭

**Comment by troy351** [comment]
+1

**Comment by liulex** [comment]
Snipaste 2.10.6
• [Mac] 新选项：可设置取色器的色彩空间，默认为 sRGB

<img width="583" alt="Image" src="https://github.com/user-attachments/assets/cb27861a-f813-4ee3-b749-840389687fd3" />

**Comment by g968948** [comment]
> 但实际取到的颜色是#d24e41。
> 虽然都是红色，但实际色值有偏差。
> 另外截图后的图片标题栏背景，与实际取色的背景颜色也不一样。
> 我是MacBook Pro 16寸，外接了一个创维27寸显示器。
> 我把显示器接口拔掉取色，也是有偏差的。

windows的颜色取色也和实际颜色不符，怎么搞

**Comment by dptr** [comment]
改成srgb色彩空间还是不对

**Comment by k1nz** [comment]
> Snipaste 2.10.6 • [Mac] 新选项：可设置取色器的色彩空间，默认为 sRGB
> 
> <img alt="Image" width="583" src="https://private-user-images.githubusercontent.com/2010459/424767513-cb27861a-f813-4ee3-b749-840389687fd3.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODMwNjkyMTgsIm5iZiI6MTc4MzA2ODkxOCwicGF0aCI6Ii8yMDEwNDU5LzQyNDc2NzUxMy1jYjI3ODYxYS1mODEzLTRlZTMtYjc0OS04NDAzODk2ODdmZDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDcwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA3MDNUMDg1NTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGVlMjhjMzAyYTI3YmQ4NTA3N2I2YWFmMTZiZDQ1ZWJhYWFhMjY3MTE2M2NkMDZiZTc2MjBhZmFiODUzZGQ2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.KYwEuyNOeSgnsP0lHfiJhyoTMY57V1gW1lK2lwsj0mM">

现在mac最新版本 2.11.3 的sRGB色值还是有差别，在web上的颜色 #1677FF 实际取色色值 #1877FF
