### ISSUE TITLE
MAC版本上取色器取值有不准确/有色差

### ISSUE THREAD

**Issue by kwokchikit** [Snipaste/feedback#2004]
PS打开一张网络上的图片，用Snipaste吸取的色值和ps吸取出来的色值不一样。
因为之前我也有一直有用win版的Snipaste并没有这种情况发生。

软件版本：2.6.6-Beta2（2021.08.14）
运行平台：macOS系统
设备：Mac mini

**Comment by liulex** [comment]
dup: #2002
