### ISSUE TITLE
在360极速浏览器和edge浏览器打开的网页中截图 不能自动识别网页的元素

### ISSUE THREAD

**Issue by jigeji** [Snipaste/feedback#2007]
软件版本：
运行平台：微软商店 / Windows 桌面 / macOS

**Comment by liulex** [comment]
[截图时无法自动选取浏览器窗口的页面元素](https://docs.snipaste.com/zh-cn/troubleshooting?id=%e6%88%aa%e5%9b%be%e6%97%b6%e6%97%a0%e6%b3%95%e8%87%aa%e5%8a%a8%e9%80%89%e5%8f%96%e6%b5%8f%e8%a7%88%e5%99%a8%e7%aa%97%e5%8f%a3%e7%9a%84%e9%a1%b5%e9%9d%a2%e5%85%83%e7%b4%a0)

**Comment by Yueasdy** [comment]
> [截图时无法自动选取浏览器窗口的页面元素](https://docs.snipaste.com/zh-cn/troubleshooting?id=%e6%88%aa%e5%9b%be%e6%97%b6%e6%97%a0%e6%b3%95%e8%87%aa%e5%8a%a8%e9%80%89%e5%8f%96%e6%b5%8f%e8%a7%88%e5%99%a8%e7%aa%97%e5%8f%a3%e7%9a%84%e9%a1%b5%e9%9d%a2%e5%85%83%e7%b4%a0)

感谢答复，我用chrome的办法在edge上操作了，也可以依样画葫芦操作edge，现在我的edge可以识别网页元素了。可以修改下故障排除。
![image](https://user-images.githubusercontent.com/22210602/141615345-cd8e1912-2cff-42b8-a4ec-662de109583b.png)

**Comment by liulex** [comment]
@Yueasdy 谢谢，已更新。

**Comment by Yueasdy** [comment]
> @Yueasdy 谢谢，已更新。

抱歉，经过两三天的使用，
`--force-renderer-accessibility`命令针对edge无法生效，不过`chrome://accessibility`命令可以在edge上生效。
此外，chrome以上两条命令都可以正常使用。

我记得之前元素识别是不需要这样操作就可以使用的，是edge/chrome对于开发者有权限改动吗，谢谢。

**Comment by Yueasdy** [comment]
![image](https://user-images.githubusercontent.com/22210602/142332983-90bc7094-cd6d-4dc6-a6da-b855e84338d6.png)
又测试了几天，`--force-renderer-accessibility`命令没有成功执行的原因是用户权限没给“完全控制”
解决方法：
1. 我给了“以管理员模式启动”(体验当然很差，会弹出用户账户控制、降低亮度)；
2. 如上图，我给了everyone这个用户“完全控制”的权限，不会弹用户账户控制弹窗，也可以启动`--force-renderer-accessibility`命令；

此外，修改了以上权限后，开始菜单快捷方式和任务栏快捷方式需要重新设置，否则以上改变对之前的快捷方式无效。

辛苦！
