### ISSUE TITLE
ESC与微软拼音输入法候选词框冲突

### ISSUE THREAD

**Issue by AnLazyOtter** [Snipaste/feedback#2008]
软件版本：2.6.6
运行平台：微软商店  Windows 11 家庭版 insider preview 22471
问题：在截图期间，使用文本工具，在微软拼音输入法出现候选词框时按下esc意图取消当前键入，会导致直接退出文本编辑。
期望：当显示候选词框时，第一次按下esc时触发微软拼音输入法取消输入文本的快捷键，第二次按下ESC才退出文本编辑。
![image](https://user-images.githubusercontent.com/40395191/138591496-70f6be74-1c86-442b-b9f5-d7c560e1740b.png)

**Comment by liulex** [comment]
Windows 10 上未能复现。
如果 Windows 11 上有问题，那也是微软输入法的问题。

**Comment by liulex** [comment]
Hmm.. 贴图上没复现，截图上复现了。

**Comment by AnLazyOtter** [comment]
> Hmm.. 贴图上没复现，截图上复现了。

这个标记为已完成，是指下个版本即将修复嘛？

**Comment by liulex** [comment]
是的，并且近几天就发布了。
