### ISSUE TITLE
可以设置粘贴截图的时候压缩图片大小么

### ISSUE THREAD

**Issue by zhengbli** [Snipaste/feedback#201]
因为是4K屏幕的缘故，有时候一小块截图文件大小就好几M，复制截图粘贴发到别的地方就比较慢。没有找到输出截图压缩的相关设置。

**Comment by liulex** [comment]
你可以试试勾选/取消勾选 “以 Windows Bitmap 格式复制图片” 看看是否有改善。
4k 屏的话，其他硬件应该也不错吧，应该不至于复制粘贴几M的图片就会卡的，可能是其他问题。

**Comment by zhengbli** [comment]
哦卡不是因为机器慢 是因为复制的文件大网络传输慢 比如微信这种
好我去试试这个选项 谢谢了

**Comment by ulpyuxa** [comment]
我有个提议，大于1920*1080的分辨率是，snipaste能够按比例缩小，这样发给其他人又快，在1920*1080的屏幕上面打开时不至于把1920*1080的整个屏幕给盖住， @liulex

**Comment by septs** [comment]
Duplicate of #357
