### ISSUE TITLE
在网页端右键复制后贴图显示是图片路径地址而不是图片

### ISSUE THREAD

**Issue by BlanklyCaT** [Snipaste/feedback#2013]
在大部分网页中的原图,比如Pixiv以及推上点开原图复制时,贴图变成了一串路径,之前是可以贴出原图的.现在只能贴地址了
![image](https://user-images.githubusercontent.com/93505908/139623304-2d74ff95-e6f1-47c7-b0e1-64f8156854fb.png)

软件版本：
运行平台：微软商店 / Windows 桌面

**Comment by liulex** [comment]
谢谢反馈，会在下个版本修复。
