### ISSUE TITLE
当打开加密视频播放器时，snipaste会被自动关闭。

### ISSUE THREAD

**Issue by lllggghhh** [Snipaste/feedback#2017]
打开加密视频播放器时，snipaste会被自动关闭。

[专用播放器.zip](https://github.com/Snipaste/feedback/files/7480377/default.zip)

付费课程用的加密视频播放器，打开后就会把snipaste给杀死，我想视频播放器的目的是为了防录屏，但snipaste并不是录屏软件。微信、钉钉有截图功能就不会被杀死。

软件版本：所有版本
运行平台：Windows 桌面

**Comment by stevenzhu25** [comment]
据[这篇腾讯云社区文章](https://cloud.tencent.com/developer/article/1494214)说，专业的加密视频播放器有常用录屏和截屏软件黑名单， 会自动关闭在名单内的软件并且防止启动。 微信和钉钉肯定不被算进这种黑名单。 感觉这不算是Snipaste的Bug吧…

**Comment by GitHub7796** [comment]
@lllggghhh 哥们，最后怎么解决了呢

**Comment by septs** [comment]
> 涉及版权的问题，Snipaste 不该做针对性的破解。

_Originally posted by @liulex in https://github.com/Snipaste/feedback/issues/330#issuecomment-277406582_
