### ISSUE TITLE
希望可以移动工具条

### ISSUE THREAD

**Issue by Jinming-D** [Snipaste/feedback#2018]
![Snipaste_2021-11-11_16-51-11](https://user-images.githubusercontent.com/46744086/141267946-89ed0f8e-aab8-4cff-a942-d1358bab365b.png)
工具条挡住了我想要圈住的部分，想要把它移开

**Comment by liulex** [comment]
按空格可以隐藏。

**Comment by Jinming-D** [comment]
@liulex 不是希望隐藏，隐藏之后就不能标记了

**Comment by liulex** [comment]
隐藏之后不影响标记啊。

**Comment by Jinming-D** [comment]
@liulex 会挡住视线瞄不准了😂
