### ISSUE TITLE
图片保存修改文件名时，能否直接聚焦到文件名，而非文件名+扩展名

### ISSUE THREAD

**Issue by jkqxl** [Snipaste/feedback#2020]
软件版本：
运行平台：Windows 桌面 

截图等后保存图片时，能否直接聚焦到文件名，而非文件名+扩展名。每次修改文件名都得单独删除原名称。

**Comment by liulex** [comment]
1. Windows 没有提供这样的接口。
2. 全选文件名+扩展名时，直接打文件名即可，也不需要你手打扩展名。

**Comment by jkqxl** [comment]
抱歉，之前从来没注意到这一点，那如果可以，可否在设置中增加一个说明等

**Comment by Geeyun-JY3** [comment]
> 抱歉，之前从来没注意到是可以直接保存的，那如果可以，可否在设置中增加一个说明等

这就是个 Windows 通用技巧，没必要吧……
