### ISSUE TITLE
MacOs深色模式下截图后工具栏按钮不可见，希望可以在设置里选择是否跟随系统更换主题

### ISSUE THREAD

**Issue by MouseKing008** [Snipaste/feedback#2022]
软件版本：2.6.6-Beta2
运行平台：macOS
MacOs 在深色模式下，截图后的工具栏无法看见按钮，希望可以在设置里选择是否跟随系统更换主题
![image](https://user-images.githubusercontent.com/41665000/141879568-ffa5eb63-68b7-46e3-bc07-dda41d0e774d.png)

**Comment by liulex** [comment]
是有自动适配深色模式的，深色模式下的工具栏正常应该是这样的：
![image](https://user-images.githubusercontent.com/2010459/142021745-b377573d-d2cb-46eb-9081-25948bd54111.png)

请问你 macOS 的系统版本是？能提供复现步骤吗？

**Comment by MouseKing008** [comment]
![image](https://user-images.githubusercontent.com/41665000/142092908-43736454-d17d-4e67-b5bf-af07e3c4986d.png)

**macOS Monterey 12.0.1**
@liulex  最新版macos系统, 深色模式下截图就是这样的效果,之前用Catalina时是没有问题的，更新了新系统后的神色模式就有这个问题
  ![image](https://user-images.githubusercontent.com/41665000/142093637-897877c7-8afc-4887-934e-00e15a45c2db.png)

**Comment by liulex** [comment]
我找 Monterey 的用户测试了下，他没有这个问题哦。

**Comment by MouseKing008** [comment]
我卸载重装之后又没问题了，之前的是从旧版本升级上来的。非常感谢耐心解答👍👍
