### ISSUE TITLE
截图转换为灰阶黑白模式

### ISSUE THREAD

**Issue by shanyUn710** [Snipaste/feedback#2023]
除了水平翻转垂直翻转这些基础功能, 希望能增加一个一键将图片转为灰阶黑白模式的图, 画画的时候找参考 看到不错的图想直接粗略的看一下图的黑白对比, 这样就不用放到其他编辑软件中作修改了.

**Comment by liulex** [comment]
![image](https://user-images.githubusercontent.com/2010459/142230081-11cb692f-422c-4058-b767-d5cc996f5ebd.png)
