### ISSUE TITLE
希望增加图片锁定的功能

### ISSUE THREAD

**Issue by PoisonerSC** [Snipaste/feedback#2024]
希望可以增加将图片位置锁定在屏幕上的功能，做有些设计时候会把绘制好的网格图片贴在屏幕上方做参考线使用，经常会不小心拖动图片。

**Comment by liulex** [comment]
有这个功能的，只是默认未设置快捷键：
![image](https://user-images.githubusercontent.com/2010459/142229882-b03f595f-9ba1-499b-abe5-67e484a8fa2f.png)
