### ISSUE TITLE
截图工具状态重启后重置，这正常吗？

### ISSUE THREAD

**Issue by Marcoooooo** [Snipaste/feedback#2028]
就是截图时，下方工具条的“矩形框”“箭头”“画笔”“记号笔”“模糊”这些选项都被重置了。
比如我本来上次使用是“箭头”，重启后就变回“直线”；我上次使用是“绿色矩形框”，重启后就是“红色矩形框”。。模糊我上次是高斯模糊，重启后变成马赛克。。
需要说明的是，自定义颜色那里色盘，是有保存我手动自定义的颜色的。。
这正常吗？

**Comment by liulex** [comment]
你在首选项里关了 自动备份 吧？

**Comment by Marcoooooo** [comment]
> 

谢谢。。试了下这个开关打开就能保存工具状态了。。
这个选项我一直没打开的。
不过按照鼠标悬浮的描述，贴图应该在重启的时候清空之类的，
我每次重启电脑都会恢复重启前的样子（贴图以及贴图位置，双显示器，一直贴在那里）。。
现在打开或关闭这个选项都按照设定来了，不能复现“没打开但重启会恢复”了。。
