### ISSUE TITLE
为什么不能将图片粘贴到剪贴板

### ISSUE THREAD

**Issue by xiaafa** [Snipaste/feedback#2029]
软件版本：
运行平台： Windows 桌面

**Comment by xiaafa** [comment]
为什么通过snipaste截图，复制之后，不能够粘贴到桌面。



在 2021-11-22 19:16:55，"Geeyun-JY3" ***@***.***> 写道：

建议提供更多信息、场景，不然很难帮你排查问题

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Geeyun-JY3** [comment]
需要 Pro：[复制图片时同时复制图像内容和图片文件](https://docs.snipaste.com/zh-cn/pro?id=%e5%85%b6%e4%bb%96)

**Comment by xiaafa** [comment]
需要什么设置/操作嘛,谢谢您

**Comment by Geeyun-JY3** [comment]
上面的链接的图标识得很清楚了吧

**Comment by xiaafa** [comment]
不好意思，谢谢
