### ISSUE TITLE
【需求】希望可以出类似于PickPick里的标尺和白板功能？

### ISSUE THREAD

**Issue by lingdage** [Snipaste/feedback#203]
1.程序员不可避免的也要与UI打点交道，有时候看图的时候标尺就很方便了，但是不要自己作图所以坐标轴量角器那些都是需求不大，但是标尺需求还是蛮大的 希望可以加一个，就省得开2个软件了
2.白板是小组演讲的时候用到的，有时候讲的时候随手画一画很不错的，虽然很多软件都带了，但还是希望集成进来

**Comment by geek000** [comment]
3.主打功能是截图和贴图，贴图很强大了，截图的方式就有点单调了，希望增加滚动窗口截图和任意形状截图

**Comment by HeDonglin** [comment]
这个功能也是我期待的

**Comment by septs** [comment]
see https://github.com/Snipaste/feedback/issues/1155#issuecomment-502735182

**Comment by fewrainbows** [comment]
我是意大利人，我喜很多用 Snipaste!

I think such feature would be interesting!
Measure a line referring to another as a scale.

![immagine](https://user-images.githubusercontent.com/88545208/144893771-97f9db51-936a-4211-8b9e-d2bb47b6c4d3.png)

谢谢
