### ISSUE TITLE
截图的时候能不能加一个箭头呀

### ISSUE THREAD

**Issue by nuo010** [Snipaste/feedback#2030]
****
只有画笔不方便
加一个这样的箭头
![image](https://user-images.githubusercontent.com/68454615/142801905-2bf7bd1c-89fb-49ee-b5e5-b5d9f104049c.png)

**Comment by nuo010** [comment]
如果可以的话可以在来个文字识别

**Comment by chenrylee** [comment]
关于第一个， https://docs.snipaste.com/zh-cn/changelog?id=v26
> 合并箭头工具到折线工具

关于第二个，  dup #188
