### ISSUE TITLE
是否可以截图后直接贴图到屏幕上，而不是还要按一下F3

### ISSUE THREAD

**Issue by yongchao-iyumi** [Snipaste/feedback#2032]
如题

**Comment by Geeyun-JY3** [comment]
目前可以用 <kbd>Ctrl</kbd> + <kbd>T</kbd>：https://docs.snipaste.com/zh-cn/key-bindings?id=只对截图有效

**Comment by yongchao-iyumi** [comment]
非常感谢，基本解决问题了：左键双击选择贴到屏幕，如果需要保存，就再在贴图上右键选择保存
