### ISSUE TITLE
很好用哦，不知道哪里夸你。

### ISSUE THREAD

**Issue by Git-kanata** [Snipaste/feedback#2037]
尤其是截图后直接贴在屏幕上，在开会评审啊或者自己更新excel对比新老数据的时候（还有在线考试截图到搜索引擎找答案）；已经安利了好几个同事了。

产品狗一枚，赞~

**Comment by Git-kanata** [comment]
对了，我是mac m1用户，也没啥购买专业版或者捐赠的渠道。。

**Comment by liulex** [comment]
谢谢，继续帮忙安利就好了 😁 
之后会有专业版的~
