### ISSUE TITLE
窗口元素获取不准确

### ISSUE THREAD

**Issue by rcyggdra** [Snipaste/feedback#2038]
窗口元素获取不准确

软件版本：2.7
运行平台：Windows 桌面
运行软件：melonds https://github.com/Arisotura/melonDS
2.5.6之前还可以正确获取游戏窗口，后面的版本会连同菜单栏一起获取
![image](https://user-images.githubusercontent.com/8652464/143561675-cc622353-d458-4bff-ae42-7d92a2085bcd.png)

**Comment by liulex** [comment]
没问题啊。
![image](https://user-images.githubusercontent.com/2010459/143602854-d7b4e8df-b0ee-4bc3-95ea-1b81f0ad59b9.png)

**Comment by rcyggdra** [comment]
系统是LTSC 2019 64bit

**Comment by liulex** [comment]
那你能否再确认下 2.5.6 没问题，2.7 有问题？
旧版下载：https://bitbucket.org/liule/snipaste/downloads/
