### ISSUE TITLE
希望新增功能：系统剪切板历史

### ISSUE THREAD

**Issue by GeekRicardo** [Snipaste/feedback#2041]
希望能有一个类似于mac下`raycast`的剪切板历史，windows 自带的只有文字没有图片

**Comment by chaohershi** [comment]
Win + v 支持文字和图片。或者使用剪贴板管理软件比如 Ditto Clipboard。

**Comment by Geeyun-JY3** [comment]
个人认为这和截图贴图无关，建议找别的应用。这里推荐 [Ditto](https://github.com/sabrogden/Ditto)  和 [CopyQ](https://github.com/hluk/CopyQ) 
Windows 10 自带的有图片的，不过功能上很弱就是了。

**Comment by GeekRicardo** [comment]
好的，谢谢


Geeyun-JY3 ***@***.***> 于2021年11月29日周一 下午3:24写道：
