### ISSUE TITLE
无法截图

### ISSUE THREAD

**Issue by whgcbngd** [Snipaste/feedback#2043]
此软件在拼多多卖家软件界面的时候，快捷不能使用

**Comment by whgcbngd** [comment]
此软件在拼多多软件界面的时候，快捷键无法使用。

**Comment by whgcbngd** [comment]
快捷键无法使用

**Comment by whgcbngd** [comment]
快捷按键无法使用

**Comment by whgcbngd** [comment]
此软件在拼多多卖家软件界面的时候，快捷不能使用

**Comment by liulex** [comment]
[有时候快捷键不响应](https://docs.snipaste.com/zh-cn/troubleshooting?id=%e6%9c%89%e6%97%b6%e5%80%99%e5%bf%ab%e6%8d%b7%e9%94%ae%e4%b8%8d%e5%93%8d%e5%ba%94)
