### ISSUE TITLE
请求开发自定义尺寸截图功能

### ISSUE THREAD

**Issue by rumengying** [Snipaste/feedback#2045]
希望研发同学添加**固定尺寸截图**功能
具体：
- 在矩形截图的功能上，可以自定义截图尺寸，如：固定 16:9 尺寸截图
- 意义：可确保每次截图的尺寸一样，加强截图的美观性一致性。增强用户体验

很喜欢你们的软件，期待越做越好。无实物比心送给您呐

**Comment by Geeyun-JY3** [comment]
有这功能：https://docs.snipaste.com/zh-cn/pro?id=截图相关

**Comment by Geeyun-JY3** [comment]
![image](https://user-images.githubusercontent.com/49396421/144196686-8abe9539-608c-4130-8c8c-2ececa9e83ab.png)

**Comment by liulex** [comment]
> 意义：可确保每次截图的尺寸一样，加强截图的美观性一致性。增强用户体验

用 <kbd>R</kbd> 不是更好？
![image](https://user-images.githubusercontent.com/2010459/145248732-961fe13d-275b-488f-938f-e98fc6615982.png)
