### ISSUE TITLE
拖动贴图的边角时总是误触放大贴图

### ISSUE THREAD

**Issue by ghost** [Snipaste/feedback#2047]
我已经查阅了能查阅的全部文档

问题描述：比如贴图放在屏幕的左下角时，往往只会漏出贴图的一个边角。

当需要这张贴图的时候，拖动贴图到屏幕中央时，贴图经常会一边放大一边移动到屏幕中央，而且贴图会一直闪烁，所以每次放大后都要使用滚轮再缩小贴图到100%。

不知道从贴图边缘拖动时放大贴图是不是快捷键，如果是的话能不能给个关闭的选项，因为太容易误触了。

<img width="574" alt="贴图" src="https://user-images.githubusercontent.com/53846879/144188392-423c6953-bdb1-44f7-897a-1d95584b1ed2.png">

**Comment by liulex** [comment]
下个版本会限制鼠标在贴图内部的时候不触发边缘缩放。

此外，贴图有 缩略图功能 和 滚轮缩放 可以缩小贴图，以及隐藏/显示所有贴图，实在没有必要把贴图拖到屏幕边缘只露出边角。
