### ISSUE TITLE
请求对截图后存在内存中的图片进行体积压缩

### ISSUE THREAD

**Issue by you-hengh** [Snipaste/feedback#2050]
系统:macOS 12.0.1 M1 
软件版本:2.7.beta

问题描述:

希望截图后选择了复制的图片进行压缩,因为目前使用的是4k屏 

随便框选一部分区域都是超高的分辨率,但是在上传到图床的时候遇到了大小限制,

所以希望软件在截图后自动压缩一下图片质量,png格式感觉没什么必要,截图怎么会有透明区域呢? 

希望截图到内存中图片格式为jpeg 或者其他体积较小的图片格式

至于为什么说截图到内存 我认为是png 格式 是因为我在typora中粘贴图片的时候,发现图片格式是png的

以上 非常感谢作者🙏

**Comment by huangheLee** [comment]
压缩请求+1， 有时候制作文档 里面有大量的图片  放到云端会占用比较大的空间
