### ISSUE TITLE
自定义截图宽高

### ISSUE THREAD

**Issue by icefery** [Snipaste/feedback#2051]
希望加入可以手动修改截图窗口左上角的宽高的功能，比如可以手动修改为 `600 * 300` 而不是必须每次去用鼠标拉动。
- 再比如设置 `i` 或者 `e` 为修改修改截图窗口大小的快捷键，这样在不使用鼠标时也会更加方便一点。
- 在原始图片固定大小的基础上，可以省去 Markdown 使用 `<img>` 对图片宽高的约束。

**Comment by Geeyun-JY3** [comment]
有这功能：https://docs.snipaste.com/zh-cn/pro?id=截图相关

**Comment by icefery** [comment]
嗯好的感谢，之前没看过文档。这样的话 `shift+f1` 也还可以满足功能。
