### ISSUE TITLE
请求添加OCR功能 

### ISSUE THREAD

**Issue by whu-lizhifu** [Snipaste/feedback#2052]
请求添加OCR文字识别功能
贵公司的精品QQ自带的截图功能，使用人数很广
QQ自带的截图功能，目前贵公司都已经支持，并且有自己的特色功能
但文字识别（OCR ）功能，目前贵公司的产品还不支持；
本人在实际工作中发现，截图文字识别（OCR）的功能需求人数很多，目前基本只有QQ自带的截图支持
因此，很多人哪怕不再使用QQ了，但还是会打开QQ，很重要的一个原因就是需要用到截图识别（OCR）的功能；
非常期待贵公司能实现OCR的功能

**Comment by Geeyun-JY3** [comment]
请先善用搜索，重复：#188

「贵公司的精品QQ自带的截图功能」什么鬼，建议重新整理一下语序。

另外这是个人开发者作品。
