### ISSUE TITLE
Windows11下右键菜单无法高亮悬浮的项

### ISSUE THREAD

**Issue by AnLazyOtter** [Snipaste/feedback#2053]
# 软件版本
2.7.0
# 运行平台
- [x] 微软商店 
- [ ] Windows 桌面 
- [ ] macOS
# 问题描述：
将光标悬浮到右键菜单上时，不会高亮。
但Windows10下没问题。

如图：
![Snipaste_2021-12-05_22-33-15](https://user-images.githubusercontent.com/40395191/144751367-c8175342-9871-4116-9f32-1620ab0fb997.png)

**Comment by chenrylee** [comment]
这应该是你电脑设置的问题，以下是我电脑上的显示：  
OS: Windows 11
Build: 22000.358
Snipaste: 2.7.0 (latest store version)
![](https://s2.loli.net/2021/12/07/vT1cICUgnMQk6F4.png)

**Comment by AnLazyOtter** [comment]
> 

我重置了一次我的电脑，现在正常了……
![image](https://user-images.githubusercontent.com/40395191/165566210-681a8447-b6f9-4c54-8f63-785a023151a5.png)
