### ISSUE TITLE
MAC OS Monterey不显示界面，首选项等信息，不显示菜单栏图标。

### ISSUE THREAD

**Issue by mapxn** [Snipaste/feedback#2054]
App version: V2.7Beta
Platform:  macOS
硬件：Macbook Pro 14寸（M1X处理器）
系统版本：Monterey 12.0.1
现象：安装后，点击图标打开，无任何反应。Activity Monitor里面可以看到进程。可以快捷键F1/F3截图使用。没有首选项界面，没有菜单栏图标。

**Comment by mapxn** [comment]
重启电脑后正常了，应该是Monterey系统的bug。

**Comment by ARROW-Z** [comment]
@mapxn 您好，请问这个问题目前你已经解决了吗，我也是出现了同样的问题，但是重启了多次也没有好

**Comment by mapxn** [comment]
> @mapxn 您好，请问这个问题目前你已经解决了吗，我也是出现了同样的问题，但是重启了多次也没有好

解决了，你可以尝试安装最新版的软件，再尝试重启。
