### ISSUE TITLE
隐藏的全部图片突然自动出现

### ISSUE THREAD

**Issue by pfjhyyj** [Snipaste/feedback#2058]
软件版本：2.7 专业版
运行平台：微软商店 

在正常使用电脑（点浏览器，挂着不动）时，隐藏的全部图片会突然自动出现，没有按键盘，只有点击网页的操作
没法稳定复现

禁用快捷键后也会突然弹出

**Comment by pfjhyyj** [comment]
开着QQ，QQ处于缩在上方的状况，鼠标移上去会弹出来。同时这个操作也会触发全部图片出现的问题

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/1936

**Comment by pfjhyyj** [comment]
理解了，感觉这个提示不是很明显，最好提示一下？
