### ISSUE TITLE
即时演示功能

### ISSUE THREAD

**Issue by pansong291** [Snipaste/feedback#2060]
具体功能类似于 `ZoomIt` 这款经典软件，可惜的是它的标注功能不支持输入中文并且再也没有更新过。

![图片](https://img.xbeta.info/zoomit.mm.png)

### 1. 屏幕放大
　　按下快捷键（默认ctrl+1），即可进入ZoomIt的放大模式。这时屏幕内容将放大后（默认2倍）显示。
　　移动光标，放大区域将随之改变。
　　用鼠标滚轮或者上下方向键，将改变放大比例。
　　关于实时放大，见下。
　　按下Esc键 或 鼠标右键，会退出放大模式。
　　在放大模式下，按上鼠标左键，将保持放大状态，启用标注功能。当然，也可以退出放大，只进行标注。

### 2. 屏幕标注
　　标注功能主要用来突出屏幕的某一部分内容，比如图片的某一细节、文章的关键段落。

　　按下快捷键（默认ctrl+2），或在放大模式下按下鼠标左键，可进入标注模式。这时，鼠标会变成一个圆形的笔点，其颜色、大小可调。
　　* 通过按住左ctrl键，使用鼠标滚轮或者上下箭头键调整画笔的宽度。
　　* 按键调整画笔颜色：r 红色；g 绿色；b 蓝色；o 橙色；y 黄色；p 粉色。

　　可轻松画出不同的形状：
　　* 按住Shift键可以画出直线；
　　* 按住Ctrl键可以画出长方形；
　　* 按住tab键可以画出椭圆形；
　　* shift+ctrl 可以画出箭头。

　　其他操作：
　　* Ctrl+Z：撤销最后的标注。
　　* e：擦除所有标注。
　　* w(白色)/k(黑色)：将屏幕变成白板或黑板。
　　* ctrl+s：保存标注或者放大后的画面。
　　* 屏幕打字：进入标注模式后，按‘t’可以进入打字模式。Esc或左键退出。鼠标滚轮或上下箭头可以改变字体大小。缺点是，**不支持中文**。
　　* 鼠标右键：退出标注模式。

### 3. 定时
　　通过快捷键（默认ctrl+3）或点击ZoomIt的托盘图标菜单，可以进入定时器模式。
　　用箭头键可以增加或减少时间。你如果alt+tab从定时器窗口退出，可以点击ZoomIt的图标再激活定时器。用Esc退出。
　　第3项是定时器功能，使用此功能时会暂时将桌面利用白色屏蔽覆盖，并在白色屏蔽上出现倒数计时的时间，您可以选择倒数计时时间的长短、倒数计时结束后是否要播放警告音效、白色屏蔽透明度、倒数计时时间显示在屏幕上的那个位置。

**Comment by Geeyun-JY3** [comment]
请善用搜索，有白板模式：https://docs.snipaste.com/zh-cn/command-line-options
https://github.com/Snipaste/feedback/issues/1155#issuecomment-502735182
