### ISSUE TITLE
标注中能否添加一个高亮

### ISSUE THREAD

**Issue by tobemaster56** [Snipaste/feedback#2063]
像下面的截图一样，标注中需要一个高亮区域，更容易凸显目标区域
![example](https://cdn.nlark.com/yuque/0/2021/png/415253/1639021708340-e5d87373-2f80-45a9-8b49-c0c45b95a3b1.png)

**Comment by Geeyun-JY3** [comment]
重复：#1075

**Comment by Geeyun-JY3** [comment]
Duplicate of #1075
