### ISSUE TITLE
mac m1 pro下，工具类图标全部变白色

### ISSUE THREAD

**Issue by yaakua** [Snipaste/feedback#2066]
截图工具栏上面的所有图标都和底色一样，变成了白色。无法识别出来哪个是哪个了。退出程序，重新打开后恢复正常。

软件版本：2.7-beta
运行平台：macOS
![image](https://user-images.githubusercontent.com/1543846/146301850-d9d9c874-9b9a-4992-bd02-18ca4f55fa28.png)

**Comment by chenrylee** [comment]
dup #2046
