### ISSUE TITLE
框选线增加调节线条粗细功能

### ISSUE THREAD

**Issue by ghostcode** [Snipaste/feedback#2070]
![image](https://user-images.githubusercontent.com/745181/146657847-4262680a-b631-4231-a9f5-51b4970c5088.png)

就像微信的：

![image](https://user-images.githubusercontent.com/745181/146657869-eda8dab6-f27b-4917-831e-e46cde497a54.png)

**Comment by chenrylee** [comment]
[调整画笔宽度](https://docs.snipaste.com/zh-cn/getting-started?id=%e8%b0%83%e6%95%b4%e7%94%bb%e7%ac%94%e5%ae%bd%e5%ba%a6)

**Comment by ghostcode** [comment]
> 

多谢，没仔细看文档。好隐蔽的功能。
