### ISSUE TITLE
linux系列除了deepin外其他的如ubuntu等没有等没有比较好的截图工具。

### ISSUE THREAD

**Issue by aohanhongzhi** [Snipaste/feedback#2075]
### 功能描述

希望开放deb安装包。适配debian系列。

**Comment by chenxinfeng4** [comment]
我也在用deepin，遇到相同问题。期望 尽快适配 linux 系统。

**Comment by xmuli** [comment]
@chenxinfeng4  @aohanhongzhi  Deepin ( Debian) 可以使用  [flameshot](https://github.com/flameshot-org/flameshot)， 然后控制中心设置一下快捷键即可；

**Comment by korant96** [comment]
> @chenxinfeng4 @aohanhongzhi Deepin ( Debian) 可以使用 [flameshot](https://github.com/flameshot-org/flameshot)， 然后控制中心设置一下快捷键即可；

flameshot在屏幕不是100%时并且多分屏时会有闪退和截图不全bug，这个你有遇到过不

**Comment by XMuli** [comment]
@korant96 没遇到，我之前用的是 deepin v20 上 4K 125% + 1080 100% 双屏，使用 flameshot 没有问题（除了图标有小）

**Comment by septs** [comment]
Duplicate of https://github.com/Snipaste/feedback/issues/711
