### ISSUE TITLE
复制贴图中的标记到另一帖图

### ISSUE THREAD

**Issue by mry4z** [Snipaste/feedback#2077]
### 功能描述

在截屏标注时，会有下述的情景：
软件中设计底稿在截图并标记完成后发现截图内容有内容表达需要改进或优化。需要对改进后的底稿重新截图并重新标记。
期望：
是否可以新增一个右键功能，可以复制一个截图(贴图)中的标记到另一个截图(贴图中)，且保持相对截图范围的位置不变。
期待回复，谢谢！

**Comment by Geeyun-JY3** [comment]
[](https://docs.snipaste.com/zh-cn/getting-started?id=%e5%9b%9e%e6%94%be%e6%88%aa%e5%9b%be%e8%ae%b0%e5%bd%95) 基本上是可以满足你的需求

**Comment by liulex** [comment]
@Geeyun-JY3 不可以的，回放的时候截图是旧的，不是当前屏幕。
我考虑在专业版加一个刷新截图的按钮吧。

**Comment by Geeyun-JY3** [comment]
看漏眼了，以为是要对旧截图编辑。

**Comment by mry4z** [comment]
> @Geeyun-JY3 不可以的，回放的时候截图是旧的，不是当前屏幕。 我考虑在专业版加一个刷新截图的按钮吧。
感觉能解决这个场景的问题。谢谢作者。

**Comment by Datamore** [comment]
有没有完整复制贴图的功能，包括里面的编辑图形，这可以随时进行裁剪，最后再进行拼接。
比如一开始，我的截图很大，做了很多标记，后面想整合一下，剔除一些不要的部分，将有用的部分压在另外的上面， 这时复制是不错的办法。

**Comment by Geeyun-JY3** [comment]
> 有没有完整复制贴图的功能，包括里面的编辑图形，这可以随时进行裁剪，最后再进行拼接。
> 比如一开始，我的截图很大，做了很多标记，后面想整合一下，剔除一些不要的部分，将有用的部分压在另外的上面， 这时复制是不错的办法。

你说的这个应该能用 #1654 解决
