### ISSUE TITLE
图片水印和文字水印

### ISSUE THREAD

**Issue by Heartflight** [Snipaste/feedback#2083]
### 功能描述

希望添加一个picpick那样的自动添加水印功能和shareX那样的文字水印，可选则自动添加或手动添加。这样截图后就可以直接添加水印。

**Comment by Heartflight** [comment]
在写博客时减少一个操作步骤，减少一个添加截图的软件。

**Comment by Geeyun-JY3** [comment]
请学会善用搜索：#454

**Comment by septs** [comment]
Duplicate of #454
