### ISSUE TITLE
商店版在一台电脑上付费内购专业版后另一台电脑仍是免费版

### ISSUE THREAD

**Issue by EX-XD** [Snipaste/feedback#2086]
### 问题描述

修复、重置、重装软件均无效。
内购系统为Win11，另一台系统为Win10。
同一个微软账号登录。
![image](https://user-images.githubusercontent.com/55660754/149272073-c76ab758-4b61-4f4a-973f-d0e1bc61bbda.png)
![image](https://user-images.githubusercontent.com/55660754/149272111-15eddf0a-3db5-42f1-88cc-afb5a0b2a1a1.png)

### 运行平台

微软商店

### 软件版本

2.7.1

**Comment by KazamaSion** [comment]
@EX-XD 在 Windows 11 中，内购系统的账号需要单独登录授权。
简单来说：在你装了 Windows 11 的机器上，尝试应用内购买 Snipaste PRO。在接下来弹出的微软账号登录页面中登录。如果该帐号已有专业版授权，则会应用会在这个步骤中自动变更为专业版应用。

**Comment by EX-XD** [comment]
@KazamaSion 懂了，其实就是只要我在每台机器上从头走一次付款流程就行了，只不过根据机器账号情况并不一定需要付款？

**Comment by KazamaSion** [comment]
@EX-XD 只要购买且授权设备数在 10 设备以内，理论上都不需要再额外付费。

**Comment by EX-XD** [comment]
OK了，谢谢
