### ISSUE TITLE
Windows 11 截图窗口圆角处会截入后方背景

### ISSUE THREAD

**Issue by renbaoshuo** [Snipaste/feedback#2088]
### 发生了什么？

在 Windows 11 下，由于窗口是圆角，截图时会在窗口的圆角处截入后面的背景，如图所示：

![Snipaste_2022-01-18_21-10-06](https://user-images.githubusercontent.com/47095648/149943406-db421e7a-b8f4-4c21-98fe-0fc3487cda20.png)

### 运行平台

微软商店

### 软件版本

2.7.1

**Comment by zhouxx2018** [comment]
之前不会吗？我用mac试了一下，也是这样的。
