### ISSUE TITLE
There is a crash when using snipaste

### ISSUE THREAD

**Issue by SaSa-123** [Snipaste/feedback#2097]
### Problem Description

I downloaded the x64 version on my computer, but every time I click and run for a few seconds, it automatically shuts down. Running as an administrator can’t solve it. It always crashes automatically for no reason, and the same is true when I download the x86 version.

### Platform

Windows Desktop

### Version

Snipaste-2.7.1-Beta-x64

**Comment by liulex** [comment]
Please provide more info:
1. Does it happen for both Snipaste 2.x and 1.x?
2. Does it only happen for Snipaste only, or also other snipping software?
3. Is there any files under the `crashes` directory of Snipaste's folder?

**Comment by dodoqwq** [comment]
> 

I suppose that i met the same issue just as the writer above, so i try answering these 3 questions.

1. Both.
2. Sorry, i haven't used any other snipping software since you creators have done such a great job.
3. None.

i really looking foward to solution to this situation for my daily work DOES relly on this maevelous  software.救救孩子。

**Comment by SaSa-123** [comment]
Chinese?
我直接中文说啦 还以为是外国人哈哈
遇到的问题就是每次一点开snipaste 隔个两秒就自动退出 别的贴图软件我没有尝试过 所以也不太清楚怎么回事 但是这两天又能用了 不闪退了 前几天每次一点开 过不了几秒就自动退出 也不知道咋回事 以管理员身份运行也不对 关掉所有杀毒软件也还是会没用 这让我很难受！😣
可能过几天又自动退出了...

---Original---
From: "Le ***@***.***&gt;
Date: Sun, Jan 23, 2022 19:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Snipaste/feedback] There is a crash when using snipaste (Issue #2097)




 
Please provide more info:
  
Does it happen for both Snipaste 2.x and 1.x? 

Does it only happen for Snipaste only, or also other snipping software? 

Is there any files under the crashes directory of Snipaste's folder? 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liulex** [comment]
@SaSa-123 闪退 99% 都是被其他软件杀掉的，其中大部分是网课的视频播放器干的。
