### ISSUE TITLE
CF游戏全窗口状态下按下F1无法使用截屏

### ISSUE THREAD

**Issue by WomorSky** [Snipaste/feedback#2099]
### 发生了什么？

我在全窗口状态下的CF游戏中按下F1没有任何反应

### 运行平台

Windows 桌面

### 软件版本

PRO 2.7.1

**Comment by stevenzhu25** [comment]
@WomorSky 请到CF游戏设置界面确认下F1按键没有被CF游戏内功能绑定

**Comment by septs** [comment]
Duplicate of #2110
