### ISSUE TITLE
需要一个清空已画路径的功能

### ISSUE THREAD

**Issue by CaiJingLong** [Snipaste/feedback#2100]
### 功能描述

有的时候我会使用这个工具作为画笔白板使用，以讲解我的思路
在画到一半的时候感觉有些思路有问题或第一个思路讲解完了要讲解第二个，需要清空，这时候我只有3条路
1. 重新截图(有的时候我的图片是某个区域，而不是窗口，所以会降低效率
2. 使用橡皮一个个的擦，效率太低
3. 撤销到开始，有时候我画了10多笔，甚至20~30笔，效率也低

所以能不能添加一个清空所有的功能

**Comment by liulex** [comment]
https://docs.snipaste.com/zh-cn/key-bindings

<html>
<body>


Ctrl + Shift + Z | 移除所有标注（无法再恢复）
-- | --



</body>
</html>
