### ISSUE TITLE
运行便携版提示缺失api-ms-win-shcore-obsolete-l1-1-0.dll

### ISSUE THREAD

**Issue by neil2023** [Snipaste/feedback#2103]
### Contact Details

19268160@qq.com

### What happened?

win7 64位操作系统，运行Snipaste-2.7.2-Beta-x64便携版，提示缺失api-ms-win-shcore-obsolete-l1-1-0.dll
![企业微信截图_16434243781068](https://user-images.githubusercontent.com/98628735/151644317-b595dbe2-4eed-4b85-8636-989af625aaf6.png)

### Platform

Windows Desktop

### Version

Snipaste-2.7.2-Beta-x64

**Comment by stevenzhu25** [comment]
请去 [https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170 )
下载Visual C++ 2015-2022 试一下

**Comment by hypogaea** [comment]
遇到相同问题，已经尝试安装操作，但系统文件夹里仍然没有出现这个文件，Snipaste仍然无法运行

**Comment by neil2023** [comment]
> 请去 https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170 下载Visual C++ 2015-2022 试一下

安装之后，重启电脑之后，仍旧无法运行，提示缺失api-ms-win-shcore-obsolete-l1-1-0.dll文件

**Comment by elvensen** [comment]
我也遇到了相同的问题，但只在win7上有，win10上商店版本和便携版都没事。VC运行库我都是装全的，所以我单独去网上找了一下这个dll文件，发现只有win8的版本。我在win10上搜索了一下，系统文件夹中只有名称类似的，而且都在不同位置的downlevel文件夹中。
我不是专业的研发人员，但我初步判断是这个文件应该是win8版本，win10默认向下兼容，而win7微软放手了所以没有向上兼容。我这边发现的信息就这些，希望有所帮助。目前win7以换回上一版本继续使用。

**Comment by stevenzhu25** [comment]
> 我也遇到了相同的问题，但只在win7上有，win10上商店版本和便携版都没事。VC运行库我都是装全的，所以我单独去网上找了一下这个dll文件，发现只有win8的版本。我在win10上搜索了一下，系统文件夹中只有名称类似的，而且都在不同位置的downlevel文件夹中。 我不是专业的研发人员，但我初步判断是这个文件应该是win8版本，win10默认向下兼容，而win7微软放手了所以没有向上兼容。我这边发现的信息就这些，希望有所帮助。目前win7以换回上一版本继续使用。
我今天上午搜的时候也是这种说法 说api-ms-win-shcore是Win 8+， Win 10其实不用这个dll也可以使用Snipaste...

非官方建议 （按靠谱程度排序）:
1. 更新电脑版本到Windows 10/11 (Win 7 ESU都到第三年，23年年初ESU就结束了 再古董也该换了）
2. 手动从Win10/11电脑提取该dll，复制到Win 7电脑中
3. 从各种第三方dll下载站搞个dll

**Comment by elvensen** [comment]
首先感谢楼上的热心建议，我有2个电脑，一个win10，一个win7。win7是留着跑一些老游戏或老软件的，所以不需要升级，目前是回滚到上一个版本，如同您建议中的第二条。

但我还是想补充一下我的想法，首先是对官方的。软件与时俱进是正常的，既然新版本对win7支持的有问题，应该在软件官网上有所说明，让用户选择是继续用旧版啊，还是折腾dll啊，都可以。但官网没说，这就是问题所在。用户到这里是当做bug来反馈的，我相信大家应该是希望看到官方类似反馈，比如：
1.官网上给出说明，新版本不再重点支持win7了，但用户可以自行搞定dll文件来运行。
2.官方确认会继续支持win7 ，下个版本会解决这个问题。
当然我知道软件开发是很辛苦的，没有任何催促之意。我这里只是表达我的期望，希望Snipaste这个软件能在各个方面都做的更好。

对于非官方反馈，感谢是一定的，有您这样的热心肠社区才会温暖。但我个人愚见，觉得应该把您建议的前两条调换一下，毕竟现在还坚持用win7的用户，应该都有坚持的理由，要换估计早换了，用老版本即好使又省事，建议首选。

**Comment by liulex** [comment]
没有不支持 Win7 的意思，是这个版本发布比较匆忙，忘了在 Win7 虚拟机测试，没想到就出问题了。但我目前没有 Windows 开发环境，只能年后再修复了。

**Comment by Femtometer** [comment]
相同问题（Same issue），2.7.1在线升级至2.7.2就不能启动了，之前别的软件遇到过类似的dll缺失提示，一般是回复不支持Win7，我暂时回退至2.7.1
[Snipaste-2.7.1-Beta-x64.zip](https://github.com/Snipaste/feedback/files/8012061/Snipaste-2.7.1-Beta-x64.zip)

**Comment by liulex** [comment]
2.7.3 Beta 已修复。

**Comment by huhu415** [comment]
没有修复啊，我window7 sp1版本，还是显示那个图，不过有一点不一样，是api-ms-win-crt-runtime-|1-1-0.dll

**Comment by stevenzhu25** [comment]
@huhu415 这是另外一个DLL， 你试试装 Visual C++ Redistributable for Visual Studio 2015

**Comment by huhu415** [comment]
@stevenzhu25 好的，我试试，thanks

**Comment by neil2023** [comment]
我通过检查更新功能，升级到2.7.3，搞定能运行了，多谢了
