### ISSUE TITLE
QiAnXin Skylar reports snipaste.exe as a Gen:Variant.Lazy virus

### ISSUE THREAD

**Issue by Starwalker2000** [Snipaste/feedback#2111]
v2.7.3-Beta (2022.02.09) 64-bit version has been reported as a virus.
v2.7.2 (2022.01.26) 64-bit version has no such problem.
Above are windows versions.

**Comment by liulex** [comment]
Indeed the 64-bit didn't pass all the detections:
https://www.virustotal.com/gui/file/e47ec0a879f0447846797925f16f28c3c2c13542c36faa317e99a61c65238287/detection
![image](https://user-images.githubusercontent.com/2010459/153436498-2c606ffd-a23f-4d91-a5fa-9e556f900f16.png)

While the 32-bit version passed all:
https://www.virustotal.com/gui/file/a6c42b280553f3bfd049a5f64578159380ac67533ff4e008e025001fc4c31df5
![image](https://user-images.githubusercontent.com/2010459/153436679-8f4cd051-7741-4b29-b542-0f45ee72d8b3.png)

It must be a false positive. I keep all the code and environment unchanged and recompile, the new binary can pass the virus detction:
https://www.virustotal.com/gui/file/5f6430b23de540a517b5dbf803e6a32ee186e79ea4f80c84463b82b36ddf5a8b?nocache=1
![image](https://user-images.githubusercontent.com/2010459/153436745-23cf34ce-b7d1-4f8e-85e8-8c30bb9b0f1c.png)

I don't think it's necessary to release a new version for this false positive. If you care about it, you may use the 32-bit version.

**Comment by Starwalker2000** [comment]
I'd like to wait and try next version. :)
