### ISSUE TITLE
请求添加 自定义history文件夹位置 的功能 类似配置文件config.ini的存储位置

### ISSUE THREAD

**Issue by LiCNs** [Snipaste/feedback#2114]
### 功能描述

类似配置文件存储位置的自定义功能，希望能让history文件夹也可以自定义位置。
我的工作要用到很多参考图，在办公室和家都需要，现在每次都要把贴图手动保存到google云盘比较麻烦，如果能自动备份到云盘会让我这种多位置办公的人方便很多。
PS：可能会出现的问题是，开机启动预加载的图片会在云盘启动前加载好，这时候云盘更新内容不知道会不会出bug

**Comment by efreer1988** [comment]
ok

**Comment by liulex** [comment]
https://docs.snipaste.com/zh-cn/advanced-configs?id=general
