### ISSUE TITLE
关于截图识别边缘出现白边的问题

### ISSUE THREAD

**Issue by Joe0517** [Snipaste/feedback#2115]
### 联系方式

1316115026@qq.com

### 发生了什么？

在win10系统，2k分辨率（2560*1440）缩放125%下，使用截图识别边缘时会在识别框左上角多截取1~2像素，如图所示，其他1920*1080分辨率下不会出现同样问题
![image](https://user-images.githubusercontent.com/99752906/154112555-73e6e1c4-84b8-4a3e-83f8-f7747932f175.png)
![image](https://user-images.githubusercontent.com/99752906/154113022-51e50699-0cd1-4f82-bf98-9becd8161262.png)

### 运行平台

微软商店, Windows 桌面

### 软件版本

2.7.3（2022.01.30）

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/318
