### ISSUE TITLE
贴图放大到全屏再拖动的时候，电脑状态栏会强烈闪烁

### ISSUE THREAD

**Issue by Fxiao1** [Snipaste/feedback#2118]
### Contact Details

18292996946

### What happened?

如题，将贴图放大到超过屏幕大小，拖动的时候，底下的状态栏会频繁闪烁
![GIF 2022-2-22 18-11-57](https://user-images.githubusercontent.com/40653617/155110918-92e04b8d-c19a-48d9-b7d6-4c1731872073.gif)

### Platform

Windows Desktop

### Version

v2.7.3 Beta (Windows 桌面版) （话说应该怎么看它的版本呢？）

**Comment by Fxiao1** [comment]
奥，忘了说了，电脑是win10系统 版本号是： 21H2

**Comment by liulex** [comment]
Windows 的正常现象，同为置顶的窗口的任务栏，它们会相互竞争。

**Comment by Fxiao1** [comment]
> Windows 的正常现象，同为置顶的窗口的任务栏，它们会相互竞争。

尝试劝自己了一段时间，现在依然难以忍受，闪眼睛是一方面，另一方面cpu也会狂转，两个程序在争夺置顶窗口的时候疯狂占用cpu，期待作者能对此有点优化方案。要么不要跟状态栏争夺置顶了也行吧

**Comment by Fxiao1** [comment]
> 那你为什么要让贴图挡到任务栏呢？

有的图片分辨率本来就比较高，复制-贴图之后本身就超出屏幕了（盖住了任务栏），稍微一拖动任务栏就开始频闪了。而且有的情况下也想放大某些图片看局部，然后其他部分也会遮住任务栏。
