### ISSUE TITLE
可以添加电子教鞭功能吗？

### ISSUE THREAD

**Issue by lixingyangok** [Snipaste/feedback#2120]
### 功能描述

可以添加电子教鞭功能吗？
● 就是把我们的箭头功能高亮功能直接往屏幕上画，不用先截图框选 😊😊😊
● 工作时为了向同事说明位置，强调信息时，常常按下截图快捷键然后框选，往框内画箭头，写字等，有时框小了还得扩大。
● 希望能直接往屏幕上画画，因为就是为了临时说明一下 😊😊
谢谢

**Comment by liulex** [comment]
免费版可以通过命令行调用白板模式： https://docs.snipaste.com/zh-cn/command-line-options
专业版可以将白板模式绑定到全局快捷键，更有[透明白板](https://github.com/Snipaste/feedback/issues/1155#issuecomment-502735182)功能。
