### ISSUE TITLE
Spotlight annotation mode (Dim everything except selected region)

### ISSUE THREAD

**Issue by jonpdw** [Snipaste/feedback#2121]
### Feature Description

Like this feature from[ Cleanshot X](https://cleanshot.com/#:~:text=at%20Earnest%20Capital-,Annotate,-In%20a%20matter)
![chrome_1094](https://user-images.githubusercontent.com/32897666/155443630-a1c721a2-0eda-4330-90ab-8229b695f009.gif)

I would love a feature like this

**Comment by Geeyun-JY3** [comment]
Duplicate: #1075
