### ISSUE TITLE
snipaste无法正常使用-闪退

### ISSUE THREAD

**Issue by Jeans-Li** [Snipaste/feedback#2126]
snipaste无法正常使用，启动软件后，软件自行闪退，系统用的是win10系统，也曾经尝试过电脑重启，但是没有效果，所以提交一个issue，希望能够有所修复！

**Comment by liulex** [comment]
请问全新安装（官网下载后解压到另一目录运行）的也会闪退吗？如果全新安装的没问题，请把旧的安装目录打包发送至 <snipaste.app@gmail.com>.

**Comment by Jeans-Li** [comment]
感谢您的回复，通过我的排查，发现是我电脑上的一个软件与系统不兼容导致的闪退问题的出现，如果您需要我的不兼容的软件，来改善snipaste，也可以将软件发送给您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Snipaste/feedback"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月5日(星期六) 中午1:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Snipaste/feedback] snipaste无法正常使用-闪退 (Issue #2126)





 
请问全新安装（官网下载后解压到另一目录运行）的也会闪退吗？如果全新安装的没问题，请把旧的安装目录打包发送至 ***@***.***
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liulex** [comment]
好呀，麻烦你将软件发送到上面的邮箱，谢谢！

**Comment by helo87** [comment]
> 

加密视频软件和snipaste都需要同时使用，有什么好的解决方案嘛

**Comment by langB123456** [comment]
是的，就是因为存在一个加密视频软件导致的

**Comment by septs** [comment]
> 谢谢你提供的详细描述和解决办法。 涉及版权的问题，Snipaste 不该做针对性的破解。 不过，这个 pdf ownerguard 看起来就像个摆设，导致根本不用做针对性处理也能绕过。。 😂

from https://github.com/Snipaste/feedback/issues/330#issuecomment-277406582
