### ISSUE TITLE
连接无线显示器后重启Snipaste才能在无线显示器中截屏

### ISSUE THREAD

**Issue by Toonyxm** [Snipaste/feedback#2128]
### 发生了什么？

重现步骤：
![image](https://user-images.githubusercontent.com/11314213/156490735-bf56c20f-ab7a-485e-b9cf-3ed7bef88d1c.png)
1. 接入无线显示器，3号屏幕为无线显示屏，显示器摆放位置如上图。
2. 点击Snipaste截屏，无线显示器中未变灰，鼠标移动至3号屏幕没有Snipaste界面。
3. 重启Snipaste。
4. 再次截屏，此时3号屏幕可正常截图。

期望：
连接无线显示器后无需重启Snipaste即可在新屏幕中截图。

### 运行平台

Windows 桌面

### 软件版本

2.7.3-beta

**Comment by liulex** [comment]
这是因为目前使用的 Qt 版本暂时无法支持显示器的动态识别，正在适配 Qt 6，到时候在看看。
