### ISSUE TITLE
希望加入一个快捷键实现将剪贴板里最近的图片贴为贴图的功能

### ISSUE THREAD

**Issue by fr1g** [Snipaste/feedback#2131]
### 功能描述

如题。有时候会直接复制IM软件里的聊天图片，复制完毕后倘若有个快捷键能将才复制的图片作为贴图贴出来就好了。

**Comment by liulex** [comment]
贴图键 (默认 <kbd>F3</kbd>) 不就是这个功能？

**Comment by fr1g** [comment]
> 贴图键 (默认 F3) 不就是这个功能？

原来是这样 我没看懂功能解释 下次一定挨个试试
