### ISSUE TITLE
pro 版边框设置为 0 时，仍然有边框

### ISSUE THREAD

**Issue by cubyee** [Snipaste/feedback#2133]
### 联系方式

cubyee@gmail.com

### 发生了什么？

![image](https://user-images.githubusercontent.com/25090754/156867270-4f838aad-35f3-425b-82e6-dc0649b825b8.png)

PRO 版截图边框设置为 0 时，仍然有细细的边框存在，如上图。请问可否在边框设置为 0 时，把边框完全去掉呢？

### 运行平台

Windows 桌面

### 软件版本

2.7.3

**Comment by liulex** [comment]
截屏的边框和输出截图的边框是两回事。你所说的细细的边框是这里控制的：
![image](https://user-images.githubusercontent.com/2010459/156868661-b2d9ac3b-7b3a-4a53-ad0b-7bd508f4d98a.png)

**Comment by cubyee** [comment]
原来是这样，应该早点来问的，困扰我很久的问题解决了，谢谢！
