### ISSUE TITLE
截图时添加文字的时候，无法输入C，应该是和C快捷键取色冲突了

### ISSUE THREAD

**Issue by SleepyHippo** [Snipaste/feedback#2136]
### 发生了什么？

如题，截图时添加文字的时候，无法输入C，应该是和C快捷键取色冲突了

### 运行平台

微软商店, Windows 桌面

### 软件版本

2.7.3

**Comment by chenrylee** [comment]
https://github.com/Snipaste/feedback/issues/640#issuecomment-346732910
