### ISSUE TITLE
从剪贴板里的文件贴图时不能贴出图片文件

### ISSUE THREAD

**Issue by Sponge-bink** [Snipaste/feedback#2147]
### 联系方式

juliegvd143@gmail.com

### 发生了什么？

Finder 选中文件，按 Command + C，按贴图快捷键贴图，只有图片的图标被贴上。在 2.2.5 beta 上会正确贴出剪贴板里的文件图片

### 运行平台

macOS

### 软件版本

v2.7.2 beta

**Comment by liulex** [comment]
谢谢反馈，会在下个版本修复。
