### ISSUE TITLE
已开启UAC，但是无法购买专业版

### ISSUE THREAD

**Issue by BoxuanZng** [Snipaste/feedback#2154]
### 问题描述

已开启UAC，但是无法购买专业版。购买专业版时右下角仍然会弹出“您需要先启用UAC（用户账户控制）才能完成购买”的提示

### 运行平台

微软商店, Windows 桌面

### 软件版本

2.7.3

**Comment by BoxuanZng** [comment]
![image](https://user-images.githubusercontent.com/61570274/160272157-75c965b8-cb7f-4a01-a1af-91f2bf9b25f6.png)
如图，UAC已经开启

**Comment by liulex** [comment]
登录了管理员账户？请以普通用户帐号登录 + 开启 UAC.

**Comment by BoxuanZng** [comment]
那我平常都是用管理员账户工作，用普通账户的话，管理员账户的数据什么的（例如存在User\Administrator\AppData里的）怎么办

**Comment by liulex** [comment]
只是购买的时候不能用管理员账户，购买成功之后就随便你了。微软商店的奇怪机制。
