### ISSUE TITLE
直接截图并实现贴图

### ISSUE THREAD

**Issue by zhengzich2020** [Snipaste/feedback#2156]
### 功能描述

截图后需要按下F3 才可以实现贴图。
操作比较繁琐，
希望能够实现：直接实现截图后显示贴图。

**Comment by limonene0x** [comment]
这是专业版的功能🌚

**Comment by Geeyun-JY3** [comment]
请先善用搜索，认真阅读文档：#2032

**Comment by bigjujube** [comment]
什么时候 mac 版才有这个功能啊？付费的也行啊，可是目前没有
