### ISSUE TITLE
贴图组功能失效

### ISSUE THREAD

**Issue by James-tech-007** [Snipaste/feedback#2159]
### Contact Details

1165324684@qq.com

### What happened?

win10
切换贴图组快捷键显示一个横杆，F2和其他键设置成截图可以用,设置成切换贴图组就不行
F5可用
![image](https://user-images.githubusercontent.com/78539681/160311239-62a487a0-5103-4e05-a7b3-f342ef429ab8.png)

F5放到切换贴图组就不可用了
![image](https://user-images.githubusercontent.com/78539681/160311300-335734a0-3ca0-422f-ad30-3d1f2a06ffcb.png)

没有新建贴图组的选项，切换到另一贴图组也没有反应
![image](https://user-images.githubusercontent.com/78539681/160311413-6ce1971d-db57-4812-9f9c-d0ce5c769713.png)

### Platform

Microsoft Store

### Version

2.7.3

**Comment by liulex** [comment]
你关闭了“自动备份”，即贴图不记录到本地文件，就没有贴图组功能。
