### ISSUE TITLE
[feature] 对于这款软件的几个新功能的建议

### ISSUE THREAD

**Issue by DotRacel** [Snipaste/feedback#2160]
# 设置
希望能给个对于这个取色框的显示/隐藏选项

因为我确实用不到，而且这个玩意太大了，并且跟踪的刷新率也没有鼠标同步，所以很难受....

![image](https://user-images.githubusercontent.com/44699887/160396448-e4eb84e5-c75d-486c-bece-682cb8aec0cc.png)

# 剪贴板
![Screenshot_2022-03-28_20-23-39](https://user-images.githubusercontent.com/44699887/160397103-9f91316a-d7fe-416f-a880-54f8a409e7f1.png)
### 图片分享对接API
希望能提供可以对接自己的上传图片API的功能，这样的话在一些软件(如Discord)里就可以用链接的方式分享图片。

并且也考虑到了微软的那个分享图片大多数人都用不到，因为他家的生态不行
### 添加其他格式复制图片的功能
比如，用png/jpg格式的来复制图片，（应该和复制为文件的实现原理不同？）

类似于QQ截图的那种，它的那个无论复制到哪里都是个jpg，而且也能在死不添加bitmap的discord里复制使用。

今天刚看到这个软件便换掉了之前的Lightshot，若能添加上面的功能那便是完美了

**Comment by Geeyun-JY3** [comment]
> 希望能给个对于这个取色框的显示/隐藏选项

专业版是能完全隐藏的：https://docs.snipaste.com/zh-cn/pro
![image](https://user-images.githubusercontent.com/49396421/160538799-480f7705-9a95-4343-861d-0725d1b41893.png)
https://github.com/Snipaste/feedback/issues/1679#issuecomment-714527302

> 图片分享对接API

重复，见 https://github.com/Snipaste/feedback/issues/282#issuecomment-268241058

> 添加其他格式复制图片的功能

或者可以参考 #646？

**Comment by liulex** [comment]
> 类似于QQ截图的那种，它的那个无论复制到哪里都是个jpg

举个例子，粘贴到哪里 Snipaste 是 png，QQ 截图是 jpg?
