### ISSUE TITLE
关于屏幕取色引用显示器 ICC，导致取色不一致

### ISSUE THREAD

**Issue by vickychinghk** [Snipaste/feedback#2161]
### 发生了什么？

通过浏览先前的 issue，发现屏幕取色不一致是因为 ICC 文件导致的。
建议 snipaste 可以选定 ICC 文件，可选择固定文件或跟随系统，这样就可以在广泛使用 SRGB 的设计软件中，取到正确的颜色。

再次感谢开发者开发出如此优秀的软件。

### 运行平台

macOS

### 软件版本

2.7.2

**Comment by cooper1x** [comment]
同建议

**Comment by septs** [comment]
Duplicate of #2002
