### ISSUE TITLE
贴图后，按住Ctrl+鼠标左键拖拽到其它应用程序，实现导入功能

### ISSUE THREAD

**Issue by lumiphone** [Snipaste/feedback#2169]
### 功能描述

贴图后，直接拖拽进其它软件使用是很直观的操作，类似quicker的截图贴图模块。就因为这一微小差别，很多时候我都是习惯于Quicker的截图，即使用Snipaste标注后也会用Quicker来贴图。

**Comment by Geeyun-JY3** [comment]
Duplicate of #1804
