### ISSUE TITLE
为什么mac没有专业版啊? Why is there no professional version of Mac?

### ISSUE THREAD

**Issue by shanyUn710** [Snipaste/feedback#2172]
### 功能描述

我需要图片转灰阶的功能, 但是这个功能只有windows专业版本才有, 什么时候Mac才可以实用专业版本?
I need the function of "image to gray scale", but this function is only available in windows professional version. When can I use the professional version on MAC system? please

**Comment by uniquejava** [comment]
我也想要mac 的 pro 版, 有下面两个功能就会立马入手:
1.  订圆形数字 的功能, 这在写操作文档时会非常方便, 像下面这样

<img width="554" alt="image" src="https://github.com/Snipaste/feedback/assets/1049271/03cca936-a3cb-469b-b50a-fe25b7f84199">

2. 标注层(原始图层)是否能保存下来,  这样方便二次编辑(修改).

**Comment by Geeyun-JY3** [comment]
https://docs.snipaste.com/zh-cn/changelog?id=v210

> ### v2.10
> 
> > 2024.09.10
> 
> - 桌面正式版 (Windows/Mac/Linux) 发布！支持解锁[专业版](https://docs.snipaste.com/zh-cn/pro)！
