### ISSUE TITLE
There is a default Chinese language under internationalization[English]

### ISSUE THREAD

**Issue by XMuli** [Snipaste/feedback#2175]
### Contact Details

xmulitech@gmail.com

### What happened?

As shown in the picture
![image](https://user-images.githubusercontent.com/33887845/163399837-406cb694-02b1-4b40-abf1-b063dbf8a67a.png)

### Platform

Windows Desktop

### Version

v2.7.3-Beta x64 (2022.02.09)

**Comment by liulex** [comment]
The name is generated and written on the first launch of Snipaste. Change of UI language would not affect it after that.
I may improve on it later. Thanks for the report!
