### ISSUE TITLE
提供屏幕画笔功能，就是目标不是截图，是直接屏幕上画标注

### ISSUE THREAD

**Issue by mokeyish** [Snipaste/feedback#2180]
### 功能描述

Snipaste 的截图功能已经标注功能已经非常完善了，希望再提供一个直接屏幕标注的模式（快捷键直接开启，全屏标注，不要截图的框选了）。像这个软件 [Ipevo annotator](https://www.ipevo.com/software/annotator) 这样。

**Comment by Geeyun-JY3** [comment]
请善用搜索，有白板模式：https://docs.snipaste.com/zh-cn/command-line-options
https://github.com/Snipaste/feedback/issues/1155#issuecomment-502735182

**Comment by mokeyish** [comment]
好的，谢谢😁
