### ISSUE TITLE
增加“给贴图描边”的功能

### ISSUE THREAD

**Issue by t01122** [Snipaste/feedback#2181]
### 功能描述

这个工具非常优秀，功能强大，很感谢！以下给出我个人的一个小建议：
增加“给贴图描边”的功能。现有设置里只有2个选项，“勾选窗口阴影”或“去掉窗口阴影”，这2个选项并不满足我的使用，因此建议增加一个“给贴图描边”的选项。

以下是我个人对现有选项的使用感受。
1、勾选窗口阴影    
特点：能够容易肉眼看到贴图的位置，边缘有渐变效果（这点不是每个人都喜欢，我个人不是特别喜欢）

2、去掉窗口阴影
特点：贴图很干净简洁，但有时候不容易找到贴图的位置（当贴图和背景相似的时候）

**Comment by Geeyun-JY3** [comment]
Duplicate of #1717
