### ISSUE TITLE
截图后图片泛红

### ISSUE THREAD

**Issue by ghost** [Snipaste/feedback#2183]
### 问题描述

系统win10，截图后，图片的RGB颜色值会改变，比如255，255，255会变为255，253，255，图片整体泛红

### 运行平台

Windows 桌面

### 软件版本

2.7.3-Beta

**Comment by tempmanifolds** [comment]
可能开了某个护眼模式？我开了护眼模式后图片变黄

**Comment by tempmanifolds** [comment]
> 可能开了某个护眼模式？我开了护眼模式后图片变黄

#1239

**Comment by kwan1525** [comment]
不是护眼模式，显示器是U2723，把显示器的HDR打开就解决了
