### ISSUE TITLE
You can't use letter "C" in text annotations, since it's used as a Hotkey

### ISSUE THREAD

**Issue by ZapAndersson** [Snipaste/feedback#2184]
### What happened?

The C key is used as a hotkey, this means you can't type the letter C when adding a text annotation! 

![image](https://user-images.githubusercontent.com/102356572/164240819-498e49de-600e-4c85-aefd-00ad21dcb98c.png)

### Platform

Windows Desktop

### Version

1.16.2

**Comment by Geeyun-JY3** [comment]
https://github.com/Snipaste/feedback/issues/640#issuecomment-346732910
See https://github.com/Snipaste/feedback/wiki/Advanced-Configs/ec0a62922d81c75264512143eca224e0ab0d0a76#snip
