### ISSUE TITLE
[Mac] Set transparency with shift+scrolling - 使用 shift + 滚动设置透明度

### ISSUE THREAD

**Issue by JohnLockeNJ** [Snipaste/feedback#2188]
### Feature Description

Could you let us adjust the transparency of a Snip by holding down the SHIFT key while scrolling, similar to how you can resize a Snip by simply scrolling?

Google Translate/谷歌翻译:
您能否让我们通过在滚动时按住 SHIFT 键来调整 Snip 的透明度，类似于您当前通过简单滚动来调整 Snip 的大小？

**Comment by liulex** [comment]
I think you can already do that by holding <kbd>Ctrl</kbd>.

**Comment by liulex** [comment]
I have no problem to change the opacity of the image window by holding <kbd>Ctrl</kbd> and scrolling on macOS.
