### ISSUE TITLE
功能请求：在截屏时选取局部区域并缩放

### ISSUE THREAD

**Issue by MichaelSuen-thePointer** [Snipaste/feedback#2190]
### 功能描述

进入截屏模式->选取截屏区域->进入局部缩放模式->框选一个范围->放大选取的局部

对于需要强调选取区域的情况，除了绘制红色矩形之外，也可以这样做

**Comment by Geeyun-JY3** [comment]
Pro 版的放大镜标注：#193？

**Comment by MichaelSuen-thePointer** [comment]
> Pro 版的放大镜标注：#193？

是的，看来已经有了，那issue可以关闭了
