### ISSUE TITLE
专业版在截图时无法通过鼠标滚轮选择父/子元素

### ISSUE THREAD

**Issue by zbt-237** [Snipaste/feedback#2192]
### 问题描述

**Windows 11在截图时无法通过鼠标滚轮选择父/子元素，详细问题如下：**
- 手动触发截图命令时可手动检测页面元素，但无法通过鼠标滚轮切换父/子级元素
- 使用Tab键可以触发“切换检测窗口”操作，但无法触发“检测界面元素”操作
- 90%的软件无法检测到界面中的元素（过去使用Windows10时并未出现这个问题）
- Tips：因多数软件无法检测到界面中的元素，以上操作均在Edge浏览器收藏夹栏进行的测试

**目前进行过的尝试：**
- 已在首选项>截屏>行为下勾选“自动检测界面元素”
- 阅读操作文档
- 重启软件/电脑
- 查阅issue（但并未发现类似的问题）

**以下是硬件及操作系统信息：**
- CPU:AMD R7 4700U
- GPU:AMD Radeon Graphics（集成显卡）
- OS:Windows 11 专业工作站版 21H2
- 操作系统版本：22000.652

### 运行平台

微软商店

### 软件版本

Snipaste Pro（64位） 2.7.3（2022.01.30）

**Comment by liulex** [comment]
可否贴一下配置文件？首选项 - 配置文件 - 打开

**Comment by zbt-237** [comment]
> 可否贴一下配置文件？首选项 - 配置文件 - 打开

[General]
as_admin=true
startup_fix=2
first_run=false
read_tips=16
font_dialog_size=@Size(500 360)

[Hotkey]
snip="16777265, 113"
snip_and_copy="134217793, 134217793"
super_snip=2

[Interface]
tray_color=@Variant(\0\0\0\x43\x1\0\0\xff\xff\xaa\xaa\0\0\0\0)
color_mode=2
copy_without_sharp=true
magnifier_pixel_scale=10
uppercase_hex=true
max_pens=5
font="Microsoft YaHei UI,9,-1,5,50,0,0,0,0,0,Regular"
auto_theme_color=true
theme_color=#00ffff00

[Misc]
preload_dlls_last_interval=30

[Snip]
abort_on_focus_out=true
auto_cross_lines=true
ask_for_confirm_on_esc=false
auto_magnifier_for_super_snip=true
border_width=0
clipboard_sound=true
disable_mouse_scroll=true
record_unsaved_screenshots=true

[Paste]
mnemonics_on_context_menu=true
text_font="\x817e\x8baf\x4f53,12,-1,5,50,0,0,0,0,0,Regular"
zoom_at_cursor=true

[Paste2]
default_background_mode=0

**Comment by liulex** [comment]
```
disable_mouse_scroll=true
```

你禁用了截图的滚轮功能。

**Comment by zbt-237** [comment]
> ```
> disable_mouse_scroll=true
> ```
> 
> 你禁用了截图的滚轮功能。

谢谢！我已经在首选项>截屏>按键下取消勾选“禁用鼠标滚轮功能”，目前已经可以在“Edge浏览器收藏夹栏”通过鼠标滚轮选择父/子级元素。但是现在”90%的软件无法检测到界面中的元素“这一问题能存在（详见图片）
![mmexport1651118105357.png](https://user-images.githubusercontent.com/72063964/165673141-c1e1a31c-2882-4e6c-9dbd-c1a8fc267e29.png)

**Comment by liulex** [comment]
由于 Qt 的原因，Snipaste 自身的窗口控件都是不支持元素识别的。

**Comment by zbt-237** [comment]
> 由于 Qt 的原因，Snipaste 自身的窗口控件都是不支持元素识别的。

😥图片只是阐释不识别元素的这一问题，并非只有Snipaste不识别元素，而是多数软件在win11下都不能识别(手动选择也不能），但过去使用win10的时候就可以正常识别，暂不能确定问题出在哪里。

**Comment by liulex** [comment]
请定义“多数软件”。我升级到 win11 后没遇到任何问题哦。

**Comment by q794531176** [comment]
问题+1，同样无法识别多数元素

**Comment by q794531176** [comment]
连演示图中的检测软件元素都检测不到

**Comment by q794531176** [comment]
[General]
startup_fix=2
first_run=false
read_tips=54
font_dialog_size=@Size(500 363)

[Hotkey]
hide="150994992, 134217840"
paste="16777264, 112"
snip="134217793, 134217793"
snip_and_copy="67108929, 67108929"
switch="150994993, 134217841"
custom_snip=
super_snip=4

[Misc]
preload_dlls_last_interval=19.53

[Snip]
auto_cross_lines=true
ask_for_confirm_on_esc=false
auto_magnifier_for_super_snip=true
record_unsaved_screenshots=true

[Update]
check_interval=100

[Interface]
auto_theme_color=true

**Comment by q794531176** [comment]
![image](https://user-images.githubusercontent.com/52478611/175458225-d672ac7d-12be-4d48-9075-be03d46328fb.png)

**Comment by yhgu2000** [comment]
https://github.com/Snipaste/feedback/assets/49391101/a76efe79-2714-49b8-85da-ea55310096ac

**Comment by yhgu2000** [comment]
> @liulex

没事了，不知道怎么回事，第二天再开机的时候又好了（真奇怪）
