### ISSUE TITLE
建议新增 Esc 开关不删除贴图

### ISSUE THREAD

**Issue by installH** [Snipaste/feedback#2195]
### 问题描述

经常性的隐藏和显示贴图，贴图会被聚焦没注意按到Esc后贴图就被误删了

### 运行平台

macOS

### 软件版本

12.2.1

**Comment by Datamore** [comment]
同意，我已经多次碰到这个问题了，弄得现在操作时高度紧张，Esc键是平时使用其它程序中频繁要用到，很容易误删除做了大量编辑的贴图，建议将目前的操作方式保留，只是这些截图或贴图可以设置保存较长时间再销毁，可以将其放置到现有一个系统自定义组中如“待清空组”，这样就完美了。

**Comment by XMB-7** [comment]
+1, 建议允许用户自行选择是否使用esc关闭贴图.
顺便问下, 这个功能专业版里有实现吗, 还是说目前专业版免费版都是在用esc关闭贴图.

**Comment by liulex** [comment]
下个版本专业版就有了：
![](https://user-images.githubusercontent.com/2010459/168194793-658f6fb3-41d7-4ab3-93a5-bc5ff31b0be3.png)
回收站功能暂不实现。
