### ISSUE TITLE
截图并编辑后，部分图形如箭头或文本框无法二次编辑，但有的又可以

### ISSUE THREAD

**Issue by Datamore** [Snipaste/feedback#2198]
### 联系方式

zengyongshanghai@gmail.com

### 发生了什么？

如题，部分无法编辑导致整个粘图无法使用，原来的编辑痕迹还在那里，要擦除。
我电脑重启了，也不行。
昨天晚上碰到这个情况，restart应用不行，但重启后正常了，今天重启了也没有恢复正常。
我是Win10的系统，用的是Pro版本。
🙏能否尽快反馈如何解决？

### 运行平台

微软商店

### 软件版本

v2.7.2

**Comment by Datamore** [comment]
刚才测试后发现其触发机制了，如图。
![image](https://user-images.githubusercontent.com/24820172/166085310-2acac54d-0729-48fe-99a6-37acee1a872a.png)

**Comment by Datamore** [comment]
请开发者确认一下这是个Bug还是原设计就是这样的。截图后本能是要在上面编辑的，这个时候要加个锁定才能保存住，会导致大量误操作，我自己就碰到好几起了，辛苦的工作全部白费。
🙏

**Comment by liulex** [comment]
就是这么设计的。你要贴图保留完整的编辑历史，就先贴图再开始编辑。
截图完成后，它就只是一张像素图片，不包含任何标注信息的。
实在想要编辑截图之前的标注，就用"回溯截图历史"这个功能。
