### ISSUE TITLE
wiki主栏漏掉了pro feature

### ISSUE THREAD

**Issue by XMB-7** [Snipaste/feedback#2202]
### 功能描述

阅读文档好几次了, 这才偶然发现侧栏提示还有一篇介绍专业版功能的, 建议补上, 提示更多用户专业版的增强功能.
![image](https://user-images.githubusercontent.com/65625632/166199705-eabea8ae-80b8-4c3d-9c64-88cb780877e8.png)

**Comment by liulex** [comment]
改好了，谢谢提醒！

**Comment by liulex** [comment]
建议从这里阅读文档哈: https://docs.snipaste.com/zh-cn/
