### ISSUE TITLE
不用管理员身份打开sinpaste，就会出现提示：No write permission on the config file!

### ISSUE THREAD

**Issue by hackyyp** [Snipaste/feedback#2203]
### 联系方式

2864283785@qq.com

### 发生了什么？

Win10系统，不用管理员身份打开sinpaste，就会出现提示：No write permission on the config file!
而且复制的图片，无法贴图。

### 运行平台

Windows 桌面

### 软件版本

2.7.3-Beta (2022.02.09) 64位

**Comment by liulex** [comment]
不要把桌面版解压到 `C:\Program Files (x86)` 或 `C:\Program Files`.
