### ISSUE TITLE
截取HDR画面颜色不正常

### ISSUE THREAD

**Issue by hao1196561270** [Snipaste/feedback#2205]
### 联系方式

hao1196561270@126.com

### 发生了什么？

![image](https://user-images.githubusercontent.com/34802963/167671255-ad99a004-10a2-4679-b0b0-5250b2501f04.png)
截图后会变得惨白应该如何解决 
朋友们

### 运行平台

Windows 桌面

### 软件版本

2.6.6-beta

**Comment by Geeyun-JY3** [comment]
请善用搜索：#1112
