### ISSUE TITLE
截图后画笔用数位板来写的性能

### ISSUE THREAD

**Issue by Hisen5** [Snipaste/feedback#2206]
### 发生了什么？

有一些延迟,写小一点的字无法准确识别,比如数字7,因为我主要看教程视频截图然后需要用数位板画一些东西作为笔记,所以这个方面的性能对我来说十分重要,希望能提升一下

### 运行平台

Windows 桌面

### 软件版本

2.7.3

**Comment by Hisen5** [comment]
已入专业版支持

**Comment by liulex** [comment]
录屏说明一下？

**Comment by Hisen5** [comment]
这是我在数位板上用笔画的,识别不准,我用的wacom的数位板,已经在PS上测试了很好画,排除了数位板本身的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Snipaste/feedback"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月15日(星期天) 晚上10:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Snipaste/feedback] 截图后画笔用数位板来写的性能 (Issue #2206)





 
录屏说明一下？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

bandicam 2022-05-16 01-52-53-122.mp4 (3.00M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=686234626566b4c9305deb431366561955505155050200051c520555074b505304011900055f011b52570000030453035756035335426454500c500b56070916035206501856511b00541452044b51041c57074f045456185c12006208&t=exs_ftn_download&code=1b4b5fd6

**Comment by liulex** [comment]
用鼠标画没有问题？

**Comment by Hisen5** [comment]
鼠标画确实没问题,根据这个情况,我试了把数位板调成笔压一定,结果还是一样的

**Comment by Hisen5** [comment]
这是我用鼠标画的,没有问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Snipaste/feedback"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月16日(星期一) 上午9:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Snipaste/feedback] 截图后画笔用数位板来写的性能 (Issue #2206)





 
用鼠标画没有问题？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

bandicam 2022-05-16 12-50-28-651.mp4 (925.6K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=6d66323944efc79c3559ed181766044c00560b000852525419520b09014b025504511f015453504e56025008505e06505554030b314236015508565052075b430656000b1c56034e05501208034b035319540a140753074d591606390c&t=exs_ftn_download&code=4f291f6c

**Comment by liulex** [comment]
![image](https://user-images.githubusercontent.com/2010459/168610543-6c42cbc6-ffbe-4847-9d4b-2974cc42a195.png)
映射模式改成“鼠标”呢？
