### ISSUE TITLE
win 11出现睡眠后唤醒 snipaste 崩溃情况

### ISSUE THREAD

**Issue by 124bill** [Snipaste/feedback#2208]
### 发生了什么？

surface pro 6，操作系统版本为win11 21H2 22000.675，snipaste运行过程中合盖休眠后一段时间，再次唤醒电脑会发生snipaste崩溃闪退，手动开启使用后无异常，休眠则有大概率再次唤醒时出现崩溃，按故障说明排除了任务管理器的启动选项，未使用管理员身份，曾使用2.4版本未出现上述情况

### 运行平台

Windows 桌面

### 软件版本

beta（2.7.3）

**Comment by 124bill** [comment]
改用32bit版本仍有出现类似情况，可能存在于word F1帮助快捷键冲突问题，替换后暂未出现崩溃闪退情况

**Comment by liulex** [comment]
2.8 版本应该修复了这个情况，如还有问题请再留言。

**Comment by yangbohz** [comment]
2.8.2依然有这个问题。商店版本。睡眠后必须重新打开一次。

**Comment by hu516** [comment]
2.8.4也还有有这个问题，日志如下

> 
[splog.txt](https://github.com/Snipaste/feedback/files/10712897/splog.txt)
