### ISSUE TITLE
M1下截屏鼠标滑动不顺畅，w,a,s,d也没反应

### ISSUE THREAD

**Issue by xiehaixin** [Snipaste/feedback#2209]
### 联系方式

xiehaixin@163.com

### 发生了什么？

截图的时候，鼠标的滑动会有明显的不顺畅，卡顿的感觉，W,S,A,D 移动鼠标1像素的功能也没有任何反应

系统平台为：macOS Monterey 12.3.1
芯片：Apple M1 Max
软件版本：v2.7.1

### 运行平台

macOS

### 软件版本

2.7.1

**Comment by liulex** [comment]
[无法检测界面元素无法使用-wasd-键移动鼠标光标](https://docs.snipaste.com/zh-cn/troubleshooting?id=%e6%97%a0%e6%b3%95%e6%a3%80%e6%b5%8b%e7%95%8c%e9%9d%a2%e5%85%83%e7%b4%a0%e6%97%a0%e6%b3%95%e4%bd%bf%e7%94%a8-wasd-%e9%94%ae%e7%a7%bb%e5%8a%a8%e9%bc%a0%e6%a0%87%e5%85%89%e6%a0%87)

**Comment by xiehaixin** [comment]
> [无法检测元素无法使用鼠标指针-wa-sd-键移动鼠标界面](https://docs.snipaste.com/zh-cn/troubleshooting?id=%e6%97%a0%e6%b3%95%e6%a3%80%e6%b5%8b%e7%95%8c%e9%9d%a2%e5%85%83%e7%b4%a0%e6%97%a0%e6%b3%95%e4%bd%bf%e7%94%a8-wasd-%e9%94%ae%e7%a7%bb%e5%8a%a8%e9%bc%a0%e6%a0%87%e5%85%89%e6%a0%87)

wasd可以移动了
