### ISSUE TITLE
多显示器截屏问题

### ISSUE THREAD

**Issue by paschen5770** [Snipaste/feedback#2210]
### 问题描述

我通常使用两个屏幕：MBP自带的Retina屏幕与1个外接显示器（分别记为屏幕A与屏幕B），有时我在屏幕A上写文件时需要截取屏幕B中某区域作为图片插入到当前写的文件中，这时我按下截屏快捷键，可能由于屏幕A当前处于激活状态，Snipaste会锁死在屏幕A，即只能在屏幕A上截图，而不能在屏幕B上截图。我必须按ESC中止，点击一下屏幕B，再按截屏快捷键，这时才能在屏幕B上截图。总结来说，当激活Snipaste截图功能后，只能在当前活动的屏幕上选择截图区域，即使此时将鼠标移到另一屏幕，也无法再另一屏幕截图。

我无数次被这个问题所打断，起初我以为是由于MAC系统层面的限制，后来我发现MAC上的iShot软件则不会有这个问题，同样MAC本身的Command+3/4也不会限制在某一屏幕，因此应该是软件BUG或开发者有意这样设计，如果是BUG，希望能尽快修复一下，如果是有意这么设计，希望开发者能增加一个可以在多屏间直接截屏的选择，因为当前的多屏下的操作逻辑对我来说确实不太直觉与方便。

### 运行平台

macOS

### 软件版本

2.7.2-beta

**Comment by fengwangatkyndryl** [comment]
我的也有同样的症状，MacBook pro2019，也是2.7.2-beta版。同时我还有一台Windows的，是2.7.3版，就没有此问题。感觉应该是bug吧，希望赶快修复，用起来很不方便。目前我自己使用的代替解决方案是，在分屏右上角直接按snipaste的图标进行截图。。。

**Comment by liulex** [comment]
dup of #2211.
