### ISSUE TITLE
无法自动选取firefox窗口的页面元素

### ISSUE THREAD

**Issue by asf00404** [Snipaste/feedback#2213]
### 问题描述

windows 11  firefox 100.0
已查阅过文档，accessibility.force_disabled 已经设置为0 但依旧无法自动选取页面元素  只能截全屏
![图片](https://user-images.githubusercontent.com/21360958/168453316-cffff462-145e-4470-966d-6dc4d4f2f8ce.png)
![图片](https://user-images.githubusercontent.com/21360958/168453355-40f1f252-1bf5-43e2-9898-d9caa2d8a06a.png)

### 运行平台

微软商店

### 软件版本

2.7.3 (2022.01.30)

**Comment by liulex** [comment]
Firefox 100.0 on Windows 10 / 11 无法复现 。
