### ISSUE TITLE
重複存成兩個檔

### ISSUE THREAD

**Issue by JamesHsutobii** [Snipaste/feedback#2223]
### 联系方式

jamcyy@gmail.com

### 发生了什么？

每次截圖存檔後都會存成兩個重複的檔案
僅有時間點會有些許落差

### 运行平台

Windows 桌面

### 软件版本

1.16.2

**Comment by liulex** [comment]
一个是你在文件对话框保存的，另一个是勾选了“自动保存”保存的。
