### ISSUE TITLE
设置样式小问题

### ISSUE THREAD

**Issue by 0x-jerry** [Snipaste/feedback#2225]
### 发生了什么？

![image](https://user-images.githubusercontent.com/14226737/170849600-925a2222-85cb-49ae-8810-85620cee528f.png)
这个配置项太窄了，如果宽一点，可能好看一点点

### 运行平台

macOS

### 软件版本

Version 2.7.2-Beta (2022.01.26)

**Comment by liulex** [comment]
2.8-Beta 会修复此问题。
