### ISSUE TITLE
貼圖標註可否加入數字序列圖標

### ISSUE THREAD

**Issue by highwaysix** [Snipaste/feedback#2226]
### 功能描述

新增此功能，將可使這個軟體成為最頂尖的截圖軟體，謝謝。

**Comment by chenrylee** [comment]
Added two years ago: https://github.com/Snipaste/feedback/issues/227

**Comment by chenrylee** [comment]
Added two years ago: https://github.com/Snipaste/feedback/issues/227

**Comment by Geeyun-JY3** [comment]
文档里也写得很清楚，请购买专业版哦：https://docs.snipaste.com/zh-cn/pro?id=snipaste-2-专业版免费版-对比

**Comment by Geeyun-JY3** [comment]
Duplicate of #227
