### ISSUE TITLE
使用命令行，截图后怎么才能获取到截图左上角的坐标

### ISSUE THREAD

**Issue by WabbyWabbo** [Snipaste/feedback#2229]
### 问题描述

例如，截取全屏时，起点就是(0,0)，终点就是(1920,1080)，怎么才能拿到这些数据？
似乎截图完成后，只能拿到该图片的宽和高。

![Image 6](https://user-images.githubusercontent.com/65695568/171159895-e6aaec5c-6d34-490d-81f2-2328c0d94b66.png)

### 运行平台

Windows 桌面

### 软件版本

Snipaste-1.16.2-x64

**Comment by liulex** [comment]
没有这个接口。
