### ISSUE TITLE
希望增加备用字体选项

### ISSUE THREAD

**Issue by GabrielxDuO** [Snipaste/feedback#2230]
### 问题描述

希望在贴图-转换-字体中增加备用字体(第二字体)选项。
<img width="359" alt="Snipaste_2022-06-01_16-09-18" src="https://user-images.githubusercontent.com/62609211/171358228-7cec3972-5b11-4e3b-b3c0-8747978a085c.png">

### 运行平台

微软商店

### 软件版本

2.7.3

**Comment by liulex** [comment]
什么情况下使用备用字体呢？

**Comment by GabrielxDuO** [comment]
> 什么情况下使用备用字体呢？

有的字体没有中文字形。比如我想主字体用 Cascadia Code，然后缺失的中文部分用 HarmonyOS Sans SC 补全这样的。

**Comment by liulex** [comment]
Snipaste 依赖 Qt，Qt 的字体显示不支持自定义 fallback 字体。 @GabrielxDuO
