### ISSUE TITLE
通过远程标注输入文本时无法输入c（与输入法无关）

### ISSUE THREAD

**Issue by kymowang** [Snipaste/feedback#2231]
### 发生了什么？

居家办公，通过向日葵软件远程公司电脑，使用F1在远程电脑上启用截图功能，标注文本时无法输入字母`c`，其他按键没有影响
系统版本：`Microsoft Windows [Version 10.0.19044.1706]`

### 运行平台

微软商店

### 软件版本

1.16.2(2018.01.22)

**Comment by Geeyun-JY3** [comment]
请
善
用
搜
索https://github.com/Snipaste/feedback/issues/640#issuecomment-346732910 https://github.com/Snipaste/feedback/wiki/高级设置/d69cbd063f8d669ceefe4a7d498f2e0a4126406b#snip

**Comment by kymowang** [comment]
多谢！这个确实没想到去搜一下，我一直以为是向日葵跟snipate冲突。

**Comment by JasonLam90** [comment]
这个可能和内置快捷键有关，我看里面有一个通用快捷键是放大镜可见时，复制颜色值，快捷键是C。没想到还真有人反馈这个问题了【多多捂脸】
