### ISSUE TITLE
贴图在win 11上不能取消“固定到所有虚拟桌面”

### ISSUE THREAD

**Issue by ZhuangQu** [Snipaste/feedback#2233]
### 发生了什么？

在设置界面中，我已经取消勾选`固定到所有虚拟桌面`，然而在使用过程中，贴图仍然是固定到所有虚拟桌面，就跟勾选了一样。

### 运行平台

微软商店

### 软件版本

2.7.3（pro）

**Comment by liulex** [comment]
2.8 会修复该问题。

**Comment by godefy** [comment]
> 2.8 会修复该问题。

我目前用的2.8.4专业版，仍然会出现这个问题。
