### ISSUE TITLE
能不能设置截图的图片格式？

### ISSUE THREAD

**Issue by mrjeke** [Snipaste/feedback#2238]
### 功能描述

现在默认是png格式的截图，但是截图下来的png格式大小显然是比jpg格式的图片体积要大。希望可以自定义截图的格式为jpg。

**Comment by chenrylee** [comment]
本来就支持jpg格式，请参考下图：  
![image](https://user-images.githubusercontent.com/10664121/172842760-888bb63e-7f20-4d3c-a3cf-1c8c6ce83757.png)

**Comment by mrjeke** [comment]
> 本来就支持jpg格式，请参考下图： ![image](https://user-images.githubusercontent.com/10664121/172842760-888bb63e-7f20-4d3c-a3cf-1c8c6ce83757.png)

鼠标滑动截图，快捷键CTRL+C复制下的图片是png格式的，如何修改成jpg格式？

**Comment by scorpion19961007** [comment]
你们是真看懂楼主问的了吗？人有说不支持吗.jpg吗？。。。人问的是如何默
![Snipaste_2022-06-21_08-12-15](https://user-images.githubusercontent.com/62248110/174691467-c8fa86e6-d566-48d7-86ec-554df44c9d0a.png)
![K1N0`@HH22RFVGQIFL {58S](https://user-images.githubusercontent.com/62248110/174691473-715ec592-f03b-48de-930a-5cb2d7f197f1.png)
认设置为.jpg，我在输出设置改为.jpg，保存的时候还是png格式的

**Comment by Geeyun-JY3** [comment]
关联：#1940

**Comment by liulex** [comment]
@scorpion19961007 设置为 jpg，保存文件对话框还是 png，原因是 Snipaste 会记住你上一次用的图片扩展名。你手动保存一次 jpg 后，下一次再保存就会变成 jpg 了。

Snipaste 2.8 会新增一个选项：
![image](https://user-images.githubusercontent.com/2010459/196208932-37109088-72a3-4a19-966b-3f7f9fd29280.png)

**Comment by ilcpm** [comment]
说一个问题，jpg并不适合存储计算机图像，尤其是图片内容含有文字时， 以下图片是相同内容截图后在jpg和png格式下无插值缩放算法的情况下放大4倍的对比

jpg图像26KB，文字的周围一堆噪点
![image](https://user-images.githubusercontent.com/36830343/201461347-bbcc397b-86a8-41dd-ae55-b8728dfa08b8.png)

png图像48KB，文字清晰，周围无噪点
![image](https://user-images.githubusercontent.com/36830343/201461436-cd9d64aa-7002-4d3c-8d79-c798a857ea6a.png)

**Comment by LoneFireBlossom** [comment]
这个问题似乎在Mac上并没有解决，我这样设置，截图粘贴得到的图片还是png

<img width="718" alt="image" src="https://github.com/Snipaste/feedback/assets/50087596/2cc023d9-f5ad-41bc-8cf3-693dfcc52947">

**Comment by Geeyun-JY3** [comment]
> 这个问题似乎在Mac上并没有解决，我这样设置，截图粘贴得到的图片还是png

本 issue [解决方案增加的这个选项](https://github.com/Snipaste/feedback/issues/2238#issuecomment-1280986292)是针对`手动保存`的，你说的「截图粘贴」是指什么？涉及到`手动保存`了吗？

**Comment by LoneFireBlossom** [comment]
> > 这个问题似乎在Mac上并没有解决，我这样设置，截图粘贴得到的图片还是png
> 
> 本 issue [解决方案增加的这个选项](https://github.com/Snipaste/feedback/issues/2238#issuecomment-1280986292)是针对`手动保存`的，你说的「截图粘贴」是指什么？涉及到`手动保存`了吗？

就是楼主在2楼发的这个 https://github.com/Snipaste/feedback/issues/2238#issuecomment-1151061985
