### ISSUE TITLE
保持分辨率的情况下对本地（非本软件截图）图片压缩

### ISSUE THREAD

**Issue by Hinlavic** [Snipaste/feedback#2239]
### 功能描述

不少网站对图片的大小有要求，SNIPASTE非常适合日常的图片处理，希望可以将图片压缩的功能也加入到软件中，都是常用的图片功能。
直接改变图片的分辨率或DPI对图片的显示效果影响很大，可以采用改变图片的压缩算法的方式，在图片整体观感没有太大变化的情况下，对图片多次压缩，一次大小不够，再压一次，或者直接设定需要的压缩后图片大小，一步到位。

**Comment by liulex** [comment]
请使用图像处理软件，Snipaste 不是。
