### ISSUE TITLE
自定义截图太麻烦，用户体验太差了

### ISSUE THREAD

**Issue by goomoon** [Snipaste/feedback#2240]
### 功能描述

问题：
现有自定义截图操作体验太差了，【快捷键】--先出来个选择框--【选择点击确定】--出来个截图框--【调整左上角位置】--【调整右下角位置】--【点击截图】，一共要操作5次+2次展示，才能完成一个最简单的截图操作；这个体验太差太差太差了，完全对不住这个软件强大的功能

建议：
可以参考 Xnip 软件，【快捷键】-- 当前鼠标位置为左上角位置--【拖拉鼠标点击为右下角位置】，一共要操作2次+1次展示，完成最简单的截图操作；而且体验非常顺畅

详细参见：https://zh.xnipapp.com/

**Comment by GregAMO** [comment]
默认截图框是自动检测界面元素\窗口元素，方便一次性选择。如果你不想按照界面元素截取，可以直接像你说的，左键按住，从左上角到右下角拖拽。

**Comment by Geeyun-JY3** [comment]
直接用普通的截屏就能实现你要的吧，就是需要长按左键，像楼上说的：按截屏的快捷键 > 长按左键并同时拖拉鼠标 > 松开即预览效果

**Comment by goomoon** [comment]
> 默认截图框是自动检测界面元素\窗口元素，方便一次性选择。如果你不想按照界面元素截取，可以直接像你说的，左键按住，从左上角到右下角拖拽。

感谢回复，用惯其它截图软件，有思维惯性了。以为截屏=>截取整个屏幕，没尝试理解错了，软件功能非常赞，谢谢。另外，为避免有人跟我一样理解错了；建议将 截屏=>窗口截屏 之类的名称，只是建议不一定合理哈~~~

**Comment by Geeyun-JY3** [comment]
> 另外，为避免有人跟我一样理解错了；建议将 截屏=>窗口截屏 之类的名称，只是建议不一定合理哈~~~

勾选了「自动检测窗口」和「自动检测界面元素」选项才会在按截屏的快捷键后直接就有个截图框，显然没必要这么改。

**Comment by goomoon** [comment]
@Geeyun-JY3 你好，另外请问下，在 mac 系统下是否支持滚动截图操作，按网上说的【捕捉鼠标指针】选中即可；但试了下貌似没作用。

系统版本：mac os 12.3.1
