### ISSUE TITLE
超级截屏无法拖拽

### ISSUE THREAD

**Issue by fty1777** [Snipaste/feedback#2242]
#### 配置
超级截屏快捷键设置为“win”，鼠标左键拖拽操作设置为“截图并贴图”（默认设置）。
#### 操作和遇到的问题
按住win和鼠标左键，会延迟一段时间后出现 1 x 1 px界面，但无论如何拖拽都无法扩大选取，导致截图失败。

如果按下鼠标左键后在出现截图框之前就拖拽，则实际的截图起始位置是出现截图框（1 x 1 px和一个小蓝矩形）时鼠标所处的位置，与按下鼠标左键时的位置相比偏移很大。

无论如何，无法通过按住鼠标左键拖拽正确选区，从而完成截图。

#### 其他现象

可以通过鼠标左键点击后松开鼠标左键，此时可以正常改变选区，再次点击左键后截图并贴图成功？但是界面明显卡顿。

### 运行平台

微软商店

### 软件版本

2.7.3

**Comment by fty1777** [comment]
补充：多显示器下会出现该问题，单显示器不会。

**Comment by scruel** [comment]
> 补充：多显示器下会出现该问题，单显示器不会。

同遇到

**Comment by yl5408** [comment]
加1

**Comment by yl5408** [comment]
本人是不同分辨率的显示器，一个4k，两个1080，目前妥协方法是把4k调成1080

**Comment by fty1777** [comment]
> 本人是不同分辨率的显示器，一个4k，两个1080，目前妥协方法是把4k调成1080

猜测是否可能和两个显示器的缩放比例大小不同有关？（例如175%+125%），我的两个显示器虽然具有相同分辨率，但由于屏幕物理尺寸不同，我使用了不同的缩放比例（175%+150%），此时问题出现。

**Comment by liulex** [comment]
2.8 已修复该问题，请等待近期发布。
