### ISSUE TITLE
在win浅色或深色主题下，任务栏上的snipaste图标变的异常难看，希望能改进，见截图！

### ISSUE THREAD

**Issue by xujieone** [Snipaste/feedback#2243]
### 联系方式

QQ：110480621

### 发生了什么？

在win浅色或深色主题下，任务栏上的snipaste图标变的异常难看，希望能改进，不知道哪里能上传截图？

### 运行平台

Windows 桌面

### 软件版本

2.7.3 pro版

**Comment by Geeyun-JY3** [comment]
直接粘贴就能上传，或点击文本输入框下方横条就能弹出对话框

另外你说的任务栏图标，是不是通知区域（托盘）的图标？
如果是，这是能自定义的
![image](https://user-images.githubusercontent.com/49396421/174421751-b55a22c6-5fae-4944-beb6-106ed6741dba.png)

**Comment by xujieone** [comment]
不是托盘里的图标。是把程序固定到任务栏上的图标。图标有灰色底色很难看。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Geeyun-JY3 ***@***.***&gt;
发送时间: 2022年6月18日 11:50
收件人: Snipaste/feedback ***@***.***&gt;
抄送: xujieone ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Snipaste/feedback] 在win浅色或深色主题下，任务栏上的snipaste图标变的异常难看，希望能改进，见截图！ (Issue #2243)





 
直接粘贴就能上传，或点击文本输入框下方横条就能弹出对话框
 
另外你说的任务栏图标，是不是通知区域（托盘）的图标？
 如果是，这是能自定义的

**Comment by Geeyun-JY3** [comment]
任务栏图标和默认 Windows 模式（非默认应用模式）有关，还是来 GitHub 发截图吧。

**Comment by xujieone** [comment]
好的。我也可以在邮件里回复截图。现在手机回复邮件。




发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Geeyun-JY3 ***@***.***&gt;
发送时间: 2022年6月18日 13:49
收件人: Snipaste/feedback ***@***.***&gt;
抄送: xujieone ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Snipaste/feedback] 在win浅色或深色主题下，任务栏上的snipaste图标变的异常难看，希望能改进，见截图！ (Issue #2243)





 
任务栏图标和默认 Windows 模式（非默认应用模式）有关，还是来 GitHub 发截图吧。

**Comment by Geeyun-JY3** [comment]
邮件回截图 GitHub 看不到的。

**Comment by xujieone** [comment]
晚上我试试发帖吧！看看截图能不能直接粘贴在回复框里。




发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Geeyun-JY3 ***@***.***&gt;
发送时间: 2022年6月18日 14:31
收件人: Snipaste/feedback ***@***.***&gt;
抄送: xujieone ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Snipaste/feedback] 在win浅色或深色主题下，任务栏上的snipaste图标变的异常难看，希望能改进，见截图！ (Issue #2243)





 
邮件回截图 GitHub 看不到的。

**Comment by xujieone** [comment]
![xujieone_2022-06-18_18-19-10](https://user-images.githubusercontent.com/92794775/174433462-4179292b-cfbf-4c18-88f8-ca979a74be3a.png)

**Comment by xujieone** [comment]
个人感觉  去掉灰色的底色，或者把彩色的logo换成白色的logo＋灰色底色（底色最后为圆角），这样和win11 UI 能匹配、统一，也协调！

**Comment by Geeyun-JY3** [comment]
> ![xujieone_2022-06-18_18-19-10](https://user-images.githubusercontent.com/92794775/174433462-4179292b-cfbf-4c18-88f8-ca979a74be3a.png)

这个是跟随的你设置的主题色。
而且这是在默认 Windows 模式为浅色时的样子，默认 Windows 模式为深色时整个图标就为纯白色，无底色背景。

**Comment by liulex** [comment]
下个版本会改进:
![image](https://user-images.githubusercontent.com/2010459/174441925-e0d44184-57ec-4ffc-9ac6-c7454f44c4f1.png)

**Comment by xujieone** [comment]
谢谢。希望尽快升级更新！


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Le Liu ***@***.***&gt;
发送时间: 2022年6月18日 22:02
收件人: Snipaste/feedback ***@***.***&gt;
抄送: xujieone ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Snipaste/feedback] 在win浅色或深色主题下，任务栏上的snipaste图标变的异常难看，希望能改进，见截图！ (Issue #2243)





 
下个版本会改进:

**Comment by Geeyun-JY3** [comment]
2.8 是改成无论默认 Windows 模式为哪种都显示彩色图标了吗？之前只是默认 Windows 模式为浅色是是彩色图标，若默认 Windows 模式为深色则是纯白色，稍微有些不习惯……
![image](https://user-images.githubusercontent.com/49396421/201924528-59e02926-ae9d-40d6-b84e-a6168ef65e66.png)

**Comment by xujieone** [comment]
我个人认为不需要，浅色模式下是彩色的，暗黑模式下就是白色的挺好！！



***@***.***
 
发件人： Geeyun-JY3
发送时间： 2022-12-08 18:54
收件人： Snipaste/feedback
抄送： xujieone; Author
主题： Re: [Snipaste/feedback] 在win浅色或深色主题下，任务栏上的snipaste图标变的异常难看，希望能改进，见截图！ (Issue #2243)
目前磁贴的图标还是纯色且会根据默认 Windows 模式切换。
需要为了保持一致性也改成彩色吗

**Comment by Geeyun-JY3** [comment]
> 我个人认为不需要，浅色模式下是彩色的，暗黑模式下就是白色的挺好！！

我用 Snipaste 2.8.2 Microsoft Store 版本的测试结果是：Windows 模式为浅色时磁贴图标为黑色，Windows 模式为深色时磁贴图标为白色。
