### ISSUE TITLE
希望超级截屏在鼠标左键单点（或拖拽距离小）的时候不会触发

### ISSUE THREAD

**Issue by czh-3** [Snipaste/feedback#2244]
### 功能描述

超级截屏在描述中是 win+鼠标左键**拖拽**触发，但实际在鼠标左键**单击**的时候也会触发（尽管在鼠标点击时会不可避免地出现鼠标位移）
希望能够给超级截屏的触发逻辑中加上**在拖拽距离过小时不触发**（如果能给个参数自行调节就更好了）

实际上，我将超级截屏设置为 ctrl+鼠标左键拖拽，并将鼠标上的辅助按键映射为 ctrl，于是可以仅使用鼠标完成包括超级截屏在内的许多功能，但超级截屏在**单击**时也触发就和常用的 ctrl+单点 多选文件、打开网址 等功能冲突

BTW，你们或许可以超级截屏在第一个按键（win/ctrl/shift/alt）中加入**鼠标中键左击/右击**选项，纯鼠标完成截屏会比需要同时使用鼠标键盘更方便吧，超级截屏不正是为了更加方便快捷
![image](https://user-images.githubusercontent.com/73211682/174418184-cf93de40-c202-40df-b5ac-546911134c4d.png)

**Comment by liulex** [comment]
你提的这些，从实现原理来说就做不到，所以超级截屏的快捷键设置不能跟其他常用操作冲突。
