### ISSUE TITLE
多显示器下截图框无法跨越显示器

### ISSUE THREAD

**Issue by iv835** [Snipaste/feedback#2245]
### 联系方式

kevin.zk.cn@gmail.com

### 发生了什么？

三台显示器，按下F1后，截图框只能在左边和中间的显示器上出现，鼠标移动到右边第三台显示器时，截图框停留在中间显示器的右侧，无法随鼠标移动到右边的第三台显示器上。

### 运行平台

Windows 桌面

### 软件版本

2.7.3

**Comment by fengwangatkyndryl** [comment]
我的mac也是，只接了一个外接屏，点完快捷键，截图区域只显示在Mac本机上，外接屏挪不过去。。。我的是2.72-beta（2022.01.26）版本。

**Comment by liulex** [comment]
应该有一台显示器是在 Snipaste 启动后接上去的。 @iv835 
即将发布的 2.8 应该修复了新接屏幕的识别问题。如届时还有问题，欢迎再反馈。
