### ISSUE TITLE
win11下F1截图失效

### ISSUE THREAD

**Issue by DongY574** [Snipaste/feedback#2246]
### 发生了什么？

点开了全屏窗口，例如word
点开了非全屏窗口，例如微信聊天窗口
此时F1截图会失效

返回桌面，点击，此时F1截图恢复

不知道什么原因

### 运行平台

Windows 桌面

### 软件版本

2.7.3

**Comment by LikeJson** [comment]
快捷键占用了？换一个试试

**Comment by liulex** [comment]
[有时候快捷键不响应](https://docs.snipaste.com/zh-cn/troubleshooting?id=%e6%9c%89%e6%97%b6%e5%80%99%e5%bf%ab%e6%8d%b7%e9%94%ae%e4%b8%8d%e5%93%8d%e5%ba%94)
