### ISSUE TITLE
MAC最新版本无法像之前一样在Finder里复制图片（Command+C）后贴图

### ISSUE THREAD

**Issue by GiHier** [Snipaste/feedback#2247]
### 联系方式

none

### 发生了什么？

MAC公测版本一直使用到现在，之前的版本是可以在Finder里直接复制图片（Command+C）然后使用贴图快捷键贴图的。但在最新版里复制后再贴图显示的不是图片而是预览图标。
<img width="232" alt="image" src="https://user-images.githubusercontent.com/108117771/175481445-99f16534-d10e-4814-9c66-7a91188e67b6.png">

如果通过以下方式复制，贴图又是正常的：
1、直接在截图时贴图，正常。
2、先用「预览」工具打开图片，然后复制，再贴图，正常。

唯独在Finder里直接复制后，贴图就不能正常显示。

### 运行平台

macOS

### 软件版本

v2.7.2-Beta（2022.01.26）

**Comment by shuwn** [comment]
@GiHier 我的很正常，我覺得跟你系統有關，不知道是不是系統哪邊出現了 Bug 造成的

**Comment by GiHier** [comment]
> 

我的是最新的12.4系统，你的也是吗？

**Comment by shuwn** [comment]
> @shuwn 我的是Monterey 12.4系统，你的也是吗？

是的，你能不能提供操作影片確認？

<img width="586" alt="image" src="https://user-images.githubusercontent.com/20023822/181675101-552c4d38-e98d-4964-89d1-47fc45afe7a4.png">

**Comment by GiHier** [comment]
15年的MBP和21年的M1 Pro，系统都是12.4，一样的问题：

影片里所有的操作都是Command+C，然后使用贴图快捷键进行贴图，只有在预览里打开图片再拷贝才能正常贴图

https://user-images.githubusercontent.com/108117771/181865558-974e604e-e0fc-4257-8f0c-03c9cf27c3bb.mp4

**Comment by shuwn** [comment]
@GiHier 
看來我誤會了，確實是會如此，需要 @liulex 幫忙處理了

https://user-images.githubusercontent.com/20023822/181878319-6d058431-d595-4c63-872e-a02be83895b1.mp4

**Comment by liulex** [comment]
-> https://github.com/Snipaste/feedback/issues/2147
下个版本会修复的。
