### ISSUE TITLE
[专业版] 未保存的截图不会进入截图历史

### ISSUE THREAD

**Issue by skyran1278** [Snipaste/feedback#2248]
### 联系方式

ad@u-ran.com

### 发生了什么？

在 F1 截图的过程中, 误触 Esc 会丢失截图 (再按 F3 无法出现). 如影片所示.

https://user-images.githubusercontent.com/20672821/175501741-02a37d37-37d7-4a5d-a348-14fe37545bd9.mp4

已经有打勾包含为保存的截图选项. 如图所示.
![image](https://user-images.githubusercontent.com/20672821/175502389-b5794856-e32b-4ec3-a2dd-28fb6119be74.png)

### 运行平台

微软商店

### 软件版本

2.7.3

**Comment by liulex** [comment]
查看截图历史是进入截图后按这些键：
![image](https://user-images.githubusercontent.com/2010459/196454938-ef917c6f-cb8e-46a9-b955-e0a9a2ebb4d9.png)
不是按贴图键。
