### ISSUE TITLE
截图使用矩形椭圆进行标注的时候希望可以移动

### ISSUE THREAD

**Issue by Gioone** [Snipaste/feedback#2250]
### Problem Description

在进行截图使用矩形进行标注的时候希望按住空格键可以移动矩形区域，更加方便。虽然画完之后拖动矩形仍然可以移动，但这样更加便捷。谢谢

### Platform

Windows Desktop

### Version

2.7.3-Beta

**Comment by liulex** [comment]
专业版支持这个操作。
