### ISSUE TITLE
保存位置希望支持网络驱动器

### ISSUE THREAD

**Issue by uLxy** [Snipaste/feedback#2251]
### 功能描述

如果截图保存位置可以是网络驱动器就好了，如 samba 共享。不知道能否实现

**Comment by uLxy** [comment]
补充一下，刚刚发现其实是是映射的网络驱动器不支持

比如 \\192.168.122.1\share 映射为驱动器 Z:\ 
保存到 Z:\ 提示找不到驱动器，手动改成 \\192.168.122.1\share 就可以了。

**Comment by slime7** [comment]
我也映射了个 z 盘，发现保存不了，即使历史记录里有带 z 盘的文件夹保存时也报错，希望可以支持直接访问映射位置

**Comment by szhu25** [comment]
刚试了一下手动保存到Z盘（SMB网络映射）没问题。
没有试自动保存， 但是可能也许也没问题？

建议看一下软件是不是用管理员模式运行的， 因为管理员模式运行的软件无法访问用户的网络映射盘 [Source](https://www.fmsinc.com/microsoftaccess/developer/mapped_drives_not_available.htm)
