### ISSUE TITLE
在截图中添加注释打字时按c键无响应

### ISSUE THREAD

**Issue by Epilogue1364** [Snipaste/feedback#2254]
### 联系方式

wanglu.skye@outlook.com

### 发生了什么？

![image](https://user-images.githubusercontent.com/89385648/176105785-369b4f8c-cc69-4a51-9de9-d11b8825a732.png)
在这里是大不了c的  不过我另一台电脑可以   重装了也没用

### 运行平台

Windows 桌面

### 软件版本

2.7.3

**Comment by Epilogue1364** [comment]
经过后来的测试发现，应该是在向日葵远程操控软件有交互影响，直接操控那台电脑可以打c。但是使用向日葵远程操控又只是在截图注释时无法使用c，还是挺奇怪的。

**Comment by Epilogue1364** [comment]
> 请善用搜索：#1397 [#640 (comment)](https://github.com/Snipaste/feedback/issues/640#issuecomment-346732910) [https://github.com/Snipaste/feedback/wiki/高级设置/d69cbd063f8d669ceefe4a7d498f2e0a4126406b#snip](https://github.com/Snipaste/feedback/wiki/%E9%AB%98%E7%BA%A7%E8%AE%BE%E7%BD%AE/d69cbd063f8d669ceefe4a7d498f2e0a4126406b#snip)
谢谢！还不知道有这个功能~

**Comment by Geeyun-JY3** [comment]
Duplicate of https://github.com/Snipaste/feedback/issues/640#issuecomment-346732910
