### ISSUE TITLE
Crushed Snip Tips on mixed DPI displays

### ISSUE THREAD

**Issue by Lemmingh** [Snipaste/feedback#2256]
#### 复现步骤

1. 连接多个显示器，并分别设置 **不同** 的缩放级别，如一个 100% 而另一个 200%。

1. 启动 Snipaste。

1. 触发 Snip。

1. 注意到 Snip Tips 扭曲变形，无法阅读：

   ![2022-06-29_Crushed Snip Tips of Snipaste](https://user-images.githubusercontent.com/43396014/176483407-f57797ce-7a05-4de6-81fb-6ec993184cca.png)

#### 可能的解决方案

如果这些组件难以实现 per monitor DPI aware，不妨按最大的缩放级别（在本例中，即 200%）渲染。

### 运行平台

微软商店

### 软件版本

2.7.3

**Comment by liulex** [comment]
2.8 会修复此问题。
