### ISSUE TITLE
增加截图的圆角功能边框的阴影能设置为透明

### ISSUE THREAD

**Issue by dongbingliu** [Snipaste/feedback#2257]
### 功能描述

类似这样的效果
![image](https://user-images.githubusercontent.com/7981299/176816358-a054497a-b13b-49d7-884a-922ce9513a90.png)

**Comment by Geeyun-JY3** [comment]
你这标题是想说什么……

**Comment by dongbingliu** [comment]
<img width="853" alt="image" src="https://user-images.githubusercontent.com/7981299/176986171-150f0d83-afdc-428b-93c3-561d9928200a.png">

**Comment by Geeyun-JY3** [comment]
Mac 版阴影截图（？）：#1908
圆角：#1510、#1928

（你标题我反正是完全看不懂，也没断句

**Comment by dongbingliu** [comment]
不好意思标题描述的不清楚 @Geeyun-JY3 

重新使用图片标记出来了2个希望增加的功能

![image](https://user-images.githubusercontent.com/7981299/177944344-8fd6aa0a-4c8e-4833-b436-249efdc1ca81.png)

**Comment by septs** [comment]
Duplicate of #1510

**Comment by dongbingliu** [comment]
2024-01-11 ， 多谢开发已经支持
