### ISSUE TITLE
Win系统ctrl+f1截图之后，截出的图像不停留，秒保存，不能标注，是怎么回事呢

### ISSUE THREAD

**Issue by GarboYang** [Snipaste/feedback#2259]
### 发生了什么？

你好，请问Win系统ctrl+f1截图之后，截出的图像也不在屏幕上停留，秒保存了，更不能标注，是怎么回事呢
我对了一下Mac上的设置，几乎一样，但Win 从来不能标注……
win2.7.3  mac 2.7.1

### 运行平台

Windows 桌面

### 软件版本

win2.7.3

**Comment by Geeyun-JY3** [comment]
<kbd>Ctrl</kbd> + <kbd>F1</kbd> 默认是截图并自动复制啊：https://docs.snipaste.com/zh-cn/changelog?id=v113

**Comment by GarboYang** [comment]
> Ctrl + F1 默认是截图并自动复制啊：https://docs.snipaste.com/zh-cn/changelog?id=v113

非常感谢，着实纳闷了很久😂
