### ISSUE TITLE
Request: easy number marking | 数字序号标注

### ISSUE THREAD

**Issue by solariz** [Snipaste/feedback#227]
Hi,

great Tool ! A short feature request of something I really miss in snipaste.
Coming from "Greenshot" I miss the Option to add "mark bubbles":

![snipaste20161116_112523](https://cloud.githubusercontent.com/assets/4168339/20343628/681bccd6-abef-11e6-8a63-88585ade21f9.png)

Like in this Shot the (1) (2) (3), meaning: A function which give me the possiblity to automatically highlight parts of the screenshot with "Number Bubbles" wich continuously count up on each I add.

Hope I could explain well :)

🔢 

Thanks

**Comment by liulex** [comment]
Hi,

Thanks for the suggestion.

Actually this feature has been requested before. #15 
But that post wanted the 'mark bubbles' to maintain counting across the image windows, which made me very confused so I said no to it.
If it's just for a single image (or for snipping), the feature could be considered.

However, I think it's better not to implement it until another feature #79 is available, which is to allow the user to directly select a finished shape and perform copy/paste/delete actions.

P.S. The issues I mentioned above are just for other users' convenience, not asking you to check duplicates with Chinese issues before posting.  We welcome English issues. :-)

**Comment by dlsdgj** [comment]
暂时可以这么替代
![snipaste20161119_201342](https://cloud.githubusercontent.com/assets/20112812/20455392/13d7d102-ae96-11e6-84d3-3a93ab23086c.png)

**Comment by dlsdgj** [comment]
暂时可以这么替代
![snipaste20161119_205303](https://cloud.githubusercontent.com/assets/20112812/20455583/43d42730-ae9a-11e6-86cb-9864d9b6c877.png)

**Comment by dlsdgj** [comment]
暂时可以这么替代
![snipaste20161119_205532](https://cloud.githubusercontent.com/assets/20112812/20455604/b40a8bca-ae9a-11e6-967d-28dbe095d0d8.png)

**Comment by dlsdgj** [comment]
@liulex 我才发现,直接拖动图片到贴图窗口是替换贴图... 那能不能不用替换,而是直接新建一个贴图,暂时方便使用图章的用户？

**Comment by GregAMO** [comment]
@dlsdgj 那不是复制图片并贴出就可以了？

**Comment by dlsdgj** [comment]
@GregAMO  是这样的,只是我觉得相对于直接拖放的操作,Ctrl+C→F3可以说是多出来的步骤,
————————————————————————
刚刚发现设置贴图→行为→新图片被贴出时选择"激活"选项,这样做,在拖动图片到贴图上并替换了原贴图后可以**立即**按F3键恢复原贴图 .   省了"Ctrl+C"的操作,好吧我不太喜欢Ctrl+C .
![snipaste20161120_135723](https://cloud.githubusercontent.com/assets/20112812/20460765/509ce980-af2a-11e6-8be6-d667c9b38579.png)
![snipaste20161120_135713](https://cloud.githubusercontent.com/assets/20112812/20460774/9dadf796-af2a-11e6-816f-adb00f935d99.png)

**Comment by liulex** [comment]
。。。作图好专业……
可以给拖拽加个选项，不过得等下下个版本了，因为下个版本已经翻译好了。

**Comment by GregAMO** [comment]
@dlsdgj 利用命令行更方便了，不必打开文件夹
`--paste-files FILE1 FILE2 ...`
贴出一组常用数字序号，1到3 或 1到6

**Comment by dlsdgj** [comment]
@GregAMO 我能切换贴图组,但贴图片不会,应该怎么做？
![snipaste20161125_205250](https://cloud.githubusercontent.com/assets/20112812/20625970/59b7ba74-b351-11e6-9a49-e437c24bc2f7.png)

**Comment by liulex** [comment]
@dlsdgj 
目前这个参数只能处理绝对路径，我下版本加上相对路径吧。

**Comment by GregAMO** [comment]
@liulex 比较常见的是同一个路径下的不同文件名，现在是贴多少张图输入多少次那个路径…

**Comment by liulex** [comment]
@dlsdgj @GregAMO 
1.10.2 已支持使用文件夹路径作为参数。

**Comment by sevelee** [comment]
一些时候想在截屏的时候添加标记，类比别的截图软件会有一个快捷的添加序号的功能。
![image](https://user-images.githubusercontent.com/8036235/61347725-916b5c00-a890-11e9-8a0f-ded32fd4366a.png)
![image](https://user-images.githubusercontent.com/8036235/61347734-9c25f100-a890-11e9-81ff-0b1dd3d9ef98.png)
只需要点击即可自动按顺序添加1 2 3 4 5…

**Comment by UncleUncleWang** [comment]
这个功能我也很想要，交互设计师/产品经理，有时候要在原型的截图上，进行数字标号，并贴到Wiki上，根据标号进行细节的解释，对此功能是很有迫切的需求的。

**Comment by linzyjx** [comment]
@UncleUncleWang 这个可以有

**Comment by cooper1x** [comment]
目前这个功能支持了吗？

**Comment by liulex** [comment]
Number marking will  be available for Snipaste 2.4 PRO.
Snipaste 2.4 专业版即支持序号标注：
![number marking](https://i.v2ex.co/CKHXqUW2.gif)

**Comment by sevelee** [comment]
太棒了！感谢开发组

**Comment by jiangjiamin** [comment]
好像mac版还还不支持这个功能

**Comment by cooper1x** [comment]
> 好像mac版还还不支持这个功能

貌似要专业版才可以 @jiangjiamin

**Comment by pengfeichencpf** [comment]
不是所有的用户都是win，Mac端还没有呢

**Comment by sato94** [comment]
> 不是所有的用户都是win，Mac端还没有呢

MAC端好像没PRO版吧？而且MAC不是有更好的截图软件可以选择吗

**Comment by pengfeichencpf** [comment]
> > 不是所有的用户都是win，Mac端还没有呢
> 
> MAC端好像没PRO版吧？而且MAC不是有更好的截图软件可以选择吗

现在没有不代表以后没有，现在仍然是beta版本。专业版是灰色，说明以后会有专业版。现在没有开放。
