### ISSUE TITLE
贴到屏幕上的图能否添加半透明支持?

### ISSUE THREAD

**Issue by menzi11** [Snipaste/feedback#2271]
### 功能描述

贴到屏幕上的图能否添加半透明支持? 比如右键菜单可调透明度. 这样可以方便的进行贴在屏幕上的图和屏幕当前内容的比对.

**Comment by Geeyun-JY3** [comment]
https://docs.snipaste.com/zh-cn/faq?id=常见问题
> 7. 贴图的透明度不能单独调节？
>
>    可以，<kbd>Ctrl</kbd> + <kbd>鼠标滚轮</kbd>。
