### ISSUE TITLE
“首选项...→输出→文件→手动保存→文件名:”中填写的后缀希望在“图像另存为”对话框中，只出现在“保存类型:”下拉列表中，而不出现在“文件名:”输入框中

### ISSUE THREAD

**Issue by wcjok** [Snipaste/feedback#2272]
### 功能描述

![20220717111352-反馈意见](https://user-images.githubusercontent.com/84137539/179382277-f1edcb26-8fab-4869-b168-f68050875ba9.png)
如箭头处所示，在红色框内填写的内容准确的填写到箭头处的输出结果中了，并且后缀名也被填入进去了。但是我们经常是想对文件名进行一些修改，然后保存，这个时候，我不得不通过鼠标点击到“-”和“.”中间，或者通过键盘移动光标位置到中间以便输入，对于经常要截图则比较麻烦，希望能修改一下，谢谢！

如果要做到最好，希望能在如图右侧所示的文件名对话框中设置指定光标的位置，当保存的时候，直接光标就是在指定的位置，
这样用户就可以直接输入，而不用调整光标的位置了。

非常感谢作者在百忙之中抽出时间来看看这个问题，谢谢。

**Comment by Geeyun-JY3** [comment]
https://github.com/Snipaste/feedback/issues/2020#issuecomment-968070634

**Comment by Geeyun-JY3** [comment]
Duplicate of #2020

**Comment by wcjok** [comment]
> 在这个对话框里「文件名」处是可以没有文件扩展名的：[#2020 (comment)](https://github.com/Snipaste/feedback/issues/2020#issuecomment-968070634)
我明白您的意思是这个【文件名】输入框处的扩展名可以删除，但是我的意思是这个【文件名】默认不要出现扩展名。
因为其实大家经常会修改这个文件名，如果【文件名】输入框带有扩展名的话，那么就需要将扩展名删除然后输入文件名内容，或者手动将光标移动到扩展名前面输入文件名内容，稍显麻烦。
我也明白可以直接将【文件名】中的所有内容直接删除，但是肯定是希望在截图的时候有一部分自动的命名，比如我上面图片中的时间，我在后面增加上截图的具体内容。不知道我表述明白我的意思没，是否可以将这个问题复活呢？谢谢。

**Comment by Geeyun-JY3** [comment]
重开当然没问题，但你见过有软件实现了这样需求吗（我印象中就只有直接聚焦到文件名部分，不过也找不到实例了，虽然开发者在 https://github.com/Snipaste/feedback/issues/2020#issuecomment-968070634 说 Windows 没有提供这样的接口）

**Comment by liulex** [comment]
#2020 说的很清楚了，Windows 做不到去掉扩展名，除非不用系统的文件保存对话框。@wcjok
