### ISSUE TITLE
截图时的文本输入框希望能够自动换行、手动调整大小，以及默认不超出边界，谢谢。

### ISSUE THREAD

**Issue by wcjok** [Snipaste/feedback#2273]
### 功能描述

和#2200issue类似的， 多行文字不能自动换行，同时超出了截图边界也没有自动动换行，希望增加上这个功能。

同时也不能手动调整输入框的大小并自动换行，希望能增加上这个功能。

希望可以通过点击边框或者其他方法手动调整边框的大小，并自动换行，谢谢。

非常感谢作者百忙之中抽出时间处理这个问题。

![20220717114355-自动换行问题反馈](https://user-images.githubusercontent.com/84137539/179383147-d9b7db4c-3748-4c15-ad88-1cb18b8ee871.png)
![20220717114947-手动调整大小2](https://user-images.githubusercontent.com/84137539/179383152-155a9508-ec98-4ffc-8889-53b2e9384be9.png)

**Comment by Geeyun-JY3** [comment]
既然和 #2200 相关在那跟评就行

**Comment by Geeyun-JY3** [comment]
Duplicate of #2200

**Comment by wcjok** [comment]
> 既然和 #2200 相关在那跟评就行

但是我这个也提出了一些新的想法嘛，比如不自动超出边框，然后调整边框大小，如果您细看我的建议，肯定还是和#2020有所区别，但是大体思路是类似的，都是要自动换行。谢谢。

**Comment by Geeyun-JY3** [comment]
我知道有所区别，但主要需求的功能还是一样的，细节上的东西在那边跟评补充即可。
