### ISSUE TITLE
希望Snipaste的标注箭头能增加上双向箭头的功能，谢谢。

### ISSUE THREAD

**Issue by wcjok** [Snipaste/feedback#2274]
### 功能描述

在有的截图中，希望能有双向箭头来实现两个内容的对比
但是现在Snipaste的标注只有单向箭头，希望能增加上双向箭头
的功能。

感谢作者百忙之中抽出时间处理这个问题，谢谢。

![20220717120347-双向箭头功能反馈](https://user-images.githubusercontent.com/84137539/179383503-1e07f570-e266-4ba5-aeb5-dae78bfb2250.png)

**Comment by chenrylee** [comment]
https://github.com/Snipaste/feedback/issues/843 专业版在2年前就提供了支持。

**Comment by wcjok** [comment]
> 

谢谢，一直用的免费版，没看专业版，现在一看，功能差距还是大，感谢感谢

**Comment by wcjok** [comment]
> #843 专业版在2年前就提供了支持。

谢谢，一直用的免费版，没看专业版，现在一看，功能差距还是大，感谢感谢

**Comment by Geeyun-JY3** [comment]
效果：https://github.com/Snipaste/feedback/issues/2036#issuecomment-979234011

**Comment by Geeyun-JY3** [comment]
Duplicate of #843
