### ISSUE TITLE
关于最大压缩的截图文件，大小还是很大的问题

### ISSUE THREAD

**Issue by btr18** [Snipaste/feedback#2276]
### 发生了什么？

最近使用snipaste截图导入图库文件时，发现snipaste截图的png文件大小特别地大，即使是最高压缩的情况下，也只比自动压缩小那么一点
用QQ自带的截图尝试截取相同大小，导入图库软件后发现大小只有snipaste导入的大概一半
本来截图保存的目的是选取需要的局部来缩小使用空间，但目前局部的截图却比图本身都要大了
希望能提供让图片更小的压缩率设置

### 运行平台

Windows 桌面

### 软件版本

2.7.2 Beta

**Comment by Geeyun-JY3** [comment]
Duplicate of #2067
