### ISSUE TITLE
识别网页元素

### ISSUE THREAD

**Issue by easonglee** [Snipaste/feedback#2278]
### 功能描述

目前的专业版在截图状态下滚动滚轮只能切换浏览器软件本身的父子元素范围，建议在此基础上增加一个web截图模式，在web截图模式下滚动滚轮只会在当前网页中切换web组件元素

**Comment by 2938137849** [comment]
这个功能我记得很早就？但是需要打开浏览器支持

**Comment by 2938137849** [comment]
https://docs.snipaste.com/zh-cn/troubleshooting?id=%e6%88%aa%e5%9b%be%e6%97%b6%e6%97%a0%e6%b3%95%e8%87%aa%e5%8a%a8%e9%80%89%e5%8f%96%e6%b5%8f%e8%a7%88%e5%99%a8%e7%aa%97%e5%8f%a3%e7%9a%84%e9%a1%b5%e9%9d%a2%e5%85%83%e7%b4%a0

**Comment by easonglee** [comment]
感谢！太有用了

**Comment by easonglee** [comment]
> https://docs.snipaste.com/zh-cn/troubleshooting?id=%e6%88%aa%e5%9b%be%e6%97%b6%e6%97%a0%e6%b3%95%e8%87%aa%e5%8a%a8%e9%80%89%e5%8f%96%e6%b5%8f%e8%a7%88%e5%99%a8%e7%aa%97%e5%8f%a3%e7%9a%84%e9%a1%b5%e9%9d%a2%e5%85%83%e7%b4%a0

感谢！太有用了
