### ISSUE TITLE
在截图工具栏添加步骤选项

### ISSUE THREAD

**Issue by jiangjiamin** [Snipaste/feedback#2279]
### 功能描述

您好，在使用过程中，进行发现需要对一些地方圈起来，并标记步骤1,2,3,4....，而做法一般是先通过方框画完，再使用文字去标记步骤，我看在其他的一些工具中，有步骤的做法，就是截图之后点击步骤工具，然后点击到截图上会显示①并输入文字。
此功能在日常使用中还挺频繁的，所以恳请博主可以支持该功能，谢谢！

**Comment by Geeyun-JY3** [comment]
Duplicate of #227

**Comment by jiangjiamin** [comment]
好像mac版还不支持这个功能

**Comment by Geeyun-JY3** [comment]
#2163
