### ISSUE TITLE
在聊天软件里粘贴多张截图或贴图时图裂或发不出

### ISSUE THREAD

**Issue by Otiguy** [Snipaste/feedback#2281]
### 联系方式

yugito@163.com

### 发生了什么？

我的是win商店专业版
重现：
1.首选项 - 输出 - 剪贴板：勾选“同时复制为文件”
2.无论是截图还是贴图，多张粘贴到聊天输入框（企微、飞书）
3.发送

结果：
飞书：除最后一张图，其他都图裂，消息能发出
企微：除最后一张图有显示，其他都显示为“   ”，而且发不出，显示叹号

取消勾选后，重复步骤，功能正常

### 运行平台

微软商店

### 软件版本

2.7.3

**Comment by liulex** [comment]
确实没有考虑到这种使用场景，下个版本会修复。谢谢反馈！
