### ISSUE TITLE
[专业版] 新功能：刷新截图，完全不会用，请教

### ISSUE THREAD

**Issue by ltanzyh** [Snipaste/feedback#2284]
### Problem Description

v2.7.2[专业版] 新功能：刷新截图 (同时保持已有标注不变) #2077
这个新专业版功能，找不到入口和设置，不会用，请大家教学

### Platform

Microsoft Store

### Version

2.7.3

**Comment by lesir831** [comment]
![image](https://user-images.githubusercontent.com/41606776/188483949-ac907a0a-a069-46ee-8433-abb46456eb8b.png)
如图，在截图界面的左上角

**Comment by liulex** [comment]
带上图示了：
https://weibo.com/5991159918/Mf6Jj8H0D
