### ISSUE TITLE
蹲一个Linux版本

### ISSUE THREAD

**Issue by zhangshengping** [Snipaste/feedback#2289]
### Feature Description

知道这个问题重复了！
还是想蹲一个Linux版本！

**Comment by willre** [comment]
我也蹲一个，从mac转 ubuntu了， 现在用 flmaeshot  感觉还是太粗糙了

**Comment by shiliu520** [comment]
我也蹲一个

**Comment by TSaltedfishKing** [comment]
我也蹲一个，也是Ubuntu，希望Wayland和X11都能支持

**Comment by wangzishi** [comment]
我们也将开发环境切换成了 Linux，希望能够推出 Linux 版本的 Snipaste

**Comment by frankcaoyun** [comment]
同蹲！

**Comment by leleplus** [comment]
这么久了  ，还没开发好

**Comment by septs** [comment]
Duplicate of https://github.com/Snipaste/feedback/issues/711

**Comment by MoyanXia** [comment]
同求
