### ISSUE TITLE
可增加初始的画笔颜色的配置文件可选, 现在默认为红色, 希望可以增加其他默认选项

### ISSUE THREAD

**Issue by uniwangwang** [Snipaste/feedback#2296]
### 功能描述

增加画笔颜色的默认初始文件配置选项;
例如增加初始黄色画笔或其他颜色画笔;
当前为红色, 每次都需要更改画笔颜色;

**Comment by liulex** [comment]
只要你没关闭首选项里的“自动备份”，Snipaste 会记住你上次使用的画笔颜色。
