### ISSUE TITLE
macos monterey12.5 软件快捷键正常使用，但是菜单栏没有图标

### ISSUE THREAD

**Issue by Alphapex1** [Snipaste/feedback#2299]
### 发生了什么？

macos monterey12.5 软件快捷键正常使用，但是菜单栏没有图标
设备：macbookair m1 

### 运行平台

macOS

### 软件版本

v2.7.2 Beta

**Comment by Geeyun-JY3** [comment]
有办法隐藏的，检查一下 `config.ini` 文件：https://docs.snipaste.com/zh-cn/advanced-configs?id=general

**Comment by liulex** [comment]
在刘海下面？
