### ISSUE TITLE
希望增加对二维码识别的支持

### ISSUE THREAD

**Issue by willxiang** [Snipaste/feedback#23]
原因：感觉网页上经常会碰到二维码，除了必须用手机扫描后APP内操作的内容，还有不少是一些地址类型的链接，这时候如果能直接截图识别就非常方便了。
截图的时候工具栏增加一个识别二维码，直接对当前截取的二维码进行识别，识别后的文本放到剪贴板直接粘贴可用。
可在设置中勾选是否启用这个功能。
（其实个人做了一个简陋版本QQ截图+二维码识别，但是不如snipaste颜值高，功能强大。）

**Comment by liulex** [comment]
在（较远的）未来可以考虑加入，目前提这个的人不多。

**Comment by GregAMO** [comment]
现在有一枚扩展（[Anything to QRcode](https://chrome.google.com/webstore/detail/anything-to-qrcode/calkaljlpglgogjfcidhlmmlgjnpmnmf)）实现**离线**解析和生成二维码，可以去试试？

但是如果二维码是鼠标悬停才显示或者鼠标放上去开始变化的，那暂时只能用手机了QAQ
（一般这种二维码是付款码，普通二维码扫描器也读不出来信息的样子）

**Comment by willxiang** [comment]
@GregAMO 这个我用过，就是考虑到只能在浏览器中用，所以才提出的（我自己做了一个小工具用来识别任意位置的二维码了，不过还是多谢你的回复）

**Comment by qrqhuang** [comment]
So , is there any progress for this ?

**Comment by SlimeNull** [comment]
我也希望有这个功能...

**Comment by yll690** [comment]
支持+1

**Comment by LongwayHao** [comment]
关心最新进展，同时，希望作者不要太累

**Comment by Vinson1014** [comment]
希望能新增此功能! 
snipaste真的很好用，感謝作者的開發!

**Comment by liulex** [comment]
2.8 版会增加此功能。

**Comment by jamesfancy** [comment]
> 工具栏增加一个识别二维码，直接对当前截取的二维

咋使用这个功能呢，好像没找到文档，截图右键菜单和工具栏上也没找到菜单项或按钮（专业版 2.8.4）

**Comment by Geeyun-JY3** [comment]
> 咋使用这个功能呢，好像没找到文档，截图右键菜单和工具栏上也没找到菜单项或按钮（专业版 2.8.4）

https://weibo.com/5991159918/Mf6Jj8H0D
https://t.me/snipaste/162

**Comment by heartacker** [comment]
我也只专业版，我截图二维码，并没有按照图示一样，显示二维码的识别结果。

> > 咋使用这个功能呢，好像没找到文档，截图右键菜单和工具栏上也没找到菜单项或按钮（专业版 2.8.4）
> 
> [weibo.com/5991159918/Mf6Jj8H0D](https://weibo.com/5991159918/Mf6Jj8H0D) [t.me/snipaste/162](https://t.me/snipaste/162)

**Comment by Geeyun-JY3** [comment]
> 我也只专业版，我截图二维码，并没有按照图示一样，显示二维码的识别结果。

我的建议是，具体描述使用场景，最好附上截图或录屏，另开 issue。
