### ISSUE TITLE
可以增加截图录屏和长截图功能吗

### ISSUE THREAD

**Issue by lrs95** [Snipaste/feedback#2301]
### 功能描述

发现qq的这功能特好用，就是必须登录才行，要是snipaste能支持的话就好了

**Comment by Geeyun-JY3** [comment]
请
善
用
搜
索
#19、https://github.com/Snipaste/feedback/issues/282#issuecomment-268239323、#2130

**Comment by Geeyun-JY3** [comment]
Duplicate of #19

**Comment by Geeyun-JY3** [comment]
Duplicate of #2130
