### ISSUE TITLE
OCR 和 截屏翻译

### ISSUE THREAD

**Issue by rational-stars** [Snipaste/feedback#2304]
### 功能描述

[OCR](https://13315641.s21v.faiusr.com/58/1/ABUIABA6GAAg9untkAYogOStxQE.mp4)
[截屏翻译](https://13315641.s21v.faiusr.com/58/1/ABUIABA6GAAg2dLClQYolLnzlAc.mp4)

顶我 顶我 要是有这两个 我觉得 这个软件就特别完美啦

**Comment by Geeyun-JY3** [comment]
Duplicate of #188
