### ISSUE TITLE
希望增加“重复上次操作”功能

### ISSUE THREAD

**Issue by wuhongyewhy** [Snipaste/feedback#2305]
### 功能描述

在网上听报告，需要对同一个视频区域，不是整个视频窗口，截图，然后粘贴到onenote里面。放映一张ppt，就要重复截图操作。目前只能用picpick来实现，但是我真的喜欢Snipaste的简洁。希望增加上面功能，仅仅在专业版里面也好。

**Comment by chenrylee** [comment]
这个功能免费版也支持的，默认快捷键是截图状态按<kbd>R</kbd>，文档参见： 
https://docs.snipaste.com/zh-cn/key-bindings?id=只对截图有效
