### ISSUE TITLE
“检测页面元素”可能无法适用于基于Firefox的其他浏览器

### ISSUE THREAD

**Issue by pm2kjiagm** [Snipaste/feedback#2307]
### 发生了什么？

Snipaste对“是否为Firefox”的检测可能基于安装路径或者文件名称，这导致基于Firefox的其他浏览器（例如：Waterfox）无法启用这一功能。

复现：
1. 正常安装Waterfox，默认安装路径为%programfiles%\Waterfox。
在此情况下，“检测页面元素”不生效，about:support的无障碍环境“已激活”显示为false；

2. 将%programfiles%\Waterfox的文件夹名称修改为“Mozilla Firefox”
在此情况下，“检测页面元素”生效，about:support的无障碍环境“已激活”显示为true；

3. 将上一步的文件夹名称恢复原状，并将执行文件“waterfox.exe”的文件名修改为“firefox.exe”
在此情况下，“检测页面元素”生效，about:support的无障碍环境“已激活”显示为true；

4. 将上一步的文件名称恢复原状
在此情况下，“检测页面元素”不生效，about:support的无障碍环境“已激活”显示为false。

暂时的回避办法：
将Waterfox安装在%programfiles%\Mozilla Firefox。

需求：
希望增加一个“Firefox所在位置”的参数，以便手动指定。

### 运行平台

Windows 桌面

### 软件版本

2.7.3-Beta

**Comment by liulex** [comment]
是基于文件名的。
下个版本 2.8 我把 `waterfox.exe` 也加上吧。
