### ISSUE TITLE
希望加入启动截图，保存退出功能

### ISSUE THREAD

**Issue by kaiyuanshequ** [Snipaste/feedback#2309]
### 功能描述

这个设计托盘菜单很另类，而且我也不习惯用快捷键，截图时要移动鼠标到托盘，截完图要退出时移动鼠标到托盘，对大屏幕很不友好
因为我用快启软件Claunch启动，希望在选项里加上：
1.启动时直接进入截图状态。
2.点击保存文件和复制到剪贴板后，自动退出。

**Comment by chenrylee** [comment]
首先呢，一个有数百数千万用户的软件不可能因为个别用户的”不习惯“而去更改设计。
其次呢，Snipaste本身就支持带参数启动： https://docs.snipaste.com/command-line-options
