### ISSUE TITLE
超级截图无法使用

### ISSUE THREAD

**Issue by yl5408** [Snipaste/feedback#2310]
### 发生了什么？

超级截图按住鼠标左键拖拽的时候，截图窗口卡顿，截图大小不是鼠标拖拽大小，和普通截图完全不一样，冲着超级截图买的专业版，用起来很糟心

### 运行平台

微软商店, Windows 桌面

### 软件版本

2.7.3

**Comment by liulex** [comment]
2.8 会大幅改进超级截图的可靠性。
