### ISSUE TITLE
Mac取色功能结果不准确

### ISSUE THREAD

**Issue by fuguocheng** [Snipaste/feedback#2317]
### 联系方式

95111938@163.com

### 发生了什么？

在mac下，取色不准确，M1芯片。
![loading](https://user-images.githubusercontent.com/23301642/186104118-26c710f2-e2be-4f91-a7b8-ff766f71c227.gif)
，比如这个图片，在mac下取色，结果为：
屏幕1: 
<img width="835" alt="image" src="https://user-images.githubusercontent.com/23301642/186106019-812c0cec-215c-4828-b1f0-4fe1a787d31b.png">

屏幕2:
<img width="826" alt="image" src="https://user-images.githubusercontent.com/23301642/186105927-8e85907b-dade-4faf-b7e8-76814238dec5.png">

同样的图片，两个屏幕取色值也不一样

而在windows下取值为：
<img width="699" alt="image" src="https://user-images.githubusercontent.com/23301642/186107485-1de4dd3e-8e43-4cf0-967b-5e64012902c4.png">

==================================================
经过测试，发现在windows下的结果是准确的。

希望能尽早修复这个bug
另外，什么时候能在mac上加入高级版？

### 运行平台

macOS

### 软件版本

2.7.2-Beta

**Comment by chenrylee** [comment]
duplicate: https://github.com/Snipaste/feedback/issues/2002

**Comment by fuguocheng** [comment]
所以解决方法是什么？

**Comment by cooper1x** [comment]
改描述文件为`sRGB IEC61966-2.1 `取色正常，但会影响显示效果。

**Comment by septs** [comment]
Duplicate of #2002
