### ISSUE TITLE
mac升级到12.5.1后没法用了，提示开启要授权，不管我怎么授权都不能用了。一点F1就弹窗提示权限问题。

### ISSUE THREAD

**Issue by user-leaf** [Snipaste/feedback#2319]
### 发生了什么？

我原先用的v1.16.2，升级系统到12.5.1后，截屏就只显示桌面。我就升级软件到v2.7.2，点击F1就出现要授权屏幕录制，我取消授权、重启软件、再授权、再重启软件，仍然无法使用，点击F1还是提示需要屏幕录制权限。（我重启过电脑了）
<img width="395" alt="image" src="https://user-images.githubusercontent.com/20150066/186370532-ae8e0a52-55dc-478b-abdb-11653d9e5943.png">
<img width="466" alt="image" src="https://user-images.githubusercontent.com/20150066/186371531-c77728e0-52d1-41b3-bc63-95e38e5251f1.png">

### 运行平台

macOS

### 软件版本

v2.7.2

**Comment by user-leaf** [comment]
可以使用了，操作如下：需要先点减号（-）把APP从系统权限列表里删除掉，再点加号（+）把APP加到列表里。

**Comment by dabing1022** [comment]
> 可以使用了，操作如下：需要先点减号（-）把APP从系统权限列表里删除掉，再点加号（+）把APP加到列表里。

帮了大忙了，感谢
