### ISSUE TITLE
复制到剪切板的截图不可以设置图片质量

### ISSUE THREAD

**Issue by wusyoweu** [Snipaste/feedback#2321]
### 功能描述

希望可以增加设置复制到剪切板截图质量的功能

### 版本

2.7.3

### 系统

Windows11

**Comment by Geeyun-JY3** [comment]
关联：#2171

另见：https://docs.snipaste.com/zh-cn/faq

> 14. 输出的图片质量怎么设置？
> 
>     `-1` 表示自动设置，`0` 表示最低质量，`100` 表示最高质量。
> 
>     对大部分用户来说，使用 `-1` 即可。如设置为 `100`，可能导致图片文件的体积非常大。
> 
>     至于复制到剪贴板中的图像质量，暂时没有提供设置。
