### ISSUE TITLE
付费版本太单一,关于我的建议

### ISSUE THREAD

**Issue by Issl-TM** [Snipaste/feedback#2322]
免费版本挺好用的,基本满足我的需求, 但是我发现少了个我需要的序号标注功能 (在付费版里)

我看到了付费版有很多强大的功能,但对我来说太过专业了,我仅仅是需要其中一些简单的功能
所以我不会为了一点需求去购买专业版 (因为仅需要一些简单基础的功能,所以性价比对我来说较低)
如果有定价更低,升级功能更少的付费版本,我很乐意购买

**Comment by liulex** [comment]
抱歉，暂时没有这个打算。
