### ISSUE TITLE
取消“开机启动”无效，重启电脑后Snipaste依旧躲在托盘里？

### ISSUE THREAD

**Issue by chensjiu** [Snipaste/feedback#2323]
### 问题描述

1、首选项里的“开机启动”已经取消勾选
2、任务计划里的“Snipaste (Run As Admin) @900F”已经选择了“禁用”

可是重启电脑后，Snipaste仍然会自动启动。这是还有哪个位置还需要修改吗？

### 运行平台

Windows 桌面

### 软件版本

2.5.6-Beta

**Comment by Geeyun-JY3** [comment]
先试试最新版？

**Comment by liulex** [comment]
系统设置 > 账户 > 登录选项 > 关闭 “自动保存可重启的应用，并在我重新登录时将它们重启”。
