### ISSUE TITLE
保存路径的命名规则增添请求

### ISSUE THREAD

**Issue by JackASil** [Snipaste/feedback#2325]
### 功能描述

请求在 **输出-文件-命名规则** 中添加“当前贴图/截图所在分组”的变量支持，以便将贴图/截图根据分组保存在对应的文件夹中。

**Comment by liulex** [comment]
截图哪来的分组呢？

**Comment by 1qzhworld** [comment]
> 截图哪来的分组呢？

***

不是可以通过在命令行中使用 `create-group "name"`的方式进行分组吗？可以将这里的name放到命名规则中吗？
我想请求的功能和他类似，但是不是存到文件夹，而是自定义文件名。可以见issue #2570

**Comment by Geeyun-JY3** [comment]
@1qzhworld 问题在于，截图的整个流程并不涉及贴图组。
