### ISSUE TITLE
贴图关闭全部、截屏圆角、贴图阴影可调

### ISSUE THREAD

**Issue by RaigonChen** [Snipaste/feedback#2331]
### 功能描述

首先感谢作者的无私奉献，win版的一直在用。

关于Mac版这里提几个建议，望采纳：
1、贴图增加『关闭全部』选项，避免多个贴图时要一个一个关闭的操作；
2、截屏增加圆角设置；
3、贴图阴影最好能调整，或者跟随系统窗口效果。

**Comment by septs** [comment]
Duplicate of #1510
