### ISSUE TITLE
"Snipaste whiteboard"  命令行如何让只在主屏，鼠标所在屏进行标注呢

### ISSUE THREAD

**Issue by winter60** [Snipaste/feedback#2335]
### Problem Description

rt.
现在使用命令行，发现进行标注的内容是双屏，如何指定单个屏或者默认在鼠标所在屏呢？

### Platform

Windows Desktop

### Version

V2.7.3（2022.01.30）

**Comment by liulex** [comment]
2.8 支持 `whiteboard --active-screen`.
