### ISSUE TITLE
万人血书，请求作者增加截图OCR功能

### ISSUE THREAD

**Issue by shengxq** [Snipaste/feedback#2336]
### 功能描述

我知道发OCR内容是重复的，重复发是为了让作者重视起来

Snipaste用习惯了，也确实好用
美中不足没有OCR功能
现在就得同时安装sharex

如果开发了ocr功能，我愿意捐赠500元

**Comment by gsdukbh** [comment]
我觉得最好吧这个OCR 和 翻译一起开发,放到专业版里面去, 而且现在 的 OCR技术已经很成熟了, 飞浆的OCR技术识别很高啊, [飞浆OCR](https://github.com/PaddlePaddle/PaddleOCR/)

**Comment by ReEmiria** [comment]
同意楼上观点，需要OCR功能，完全替代QQ的截图也不是不可能。（再多个长截图的话）

**Comment by shengxq** [comment]
换verycapture
结贴把
