### ISSUE TITLE
截图贴在屏幕上，鼠标移动屏幕左右上角，隐藏的贴图会自己出现

### ISSUE THREAD

**Issue by yl5408** [Snipaste/feedback#2337]
### 问题描述

截图贴在屏幕上，鼠标移动屏幕左右上角，隐藏的贴图会自己出现，这个有啥方式可以关闭吗，和本人使用习惯冲突，我看了设置，没找到关闭的选项

### 运行平台

Windows 桌面

### 软件版本

2.7.3

**Comment by CCC121** [comment]
<img width="399" alt="Snipaste_2022-10-25_15-24-35" src="https://user-images.githubusercontent.com/64135321/197709771-6f30f950-7143-4783-bbbe-5af714b340d1.png">
如图即可关闭
