### ISSUE TITLE
Windows上连个好用的截图软件都没有

### ISSUE THREAD

**Issue by cv0cv0** [Snipaste/feedback#2338]
### Feature Description

macOS上的Xnip可以在窗口外面加一层阴影，看起来更自然，Windows的截图软件都是贴着窗口边缘截，太丑了。

**Comment by Geeyun-JY3** [comment]
阴影截图需要 Pro：https://docs.snipaste.com/zh-cn/pro?id=%e4%b8%93%e4%b8%9a%e7%89%88%e7%89%b9%e6%80%a7
