### ISSUE TITLE
截图时，ahk映射esc失败，有办法解决么？

### ISSUE THREAD

**Issue by linwan623910** [Snipaste/feedback#2342]
### 问题描述

如题，我想截图时，ahk将esc映射成我要的另外功能，可惜无效，如：
esc:: MsgBox,1

请问怎么设置呢？

### 运行平台

Windows 桌面

### 软件版本

2.4.0

**Comment by linwan623910** [comment]
测试过，贴图下esc可映射成功，截图下不行

**Comment by xntzmk** [comment]
我也碰到了这问题，不过我是贴图和截图里用esc都没有效果，请问你后面怎么解决的

**Comment by liulex** [comment]
Snipaste 对截屏的 Esc 有特殊处理，防止截屏窗口的 Esc 被传到其他程序导致预期以外的行为，例如对网站上的全屏视频截图，如果不做这个处理，会导致 Esc 退出截屏的同时退出了视频全屏。
