### ISSUE TITLE
界面对Windows11不友好

### ISSUE THREAD

**Issue by georgel2020** [Snipaste/feedback#2343]
### 联系方式

georgel2020@163.com

### 发生了什么？

右键托盘中的Snipaste图标，弹出的右键菜单左侧有极明显的空白区域（应当是按钮图标），但Snipaste并未制作图标

### 运行平台

Windows 桌面

### 软件版本

2.7.3-Beta (2022.02.09)

**Comment by liulex** [comment]
2.8 会适配 WIndows 11 的菜单样式。
