### ISSUE TITLE
免费版在MAC上，截图单位是PT，且没有修改入口

### ISSUE THREAD

**Issue by engvuchen** [Snipaste/feedback#2345]
### 问题描述

PT 单位的图片保存下来，刚好是 PX 的两倍；
少一步计算判断简单些；
MAC 上这个问题除了“升级到 PRO”，没有其他解决方法吗？

### 运行平台

macOS

### 软件版本

2.7.2-beta

**Comment by liulex** [comment]
只能等专业版发布了。。。
