### ISSUE TITLE
在安装了Messa3D的Windows平台下无法运行

### ISSUE THREAD

**Issue by Alion548** [Snipaste/feedback#2346]
### 发生了什么？
https://github.com/pal1000/mesa-dist-win#uninstall-messa3d  安装该驱动后，Snipaste 无法正常运行，既没有报错信息，任务管理器也没有Snipaste相关进程。

### 运行平台

Windows 桌面

### 软件版本

2.7.3-Beta

**Comment by liulex** [comment]
2.8 会修复 Mesa 驱动导致  crash.
