### ISSUE TITLE
针对游戏的一键截图 | One-Tap Snapping for Games

### ISSUE THREAD

**Issue by frnksmdlkedjnfr** [Snipaste/feedback#2347]
### 功能描述

能否添加一个一键截图功能，按下快捷键静默截图保存，类似于 Steam 的 F12 截图键。

Can we get a one-tap snapping feature where Snipaste captures and saves the screen silently, like the F12 key in Steam.

**Comment by Geeyun-JY3** [comment]
勾选启用 `自动保存`，再利用专业版的将命令行参数与全局快捷键绑定，即可实现你想要的：https://docs.snipaste.com/zh-cn/pro?id=b-%e6%9b%b4%e8%87%aa%e7%94%b1%e7%9a%84%e5%ae%9a%e5%88%b6%e5%8c%96

#1442

不过游戏截屏这块有言在先……说是不做：https://github.com/Snipaste/feedback/issues/282#issuecomment-268239624
