### ISSUE TITLE
How to disable the magnifier?

### ISSUE THREAD

**Issue by ms-2525** [Snipaste/feedback#2352]
### Problem Description

Is there a shortcut key for enabling and disabling the Magnifier?
The Magnifer is blocking the view when taking snip at the edge of the screen.

### Platform

Windows Desktop

### Version

2.7.3 Beta (2022-02-09)

**Comment by Geeyun-JY3** [comment]
Need Pro: https://docs.snipaste.com/pro?id=b-higher-freedom-of-customization
> 2. Full control of the appearance of the magnifier
