### ISSUE TITLE
切换图片分组的快捷键应该立刻切换

### ISSUE THREAD

**Issue by mefengl** [Snipaste/feedback#2354]
### 发生了什么？

<img width="580" alt="image" src="https://user-images.githubusercontent.com/71683364/195496573-ddd7e69a-3b49-4a57-8452-f0f4af274f72.png">

该快捷键第一次点击是调出image group菜单，第二次点击才是`Switch to another image group`，和功能描述不符。

使用中，往往需要点击两次才能切换到下一分组，相当的不方便

### 运行平台

macOS

### 软件版本

2.7.2-beta

**Comment by mefengl** [comment]
另外，切换后会有一个很卡顿的由半透明变为100%的过程，大约需要2s，去掉这一动效可能更好

**Comment by liulex** [comment]
2.8 会改成直接选中下一个贴图组。
`由半透明变为100%的过程` 这个是为了提醒你贴图的所在位置，我会调整下动画速度。

**Comment by liulex** [comment]
此外，半透明效果可以关闭的：
![](https://user-images.githubusercontent.com/2010459/200121164-72762958-ba90-410c-aa8f-f5c8107d2818.png)

**Comment by mefengl** [comment]
> 此外，半透明效果可以关闭的： ![](https://user-images.githubusercontent.com/2010459/200121164-72762958-ba90-410c-aa8f-f5c8107d2818.png)

了解，谢谢你

**Comment by Geeyun-JY3** [comment]
背景：根据更新日志，在 [1.13 版本](https://docs.snipaste.com/zh-cn/changelog?id=v113)（应该？）加入了切换贴图组会显示的贴图组列表，在[1.15 版本](https://docs.snipaste.com/zh-cn/changelog?id=改进：-9
) 根据 <https://github.com/Snipaste/feedback/issues/556#issue-250515261> 提的需求改为切换贴图组时不自动选中下一贴图组。

没猜错的话本 issue 提到的这个动作对应的是 [`switch-groups`](https://docs.snipaste.com/zh-cn/command-line-options?id=其他命令) 这个命令行选项。
所以文档得改了。

虽然我本人也更偏好切换贴图组时默认选中下一个贴图组，但是现在又改回去会不会有用户不习惯？还是给个开关？或者放在高级设置里？（不过有个开关或高级设置项控制命令行选项好像有些怪怪的）

如果要加上述开关，建议在首选项 > 控制 > 全局快捷键 > 旁边加个提示：该快捷键在关掉上述开关时按第一下不会自动选中下一贴图组。
另外建议[`切换到另一贴图组`（`Switch to another image group`）](https://translations.snipaste.com/translate/snipaste/snipaste/zh_Hans/?checksum=295482fe52e94ede)中的 `另一`（`another`）改成 `下一`（`next`）吧，也更准确（至少增强版托盘菜单的菜单项和首选项 > 控制 > 全局快捷键里的都得改）。

***

顺便问一句，[`切换到上一个组`（`Switch to the previous image group`）](https://translations.snipaste.com/translate/snipaste/snipaste/zh_Hans/?checksum=9949aca91a9083ce)对应的是 [`switch-group-prev`](https://docs.snipaste.com/zh-cn/command-line-options?id=其他命令) 这个命令行选项吗？是的话应用里的这句文案（`previous`）不准确吧，应该和文档的说法保持一致。

***

出于一致性考虑，建议含英文原文「[image group](https://translations.snipaste.com/languages/zh_Hans/snipaste/search/?offset=1&q=image+group&sort_by=-priority%2Cposition&checksum=)」的字符串的译文中都包含「贴图组」。
