### ISSUE TITLE
Paste error after copying image files under Macos

### ISSUE THREAD

**Issue by wushu037** [Snipaste/feedback#2355]
### 发生了什么？

![image](https://user-images.githubusercontent.com/61787040/195873772-5bedf785-1b84-44bf-ba53-38f30212e971.png)

MacOS copy image file in Finder and then paste it, this result will appear

![image](https://user-images.githubusercontent.com/61787040/195873927-cc8156e5-cc3e-4a7b-85ec-a4de007175c0.png)

### 运行平台

macOS

### 软件版本

2.7.2-Bata (2022.01.26)

**Comment by liulex** [comment]
Will be fixed in the coming v2.8.
