### ISSUE TITLE
能不能增加禁用Esc关闭图片的功能

### ISSUE THREAD

**Issue by Thesaurus0** [Snipaste/feedback#2356]
### 功能描述

Pin to Screen之后， 我总是经常性的会按下ESC，我本意不是针对Snipaste, 但因为这个图片在最上面， 它总是关闭我的图片，我又得重新截取一遍图片。 我找了一下， 没有发现，可以哪里可以禁用ESC关闭图片的功能。

**Comment by Geeyun-JY3** [comment]
不小心通过 <kbd>Esc</kbd> 关闭最近一个贴图，再按一次贴图快捷键就刚才的贴图就回来了。

另外重复：#2195

**Comment by Geeyun-JY3** [comment]
Duplicate of #2195

**Comment by Thesaurus0** [comment]
> 不小心通过 Esc 关闭最近一个贴图，再按一次贴图

> 不小心通过 Esc 关闭最近一个贴图，再按一次贴图快捷键就刚才的贴图就回来了。
> 
> 另外重复：#2195

贴图快捷键是哪一个呀？我按了一下，好像它是截整个屏的， 并不是刚才关闭的图片。

**Comment by Geeyun-JY3** [comment]
> 贴图快捷键是哪一个呀？我按了一下，好像它是截整个屏的， 并不是刚才关闭的图片。

请认真阅读文档：https://docs.snipaste.com/zh-cn/

你可以去首选项 > 控制 > 全局快捷键那看看你有没有改过快捷键。
