### ISSUE TITLE
允许给pin to screen自定义快捷键

### ISSUE THREAD

**Issue by Thesaurus0** [Snipaste/feedback#2357]
### 功能描述

我会经常性的用到pin to screen, 能不能让我们可以为这个自定义快捷键？

**Comment by Thesaurus0** [comment]
这个可以有吗？像setuna一样？

**Comment by liulex** [comment]
不是有全局快捷键可以设置吗？

**Comment by Geeyun-JY3** [comment]
感觉这个「pin to screen」说的是目前[只对截图有效](https://docs.snipaste.com/zh-cn/key-bindings?id=%e5%8f%aa%e5%af%b9%e6%88%aa%e5%9b%be%e6%9c%89%e6%95%88)的 <kbd>Ctrl</kbd> + <kbd>T</kbd> 这个组合键对应的功能：https://translations.snipaste.com/translate/snipaste/snipaste/zh_Hans/?checksum=1006ab7fe074d6e2

**Comment by liulex** [comment]
一样的，全局的贴图快捷键也可以在截图的时候按。

**Comment by Thesaurus0** [comment]
你说的那个和我说的不是同一个东西吧？ 你用一下setnua这个软件， 就知道什么意思了。 就是直接按一个快捷键，开始截屏，截了之后， 就直接显示在屏幕上了。你说的要多点一步还是两步。 实在不好用。

**Comment by Geeyun-JY3** [comment]
> 你说的那个和我说的不是同一个东西吧？ 你用一下setnua这个软件， 就知道什么意思了。 就是直接按一个快捷键，开始截屏，截了之后， 就直接显示在屏幕上了。你说的要多点一步还是两步。 实在不好用。

看你这描述感觉你需要专业版的 全局快捷键 与 命令行调用 绑定：https://docs.snipaste.com/zh-cn/pro?id=b-%e6%9b%b4%e8%87%aa%e7%94%b1%e7%9a%84%e5%ae%9a%e5%88%b6%e5%8c%96

**Comment by Geeyun-JY3** [comment]
> 你说的专业版中的， 超级截屏--截图并贴屏， 就是我想要的功能，只是这个只能用windows键。不可以自定义快捷键。

呃真的不能用命令行选项搭配出这功能吗：https://docs.snipaste.com/zh-cn/command-line-options

**Comment by Thesaurus0** [comment]
我的是免费版，没有 添加新命令的按钮。 要专业版才行吧？
















在 2022-11-24 22:13:36，"Geeyun-JY3" ***@***.***> 写道：

你说的专业版中的， 超级截屏--截图并贴屏， 就是我想要的功能，只是这个只能用windows键。不可以自定义快捷键。

呃真的不能用命令行选项搭配出这功能吗：https://docs.snipaste.com/zh-cn/command-line-options

**Comment by Geeyun-JY3** [comment]
> 我的是免费版，没有 添加新命令的按钮。 要专业版才行吧？ 

https://github.com/Snipaste/feedback/issues/2357#issuecomment-1312448008
