### ISSUE TITLE
工具栏增加一个一键将截图区域设为壁纸的按钮

### ISSUE THREAD

**Issue by Gd-Gordon** [Snipaste/feedback#2359]
### 功能描述

有时想截取一张图的一部分做壁纸，但需要额外将截图保存为文件再设为壁纸，有点繁琐。如果截图工具栏有一个一键将选区设为壁纸的按钮就好了，当然图像质量最好无损。

**Comment by Geeyun-JY3** [comment]
这是个截图工具，你说的这使用频率太低了，使用场景又十分局限。
