### ISSUE TITLE
为什么有的元素可以自动选中，有的却不行呢？

### ISSUE THREAD

**Issue by sepwolves** [Snipaste/feedback#2360]
### 问题描述

有些，比如微信里的引用记录，我一点击，然后snipaste就能直接把外框给截下来。
有的，就不行。http://www.nmc.cn/，比如这个降水预报图，以前一直都是可以的。不知道从什么时候开始就不行了。必须要我手动来截取范围。
这是为什么？

### 运行平台

Windows 桌面

### 软件版本

1.16.2

**Comment by Geeyun-JY3** [comment]
浏览器窗口的页面元素的问题：https://github.com/Snipaste/feedback/wiki/%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4#%E6%88%AA%E5%9B%BE%E6%97%B6%E6%97%A0%E6%B3%95%E8%87%AA%E5%8A%A8%E9%80%89%E5%8F%96%E6%B5%8F%E8%A7%88%E5%99%A8%E7%AA%97%E5%8F%A3%E7%9A%84%E9%A1%B5%E9%9D%A2%E5%85%83%E7%B4%A0

顺便提醒：https://docs.snipaste.com/zh-cn/pro?id=%e4%b8%93%e4%b8%9a%e7%89%88
> Snipaste 1.x 版将停留在 1.16.2，不再更新
