### ISSUE TITLE
安装了最新版本之后，添加了屏幕录制权限还是不能正常截图

### ISSUE THREAD

**Issue by lin559** [Snipaste/feedback#2364]
### 发生了什么？

macOs Monterey 12.3
Snipaste 2.7.2-beta
<img width="472" alt="image" src="https://user-images.githubusercontent.com/20829665/197396865-4e75a1ee-f30b-446d-8071-f58fcb29c0d1.png">

### 运行平台

macOS

### 软件版本

Snipaste 2.7.2-beta

**Comment by liulex** [comment]
[截图时只显示了桌面](https://docs.snipaste.com/zh-cn/troubleshooting?id=%e6%88%aa%e5%9b%be%e6%97%b6%e5%8f%aa%e6%98%be%e7%a4%ba%e4%ba%86%e6%a1%8c%e9%9d%a2):
> * 如 Snipaste 已经勾选但仍有问题，请先取消勾选 Snipaste，然后退出 Snipaste，勾选权限后再重启 Snipaste
