### ISSUE TITLE
There is a confusing `Le Liu` in `Allow in the Background` on macOS 13

### ISSUE THREAD

**Issue by liplum** [Snipaste/feedback#2366]
### What happened?

On my macOS 13, I found a `Le Liu` in the Settings\General\Login Items with no clue what it's.
But whenever I disable it, the Snipaste icon on the menu bar disappears. So I can confirm that an issue comes from Snipaste.
<img width="715" alt="image" src="https://user-images.githubusercontent.com/41872415/198163253-847771e2-299f-4b1c-ab27-e1217ada693f.png">

### Platform

macOS

### Version

2.7.2-Beta

**Comment by stevenzhu25** [comment]
Based on the description and an Apple Developer forum discussion, that item could be a helper to help Snipaste stay in the background. 
I am too poor to afford a Mac, so I can only assume the name is generated based off the developer field (company/person) in an app's signature, which in this case is Liu Le. 
I do not think this can be changed (alias?), So maybe @liulex should add a FAQ to Snipaste site acknowledging this situation.

**Comment by liulex** [comment]
Will fix it in 2.8.

**Comment by marypeng1020** [comment]
I still have it after I deleted snipaste.
