### ISSUE TITLE
色彩管理问题

### ISSUE THREAD

**Issue by jiabaoyu** [Snipaste/feedback#2373]
### 发生了什么？

windows一直以来的色彩管理都很烂，绝大多数系统应用、及第三方应用都默认显示器都是srgb。
这里提供一张图片作为试验素材：
<img width="500" alt="Snipaste_2022-11-05_10-34-43" src="https://user-images.githubusercontent.com/12813865/200097428-f3211526-c7e7-4ebb-8014-c92743e4aa1e.png">

> win11之前，如果使用srgb屏幕，屏幕无法显示超srgb范围的内容，色域自动裁切至srgb能显示的最鲜艳的值，截图结果自然是一片纯红；
> win11之前，如果使用广色域屏幕，屏幕可以显示超srgb范围的内容，截图结果可以反映超srgb范围的色彩与未超限的颜色的不同，但只是粗暴的嵌入srgb到结果文件中；
> win11 22H2之后，微软带来了实验性的[自动色彩管理ACM](https://devblogs.microsoft.com/directx/auto-color-management/)， 在SDR的广色域屏幕上，可以启用该功能。但一切未采用新API的旧版软件都将被系统限制为只能输出srgb画面，少数APP（如PS等）可以通过在exe的属性面板兼容性中开启“使用旧版显示器icc色彩管理”来使用他们自己的色彩管理方案，可以正确地在广色域屏幕上显示广色域图像；少数APP（如自带的图片查看器）则已经适配了，也可以正确地在广色域屏幕上显示广色域图像。但是对于Snipaste截图应用，至此则无法截取已正确显示的广色域显示的画面。

**建议：**
1. 对于广色域的内容，无论是什么windows版本，只要用户使用的广色域显示器则需要在截图APP的设置中提供选项: 嵌入当前显示器的icc或者维持现在的行为（即将广色域内容保留相对色度地转换到srgb）
2. 在上一点的基础上，参与兼容ACM，使之能正确截取广色域内容

### 运行平台

微软商店

### 软件版本

2.7.3（2022.01.30）

**Comment by septs** [comment]
Duplicate of #1520
