### ISSUE TITLE
与NVDIA显卡自动切换不兼容

### ISSUE THREAD

**Issue by Linghang659** [Snipaste/feedback#2375]
### 发生了什么？

在Snipaste在后台运行的情况下，NVDIA无法自动切换显卡，显示Snipaste.exe阻止了切换，关Snipaste后就正常了

### 运行平台

微软商店

### 软件版本

2.7.3

**Comment by liulex** [comment]
在 2.8 可以关掉 GPU 加速，就不会用到 GPU 了: https://docs.snipaste.com/zh-cn/advanced-configs?id=general
