### ISSUE TITLE
snipaste的官网似乎打不开了

### ISSUE THREAD

**Issue by SWHL** [Snipaste/feedback#2377]
### Problem Description

- 网址：https://www.snipaste.com/
- 显示：500 Internal Server Error
---
- 打开文档网址：https://docs.snipaste.com/zh-cn
- 显示：502 Bad Gateway

### Platform

Windows Desktop

### Version

v2.7.3

**Comment by KazamaSion** [comment]
@SWHL Check again.

**Comment by SWHL** [comment]
I can open the official website now, may it's a problem with my network here.
Thanks.
