### ISSUE TITLE
鼠标移动到屏幕左上角或右上角贴图会自动隐藏bug

### ISSUE THREAD

**Issue by zhishuchen** [Snipaste/feedback#2380]
贴图后移动鼠标指针到电脑屏幕左上角或右上角贴图会自动隐藏，需要按shift+F3才能再次显示
专业版2.7.3
Window10 Version 21H2
matebook b5-420 屏幕比例3:2

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/1936
