### ISSUE TITLE
v2.8-Beta (2022.11.15) 版本在 Mac 上无法启动

### ISSUE THREAD

**Issue by EpLiar** [Snipaste/feedback#2382]
### 发生了什么？

安装新版后启动没有任何托盘图标，命令行启动会自动结束但没有错误代码返回

macOS 版本为 13.0

### 运行平台

macOS

### 软件版本

v2.8-Beta (2022.11.15)

**Comment by wujr5** [comment]
遇到了相同的问题。系统信息接入如下：

![image](https://user-images.githubusercontent.com/7693440/201807393-4ad0f57a-9264-44de-a2a2-8a7c447691c9.png)

**Comment by ncuxzy** [comment]
有同样的问题，右键打开和双击打开，均无反应，系统macOS 13.0.1 (22A400)

**Comment by wujr5** [comment]
可以临时回滚一下：https://macdownload.informer.com/snipaste/，等待官方解决问题

**Comment by starudream** [comment]
官方的版本归档下载：https://bitbucket.org/liule/snipaste/downloads/

**Comment by SuperHuangXu** [comment]
+1

**Comment by AllenPu2020** [comment]
MacOS 12.6 也无法启动

**Comment by idelin** [comment]
+1

**Comment by liulex** [comment]
现在已经修复了，请到[官网](https://zh.snipaste.com/)下载新版。

非常抱歉给大家带来的不便……
