### ISSUE TITLE
Can't open Snipaste on mac after update ver 2.8

### ISSUE THREAD

**Issue by JeremyT666** [Snipaste/feedback#2385]
**Description:**
After update to v.2.8,  Snipaste can't be opened on Mac.
Already tried reinstall app, but it still could not be opened successfully.

**Device:**
macOS: v.13.0.1

**Comment by kahosan** [comment]
me too

**Comment by JeremyT666** [comment]
> me too

I downgraded to previous version @ v.2.7.2
It's a stable version.

**Comment by IslandOwnerHuang** [comment]
Same problem.

**Comment by fengqi5866** [comment]
+1

**Comment by Geeyun-JY3** [comment]
#2382

**Comment by vincentlai123** [comment]
how to downgrade?

**Comment by liulex** [comment]
Fixed in 2.8 Beta2. Please download it from the [website](https://snipaste.com/).

Sorry for the troubles....

**Comment by vincentlai123** [comment]
sorry for my impolite behavior... thanks again for your reply.
sorry again...

Le Liu ***@***.***> 於 2022年11月15日 週二 晚上8:14寫道：
