### ISSUE TITLE
有問題：********==>>爛功能：  新增选项：自由选中标注

### ISSUE THREAD

**Issue by vincentlai123** [Snipaste/feedback#2388]
### 联系方式

vinlai123@gmail.com

### 发生了什么？

新增选项：自由选中标注... 
這個功能太爛了… 我原本用得好好的… 
這樣我光是在箭頭上按個標示1，都沒有辦法，還要在旁邊按完再移過去。
原本分類移動，用得好好的，你們工程師在想什麼？  

天才工程師…我可以改回 2.7X版的嗎？ 

請問如何DOWNGRADE??????

### 运行平台

Windows 桌面

### 软件版本

2.8

**Comment by liulex** [comment]
都说是新增**选项**，不合适你，你自己不会关掉么？

![image](https://user-images.githubusercontent.com/2010459/201909906-7808cafa-379a-44a7-abf8-9859b086badb.png)
