### ISSUE TITLE
UI界面变大了也变糊了？

### ISSUE THREAD

**Issue by erruicoders** [Snipaste/feedback#2389]
### 问题描述

UI界面适配了win11但是变大了也变糊了？这是我的错觉嘛？

### 运行平台

微软商店

### 软件版本

2.8

**Comment by liulex** [comment]
截图说明一下？

**Comment by GaoyangWu** [comment]
![image](https://user-images.githubusercontent.com/118556302/202759293-cbdcdb94-3fff-4379-8f3e-4b5057785b9d.png)
Usage tips‘ fonts is bigger in v2.8 than v2.7.3, display resolution 2880*1800 with 14’, scale 200%, picture for reference.

**Comment by GaoyangWu** [comment]
Usage tips‘ fonts is bigger in v2.8 than v2.7.3, display resolution 2880*1800 with 14’, scale 200%, picture for reference.
![image](https://user-images.githubusercontent.com/118556302/202761281-50aec5f1-afa4-42c7-9401-0142af5c02b5.png)

**Comment by GaoyangWu** [comment]
And usage tips‘ fonts in v2.7.3.
![image](https://user-images.githubusercontent.com/118556302/202762621-79b52379-7883-4567-8742-9d009639944c.png)

**Comment by GaoyangWu** [comment]
And usage tips‘ fonts in v2.7.3
![image](https://user-images.githubusercontent.com/118556302/202763779-f4a20cdf-629f-4998-b785-630928ddd1ae.png)

**Comment by CrazyZhang666** [comment]
我都2.8版本也有整个问题，截图时的提示文本字体异常大，我显示器是100%缩放的，但是感觉截图时提示字体是200%缩放，感觉很不和谐

**Comment by liulex** [comment]
@GaoyangWu It's bigger, but I don't think it's too big compared to the size of the toolbar. Also the OP is complaining about blurry interface, but I don't see any blurry in your screenshot.

@CrazyZhang666 请提供日志和屏幕截图来说明问题。

**Comment by GaoyangWu** [comment]
Yes, it's not a big problem, just looks bigger than previous version at first sight. I'm not sure it scale problem (looks like 200% sacle) or just font sizes adjustment in new version.

**Comment by GaoyangWu** [comment]
Yes, it's not a big problem, just looks bigger than previous version at first sight. I'm not sure it scale problem (looks like 200% sacle) or just font sizes adjustment in new version.
No blurry interface found.

**Comment by GaoyangWu** [comment]
Recently I updated Snipaste to latest version on laptop with 1366*768 display, toolbar's font size is bigger than previous version also, shows it's just font size adjust since version 3.8, my question can be closed.
