### ISSUE TITLE
Option to select the entire area of only the active monitor by Ctrl + A shortcut

### ISSUE THREAD

**Issue by Japanese-Schoolgirl** [Snipaste/feedback#2392]
### Feature Description

When using several monitors, it is often necessary to select the entire area of only one of several monitors to edit (add text, arrows and etc. via Snipaste tools) and make a screenshot. Using a pre-selected area via "Custom snip" for this purpose is inconvenient, even with the presets system. Because of this, **I would like to suggest adding an option to the settings that would allow the `Ctrl + A` shortcut to select the entire area of the active monitor only, rather than all of them**.
If this functionality is already present or in the plans, I apologize for the inappropriate suggestion.

Thank you for your time and your wonderful program!

**Comment by liulex** [comment]
I think an option is not necessary. How about this behavior:
Ctrl+A will select the active monitor, Ctrl+A again to select all monitor.

**Comment by Japanese-Schoolgirl** [comment]
@liulex I think this behavior will be perfect
