### ISSUE TITLE
win11 22h2，启动即崩溃

### ISSUE THREAD

**Issue by jiabaoyu** [Snipaste/feedback#2397]
### What happened?

无法启动，无论是商店版还是官网下载的版本

系统信息：
版本	Windows 11 专业版
版本	22H2
安装日期	‎2022/‎11/‎4
操作系统版本	22621.819
体验	Windows Feature Experience Pack 1000.22636.1000.0

windows crash dump文件：
[snipaste.exe.1220.zip](https://github.com/Snipaste/feedback/files/10072474/snipaste.exe.1220.zip)

### Platform

Microsoft Store, Windows Desktop

### Version

2.8.0.0

**Comment by liulex** [comment]
dump 显示是 mactype 导致的。

**Comment by jiabaoyu** [comment]
> dump 显示是 mactype 导致的。

谢谢！的确是，关闭mactype就OK了。 请教一下dump文件如何自行查看呢？

**Comment by liulex** [comment]
我用 Visual Studio 看的，不清楚非编程人员如何查看。

**Comment by jiabaoyu** [comment]
@liulex 不好意思，上回我是用todesk远程操作的，在关闭mactype后就能打开snipaste了。现在多次在物理机上操作，又失效了。包括卸载了mactype重启，还是无法打开。
非常奇怪，我家中的PC却一直很正常，并不与mactype有任何冲突

**Comment by jiabaoyu** [comment]
C:\Users\jiabaoyu\AppData\Local\CrashDumps
[snipaste.exe.15016.zip](https://github.com/Snipaste/feedback/files/10104360/snipaste.exe.15016.zip)

C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_45479liulios.170_ea8bb882b9f3a59c694ed8926f902126d82a2ae_fb8bb822_a5d936e3-9f1c-4914-8d7e-fb4c6d2345d0
[Report.zip](https://github.com/Snipaste/feedback/files/10104363/Report.zip)

**Comment by liulex** [comment]
上面的 dump 跟 https://github.com/Snipaste/feedback/issues/2401 一样，是因为萍方字体。

**Comment by jiabaoyu** [comment]
> 上面的 dump 跟 #2401 一样，是因为萍方字体。

可是我根本没装苹方字体啊😂 我用的noblescarlet

**Comment by liulex** [comment]
看堆栈两者是一样的，可能苹方外的其他字体也会导致相同的问题。
你可以试试将以下压缩包解压后替换掉桌面版的同名文件，应该就不崩了。

[Qt6Gui.zip](https://github.com/Snipaste/feedback/files/10108628/Qt6Gui.zip)

**Comment by jiabaoyu** [comment]
谢谢，的确有用！
