### ISSUE TITLE
贴图后, 在贴图上面右键相应的功能快捷键貌似没有了?

### ISSUE THREAD

**Issue by Pluto0615** [Snipaste/feedback#2398]
### 问题描述

请教一下,

之前用V2.7.3版本, 在把截图贴到桌面上后, 并在上面右键, 会有功能键的相应的键盘按键, 例如 标注-E, 撤销-D....
如下图:
<a href="https://imgur.com/3trUzvY"><img src="https://i.imgur.com/3trUzvY.png" title="source: imgur.com" /></a>

但新的版本V2.8, 发现貌似都消失了. 如下图
<a href="https://imgur.com/a5MouKX"><img src="https://i.imgur.com/a5MouKX.jpg" title="source: imgur.com" /></a>

能否帮忙看看是我哪里设置不对吗? 还是版本更新中去掉了这一功能?

能否添加回来? 感谢..

### 运行平台

Windows 桌面

### 软件版本

V2.8

**Comment by Geeyun-JY3** [comment]
先看看 `在右键菜单显示助记键` 开了没？
![image](https://user-images.githubusercontent.com/49396421/203518428-2d2cdbe3-cbe3-4332-a65d-7ddc43b88831.png)

（另外我用的不是 Windows 11，不清楚 Windows 11 是否有所不同）

**Comment by Pluto0615** [comment]
> 先看看 `在右键菜单显示助记键` 开了没？ ![image](https://user-images.githubusercontent.com/49396421/203518428-2d2cdbe3-cbe3-4332-a65d-7ddc43b88831.png)
> 
> （另外我用的不是 Windows 11，不清楚 Windows 11 是否有所不同）

我去, 原来在这等着我呢...
果然是这个原因....(只不过这个名字起的"助记键"....不应该通常是叫字母快捷键啥的吗...)

非常感谢呀!

**Comment by Pluto0615** [comment]
嗯嗯, 非常感谢分享.
