### ISSUE TITLE
截图时显示光标，光标总是以反色显示

### ISSUE THREAD

**Issue by wzddl** [Snipaste/feedback#2399]
### 联系方式

weizhidedongli@qq.com

### 发生了什么？

专业版截图时候，按~键显示出光标或默认打开捕捉光标时，光标会以反色显示，希望修复一下这个问题
不仅是默认windows光标、游戏内光标、还是类似于Yolo之类第三方钩子光标都会如此
光标正常显示的颜色
应该是白色
[https://pic.imgdb.cn/item/637e0a1516f2c2beb1453565.png](光标正常显示的颜色)
应该是蓝色
[https://pic.imgdb.cn/item/637e0a1516f2c2beb1453589.png](蓝色与浅蓝渐变)

使用Snipaste截图时
出现反色问题
[https://pic.imgdb.cn/item/637e0a1516f2c2beb1453561.png](光标变成黑色)
出现反色问题
[https://pic.imgdb.cn/item/637e0a1516f2c2beb145357c.png](光标变成橙红渐变)

### 运行平台

Windows 桌面

### 软件版本

2.8.1 (2022.11.22)

**Comment by liulex** [comment]
下个版本修复。
