### ISSUE TITLE
win11 无法启动snipaste

### ISSUE THREAD

**Issue by xiamocc** [Snipaste/feedback#2401]
Contact Details
No response

What happened?
无法启动，商店版和官网版本都没法启动,
重启重装都试过了,
官网版启动会输出dump文件,商店版日志里到初始化就结束了,未输出dump文件

系统信息：
版本	Windows 11 专业版
版本	22H2
安装日期	‎2022/‎6/‎10
操作系统版本	22621.819
体验	Windows Feature Experience Pack 1000.22636.1000.0

日志与windows crash dump文件：
[商店版-日志.txt](https://github.com/Snipaste/feedback/files/10083555/-.txt)

[官网版-日志.txt](https://github.com/Snipaste/feedback/files/10083559/-.txt)
[官网版dump.zip](https://github.com/Snipaste/feedback/files/10083561/dump.zip)

Platform
Microsoft Store, Windows Desktop

Version
官网 - 2.8.1-Beta
商店 - 2.8.100.0

**Comment by liulex** [comment]
在读系统字体配置的时候出错了，请问是有安装过什么字体或者改动过系统字体相关的设置吗？

**Comment by liulex** [comment]
用了萍方字体？

**Comment by xiamocc** [comment]
装过一个等宽的字体CaskaydiaCove Nerd Font Mono.萍方字体也装过

> 用了萍方字体？

**Comment by xiamocc** [comment]
那请问解决方案是什么呢? 卸载这些字体么? 当前反馈问题是使用我的工作电脑.我家中的电脑也发生一样的问题..

**Comment by liulex** [comment]
卸载萍方字体，或者等我下周的修复版。

**Comment by xue-long** [comment]
启动后，任务栏不显示，但按下Ctrl+F1能截图

**Comment by skpll** [comment]
> 启动后，任务栏不显示，但按下Ctrl+F1能截图

Win11默认隐藏了。。
设置--个性化--任务栏--其他系统托盘图标--打开Snipaste

**Comment by ZhiboWong** [comment]
> > 启动后，任务栏不显示，但按下Ctrl+F1能截图
> 
> Win11默认隐藏了。。 设置--个性化--任务栏--其他系统托盘图标--打开Snipaste

没有“其他系统托盘图标”的选项。
[https://youke.xn--y7xa690gmna.cn/s1/2026/02/13/698e9c2484cb5.webp](url)
