### ISSUE TITLE
升级专业版之后，隐藏/显示所有截图的功能经常失灵？

### ISSUE THREAD

**Issue by fightar2022** [Snipaste/feedback#2402]
### 联系方式

445043261@qq.com

### 发生了什么？

升级专业版之后，隐藏/显示所有截图的功能经常失灵？

之前是普通版本，觉得好用就升级到了专业版，但尴尬的是升级之后，经常会弹出我之前的截图，就像隐藏/显示所有截图这个功能经常误触发。

### 运行平台

微软商店

### 软件版本

v2.8.1

**Comment by Geeyun-JY3** [comment]
贴图吧。#1936？

**Comment by fightar2022** [comment]
收到（自动回复）

**Comment by fightar2022** [comment]
> 隐藏/显示所有贴图吧。#1936？

对,但我自己没有操作,它自动显示出来了

**Comment by liulex** [comment]
请点进去 https://github.com/Snipaste/feedback/issues/1936 看一看，已经解释了你的问题并且提供了解决方案。
