### ISSUE TITLE
请求新功能: 快捷键快速启动关闭复制为文件

### ISSUE THREAD

**Issue by liawt** [Snipaste/feedback#2404]
### 功能描述

请求新功能: 快捷键快速启动关闭复制为文件

当使用Outlook编辑文件时, 如果勾选了复制图片为文件, 测试Outlook中黏贴的默认操作是黏贴为附件而不是直接插入图片. 是否可以添加快捷键功能而不是手动进入选项更改.

对于办公一族而言, 直接保存截图到文件夹和在Outlook中直接插入截图都是很频繁的操作, 还请添加此功能. 谢谢

**Comment by liulex** [comment]
下个版本可选择用 Ctrl+Alt+C 触发"复制图像为文件"：
![image](https://user-images.githubusercontent.com/2010459/232076486-b71990b8-be68-454c-86e2-b09c2eb60a89.png)
