### ISSUE TITLE
请求新功能: 保存并重新载入贴图及其修改

### ISSUE THREAD

**Issue by L-Trump** [Snipaste/feedback#2407]
### 功能描述

希望有方法能够保存一个贴图以及对其进行的所有修改，在重新打开的时候能够恢复并且编辑这些修改（标注、文字等）。目前可以看到的有history文件夹，但并没有程序内存档的方法。感谢

**Comment by Jeans-Li** [comment]
同求！

**Comment by Geeyun-JY3** [comment]
Duplicate of #1654
