### ISSUE TITLE
在Win11中软件无法长期存活在托盘区

### ISSUE THREAD

**Issue by Lujc0523** [Snipaste/feedback#2409]
### 发生了什么？

开机启动Snipaste后，长时间（未进行详细统计但在1小时以上）不使用软件，再次使用时无法拉起该程序，排查后发现软件已停止运行

### 运行平台

Windows 微软商店

### 软件版本

2.8

**Comment by jonhon158** [comment]
同样的问题：64bit 桌面版可长时间稳定使用，微软商店pro版会后台闪退

**Comment by liulex** [comment]
试试桌面版可以复现吗？

**Comment by Lujc0523** [comment]
因为购买的pro版本  所有一直是在微软商店下载的   我之后试试

**Comment by Lujc0523** [comment]
[splog.txt](https://github.com/Snipaste/feedback/files/10200370/splog.txt)
刚刚找到了  日志文件   你们可以看下是不是有问题

**Comment by liulex** [comment]
@Lujc0523 日志只能看出确实有几次异常退出，但无法用于调试。
用桌面版崩溃后会在程序目录的 crashes 文件夹生成 .dmp 文件，将它发给我就可以解决问题了。

**Comment by Lujc0523** [comment]
好的 正在尝试

**Comment by VerletKing** [comment]
> 好的 正在尝试

我和你是一样的问题。但是我的 crashes 文件夹是空的

**Comment by xuergo** [comment]
我也是 不过我是win10

**Comment by xuergo** [comment]
> @Lujc0523 日志只能看出确实有几次异常退出，但无法用于调试。 用桌面版崩溃后会在程序目录的 crashes 文件夹生成 .dmp 文件，将它发给我就可以解决问题了。

你好，我win10 也出现无法常驻问题。我尝试了商店和桌面版都不行。
[splog.txt](https://github.com/Snipaste/feedback/files/10218913/splog.txt)

**Comment by Lujc0523** [comment]
@liulex 这周试一下  桌面版 在托盘区持续存活 未出现问题
