### ISSUE TITLE
在win11中启用win ink无法正常使用画笔功能

### ISSUE THREAD

**Issue by lbyxiaolizi** [Snipaste/feedback#2411]
### 联系方式

lbyxiaolizi@x6z.top

### 发生了什么？

在win11中启用win ink无法正常使用画笔功能。

> 视频： `https://user-images.githubusercontent.com/65098936/205836077-aa751728-1003-4289-b122-449a5b54be8a.mp4`
   

### 运行平台

微软商店, Windows 桌面

### 软件版本

v2.8.2

**Comment by Geeyun-JY3** [comment]
录屏似乎是全黑屏
