### ISSUE TITLE
截图后直接使用鼠标中键进行的贴图，按Esc键后它会被销毁，无法恢复

### ISSUE THREAD

**Issue by TaoShanCode** [Snipaste/feedback#2413]
### 发生了什么？

我设置了“可被恢复的贴图数”为10，操作流程如下：
1. 截图后，直接用鼠标中键进行贴图
2. 按Esc键关闭贴图
3. 按F3无法显示这张图片 ，该图片被销毁了

如果是截图后，左键双击，则是正常的：
1. 截图后，鼠标左键双击（复制到剪贴板，并退出截屏）
2. 按F3贴图
3. 按Esc关闭贴图
4. 按F3 ，可以正常显示贴图

### 运行平台

微软商店

### 软件版本

2.8.2

**Comment by liulex** [comment]
> 3. 按F3无法显示这张图片 ，该图片被销毁了

再按多一次就显示了。

**Comment by TaoShanCode** [comment]
> 

还真是这样，这是为啥。。。两者不都是贴图吗，能统一吗

**Comment by Geeyun-JY3** [comment]
@TaoShanCode 还是不太一样的。

截图后（准确地说是确定截图区域后）

- 鼠标中键单击是将当前截图保存到贴图：#63（不过文档里 [1](https://docs.snipaste.com/zh-cn/getting-started?id=何谓一次-成功的截图)、[2](https://docs.snipaste.com/zh-cn/getting-started?id=如何贴图) 都没写， @liulex 是不是可以补充一下）
- 鼠标左键双击是将当前截图保存到剪贴板，详见：https://docs.snipaste.com/zh-cn/getting-started?id=何谓一次-成功的截图

**Comment by TaoShanCode** [comment]
> @TaoShanCode 还是不太一样的。
> 
> 截图后（准确地说是确定截图区域后）
> 
> * 鼠标中键单击是将当前截图保存到贴图：[希望增加自动贴图功能 #63](https://github.com/Snipaste/feedback/issues/63)（不过文档里 [1](https://docs.snipaste.com/zh-cn/getting-started?id=%E4%BD%95%E8%B0%93%E4%B8%80%E6%AC%A1-%E6%88%90%E5%8A%9F%E7%9A%84%E6%88%AA%E5%9B%BE)、[2](https://docs.snipaste.com/zh-cn/getting-started?id=%E5%A6%82%E4%BD%95%E8%B4%B4%E5%9B%BE) 都没写， @liulex 是不是可以补充一下）
> * 鼠标左键双击是将当前截图保存到剪贴板，详见：[https://docs.snipaste.com/zh-cn/getting-started?id=何谓一次-成功的截图](https://docs.snipaste.com/zh-cn/getting-started?id=%E4%BD%95%E8%B0%93%E4%B8%80%E6%AC%A1-%E6%88%90%E5%8A%9F%E7%9A%84%E6%88%AA%E5%9B%BE)

感谢答疑，但是您看两次的操作流程，只有贴图前的步骤不一样，后边都是贴图动作呢，一个是截屏后直接贴图（下称快捷贴图），一个是双击保存后，再按F3贴图（二次贴图）。

给人的感觉其实都是贴图，但是在Esc隐藏后，他们恢复的顺序有了区别，是不是可以优化一下呢。

**Comment by Geeyun-JY3** [comment]
> 感谢答疑，但是您看两次的操作流程，只有贴图前的步骤不一样，后边都是贴图动作呢，一个是截屏后直接贴图（下称快捷贴图），一个是双击保存后，再按F3贴图（二次贴图）。
> 
> 给人的感觉其实都是贴图，但是在Esc隐藏后，他们恢复的顺序有了区别，是不是可以优化一下呢。

左键双击会把截图保存到剪贴板，接着按贴图当然会直接出来；
中键单击默认并不会把截图保存到剪贴板，我目前的实测是按第一次贴图出来的是剪贴板的首项内容，按第二下才出来先前截图，不清楚是否还有其他情况，这也符合[文档](https://docs.snipaste.com/zh-cn/getting-started?id=什么时候可以贴图)的说法。

优化空间当然还是有的，我也觉得这里第一次按贴图就直接出现刚才被关闭的贴图更好，只是我也不太确定这是否会造成逻辑问题。
