### ISSUE TITLE
贴图的平滑吸附功能(Shift + 拖动)无法自然对齐缩略图

### ISSUE THREAD

**Issue by GitPopcorn** [Snipaste/feedback#2414]
### 问题描述

- 以前贴图多的时候，习惯全部双击变成缩略图，然后用Shift + 拖拽把贴图整齐地堆在一个角落里。
- 但是感觉自从2.8版本以后，按住Shift + 拖拽去放置贴图缩略图，就是怎么样都无法对齐，不是高2个像素就是低2个像素。
- 关掉贴图的阴影显示，也依然无法对齐缩略图。
- 但是完整贴图又是可以对齐的，感觉像是进行对齐处理时忘了处理缩略图的边框宽度。

### 复现过程

- 任意截取两张尺寸大于(50 x 50)的截图，添加最外侧边框，然后贴图到屏幕上。
- 右键贴图，关闭窗口阴影。
- Shift + 左键拖拽贴图，将其拖拽到另一个贴图附近或上方，此时平滑吸附功能正常。
- Shift + 左键双击将两张贴图都变成缩略图。
- Shift + 左键拖拽缩略图，将其拖拽到另一个缩略图附近或上方，此时平滑吸附功能无法正常生效，两个缩略图始终无法对齐。

### 运行平台

微软商店

### 软件版本

Snipaste Pro 64 2.8.2 (2022.12.02)

**Comment by GitPopcorn** [comment]
只有我能复现出这个问题吗？是我的环境问题？

**Comment by liulex** [comment]
谢谢反馈，下个版本修复。

**Comment by iamqiz** [comment]
@liulex 大佬,啥时候出滚动截图呢? 孩子们都等哭了🐱
![Snipaste_2022-12-11_11-10-26](https://user-images.githubusercontent.com/48077521/206884529-6fe8d0c4-cc83-4279-a255-8b5b937c9c4f.png)
