### ISSUE TITLE
建议 增加延时截图功能

### ISSUE THREAD

**Issue by 1772189738** [Snipaste/feedback#2417]
### 功能描述

按下快捷键后在设定的时间后截图

**Comment by lhbdhr** [comment]
纯路人，这功能的使用场景是什么？感觉好奇怪怎么会有这种需求。

**Comment by Geeyun-JY3** [comment]
请善用搜索：#181、#1451

@lhbdhr 看看这几个 issue 就知道了
文档中的故障排除部分也有相关内容：https://docs.snipaste.com/zh-cn/troubleshooting?id=无法截取菜单，一按截图快捷键菜单就消失了

**Comment by Geeyun-JY3** [comment]
Duplicate of #181

Duplicate of #1451
