### ISSUE TITLE
win11 系统第一次使用正常，第二次使用就闪退，重启后也是第一次使用正常， 第二次及其以后闪退。

### ISSUE THREAD

**Issue by VerletKing** [Snipaste/feedback#2421]
### 发生了什么？

win11 系统第一次使用正常，第二次使用就闪退，重启后也是第一次使用正常， 第二次及其以后闪退。
卸载重装都没用。

### 运行平台

微软商店, Windows 桌面

### 软件版本

2.8.2

**Comment by stevenzhu25** [comment]
@VerletKing 建议看看你后台软件， 是不是哪个给杀了。 
另外可以看下事件查看器（Event Viewer）， 看看所有的红标错误信息，里面可能有为什么Snipaste无法启动的原因

**Comment by VerletKing** [comment]
> @VerletKing 建议看看你后台软件， 是不是哪个给杀了。 另外可以看下事件查看器（Event Viewer）， 看看所有的红标错误信息，里面可能有为什么Snipaste无法启动的原因

这是Event Viewer 应用程序崩溃事件
错误应用程序名称: Snipaste.exe，版本: 2.8.2.0，时间戳: 0x638a0b80
错误模块名称: unknown，版本: 0.0.0.0，时间戳: 0x00000000
异常代码: 0xc0000005
错误偏移量: 0x0078f3b4
错误进程 ID: 0x0x30C0
错误应用程序启动时间: 0x0x1D90D41D5DAC39F
错误应用程序路径: C:\Snipaste\Snipaste.exe
错误模块路径: unknown
报告 ID: ade98ede-2c81-4c26-801a-97d3a5082b64
错误程序包全名: 
错误程序包相对应用程序 ID: 


只知道崩溃，不知道什么原因导致的。我就升级到win11

**Comment by stevenzhu25** [comment]
@VerletKing 确认一下，你这个是Microsoft Store下载的还是通过Snipaste.com下载的？
看路径像是Snipaste.com的

**Comment by VerletKing** [comment]
> @VerletKing 确认一下，你这个是Microsoft Store下载的还是通过Snipaste.com下载的？ 看路径像是Snipaste.com的

我是Snipaste.com，闪退，之后我又去Microsoft Store下载，也是不行。只有重启的第一次使用正常，再次使用就闪退了。

**Comment by stevenzhu25** [comment]
@VerletKing emmm 你电脑上装什么杀毒软件了么？

**Comment by VerletKing** [comment]
> 

火绒安全

**Comment by stevenzhu25** [comment]
@VerletKing 试试查下火绒安全运行阻止区？ 我总是感觉这个是杀软阻止了

**Comment by stevenzhu25** [comment]
@stevenzhu25 如果不是的话… 那我也不知道了， 可能要等作者或者其他人来看看…

**Comment by VerletKing** [comment]
> 

退出火绒安全，还是一样的闪退。如果是杀软阻止的话，第一也应该闪退。
[splog.txt](https://github.com/Snipaste/feedback/files/10201846/splog.txt)

**Comment by stevenzhu25** [comment]
> > 
> 
> 退出火绒安全，还是一样的闪退。如果是杀软阻止的话，第一也应该闪退。
> [splog.txt](https://github.com/Snipaste/feedback/files/10201846/splog.txt)
> 

看了下你传的splog， 是开了兼容模式么？ 如果关掉再开也会闪退么？

**Comment by VerletKing** [comment]
> > > 
> > 
> > 
> > 退出火绒安全，还是一样的闪退。如果是杀软阻止的话，第一也应该闪退。
> > [splog.txt](https://github.com/Snipaste/feedback/files/10201846/splog.txt)
> 
> 看了下你传的splog， 是开了兼容模式么？ 如果关掉再开也会闪退么？

已经关掉了，重启系统刚开始可以，一段时间后不行了。
[splog.txt](https://github.com/Snipaste/feedback/files/10202651/splog.txt)

**Comment by liulex** [comment]
没有崩溃记录，明显就是被其他进程杀的。

**Comment by 3song** [comment]
这个问题不是崩溃，软件本身没有崩溃，但是光标不显示导致无法截图，软件截图失效了
