### ISSUE TITLE
请求添加可以设置截图水印的功能

### ISSUE THREAD

**Issue by TakizawaAnn** [Snipaste/feedback#2423]
### 功能描述

冒昧的问下作者，有考虑过为这款截图工具**添加自定义水印**的功能吗？
作为一名艺术创作者，平时在社交中涉及到作品交流的时候总是需要保存图片后再单独添加水印，这样的操作相对繁琐，如果能做截图这个过程中就能添加上水印，这将会非常的方便！

**Comment by SoTender** [comment]
一年过去了。看来屎没有计划

**Comment by Geeyun-JY3** [comment]
Duplicate of #454
