### ISSUE TITLE
公司电脑禁止从MicsoftStore下载软件，所以买完专业版无法在公司电脑上安装使用，有没有什么办法解决一下

### ISSUE THREAD

**Issue by weixxcle** [Snipaste/feedback#2424]
### 问题描述

如题，有没有什么方法能解决一下的。家里的电脑能正常下载安装使用。

### 运行平台

微软商店, Windows 桌面

### 软件版本

2.8.2（2022.12.02）

**Comment by scruel** [comment]
换个公司

**Comment by ViperThanks** [comment]
6还得是你

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/1059#issuecomment-1018028358
