### ISSUE TITLE
macOS 13.1 取消开机自启无效

### ISSUE THREAD

**Issue by LiJiabo** [Snipaste/feedback#2428]
### 联系方式

li_jiabo@qq.com

### 发生了什么？

在首选项取消开机自启，系统设置——登录项中将com.Snipaste取消后重启仍然会开机自启，并且退出后系统会不断弹出“已添加登录项”提示，在系统设置——登录项中重新打开后软件会自动开启

### 运行平台

macOS

### 软件版本

2.8.1-Beta

**Comment by LiJiabo** [comment]
取消开机自启后系统设置中登录项那里还是开启的，launchctl查看好像也还是加载了，用launchctl disable禁用就好了，再退出登录重进launchctl list就看不到了（2.8.3-Beta版本）

**Comment by liulex** [comment]
谢谢反馈，已于 Snipaste 2.8.3 Beta2 修复。
