### ISSUE TITLE
软件命令行运行与手册描述不符合

### ISSUE THREAD

**Issue by xyhh4** [Snipaste/feedback#2431]
### 联系方式

xyhh4@163.com

### 发生了什么？

根据手册的描述：Snipaste 支持使用命令行选项进行功能调用，但除了带 * 标记的选项（如 --config）外，其他选项只在 Snipaste 启动后才有效。所以我认为以下命令可以得到正确的结果:
SnipasteDir是软件所在目录, 在windows cmd.exe中执行
SnipasteDir>snipaste.exe                                                               ;启动snipaste软件
SnipasteDir>snipaste.exe snip --area 0 0 100 100 -o d:\abc.jpg     ;在截图特定区域并保持到指定位置

但是明显不行，它的运行结果是：
SnipasteDir>snipaste.exe                                                               ;确实成功启动了软件 
SnipasteDir>snipaste.exe snip --area 0 0 100 100 -o d:\abc.jpg     ;并没有执行前面所述指令，反而触发了鼠标框选区域模式！这不是我需要的，所以我强制退出了这种模式。
SnipasteDir>snipaste.exe snip --area 0 0 100 100 -o d:\abc.jpg     ;再次执行这条指令，成功

结论：
在完成软件启动后，貌似必须先触发一次鼠标框选指令，后面的命令行指令才能正常运行。

### 运行平台

Windows 桌面

### 软件版本

Snipaste-2.8.2-Beta-x86

**Comment by liulex** [comment]
见 https://github.com/Snipaste/feedback/issues/2419，下个版本修复。
