### ISSUE TITLE
希望增加全屏下忽略快捷键功能

### ISSUE THREAD

**Issue by Karben233** [Snipaste/feedback#2432]
### 功能描述

在游戏时按F1按键会呼出截屏功能,虽然可以通过更改快捷键解决此问题,但我觉得如果增加全屏下忽略快捷键功能可能会更友好

**Comment by Geeyun-JY3** [comment]
感觉这可以满足你的需求：https://github.com/Snipaste/feedback/issues/2015#issuecomment-968065514

**Comment by Geeyun-JY3** [comment]
Duplicate of #1020
