### ISSUE TITLE
Mac上截图点击复制有明显的卡顿

### ISSUE THREAD

**Issue by guoiaoang** [Snipaste/feedback#2434]
### 发生了什么？

Mac上截图快捷键反应迅速，但是选取区域后点击复制按钮能明显感觉到卡了一下，选取“截屏并自动复制”也是。设置已经恢复到默认值了,版本升级到最新版也是一样。微信的复制按钮没有明显的卡顿感觉，不知道是怎么实现的。

### 运行平台

macOS

### 软件版本

2.8.1-Beta(2022.11.22)

**Comment by SAKURA-CAT** [comment]
感觉是优化的问题，在截取小窗口的时候不会有卡顿感觉，随着窗口面积增大，卡顿感变明显。

**Comment by liulex** [comment]
下个版本会改善复制时卡顿。

**Comment by liubin595338764** [comment]
@liulex  我这又开始卡顿了，
版本 2.8.6-Beta (2023.09.20)

运行平台
macOS
