### ISSUE TITLE
建议调整贴图绘制编辑时对双击的响应逻辑

### ISSUE THREAD

**Issue by BobYue-01** [Snipaste/feedback#2435]
### 发生了什么？

贴图绘制编辑时，连续操作中出现双击就会错误地引发退出，导致大量工作丢失。
我认为在绘制贴图时，用户很少想到使用双击进行关闭。应当取消绘制贴图过程中对双击的响应。

### 运行平台

微软商店

### 软件版本

2.8.2 (2022.12.02)

**Comment by Geeyun-JY3** [comment]
习惯问题。

另外左键双击只是关闭贴图，不是销毁，再按一次或多次贴图快捷键就会出来的：https://docs.snipaste.com/zh-cn/getting-started?id=关闭单张贴图
> - 被关闭的贴图，可再次被贴出，除非超过“可被恢复的已关闭贴图数”
>   - 如何恢复：按下贴图键一次或多次

**Comment by BobYue-01** [comment]
哦哦确实，我忘记了这个🥹
