### ISSUE TITLE
希望为截图功能增加文字识别

### ISSUE THREAD

**Issue by soulocker** [Snipaste/feedback#2438]
### 功能描述

我是微软商店购买的正版用户（￥98？）
snipaste对我而言是非常重要的工具，但是因为不支持OCR，所以很多场合我需要其他软件来补充；
这明显违反了snipaste一站式、简洁、高效的原则。

故而希望新版本增加OCR功能

**Comment by Geeyun-JY3** [comment]
Duplicate of #188
