### ISSUE TITLE
snipaste捕获鼠标指针时不能捕获其阴影

### ISSUE THREAD

**Issue by 212112111zwl** [Snipaste/feedback#2442]
### 发生了什么？

在设置中启动鼠标指针的阴影，并且在鼠标阴影正常显示的情况下
使用snipaste截图并显示捕获的鼠标指针时不会显示阴影

虽然对日常使用影响不大，但还是希望尽量注重每一个细节~

操作系统：Win10 专业版
Snipaste版本：2.7.3-Beta

### 运行平台

Windows 桌面

### 软件版本

2.7.3-Beta

**Comment by StarryVoid** [comment]
动态指针识别鼠标阴影会出现黑块，所以干脆都不带阴影。
