### ISSUE TITLE
箭头和直线支持单独的快捷键

### ISSUE THREAD

**Issue by LvShuaiChao** [Snipaste/feedback#2443]
### Feature Description

![image](https://user-images.githubusercontent.com/35528109/209075286-7f01a222-44c4-4c79-ad0c-9387f963f57a.png)
Snipaste最新版如何通过快捷键来快速打开箭头和直线呢？（以前的版本是把箭头和直线放在不同的按钮上，我看现在都合并到了一个组里面，二次选择很繁琐，特别是需要频繁切换直线和箭头的时候）

**Comment by Geeyun-JY3** [comment]
目前还可以通过按 <kbd>Tab</kbd> 互相切换：https://github.com/Snipaste/feedback/issues/1939#issuecomment-896440602

**Comment by LvShuaiChao** [comment]
> 目前还可以通过按 Tab 互相切换：[#1939 (comment)](https://github.com/Snipaste/feedback/issues/1939#issuecomment-896440602)

好的，非常感谢
