### ISSUE TITLE
贴图之后做的批注能保存吗，现在是每次重启软件或者重启电脑之前贴图的文件就没有了，批注也没了

### ISSUE THREAD

**Issue by a156168128** [Snipaste/feedback#2451]
### 联系方式

1561683128@qq.com

### 发生了什么？

贴图之后做的批注能保存吗，现在是每次重启软件或者重启电脑之前贴图的文件就没有了，批注也没了。
想把图片和图片上的批注作为一个独立的文件，可以随时批注更改

### 运行平台

Windows 桌面

### 软件版本

2.5.6

**Comment by Geeyun-JY3** [comment]
Duplicate of #1654

**Comment by a156168128** [comment]
并没有解决我的问题啊。。
《对于可能需要再次编辑的文件，建议先贴图出来，再进行编辑，然后放到一个特定的贴图组里面永久保存。》
我无法永久保存，每次重启软件批注贴图组都会消失。
希望增加可以用Snipaste 打开的批注文件（Windows文件，记录批注的内容和图片的内容），可以供用户随时复制粘贴修改批注
