### ISSUE TITLE
截图是放大镜遮挡选区大小信息

### ISSUE THREAD

**Issue by guoiaoang** [Snipaste/feedback#2452]
### 发生了什么？

在屏幕下方，从右下角向左上角截图拖拽时，屏幕放大镜遮挡住截图区域左上角的选区大小的显示了。跟 [#255](https://github.com/Snipaste/feedback/issues/255) 不是同一个问题。另外，可以选择隐藏左下角的截图提示吗，看起来很碍眼，放大镜有时也希望隐藏。

### 运行平台

macOS

### 软件版本

2.8.1-Beta(2022.11.22)

**Comment by Geeyun-JY3** [comment]
可以隐藏左下角快捷键提示：
![image](https://user-images.githubusercontent.com/49396421/209963192-511bf78a-e866-42b0-bb54-45fe7718aa71.png)

macOS 截图时隐藏放大镜：#1207

另外建议给个放大镜遮挡住截图区域左上角的选区大小的显示的截图，或者是 bug，Windows 实测不会遮挡。

**Comment by StarryVoid** [comment]
Windows也遮挡，这是两个UI同时显示的相互覆盖

**Comment by liulex** [comment]
下个版本会避免放大镜挡住选区大小。
