### ISSUE TITLE
《对于可能需要再次编辑的文件，建议先贴图出来，再进行编辑，然后放到一个特定的贴图组里面永久保存。》 我无法永久保存，每次重启软件批注贴图组都会消失。 希望增加可以用Snipaste 打开的批注文件（Windows文件，记录批注的内容和图片的内容），可以供用户随时复制粘贴修改批注

### ISSUE THREAD

**Issue by a156168128** [Snipaste/feedback#2453]
### 联系方式

1561683128@qq.com

### 发生了什么？

并没有解决我的问题啊。。
《对于可能需要再次编辑的文件，建议先贴图出来，再进行编辑，然后放到一个特定的贴图组里面永久保存。》
我无法永久保存，每次重启软件批注贴图组都会消失。
希望增加可以用Snipaste 打开的批注文件（Windows文件，记录批注的内容和图片的内容），可以供用户随时复制粘贴修改批注
你们的批注真的太好用了，希望有解决办法
https://github.com/Snipaste/feedback/issues/2451

### 运行平台

Windows 桌面

### 软件版本

2.5.6

**Comment by Geeyun-JY3** [comment]
#1654 还开着，还没说这功能不做呢，那只是开发者两年前的回复，不是说那就是最终解决方案。

另外不用这么急着另开新 issue，如果确实不是重复会给你重开的。

**Comment by Geeyun-JY3** [comment]
Duplicate of #1654
