### ISSUE TITLE
保存时，如果在窗口内移动文件，会误报“文件已存在，是否覆盖”

### ISSUE THREAD

**Issue by CWZ7605** [Snipaste/feedback#2456]
### 发生了什么？

https://user-images.githubusercontent.com/4016785/210303907-bb3937aa-7730-4171-a03b-a23d33b604ef.mp4

在保存窗口里面，将现有文件拖到其他目录后，再保存为之前的文件名，就会提示文件已存在。
但实际上，文件已经被移动到其他目录了。

### 运行平台

微软商店

### 软件版本

2.8.3

**Comment by liulex** [comment]
这个是系统自带的文件对话框的逻辑，你用其他软件保存文件，相同的操作也会有同样的提示。

**Comment by CWZ7605** [comment]
> 这个是系统自带的文件对话框的逻辑，你用其他软件保存文件，相同的操作也会有同样的提示。

我用Word，保存为PDF进行测试，没有这样的问题。

https://user-images.githubusercontent.com/4016785/210477505-be043f89-75e4-458d-a834-c71813b5d96f.mp4

**Comment by liulex** [comment]
不如你用记事本试一下？
