### ISSUE TITLE
检测窗口元素功能时灵时不灵

### ISSUE THREAD

**Issue by jqrxjkpyjpn** [Snipaste/feedback#2457]
### 联系方式

yf1205204316@gmail.com

### 发生了什么？

在给图表截图时，有时可以自动检测出表格，非常好用，直接截图就行，但有时功能又会失效，不知道究竟是什么原因，设置也没动过。

### 运行平台

Windows 桌面

### 软件版本

v2.8.3

**Comment by StarryVoid** [comment]
图表，什么图表，什么表格，什么截图方式
请详细描述

**Comment by jqrxjkpyjpn** [comment]
> 图表，什么图表，什么表格，什么截图方式 请详细描述

比如在这个界面，按F1截图时，
![image](https://user-images.githubusercontent.com/47104294/211466647-f206e272-afe4-4157-ab01-1041aa1f0b77.png)
“自动检测表格”功能生效时，会自动截出画红线的图表区域
![image](https://user-images.githubusercontent.com/47104294/211466853-87f874c4-3cdc-4c2e-a340-b28949c68522.png)
就是“自动检测窗口”这个功能可以“自动检测图表”。
但这个功能有时会生效，有时又不会，按tab切换也没用，设置里面功能是打开的。
![image](https://user-images.githubusercontent.com/47104294/211467168-900cf13f-0606-4224-aea8-7f8675d3424c.png)

**Comment by Geeyun-JY3** [comment]
这是在浏览器内打开的还是什么应用

**Comment by jqrxjkpyjpn** [comment]
> 这是在浏览器内打开的网页还是什么别的软件

百分浏览器，版本 5.0.1002.295（正式版本） （64 位） (Portable) (Chromium 102.0.5005.167)，一款chromium内核的浏览器，另外chrome、edge也都试过了，一样的问题。
网站是粉笔网 的行测题库。

**Comment by Geeyun-JY3** [comment]
> > 这是在浏览器内打开的网页还是什么别的软件
> 
> 百分浏览器，版本 5.0.1002.295（正式版本） （64 位） (Portable) (Chromium 102.0.5005.167)，一款chromium内核的浏览器，另外chrome、edge也都试过了，一样的问题。
> 网站是粉笔网 的行测题库。

开了无障碍没有：https://docs.snipaste.com/zh-cn/troubleshooting?id=截图时无法自动选取浏览器窗口的页面元素

**Comment by jqrxjkpyjpn** [comment]
> > > 这是在浏览器内打开的网页还是什么别的软件
> > 
> > 
> > 百分浏览器，版本 5.0.1002.295（正式版本） （64 位） (Portable) (Chromium 102.0.5005.167)，一款chromium内核的浏览器，另外chrome、edge也都试过了，一样的问题。
> > 网站是粉笔网 的行测题库。
> 
> 开了无障碍没有：[https://docs.snipaste.com/zh-cn/troubleshooting?id=截图时无法自动选取浏览器窗口的页面元素](https://docs.snipaste.com/zh-cn/troubleshooting?id=%E6%88%AA%E5%9B%BE%E6%97%B6%E6%97%A0%E6%B3%95%E8%87%AA%E5%8A%A8%E9%80%89%E5%8F%96%E6%B5%8F%E8%A7%88%E5%99%A8%E7%AA%97%E5%8F%A3%E7%9A%84%E9%A1%B5%E9%9D%A2%E5%85%83%E7%B4%A0)

这两个点上后，问题解决，非常感谢~
