### ISSUE TITLE
贴图激活时的边框阴影（窗口阴影）颜色可否自定义

### ISSUE THREAD

**Issue by FanNengHu** [Snipaste/feedback#2462]
### 功能描述

贴图激活时（就是用鼠标点着的时候），边框阴影是蓝色的。而贴图不激活时，边框阴影是灰色的。

如果我想让贴图激活和不激活的时候，边框阴影颜色保持一致（我觉得这样更加不容易分散注意力），那么我只能改变主题的颜色，让主题的颜色和贴图的边框阴影颜色保持一致才可以。

而这样也很不好，因为一旦改变主题的颜色，那么截图的时候，边框的颜色也会跟着变。

所以我想建议作者，贴图激活时的边框阴影颜色，能不能也增加一个自定义的选项，让用户可以自己调节。

非常感谢作者的努力。

**Comment by liulex** [comment]
![image](https://user-images.githubusercontent.com/2010459/226154932-5409e346-3578-45ff-99c8-4b69d166ec8e.png)
