### ISSUE TITLE
增加功能: 截图粘贴图片压缩功能

### ISSUE THREAD

**Issue by jqtmviyu** [Snipaste/feedback#2464]
### 功能描述

~~1. 希望 macos 增加开关: 双击贴图不关闭贴图~~
~~原因: 误操作的概率有点高, 在贴图及附近一定范围快速双击, 贴图就会消失. 隔几天就发生一次. 特别是工作经常切换窗口的时候.~~
~~仔细寻找没有找到开关, 不知道是功能还是bug~~
快捷键在**控制:鼠标**

2. 增加功能: 复制粘贴图片能选择图片质量以及格式
原因: 写markdown文档时经常要使用截图, 想压缩只能先保存再使用. 

系统: macos 12.5.1

**Comment by Geeyun-JY3** [comment]
图片质量重复：#2171

另见：https://docs.snipaste.com/zh-cn/faq

> 14. 输出的图片质量怎么设置？
> 
>     `-1` 表示自动设置，`0` 表示最低质量，`100` 表示最高质量。
> 
>     对大部分用户来说，使用 `-1` 即可。如设置为 `100`，可能导致图片文件的体积非常大。
> 
>     至于复制到剪贴板中的图像质量，暂时没有提供设置。
