### ISSUE TITLE
不小心在Microsoft Store免密支付购买了，无法退款，能不能告诉我怎么退款

### ISSUE THREAD

**Issue by Shesaid-No** [Snipaste/feedback#2468]
### Problem Description

不小心在Microsoft Store免密支付购买了，无法退款，能不能告诉我怎么退款

### Platform

Microsoft Store

### Version

Snipaste 截图+贴图

**Comment by KazamaSion** [comment]
@Shesaid-No 如果下面的方法不管用，就是无法退款了。

https://answers.microsoft.com/zh-hans/windows/forum/all/微软绑定了/dbe307fa-9ef2-4ef7-8d3f-2ba424a60f82

**Comment by Shesaid-No** [comment]
> @Shesaid-No 如果下面的方法不管用，就是无法退款了。
> 
> [https://answers.microsoft.com/zh-hans/windows/forum/all/微软绑定了/dbe307fa-9ef2-4ef7-8d3f-2ba424a60f82](https://answers.microsoft.com/zh-hans/windows/forum/all/%E5%BE%AE%E8%BD%AF%E7%BB%91%E5%AE%9A%E4%BA%86/dbe307fa-9ef2-4ef7-8d3f-2ba424a60f82)

谢谢，已解决，电话联系微软客服帮忙退款了
