### ISSUE TITLE
希望更加开放，更加灵活

### ISSUE THREAD

**Issue by cesarli** [Snipaste/feedback#2471]
### 功能描述

希望开放一些SDK在pro版本中，可以实现很多自定义功能，比如我可以根据SDK + 设置中设置好接口。可以实现截图后自动上传到其他地方，比如我自己的群晖，百度云盘等等。

**Comment by Geeyun-JY3** [comment]
相关：#60、https://github.com/Snipaste/feedback/issues/282#issuecomment-268238525

**Comment by liulex** [comment]
已经可以通过自定义命令实现截图后自动调用其他程序。
https://docs.snipaste.com/zh-cn/command-line-options
