### ISSUE TITLE
何时开放桌面版授权？

### ISSUE THREAD

**Issue by lawrenceching** [Snipaste/feedback#2472]
### 问题描述

你好，

同为开发者，我经常会在Windows, macOS 和 Ubuntu Desktop 开发环境来回切换。
（虽然目前 macOS 版还在Beta阶段，Linux 还未推出，但我对软件的未来发展充满期待。）
跨平台的授权是刚需。但等待许久也未看到你开放桌面版购买选项。

另外，你目前提供的3个购买渠道，似乎都要求绑定微软账号。
而工作电脑使用的是公司账号，我购买的专业版无法在工作场景下使用。
在公司提供的虚拟桌面环境，更是禁止了Microsoft Store.

因此 无法跨平台 和 微软账号绑定 是我购买专业版的首要阻碍。

请问作者能否给个大概的时间，何时能开放桌面版授权？

非常感谢。

### 运行平台

微软商店

### 软件版本

2.8.4

**Comment by BellModena** [comment]
我等了2年都没等到，最后还是买了微软商店版本，我们公司也是禁用微软商店的，但我偷偷换了硬盘重新做了系统

**Comment by hzhbest** [comment]
作者更新了这么多个版本依然是beta，为什么，因为桌面版他非常非常非常的害怕被破解，害怕自己该收到的钱收不到，这很正常，只是他无论如何，即使让用户死活得不到专业版，也不愿意勇敢面对这种恐惧，就有点过了。
因此，作者只是在他信得过的微软商店放上专业版，Steam他也信不过，更不用说开放桌面版了。
当然，是否开放是作者的自由；我只能继续使用1.x版。

**Comment by stevenzhu25** [comment]
@hzhbest （不是作者）
我觉得你前面一些说的没毛病… 
哪个开发者都怕盗版， 尤其是现在没出桌面版但是Google一搜都有所谓的破解版链接 
https://www.google.com/search?q=Snipaste%20%E7%A0%B4%E8%A7%A3

我倒是不太同意你说即使让用户死活得不到专业版这句， 毕竟Microsoft Store的确有专业版… 
我自己是家里买了Store版的专业版内购， 然后公司电脑用1.x… （我也希望能有非Store版的专业版授权， 但是说实话如果大部分用户会跑去下载破解版那对作者来说就很悲哀了… 毕竟现在还是有很多人花钱去淘宝买各种免费版下载链接 - 不是说这个软件，但是不愿意给付费软件花钱）

**Comment by hzhbest** [comment]
@stevenzhu25 
我倒是从来没搜过它的破解版；刚才打开你的链接从中随便下了四个，四个都是免费版或者重新打包的免费版压缩包，有些搜索结果写“破解”，里面页面没有；就算页面有，下载回来的依然只是免费版。而且，也不存在微软商店版转成桌面版这种可能性吧？
所以，作者就是靠此杜绝了破解，杜绝了该收到的钱收不到的可能（而且其对收钱的渴望可是写在专业版的介绍中的）。
让用户死活得不到专业版有问题吗？就是无法得到啊。多少公司是禁用微软商店的，多少公司直接装的就是不含微软商店（及游戏）的企业版，用这些电脑办公的人就是无法得到啊。而他明确写着，“Snipaste 2.x 只对个人用户免费，公司使用请购买专业版或使用 Snipaste 1.x”，所以不能装能解锁专业版的电脑还是只能装1.x。
-------
我是从知道这个软件的第一天起（都有5、6年了吧）就一直关注它2.0的桌面版，为的是其专业版声称的截图时可以滚轮选择父／子控件（元素），特别是它本身就支持对Firefox的网页元素进行选择，这让我对滚轮调整选择这个功能十分之向往，但我那时候还是用Win7，于是也无缘试用或购买，即使如此我仍然是月月关注着其桌面版；到2.0的桌面版真出来了，我反倒失望了，期望极久的滚轮调整选择功能连试用都不给，这就算了，还是一直一直，一直都不提供解锁专业版的入口……多少年了，心灰意冷了。
-----------
我平时用软件基本能是免费版的都用免费版 ，办公抛弃Office用WPS，查空间占用抛弃TreeSize Professional用WizTree，压缩抛弃WinRAR用几乎一样好用的BandiZip，还是无广告的旧版。
我仅有的几次真心愿意付钱购买的软件，先是UltraISO，用来加载镜像和刻盘，其实两个功能都有免费替代，但用它的破解版用多了，决定支持一下作者；然后是Beyond Compare，因为比较过好多软件，能够像BC那么全能和方便易用的实在找不到（当然它时不时会让破解无法运行也是一个因素），文件比较可以查看内容差异，文件夹比较可以用来选择性同步文件，实在必须就买了，感觉也值，而且不限设备，只是同一个注册码不能同时在不同电脑上运行罢了；然后就是Snipaste，钱都攒在手里老久了，它就是不出，就是不出，我能怎样。顺便，我现在也没那么强烈的必须能滚轮调整选择的需求了，1.x足矣（甚至还觉得2.0反应慢）。

**Comment by septs** [comment]
Duplicate of #1162

**Comment by lededev** [comment]
> ## 我是从知道这个软件的第一天起（都有5、6年了吧）就一直关注它2.0的桌面版，为的是其专业版声称的截图时可以滚轮选择父／子控件（元素），特别是它本身就支持对Firefox的网页元素进行选择，这让我对滚轮调整选择这个功能十分之向往，但我那时候还是用Win7，于是也无缘试用或购买，即使如此我仍然是月月关注着其桌面版；到2.0的桌面版真出来了，我反倒失望了，期望极久的滚轮调整选择功能连试用都不给，这就算了，还是一直一直，一直都不提供解锁专业版的入口……多少年了，心灰意冷了。

## 我也喜欢这个想法，滚轮选择窗口很方便。但是只有商店版本的确不符合我的需求，于是我用GPL3开源的Flameshot自己做了[这个功能](https://github.com/lededev/flameshot-win/releases)，上滚从当前鼠标位置所包含的窗口中选择面积最小的一个，连续上滚选择面积更大的窗口。下滚从当前鼠标位置选择面积最小的主程序窗口（顶级窗口），如果不是想要的窗口则改为上滚，选择更大面积窗口，如果想选子窗口则继续下滚，选择面积更小的窗口。

**Comment by PjqDD** [comment]
固步自封，只会死的很惨。PixPin 功能媲美Snipaste的专业付费版，无广告干扰， 软件目前是完全免费的，后期是否会收费不得而知，挂个官网链接  https://pixpinapp.com
