### ISSUE TITLE
我想购买专业版但是出现了问题

### ISSUE THREAD

**Issue by BlissFulLei** [Snipaste/feedback#2473]
### 问题描述

![image](https://user-images.githubusercontent.com/122717601/212527801-60904324-7fb9-479b-b6c9-cb305cd0db4d.png)

### 运行平台

微软商店

### 软件版本

2.8.4

**Comment by Geeyun-JY3** [comment]
那就先按图里说的试试取消以管理员身份运行

**Comment by BlissFulLei** [comment]
我就没法选择，也没用管理员运行，但已经搞定了，用了大佬做的脚本把最新版的任务栏关掉了，就好了

**Comment by BlissFulLei** [comment]
> 

我没有办法调整，并且我也没有用管理员运行
![image](https://user-images.githubusercontent.com/122717601/212593246-a5c8e56e-247f-4251-9dde-b473f41a6a60.png)

**Comment by Geeyun-JY3** [comment]
呃是无法以管理员身份运行吗？

**Comment by kymowang** [comment]
我也遇到这个问题了，win10, ver2.8.4

**Comment by Pandaft** [comment]
可能是关闭 UAC 导致的问题：
- https://github.com/Snipaste/feedback/issues/1059#issuecomment-981223209

**Comment by kymowang** [comment]
> 可能是关闭 UAC 导致的问题：
> 
> * [Microsoft Store 内购专业版弹出界面瞬间退出 #1059 (comment)](https://github.com/Snipaste/feedback/issues/1059#issuecomment-981223209)

的确是，打开UAC就可以了，这个错误报的太离谱了。

**Comment by liulex** [comment]
下个版本会改进这里的提示的，谢谢反馈和建议！
