### ISSUE TITLE
历史版本下载

### ISSUE THREAD

**Issue by Hisolated** [Snipaste/feedback#2474]
### 功能描述

我有个低版本的mac，无法安装snipaste，也没法选择指定的版本下载，希望有个历史版本下载功能

**Comment by KazamaSion** [comment]
@Hisolated Duplicate of #1952

**Comment by Hisolated** [comment]
> @Hisolated Duplicate of #1952

谢谢

**Comment by Geeyun-JY3** [comment]
Duplicate of #1952
