### ISSUE TITLE
刚刚购买了付费版本，windows11下F1键冲突，好像其他组合键也按不出来。

### ISSUE THREAD

**Issue by wh000wh000** [Snipaste/feedback#2489]
### 问题描述

不知道原因= =好像软件本身也没有提示冲突，用起来很不方便，家里的win11到是正常。可以帮帮我吗，谢谢。

### 运行平台

微软商店

### 软件版本

2.8.4 2023.01.09 64位pro

**Comment by wh000wh000** [comment]
误打误撞找到原因了，罗技键盘必须要按FN+F键

**Comment by stevenzhu25** [comment]
@wh000wh000 那是因为你罗技键盘的FN锁开了… 调一下就行了
