### ISSUE TITLE
当全屏应用退出时，所有贴图马上消失

### ISSUE THREAD

**Issue by 226723** [Snipaste/feedback#2490]
### 发生了什么？

**### 问题描述：**
1. 无论**贴图**是在 全屏软件打开之前已经存在 还是 全屏软件打开之后存在，只要存在一个全屏软件**关闭**之后(不是最小化)，所有贴图马上消失（例如全屏的浏览器，甚至win自带的文件管理器全屏）。当下一次进行贴图时，所有贴图又会重新出现。概率为95%。（发这个issue之前，又测试了一下，发现鼠标只要移动到全屏软件的关闭按钮上时并不用点击，贴图就会消失）
2. 当存在一个贴图时，打开一个全屏应用，贴图有概率会消失。概率不大，测试了10多次，就有两次出现。

### 运行平台

Windows 桌面

### 软件版本

专业版Pro 2.8.2

**Comment by 226723** [comment]
所以在打开全屏应用或者关闭全屏应用时，贴图就很鬼畜。。。时而消失时而出现。（系统为win10）

**Comment by Jessica0401-33** [comment]
可以試按 F3，會跳出來

**Comment by acbetter** [comment]
这个 bug 挺烦人的。。。

**Comment by 226723** [comment]
> 可以試按 F3，會跳出來

但是它先跳出来的是剪辑版里的，再按一下才出来。而且有时候贴图会全出来。

**Comment by 226723** [comment]
> 这个 bug 挺烦人的。。。

的确，都快烦死我了，贴图一会出现一会消失的

**Comment by acbetter** [comment]
> > 这个 bug 挺烦人的。。。
> 
> 的确，都快烦死我了，贴图一会出现一会消失的

我发现重启 snipaste 可以恢复之前的贴图，而且使用 sharex 有时也会复现这个 bug，可能是 windows 设置的问题

**Comment by liulex** [comment]
> 只要存在一个全屏软件关闭之后(不是最小化)，所有贴图马上消失

这是专业版触发角的功能，如果不需要请关闭或者调整参数降低误触。
![image](https://user-images.githubusercontent.com/2010459/226155028-daf7ea8a-495f-4a07-aff7-1baabfee7c8e.png)
