### ISSUE TITLE
win11商店版无法正常启动，事件查看器错误模块名称

### ISSUE THREAD

**Issue by Yj0211** [Snipaste/feedback#2492]
### Problem Description

很早前已经购买过专业版本，之前使用一直正常，近期出现无法启动的问题，尝试微软商店卸载Snipaste后重装还是不行

事件查看器内容：

错误应用程序名称: Snipaste.exe，版本: 2.8.4.0，时间戳: 0x63bc0750
错误模块名称: combase.dll，版本: 10.0.25290.1000，时间戳: 0x7940a621
异常代码: 0xc0000602
错误偏移量: 0x00000000000413c9
错误进程 ID: 0x0x1C1C
错误应用程序启动时间: 0x0x1D93849C5E8CC4E
错误应用程序路径: C:\Program Files\WindowsApps\45479liulios.17062D84F7C46_2.8.400.0_x64__p7pnf6hceqser\Snipaste.exe
错误模块路径: C:\WINDOWS\System32\combase.dll
报告 ID: 3e15d040-9c38-4e99-b646-799918c3dbd7
错误程序包全名: 45479liulios.17062D84F7C46_2.8.400.0_x64__p7pnf6hceqser
错误程序包相对应用程序 ID: Snipaste

### Platform

Microsoft Store

### Version

2.8.4

**Comment by Yj0211** [comment]
补充：很早前已经购买过专业版本，之前使用一直正常，近期出现无法启动的问题，尝试微软商店卸载Snipaste后重装还是不行

**Comment by Hsnico** [comment]
是不是最近更新到了Windows 11 Insider 25290？可以使用dism++修复系统暂时解决，不过一段时间后问题又会出现，回退到上一个Windows版本问题消失

**Comment by Hsnico** [comment]
微软应该已经知道了这个问题 [已知问题](https://blogs.windows.com/windows-insider/2023/02/01/announcing-windows-11-insider-preview-build-25290/#:~:text=investigating%20this%20issue.-,%5BADDED%202/3%5D,-We%E2%80%99re%20investigating%20reports)，NVIDIA 控制面板之类应用也出现了类似的情况

**Comment by Yj0211** [comment]
> 是不是最近更新到了Windows 11 Insider 25290？可以使用dism++修复系统暂时解决，不过一段时间后问题又会出现，回退到上一个Windows版本问题消失

是的，这两天刚更新的，那我先回退吧

**Comment by Yj0211** [comment]
> 微软应该已经知道了这个问题 [已知问题](https://blogs.windows.com/windows-insider/2023/02/01/announcing-windows-11-insider-preview-build-25290/#:~:text=investigating%20this%20issue.-,%5BADDED%202/3%5D,-We%E2%80%99re%20investigating%20reports)，NVIDIA 控制面板之类应用也出现了类似的情况

那就等他们修复吧，谢谢！！

**Comment by HanHua0402** [comment]
> 是不是最近更新到了Windows 11 Insider 25290？可以使用dism++修复系统暂时解决，不过一段时间后问题又会出现，回退到上一个Windows版本问题消失

确实是因为Windows 11 Insider Preview 25290.1000 (rs_prerelease)的问题，真是头大
