### ISSUE TITLE
网页图片拖拽到已有贴图不可操作，显示一个禁止符号

### ISSUE THREAD

**Issue by Haiirose** [Snipaste/feedback#2493]
### Problem Description

本地图片拖放到已有贴图也是禁止符号

微软商店的专业版，最新版
系统win10，浏览器是谷歌浏览器

### Platform

Microsoft Store

### Version

2.8.4

**Comment by Haiirose** [comment]
看来是管理员权限的问题，关了后能拖放

但是关掉管理员权限，全局快捷键不能用，希望以后能有两全的办法

**Comment by liulex** [comment]
这是 Windows 系统的限制，解决起来比较麻烦，以后有空再尝试。
