### ISSUE TITLE
功能扩展建议：1）双击屏幕截图，最小化/还原；2）屏幕截图的透明度支持；3）允许屏幕截图不显示在最前

### ISSUE THREAD

**Issue by WaylandGod** [Snipaste/feedback#2494]
### 功能描述

截屏需要长时间存在，以便后续进行对比时，每个截屏比较占屏幕空间，比如需要监听一些性能数据，随手进行了多次截屏。可以考虑，1）比如在双击时，最小化成图标大小，然后再次双击时，还原到原大小；2）添加对屏幕上截图的透明度调整的支持；3）允许屏幕截图不显示在最前的接口。这样不必反复去操作保留下的截图文件，可以提高很大的效率

**Comment by Geeyun-JY3** [comment]
请认真阅读文档，善用搜索。

1. https://docs.snipaste.com/zh-cn/getting-started?id=缩略图模式
有快速缩略图的操作，默认操作是 <kbd>Shift</kbd>+<kbd>左键双击</kbd>，改成左键双击注意和其他操作的冲突
如果还是嫌缩略图大，专业版缩略图可以自由尺寸
![image](https://user-images.githubusercontent.com/49396421/216828938-98130876-09c8-4e46-9ced-dd116f3a5581.png)
2. https://docs.snipaste.com/zh-cn/getting-started?id=设置贴图透明度
<kbd>Ctrl</kbd> + <kbd>滑动滚轮</kbd> 或 <kbd>Ctrl</kbd> + <kbd>+</kbd>/<kbd>-</kbd> 
3. 什么叫「不显示在最前的接口」？不显示在最前的**贴图**？有显示/隐藏所有贴图的快捷键，你也可以将保留下暂时用不到的贴图放到一个贴图组后切换到另一个贴图组再截图

**Comment by Geeyun-JY3** [comment]
哦 3 说的是让贴图不置顶是吧。这需要 Pro: https://docs.snipaste.com/zh-cn/pro?id=贴图相关
