### ISSUE TITLE
文档及应用内文案错误反馈

### ISSUE THREAD

**Issue by Geeyun-JY3** [Snipaste/feedback#2498]
### 发生了什么？

1. 文档错误：
   1. [常见问题](https://docs.snipaste.com/zh-cn/faq) 里的第 11 点可以删掉了
   ![image](https://user-images.githubusercontent.com/49396421/217156820-72ffebd4-b3c8-4eaf-9809-ab8796b97bc5.png)
   [2.4 版本](https://docs.snipaste.com/zh-cn/changelog?id=v24) 已经更改了设置方式，首选项里能直接选择彩色图标了。
![image](https://user-images.githubusercontent.com/49396421/217156919-061ef5d2-0698-48f8-ae33-d89c724305ac.png)
   2. [2.8 版本](https://docs.snipaste.com/zh-cn/changelog?id=v28)加入的需要专业版的 `empty-group` 和 `show-group-manager` 命令行选项在[其他命令部分](https://docs.snipaste.com/zh-cn/command-line-options?id=%e5%85%b6%e4%bb%96%e5%91%bd%e4%bb%a4)中未加粗：
![image](https://user-images.githubusercontent.com/49396421/217160130-3faedb0d-5103-42f6-979f-073b5f6102da.png)
2. 应用内文案错误（我个人感觉不是很准确）：
命名规则里的几个输出结果非数字的日期和时间变量：[`周几（Localized day name (abbr.)）`](https://translations.snipaste.com/translate/snipaste/snipaste/zh_Hans/?checksum=cf4d7dd0eec49c95)、[`星期几（Localized day name）`](https://translations.snipaste.com/translate/snipaste/snipaste/zh_Hans/?checksum=6467d3c006dd618e)、[`月份名 (小写)（Localized month name (abbr.)）`](https://translations.snipaste.com/translate/snipaste/snipaste/zh_Hans/?checksum=29af0a2758bc2099)、[`月份名 (大写)（Localized month name）`](https://translations.snipaste.com/translate/snipaste/snipaste/zh_Hans/?checksum=33514a11da4ad7d2)（即其英文为以「[Localized](https://translations.snipaste.com/languages/zh_Hans/snipaste/search/?offset=1&q=Localized&sort_by=-priority%2Cposition&checksum=)」开头的几个字符串）的名称感觉（无论简体中文还是英文）都不太准确，上述几个变量实际输出到文件名里的都是英文，区别只是全称还是缩写，和「大写」「小写」「Localized」都无关吧，简体中文可改成如 `星期几 (英文缩写)`、`星期几 (英文全称)`，英文可改成如 `English day name (abbr.)`、`English day name`。

### 运行平台

微软商店

### 软件版本

2.8.4 (2023.01.09)

**Comment by liulex** [comment]
文档错误已更正。
关于命令行选项 `empty-group`，其实是免费版就可以用的，是更新日志写错了，也已更正。

命名规则里的文案，在以前确实是本地化过的名字，但对于部分 locale 会出现乱码的情况 (e.g. https://github.com/Snipaste/feedback/issues/969)，所以后面统一用英文作为 locale 了。
我会在下个版本更新相应的文案。

非常感谢您的反馈！
