### ISSUE TITLE
Screenshot OCR needed!!!

### ISSUE THREAD

**Issue by dw0216** [Snipaste/feedback#2499]
### Feature Description

Please add OCR(Optical character recognition) feature as it would be one of the key feature to select a screenshot software.

**Comment by Geeyun-JY3** [comment]
Duplicate of #188

**Comment by dw0216** [comment]
Will OCR never be implemented as Snipaste's feature?
Snipaste Pro is one of my favorite software but OCR is one essential function I needed which Snipaste is missing...

**Comment by Geeyun-JY3** [comment]
I close your issue just because it is duplicate. 
I do not know if it would be implemented, either
