### ISSUE TITLE
希望mac版菜单栏图标可以支持关闭

### ISSUE THREAD

**Issue by vannvan** [Snipaste/feedback#2503]
如题

**Comment by Geeyun-JY3** [comment]
请善用搜索，认真阅读文档：https://docs.snipaste.com/zh-cn/advanced-configs?id=general

> ```
> ; 隐藏托盘图标 (>= v1.8)
> ; 图标隐藏后，如需唤出首选项窗口，请在贴图上按 Ctrl + Shift + P (Windows) / Cmd + , (macOS)
> ; 有效值：true, false
> ```
> 
> hide_tray_icon=true

**Comment by vannvan** [comment]
哈哈，大意了😁
