### ISSUE TITLE
增加图片文件右键菜单“贴图”功能

### ISSUE THREAD

**Issue by RxinnotRstar** [Snipaste/feedback#2510]
### 功能描述

之前用过utools，它的“贴图”功能非常好用，支持贴本地文件、截图（就像snipaste一样），甚至是QQ里的图片。我希望snipaste也能做一个类似的功能，只需要右键一个图片文件，就可以用贴图功能把它贴在屏幕上。

**Comment by Geeyun-JY3** [comment]
请不要再开重复 issue，你已经开过一次了：#2446

**Comment by Geeyun-JY3** [comment]
Duplicate of #1485
