### ISSUE TITLE
文字贴图支持自定义回退字体

### ISSUE THREAD

**Issue by ExcuseLme** [Snipaste/feedback#2511]
### 功能描述

现在只能设置一份主字体, 有的字体只支持西文, 这时候复制的中文贴图出来会自动回退为不知道是什么字体(经过测试, 应该不是回退为系统字体, 我的系统字体是微软雅黑, 但在我这儿复制中文后贴图出来的字体明显不是微软雅黑), 但我更希望自己指定回退字体, 比如主字体设置为JetbrainsMono, 回滚字体设置为微软雅黑, 这种主字体/回滚字体双重设置的支持在别的软件里也挺常见的, 可见有一定需求量, 希望能够安排到开发计划里, thanks!

**Comment by Geeyun-JY3** [comment]
#2230
