### ISSUE TITLE
在百度网盘窗口无法使用任何截屏快捷键

### ISSUE THREAD

**Issue by 524785937** [Snipaste/feedback#2512]
### 联系方式

xiao_524785937@qq.com

### 发生了什么？

win11 PRO商店版本，是什么原因呢

### 运行平台

微软商店, Windows 桌面

### 软件版本

2.8.4

**Comment by BellModena** [comment]
那是因为那个软件本身也有这个快捷键，它们产生了冲突

**Comment by liulex** [comment]
[故障排除 | 有时候快捷键不响应](https://docs.snipaste.com/zh-cn/troubleshooting?id=%e6%9c%89%e6%97%b6%e5%80%99%e5%bf%ab%e6%8d%b7%e9%94%ae%e4%b8%8d%e5%93%8d%e5%ba%94)
