### ISSUE TITLE
截图加上标注时，不能使用 C键

### ISSUE THREAD

**Issue by 13-ts** [Snipaste/feedback#2516]
### 发生了什么？

使用快捷键ctrl+w，然后点击标注，输入文字在我想打”词“这个字的时候出现了问题，然后我试了一下，c打不出来其他字母都没有问题

### 运行平台

Windows 桌面

### 软件版本

当时使用的snipaste-2.7.3-Beta-x64，但是刚刚我更新到了最新版本还是有这个问题

**Comment by Geeyun-JY3** [comment]
#2078？

另外 <kbd>Ctrl</kbd>+<kbd>W</kbd> 不是关闭贴图窗口么，和这没关系吧

**Comment by 13-ts** [comment]
emmm我设置的快捷键是ctrl+w。反正就是在标注的时候用不了C键&nbsp;


13ts
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月21日(星期二) 中午12:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Snipaste/feedback] 截图加上标注时，不能使用 C键 (Issue #2516)





 
#2078？
 
另外 Ctrl+W 不是关闭贴图窗口么，和这没关系吧

**Comment by Geeyun-JY3** [comment]
所以是不是在远程桌面上：#2078

**Comment by 13-ts** [comment]
不是在远程桌面，就是非常普通的操作。上一周都还是好的。我想说卸载重装，但是没在网上找到卸载的方法~
&nbsp;


13ts
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月21日(星期二) 下午2:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Snipaste/feedback] 截图加上标注时，不能使用 C键 (Issue #2516)





 
所以是不是在远程桌面上：#2078

**Comment by ming2048** [comment]
遇到同样的问题，是在远程桌面上，截图标注时，无法打出字母 C ，其他都正常，版本2.4.0beta

**Comment by Geeyun-JY3** [comment]
> 我想说卸载重装，但是没在网上找到卸载的方法~

便携软件卸载就直接把文件夹删了就行。

**Comment by Geeyun-JY3** [comment]
不管是不是远程桌面，都试试这个方法能不能解决吧，毕竟文档里有提到也不只是远程桌面会造成这种现象：https://github.com/Snipaste/feedback/issues/640#issuecomment-346732910
https://github.com/Snipaste/feedback/wiki/%E9%AB%98%E7%BA%A7%E8%AE%BE%E7%BD%AE/d69cbd063f8d669ceefe4a7d498f2e0a4126406b#snip

**Comment by Geeyun-JY3** [comment]
还有个相关的选项……：https://github.com/Snipaste/feedback/issues/2967#issuecomment-2158628895
