### ISSUE TITLE
类似QQ截图的数字标注功能

### ISSUE THREAD

**Issue by Fowindy** [Snipaste/feedback#2525]
### 功能描述

![image](https://user-images.githubusercontent.com/45205351/221554281-73c6b25c-a490-4ebd-bdd1-6006888cbb5d.png)
做截图笔记的时候非常需要这个功能,请作者帮忙添加,谢谢

**Comment by liulex** [comment]
专业版早就有了。

**Comment by Fowindy** [comment]
你没有听明白我的意思啊?我知道snipaste有数字标准的功能,只是点完数字之后我还想自己打字说明,snipaste还得按一下T才可以,而QQ点击数字之后,立马旁边就有一个编辑框,我想输入内容就可以直接输入内容,而snipaste还得再按一下T

从 Windows 版邮件发送

发件人: Le Liu
发送时间: 2023年3月19日 12:21
收件人: Snipaste/feedback
抄送: Fowindy; Author
主题: Re: [Snipaste/feedback] 类似QQ截图的数字标注功能 (Issue #2525)

专业版早就有了。

**Comment by Fowindy** [comment]
shang

上图是snipaste的效果,我店家数字标签出现1之后我如果想打字,我还得点一下T才行,


下图是QQ截图的效果,点击1之后,后面立马出现一个编辑框,我可以直接编辑想打的字,如果不想编辑不用打字就可以了



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "470026339"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月19日(星期天) 中午1:19
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复: [Snipaste/feedback] 类似QQ截图的数字标注功能 (Issue #2525)



 
你没有听明白我的意思啊?我知道snipaste有数字标准的功能,只是点完数字之后我还想自己打字说明,snipaste还得按一下T才可以,而QQ点击数字之后,立马旁边就有一个编辑框,我想输入内容就可以直接输入内容,而snipaste还得再按一下T

&nbsp;

从 Windows 版邮件发送

&nbsp;

发件人: Le Liu
发送时间: 2023年3月19日 12:21
收件人: Snipaste/feedback
抄送: Fowindy; Author
主题: Re: [Snipaste/feedback] 类似QQ截图的数字标注功能 (Issue #2525)


&nbsp;

专业版早就有了。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

&nbsp;

**Comment by Geeyun-JY3** [comment]
怪不得这么多人叫这功能「序号笔」还持续来开 issue，原来 QQ 的序号笔还这样能带注释。

@Fowindy 你来 GitHub 看，作者编辑过评论且明确回应了：

> ~~专业版早就有了。~~
> 抱歉，理解错了，但你提到的功能我目前不会考虑。

另外不要通过邮件发图，GitHub 这边也看不到的。

***

感觉可以合并至 #1604。
