### ISSUE TITLE
自定义截屏不需要每次弹出窗口

### ISSUE THREAD

**Issue by ken-gu** [Snipaste/feedback#2530]
### 功能描述

自定义截屏不需要每次弹出窗口，比如使用快捷键进行自定义截屏时，不需要每次都弹出窗口设置截屏大小，可以只需要在鼠标点击时弹出，快捷键时无需弹出。(mac系统）
![03_06_08_54_12](https://user-images.githubusercontent.com/3443681/222996824-e45578bd-54f4-4542-b41f-365271f6dc49.jpg)

**Comment by Geeyun-JY3** [comment]
不弹出对话框让用户选怎么知道接下来干嘛

**Comment by ken-gu** [comment]
> 不弹出对话框让用户选怎么知道接下来干嘛

不就是截图吗，就是在对应位置（默认0，0）显示出截屏框的大小，只不过是去掉弹框这一步，省略掉点击窗口上的确定按钮而已，怎么不知道接下来干嘛了？

**Comment by Geeyun-JY3** [comment]
> 不就是截图吗，就是在对应位置（默认0，0）显示出截屏框的大小，只不过是去掉弹框这一步，省略掉点击窗口上的确定按钮而已，怎么不知道接下来干嘛了？

呃那怎么知道用户是否需要更改左上角位置、更改截图区域大小、是否需要进行延迟截图、是否需要更改延迟秒数？

**Comment by ken-gu** [comment]
> > 不就是截图吗，就是在对应位置（默认0，0）显示出截屏框的大小，只不过是去掉弹框这一步，省略掉点击窗口上的确定按钮而已，怎么不知道接下来干嘛了？
> 
> 呃那怎么知道用户是否需要更改左上角位置、更改截图区域大小、是否需要进行延迟截图、是否需要更改延迟秒数？

在菜单上点击的时候可以弹出来，快捷键唤出时不需要弹出来

**Comment by Geeyun-JY3** [comment]
> 在菜单上点击的时候可以弹出来，快捷键唤出时不需要弹出来

在专业版支持[全局快捷键 与 命令行调用 绑定](https://docs.snipaste.com/zh-cn/pro?id=b-更自由的定制化)的现状下，感觉没有必要。（Mac 版的专业版是另一个问题）
再说了，明明就是一个功能的不同进入方式，为什么要让鼠标点击和快捷键唤起的结果不一致？用户不会困惑吗？Snipaste 中似乎也无相关先例。

**Comment by ken-gu** [comment]
那我想快捷截图怎么处理？每次自定义截图，你都弹出窗口让我设置，其实我不用设置，就按第一次设置的截图就行了，又要多点击一下才可以，用户体验的问题。

**Comment by Geeyun-JY3** [comment]
> 那我想快捷截图怎么处理？每次自定义截图，你都弹出窗口让我设置，其实我不用设置，就按第一次设置的截图就行了，又要多点击一下才可以，用户体验的问题。

不说了吗，用专业版的[全局快捷键 与 命令行调用 绑定](https://docs.snipaste.com/zh-cn/pro?id=b-%E6%9B%B4%E8%87%AA%E7%94%B1%E7%9A%84%E5%AE%9A%E5%88%B6%E5%8C%96)啊。

**Comment by ken-gu** [comment]
没看明白怎么绑定可以进行自定义截图，但不弹出对应窗口的命令

**Comment by Geeyun-JY3** [comment]
> 没看明白怎么绑定可以进行自定义截图，但不弹出对应窗口的命令

你不说按你第一次的设置截图就行了吗，那就按[文档](https://docs.snipaste.com/zh-cn/command-line-options?id=截图命令)搭配出你要的设置然后去绑定啊，还管什么自定义截图。

**Comment by Todayos** [comment]
都快捷方式截屏了，而且有鼠标为啥还要再设置一下这个尺寸，拖动鼠标不就能直接调整尺寸了吗？

**Comment by Geeyun-JY3** [comment]
> 都快捷方式截屏了，而且有鼠标为啥还要再设置一下这个尺寸，拖动鼠标不就能直接调整尺寸了吗？

这是针对需要截指定大小的图而给的选项，如果不需要可以不勾选。
