### ISSUE TITLE
可以增加屏幕 Mask 功能来窥屏吗？

### ISSUE THREAD

**Issue by lbl0803** [Snipaste/feedback#2531]
### Feature Description

在网上查了很久屏幕 Mask，几乎没有这方面的软件。只有个别几款窗口聚焦工具。因为我的需求和 Snipaste 有一些共性，所以冒昧建议一下。比如我打开截图，但是屏幕活动不静止，而是选择一个区域正常显示，其他区域变模糊。可以参考 Obsidian 的第三方插件Privacy Glasses 。点击左边那个小眼睛其他区域都变糊，达到防窥屏的效果。

![image](https://user-images.githubusercontent.com/59354412/223308638-e2d65083-54b7-41d3-b1bc-1e635c02f605.png)

**Comment by sato94** [comment]
无语

**Comment by Geeyun-JY3** [comment]
没懂这需求和 Snipaste 有什么共性……

**Comment by lbl0803** [comment]
> 无语

就是进入截图的那个画面啊，你截图的时候整个屏幕不是变暗了吗？很难理解吗

**Comment by lbl0803** [comment]
> 没懂这需求和 Snipaste 有什么共性......

就是进入截图的那个画面啊，你截图的时候整个屏幕不是变暗了吗？很难理解吗

**Comment by sato94** [comment]
就是无法理解，有问题吗？

**Comment by lbl0803** [comment]
> 就是无法理解，有问题吗？

理解不了就不要和我说话

**Comment by stevenzhu25** [comment]
@lbl0803 说实话， 我理解你想达成什么效果， 但是实在不知道为什么这个会和截图软件有关系。
截图，贴图什么的目的是对屏幕进行定点化… 如果你要防窥屏， 最简单的应该是去买个防窥屏的膜贴在你屏幕上… 或者安装专业的隐私插件（虽然感觉这种就是浪费系统资源…）

**Comment by lbl0803** [comment]
> @lbl0803 说实话， 我理解你想达成什么效果， 但是实在不知道为什么这个会和截图软件有关系。 截图，贴图什么的目的是对屏幕进行定点化… 如果你要防窥屏， 最简单的应该是去买个防窥屏的膜贴在你屏幕上… 或者安装专业的隐私插件（虽然感觉这种就是浪费系统资源…）

谢谢你的理解。每个人需求不一样。你觉得防窥膜可以解决，但是我更需要的是屏幕 Mask 类型的软件。这类型软件不是没有，但是都不太好用。而且它确实和屏幕截图软件非常像，刚好这儿又可以和开发者交流，所以我才来这里发。我总不可能去找 QQ 截图发吧，会有人理我吗？
