### ISSUE TITLE
截图里输入阿拉伯数字后不显示

### ISSUE THREAD

**Issue by BarrySong** [Snipaste/feedback#2536]
### 联系方式

songshaopenghe@gmail.com

### 发生了什么？

打开截图功能后点击文本，然后里面敲数字但无法显示，比如123。输入其他字符均正常。
![IMG_0386](https://user-images.githubusercontent.com/23122409/223957893-2d17b3fd-a61c-4767-9ad3-bb6614f345c7.jpeg)

### 运行平台

macOS

### 软件版本

2.8.3-Beta2 (2022.12.25)

**Comment by liulex** [comment]
注意你用的字体：
![image](https://user-images.githubusercontent.com/2010459/226153416-57fbe5d0-8226-41df-8ccf-9e5c5f84c39a.png)
