### ISSUE TITLE
长截图+App Store

### ISSUE THREAD

**Issue by pengfeichencpf** [Snipaste/feedback#2537]
### 功能描述

1.请问会考虑一下长截图和文字识别功能吗？
2.请问一下会考虑上架MacOS的AppStore吗？
谢谢！

**Comment by septs** [comment]
Duplicate of #19

**Comment by pengfeichencpf** [comment]
这个帖子出来很久了，一直没有收到正面回答过。另，会上架MacOS Store吗？

**Comment by stevenzhu25** [comment]
@pengfeichencpf 长截图是属于 #19 的issue.
MacOS Store作者回复是应该不上
https://t.me/c/1062811297/87544

**Comment by septs** [comment]
<img width="317" alt="CleanShot 2023-03-11 at 17 08 25@2x" src="https://user-images.githubusercontent.com/3842474/224475643-ac00a460-3168-4de5-ba71-1fa3841691e8.png">

**Comment by pengfeichencpf** [comment]
#19 的issue作者一直尚未回复，会更新长截图功能吗？

**Comment by stevenzhu25** [comment]
@pengfeichencpf 如果作者都没回复… 我们怎么会有官方答案

**Comment by pengfeichencpf** [comment]
好的 谢谢！
