### ISSUE TITLE
在使用动态指针的情况下，捕捉鼠标指针无效

### ISSUE THREAD

**Issue by yihao0628** [Snipaste/feedback#2538]
### 联系方式

1872942591@qq.com

### 发生了什么？

**问题出现**
我使用了一个动态鼠标指针，截图时按 ` 或者 ! 都无法显示鼠标指针

**问题定位**
将指针移动到文本上，指针形态变换为静态竖线，截图后正常捕捉到指针

**问题验证**
将鼠标指针换回默认的Windwos自带指针，正常截图也可以捕获指针位置

**反馈目的**
希望可以修复动态鼠标指针导致的问题

### 运行平台

Windows 桌面

### 软件版本

2.8.3-Beta

**Comment by liulex** [comment]
请提供动态指针资源。

**Comment by yihao0628** [comment]
好的，感谢 https://wwqa.lanzoum.com/iJMIn0qhv2eb

**Comment by yihao0628** [comment]
> 请提供动态指针资源。
好的，感谢
https://www.lanzoub.com/iJMIn0qhv2eb

**Comment by yihao0628** [comment]
> 请提供动态指针资源。

好的，感谢 https://www.lanzoub.com/iJMIn0qhv2eb

**Comment by liulex** [comment]
下个版本修复。
