### ISSUE TITLE
希望增加 不过滤图片HTML标签 的功能

### ISSUE THREAD

**Issue by BreakingBody** [Snipaste/feedback#2539]
### 功能描述

希望增加【不过滤图片HTML标签】的功能
这样就可以在
paste图片的同时
使用自定义的字体
![image](https://user-images.githubusercontent.com/113698333/224481984-1849a4dc-5137-498c-aba7-dc760a65e0b7.png)

**Comment by liulex** [comment]
不是特意过滤了图片，而是目前不支持 html 里的图片。
