### ISSUE TITLE
mac 截图添加文本 卡死

### ISSUE THREAD

**Issue by QuantYu** [Snipaste/feedback#2542]
### 联系方式

1102247022@qq.com

### 发生了什么？

仅截图功能正常，但是要在截图上添加文本的话，点完添加文本按钮，就一直在转圈，停在截图的页面，无法进行其他操作和强制关闭。只能重启电脑解决

### 运行平台

macOS

### 软件版本

v2.8.3 Beta2

**Comment by QuantYu** [comment]
发现问题了。。  卡住转圈的时候，tuch bar上显示了 “下载”“跳过”两个按钮，点击跳过就解决了

**Comment by septs** [comment]
建议证实该问题由 Snipaste 自身缺陷(bug)导致
