### ISSUE TITLE
截图及编辑时卡顿

### ISSUE THREAD

**Issue by zuiledege** [Snipaste/feedback#2543]
### 联系方式

1409890168@qq.com

### 发生了什么？

前提：使用罗技G604鼠标
操作：按下截图快捷键后，移动鼠标，指针移动正常，截图提示框跟不上鼠标，卡顿，编辑界面的箭头等同样跟不上鼠标指针，卡顿。电脑上同时插入两个鼠标，另一个G304无此问题。换成QQ或者微信截图，两个鼠标均无问题。
是不是snipaste的配置与这种自定义编程鼠标有冲突？

### 运行平台

微软商店, Windows 桌面

### 软件版本

2.8.4

**Comment by zuiledege** [comment]
切换成蓝牙连接模式时，无卡顿，用无线接收器就会卡顿。

**Comment by septs** [comment]
建议证实该问题由 Snipaste 自身缺陷(bug)导致

**Comment by 1572990942** [comment]
the same
