### ISSUE TITLE
色彩吸管功能

### ISSUE THREAD

**Issue by ThinkCodeStudio** [Snipaste/feedback#2545]
### 功能描述

像PS软件中的色彩吸管工具. 

我希望他它能在截取画面时在底部工具栏有个拾取颜色的工具, 他能点击截取画面的某一个像素点获得颜色编码(#FFAAFF)保存到我的剪切板中.
还有在按F3后对已经截取的画面右键也能使用相同的功能来拾取颜色, 这样我可以截取多个色块画面放在旁边来使用它们.

因为我会设计UI的一部分工作, 工作时找一些好看的UI配色截图吸取颜色的编码到我的UI中使用

**Comment by septs** [comment]
https://docs.snipaste.com/zh-cn/getting-started?id=%e5%8f%96%e8%89%b2

**Comment by slanterns** [comment]
![Snipaste_2023-03-15_16-22-30](https://user-images.githubusercontent.com/10987206/225249897-36baafee-c15b-4c8e-838e-88e0d6aafc5f.jpg)

第二个需求在F3贴图之后再F1对着贴图取色感觉就可以了
