### ISSUE TITLE
工具栏按钮特效问题

### ISSUE THREAD

**Issue by hikinsley** [Snipaste/feedback#2548]
### 发生了什么？

特效似乎不正确
情况如下：

![IMG_7563](https://user-images.githubusercontent.com/42203894/225562913-2c336c29-540e-4ec9-b4af-9b67a89b9d63.jpeg)

https://user-images.githubusercontent.com/42203894/225563528-34d1fd29-c575-47ab-843f-c8ad839523dc.MOV

### 运行平台

macOS

### 软件版本

2.8.3-Beta2(2022.12.25)

**Comment by liulex** [comment]
是哪里不正确？

**Comment by hikinsley** [comment]
![image](https://user-images.githubusercontent.com/42203894/226221798-ea6ca10f-4001-4caa-8cb7-721aaafe4584.png)
鼠标移动到工具栏的按钮上时，底部高亮有重叠，最左侧按钮与最右侧底部高亮也有区别

**Comment by liulex** [comment]
谢谢，下个版本会修复。

**Comment by hikinsley** [comment]
问题好像还存在
macOS版
![eliseot_2023-09-14_11-40-15](https://github.com/Snipaste/feedback/assets/42203894/d4e62ebc-a777-46f3-8fe5-fac78a9c96e2)

**Comment by liulex** [comment]
因为新版还没发布。

**Comment by hikinsley** [comment]
哈哈哈，明白了大佬

**Comment by liulex** [comment]
@hikinsley 你的意思是最左边图标的高亮不应该转弯吗？

**Comment by hikinsley** [comment]
是这样，因为中间都是横线，两边的有些特立独行。（我好像有点吹毛求疵
