### ISSUE TITLE
什么时候更新到Snipaste3版本？想买专业版但有点担心

### ISSUE THREAD

**Issue by hcllmsx** [Snipaste/feedback#2550]
### Problem Description

我怕我现在买了专业版，没几个版本就更新到3了，因为现在已经2.8几了。到时候怕又要重买....0.0

### Platform

Microsoft Store

### Version

2.8.4

**Comment by scorpion19961007** [comment]
为什么你会觉得下个版本的专业版需要另外买

**Comment by hcllmsx** [comment]
> 为什么你会觉得下个版本的专业版需要另外买

因为大版本更新要重新买啊！比如我今天买了2.8.4专业版，下个版本2.9，下下个版本马上就3.0了，那我岂不是刚买，就又要重新买才能享受更新？所以干脆等到3出来，这样总不至于3版本到4版本一下子就更新完吧？
为什么觉得要下个版本需要买？因为我要更新！我要更新！

**Comment by septs** [comment]
纵观 Snipaste 更新历史，迭代速度可能真的会使你失望

https://docs.snipaste.com/zh-cn/changelog

**Comment by liulex** [comment]
一年内不会出 Snipaste 3.

**Comment by w999w** [comment]
我现在想买，我也怕这个，感觉很快就要出3了
