### ISSUE TITLE
序号笔功能以及长截图或者滚动截图

### ISSUE THREAD

**Issue by Sangxudong** [Snipaste/feedback#2551]
### 功能描述

序号笔功能：现有的序号笔功能后增加带有文本框的输入区域，方便一次性说明序号笔这里说明了什么

**Comment by Geeyun-JY3** [comment]
Duplicate of https://github.com/Snipaste/feedback/issues/2525#issuecomment-1475098088

**Comment by Geeyun-JY3** [comment]
Duplicate of #19
