### ISSUE TITLE
Cannot find how to edit key bindings

### ISSUE THREAD

**Issue by Neykuratick** [Snipaste/feedback#2554]
### Problem Description

How do i change enter to quick save?

![image](https://user-images.githubusercontent.com/63598014/226835320-948b02b9-3bbe-4ed2-962b-0170b7c77039.png)

### Platform

Microsoft Store

### Version

2.8.4

**Comment by liulex** [comment]
Key bindings cannot be editted. Only global hotkeys can be customized.
