### ISSUE TITLE
箭头反向

### ISSUE THREAD

**Issue by lbyxiaolizi** [Snipaste/feedback#2558]
### 发生了什么？

箭头反向，是这么设计的还是bug？

https://user-images.githubusercontent.com/65098936/227707611-28a22c5f-7615-48c9-b82e-69674fdca1b3.mp4

### 运行平台

微软商店

### 软件版本

v2.8.4

**Comment by lbyxiaolizi** [comment]
https://user-images.githubusercontent.com/65098936/227707722-7503a00a-1a26-46b1-a756-539160526627.mov

**Comment by liulex** [comment]
![image](https://user-images.githubusercontent.com/2010459/227711080-45327b48-4106-49cf-a8cb-ed50d447a767.png)

**Comment by lbyxiaolizi** [comment]
感谢！
