### ISSUE TITLE
能否在标注中增加尺寸标注功能

### ISSUE THREAD

**Issue by sangfeeling** [Snipaste/feedback#256]
我是一个机械设计工程师，经常需要在概念设计阶段或客户解释阶段对意向图进行尺寸标注，所以希望能够增加这样一个功能，类似的功能有的软件能够实现，比如Markman（马克鳗）等，但是他们只能对保存好的图片进行尺寸标注编辑，不能在截图时直接进行尺寸标注，建议加入此功能，谢谢。
http://www.jianshu.com/p/83af310f5939
可以参考此网址上提到的一些软件，功能不用特别强大，简单点就好。如有打扰，请见谅。

**Comment by liulex** [comment]
恐怕 Snipaste 并不能替代专业的图片标注工具。
不过以后开放插件系统之后，也许会有人去写类似的插件。

**Comment by sangfeeling** [comment]
非常感谢回复，随时关注插件系统的开放。






在 2016-12-03 21:45:04，"Le Liu" <notifications@github.com> 写道：


恐怕 Snipaste 并不能替代专业的图片标注工具。
不过以后开放插件系统之后，也许会有人去写类似的插件。

**Comment by shuwn** [comment]
這個跟 #843 有類似的需求，建議可以合併處理

**Comment by septs** [comment]
> Snipaste 2.5 专业版已支持。

from #843

部分支持

**Comment by chenrylee** [comment]
> 能增加双向箭头吗？

双向箭头在2.5就支持了 #843
