### ISSUE TITLE
截图出来的图有黑边

### ISSUE THREAD

**Issue by lc123452000** [Snipaste/feedback#2561]
### 发生了什么？

Windows环境，这段时间截图出来的图片都有黑边，其他截图软件不会
截图效果：[https://vasvip-pub.wpscdn.cn/prod/Mobile/lc_test/wei_shen_tu_pian__20230328150218.png](url)

### 运行平台

Windows 桌面

### 软件版本

2.8.4 64位PRO

**Comment by septs** [comment]
请检查设置

Duplicate of https://github.com/Snipaste/feedback/issues/197#issuecomment-672933315

**Comment by lc123452000** [comment]
> 请检查设置
> 
> Duplicate of #197

请问「带边框输出图像」在哪里设置？找了很久没找到

**Comment by liulex** [comment]
![image](https://user-images.githubusercontent.com/2010459/228284430-bf15e654-eb65-4a07-bcbd-a05b2003d0fd.png)
