### ISSUE TITLE
如何查看自己的版本是微软商店版还是windows版？

### ISSUE THREAD

**Issue by vcmiaowu** [Snipaste/feedback#2564]
### 问题描述

如何查看自己的版本是微软商店版还是windows版？

### 运行平台

微软商店, Windows 桌面

### 软件版本

2.8.1 x64 PRO

**Comment by vcmiaowu** [comment]
查看版本的目的是，现在版本是64位的，有时会崩溃
帮助文档中建议改为32位，如果是微软商店版本如何改为32位软件？

**Comment by Geeyun-JY3** [comment]
目前只有商店版能激活 PRO

**Comment by Geeyun-JY3** [comment]
所以既然你有 PRO 那就是商店版。

另外现在最新版是 2.8.4，可以更新看看还会不会崩溃。
