### ISSUE TITLE
Edge浏览器 快捷功能

### ISSUE THREAD

**Issue by BellModena** [Snipaste/feedback#2567]
### 联系方式

137642435@qq.com

### 发生了什么？

在最新版本111.0.1661.62 (正式版本) 的Edge浏览器中新增了个F1快捷键，这个快捷键无法被删除。有什么方法可以绕过浏览器的快捷键嘛
![QQ截图20230331194641](https://user-images.githubusercontent.com/52617822/229111851-fcbbbbfb-6b01-494b-b473-4f0b9763b82c.png)

### 运行平台

微软商店

### 软件版本

2.8.4

**Comment by Geeyun-JY3** [comment]
开 Edge  试了下 Snipaste 能正常用啊。

Chrome 也一直能用 <kbd>F1</kbd> 调出类似的东西。

**Comment by Geeyun-JY3** [comment]
> 是今天下午更新的最新版本Edge嘛？ 为什么更新完后就不能用了😭

说版本号。
谁知道你今天下午更新了什么版本。

**Comment by BellModena** [comment]
我原文有附带版本号 &nbsp;我现在下班了看不到






------------------ 原始邮件 ------------------
发件人: Geeyun-JY3 ***@***.***&gt;
发送时间: 2023年3月31日 20:27
收件人: Snipaste/feedback ***@***.***&gt;
抄送: BellModena ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Snipaste/feedback] Edge浏览器 快捷功能 (Issue #2567)

**Comment by Geeyun-JY3** [comment]
抱歉我眼瞎了，确实有

**Comment by Geeyun-JY3** [comment]
我就是用和你同一个版本实测的。并无问题。

**Comment by BellModena** [comment]
？？？ 那我回家用家里电脑试一试 可能是bug


------------------ 原始邮件 ------------------
发件人: Geeyun-JY3 ***@***.***&gt;
发送时间: 2023年3月31日 20:33
收件人: Snipaste/feedback ***@***.***&gt;
抄送: BellModena ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Snipaste/feedback] Edge浏览器 快捷功能 (Issue #2567)

**Comment by septs** [comment]
Duplicate of #2110
