### ISSUE TITLE
Add icon options on the taskbar

### ISSUE THREAD

**Issue by iuwlsvh** [Snipaste/feedback#2568]
### Feature Description

Sometimes people are willing to just click with the mouse, hiding in the taskbar requires two clicks.

**Comment by Geeyun-JY3** [comment]
> hiding in the taskbar requires two clicks.

Do you mean Snipaste hidden in the notification area (tray) requires two clicks?

**Comment by iuwlsvh** [comment]
No, what I mean is: click on the notification area (tray) once, and then click on the application icon again, which adds up to two times. It is better to make the application icon appear in the taskbar with only one click. Overall, the software is great!

**Comment by stevenzhu25** [comment]
@iuwlsvh so… have you ever tried to drag snipaste from notification tray to your taskbar?

**Comment by iuwlsvh** [comment]
@stevenzhu25 Thank you for the reminder, it works.
