### ISSUE TITLE
Is that possible to add the name of image group to the naming rule?

### ISSUE THREAD

**Issue by 1qzhworld** [Snipaste/feedback#2570]
### 功能描述

可以把image group（图片分组）的内容作为Naming rule的方式吗？
我看到好多问题关于图片保存的，但是文件夹可以是随机名称，但是可以让文件在设置自动保存的时候使用文件分组的名字吗？
这样至少可以配合everything之类的以后找图片更方便一些。或者如果pro版本里面有这个naming rule的话我愿意充值一个！
目前的naming rule里面好像environment variables:没有image naming 相关的，只有%os%, %computername%, and %username%

**Comment by Geeyun-JY3** [comment]
Duplicate of #2325
