### ISSUE TITLE
复制编辑后的图片后，历史截图中只存在复制的初始图片

### ISSUE THREAD

**Issue by xingmumu** [Snipaste/feedback#2572]
### 联系方式

1006510808@qq.com

### 发生了什么？

1.截图
2.将图片贴在屏幕上————如果不把图片贴在屏幕上，而是直接编辑是可以找到历史记录的（刚刚发现，但之前的版本没有这个问题）
3.编辑图片，画矩形，添加文字
4.点击工具栏复制按钮
5.点击esc退出图片
6.","回退历史记录，发现没有保存编辑后的图片，只有初始图片

### 运行平台

macOS

### 软件版本

2.8.3-Beta2（2022.12.25）

**Comment by Geeyun-JY3** [comment]
这不是符合文档的描述么：https://docs.snipaste.com/zh-cn/getting-started?id=回放截图记录
> - 只有 `成功的截图` 才会出现在截图记录中

https://docs.snipaste.com/zh-cn/getting-started?id=何谓一次-成功的截图

**Comment by xingmumu** [comment]
但是，我把截图贴在桌面编辑以后，又点击过复制图片的，这样也是成功的截图哇

**Comment by Geeyun-JY3** [comment]
> 但是，我把截图贴在桌面编辑以后，又点击过复制图片的，这样也是成功的截图哇

所以你有没有认真看文档……什么算一次成功的截图文档不是写得很清楚吗：https://docs.snipaste.com/zh-cn/getting-started?id=何谓一次-成功的截图

> 何谓一次 `成功的截图`
> 
> - 保存到剪贴板
> - 保存到文件
> - 保存到贴图
> - 快捷保存

在你上述第 2 步「将图片贴在屏幕上」后就已经完成了一次**成功的截图**，历史记录中当然是在这一步完成后得到的截图。

**Comment by liulex** [comment]
> 把截图贴在桌面编辑以后

这就成为贴图了，不再算截图操作。
