### ISSUE TITLE
截屏捕获鼠标时鼠标颜色能否更改

### ISSUE THREAD

**Issue by lexiechen-pki** [Snipaste/feedback#2576]
### 问题描述

![image](https://user-images.githubusercontent.com/84299094/230303252-615efa9f-40d2-4aef-8387-7cc04dc08dd3.png)
浅色背景下截屏并显示鼠标时鼠标是黑色的，能否调整成白色？

### 运行平台

Windows 桌面

### 软件版本

2.8.1-beta-x64

**Comment by stevenzhu25** [comment]
@lexiechen-pki 有点懵… 如果你是浅色背景（现在白色），显示鼠标， 然后需要鼠标是白色的话，那不就相当于不显示鼠标了么…

**Comment by lexiechen-pki** [comment]
> @lexiechen-pki 有点懵… 如果你是浅色背景（现在白色），显示鼠标， 然后需要鼠标是白色的话，那不就相当于不显示鼠标了么…

就是需要显示原本鼠标的样子，正常白色鼠标是有黑色边框的~

**Comment by lexiechen-pki** [comment]
查阅更新日志发现已经有人提出相关问题并在2.8.2版本中修复了~感谢
