### ISSUE TITLE
增加新功能，放置“①”这种标记。

### ISSUE THREAD

**Issue by elincy** [Snipaste/feedback#2577]
### 功能描述

增加触发截图后，可以放置“①”这种标记，且可以编辑文字，删除一个标记后，自动排序。比如，①②③，删除②，③会变成②。

**Comment by sato94** [comment]
这不就是PRO版的功能吗，已经有了额

**Comment by elincy** [comment]
> 这不就是PRO版的功能吗，已经有了额

那可能我版本不对，我看看。

**Comment by chenrylee** [comment]
这个功能三年前就添加了： https://github.com/Snipaste/feedback/issues/227#issuecomment-628125908

**Comment by Geeyun-JY3** [comment]
Duplicate of #227
