### ISSUE TITLE
特殊的文字识别功能

### ISSUE THREAD

**Issue by HY-hy-cuber** [Snipaste/feedback#2578]
### 功能描述

我们利用F1选中目标区域，用F3截取选中区域并将其置于桌面最前。我想这时候可不可以设置一个快捷键或者设置一个选项开启一个功能就是可以选中置于前方的图片的部分区域文字，然后复制（就微信现在有这个功能，可以复制图片上的文字）

**Comment by septs** [comment]
Duplicate of #188
