### ISSUE TITLE
win10系统f1键被占用

### ISSUE THREAD

**Issue by wwwwugencom** [Snipaste/feedback#2581]
### 问题描述

win10系统，之前一直使用f1键截图，今天f1突然变成了window自带的睡眠功能，重装snipaste无效，请教怎么修改？

### 运行平台

Windows 桌面

### 软件版本

Snipaste-2.8.3-Beta-x64

**Comment by scorpion19961007** [comment]
这东西你百度一下改快捷键就行了，称得着在这问，，主要不一定能及时得到回复

**Comment by wwwwugencom** [comment]
> 这东西你百度一下改快捷键就行了，称得着在这问，，主要不一定能及时得到回复

百度了确实没有解决，请问您有好的方法吗？

**Comment by scorpion19961007** [comment]
同时按住fn+esc,可以关闭按F1直接进入休眠。先试试

**Comment by wwwwugencom** [comment]
> 
好了好了，谢谢您
