### ISSUE TITLE
标注截图时，希望支持自动编号

### ISSUE THREAD

**Issue by kelegele** [Snipaste/feedback#2583]
在标注截图的时候，文本输入单纯就只能输入文本，希望可以支持自动编号文本，参考 QQ 截图
如下图可自动编号每次输入的文本序号，用于引导步骤很有意义

![image](https://user-images.githubusercontent.com/29626372/231919422-718128bc-e12a-467d-967a-71b849e91c58.png)

**Comment by chenrylee** [comment]
自动编号的功能在三年前就加入了，如有需要请购买专业版，详情请参考官方网站的文档。

**Comment by Geeyun-JY3** [comment]
Duplicate of https://github.com/Snipaste/feedback/issues/2525#issuecomment-1475098088
