### ISSUE TITLE
文本ocr功能实现？

### ISSUE THREAD

**Issue by Moon-xm** [Snipaste/feedback#2587]
### 功能描述

希望可以实现文本识别功能，目前使用的截图软件有QQ截图和snipaste的专业版，虽然一直想舍弃QQ截图全面转用snipaste，但文本识别功能太常用了，使用QQ截图的唯一功能就是文本识别，中英识别就已经包括了绝大多数的使用场景。

**Comment by Geeyun-JY3** [comment]
Duplicate of #188

**Comment by HongweiLee233** [comment]
我也希望加入简单的文字ocr,就算是付费的也可以
