### ISSUE TITLE
希望增加截图后进行防ocr处理的功能

### ISSUE THREAD

**Issue by gungnirayu** [Snipaste/feedback#2592]
### 功能描述

自从wx增加图片自动ocr功能之后，突然想到……现在不仅是通讯工具，很多社交媒体都会对图片ocr审核，希望能增加截图后进行防ocr处理的功能

**Comment by septs** [comment]
从技术上来说对抗 OCR 是很困难的，可以通过了解 [验证码的发展史](https://finance.sina.com.cn/tech/2021-04-07/doc-ikmyaawa5056011.shtml) 来理解

以及这触及到了国内合规经营的问题，我觉得很难

**Comment by Dirreke** [comment]
以目前的技术，这几乎是不可能的，OCR-GAN目前应该做不到

**Comment by gungnirayu** [comment]
是的，我最近也试了试屈指可数的几个开源产品，无非就是文字旋转，缩小字间距，添加噪点和画线，不过wx这个ocr还真的挺强，要想达到一定的效果，对阅读就会产生比较大的影响了

**Comment by septs** [comment]
在不影响阅读的前提无技术可行性
