### ISSUE TITLE
功能建议：添加程序黑名单

### ISSUE THREAD

**Issue by ZhangPF2000** [Snipaste/feedback#2596]
### 功能描述

软件默认的快捷键十分的好用，但是当我打游戏，像是dota2的时候，有时候会用到F1和F3，这个时候会导致出现截图或者贴图，无法操作，通常来说我也不怎么会在游戏内截图，如果可以的话，可以添加一个黑名单机制，当某程序在黑名单，且我正在操作该程序时，禁止使用Snipaste的快捷键。

**Comment by Geeyun-JY3** [comment]
需要 Pro：https://docs.snipaste.com/zh-cn/pro?id=b-更自由的定制化
