### ISSUE TITLE
任务计划命令截屏出现黑色图片

### ISSUE THREAD

**Issue by addstone** [Snipaste/feedback#2598]
@Snipaste 我的情况是使用Windows自带的定时任务截屏 有30%概率出现黑屏，双屏幕.命令如下 snip --delay 1.5 --full -o quick-save  windows11最新版 

**联系方式**
No response

**发生了什么？**
我的动作
使用自带任务计划程序执行命令 snip --delay 1.5 --full -o quick-save ，每10分钟执行一次
从三月份开始到现在，我的电脑每天关机。很平均，几乎都是每8张截图有内容，然后后面的8章就黑屏
造成结果
平均每8张图片后就会截屏8章黑色背景大小2.36KB的图片
推测
看别的issues说是双屏显示器造成的，不知道是不是这个原因

系统版本 
Windows 11 企业版
22H2
Windows Feature Experience Pack 1000.22641.1000.0

**运行平台**
微软商店

**软件版本**
2.8.4 PRO

**Comment by addstone** [comment]
"C:\Program Files\WindowsApps\45479liulios.17062D84F7C46_2.8.400.0_x64__p7pnf6hceqser\snipaste.exe" snip --delay 1.5 --full -o quick-save
经我测试手动在cmd执行上述命令30此，也是前8张有内容，后8章是黑图。可以确定这是程序缺陷了。

**Comment by liulex** [comment]
无法复现。。

**Comment by addstone** [comment]
日志我已经发送到 snipaste.app@gmail.com 这个邮箱了

**Comment by addstone** [comment]
我的台式机与笔记本都出现了这个问题，你需要什么资料我发给你。我是6年Java后端开发者

**Comment by liulex** [comment]
@addstone 你先切换到 Guest 账户，看能否重现？

**Comment by addstone** [comment]
@liulex  在Windows11上已经不提供Guest 账户了，我新建了用户并设置管理员权限。再次执行任务计划。奇怪的事情发生了，只截图8张后就不会截图了，重启Snipaste 也无效，必须要重启电脑才能再次截图。以上问题都是出现在命令行或者任务计划里执行命令的问题，手动点击Snipaste图标或者使用快捷键都是正常的。

**Comment by addstone** [comment]
这个问题，有跟进吗

**Comment by addstone** [comment]
今天来上看，这个问题在2023年11月份就不再出现了。不知道是我重装系统的原因，还是这个问题修复了。
