### ISSUE TITLE
截图时通过键盘选择截图区域

### ISSUE THREAD

**Issue by czffour** [Snipaste/feedback#2601]
### 功能描述

在截图状态下可以通过WASD 移动光标，但现在想在通过键盘快捷键选择截图区域。(既用键盘完成鼠标左键选择截图区域的功能)
大致流程是
1. 通过WASD移动光标到点A
2. 按快捷键1
3. 通过WASD移动光标点B
4. 按快捷键2
出现截屏区域。
这个功能可以做吗？

**Comment by Geeyun-JY3** [comment]
与 #1252 第 4 点类似

**Comment by liulex** [comment]
无计划。
