### ISSUE TITLE
Windows 11无法正常运行

### ISSUE THREAD

**Issue by ykong1337** [Snipaste/feedback#2605]
### 问题描述

![image](https://user-images.githubusercontent.com/66518156/236967448-0bb7963d-eaec-4900-ba6a-ac6f466e86d8.png)
来自Scoop的Extras桶
```
scoop bucket add extras
scoop install snipaste
```
在Windows 11 家庭中文版 22H2下无法正常运行
![image](https://user-images.githubusercontent.com/66518156/236967580-38630db5-d588-46d2-9d08-636c0d7aefb4.png)
无托盘图标，无任何提示，正常显示在进程中，10几秒后自动结束

### 运行平台

Windows 桌面

### 软件版本

1.16.2

**Comment by Geeyun-JY3** [comment]
Duplicate of #2232

**Comment by elecfrog** [comment]
scoop下载v2.8.5-Beta (2023.05.08)版可以打开。 v1.16.2 (2018.01.22) 无法打开
