### ISSUE TITLE
使用 F3 粘贴文字时无法拖曳

### ISSUE THREAD

**Issue by likkai** [Snipaste/feedback#2606]
正常情况下：
拷贝文字后使用 F3 粘贴会产生一个可拖曳的白块，双击白块后会消失，白块也可拖曳。

然而在该网站下拷贝代码后使用 F3 则会造成一下情况：
所拷贝的文字依旧显示，然而背景是透明的。这种情况下白块（此时为透明背景）无法拖曳（大部分情况下），也无法双击消失。唯一使它消失的方法则是双击白块四周的格子（如影片中显示）

网站为 https://askubuntu.com/questions/262598/e-unable-to-locate-package-repo
影片在 https://1drv.ms/v/s!AjlVdnwJiU-2hI8e_yTMa6qg3LiWWA?e=UyziFi

**Comment by Geeyun-JY3** [comment]
贴图背景模式的问题，你视频里拖得动的时候就是点到了不透明部分：
https://docs.snipaste.com/zh-cn/pro?id=贴图相关

> 四种背景模式：
> 
> - 透明：贴图中透明背景完全不绘制，鼠标无法点击透明部分
> - 伪透明：透明背景依旧透明，但鼠标可以点击透明部分，方便移动贴图
