### ISSUE TITLE
希望恢复在截图区域滑动滚轮调节选框和箭头粗细

### ISSUE THREAD

**Issue by yuyao777** [Snipaste/feedback#2607]
### 问题描述

较早的版本就说这么操作的，后来改成在左下角滑动滚轮才改变粗细感觉不是很友好，希望恢复

### 运行平台

Windows 桌面

### 软件版本

2.85

**Comment by Geeyun-JY3** [comment]
你说的「在左下角滑动滚轮」是指在工具栏相应区域滚动？
实测 2.8.5 在编辑模式下在任意区域滚动滚轮仍能改变粗细，一切如故。

**Comment by yuyao777** [comment]
| |
yyawen2022
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年5月13日 12:01 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [Snipaste/feedback] 希望恢复在截图区域滑动滚轮调节选框和箭头粗细 (Issue #2607) |

你说的「在左下角滑动滚轮」是指在工具栏相应区域滚动？
实测 2.8.5 在编辑模式下在任意区域滚动滚轮仍能改变粗细，一切如故。

**Comment by Geeyun-JY3** [comment]
GitHub 这边目前根本看不到你邮件回复了啥，建议来 GitHub 这里回复。

**Comment by yuyao777** [comment]
![23DE30DB-440A-48AC-98CE-A4C3DC672868](https://github.com/Snipaste/feedback/assets/133181927/db998a10-80fa-4ab5-a56d-6795e0c707ab)

**Comment by Geeyun-JY3** [comment]
对啊我的意思就是我这边实测是没这个问题的，截图区域内一直都可以使用滚轮调节粗细。

建议排查是否有冲突软件。

**Comment by yuyao777** [comment]
这还能冲突？我也不知道怎么排查啊

**Comment by Geeyun-JY3** [comment]
你是不是在首选项里勾选了「截屏 > 按键」下的「禁用鼠标滚轮功能」？
![image](https://github.com/Snipaste/feedback/assets/49396421/55042694-bce0-4d79-80d5-c4c3f2786fa0)

**Comment by yuyao777** [comment]
确实，这个被勾选了，是你软件安装据默认禁用的吧？

**Comment by stevenzhu25** [comment]
我的默认安装的就没有勾选这个…… @yuyao777

**Comment by Geeyun-JY3** [comment]
我不知道，我不是开发者。

**Comment by yuyao777** [comment]
@Geeyun-JY3 我还以为你是开发者，感谢你的帮助
