### ISSUE TITLE
浏览器页面出现截图颜色发白的问题

### ISSUE THREAD

**Issue by E-17** [Snipaste/feedback#2608]
### 发生了什么？

![image](https://github.com/Snipaste/feedback/assets/48985448/cf345d9a-e046-42fc-ab84-e2d17c2e5d49)
![image](https://github.com/Snipaste/feedback/assets/48985448/642050d6-50da-4ed8-ac9c-aeac437177c9)

### 运行平台

微软商店

### 软件版本

2.8.5

**Comment by Geeyun-JY3** [comment]
HDR：#1112？

**Comment by E-17** [comment]
> 

的确开了 HDR，我回去试一下，提及的解决办法

**Comment by Geeyun-JY3** [comment]
Duplicate of #1112
