### ISSUE TITLE
我作为个人在公司使用这个软件，这是可以的吗？

### ISSUE THREAD

**Issue by df257** [Snipaste/feedback#2612]
### Problem Description

如果不可以的话，在哪里可以下载1.x版本的

### Platform

Microsoft Store, Windows Desktop

### Version

2.x

**Comment by stevenzhu25** [comment]
@df257 不可以。
1.x版本可以在 snipaste.com 下载

**Comment by df257** [comment]
> @df257不可以。 1.x版本可以在snipaste.com 下载
1.x是可以的对吧？
可以给个链接吗？我找不到1.x的链接地址

**Comment by df257** [comment]
1.x版本是可以使用的对吧？

**Comment by df257** [comment]
![image](https://github.com/Snipaste/feedback/assets/7835444/b6034e2a-095f-4b86-abdb-c088cdfaadd9)
这个1.6的64位版本，下载后在win10上没法运行😂

**Comment by stevenzhu25** [comment]
> 1.x版本是可以使用的对吧？

是的
> Snipaste 2.x 只对个人用户免费，公司使用请购买专业版或使用 Snipaste 1.x
> Snipaste 1.x 版将停留在 1.16.2，不再更新
https://docs.snipaste.com/zh-cn/pro

链接就是你下载的那个……
如果无法运行， 是否有报错信息之类的？ （另外你可能需要考虑先把Snipaste v2或者其他的从托盘区退出再打开）

**Comment by df257** [comment]
>86位的可以

**Comment by jonyt99** [comment]
是否可以在截图后自动在右下角或者左下角添加前期日期
![image](https://github.com/Snipaste/feedback/assets/32587118/3dc5c35e-d932-4098-ab8d-cd0da97df5ea)

**Comment by stevenzhu25** [comment]
> >86位的可以，但我电脑是64位的

如果有错误报告麻烦发一下， 
我自己的几个猜测：
1. 你电脑是32位（即使CPU支持64位）
2. 你少了某些依赖项

**Comment by df257** [comment]
> > > 86位的可以，但我电脑是64位的
> 
> 如果有错误报告麻烦发一下， 我自己的几个猜测：
> 
> 1. 你电脑是32位（即使CPU支持64位）
> 2. 你少了某些依赖项

没有错误报告，就是双击后没反应
![image](https://github.com/Snipaste/feedback/assets/7835444/e250280d-bc71-47d2-b627-2479a87eeec7)
