### ISSUE TITLE
软件运行不了

### ISSUE THREAD

**Issue by yang814** [Snipaste/feedback#2616]
### Problem Description

环境：win11 22H2 x64
双击运行后图标在托盘闪一下消失。
软件32，64，微软商店都不行，也有弹出，快捷键注册失败。

### Platform

Windows Desktop

### Version

v1.16.2

**Comment by stevenzhu25** [comment]
@yang814 Event Viewer里面可以查到错误/崩溃日志吗？ 如果有的话请提供一下

**Comment by Geeyun-JY3** [comment]
https://docs.snipaste.com/zh-cn/pro?id=专业版
> Snipaste 1.x 版将停留在 1.16.2，不再更新

之前也有过不少 1.x 版本在 Windows 11 上没法用的 issue：#2174、#2232、#2400、#2605

**Comment by Geeyun-JY3** [comment]
？所以商店最新版行不行？商店版可不是 v1.16.2

**Comment by yang814** [comment]
之前用的是zip版，可能是系统问题，更新功能.NET Framework 3.5和4.8.1，重启后微软商店可以正常运行，zip版还是不行。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月19日(周五) 晚上10:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Snipaste/feedback] 软件运行不了 (Issue #2616)




 
？所以商店最新版行不行？商店版可不是 v1.16.2

**Comment by yang814** [comment]
感谢解答！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月19日(周五) 晚上10:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Snipaste/feedback] 软件运行不了 (Issue #2616)




 
https://docs.snipaste.com/zh-cn/pro?id=专业版
  
Snipaste 1.x 版将停留在 1.16.2，不再更新
  
之前也有过不少 1.x 版本在 Windows 11 上没法用的 issue：#2174、#2232、#2400、#2605

**Comment by yang814** [comment]
我在更新功能.NET Framework 3.5和4.8.1，微软商店的可以正常运行了，下载的zip版还是不行。
Event Viewer提供不了，卡在了查找事件（不知道是不是系统问题）

---原始邮件---
发件人: "Steven ***@***.***&gt;
发送时间: 2023年5月19日(周五) 晚上9:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Snipaste/feedback] 软件运行不了 (Issue #2616)




 
@yang814 Event Viewer里面可以查到错误/崩溃日志吗？ 如果有的话请提供一下

**Comment by Geeyun-JY3** [comment]
你所说的 zip 版是 v1 还是 v2？

**Comment by yang814** [comment]
v1，v2都有试过，v1没有反应，v2提示快捷键注册失败



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月20日(周六) 上午10:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Snipaste/feedback] 软件运行不了 (Issue #2616)




 
你所说的 zip 版是 v1 还是 v2？

**Comment by Geeyun-JY3** [comment]
> v2提示快捷键注册失败

https://github.com/Snipaste/feedback/issues/2110#issuecomment-1059689693

**Comment by juanyilxc** [comment]
环境: win 10 22H2    
使用Snipaste-1.16.2-x64 、Snipaste-1.15.3-x64点击没反应
使用Snipaste-1.16.2-x86 正常

查看日志
```
错误应用程序名称: Snipaste.exe，版本: 1.16.2.0，时间戳: 0x5a64bd08
错误模块名称: LIBEAY32.dll，版本: 1.0.2.8，时间戳: 0x57294976
异常代码: 0xc0000005
错误偏移量: 0x0000000000003763
错误进程 ID: 0x33ac
错误应用程序启动时间: 0x01da3487c7a14d93
错误应用程序路径: D:\Program Files\Snipaste-1.16.2-x64\Snipaste.exe
错误模块路径: D:\Program Files\Snipaste-1.16.2-x64\LIBEAY32.dll
报告 ID: 9c493e17-8da1-481b-ae59-42970897b088
错误程序包全名: 
错误程序包相对应用程序 ID: 
```
得知是LIBEAY32.dll 文件导致，比对SHA1，结果如下       
||SHA1|
|-|-|
|1.16.2-x86 LIBEAY32.dll |080f021380ccd640612f82303fd995fb07d12906|
|1.16.2-x64 LIBEAY32.dll|6f6678a24f1c1b8250c40adfa92a4bd874602498|

尝试将x86中的LIBEAY32.dll，复制到x64，打开x64 正常     
具体为什么LIBEAY32.dll会导致异常，能力有限，没有做进一步的分析


[日志细节](https://github.com/Snipaste/feedback/files/13748483/Snipaste.Application.Error.zip)
