### ISSUE TITLE
Mac版本一直以来都有个bug 设置的所有配置，在重启电脑后会丢失，且快捷键会失效

### ISSUE THREAD

**Issue by ZhsKevin** [Snipaste/feedback#2617]
### 联系方式

260133172@qq.com

### 发生了什么？

个人使用了两年多了 Mac版本使用一年左右 一直以来都有个bug 设置的所有配置，在重启电脑后会丢失，且快捷键会失效。每次重启都需要命令行执行“open ~/.snipaste” 然后手动修改config.ini里的hide_tray_icon=true 改成false，这样就能展示出来菜单栏图标，然后右键首选项 重新设置快捷键等 
这样真的太麻烦了 我windows就没有这个问题 
希望作者能尽快修复下 非常影响mac用户体验

<img width="1121" alt="image" src="https://github.com/Snipaste/feedback/assets/73825126/bc9b848f-571a-444e-8b4e-5d1d69da5f62">

<img width="97" alt="image" src="https://github.com/Snipaste/feedback/assets/73825126/6e7815e8-124b-4723-b77a-a738928286f7">

### 运行平台

macOS

### 软件版本

2.x

**Comment by liulex** [comment]
> Mac版本一直以来都有个bug 

属实的话，反馈问题的肯定不会只有你一个。会不会是你自己某一次修改后导致 config.ini 的读写权限有问题呢？
