### ISSUE TITLE
Snipaste总是复制图片到剪贴板，怎么关闭？

### ISSUE THREAD

**Issue by NONONO1V** [Snipaste/feedback#2619]
### 问题描述

如题
![Snipaste_2023-05-22_20-39-41](https://github.com/Snipaste/feedback/assets/109849776/c733d187-badd-4e1b-b84b-c63af752abb2)

### 运行平台

微软商店

### 软件版本

2.8.5

**Comment by Geeyun-JY3** [comment]
emmmm 这个快捷键只是开始截图的快捷键，最后的输出方式是你自己选的啊，并不总是复制图片到剪贴板的：
![image](https://github.com/Snipaste/feedback/assets/49396421/f405535c-b447-4ebe-bf8f-6de896fcedba)
你可以用命令行参数自定义你想要的输出结果，再将命令行参数与全局快捷键绑定，不过这需要专业版：https://docs.snipaste.com/zh-cn/pro?id=b-%e6%9b%b4%e8%87%aa%e7%94%b1%e7%9a%84%e5%ae%9a%e5%88%b6%e5%8c%96
