### ISSUE TITLE
是否能增加截图后添加序号功能

### ISSUE THREAD

**Issue by Hyton411** [Snipaste/feedback#2623]
### 功能描述

是否能增加类似QQ截图工具里的添加①②....等序号的功能

**Comment by scorpion19961007** [comment]
@Hyton411 序号功能不是一直都有吗

**Comment by scorpion19961007** [comment]
![image](https://github.com/Snipaste/feedback/assets/62248110/354206fc-d552-49b5-9661-65f704c0e925)

**Comment by Hyton411** [comment]
没有这个功能。我用的是免费版，是专业版才有的吧？

**Comment by Geeyun-JY3** [comment]
> 没有这个功能。我用的是免费版，是专业版才有的吧？

所以请善用搜索：#227
认真阅读文档：https://docs.snipaste.com/zh-cn/pro?id=snipaste-2-专业版免费版-对比

另外这功能和 QQ 的序号笔不完全相同：https://github.com/Snipaste/feedback/issues/2525#issuecomment-1475098088

**Comment by Geeyun-JY3** [comment]
Duplicate of #227
