### ISSUE TITLE
Edit with Snipaste

### ISSUE THREAD

**Issue by xeuyuuyuex** [Snipaste/feedback#2628]
### 功能描述

Snipaste 的标注功能非常实用，有时候想对已有的图片进行标注，又不希望对他重新截图一次，因为这样有时候会变得模糊。
希望增加：右键已有的本地图片，可以选择 “Edit with Snipaste”，对它再次标注。

**Comment by Geeyun-JY3** [comment]
目前你想用 Snipaste 标注本地图片可以先复制该本地图片，然后将其贴出来。

另外请善用搜索：#16

**Comment by Geeyun-JY3** [comment]
Duplicate of #16
