### ISSUE TITLE
贴出新贴图以后会把工具条设置恢复到默认。恳请新增设置”新贴图保存上一次使用的工具设置“

### ISSUE THREAD

**Issue by 01Vanadium** [Snipaste/feedback#2631]
### 联系方式

1512137980@qq.com

### 发生了什么？

比如我习惯把画笔最小号调到2，贴出新贴图还是会恢复到3

### 运行平台

微软商店

### 软件版本

2.8.5

**Comment by liulex** [comment]
贴图继承的是截图的工具设置，你在截图时调整工具条即可。
