### ISSUE TITLE
识别率优化和迫切添加的功能 Recognition rate optimization and urgently added features

### ISSUE THREAD

**Issue by wenaqh2007** [Snipaste/feedback#2634]
### 功能描述

1、希望添加类似 iShot 的截图OCR功能；
2、希望可截图后出图为，类似 ishot 的圆角；
3、优化活动窗口截图识别率，类微信识别率；
4、专业版添加OCR识别和翻译的API接口功能；
5、希望专业版加入滚动截图，参考picpick和FastStone Capture。

1、Want to add the screenshot OCR function similar to iShot;
2、I hope that the screenshot can be taken after the picture for, similar to ishot's rounded corners;
3、Optimize the recognition rate of screenshots of active windows, similar to the recognition rate of WeChat;
4、Professional version to add OCR recognition and translation API interface function;
5, hope that the professional version to join the scrolling screenshot, reference picpick and FastStone Capture.

**Comment by Geeyun-JY3** [comment]
请善用搜索：
1. #188
2. #1510 
4. #188
5. #19

**Comment by wenaqh2007** [comment]
我不是专业开发者，只能通过类似软件的功能去提供思路建议。

关于OCR和翻译功能，微信这种是调用自己的，国外的截图软件OCR和翻译我不清楚，

这里有一个天若的OCR的实现方式，是否有参考价值
https://ocr.tianruo.net/server/interface.php

***@***.***
***@***.***




从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年6月9日 11:07
收件人: ***@***.***>
抄送: Qianjin ***@***.***>; ***@***.***>
主题: Re: [Snipaste/feedback] 识别率优化和迫切添加的功能 Recognition rate optimization and urgently added features (Issue #2634)


请善用搜索：

  1.  #188<https://github.com/Snipaste/feedback/issues/188>
  2.  #1510<https://github.com/Snipaste/feedback/issues/1510>
  3.  #188<https://github.com/Snipaste/feedback/issues/188>
  4.  #19<https://github.com/Snipaste/feedback/issues/19>

―

**Comment by scorpion19961007** [comment]
@wenaqh2007

**Comment by scorpion19961007** [comment]
@wenaqh2007 那你直接使用天若ocr就好了，我就是用的snipaste和天若ocr，2.0的天若更好用了

**Comment by wenaqh2007** [comment]
> @wenaqh2007 那你直接使用天若ocr就好了，我就是用的snipaste和天若ocr，2.0的天若更好用了 ![image](https://user-images.githubusercontent.com/62248110/244583670-ae70a110-623f-4580-bce7-1a1481748945.png)

现在基本上是微信的截图比较简单偶尔用用，基本在用快捷键的snipaste（在mac的iShot），但是微信这俩都没有滚动截图，所有用picpick（picpick主要编辑功能强，偶尔进行大截图的拼接、截图标注），OCR和翻译，基本web页面就是edge之前是谷歌，文档和截图的内容就是ABBYY FineReader（某丁一搞现在不行了）， 现在复制的内容或者文档用 deepL，现在微信截图自带了OCR和翻译倒是也偶尔省点功夫。
天若之前一直没用，现在配置不少API尝试了下

**Comment by wenaqh2007** [comment]
就在刚刚DeepL更新了 截屏OCR翻译和划词翻译功能

**Comment by scorpion19961007** [comment]
ocr用天若，普通截图用snipaste，长截图的话就调用qq吧。qq基本全天都在，这样等于只需要额外开两个软件就好。你现在等于额外多开四个软件

Qianjin Liu ***@***.***> 于2023年6月9日周五 13:12写道：
