### ISSUE TITLE
使用截图功能后，在屏幕中间出现透明的方框

### ISSUE THREAD

**Issue by Qiang-Yun** [Snipaste/feedback#2637]
### 发生了什么？

![image](https://github.com/Snipaste/feedback/assets/58579104/da9d57ee-7f00-4167-b44d-2cd04c689298)
如图所示，出现透明的框，当我使用隐藏所有贴图后会消失，但是又进行截图并贴图后再次出现

### 运行平台

Windows 桌面

### 软件版本

2.7.3（2022.01.30）

**Comment by HK-9956** [comment]
我也遇到了同样的问题

**Comment by Qiang-Yun** [comment]
收到了O(∩_∩)O~

**Comment by Geeyun-JY3** [comment]
双击边框试试？：https://github.com/Snipaste/feedback/issues/2125#issuecomment-1059689382

**Comment by Qiang-Yun** [comment]
双击边框问题解决了
