### ISSUE TITLE
線段與箭頭被合併了

### ISSUE THREAD

**Issue by apxchangli** [Snipaste/feedback#2638]
### 发生了什么？

原來版本，線段與箭頭分別是兩個選項。可以快速完成劃線與箭頭標示，現在需要額外一步驟進行選擇才能完成畫線與箭頭。可以改回以前版本的選單樣式嗎？

### 运行平台

macOS

### 软件版本

2.8.5-Beta

**Comment by Geeyun-JY3** [comment]
Duplicate of #2113
