### ISSUE TITLE
深色背景浅色字体 (例如-黑底白字) 场景下, 使用记号笔 (黄色) 框选内容时边界不易分辨的问题

### ISSUE THREAD

**Issue by Pluto0615** [Snipaste/feedback#2640]
### 问题描述

您好, 

在经常使用软件是发现的一个不太方便的情况. 能否劳烦各位看看, 是否可以考虑一下解决方案呢?

在 深色背景 浅色字体 (相信很多场景, 尤其是coding的, 都有黑底白字的界面搭配) 时候, 不论对截图或是贴图做编辑 使用记号笔的时候, 在框选想要高亮内容时, 黄色的边界和白色的字体比较难分辨出来. 
如下视频所示:
https://github.com/Snipaste/feedback/assets/117872625/f6b47f75-6867-49d2-a855-b93588e66c2a

其实不仅是 黄色记号笔用在黑底白字上面, 其他颜色记号笔在一些 其他色的背景+内容 也会出现类似的问题.
还挺难分辨实际高亮到哪行哪列了. 比较难控制要高亮的内容范围, 在这些特定颜色搭配的场景下.
![image](https://github.com/Snipaste/feedback/assets/117872625/5380f211-73ff-4064-b622-f372cb908a67)

我试了几款其他软件, 发现下面这个解决办法比较好:
在使用记号笔(有叫荧光笔/高亮等等...)时候, 先只显示要高亮内容的框/边界, 选好后自动上已选好的高亮色.
如下视频所示:
https://github.com/Snipaste/feedback/assets/117872625/3fc4c8a6-773c-404d-a46c-006d8e49fff5

感觉这样对任何颜色搭配场景都比较适用.

我还没有使用专业版, 不知道专业版里面是否有不一样.
如没有, 可以考虑一下所说的这个办法 (点开看大图).
![image](https://github.com/Snipaste/feedback/assets/117872625/166ce7c4-5795-4456-96d9-5d2b89d05554)

多谢各位.

### 运行平台

Windows 桌面

### 软件版本

2.8.5-Beta (2023.05.08)

**Comment by liulex** [comment]
像这样呢？
![highlight_with_border](https://github.com/Snipaste/feedback/assets/2010459/aa791184-67d3-416d-a5f3-f1c27f4b0769)

**Comment by Pluto0615** [comment]
> 像这样呢？ ![highlight_with_border](https://user-images.githubusercontent.com/2010459/258556355-aa791184-67d3-416d-a5f3-f1c27f4b0769.gif)

对对对, 就是类似这种...只要能比较清晰对比地框出来要高亮的部分 知道边界在哪就可以了....
你这个是新版版吗?还是专业版? 还是?
多谢啦.

**Comment by liulex** [comment]
反色的。等下个版本，不需要专业版。
