### ISSUE TITLE
运行LOL英雄联盟软件时，使用快捷键进行截屏无响应

### ISSUE THREAD

**Issue by zhajiang** [Snipaste/feedback#2651]
### 问题描述

使用环境：
windows版本 ：win10 22H2    

使用问题：
运行LOL游戏之后按下snipaste快捷键无响应，尝试了切换全屏和无边框窗口都无响应，只有窗口化状态下才可以有响应

### 运行平台

微软商店, Windows 桌面

### 软件版本

2.8.5

**Comment by septs** [comment]
> 无计划。请使用游戏自带的截屏功能。

see https://github.com/liulex/Snipaste-Feedback/issues/282#issuecomment-268239624
