### ISSUE TITLE
某次的截屏灰框一直停留在屏幕上无法消除

### ISSUE THREAD

**Issue by HK-9956** [Snipaste/feedback#2656]
### 联系方式

778501189@qq.com

### 发生了什么？

![image](https://github.com/Snipaste/feedback/assets/73985961/0905e670-22b4-4d8e-a67d-017b3a2b1f91)
在一次截屏贴图后，用于标识这个截图范围的灰框一直停留在屏幕上，且重启snipaste和重启主机后也无法消除。但关闭snipaste，或是选择隐藏所有贴图功能后，灰框可以暂时隐藏。

### 运行平台

微软商店

### 软件版本

v2.8.5

**Comment by HK-9956** [comment]
灰框底色是透明的，不影响查看灰框背后的屏幕内容

**Comment by Geeyun-JY3** [comment]
Duplicate of #2637
