### ISSUE TITLE
无论是64位还是32位使用一段时间后会退出，勾选了管理员启动和自启动

### ISSUE THREAD

**Issue by z147147216** [Snipaste/feedback#2658]
### 问题描述

无论是64位还是32位使用一段时间后会退出，勾选了管理员启动和自启动，退出没有任何提示。使用这款软件已经一两年了，都没出现这种问题。

### 运行平台

Windows 桌面

### 软件版本

1.16.2

**Comment by Geeyun-JY3** [comment]
Windows 版本是多少啊，有过 v1 在 Windows 11 上不能用的反馈
另外再提醒一下：https://docs.snipaste.com/zh-cn/pro
> Snipaste 1.x 版将停留在 1.16.2，不再更新

**Comment by z147147216** [comment]
> Windows 版本是多少啊，有过 v1 在 Windows 11 上不能用的反馈：#2232 另外再提醒一下：https://docs.snipaste.com/zh-cn/pro
> 
> > Snipaste 1.x 版将停留在 1.16.2，不再更新

版本22H2  操作系统版本22621.1992

**Comment by Geeyun-JY3** [comment]
> 版本22H2  操作系统版本22621.1992

Windows 11 是吧，那用不了也没办法了，毕竟：https://docs.snipaste.com/zh-cn/pro
> Snipaste 1.x 版将停留在 1.16.2，不再更新

**Comment by Geeyun-JY3** [comment]
Duplicate of #2232
