### ISSUE TITLE
当我复制了一个3位到5位的数字, 按F3贴图却贴了一个取色值的图

### ISSUE THREAD

**Issue by duguerdan** [Snipaste/feedback#2659]
### 联系方式

1312970787@qq.com

### 发生了什么？

复制一个3位到5为的数字比如3424, 然后按F3贴图, 贴图并不是我复制的内容而是一个取色值的图
![image](https://github.com/Snipaste/feedback/assets/45675692/55dea3cb-9c2a-4491-9ddf-311f1a79818a)

### 运行平台

Windows 桌面

### 软件版本

2.8.5

**Comment by liulex** [comment]
谢谢反馈，下个版本修复。
