### ISSUE TITLE
【强烈建议】“滚动截图-截长屏”功能

### ISSUE THREAD

**Issue by tasty007** [Snipaste/feedback#2663]
### 功能描述

强烈建议，
加入“滚动截图-截长屏”功能，都2023年了，
其他家截图软件这个功能都是标配了呀！

**Comment by Vstory** [comment]
这个问题有反馈的，一直没出，做的可能就基本没有。

找替代品。

**Comment by Geeyun-JY3** [comment]
Duplicate of #19

**Comment by ggup13** [comment]
> 这个问题有反馈的，一直没出，做的可能就基本没有。
> 
> 找替代品。

找到替代品了吗，我现在用QQ，但是还要登录QQ，很麻烦
