### ISSUE TITLE
Win 多桌面显示希望可以配置

### ISSUE THREAD

**Issue by GeekRicardo** [Snipaste/feedback#2664]
### 问题描述

win中的多桌面希望可以配置只单独在其中一个桌面置顶贴图，切换到另一个桌面的时候 不显示贴图

### 运行平台

微软商店

### 软件版本

2.8.5

**Comment by Bit51** [comment]
我也有这样的希望。win中的多桌面希望可以配置只单独在其中一个桌面置顶贴图，切换到另一个桌面的时候 不显示贴图

**Comment by liulex** [comment]
专业版有这个选项：
![image](https://github.com/Snipaste/feedback/assets/2010459/820084b1-e658-4aa0-a331-a8e70a64ac26)
但是对新版 Windows 11 支持有点问题，下个版本会修复。
