### ISSUE TITLE
希望可以加入在上次截图位置继续截图的功能

### ISSUE THREAD

**Issue by Priest333** [Snipaste/feedback#2665]
### 功能描述

工作或者记笔记的时候有时会需要对比图展示，或者有时就是需要两张像素相同的图片，如果能在相同的位置截图会省掉PS手动对图的麻烦。

**Comment by Geeyun-JY3** [comment]
https://docs.snipaste.com/zh-cn/key-bindings?id=只对截图有效

> **按键** | **命令**
> -- | --
> …… | ……
> R | 将截屏区域设置为上一次成功截图时的区域

**Comment by Priest333** [comment]
谢谢，问题解决了
