### ISSUE TITLE
希望能加入截图提取文字和翻译的功能

### ISSUE THREAD

**Issue by xiolovelife** [Snipaste/feedback#2666]
### 功能描述

1.提取文字：日常工作中会遇到同事发送图片，但需要提取图片内的文字进行粘贴的场景
2.翻译：在某些软件中有不可复制的文案，只能通过截图识别文字再进行翻译，类似于有道翻译
想着都是截图，能不能新增这两个功能，就不需要再装其他截图工具了，加入专业版也行。

**Comment by Geeyun-JY3** [comment]
Duplicate of #188

**Comment by aihacker** [comment]
希望能加入截图提取文字功能
