### ISSUE TITLE
文字识别功能

### ISSUE THREAD

**Issue by Z001Shen** [Snipaste/feedback#2667]
### 功能描述

生成的贴图 可以识别文字并复制
类似微信中的图片,打开图片可以选中文字直接复制,如果在贴图中能实现这种选中文字直接复制的话,那对于平时工作来说也是提升了一大步.
使用场景: 
- 在看视频学习的时候,视频中有一段文字,一般都是截图贴图然后一个个敲,或者使用其他软件识别.现在贴图可以直接选中复制文字的话可以大大提升效率

**Comment by szhu25** [comment]
Duplicate of #188

**Comment by Geeyun-JY3** [comment]
Duplicate of #188
