### ISSUE TITLE
取色功能添加新的颜色格式

### ISSUE THREAD

**Issue by BreakDreamGan** [Snipaste/feedback#2669]
### 功能描述

希望可以为截图或者贴图的取色功能添加新的颜色格式。
目前有RGB/HEX，这两者本质上都是RGB的。
希望可以再加上HSV等。
或许可参考：
https://blog.csdn.net/lly_3485390095/article/details/104570885

**Comment by Geeyun-JY3** [comment]
Duplicate of #2280
