### ISSUE TITLE
安装后迅速被自动删除

### ISSUE THREAD

**Issue by owenosp** [Snipaste/feedback#2672]
### 联系方式

owenosp@163.com

### 发生了什么？

snipaste在安装好后会在几秒内被迅速自动清除，换了32位和旧版本都无法解决该问题，系统是win10

### 运行平台

Windows 桌面

### 软件版本

基本都试过

**Comment by Geeyun-JY3** [comment]
这……真的不是其他软件干的？

**Comment by liulex** [comment]
显然 Snipaste 自己不会这么做，请自行排查。
