### ISSUE TITLE
能否添加标数字序号功能以及识别/翻译文字的功能

### ISSUE THREAD

**Issue by XLOIEUD** [Snipaste/feedback#2681]
### 功能描述

一、标数字号指这几个圆圈标号，即qq的截图功能，自动按点击顺序生成序号“1”“2”“3”，并可以通过更改颜色以及直接添加注释来与方框配合更加便利于阐述先后关系。（如图）
![image](https://github.com/Snipaste/feedback/assets/56102571/b343450c-ef40-46bc-ad2a-90db3b4891c9)
![image](https://github.com/Snipaste/feedback/assets/56102571/f816902b-a7d4-43f6-a5bd-1b7fd33f88bc)
二、点击按钮一键识别/翻译文字（如图）
![image](https://github.com/Snipaste/feedback/assets/56102571/19bac589-e4ac-409a-b5a3-d4a34d0e8711)
![image](https://github.com/Snipaste/feedback/assets/56102571/4572b440-4956-4c45-847e-9e6bb2958b51)

**Comment by Geeyun-JY3** [comment]
Duplicate of https://github.com/Snipaste/feedback/issues/2525#issuecomment-1475098088

**Comment by Geeyun-JY3** [comment]
Duplicate of #19

**Comment by Geeyun-JY3** [comment]
Duplicate of #188
