### ISSUE TITLE
Option to show snip after snipping

### ISSUE THREAD

**Issue by Din0Git** [Snipaste/feedback#2683]
### Feature Description

Is it possible to make it a option to show the snip after making the snip. This would be great for temp snips without pressing the f3 key al the time.

**Comment by Geeyun-JY3** [comment]
You can click the 📌 button / <kbd>Ctrl</kbd> + <kbd>T</kbd> / Midle click on the snipping area: https://docs.snipaste.com/getting-started?id=what-is-a-successful-snipping

**Comment by Din0Git** [comment]
Thanks for the answer. Is that not the same as f3 (show paste). 

I meanly use snipping when I am working on one screen and need to check some values in different documents. 
My workflow is then snip (f1) area f3 to pin it at top check the value en then discard the snip. 

It would be a nice feature if it was possible to make the snip and it would automatically pin to the screen. This would be awesome. 

Greetz Dino

**Comment by Geeyun-JY3** [comment]
It seems that [Super-snip](https://docs.snipaste.com/pro?id=snip) is what you need. It needs pro.

**Comment by Din0Git** [comment]
That is exactly the feature I am looking for. Is there also a macOS pro version?

**Comment by Geeyun-JY3** [comment]
> That is exactly the feature I am looking for. Is there also a macOS pro version?

Currently no.

**Comment by Geeyun-JY3** [comment]
Duplicate of #2172
