### ISSUE TITLE
能否加个关闭放大镜的功能

### ISSUE THREAD

**Issue by NecocNeko** [Snipaste/feedback#2691]
### 功能描述

每次截图都会自带放大镜，还关不掉
快捷键是默认的，点托盘图像也会
说实话真的不想要这个功能，没什么大用处而且还蛮卡的
![image](https://github.com/Snipaste/feedback/assets/114891998/a5270fb0-421a-4121-b974-bc724b7da757)

**Comment by Geeyun-JY3** [comment]
请善用搜索，专业版是能完全隐藏的：https://docs.snipaste.com/zh-cn/pro
![image](https://user-images.githubusercontent.com/49396421/160538799-480f7705-9a95-4343-861d-0725d1b41893.png)

**Comment by Geeyun-JY3** [comment]
Duplicate of https://github.com/Snipaste/feedback/issues/1679#issuecomment-714527302
