### ISSUE TITLE
在启用了HDR功能后截图会导致截图过曝

### ISSUE THREAD

**Issue by linyu04** [Snipaste/feedback#2693]
### 问题描述

在我使用此软件的过程中，我经常因为开启了HDR功能导致截图过曝问题，但我并不能接受没有HDR的功能后的色彩，如果可以我希望作者能解决开启了HDR后截图导致截图过曝的问题！！！

截图在以下场景经常遇到截图过曝光

1. 网页截图：网页截图一般可能是某些网页元素导致浏览器自适应了HDR导致浏览器显示的页面过曝。
2. 游戏截图：一般在支持HDR的游戏中截图一定会导致截图过曝。

很喜欢这个截图工具，功能非常方便好用非常喜欢！！美中不足的地方是HDR的支持欠缺希望作者能在HDR上做一些优化。

### 运行平台

微软商店, Windows 桌面

### 软件版本

2.8.5（2023.05.08）

**Comment by septs** [comment]
Duplicate of #1112
