### ISSUE TITLE
【OCR、翻译、滚动截图 等痛点需求的参考解决方案】

### ISSUE THREAD

**Issue by Ethkuil** [Snipaste/feedback#2697]
### 功能描述

Pro版 可以自定义一些命令来做后处理。最理想的方式是扩充截图后的工具栏，不过目前新增命令再绑快捷键也能凑合用吧。

如 OCR 就能通过这种方式实现。例：`snip -o "D:\bin\ocr\ocr.png";exec(cmd /c python "D:\bin\ocr\ocr.py" "D:\bin\ocr\ocr.png" | clip && snipaste paste)`（我使用的是百度API）。

翻译、上传图片同理，都可以调 API。

滚动截图一般只在浏览器有用，F12 + capture element screenshot 即可，甚至连扩展不用装，而且又快又整齐。可以满足绝大多数情况的需求。

（希望可以在置顶 issue 或 文档里把这方面讲清楚，如果作者确实不打算在有生之年实现相关功能的话。）

---

然后，希望 Snipaste 能继续提高可扩展性，方便用户自己定制以便实现各种（稀奇古怪的）需求。不过相对算是锦上添花了，因为目前也能凑合。

引用issue：
- #2580

---

最后，作者有空把 issues 清理一下吗（比如把无效/重复/拒绝/已完成的issue关一下），应该能大大减少 issue 数量。如果已经开摆了就当我没说🤣

**Comment by Alexios-cd** [comment]
同样想要 OCR
