### ISSUE TITLE
Disable hotkeys when game window active

### ISSUE THREAD

**Issue by GnatGoSplat** [Snipaste/feedback#2701]
### Feature Description

I like to use PrintScreen key as my Snipaste hotkey since Windows built-in PrintScreen function is useless.  I use a huge 43" display so I often play games windowed.  Games usually have their own screencap function on PrintScreen, and many games also use all the F-keys so those aren't good hotkeys either.  It makes sense for Snipaste to be disabled when the game is the active window.  I would like the ability to configure programs so when their window is active, Snipaste hotkey is disabled.

**Comment by Geeyun-JY3** [comment]
Snipaste can ignore global hotkeys for specified applications. This needs PRO: https://docs.snipaste.com/pro?id=b-higher-freedom-of-customization
