### ISSUE TITLE
使用 autohotkey 映射出的 esc 对截图和贴图操作无效

### ISSUE THREAD

**Issue by xntzmk** [Snipaste/feedback#2702]
### 问题描述

我将 ctrl 映射为 esc，在编辑器和浏览器，qq程序使用都是正常输出esc功能。但是在snipaste上映射失效了。而如果我用键盘上原有的esc按键，可以正常退出snipaste的截图和贴图

### 运行平台

Windows 桌面

### 软件版本

2.8.5

**Comment by liulex** [comment]
贴图我测试过没问题，可能需要你以管理员权限运行 ahk 脚本。
对截图无效的原因参考 #2342.
