### ISSUE TITLE
任务栏的提示经常遮挡截图

### ISSUE THREAD

**Issue by dst1213** [Snipaste/feedback#2704]
### 功能描述

![image](https://github.com/Snipaste/feedback/assets/8596814/ca3d98b9-ed90-4070-a9c5-8132705a273d)
鼠标点击Windows任务栏的snipaste图标触发截图时，尤其是浏览器窗口截图时，snipaste的使用提示气泡经常遮挡网页内容，能不能通过配置去掉或者像有的截图软件那样，使用帮助的提示气泡可以主动避开截图框？

**Comment by liulex** [comment]
可以设置点击托盘图标延迟 0.1s 截图：
![image](https://github.com/user-attachments/assets/4419503b-521e-4700-bafb-f2d5b0a36462)

**Comment by Hvoicecon** [comment]
你好，首先非常感谢你的回复，但是我找不到这个选项，我是免费版的，免费版是不是没有这个选项

**Comment by liulex** [comment]
是的，免费版会少一些定制项。

**Comment by Hvoicecon** [comment]
那就是没办法解决对吗
