### ISSUE TITLE
snipaste.exe和可疑域名www[.]snipste[.]com有通信

### ISSUE THREAD

**Issue by Fay86** [Snipaste/feedback#2705]
### 发生了什么？

公司内部安全检查发现软件进程snipaste.exe和可疑域名www[.]snipste[.]com有通信，这个域名和软件官方的域名 – snipaste[.]com没有任何联系，因此触发了安全报警。
这个域名snipste[.]com是一家欧洲的域名服务商（1API GmbH）在2023/08/20新注册的，目前还没有关于这个域名的风险评级。
然而，软件和非官方的域名进行通信，尤其是和官方域名相似的域名，通常会被攻击者用做建立C&C （Command & Control）通信，以达到窃取信息的目的。
这个工具在公司内部非常好用，但是由于这个问题被移除白名单导致无法使用了。
可否安排修复此问题，以方便继续使用，万分感谢！
![image](https://github.com/Snipaste/feedback/assets/7043094/7a6adaa0-1e47-46a6-862e-92a04a3e2e6f)

### 运行平台

Windows 桌面

### 软件版本

2.8.3

**Comment by szhu25** [comment]
@Fay86 能否确认一下版本和是否从官网（snipaste.com）下载？

**Comment by szhu25** [comment]
@Fay86 两个问题：
目前官网最新版本是2.8.5-beta， 建议检查更新后是否有同样问题
另外… 
    Snipaste 2.x 只对个人用户免费，公司使用请购买专业版或使用 Snipaste 1.x
    Snipaste 1.x 版将停留在 1.16.2，不再更新

请问在公司使用的话，是否通过微软商店或者联系作者购买了Snipaste 2专业版的使用许可？

https://docs.snipaste.com/zh-cn/pro

**Comment by StarryVoid** [comment]
烦请提供 Snipaste 主进程 的 SHA1 值，以及软件下载来源

**Comment by StarryVoid** [comment]
已确认问题现象，已找到问题发生位置，正在检查相关版本号
确认问题版本影响范围为 V2.1.0 > V2.8.5-BETA
问题影响范围 检查软件更新历史记录 的回馈内容

**Comment by Fay86** [comment]
@szhu25 都是从官方网站下载的。目前被1.x和2.x都是被监控和警告的。
![image](https://github.com/Snipaste/feedback/assets/7043094/93ef347e-fe1c-4e64-a857-7e2a070418dd)

**Comment by Fay86** [comment]
> @Fay86 两个问题： 目前官网最新版本是2.8.5-beta， 建议检查更新后是否有同样问题 另外… Snipaste 2.x 只对个人用户免费，公司使用请购买专业版或使用 Snipaste 1.x Snipaste 1.x 版将停留在 1.16.2，不再更新
> 
> 请问在公司使用的话，是否通过微软商店或者联系作者购买了Snipaste 2专业版的使用许可？
> 
> https://docs.snipaste.com/zh-cn/pro

**Comment by Fay86** [comment]
> 已确认问题现象，已找到问题发生位置，正在检查相关版本号 确认问题版本影响范围为 V2.1.0 > V2.8.5-BETA 问题影响范围 检查软件更新历史记录 的回馈内容

好的，感谢反馈，敬候佳音。😊

**Comment by KazamaSion** [comment]
非常感谢您的支持，也为给您带来问题表示抱歉。
目前问题已经定位到并且已经修正错误。

这个问题的起因是在增设服务器的时候，错误地将默认跳转域名写了一个 typo 上去。

考虑到问题发生的时间节点，这个域名很可能是域名服务商发现大量 IP 请求到该错误域名时，自行注册想进行售卖。由于时间较短，应该还不涉及黑产问题。根据 log 朔源，发现时间节点“完全一致”。

**Comment by Fay86** [comment]
> 非常感谢您的支持，也为给您带来问题表示抱歉。 目前问题已经定位到并且已经修正错误。
> 
> 这个问题的起因是在增设服务器的时候，错误地将默认跳转域名写了一个 typo 上去。
> 
> 考虑到问题发生的时间节点，这个域名很可能是域名服务商发现大量 IP 请求到该错误域名时，自行注册想进行售卖。由于时间较短，应该还不涉及黑产问题。根据 log 朔源，发现时间节点“完全一致”。

感谢反馈，速度惊人╰(*°▽°*)╯，那么我是等待发布最新版本后可以验证此问题被修复吗？

**Comment by KazamaSion** [comment]
> > 非常感谢您的支持，也为给您带来问题表示抱歉。 目前问题已经定位到并且已经修正错误。
> > 这个问题的起因是在增设服务器的时候，错误地将默认跳转域名写了一个 typo 上去。
> > 考虑到问题发生的时间节点，这个域名很可能是域名服务商发现大量 IP 请求到该错误域名时，自行注册想进行售卖。由于时间较短，应该还不涉及黑产问题。根据 log 朔源，发现时间节点“完全一致”。
> 
> 感谢反馈，速度惊人╰(_°▽°_)╯，那么我是等待发布最新版本后可以验证此问题被修复吗？

已经被修复，无需更新。这次是增设下载服务器时出现的问题，和软件无关。
如果有更高安全性要求，可以使用商店版。它连联网都不联网。（桌面版也只有更新相关才联网）

**Comment by Fay86** [comment]
> 

咨询下，由于公司禁用了Microsoft Store 的，所以我只能通过桌面版购买专业版，但是我看描述说明说【暂未发布】，请问有计划日程发布吗😅，感谢！

**Comment by StarryVoid** [comment]
<del>当鸡啄完了米，狗舔完了面，火烧断了锁，方可</del>
当不会有人搞盗版，也没有盗版收益可能，以及正版收益不会有那么大抽成，方可

**Comment by KazamaSion** [comment]
首先公司如果限制了商店，一定无法用专业版。
考虑到授权问题，要合规的话可以选择 1.15.x 版本的商店版。

可以直接在下方输入商店链接，下载对应版本手动安装
https://store.rg-adguard.net/

可以在安装前检查数字签名是否是合法的，来验证下载是否可靠。无有效数字签名一定有问题。

该版本因为属于商店版，是不会联网的。也就不会有这次的这个问题。

另外：禁用商店不代表无法安装商店版应用，但是否符合公司规矩看你们公司的具体规定。
