### ISSUE TITLE
支持多个截图快捷键

### ISSUE THREAD

**Issue by AngryChocobo** [Snipaste/feedback#2706]
### 功能描述

需求：可以支持同时配置多个快捷键，如ctrl + alt + A， ctrl + F12
理由：程序员debug代码时候需要截取鼠标hover上去的提示，这时候按alt就会隐藏hover导致无法截到想要内容。 而日常时候则无此限制。我知道**更好的办法是找一个更通用的快捷键可以适配所有场景，但那并不容易，且影响现有习惯**

**Comment by liulex** [comment]
专业版可以。
