### ISSUE TITLE
下载系统

### ISSUE THREAD

**Issue by SHU123123** [Snipaste/feedback#2719]
我无法下载亚当的软件，我是WIN11 系统，请问怎么下载？谢谢

**Comment by Geeyun-JY3** [comment]
什么亚当？官网在这：https://zh.snipaste.com

**Comment by liulex** [comment]
> 我在官网也下载了软件，在QQ 软件管理器也下载了软件，都是出现同一个问题，
> ![image](https://github.com/Snipaste/feedback/assets/2010459/397f95c1-77bf-4480-afa6-2d9a6bb4a2b7)

请先解压再运行！
