### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by ZhangsuEve** [Snipaste/feedback#2729]
### 问题描述

无法启动此应用，因为计算机中丢失api-ms-win-shcore-obsolete-|1-1-0.ddl

### 运行平台

Windows 桌面

### 软件版本

2.8.6

**Comment by szhu25** [comment]
@ZhangsuEve 请下载Visual Studio C++ Redistributable

**Comment by ZhangsuEve** [comment]
张粟
***@***.***



&nbsp;
你好，我的报错是：因为计算机中丢失api-ms-win-shcore-obsolete-|1-1-0.ddl错误
而非故障排除指南中：运行后遇到提示计算机中丢失 api-ms-win-crt-runtime-l1-1-0.dll 错误
已尝试安装Visual Studio C++ Redistributable，无法修复错误


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Snipaste/feedback"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月23日(星期六) 中午11:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Snipaste/feedback] 安装报错 (Issue #2729)





 
@ZhangsuEve 请下载Visual Studio C++ Redistributable

**Comment by szhu25** [comment]
请问
1. 你下载安装的是VS C++ Redist的哪个版本？
2. 你Windows电脑是哪个版本 (Win 10/Win11/Win7， 还有版本号）

我也再去找找是哪个系统/软件提供的这个dll

**Comment by liulex** [comment]
这两天会发个修复版的。

**Comment by ZhangsuEve** [comment]
我的电脑是win7
尝试过指南中的32位和64位版本，均不生效







张粟
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Snipaste/feedback"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月23日(星期六) 中午11:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Snipaste/feedback] 安装报错 (Issue #2729)





 
请问
  
你下载安装的是VS C++ Redist的哪个版本？
 
你Windows电脑是哪个版本 (Win 10/Win11/Win7， 还有版本号）
  
我也再去找找是哪个系统/软件提供的这个dll
