### ISSUE TITLE
截图时把护眼软件修改后的画面截图了。

### ISSUE THREAD

**Issue by cike-567** [Snipaste/feedback#2730]
### 发生了什么？

我使用 iris 这个护眼软件，在截图时把 iris 修改过的画面截图了。

Windows 原生的截图效果：

<img width="808" alt="image" src="https://github.com/Snipaste/feedback/assets/68531942/721118ab-92a0-4beb-9403-2797f8541548">

snipaste 的截图效果：

![image](https://github.com/Snipaste/feedback/assets/68531942/22fb2722-ad88-4078-9b42-0c402dd75f5a)

### 运行平台

微软商店

### 软件版本

2.8.6

**Comment by Geeyun-JY3** [comment]
Duplicate of #1239
