### ISSUE TITLE
更新最新版本后多屏截图故障

### ISSUE THREAD

**Issue by sonatasss** [Snipaste/feedback#2731]
### 发生了什么？

之前一直没有这个问题。
更新到最新版本之后，我双屏只能截图一个屏幕了（只能截图副屏副屏，主屏没办法截图），而且可以截图的这个屏幕一直显示黑屏，也没办法正常截图。（我屏幕都是正常使用的）

### 运行平台

Windows 桌面

### 软件版本

v2.8.7

**Comment by liulex** [comment]
请提供日志文件。

**Comment by liuyike98** [comment]
我也遇到这个问题，直接无法使用了

**Comment by fishtailstudio** [comment]
我也遇到了这个问题，和描述一致

**Comment by Qinnnnnn** [comment]
和楼主描述一致

**Comment by iccfish** [comment]
完全一致的情况：

1. 显示器识别错误，在主窗口上右击托盘图标，但是菜单在副屏上弹出（图1）
2. 截图只能截副屏，主屏没有反应；副屏上虽然能截图，但是显示全黑（图2）

<img width="685" alt="屏幕截图 2023-09-25 194919" src="https://github.com/Snipaste/feedback/assets/1091653/95087bbd-8909-43cb-9168-2319e02459eb">

<img width="3840" alt="屏幕截图 2023-09-25 195011" src="https://github.com/Snipaste/feedback/assets/1091653/6b74805a-31b6-4af2-be1c-7381003535cc">

相关日志：
```
[2023-09-25 19:48:50.098] [I] Parsing command arguments [0]: (sp, show-tray-menu)
[2023-09-25 19:48:57.113] [I] Parsing command arguments [0]: (sp, show-tray-menu)
[2023-09-25 19:49:02.672] [I] Parsing command arguments [0]: (sp, show-tray-menu)
[2023-09-25 19:49:06.750] [I] Parsing command arguments [0]: (sp, show-tray-menu)
[2023-09-25 19:50:03.686] [I] Parsing command arguments [1]: (sp, snip)
[2023-09-25 19:50:03.686] [I] Snip request: 0 (dest: 0)
[2023-09-25 19:50:03.686] [I] Snipper: preparing...
[2023-09-25 19:50:03.686] [I] Desktop: QRect(3840, 0, 3840 x 2160)
[2023-09-25 19:50:03.704] [I] Background size: QSize(3840, 2160)
[2023-09-25 19:50:03.704] [I] Screens: 1
[2023-09-25 19:50:03.704] [I]     QRect(3840, 0, 3840 x 2160), NAME = "M27NQC-STC (1)", Manufacturer = "LLT", Model = "M27NQC-STC-", Serial Number = "0000000000000", DPI = 144 , DPR = 1
[2023-09-25 19:50:03.712] [I] Focus set
[2023-09-25 19:50:03.712] [I] Snipper: preparation done (0)
[2023-09-25 19:50:03.712] [I] Snipper: about to appear...
[2023-09-25 19:50:03.712] [I] Snipper: prepare to show...
[2023-09-25 19:50:03.714] [I] Snipper: shown
[2023-09-25 19:50:03.732] [I] Snipper: focus in
[2023-09-25 19:50:03.732] [I] Snipper: ready [0.045 s]
[2023-09-25 19:50:09.114] [I] Snipper: focus out [3] (Foreground window: )
[2023-09-25 19:50:11.834] [I] Snipper: focus in
[2023-09-25 19:50:13.118] [I] Snipper: focus out [3] (Foreground window: 新通知)
[2023-09-25 19:50:16.121] [I] Snipper: focus in
[2023-09-25 19:50:16.280] [I] Screenshot (3840, 106, 3840 x 1982) destination: clipboard, 
[2023-09-25 19:50:16.286] [I] Snipper: about to quit...
[2023-09-25 19:50:16.312] [I] Snipper: focus out [3] (Foreground window: Snipper - Snipaste)
[2023-09-25 19:50:16.315] [I] Snipper: hidden
[2023-09-25 19:50:16.317] [I] Snipper: quit
[2023-09-25 19:50:16.317] [I] Screenshot successfully saved: clipboard, 
[2023-09-25 19:50:16.455] [I] Snipper: scene saved
[2023-09-25 19:50:52.977] [I] Parsing command arguments [0]: (sp, show-tray-menu)
```
不知道还有没有更多的日志位置，有请告知。

留意到2.8.7beta更新日志是 `修复在少数多屏环境下无法正常截屏`，所以我成少数了属于是。

另外求一下老版本（2.8.6）的下载地址，找不到了，现在没法用，并不太想下回正式版，感谢。

**Comment by liulex** [comment]
@iccfish 这里可以下载旧版: https://bitbucket.org/liule/snipaste/downloads/
这个问题我会尽快修复，谢谢反馈！

**Comment by iccfish** [comment]
已回退到2.8.6-beta，前述两个问题都已恢复，感谢。

**Comment by chunguangfu** [comment]
同样的问题 +1

**Comment by rainbowflesh** [comment]
> 完全一致的情况：
> 
>     1. 显示器识别错误，在主窗口上右击托盘图标，但是菜单在副屏上弹出（图1）
> 
>     2. 截图只能截副屏，主屏没有反应；副屏上虽然能截图，但是显示全黑（图2）
> 
> 
> <img alt="屏幕截图 2023-09-25 194919" width="685" src="https://private-user-images.githubusercontent.com/1091653/270331905-95087bbd-8909-43cb-9168-2319e02459eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzU3OTgsIm5iZiI6MTcwMTI3NTQ5OCwicGF0aCI6Ii8xMDkxNjUzLzI3MDMzMTkwNS05NTA4N2JiZC04OTA5LTQzY2ItOTE2OC0yMzE5ZTAyNDU5ZWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjlUMTYzMTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjVhMmMwZDdiNTgwZmU1MjI5ZTM0OTI2YzNiMWIxZTJlNDA4MDI1NTA4NzlhMTI0MjIzM2QxN2YzMDYxZDBlYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jNejH6Gb6ppQU3tBhMJRplDr530idfk203c0vT94tbo"> <img alt="屏幕截图 2023-09-25 195011" width="2000" src="https://private-user-images.githubusercontent.com/1091653/270331935-6b74805a-31b6-4af2-be1c-7381003535cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzU3OTgsIm5iZiI6MTcwMTI3NTQ5OCwicGF0aCI6Ii8xMDkxNjUzLzI3MDMzMTkzNS02Yjc0ODA1YS0zMWI2LTRhZjItYmUxYy03MzgxMDAzNTM1Y2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjlUMTYzMTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmU3MDYwNDQ3ZGYyNDZiMTM4MDg0YWQ1ODIyOWUwNTdmNWQ0ODI4NTA1ODMwYjEzZTdlOWNlY2U2YjcxNTU1ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7baoTfETtuPQ7vhiqtZ1_jeiMWlOhTH1RTIlYZp59jA">
> 
> 相关日志：
> 
> ```
> [2023-09-25 19:45:35.233] [I] Snipaste 2.8.7-Beta x64 (Desktop) (Qt 6.2.4)
> [2023-09-25 19:45:35.233] [I] OS: Windows 11 Version 2009 [10.0.25951]
> [2023-09-25 19:45:35.233] [I] Cores: 32
> [2023-09-25 19:45:35.233] [I] Elevated: false
> [2023-09-25 19:45:35.233] [I] Log level: 2
> [2023-09-25 19:45:35.233] [I] Application dir: C:/Software/6.Picture/Snipaste
> [2023-09-25 19:45:35.233] [I] Working dir: C:/Software/6.Picture/Snipaste
> [2023-09-25 19:45:35.233] [I] Config: C:/Software/6.Picture/Snipaste/config.ini
> [2023-09-25 19:45:35.233] [I] Library paths: (C:/Software/6.Picture/Snipaste)
> [2023-09-25 19:45:35.233] [I] Screen scale: 1.5
> [2023-09-25 19:45:35.233] [I] Retina factor: 1
> [2023-09-25 19:45:35.233] [I] Screens: 1
> [2023-09-25 19:45:35.233] [I]     QRect(3840, 0, 3840 x 2160), NAME = "M27NQC-STC (1)", Manufacturer = "LLT", Model = "M27NQC-STC-", Serial Number = "0000000000000", DPI = 144 , DPR = 1
> [2023-09-25 19:45:35.238] [I] Desktops: -1
> [2023-09-25 19:45:35.238] [I] Compatability layer: 
> [2023-09-25 19:45:35.238] [I] About to import settings from: C:/Software/6.Picture/Snipaste/config.ini
> [2023-09-25 19:45:35.248] [I] Settings imported
> [2023-09-25 19:45:35.249] [I] Breakpad initialized
> [2023-09-25 19:45:35.410] [I] OpenGL acceleration: true
> [2023-09-25 19:45:35.460] [I] Process priority: 1
> [2023-09-25 19:45:35.460] [I] Initializing Snipaste...
> [2023-09-25 19:45:36.133] [I] Prefetch...
> [2023-09-25 19:45:36.137] [I] Preloaded 28 files: 4 ms
> [2023-09-25 19:45:36.142] [I] Load default ssl configuration: 8 ms
> [2023-09-25 19:45:36.147] [I] About to apply settings...
> [2023-09-25 19:45:36.156] [I] Settings applied
> [2023-09-25 19:45:36.159] [I] Log level set to: 2
> [2023-09-25 19:45:36.201] [I] History dir: C:/Software/6.Picture/Snipaste/history
> [2023-09-25 19:45:36.202] [I] Header version: 198
> [2023-09-25 19:45:36.202] [I] About to restore pasters...
> [2023-09-25 19:45:36.202] [I] Group 0 [LH0OXD]: "默认"
> [2023-09-25 19:45:36.202] [I] Record version: 198
> [2023-09-25 19:45:36.202] [I] To restore: 0
> [2023-09-25 19:45:36.202] [I] Pasters touched
> [2023-09-25 19:45:36.202] [I] All pasters activated: true
> [2023-09-25 19:45:36.335] [I] Unref images: 0 (0 removed)
> [2023-09-25 19:45:36.335] [I] Unref dirs: 0 (0 removed)
> [2023-09-25 19:45:36.336] [I] Empty history info files: 0 (0 removed)
> [2023-09-25 19:45:36.336] [I] Pasters restored
> [2023-09-25 19:45:36.336] [I] Launch time: 1103 ms
> .....
> [2023-09-25 19:48:50.098] [I] Parsing command arguments [0]: (sp, show-tray-menu)
> [2023-09-25 19:48:57.113] [I] Parsing command arguments [0]: (sp, show-tray-menu)
> [2023-09-25 19:49:02.672] [I] Parsing command arguments [0]: (sp, show-tray-menu)
> [2023-09-25 19:49:06.750] [I] Parsing command arguments [0]: (sp, show-tray-menu)
> [2023-09-25 19:50:03.686] [I] Parsing command arguments [1]: (sp, snip)
> [2023-09-25 19:50:03.686] [I] Snip request: 0 (dest: 0)
> [2023-09-25 19:50:03.686] [I] Snipper: preparing...
> [2023-09-25 19:50:03.686] [I] Desktop: QRect(3840, 0, 3840 x 2160)
> [2023-09-25 19:50:03.704] [I] Background size: QSize(3840, 2160)
> [2023-09-25 19:50:03.704] [I] Screens: 1
> [2023-09-25 19:50:03.704] [I]     QRect(3840, 0, 3840 x 2160), NAME = "M27NQC-STC (1)", Manufacturer = "LLT", Model = "M27NQC-STC-", Serial Number = "0000000000000", DPI = 144 , DPR = 1
> [2023-09-25 19:50:03.712] [I] Focus set
> [2023-09-25 19:50:03.712] [I] Snipper: preparation done (0)
> [2023-09-25 19:50:03.712] [I] Snipper: about to appear...
> [2023-09-25 19:50:03.712] [I] Snipper: prepare to show...
> [2023-09-25 19:50:03.714] [I] Snipper: shown
> [2023-09-25 19:50:03.732] [I] Snipper: focus in
> [2023-09-25 19:50:03.732] [I] Snipper: ready [0.045 s]
> [2023-09-25 19:50:09.114] [I] Snipper: focus out [3] (Foreground window: )
> [2023-09-25 19:50:11.834] [I] Snipper: focus in
> [2023-09-25 19:50:13.118] [I] Snipper: focus out [3] (Foreground window: 新通知)
> [2023-09-25 19:50:16.121] [I] Snipper: focus in
> [2023-09-25 19:50:16.280] [I] Screenshot (3840, 106, 3840 x 1982) destination: clipboard, 
> [2023-09-25 19:50:16.286] [I] Snipper: about to quit...
> [2023-09-25 19:50:16.312] [I] Snipper: focus out [3] (Foreground window: Snipper - Snipaste)
> [2023-09-25 19:50:16.315] [I] Snipper: hidden
> [2023-09-25 19:50:16.317] [I] Snipper: quit
> [2023-09-25 19:50:16.317] [I] Screenshot successfully saved: clipboard, 
> [2023-09-25 19:50:16.455] [I] Snipper: scene saved
> [2023-09-25 19:50:52.977] [I] Parsing command arguments [0]: (sp, show-tray-menu)
> ```
> 
> 不知道还有没有更多的日志位置，有请告知。
> 
> 附上往期正常的日志(`2.8.6beta`)供参考：
> 
> ```
> [2023-09-22 02:40:07.162] [I] Snipaste 2.8.6-Beta x64 (Desktop) (Qt 6.2.4)
> [2023-09-22 02:40:07.162] [I] OS: Windows 11 Version 2009 [10.0.25951]
> [2023-09-22 02:40:07.162] [I] Cores: 32
> [2023-09-22 02:40:07.162] [I] Elevated: false
> [2023-09-22 02:40:07.162] [I] Log level: 2
> [2023-09-22 02:40:07.162] [I] Application dir: C:/Software/6.Picture/Snipaste
> [2023-09-22 02:40:07.162] [I] Working dir: C:/Software/6.Picture/Snipaste
> [2023-09-22 02:40:07.162] [I] Config: C:/Software/6.Picture/Snipaste/config.ini
> [2023-09-22 02:40:07.162] [I] Library paths: (C:/Software/6.Picture/Snipaste)
> [2023-09-22 02:40:07.162] [I] Screen scale: 1.5
> [2023-09-22 02:40:07.162] [I] Retina factor: 1
> [2023-09-22 02:40:07.162] [I] Screens: 2
> [2023-09-22 02:40:07.162] [I]     QRect(0, 0, 3840 x 2160), DPI = 144 , DPR = 1
> [2023-09-22 02:40:07.162] [I]     QRect(3840, 0, 3840 x 2160), DPI = 144 , DPR = 1
> [2023-09-22 02:40:07.167] [I] Desktops: -1
> [2023-09-22 02:40:07.167] [I] Compatability layer: 
> [2023-09-22 02:40:07.167] [I] About to import settings from: C:/Software/6.Picture/Snipaste/config.ini
> [2023-09-22 02:40:07.174] [I] Settings imported
> [2023-09-22 02:40:07.175] [I] Breakpad initialized
> [2023-09-22 02:40:07.360] [I] OpenGL acceleration: true
> [2023-09-22 02:40:07.419] [I] Process priority: 1
> [2023-09-22 02:40:07.419] [I] Initializing Snipaste...
> [2023-09-22 02:40:08.225] [I] Prefetch...
> [2023-09-22 02:40:08.230] [I] Preloaded 28 files: 4 ms
> [2023-09-22 02:40:08.235] [I] Load default ssl configuration: 8 ms
> [2023-09-22 02:40:08.243] [I] About to apply settings...
> [2023-09-22 02:40:08.255] [I] Settings applied
> ....
> [2023-09-23 16:21:18.142] [I] Snipper: preparing...
> [2023-09-23 16:21:18.142] [I] Desktop: QRect(0, 0, 7680 x 2160)
> [2023-09-23 16:21:18.301] [I] Background size: QSize(7680, 2160)
> [2023-09-23 16:21:18.301] [I] Screens: 2
> [2023-09-23 16:21:18.301] [I]     QRect(0, 0, 3840 x 2160), DPI = 144 , DPR = 1
> [2023-09-23 16:21:18.301] [I]     QRect(3840, 0, 3840 x 2160), DPI = 144 , DPR = 1
> [2023-09-23 16:21:18.311] [I] Focus set
> [2023-09-23 16:21:18.312] [I] Snipper: preparation done (0)
> [2023-09-23 16:21:18.312] [I] Snipper: about to appear...
> [2023-09-23 16:21:18.312] [I] Snipper: prepare to show...
> [2023-09-23 16:21:18.316] [I] Snipper: shown
> [2023-09-23 16:21:18.352] [I] Snipper: focus in
> [2023-09-23 16:21:18.352] [I] Snipper: ready [0.21 s]
> [2023-09-23 16:21:24.393] [I] Screenshot (4538, 1626, 786 x 291) destination: clipboard, 
> [2023-09-23 16:21:24.393] [I] Snipper: about to quit...
> [2023-09-23 16:21:24.408] [I] Snipper: focus out [3] (Foreground window: Snipper - Snipaste)
> [2023-09-23 16:21:24.413] [I] Snipper: hidden
> [2023-09-23 16:21:24.414] [I] Snipper: quit
> ```
> 
> 确认了一下，2.8.6beta是正常的，2.8.7beta出的问题（根据日志显示）。 留意到2.8.7beta更新日志是 `修复在少数多屏环境下无法正常截屏`，所以我成少数了属于是。
> 
> 另外求一下老版本（2.8.6）的下载地址，找不到了，现在没法用，并不太想下回正式版，感谢。

offtopic, M27NQC-STC 这台显示器好用么?
