### ISSUE TITLE
Latest macOS 2.8.6 beta does not start

### ISSUE THREAD

**Issue by navhaxs** [Snipaste/feedback#2732]
### What happened?

Hi, I upgraded to the latest macOS beta today, which is not starting.
**Snipaste-Mac-2.8.6-Beta.dmg**

`open /Applications/Snipaste.app/Contents/MacOS/Snipaste`

```
❯ /Applications/Snipaste.app/Contents/MacOS/Snipaste ; exit;
qt.gui.icc: fromIccProfile: failed minimal tag size sanity
macOS generated a color-profile Qt couldn't parse. This shouldn't happen.
qt.gui.icc: fromIccProfile: failed minimal tag size sanity
macOS generated a color-profile Qt couldn't parse. This shouldn't happen.
QIODevice::write (QLocalSocket): device not open
QAbstractSocket::waitForBytesWritten() is not allowed in UnconnectedState

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

Any other logs I can help provide?

macOS 13.5.2 (22G91)

### Platform

macOS

### Version

2.8.6-Beta

**Comment by liulex** [comment]
Does restarting macOS help?

**Comment by navhaxs** [comment]
@liulex just did a full reboot, still not working :( Do you have a link to an older mac build I can compare and test?

**Comment by navhaxs** [comment]
<img width="382" alt="image" src="https://github.com/Snipaste/feedback/assets/5162718/0b93c369-bc9d-4f1d-845f-4c612fd7d10e">

Apologies, it is working actually 👍🏼 

Closing this issue.

btw would love to have a PRO mac version sometime!
