### ISSUE TITLE
希望能有选定完截图区域，自动结束截图工作，不弹出修改图片界面

### ISSUE THREAD

**Issue by fanglangxinghai** [Snipaste/feedback#2735]
### 功能描述

我只希望截完区域，就自动保存图片到文件夹，不需要弹出那个修改图片选项的界面

**Comment by Geeyun-JY3** [comment]
可以命令行参数实现。
如果你是需要通过快捷键开始这个流程，需要专业版：https://github.com/Snipaste/feedback/issues/1662#issuecomment-696139652
