### ISSUE TITLE
强烈希望增加截屏OCR功能

### ISSUE THREAD

**Issue by clcaod** [Snipaste/feedback#2736]
### 功能描述

学习党跟视频学习时候如果能够截屏取词，这将对效率有巨大的提升，目前遇到看视频时候想要提取文字，采用的都是第三方工具，比如QQ截屏，Mac自带截屏，但是之所以选择snipaste就是因为他的便携，但是每次遇到ocr需求时候，就不得不放弃snipaste，如果能新增截屏OCR功能这将对我非常有帮助！

**Comment by Geeyun-JY3** [comment]
Duplicate of #188

**Comment by ChyweiChen** [comment]
对对对，强烈推荐增加此功能
