### ISSUE TITLE
保存在剪贴板的截图的名字

### ISSUE THREAD

**Issue by goldenLeaf3** [Snipaste/feedback#2745]
### 发生了什么？

在使用obsidian写markdown文章时，将截图直接粘贴在markdown文章中，截图的文件名如下：

![image](https://github.com/Snipaste/feedback/assets/102369691/1d8910ed-c6ce-43a8-a659-64db2905da4b)

对应的，在磁盘中的文件名如下：

![image](https://github.com/Snipaste/feedback/assets/102369691/b89c7e5c-08da-47a9-a41f-08d59c62733e)

由于markdown文章中引用图片的文件名和磁盘中的文件名不一致，会导致文章部署到博客后图片显示失败：

![image](https://github.com/Snipaste/feedback/assets/102369691/9a93c3b8-24e0-4a15-a541-327ba005eec5)

**修改图片的文件名，保持markdown引用的文件名和磁盘文件名一致后就能正常显示了**

如果Snipaste在生成保存在剪贴板中的截图的文件名时，不含空格就能很好的解决这个问题

### 运行平台

Windows 桌面

### 软件版本

2.7.3-beta

**Comment by liulex** [comment]
……这明显是 Obsidian 自己给粘贴的图像起的名字。
