### ISSUE TITLE
Snipaste 贴图通过右键菜单 "复制图像" 复制进剪贴板后透明通道丢失，只有 Snipaste 自己能正常识别

### ISSUE THREAD

**Issue by yixy-only** [Snipaste/feedback#2751]
### 联系方式

yixy@xege.org

### 发生了什么？

发现图像透明通道丢失的情况，是在CSDN博客平台上写博客时，粘贴剪切板里的图像发现的。
步骤：
1. 先在 **Edge 中右键复制**一张带透明通道的图片。
2. 按 **F3 键将图片贴到桌面上**，透明通道正常。然后 Snipaste 右键贴图，选择 “复制图像”，**Snipaste将图像复制到剪贴板**。
3. 在博客编辑器里粘贴，发现剪贴板粘贴进编辑器的图像背景是黑色的，即**透明通道丢失**。
4. Snipaste再次使用 F3 贴图，发现透明通道是正常的，说明 Snipaste 能正常读取自己复制进剪贴板的数据。

为什么说是 Snipaste 的问题，而不是其它工具：
1. 尝试过在 Edge 浏览器里复制带透明通道图像，**没有经过 Snipaste**，直接粘贴到博客编辑器中，透明通道正常保留。再次粘贴到微信中发送消息，**透明通道正常保留**。
2. 将上一步复制的图片使用 **Snipaste 贴图到桌面**，**透明背景正常显示**，Snipaste 贴图的右键菜单选择“复制图像”。查看剪贴板工具，看到图像确实已经复制到剪贴板，而并非是以文件的形式。
3. 再次将经由 **Snipaste 复制进剪贴板的图像粘贴**到编辑器、微信聊天框，均发现**黑色背景，透明通道丢失**。
4. 上述对比操作，说明了确实是 Snipaste 复制进剪贴板里的数据有问题，其它工具无法正常识别。
5. 通过检查软件设置，发现“输出”选项卡里有个 "以 Windows Bitmap 格式复制图片"，提示会丢失透明通道，使用的是默认设置， **“贴图” 一项并未勾选**。经过测试，无论勾不勾选，复制进剪贴板里的图像，粘贴到其他编辑器都丢失了透明通道。
6. 再次测试 WPS 和 Word，发现**经由 Snipaste 贴图复制进剪贴板的图像**，WPS 能正常读取透明通道但**图像会稍微往右偏移**，移出的部分填入左侧。而 **Word 则无法读取透明通道**。

 综合所述，只有 Snipaste 能正常贴出自己复制进剪贴板的图像数据，其它工具均无法正常读取。

### 运行平台

微软商店

### 软件版本

Snipaste PRO 2.8.8

**Comment by liulex** [comment]
试试 Snipaste 2.9？

**Comment by yixy-only** [comment]
> 试试 Snipaste 2.9？

@liulex  还是不行，刚刚更新了最新版，已重新启动，**没有勾选** 以 Windows Bitmap 格式复制图像。把 Snipaste 贴出来的图像右键选择 "复制图像"，复制进剪贴板的图像还是透明通道丢失的。

![image](https://github.com/Snipaste/feedback/assets/34703796/80a29f4e-4829-41c3-865a-862966a1951d)

不止粘贴到博客编辑器，包括微信，可以明显看到有透明通道和没有通道的区别
![image](https://github.com/Snipaste/feedback/assets/34703796/b02eb3a9-e785-4d59-8a50-091be37f1b9d)

**Comment by liulex** [comment]
没几个程序支持读取剪贴板图像的透明通道，用”复制为文件“（Ctrl+Alt+C) 吧，这样大部分程序应该都能读，包括你提到的微信。
至于你论述的
> 为什么说是 Snipaste 的问题，而不是其它工具：
>  1. 尝试过在 Edge 浏览器里复制带透明通道图像，没有经过 Snipaste，直接粘贴到博客编辑器中，透明通道正常保留。再次粘贴到微信中发送消息，透明通道正常保留。

这第一条我就复现不了，用 Edge 复制 google 首页的 logo，粘贴到微信就是黑底的：
![image](https://github.com/Snipaste/feedback/assets/2010459/2caec09a-3743-495e-b59e-9cefff162f8f)
