### ISSUE TITLE
强制贴图复位/集中以解决 Windows 多屏显示可能导致的问题

### ISSUE THREAD

**Issue by PaperL** [Snipaste/feedback#2760]
## 功能

将当前组所有贴图移动至某屏幕指定位置（例如主屏幕左上角）

## 问题与需求

笔记本办公，不使用笔记本屏幕，外接双屏。主屏 type-c 直连笔记本，副屏(竖屏)通过 USB Hub + HDMI 连接，导致副屏优先级高 Windows 多屏显示经常不断刷新，即开机时只能识别到主屏或副屏，在进入桌面后会在单主屏/单副屏 -> 双屏显示之间切换，导致窗口布局混乱。

某次重启后，可能是由于启动时先仅有主屏显示，副屏贴图位置本应重回主屏，但贴图跑到了屏幕外面。检查图片组确认图片确实还在。查阅 issues 和文档后没发现直接解决方案，最后看到有选中所有图片功能，可以通过屏幕范围内的贴图右键菜单全选图片然后带着屏幕外的贴图拖回来。

虽然这个问题非常小众但是解决方案比较简单，只需提供将当前组所有贴图移动至某屏幕指定位置（例如主屏幕左上角）的功能即可。当然如果能实现全屏贴图管理功能则更为强大，类似 Mac 的 Mission Control。

## 环境
> 无法稳定复现贴图超出屏幕范围
- 系统: Windows 10 Pro
- 硬件
  - XPS-17 9700
  - Dell U2713H (on type-c)
  - 倍思 BS-OH102 拓展坞 + EHOMEWEI E156TSL-G(L12) 便携显示器 (on HDMI)
- 软件
  - Snipaste Pro 2.8.8
  - Intel Graphics Command Center (for multi-screen settings) and NVIDIA GeForce Experience

**Comment by liulex** [comment]
当没有新贴图能被贴出的时候，按贴图键就会检查所有贴图是否在屏幕范围内。
所以如果有贴图在屏幕范围之外，按多几次贴图键，就会把它们放回主屏中央。

**Comment by PaperL** [comment]
> 按多几次贴图键，就会把它们放回主屏中央。

感谢！
