### ISSUE TITLE
WebP 格式不生效

### ISSUE THREAD

**Issue by cyio** [Snipaste/feedback#2765]
### 发生了什么？

保存选择 .webp 格式，输出实际是 png

<img width="487" alt="image" src="https://github.com/Snipaste/feedback/assets/3146103/375076e2-a411-4dec-887b-4bdd234fa0cf">

### 运行平台

macOS

### 软件版本

2.8.6-Beta

**Comment by liulex** [comment]
谢谢反馈，mac 版确实有问题。
