### ISSUE TITLE
开启HDR模式后，在微信应用内的截图对比度过高

### ISSUE THREAD

**Issue by hzccn** [Snipaste/feedback#2768]
### 联系方式

Fanhlh@163.com

### 发生了什么？

触发条件：
1、windows 11系统开启HDR显示模式后
2、在微信的小程序窗口及浏览器窗口内截图时
BUG表现：截图的对比度变高，明显感觉刺眼。
下图为开启HDR模式后微信浏览器的截图：
![Snipaste_2023-10-30_22-25-34](https://github.com/Snipaste/feedback/assets/57343006/3bd6218f-1059-4014-8828-8d222ad249a6)
下图为开启HDR模式后微信小程序的截图：
![Snipaste_2023-10-30_22-25-53](https://github.com/Snipaste/feedback/assets/57343006/191a0f12-9d37-49b3-a76a-3ce79ca4629c)

下图为关闭HDR模式后微信浏览器的截图：
![Snipaste_2023-10-30_22-26-12](https://github.com/Snipaste/feedback/assets/57343006/c576a97f-b4fa-4d75-b560-5a9242d71d1f)
下图为关闭HDR模式后微信小程序的截图：
![Snipaste_2023-10-30_22-26-03](https://github.com/Snipaste/feedback/assets/57343006/e14685a8-8054-4cb5-971b-30378e6a0371)

### 运行平台

Windows 桌面

### 软件版本

2.8.5-Beta

**Comment by Geeyun-JY3** [comment]
Duplicate of #1112

**Comment by WangZiY4-3** [comment]
同样遇到这个问题，还没修复，20240422
