### ISSUE TITLE
“最大历史记录数”对性能影响大吗？

### ISSUE THREAD

**Issue by 1tonsilla** [Snipaste/feedback#2781]
### 问题描述

昨天想找一个东西，找不到，然后用历史记录功能，发现特别好用，我想给最大历史记录设置100个，或者200个，相当于电脑时间线快照功能

但是有点疑惑，不知道这个历史记录，对性能影响大吗？

---
还有一个额外的问题，不知道“最大历史截屏区域数 8”这个是啥意思？

### 运行平台

Windows 桌面

### 软件版本

2.8.5 beta

**Comment by Geeyun-JY3** [comment]
> 还有一个额外的问题，不知道“最大历史截屏区域数 8”这个是啥意思？

进入截图模式后按一下 <kbd>R</kbd> 或 <kbd>Shift</kbd>+<kbd>R</kbd> 你就明白「历史截屏区域」是什么了：#249

**Comment by 1tonsilla** [comment]
> > 还有一个额外的问题，不知道“最大历史截屏区域数 8”这个是啥意思？
> 
> 进入截图模式后按一下 R 或 Shift+R 你就明白「历史截屏区域」是什么了：#249

恩这个懂啦！
下面就等开发大佬过来说下第一个问题了~
如果历史记录功能占用系统资源不多，我准备多设置点

**Comment by liulex** [comment]
> 不知道这个历史记录，对性能影响大吗？

只是占更多磁盘空间，对性能没影响。

**Comment by 1tonsilla** [comment]
> > 不知道这个历史记录，对性能影响大吗？
> 
> 只是占更多磁盘空间，对性能没影响。

谢谢，那我放心了！ 硬盘空间大着了。。我要给数值调大一些 哈哈
