### ISSUE TITLE
自定义截图总是要弹出一个框才能截图!!!!!!很不方便

### ISSUE THREAD

**Issue by AlexanderDash** [Snipaste/feedback#2784]
### 发生了什么？

可以把"自定义截屏"这个窗口中的参数,提前在首选项中设置好么,当自定义截屏的时候就直接进入截屏界面就好了

### 运行平台

Windows 桌面

### 软件版本

2.8.8

**Comment by Geeyun-JY3** [comment]
#2530

**Comment by Geeyun-JY3** [comment]
Duplicate of #2530
