### ISSUE TITLE
设置了自定义文件名，但是粘贴时的文件名还是默认的文件名

### ISSUE THREAD

**Issue by Contentsearch** [Snipaste/feedback#2785]
### 发生了什么？

![image](https://github.com/Snipaste/feedback/assets/51782090/314f6134-d520-4abe-98b5-9d0e122bfbbc)
设置了自定义的文件名后，保存文件时会使用这个名字，但是不操作保存。
直接用Snipaste自带的复制按钮或者 快捷键截图后直接粘贴出来的图片还是默认的文件名格式：如下图，这并不是我设置的格式
![image](https://github.com/Snipaste/feedback/assets/51782090/1278fa7a-ad30-41ba-87c9-ecde8cb850f7)
因为在很多场景不需要保存图片，而是直接粘贴使用

### 运行平台

Windows 桌面

### 软件版本

2.8.3-Beta

**Comment by Geeyun-JY3** [comment]
既然你用的是免费版，你说的「直接粘贴出来」是指什么？
在无法启用`首选项` - `输出` - `剪贴板`下的`复制图像为文件`的情况下，首选项中的`手动保存`的文件名规则应该是无法影响到你复制到剪贴板的图片的文件名的：https://github.com/Snipaste/feedback/issues/1334#issuecomment-558600611

顺便提一句，你这是不是直接粘贴到 Obsidian 里了，之前有人开过相关 issue：#2745
