### ISSUE TITLE
【建议】鼠标穿透激活 / 关闭后加入左上角提示

### ISSUE THREAD

**Issue by Konjac-XZ** [Snipaste/feedback#2791]
### 功能描述

![image](https://github.com/Snipaste/feedback/assets/71483384/e79e98a3-aac4-49f1-83a6-c0ae91418f2a)  
↑ 希望鼠标穿透也有一个这样的提示。  

鼠标穿透这个功能很好用，但是我觉得按下快捷键触发鼠标穿透后没有反馈是一件很奇怪的事情。还得主动用鼠标右键单击一下确认穿透激活没有。  
我认为良好的软件交互设计应该让用户获得每一个输入操作的清晰反馈。搜了一下 Issues 好像没人提这件事，请作者考虑一下。

**Comment by liulex** [comment]
下个版本会加入。
