### ISSUE TITLE
怀疑被隔壁抄袭

### ISSUE THREAD

**Issue by CyanAutumn** [Snipaste/feedback#2792]
### 功能描述

之前描述的不太清楚，重新编辑一下
那个软件我试过了，功能基本上都是一模一样，

我判断抄袭是因为目前来讲，一个截图软件应该做成什么样，实现哪些功能这方面完全没有一个明确的定义，但是这软件就是做到了跟Snipaste做到了起码9成以上的功能，就连操作都一样，可以无缝过渡，（按照腾讯qq开头那几个游戏的判断），所以我认为这就是抄袭，是整个软件层面乃至各种意义上的

我认为有部分代码上的抄袭是这两个软件都有着在win11截超过屏幕分辨率的图片情况下会有开始菜单狂闪的bug，怀疑是用了一样的代码或者api啥的，可能是引用了开源部分的代码？

希望开发组可以重视一下这件事
软件名叫PixPin

**Comment by septs** [comment]
不算抄袭吧，[趋同演化](https://zh.wikipedia.org/zh-cn/%E8%B6%8B%E5%90%8C%E6%BC%94%E5%8C%96)；同一个[生态位](https://zh.wikipedia.org/zh-cn/%E7%94%9F%E6%80%81%E4%BD%8D)上，诉求类似那结果也会大岔不差

**Comment by kerwenard** [comment]
> > > 人家新晋软件直接实现了Snipaste多少年都实现不了的长截屏和OCR 用户在意的是功能性，我说的不对吗
> > 
> > 
> > 这issue也没拉踩软件啊，不是说的怀疑抄袭吗，和用户在意啥有关系吗
> 
> issue发言跟引战似的，首先楼主自己明确说鉴定抄袭，但是我也不知道它怎么鉴定的，理由就是在win11出现同样的bug，pixpin也是延续了snipaste的风格，你想像吧，他也不完全像，你说不像吧它也有点像，不过它整合了受众需要的功能，这是无可厚非的，其次楼主说收集个人信息，大可利用防火墙禁网使用

第一个是软件层面上的抄袭，截图软件应该做成什么样，应该有哪些功能这个没人定义过吧，至少那个软件做到了和Snipaste这个软件我不知道多少，但是用下来9成以上的功能都是有的，有可能更多，我觉得这个在软件层面上就是抄袭了，如果你这东西要硬说不是，那我觉得性质应该更贴近腾讯系qq那几个字开头的游戏吧

**Comment by Vstory** [comment]
> 这么优秀的软件开源不好吗？后继者还可以锦上添花。

搞笑呢

**Comment by Nowaterisenough** [comment]
snipaste也没开源哦，相同的bug可能是因为两者都是基于Qt框架开发的，Qt有的bug，两边可能都有

**Comment by Haerbin23456** [comment]
其实那个 Pixpin 大概就是冲着”想要一个比 Snipaste 更好用的截图工具“来做的，所以 Snipaste 有的他全有了，你要说他抄袭那确实抄了[滑稽]

**Comment by Haerbin23456** [comment]
呀，你是 pixiv 上面那个人吗？我还关注你了 hhh

**Comment by shink** [comment]
虽然但是，貌似确实有点像
