### ISSUE TITLE
两个功能：用键盘设置截图框区域大小；重复截图  谢谢关注

### ISSUE THREAD

**Issue by yangyangxi** [Snipaste/feedback#28]
1.截图时拖出一个区域后， 以100*200格式输入数字  可以将区域大小设置为100*200

2.重复截图：以上一次截图框的位置和大小截图，（可用快捷键）

**Comment by liulex** [comment]
1. 以后会添加此功能。
2. 进入截图后按 `R` 键。

**Comment by GregAMO** [comment]
[命令行选项 · Snipaste](https://github.com/liulex/Snipaste-Feedback/wiki/命令行选项) **初步** 支持了设置截图框区域大小
> --snip X Y WIDTH HEIGHT           开始截屏，并把选区左上角设为 (X, Y)，
                                  宽度为 WIDTH，高度为 HEIGHT
--snip WIDTH HEIGHT               开始截屏，并把选区宽度设为 WIDTH，
                                  高度为 HEIGHT，选区中心为当前的光标位置

常驻 一个 Snipaste 的路径的 文字 贴图 会比较方便哒

**Comment by libukai** [comment]
Win上实现自定义截图尺寸的软件很多，Mac上却一个都找不到，现在是用Snipaste的重复截图来解决的，效率还算是高，不过的确建议是能有输入式自定义的功能
另外，求Mac版能尽快同步Win版的功能，尤其是Pro的高级功能，钱包已经准备好，随时可以付费
