### ISSUE TITLE
snipaste和mydockfinder冲突

### ISSUE THREAD

**Issue by GuXng** [Snipaste/feedback#2802]
### 发生了什么？

开着myDockFinder的话，Snippaste就无法使用截图，按F1会出现颜色识别的小窗口，但是无法使用，再点击任意位置就消失了，重新启动软件也无法解决

### 运行平台

微软商店

### 软件版本

PRO 2.8.8（2023.09.25）（64位）

**Comment by GuXng** [comment]
> ### 联系方式
> _No response_
> 
> ### 发生了什么？
> 开着myDockFinder的话，Snippaste就无法使用截图，按F1会出现颜色识别的小窗口，但是无法使用，再点击任意位置就消失了，重新启动软件也无法解决
> 
> ### 运行平台
> 微软商店
> 
> ### 软件版本
> PRO 2.8.8

**Comment by Mel-SRK** [comment]
我也遇到了此问题

**Comment by liulex** [comment]
可能跟 MyDockFinder 的某项配置有关？我跑了最新版的 MyDockFinder，没重现异常。

**Comment by liulex** [comment]
2.9.2 Beta 已修复。
