### ISSUE TITLE
某些纯文本贴图上点击 复制纯文本 无效

### ISSUE THREAD

**Issue by paul525505651** [Snipaste/feedback#2809]
### 联系方式

paul525505651@gmail.com

### 发生了什么？

某些纯文本贴图上点击 复制纯文本 无效

### 运行平台

Windows 桌面

### 软件版本

2.8.8 pro

**Comment by paul525505651** [comment]
补充，大部分纯文本贴图都是可以正常复制文本的，少部分会出现这个问题

**Comment by liulex** [comment]
请提供具体的可复现步骤。

**Comment by paul525505651** [comment]
> 请提供具体的可复现

**Comment by paul525505651** [comment]
> 请提供具体的可复现步骤。

复现步骤找到了
1 复制一段文本 ，贴图
2 右键点击贴图，保存图片
3 复制步骤2种保存的图片，再次贴图
4 右键点击贴图，菜单项里出现 ，复制纯文本，我理解这里不应该出现这个选项，点击后，复制的其实是图片

**Comment by liulex** [comment]
第四步的“复制纯文本”，获取的是图片的文件路径。
