### ISSUE TITLE
启动 Snipaste-2.8.8-Beta-x86_64.AppImage 执行后未输出任何信息，也没有看到新的进程

### ISSUE THREAD

**Issue by Corybyte** [Snipaste/feedback#2813]
### 联系方式

rzd200213@gmail.com

### 发生了什么？

启动 Snipaste-2.8.8-Beta-x86_64.AppImage 执行后未输出任何信息，也没有看到新的进程
发行版本：Arch LInux 
桌面环境：i3wm
内核版本：x86_64 Linux 6.6.8-arch1-1

### 软件版本

2.8.8

**Comment by zzy-ac** [comment]
@Corybyte 报错跟这个issue一样的

**Comment by liulex** [comment]
抱歉，已发布新版修复这个问题，请从[官网](https://zh.snipaste.com)重新下载。
