### ISSUE TITLE
ubuntu 20.04下 sudo下无法运行，想设置开启自启动

### ISSUE THREAD

**Issue by aohanhongzhi** [Snipaste/feedback#2814]
### 问题描述

```shell
sudo ./Snipaste-2.8.8-Beta2-x86_64.AppImage
```
但是没法执行。

![image](https://github.com/Snipaste/feedback/assets/37319319/497337a9-2389-4859-964a-849a12308bdd)

想从sudo下，设置开启自启动。

![image](https://github.com/Snipaste/feedback/assets/37319319/78577694-71df-4f60-8791-756bd1165faf)

操作系统

![image](https://github.com/Snipaste/feedback/assets/37319319/ca61468f-1f0a-4156-82a0-1c11a6607b42)

### 运行平台

macOS

### 软件版本

2.8.8

**Comment by Corybyte** [comment]
开机自启直接写入到 /etc/profile 中也行

**Comment by liulex** [comment]
”开机启动“灰掉和是否 sudo 没有关系，下个版本会支持设置开机启动。
