### ISSUE TITLE
Named custom snip presets

### ISSUE THREAD

**Issue by DominikMoelter** [Snipaste/feedback#2817]
### Feature Description

Currently if you used custom snip presets they are just named by its size. If you have multiple presets with the same size but with different position from top left you can't differentiate them, because both would be named for example 1021x1276.
![image](https://github.com/Snipaste/feedback/assets/58733212/18c580d9-e266-49bd-ba7d-cf5c5cb5c882)

As far as I can see from the "Edit presets..." dialog, the presets are saved in a simple text file, here it might be possible to save a name at the end, which is then used in the preset selection.

![image](https://github.com/Snipaste/feedback/assets/58733212/8d11d444-0d39-48c4-88dd-9e8ff1c55d2b)

**Comment by liulex** [comment]
> If you have multiple presets with the same size but with different position from top left you can't differentiate them, 

It's a bug. They should look like this:
![image](https://github.com/Snipaste/feedback/assets/2010459/ff7d5a1e-1bfd-4bb9-902c-2bcf77db0c99)
I will fix it in the next release.

To name the presets, it requires the Pro version, but it's not available for macOS yet.
