### ISSUE TITLE
[Ubuntu 20.04] 双屏状态下，两个显示器位置不平导致截图时区域错误

### ISSUE THREAD

**Issue by linzyjx** [Snipaste/feedback#2819]
### 发生了什么？

如这样的双屏布局：
![image](https://github.com/Snipaste/feedback/assets/8017477/16906333-85fb-4d8d-999a-ca8de9e01e2b)

截屏时可能会导致定位问题（此全屏截图下端有问题，大致是把整个桌面往上挪了一下再截图）
![image](https://github.com/Snipaste/feedback/assets/8017477/e2e6afe8-9af2-49d7-9bfb-349c16b7e1a8)

将两个屏幕位置对齐则没这个问题

系统环境：
![image](https://github.com/Snipaste/feedback/assets/8017477/ec7c65da-013d-4e0c-b6ae-0f078c255f11)

### 运行平台

Linux

### 软件版本

2.8.8-Beta2（2023.12.30）

**Comment by StudyingLover** [comment]
same,I use Archlinux and gnome desktop

**Comment by joezhouchenye** [comment]
仍然有这个问题，Ubuntu 23.10，显示器1是16:10 2560x1600，显示器2是2560x1440，像底下图里底边拉平了就没问题

![image](https://github.com/Snipaste/feedback/assets/59191277/f65dfca3-c120-4107-8554-43cb346e3e86)
