### ISSUE TITLE
如何设置linux开机自启动

### ISSUE THREAD

**Issue by StudyingLover** [Snipaste/feedback#2820]
### 问题描述

我想知道在linux如何设置开机自启动？例如systemctl？

### 运行平台

Linux

### 软件版本

v2.88-beta2(2023.12.30)

**Comment by Corybyte** [comment]
在 /etc/profile 中写入 nohup 就好了吧

**Comment by liulex** [comment]
下个版本会支持设置开机启动。

**Comment by linzyjx** [comment]
如果是Gnome等桌面，一般都有一个启动应用程序的配置。感觉用这种在桌面管理下才拉起来的方法会比较好。
