### ISSUE TITLE
Mac版本，以后会上线App Store 吗？谢谢！

### ISSUE THREAD

**Issue by loongtex** [Snipaste/feedback#2821]
### 功能描述

希望这么好的产品，可以上线App Store，到时候我肯定下载使用。（因为公司的奇怪规定，只能在App Store下载使用）

**Comment by Geeyun-JY3** [comment]
之前说的是不上：https://github.com/Snipaste/feedback/issues/2537#issuecomment-1464866895

**Comment by Geeyun-JY3** [comment]
Duplicate of https://github.com/Snipaste/feedback/issues/2537#issuecomment-1464866895
