### ISSUE TITLE
Snipaste.exe 进行了大量的I/O读取

### ISSUE THREAD

**Issue by xiejiang2014** [Snipaste/feedback#2822]
### 问题描述

系统:win10
Snipaste版本:2.8.3 beta
我的电脑一般不关闭, 每天用完就睡眠,所以进程存活时间比较长,这次开机后总运行时间大概是22天多
![image](https://github.com/Snipaste/feedback/assets/44390984/54fb983a-8070-4407-809b-7073cc21c6a2)
我设置了 Snipaste 开机自动启动,但其实很少用,这次开机以来,截图数量绝对不会超过30张.

今天偶然打开任务管理器看了一下性能状况,看到其产生了大量的I/O读取,换算了一下大概是接近17GB的数据量
![image](https://github.com/Snipaste/feedback/assets/44390984/0bb74386-2c17-4651-adba-d6a8fb9f1a46)

请问为什么会产生如此大量的数据读取呢?

### 运行平台

Windows 桌面

### 软件版本

2.8.3 beta

**Comment by liulex** [comment]
打开日志你就会发现 `Preloaded xx files: xx ms [every xx m]`.
如果你希望知道这里的 files 是什么文件，可以自行用软件 Process Monitor 查看。
17GB / 22，一天不过是 770MB，load 一组文件大概是 20MB，一天也大概就 load 了 40 次，是符合预期的。
如果你希望关掉该功能，可以自行在 `首选项` - `常规` - `保持快速响应` 取消勾选。
功能背景：https://github.com/Snipaste/feedback/issues/373 https://github.com/Snipaste/feedback/issues/374

**Comment by xiejiang2014** [comment]
原来是这样, 谢谢解答.
