### ISSUE TITLE
Trayicon context menu position issue, and snipper window

### ISSUE THREAD

**Issue by JokerQyou** [Snipaste/feedback#2826]
### 发生了什么？

多次右键点击托盘图标后，右键菜单位置会出现一个偏移（跑到右上角很远的位置），并且此后每次右键点击托盘图标，菜单都有一定机率出现在这个错误的位置，如图：
![图片](https://github.com/Snipaste/feedback/assets/1465267/33973e61-91c5-41a4-b35e-04eed609eec3)

显示器是1920*1080单屏，缩放100%。操作系统Manjaro Linux。

此外，有一定机率在截图界面选择“复制”后，Snipper窗口（就是那个截图时，内容是全屏图像的窗口）会继续保持在最上层，导致除底部任务栏之外的屏幕区域都无法进行鼠标点击。通过Alt+Tab可以在窗口切换界面看到这个窗口，如果切换到其他窗口，或在切换界面点击关闭Snipper窗口，则可以恢复正常。此外，因为这个窗口不会自动关闭，它会干扰Alt+Tab的切换操作，举例说明：截图之前应用A和应用B有窗口，A当前是活跃窗口，按Alt+Tab会切换到B。截图之后，A恢复为活跃窗口，但Snipper窗口没有关闭，此时Alt+Tab会切换到Snipper，这是一个很反直觉的情况。个人认为Snipper窗口可以在截图完成之后自动关闭。

### 运行平台

Linux

### 软件版本

2.8.9-Beta (2024.01.08) for Linux (AppImage)

**Comment by JokerQyou** [comment]
补充：有时候截图完成后，活跃窗口恢复，Snipper窗口会自己跳出来到最上层。此外，Snipper窗口的位置有时候也是错误的，与右键菜单一样都是向右上角便宜了比较大的一块。

**Comment by Wa-Chilleri** [comment]
相同的问题

**Comment by JokerQyou** [comment]
更多信息：`2.8.8-Beta2 (2023.12.30) for Linux` 这个版本也存在托盘图标右键菜单有机率出现偏移的问题，但是不存在“截图窗口出现大幅偏移”和“拖动贴图后必须再次点击鼠标才能脱离拖拽模式”这两个问题。

因为“截图窗口出现大幅偏移”严重影响使用（基本上三次截图里面两次位置都是错的），我已经暂时回退到`2.8.8`版本。

**Comment by liulex** [comment]
试试刚发布的 2.9 Beta for Linux 版，如果还有问题欢迎 reopen issue.
