### ISSUE TITLE
ubuntu在顶部控制栏点击snipaste菜单里面的截图，不会自动隐藏当前菜单，导致菜单遮挡需要截图的元素

### ISSUE THREAD

**Issue by wordhui** [Snipaste/feedback#2828]
### 发生了什么？

ubuntu在控制栏点击snipaste菜单里面的截图，不会自动隐藏当前菜单，导致菜单遮挡需要截图的元素
* 
![image](https://github.com/Snipaste/feedback/assets/19604635/dcad233e-fe97-4b99-b468-e67a96ef5057)

### 运行平台

Linux

### 软件版本

2.8.9-Bete(2024-01-08)

**Comment by liulex** [comment]
刚发布的 2.9 Beta for Linux 版已修复该问题。
