### ISSUE TITLE
[Linux] 将显示器2设置为主显示器后，截图显示区域不正常。

### ISSUE THREAD

**Issue by linzyjx** [Snipaste/feedback#2829]
### 发生了什么？

# 复现步骤
1. 双屏模式下，将主显示器设置为显示器2
2. 将鼠标分别随机挪到两个屏幕内，触发几次截图（我使用快捷键F1）
3. 发现问题

# 问题描述
在显示器2（鼠标挪到了显示器2的桌面）截图时，截图操作界面在显示器1显示了。

# 临时解决办法
将显示器1设置为主屏幕

# 系统环境
![image](https://github.com/Snipaste/feedback/assets/8017477/77294725-8b61-42ed-9af5-6c9ee2a648ba)

### 运行平台

Linux

### 软件版本

2.8.9-Beta (2024.01.08)

**Comment by MaYueCheng** [comment]
+1，双屏截图有问题

**Comment by linzyjx** [comment]
> +1，双屏截图有问题

@MaYueCheng 将哪个显示器设为主屏幕了，将主屏幕设为另一个显示器能否解决问题？

**Comment by liulex** [comment]
试试刚发布的 2.9 Beta for Linux 版，如果还有问题欢迎 reopen issue.
