### ISSUE TITLE
贴图时，自动生成了一个白色的页边距，如何去掉？

### ISSUE THREAD

**Issue by ohownew** [Snipaste/feedback#2833]
### 问题描述

![image](https://github.com/Snipaste/feedback/assets/17061417/595b4d64-ffff-4ec1-ada4-ef77e3641a67)

### 运行平台

Windows 桌面

### 软件版本

snipaste pro 2.8.8

**Comment by Geeyun-JY3** [comment]
你开了阴影？

**Comment by ohownew** [comment]
> 用 Snipaste 截完图贴出来的？截图时你开了阴影？

是贴出来的。

阴影是开的，但是关掉了之后还是有白边。

![image](https://github.com/Snipaste/feedback/assets/17061417/0f9393f8-52c0-4076-a0ab-7829c54e43e7)

**Comment by ohownew** [comment]
应该不是阴影的问题，是截图的四周多加一圈白色的等距的margin

**Comment by Geeyun-JY3** [comment]
不是贴图的窗口阴影，我是问你用 Snipaste 截图时是不是在输出选项里勾选了阴影？然后将这张图贴了出来？

**Comment by ohownew** [comment]
确实，输出选项去掉阴影就可以了。感谢！！！
