### ISSUE TITLE
这个bug已经修复3个月了，什么时候更新？

### ISSUE THREAD

**Issue by hiforrest** [Snipaste/feedback#2838]
### Problem Description

https://github.com/Snipaste/feedback/issues/2733

遇到这个bug简直是日常操作了，体验直接跳崖。提交了bug报告很快就修复了，可新版本的脚步咋就这么沉重呢？三个月了，我的耐心已经被拉扯得像橡皮筋了，快给我更新啊！😩

### Platform

Windows Desktop

### Version

2.8.8

**Comment by liulex** [comment]
因为这个 bug 存在时间比较久了，近期才被你提出来，说明总体影响较小，不太需要紧急发布修复。
如果对你的日常使用影响较大，可以发送你的微软帐号邮箱到 <snipaste.app@gmail.com>，参与内测版。

**Comment by hiforrest** [comment]
已发送邮件申请内测📧
