### ISSUE TITLE
The middle click shortcut key cannot be assigned. help

### ISSUE THREAD

**Issue by Kimsihong** [Snipaste/feedback#2839]
### Problem Description

I am a paid user who purchased from the Korean Microsoft App Store.
No matter how hard I try to reset the image size with the middle click button, it doesn't work.

The middle click button does not overlap with any other key.
You can use it by pressing shift+middle click.
Just middle clicking the key does not work.

We would appreciate your reply to comsasa@daum.net.

### Platform

Windows Desktop

### Version

ver 2.8.8 (2023.09.25)

**Comment by liulex** [comment]
Resolved offline. Cause: Some other software has taken control of the middle click events.
