### ISSUE TITLE
希望增加对贴图进行裁剪的功能

### ISSUE THREAD

**Issue by yinhux** [Snipaste/feedback#284]
@liulex 有时候从网页复制一张参考图贴图出来，但是如果这个参考图分辨率比较大 已经超过屏幕大小，但我只需要其中的一部分作为参考，这时候如果缩小后再截图这张贴图的话，那么它的分辨率就变了，看不到里面的细节 ，所以也就没什么意义了，所以希望在不改变分辨率的情况下增加对参考图裁剪的功能，主要是有时候绘画我会在桌面放置很多参考图，有的参考图的其余部分是没用的，但是想要在不改变这张参考图的情况下去掉那些没用的 ，这样桌面放置的参考图也就多，而且这张参考图分辨率也不会因此改变 ，也鞥看到更多的细节，如果可以，希望作者可以实现它，谢谢！

还有就是我的贴图缩略图设置的是250x250，为的是将它缩小后可以看到局部细节，不至于设置很小的缩略图看不到一些细节，所以有时候某些需要这样，某些贴图是完全展开的【如果作者可以早点实现对缩略图进行单边缩放的话这个裁剪好像就可以不需要了。。】

**Comment by dlsdgj** [comment]
是裁剪出透明通道吧

**Comment by septs** [comment]
能直接描述需求吗？并不是很明白您的需求及意图

**Comment by septs** [comment]
1. 编辑时可裁剪贴图？
2. 贴图单边缩放？

那么 单边缩放 是一个什么样的概念？

**Comment by liulex** [comment]
@dlsdgj @septs 
我跟他交流过，他的意思是：
1. 对贴图进行裁剪，同时保留裁剪前的缩放状态。比如 1000 * 1000 的贴图，我缩放成 500 * 500，然后再裁剪成 300 * 300 的，这时裁剪后的贴图还可以再还原成 600 * 600 的。不过这个的应用场景还是太窄，适用于超大的、超出屏幕范围的图片。
2. 贴图变为缩略图之后，可以再自由调整贴图的大小。这是个很实用的功能，准备放到专业版。
