### ISSUE TITLE
ubuntu黑屏

### ISSUE THREAD

**Issue by spirit223** [Snipaste/feedback#2841]
### 联系方式

2235569493@qq.com

### 发生了什么？

在Ubuntu系统中使用Snipaste时，只要截屏屏幕就会变成黑屏，但是可以进行所有操作，截图后贴图和保存图片图片也都是黑色的。
当为通过Snipaste点击截屏或者是快捷键按下F1启动截屏时都会变成黑色，不过我的鼠标可以正常操作，拖动截图，贴图等操作都不会受影响，只是屏幕变黑，截图结果也是一张黑图。
我的Ubuntu是在VM Ware17中运行的，相关的系统信息为：
![system_info](https://github.com/Snipaste/feedback/assets/63941510/ba026a5f-bc32-4644-9f9f-164ba08a0b90)
Snipaste的版本为：
![Snipaste_info](https://github.com/Snipaste/feedback/assets/63941510/3edc4181-190e-4208-98dd-c451869bae14)
我通过在官网获取到appimage，使用./Snipaste-2.8.9-Beta-x86_64.AppImage --appimage-extract之后在生成的squashfs-root文件夹中运行AppRun。
发现日期：2021-1-19
我不确定是虚拟机的问题还是我运行软件的方式有问题

### 运行平台

Linux

### 软件版本

2.8.9-Beta(2024.01.08)For Linux

**Comment by XiaoLey** [comment]
Wayland问题，你换成X11就会发现正常了。Linux下，目前我只能在X11上使用这个软件，Wayland下截图会一片黑

**Comment by PDKaren1** [comment]
是的，这个issue有提到未支持WAYLANDhttps://github.com/Snipaste/feedback/issues/2812

**Comment by PDKaren1** [comment]
> 这个网站里面有提到如何切换到X11 http://m.blog.chinaunix.net/uid-15732309-id-5883267.html

3Q!!!!!

**Comment by ousui** [comment]
俺也一样，等作者适配 wayland 吧。

**Comment by shuwn** [comment]
與 #2812 相同問題

**Comment by liulex** [comment]
试试刚发布的 2.9 Beta for Linux 版，已支持 Wayland，如果还有问题欢迎 reopen issue.

**Comment by ousui** [comment]
> 试试刚发布的 2.9 Beta for Linux 版，已支持 Wayland，如果还有问题欢迎 reopen issue.

快捷键有问题，我重新提一个吧。
