### ISSUE TITLE
xfce4桌面环境全屏截图会把图片下移顶部pannel的高度

### ISSUE THREAD

**Issue by uilzzw** [Snipaste/feedback#2842]
### 发生了什么？

系统：ArchLinux
桌面：XFCE4
在XFCE4桌面环境中，桌面上下都有pannel的时候，截图会把图片下移顶部pannel的高度。顶部会显示两个pannel，一个是系统自带的，一个是图片的。

### 运行平台

Linux

### 软件版本

2.8.9_Beta-1

**Comment by coffee0224** [comment]
我也遇到了

**Comment by liulex** [comment]
试试刚发布的 2.9 Beta for Linux 版，如果还有问题欢迎 reopen issue.
