### ISSUE TITLE
[Ubuntu 23.10] 任务栏右键菜单打不开

### ISSUE THREAD

**Issue by joezhouchenye** [Snipaste/feedback#2843]
### 发生了什么？

Xorg

托盘右键打不开菜单

临时解决办法：
贴图，ctrl+shift+P可以打开设置

### 运行平台

Linux

### 软件版本

2.8.9 Beta

**Comment by liulex** [comment]
暂时没有这个系统做测试。。

**Comment by coffee0224** [comment]
OS: openSUSE Tumbleweed
Xfce Version: 4.18
GTK Version: 3.24.39
该环境下托盘右键同样打不开菜单，版本v2.9

**Comment by joezhouchenye** [comment]
之前没更新，现在的现象是右键然后菜单闪一下就没，截图之后再右键可以正常打开一次。
还有不太了解这个右键菜单实现应该用什么库，但是右键菜单的外观看起来是那种很旧的win7风格

**Comment by liulex** [comment]
@coffee0224 @joezhouchenye 
麻烦在首选项里将日志等级设为“调试”，然后右键点一下托盘图标，然后发一下对应的日志 “Tray cion clicked: xxx".
以及在 Ubuntu 20.04，托盘菜单是**左键**触发的，23.10 不能左键触发吗？

**Comment by joezhouchenye** [comment]
日志看起来没啥问题，左键点击是直接就开始截图了，菜单是右键，右键就是会菜单闪一下，截一下图之后能正常打开一次。

还有现在Ubuntu23的托盘图标有点混乱，部分大概是使用新API的显示正常，部分会显示黑色背景。

日志：
![image](https://github.com/Snipaste/feedback/assets/59191277/ed0e3608-d1fa-4635-a433-d7aa4f6ec716)

系统信息：
![image](https://github.com/Snipaste/feedback/assets/59191277/c5389728-7feb-48c8-b388-05c945c29315)

闪烁现象：
[录屏 2024-04-27 13-36-43.webm](https://github.com/Snipaste/feedback/assets/59191277/10ebf4e1-8dbf-49eb-90f9-59f799e57b72)

黑色背景：
![image](https://github.com/Snipaste/feedback/assets/59191277/98acdd5e-bcb2-42ba-9005-cbe282100845)

**Comment by liulex** [comment]
搜了一下，似乎需要安装 `gir1.2-appindicator3-0.1` 这个包。 @joezhouchenye

**Comment by joezhouchenye** [comment]
装了的，我感觉大概率是GNOME改了啥，正好有台旧电脑Ubuntu22.04 GNOME 42.9的试了一下，Snipaste一切正常，包括右键菜单外观。
但是看了一下grep得到的已经安装的appindicator相关的包是一模一样的

![image](https://github.com/Snipaste/feedback/assets/59191277/c58f0adc-dbc7-43e4-9940-a19506c951e6)

**Comment by joezhouchenye** [comment]
Ubuntu22.04：
![image](https://github.com/Snipaste/feedback/assets/59191277/19d785ae-b5f7-408e-baf1-af0362a61605)

**Comment by NextAlone** [comment]
Archlinux + 2.9_Beta2-1 复现问题

**Comment by kaneha** [comment]
我用的debian12出现相同问题, 右键打不开设置界面.

**Comment by Mj65536** [comment]
debian 12 系统，同样的问题，右键闪烁一下，然后马上消失

**Comment by KrisShin** [comment]
ubuntu 24.04 一样无法正常触发右键菜单

**Comment by directentis1** [comment]
我在 Ubuntu 22.04、Xfce4 4.18.4 上也遇到了同样的问题。

左右托盘图标都可以用鼠标右键正常打开，只有 Snipaste 不显示任何内容/显示 Xfce4-trayicon-plugin 的默认值。

![](https://i.imgur.com/AQeMUsP.png)

**Comment by KrisShin** [comment]
> 我在 Ubuntu 22.04、Xfce4 4.18.4 上也遇到了同样的问题。
> 
> 左右托盘图标都可以用鼠标右键正常打开，只有 Snipaste 不显示任何内容/显示 Xfce4-trayicon-plugin 的默认值。
> 
> ![](https://i.imgur.com/AQeMUsP.png)

截个图  Ctrl+Shift+p  可以进设置

**Comment by liulex** [comment]
2.9.2 Beta 已修复。
