### ISSUE TITLE
【Mac平台】希望可以在截图中进行序号标注功能

### ISSUE THREAD

**Issue by Alen-wang** [Snipaste/feedback#2844]
### 功能描述

希望可以在截图中进行序号标注的①②③这些红色标数字序号，标的同时可以填写对应的文字描述。可以参考一下QQ截图，如能增加一下录屏功能当然最好了，这样Snipaste可以秒掉一大部分截图软件【Mac平台】

**Comment by Geeyun-JY3** [comment]
Duplicate of #2172
