### ISSUE TITLE
Load images as a snip

### ISSUE THREAD

**Issue by samohd** [Snipaste/feedback#2846]
### Feature Description

It would be useful to load an image from disk as an onscreen snip to be used as reference, for simple "toolbar" modifying, etc. The way I do it currently is to view image with whatever image viewer, and then snip it. This would be a direct way to achieve the same thing.

**Comment by liulex** [comment]
Just copy the image file, then paste it by <kbd>F3</kbd>. Press <kbd>Space</kbd> on it to show the toolbar.

**Comment by samohd** [comment]
I don't see anywhere in Snipaste where F3 is defined. Where is it? F3 otherwise is a standard shortcut for Search/Next so it seems an unlikely choice. Regardless, this still requires more steps than it should (open file, copy, close file, F3). The simplest would be to just allow drag/drop of file onto the tool tray icon.

**Comment by abc35277** [comment]
> I don't see anywhere in Snipaste where F3 is defined. Where is it? F3 otherwise is a standard shortcut for Search/Next so it seems an unlikely choice. Regardless, this still requires more steps than it should (open file, copy, close file, F3). The simplest would be to just allow drag/drop of file onto the tool tray icon.

Set the F3 key method as shown in the following picture.
![image](https://github.com/Snipaste/feedback/assets/18548307/0842a39e-e5dc-41b8-9b0d-4097312fc9f1)
