### ISSUE TITLE
Linux 版本的鼠标指针没法显示，按什么键都不好使，设置选择了“捕捉鼠标指针”也没用

### ISSUE THREAD

**Issue by XiaoLey** [Snipaste/feedback#2849]
### 发生了什么？

问题：Linux 版本的鼠标指针没法显示，按什么键都不好使，设置选择了“捕捉鼠标指针”也没用
系统：Ubuntu 22.04
GNOME：42.9
窗口系统：X11

CPU：12th Gen Intel® Core™ i7-12700H × 20
显卡：NVIDIA GeForce RTX 3070 Ti Laptop GPU (GPU 0)

### 运行平台

Linux

### 软件版本

2.8.9-Beta (2024.01.08) for Linux

**Comment by liulex** [comment]
刚发布的 2.9 Beta for Linux 版已支持捕捉鼠标指针。
