### ISSUE TITLE
能否添加一个“禁用/开启快捷键”的快捷键

### ISSUE THREAD

**Issue by Watermelon-xxx** [Snipaste/feedback#2851]
### 功能描述

能否添加一个“禁用/开启快捷键”的快捷键，虽然默认的快捷键很方便也可以自定义快捷键，但是PC里不同的应用程序都有着大量自己的快捷键，无论怎么设置总会有那么几个是重叠，而且方便快捷的键位其实就那么几个常用的，所以如果有这么一个快捷键的话，就可以选择在需要截图的时候一键开启snipaste的快捷键进行截图，不需要截图的时候一键关闭其快捷键，从而不影响其他应用或者游戏的快捷键运作，避免在“快捷键冲突”与“截图需求”两个状态之间来回切换，而反复的关闭和打开snipaste程序。

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/947
