### ISSUE TITLE
快捷键问题

### ISSUE THREAD

**Issue by xivi1839** [Snipaste/feedback#2855]
### 发生了什么？

Snipaste，版本v2.8.8，WIN10

全局快捷键，
截屏：Alt+O，

反馈：
快捷键设定为组合键，无法截屏下拉菜单，例如记事本栏目的下拉菜单，可以修复此问题吗。

就像图片这样

![Snipaste_2024-02-02_05-07-25](https://github.com/Snipaste/feedback/assets/24610024/ceda4104-06f4-4386-aec8-2c20d0d62a60)

### 运行平台

Windows 桌面

### 软件版本

Snipaste，版本v2.8.8，WIN10

**Comment by Geeyun-JY3** [comment]
请认真阅读文档：https://docs.snipaste.com/zh-cn/troubleshooting?id=无法截取菜单，一按截图快捷键菜单就消失了

> - 对于 Windows 系统，<kbd>Alt</kbd> 按下时菜单会自动消失。因此，如果需要截取菜单，截图快捷键不要包含 <kbd>Alt</kbd> 即可
> - 也可以使用延时截屏
