### ISSUE TITLE
内置快捷键能否改为可自定义或者部分禁用

### ISSUE THREAD

**Issue by xiaoshouhouzi** [Snipaste/feedback#2857]
### 问题描述

Ctrl+A在使用此软件后变为了截屏，并且不可修改，但是全选功能在平常工作中也在使用，所以能否将内置快捷键改为可自定义的或者部分禁用，这样灵活性会大很多。

### 运行平台

Windows 桌面

### 软件版本

2.8.8

**Comment by Geeyun-JY3** [comment]
这不是可以自定义吗：
![image](https://github.com/Snipaste/feedback/assets/49396421/8c5ede3b-0450-44d7-b927-46a42a24213d)

另：Snipaste 的默认截屏快捷键是 <kbd>F1</kbd>，不会是 <kbd>Ctrl</kbd>+<kbd>A</kbd>，你是不是之前不经意间改过。

**Comment by liulex** [comment]
内置快捷键和全局快捷键是两回事，内置快捷键一定不会影响其他程序。
