### ISSUE TITLE
截图的时候背景变暗了，重启软件也不行，之前还不会的

### ISSUE THREAD

**Issue by SuremyTse** [Snipaste/feedback#2860]
### 发生了什么？

已附图
![Snipaste_2024-02-04_16-26-18](https://github.com/Snipaste/feedback/assets/133620172/09e1ab28-ecbd-4ae5-9340-e71fe40dd0d1)

### 运行平台

Windows 桌面

### 软件版本

Windows11

**Comment by Geeyun-JY3** [comment]
你是不是开了哪个第三方软件的护眼模式：#1239

**Comment by SuremyTse** [comment]
> 你是不是开了哪个第三方软件的护眼模式：#1239

enen 我有开护眼模式，今天问题没出现了

**Comment by SuremyTse** [comment]
您好，
23年购买了pro版，现在笔记本电脑更新了系统，重新下载snipaste软件，结果用不了pro版了，我也没找到licence，能帮我解决这个问题吗？
谢谢！
________________________________
发件人: Geeyun-JY3 ***@***.***>
发送时间: 2024年2月5日 12:02
收件人: Snipaste/feedback ***@***.***>
抄送: SuremyEnglish ***@***.***>; Author ***@***.***>
主题: Re: [Snipaste/feedback] 截图的时候背景变暗了，重启软件也不行，之前还不会的 (Issue #2860)


你是不是开了哪个第三方软件的护眼模式：#1239<https://github.com/Snipaste/feedback/issues/1239>

―
