### ISSUE TITLE
fedora38系统使用时截图黑屏

### ISSUE THREAD

**Issue by Mayday05Jqx** [Snipaste/feedback#2862]
### 发生了什么？

运行软件后, 按F1键截屏,屏幕全黑.

### 运行平台

Linux

### 软件版本

Snipaste-2.8.9-Beta-x86_64

**Comment by iceBear67** [comment]
尝试 2.8.8 是不是正常截图？

**Comment by TheSnowfield** [comment]
你是否使用wayland而不是x11?

**Comment by ningblue** [comment]
我也遇到了,manjaro系统 wayland

**Comment by liulex** [comment]
试试刚发布的 2.9 Beta for Linux 版，已支持 Wayland，如果还有问题欢迎 reopen issue.
