### ISSUE TITLE
快捷键设置与对应操作的一些建议(增加复选框)

### ISSUE THREAD

**Issue by 421009692** [Snipaste/feedback#2865]
### 功能描述

希望对“快捷键设置界面“进行调整，增加复选框，以达到更加灵活的使用体验。
例如：
 Alt+A    ☑截图    ▢工具条  ☑贴图 ☑复制到剪贴板  ▢保存文件
 Ctr+A    ☑截图  ☑工具条  ▢贴图   ☑复制到剪贴板  ▢保存文件
Ctrl+Alt+A    ☑截图  ☑工具条  ☑贴图 ☑复制到剪贴板 ☑保存文件

**Comment by Geeyun-JY3** [comment]
说实话没看太懂。你说的「快捷键设置界面」是指什么？

**Comment by 421009692** [comment]
哦  我收到了
会看的

**Comment by 421009692** [comment]
> 说实话没看太懂。你说的「快捷键设置界面」是指什么？
![Snipaste_2024-02-20_21-15-01](https://github.com/Snipaste/feedback/assets/61961313/4c08f431-f937-420d-bc9d-12ce2d233056)

**Comment by Geeyun-JY3** [comment]
呃所以你是嫌这个面板给出的可选的功能组合太少？这你应该用专业版的全局快捷键 与 命令行调用 绑定：https://docs.snipaste.com/zh-cn/pro?id=b-更自由的定制化

**Comment by 421009692** [comment]
哦  我收到了
会看的
