### ISSUE TITLE
Linux 公测版 鼠标中键功能失效

### ISSUE THREAD

**Issue by Darlilu** [Snipaste/feedback#2869]
### 联系方式

darlilu1999@hotmail.com

### 发生了什么？

我使用的系统是Ubuntu20.04,按F1截图选取界面，然后按中键无法创建贴图

### 运行平台

Linux

### 软件版本

v2.8.9-Beta

**Comment by liulex** [comment]
未能复现，不过可以试试刚发布的 2.9 Beta for Linux 版，如果还有问题欢迎 reopen issue.
