### ISSUE TITLE
这是我用过最好用最高效的截图工具软件,但是现在工作中有新的需求,就是截图图片文字识别功能,希望能够在今年增加

### ISSUE THREAD

**Issue by javaxubo** [Snipaste/feedback#2873]
### 联系方式

java_xubo1995@163.com

### 发生了什么？

不是bug缺陷,是想能够增加一个新的功能,截图图片文字识别功能.

### 运行平台

Windows 桌面

### 软件版本

2.8.3

**Comment by Geeyun-JY3** [comment]
Duplicate of #188
