### ISSUE TITLE
画圆形方形时能加一个旋转按钮吗？

### ISSUE THREAD

**Issue by msjsc001** [Snipaste/feedback#2874]
### 功能描述

画圆形方形时能加一个如文字编辑一样的旋转按钮吗？
![image](https://github.com/Snipaste/feedback/assets/93178788/299cd3ca-55ed-468a-8653-ebe42c2331a0)

**Comment by Geeyun-JY3** [comment]
需要专业版：

https://docs.snipaste.com/pro?id=snipaste-2-pro-vs-free-version

> <table>
> <tr>
> 	<td>
> 	<td>免费版
> 	<td>专业版
> <tr>
> 	<td><b>标注</b>
> 	<td>
> 	<td>
> <tr>
> 	<td>……
> 	<td>……
> 	<td>……
> <tr>
> 	<td>旋转标注图形
> 	<td>仅文字标注
> 	<td>除线条标注外都支持
> </table>

#877

**Comment by Geeyun-JY3** [comment]
Duplicate of #877
