### ISSUE TITLE
请加入截图后能自动保存不用确定保存路径的功能

### ISSUE THREAD

**Issue by TheFishbone** [Snipaste/feedback#2877]
### 功能描述

如题，每次截图完都有“图片另存为”窗口弹出，希望有开关选项:截完图快速保存不用点保存也不用再确定保存路径

**Comment by Geeyun-JY3** [comment]
这不是有吗：
![image](https://github.com/Snipaste/feedback/assets/49396421/1e3c0924-87fb-423d-b9cb-c74301dc8509)
