### ISSUE TITLE
win10设置为系统启动 , 后台运行一段时间后自动退出

### ISSUE THREAD

**Issue by qianjigit** [Snipaste/feedback#288]
发现了 bug？
* 请描述一下重现的步骤，越详细越好

**一直都是默认后台启动的 , 最新版本发现会自己退出 / 闪退 , 进程消失 , 需要重新运行 , 再次手动运行后无其它异常.**

**Comment by septs** [comment]
请检查 360加速球、腾讯电脑管家 是否有将其杀死。

**Comment by will6618** [comment]
谢谢 , 无上述软件 , 倒是装了个火绒在尝试 , 我添加信任试试.

**Comment by liulex** [comment]
开机启动是否有勾选”管理员身份“？（非解决办法，只是需要确定一下开机自启和手动启动的差异）

**Comment by will6618** [comment]
有的 , 并且默认是以管理员身份开机启动 

![](http://ww3.sinaimg.cn/large/0060lm7Tgw1fb452wviczj30a60ax0tw.jpg)

另外火绒上设置无异常 , 日志也无异常

**Comment by archonwang** [comment]
+1
同样问题，是否有后台冲突？

**Comment by septs** [comment]
发现 Snipaste 死亡时托盘图标是否存在驻留？
（如果有则是第三方杀死）

**Comment by will6618** [comment]
按快捷键没响应时 , 去看托盘图标是在的 , 鼠标移动上去 , 才会闪没 , 最近新装常驻后台或者一样系统启动的程序就是 everything 和 火绒 . 

其它的以前没有问题的版本也有 : capslock+ , ss2.5.6  , 至于手动运行的就是常用软件如chrome , vmware , QQ轻聊版 , 微信PC版 , 印象笔记 , Directory opus

**Comment by liulex** [comment]
@will6618 @archonwang 
试试手动启动 `%appdata%Microsoft\Windows\Start Menu\Programs\Startup\` 里的 snipaste.lnk，而非双击 exe，看是否还会退出。
另，是启动后马上就挂掉，还是执行了 Snipaste 的什么操作之后才挂掉？

**Comment by will6618** [comment]
@liulex 
设置了系统自启动 , 开机一段时间内还能正常使用 , 突然就不能用的 , 然后只要重新手动启动 , 不管是双击exe , 还是通过lnk运行 , 都会一直正常.

**Comment by septs** [comment]
请查看 事件查看器 中是否有与 Snipaste 相关的事件

**Comment by liulex** [comment]
@will6618 
感谢反馈，我也不太清楚为什么开机自启的进程会有所不同。麻烦你再测试下：

1. 大概是启动多久后会消失
1. 是否启动后不碰 Snipaste，Snipaste 也会在一段时间后消失
1. 取消勾选管理员，再开机启动是否还会崩
1. 从 https://bitbucket.org/liule/snipaste/downloads 下载历史版本，试试问题是从哪个版本开始存在的

第四步有些麻烦，要不你发封邮件到 <snipaste.app@gmail.com>，我给你发个带控制台的版本，应该可以在程序异常的时候看到一些输出。

**Comment by will6618** [comment]
@septs 系统日志初步看无相关信息事件

@liulex 我再测试多两天看看 , 我另一台电脑一直正常使用的是1.10.1 , 未出现过这个情况 , 差别就是没有上述说的everything 和 火绒 , 另外系统是 2015 ltsb版 , 有问题的是 2016 ltsb版  ,  snipaste 是 1.10.5 , 我也尝试把那台更新看看会不会有这个情况 , 另外邮箱的话可以发我后缀gmail.com

**Comment by archonwang** [comment]
@liulex 
出现这种情况不是一开始的时候就自动退出了，而是过了一段时间后会自动关闭，比较莫名。。
麻烦一并发个带控制台的版本用来测试下，最好能输出log文件。我检查过对应的windows错误日志，找不到相应的错误。。。
头大。。。。

不知道是不是因为电源管理的问题，从休眠切换回来不知道是不是能重现该错误。谢谢。

**Comment by archonwang** [comment]
@liulex 已发邮件到你gmail邮箱。谢谢。

**Comment by liulex** [comment]
@will6618 @archonwang 已发送。

**Comment by KNCheung** [comment]
这个是不是Win 10的Defender的锅？我最近用连续几个版本都会时不时出现这种问题。我在后台有自己写 的Autohotkey脚本，如果Snipaste被杀了的话，Autohotkey的脚本也会被杀掉，两者是同时消失的。

常驻的进程有QQ轻聊版、Steam等等。

**Comment by archonwang** [comment]
可能是，目前win10上有些机制让我等小白用户比较纠结。有些程序会莫名其妙出现问题。比如UAC。

**Comment by liulex** [comment]
@will6618 @archonwang 才想起来你们还没用测试程序给我提供反馈。。=_=
@KNCheung 应该也不是 Defender 的锅，因为我这边没问题。
我觉得应该是其它某个程序造成的，不知道你们三个共同用的常驻后台的程序有什么。。

**Comment by xintiandi** [comment]
我最近也需要这样了这样的问题，不知道什么情况出现，win10,1607，前几天几乎每天都出现，这2天好像又正常了。和楼主的描述一模一样。托盘去图标，看着有，鼠标一悬停就消失了。f1无法呼出，确认程序退了。

**Comment by KNCheung** [comment]
@liulex @will6618 @archonwang 
Defender,  OneDrive,  QQ轻聊版  Everything  A卡的催化剂  Listary  Rainmeter  坚果云  iCloud  Ditto  f.lux  XX-net  锐捷  AHK脚本一个  Steam  哦，还有个RIME输入法
托盘上看到的就这些。iCloud  Ditto应该不关事。
有办法查到是谁干掉的么？好像根本没规律。

**Comment by liulex** [comment]
@KNCheung 
除了这几个，Qt我都有在用：
 QQ轻聊版 A卡的催化剂 Rainmeter Ditto XX-net 锐捷 AHK脚本一个 Steam RIME输入法
没有特别可疑的= =

我给你邮箱发了带 log 的测试版了，问题重现了请发回 log 给我~

**Comment by KNCheung** [comment]
@liulex 
已经换上了。我用电脑用得比较多，一旦崩了就回报。估计QQ&Steam比较可疑，毕竟自带保护，不过也说不好……

**Comment by archonwang** [comment]
我的和@KNCheung基本一样，还有个chrome常驻后台。

**Comment by will6618** [comment]
@liulex 我发现用了带log版本的不退了 , 是1.11的原因吗? 不闪退了就没有log了 , 而且我用回旧版本测试 , 只要不是开机自启动就不会闪退 , 开机后手动运行是一点问题都没有的.

**Comment by will6618** [comment]
@KNCheung Defender 我新版win10是停用了的 , 应该跟它无关

**Comment by liulex** [comment]
@will6618 那你用官网的不带 log 的 1.11 试试……
@KNCheung 你遇到的情况是用的 1.11 吗？

**Comment by will6618** [comment]
@liulex 好的 , 不带log的也试过手动运行没问题... 自启我再试试

**Comment by ImFengLala** [comment]
我的也是这个情况，但是snipaste不是这样，teamviewer，adsafe是这样，开机后一会CPU飙到100%，然后就挂掉了，托盘图标还在，然后鼠标挪上去就不在了。everthing，必应词典，snipaste则是根本不开机自自启了。用的win10 10586版本，开启defender，系统更新一直更新。我觉得是win10的锅，我的系统一直升不了新版win10，好像也是这个原因

**Comment by ImFengLala** [comment]
我的开启了UAC提示，而且据我经验貌似只要有UAC提示的软件设置为开机都会出现问题。。。

**Comment by septs** [comment]
@ImFengLala `Windows 10 1607 (OS Build 14393.576)` 我目前并没有观测到这一问题

**Comment by ImFengLala** [comment]
@septs 我的更新不了系统，尝试好多好多方法好多次都不行，不知道怎么回事，现在还是买来时候的10586.713

**Comment by will6618** [comment]
@ImFengLala @liulex 版本号 `Windows 10 1607 (OS Build 14393.576) `  2016 ltsb 企业版 , 经测试最新的Snipaste1.11.0官方版本正常 , 无其它异常.

另一台同配置电脑在公司 , 版本号会低点 , 是2015 ltsb 企业版的 , 官方版本还有待测试 , 带log版本有异常.

均关闭了Windows Defender

**Comment by will6618** [comment]
另外我的UAC也是设置为最低`从不通知`

**Comment by KNCheung** [comment]
这就有点尴尬了……没崩……AHK崩了……

**Comment by xintiandi** [comment]
我今天又出现了退出的情况，只有暂时多开一个截图软件

**Comment by will6618** [comment]
@liulex 版本号 Windows 10 1607 (OS Build 14393.576) 2016 ltsb 企业版 , 最新的Snipaste1.11.0官方版本今天自启后 , 用到下午异常退出1次 , 另外新版本截图按快捷键后的响应很慢 , 特别是自动启动 , 默认是管理员模式 ,  首次截图的响应特别明显 . 手动运行没有这个情况

**Comment by liulex** [comment]
@will6618 启动后首次截图卡和首次检查更新卡的问题会在下个版本修复。
至于崩溃，真是没办法了……不截图不贴图 Snipaste 应该是不会有任何操作的，所以后台时自动退出应该是其他程序影响的 @xintiandi

**Comment by liulex** [comment]
@xintiandi @will6618 @ImFengLala @archonwang @KNCheung 
你们可以试试不带管理员权限运行，看情况是否还存在。
或者试试 32 位的 Snipaste，有一些用户是用 64 位有问题 32 位没问题的。

**Comment by will6618** [comment]
@liulex 另一台电脑带log版本的依然是正常的 , 还是不自启好了 , 手动运行也挺好

**Comment by tony1ee** [comment]
同样问题 运行一段时间以后 快捷键就会失效 鼠标移上托盘图标 图标就消失了

**Comment by tony1ee** [comment]
怀疑是sleep以后唤醒的时候死的

**Comment by tony1ee** [comment]
这么久了 发现这个bug似乎还没被解决啊 我有用bitlocker请问这个会导致吗

**Comment by psby233** [comment]
@liulex 我换成商店版之后再也没见过这个问题了……除了偶尔响应慢之外。

**Comment by tony1ee** [comment]
@liulex 目前使用的版本是1.15.3 
最近一直没有遇到这个问题，已经忘却了，似乎已经没有这个问题了。

**Comment by zongyun1999** [comment]
同样的问题 我似乎是因为火绒的原因  火绒里面关闭这“防护中心”的“应用加固”解决问题

**Comment by PYguldan** [comment]
我也遇到这种情况了，就是开机自启的，然后用着用着，突然想截图没反应了，发现它被关了。有没有解决了这个问题的。
一开始还无所谓，再去开一下就好。遇上好几次了，就想着是不是没更新，检查更新也是最新版了。
是windows安全中心把他关了吗，别的安全软件我都没有装过。

**Comment by ninjaxyh** [comment]
我天，这个问题原来已经好多年了。我也遇到这种情况了，自启动，过段时间它自己就退了

**Comment by KazamaSion** [comment]
@ninjaxyh 我在更新 win11 一段时间里也遇到过这个情况，但后来不知道怎么的它自己又好了。我也什么都没做，摸不透规律。

**Comment by ninjaxyh** [comment]
> @ninjaxyh 我在更新 win11 一段时间里也遇到过这个情况，但后来不知道怎么的它自己又好了。我也什么都没做，摸不透规律。

这么巧，我刚评论就回了

**Comment by greenhand-xj** [comment]
我这几天都是这样，莫名其妙就退了

**Comment by jazzii36** [comment]
我这几天都是这样，莫名其妙就退了

**Comment by greenhand-xj** [comment]
我最近几天还是这样 

> 我这几天都是这样，莫名其妙就退了

**Comment by jazzii36** [comment]
来信已收到，谢谢。

**Comment by greenhand-xj** [comment]
我window11的系统，没有这类软件，现在没有之前那么频繁退出了

> > 我最近几天还是这样
> > > 我这几天都是这样，莫名其妙就退了
> 
> 你是不是用的360或者游戏加速软件的一键提速或者类似功能的软件？

**Comment by su-yh** [comment]
我也这样的问题，我用的是1.16.2-x64 。不过这个问题在我这里挺长时间了，不知道怎么回事，也就没去管了，有时候就用QQ 的截图。这边有找到根本原因吗？
