### ISSUE TITLE
deepin v23截图后会弹出一个遮罩层，导致系统无法操作

### ISSUE THREAD

**Issue by LinThon** [Snipaste/feedback#2889]
### Contact Details

1047214125@qq.com

### What happened?

系统：deepin linux （社区版v23 beta3）
软件版本：Snipaste-2.8.9-Beta-x86_64.AppImage
问题： 当点击完成截图，会弹出一个snipaste的遮罩层，使得系统出现不能操作的假像；需要切换到其他界面才能关掉这个遮罩层，恢复正常使用

### Platform

Linux

### Version

Snipaste-2.8.9-Beta-x86_64.AppImage

**Comment by liulex** [comment]
试试刚发布的 2.9 Beta for Linux 版，如果还有问题欢迎 reopen issue.
