### ISSUE TITLE
截好图，点击复制到剪贴板，然后打开某个文件夹，然后按ctrl+v可否直接把剪贴板的图片在当前文件夹下创建图片文件？

### ISSUE THREAD

**Issue by datakm** [Snipaste/feedback#2894]
### 功能描述

点击复制到剪贴板，然后打开某个文件夹，然后按ctrl+v可否直接把剪贴板的图片在当前文件夹下创建图片文件？在某些场景下，这样就可以节省简化一些操作步骤

**Comment by lu230601** [comment]
你设置截图输出目录不可以吗？

**Comment by datakm** [comment]
可以的，只是平常复制后会不自觉的直接ctrl+v。设置截图输出目录要找到对应的截图要不停的点点才能找到，我感觉有点繁琐。感觉ctrl+v一步到位好用点~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月22日(星期五) 中午1:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Snipaste/feedback] 截好图，点击复制到剪贴板，然后打开某个文件夹，然后按ctrl+v可否直接把剪贴板的图片在当前文件夹下创建图片文件？ (Issue #2894)





 
你设置截图输出目录不可以吗？

**Comment by foreveruand** [comment]
有这个功能啊，建议你找找看是不是专业版有的。反正专业版可以

**Comment by Geeyun-JY3** [comment]
请认真阅读文档，需要专业版：https://docs.snipaste.com/zh-cn/pro?id=%e5%85%b6%e4%bb%96
