### ISSUE TITLE
文字截取不会自动换行.复制VScode的代码，不会自动换行导致图片横向蔓延。

### ISSUE THREAD

**Issue by xyself** [Snipaste/feedback#2901]
### 发生了什么？

**复制代码时。ctrl+c复制代码后。F3唤出截图。
未忽略格式下。文本不会自动根据屏幕换行。无限往右蔓延。
建议增加自动换行功能**
![image](https://github.com/Snipaste/feedback/assets/133769218/f0624f2c-0456-4673-b40e-bce75e24703a)

### 运行平台

微软商店

### 软件版本

2.88

**Comment by liulex** [comment]
下个版本修复，但需要手动在配置文件加上：
```
[Paste]
force_html_wrap=true
```
