### ISSUE TITLE
Mac 截图时怎么取消圆角？

### ISSUE THREAD

**Issue by Reedef** [Snipaste/feedback#2902]
### 问题描述

虽然很多时候圆角截的图很不错，但有些场景下又需要用到直角，在 2.8.6-beta 上并没有设置圆角的选项，这个是没考虑还是我没找到？

### 运行平台

macOS

### 软件版本

2.8.6-beta

**Comment by szhu25** [comment]
@Reedef Win专业版已支持

**Comment by liulex** [comment]
下个版本会修复免费版误触发圆角截图的问题。
