### ISSUE TITLE
Cannot stop quicksaving into general desktop folder

### ISSUE THREAD

**Issue by D-Dot7** [Snipaste/feedback#2903]
Problem Description
I have no idea how to configure the quick save path. I at first downloaded the beta version in my desktop folder. Then it would save all my quicksaves directly into there. I deleted the program and tried to install the regular one into a folder I made called "Snips", but it STILL saved my quick saves into my general desktop folder. How to I get it to save them into my "Snips" folder?

Operating platform
Windows 10

Software version
v1.16.2

**Comment by liulex** [comment]
Change it here:
![image](https://github.com/Snipaste/feedback/assets/2010459/30b9beb0-38ed-4cd0-8cf1-626697656dfe)
