### ISSUE TITLE
Hope to obtain screen XY coordinate value

### ISSUE THREAD

**Issue by Javahhhh** [Snipaste/feedback#2912]
### 功能描述

![Uploading Snipaste_2024-04-20_15-34-07.png…]()

**Comment by Geeyun-JY3** [comment]
Your pictures was not uploaded successfully.

**Comment by Javahhhh** [comment]
![坐标](https://github.com/Snipaste/feedback/assets/112531492/bb810e75-86cc-44c6-bd93-3cf7b912de0b)
obtain screen XY coordinate value ，How did you obtain the code for the x and y coordinates? Can you tell me which line the source code is? thanks

**Comment by Geeyun-JY3** [comment]
Duplicate of #2362
