### ISSUE TITLE
建议添加一个设置选项，缩放时以鼠标为中心

### ISSUE THREAD

**Issue by Albertdjy** [Snipaste/feedback#2913]
### 功能描述

当我把截图固定在桌面上时，将鼠标移至截图后滑动滚轮缩放是以截图的左上角为缩放中心，这有时会导致鼠标脱离截图，从而误操作到其他界面如：浏览器、word等。希望添加一个选项使用户能选择缩放时以鼠标为中心或以截图左上角为中心。

**Comment by foreveruand** [comment]
![Snipaste_2024-04-20_16-20-25](https://github.com/Snipaste/feedback/assets/43624948/dc349661-417e-4430-8548-4e0c8f126e88)

**Comment by Geeyun-JY3** [comment]
如上所述，已有这个设置项，就在`贴图` > `行为`下。

**Comment by Geeyun-JY3** [comment]
Duplicate of #277

**Comment by Albertdjy** [comment]
谢谢
