### ISSUE TITLE
支持截屏翻译功能

### ISSUE THREAD

**Issue by Hfy-xxx** [Snipaste/feedback#2914]
### 功能描述

请问是否可以通过图片识别文字或其他方式来翻译图片中的文本，实现截图后通过在图片的某个位置弹框的方式来显示翻译后的结果？
这功能省去了手动将图片转换为文字，然后通过翻译软件翻译的步骤，省去了一步操作

**Comment by Geeyun-JY3** [comment]
Duplicate of #188
