### ISSUE TITLE
kubuntu22.04下截图后会自动截一张全屏图且无法退出，只能重启才可以解决

### ISSUE THREAD

**Issue by willre** [Snipaste/feedback#2916]
### 发生了什么？

操作系统： Kubuntu 22.04
KDE Plasma 版本： 5.24.7
KDE 程序框架版本： 5.92.0
Qt 版本： 5.15.3
内核版本： 6.5.0-28-generic (64-位)
图形平台： X11
处理器： 20 × 12th Gen Intel® Core™ i7-12700H
内存： 30.5 GiB 内存
图形处理器： NVIDIA RTX A2000 8GB Laptop GPU/PCIe/SSE2

程序版本: 2.8.9-Beta (2024.01.08) for Linux

问题： 截图（第一张图）后 会自动再次做一下全屏截图（第二张图）， 第一张图可正常操作且可退出，第二张则无法操作，鼠标右键点击后无菜单出现
![Uploading 05.png…]()

### 运行平台

Linux

### 软件版本

2.8.9-Beta (2024.01.08) for Linux

**Comment by liulex** [comment]
试试刚发布的 2.9 Beta for Linux 版，如果还有问题欢迎 reopen issue.
