### ISSUE TITLE
冷启动时，启动的命令参数不会被运行

### ISSUE THREAD

**Issue by jfcherng** [Snipaste/feedback#2918]
#### 问题描述

当后台没有 Snipaste 进程时，使用命令行截图的参数不起作用。

#### 问题复现步骤

1. 杀死 Snipaste 进程
1. 使用以下命令截图并保存

    ```bash
    Snipaste.exe snip --full -o out.png
    ```
1. Snipaste 启动了，但什么也没有发生

### 运行平台

Windows 桌面

### 软件版本

2.8.8

**Comment by liulex** [comment]
by design, [文档](https://docs.snipaste.com/zh-cn/command-line-options)第一句话就写了：
> Snipaste 支持使用命令行选项进行功能调用，但除了带 * 标记的选项（如 --config）外，**其他选项只在 Snipaste 启动后才有效。**
