### ISSUE TITLE
Do Snipaste support Ubuntu18.04?

### ISSUE THREAD

**Issue by Willis814** [Snipaste/feedback#2925]
### 问题描述

When I try to Open the Snipaste on Ubuntu，it ocurred error:

./Snipaste-2.9-Beta2-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./Snipaste-2.9-Beta2-x86_64.AppImage)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./Snipaste-2.9-Beta2-x86_64.AppImage)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Snipasm776FG/usr/bin/../lib/libQt6Widgets.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_Snipasm776FG/usr/bin/../lib/libQt6Widgets.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /tmp/.mount_Snipasm776FG/usr/bin/../lib/libQt6Widgets.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Snipasm776FG/usr/bin/../lib/libQt6Multimedia.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Snipasm776FG/usr/bin/../lib/libQt6OpenGL.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Snipasm776FG/usr/bin/../lib/libQt6Gui.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_Snipasm776FG/usr/bin/../lib/libQt6Gui.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /tmp/.mount_Snipasm776FG/usr/bin/../lib/libQt6Gui.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /tmp/.mount_Snipasm776FG/usr/bin/../lib/libQt6Xml.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_Snipasm776FG/usr/bin/../lib/libQt6Xml.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Snipasm776FG/usr/bin/../lib/libQt6Core.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /tmp/.mount_Snipasm776FG/usr/bin/../lib/libQt6Core.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_Snipasm776FG/usr/bin/../lib/libQt6Core.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_Snipasm776FG/usr/bin/../lib/libQt6Core.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Snipasm776FG/usr/bin/../lib/libpulse.so.0)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_Snipasm776FG/usr/bin/../lib/libglib-2.0.so.0)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Snipasm776FG/usr/bin/../lib/libpulsecommon-13.99.so)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_Snipasm776FG/usr/bin/../lib/libsystemd.so.0)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /tmp/.mount_Snipasm776FG/usr/bin/../lib/libsystemd.so.0)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Snipasm776FG/usr/bin/../lib/libsndfile.so.1)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Snipasm776FG/usr/bin/../lib/libFLAC.so.8)

The versions of the GNU C Library (GLIBC) and C++ Standard Library (libstdc++) on my system do not meet the requirements of Snipaste AppImage.

### 运行平台

Linux

### 软件版本

v2.9-beta2

**Comment by liulex** [comment]
No, Ubuntu 18.04 is not supported.

**Comment by 1053912923** [comment]
升级gcc版本，升级libc即可，已经解决
