### ISSUE TITLE
[Arch Linux + Plasma 6.0.4  + wayland ]多屏幕，副屏如果最低位置比主屏幕低，低出的部分截图时无法选区

### ISSUE THREAD

**Issue by daringwalker** [Snipaste/feedback#2927]
### 发生了什么？

显示器排列如下：
![图片](https://github.com/Snipaste/feedback/assets/4189740/a2d65b15-06d3-43ab-8ba5-1d0c5361c715)

左侧是副屏(3840x2560)，顺时针旋转90度，右侧是主屏幕(3840x2160)，缩放皆为175%，使用Snipaste截图时，在副屏幕的选区只能选择与主屏幕相接的最低位置的上方的区域，下方的区域无法选择

如下图示例，绿色框内区域是可选区域，红框内是无法选区的区域
![图片](https://github.com/Snipaste/feedback/assets/4189740/7ae49b20-8d68-44d5-a63b-8985371597c2)

### 运行平台

Linux

### 软件版本

2.9-Beta2 (2024.04.27) for Linux

**Comment by liulex** [comment]
2.9.2 Beta 已修复。
