### ISSUE TITLE
win11中 虚拟桌面功能消失

### ISSUE THREAD

**Issue by BiHong-Yang** [Snipaste/feedback#2931]
### 发生了什么？

我使用的是专业版，这里面无论勾不勾选虚拟桌面功能，都无法把贴图和虚拟桌面绑定
![image](https://github.com/Snipaste/feedback/assets/61420495/8cea4b87-e348-414c-8fda-221b7c02e3c8)
而且右键图片也不会出现虚拟桌面相关的功能
![image](https://github.com/Snipaste/feedback/assets/61420495/bc979030-0914-4af7-ada0-2413c1058b6a)
Windows如下为：
23H2 OS build 22631.3527
![image](https://github.com/Snipaste/feedback/assets/61420495/0a67b252-7949-41f5-8b02-c2c2975f50d0)

### 运行平台

微软商店, Windows 桌面

### 软件版本

v2.9

**Comment by liulex** [comment]
2.9.1 会支持 23H2 的虚拟桌面。
