### ISSUE TITLE
求增加一个非常实用的功能

### ISSUE THREAD

**Issue by haiyuanbo** [Snipaste/feedback#2937]
### 功能描述

非常实用的功能：截了多个图之后，按F3显示出贴图，这时要是能设置快捷键切换上张贴图和下张贴图就完美了，查了好多视频都没有这个功能，麻烦大神增加这个快捷键功能，感谢了

**Comment by Geeyun-JY3** [comment]
#556、#1252、#1408

**Comment by Geeyun-JY3** [comment]
Duplicate of #556
