### ISSUE TITLE
Inconsistent behavior with Snip and copy on multi monitors

### ISSUE THREAD

**Issue by tsengf** [Snipaste/feedback#2940]
### Problem Description

Hi, I have F10 bound to "Snip and copy". When I press F10, I can snip a window and generate a screen capture with a single click of my mouse. If I press F10, move my cursor to another monitor, then move the cursor back to the original monitor, and I click a window to snip, I have to then double click the on the snipped window to generate the screen capture. Is it possible to make this behavior consistent when using multi monitors?

### Platform

macOS

### Version

2.9-Beta

**Comment by liulex** [comment]
Thanks for reporting! It will be fixed in the next release.
