### ISSUE TITLE
OpenSSL libs included in latest MS Store package reportedly vulnerable, deprecated v1.1.1

### ISSUE THREAD

**Issue by MfMpEng** [Snipaste/feedback#2946]
### What happened?

libcrypto-1_1-x64.dll
libssl-1_1-x64.dll

are deprecated by openSSL authors in lieu of version 3.3.3. Trusted updated precompiled ported c binaries are available via the openssl official site wiki. If these are an inclusion from the QT framework and not included directly by snipaste project, please disregard I'll take this issue upstream.

### Platform

Microsoft Store

### Version

Name="45479liulios.17062D84F7C46" ProcessorArchitecture="x64" Publisher="CN=B80E3F07-3BEE-46F7-9B4C-A2E23B97D30E" Version="2.9.1.0"

**Comment by liulex** [comment]
Thanks for reminding. I will upgrade to OpenSSL 3.3.0 in the next release.

**Comment by MfMpEng** [comment]
Thanks, Le! Great software :)

**Comment by liulex** [comment]
Fixed in 2.9.2 Beta.
