### ISSUE TITLE
Chrome无法根据网页排版自动选择截图区域，但firefxo可以

### ISSUE THREAD

**Issue by lxr760** [Snipaste/feedback#2950]
### 发生了什么？

Chrome无法根据网页排版自动选择截图区域，但firefxo可以
如图在ffirefox里截图，软件可以自动框选某个小区域，但是chrome里不能，必须自己手动选择截图区域的大小

![image](https://github.com/Snipaste/feedback/assets/8476457/520b57f0-2b94-4cfe-bbfe-82bcf99d8588)

### 运行平台

Windows 桌面

### 软件版本

2.9.1

**Comment by Geeyun-JY3** [comment]
请认真阅读文档：https://docs.snipaste.com/zh-cn/troubleshooting?id=截图时无法自动选取浏览器窗口的页面元素
