### ISSUE TITLE
2.9.1无法放大，但2.9.0可以

### ISSUE THREAD

**Issue by cloud888** [Snipaste/feedback#2951]
### 发生了什么？

在首选项里：控制：鼠标：贴图缩放，改为：ctrl+无+滑鼠滚轮或+/-
奇妙的的是，2.9.1，贴图，不能用此方法，放大或缩小，但
2.9.0可以！

### 运行平台

Windows 桌面

### 软件版本

2.9.1

**Comment by liulex** [comment]
无法复现。

**Comment by cloud888** [comment]
我录了一段视频，重现这问题！
https://62drop.co/433044

**Comment by liulex** [comment]
你应该是还改动了这个选项：
![image](https://github.com/Snipaste/feedback/assets/2010459/37965813-cf6e-4279-9f47-72d639ba0d4e)

两处选项确实重复了，我会在下个版本把图中的选项去掉。

**Comment by cloud888** [comment]
对耶，我真的改到了，你说的选项，改回之后，果然正常了

顺便，建议一个功能
Windows
在单纯，按Print Screen时，是抓整个画面
但加按Alt时，即：Alt+Print Screen，就是抓目前选择的窗口！

因此在此建议
Snipaste
没按alt之前，截屏为普通截屏，例如我用：Print Screen
但加按alt之后，启动：自动检测窗口，例如可用：alt+Print Screen
但放开alt之后，单纯截屏，又回到，没有启动：自动检测窗口
