### ISSUE TITLE
在deepin linux v23 RC上托盘区域右键菜单快速闪一下后消失

### ISSUE THREAD

**Issue by winter110** [Snipaste/feedback#2952]
### 发生了什么？

系统版本：deepin linux v23 RC
软件版本：v2.9-Beta2
现象：双击软件后可以正常运行，截图功能也正常，可以通过右键正常打开菜单，但是退出软件后再重新打开软件后，在系统右下角托盘区域的snipaste图标上右键打开的弹出式菜单会快速闪一下就消失了，每次右键菜单都是闪一下就消失。

### 运行平台

Linux

### 软件版本

v2.9-beta2

**Comment by everyx** [comment]
gnome 使用 AppIndicator and KStatusNotiferItem support 托盘插件也是有时候用的了右键，有时候又不行，不知道为什么

**Comment by linzyjx** [comment]
Ubuntu 24也有类似问题

**Comment by liulex** [comment]
2.9.2 Beta 已修复。
