### ISSUE TITLE
箭头突然变的这么细，请问在哪里可以设置回来？

### ISSUE THREAD

**Issue by MattCraftsCode** [Snipaste/feedback#2953]
### 问题描述

箭头突然变的这么细，请问在哪里可以设置的粗一些？
![image](https://github.com/Snipaste/feedback/assets/5785421/2dda8ccd-1d41-4fcb-9e00-468c26bd4bc6)

### 运行平台

macOS

### 软件版本

2.9-beta

**Comment by Geeyun-JY3** [comment]
光标悬停在工具条箭头菜单左下角，滚动鼠标滚轮即可调节粗细：
![image](https://github.com/Snipaste/feedback/assets/49396421/e376b630-7846-4a27-9777-1fa19ead2621)
