### ISSUE TITLE
How do i get rid of a snip that has gone outside of the screen

### ISSUE THREAD

**Issue by sunnwydays** [Snipaste/feedback#2954]
### Problem Description

when i group some images together with ctrl, and drag them to the edge of the screen, sometimes some images are outside of the screen. then i accidentally click just one of the images making them no longer grouped, so i can't access the image outside of the screen. 
is there a way to access it again or at least delete it (like delete all snips on screen or something)?

### Platform

Microsoft Store

### Version

2.9.1

**Comment by liulex** [comment]
Two ways:
1. Click one of the images, then Press Ctrl+A. All images will be selected.
2. Press the 'Paste image' hotkey (default F3) a few times, images outside the screen will be moved back to the screen.
