### ISSUE TITLE
Customize/Change F1, F3, F5, etc. Hotkeys

### ISSUE THREAD

**Issue by SchaedlerYescoAdmin** [Snipaste/feedback#2955]
### Feature Description

I use a terminal-based program, which uses the F keys for navigation. If I can't customize/change the F key hotkeys in snipaste, I can't use it because it will take a screenshot every time I'm trying to open a menu in this terminal-based program.

**Comment by Geeyun-JY3** [comment]
Actually, you can customize the global hotkeys in Preferences > Control > Global Hotkeys:
![image](https://github.com/Snipaste/feedback/assets/49396421/ef55d1c9-77d7-4a0e-aa4b-eb87bedd15b9)
