### ISSUE TITLE
自定义复制到剪贴板的图片格式为JPG

### ISSUE THREAD

**Issue by youthlql** [Snipaste/feedback#2960]
### 功能描述

1.当前只支持保存图片时，输出为png格式
2.在做笔记的场景下，截完图保存到粘贴板的场景更为常见，但是当前粘贴板默认输出png，无法自定义为jpg。图像大小基本差了一倍，显示质量肉眼看并未差多少，这对于语雀，博客等云笔记场景非常耗费流量和存储。
3.这个同样的需求，我在issue里搜索到了4个，最早是2017年提出的，最晚是2023年，不知道出于什么顾虑迟迟不推出这个功能呢？
![image](https://github.com/Snipaste/feedback/assets/49017153/75eeaf31-6737-4ac1-8cb6-d1ed6e71532f)

**Comment by Geeyun-JY3** [comment]
Duplicate of #2806
