### ISSUE TITLE
建议贴图新增“磁吸”功能

### ISSUE THREAD

**Issue by zhiqiang94** [Snipaste/feedback#2963]
### 功能描述

日常在使用中，经常遇到需要合并贴图的时候。
我都是手动将贴图放到一起再进行截图的操作，但是这样会出现部分小问题。
1、我需要将所有贴图移动到一个背景为纯色或者未泄露我电脑其他信息的位置
2、贴图与贴图直接存在不同的间隙，看起来很难受
3、有时候几个贴图的尺寸比较大，超过了电脑屏幕，只能将贴图缩小，但缩小后再截图，内容因为太小看不清或看不见

建议：
贴图加一个磁吸功能，拖拽到两者边框相距正负N个像素的时候 将两张贴图的间距设置为0，还可以磁吸之后 当磁吸的贴图数量大等于2的时候 在右键菜单中新增一个“合并贴图”的功能，点击后将贴图合并成一张贴图

**Comment by Geeyun-JY3** [comment]
有没有一种可能，早就有你要的这个所谓「磁吸」功能了：https://docs.snipaste.com/zh-cn/advanced-tips?id=%e5%af%b9%e9%bd%90%e8%b4%b4%e5%9b%be%e7%aa%97%e5%8f%a3%e5%88%b0%e5%85%b6%e4%bb%96%e8%b4%b4%e5%9b%be%e6%88%96%e5%85%b6%e4%bb%96%e7%a8%8b%e5%ba%8f%e7%aa%97%e5%8f%a3

你都在 #45 下评论了还重复提贴图合并功能干嘛。

**Comment by Geeyun-JY3** [comment]
Duplicate of #45
