### ISSUE TITLE
希望mac版添加打开本地图片的功能

### ISSUE THREAD

**Issue by nonozone** [Snipaste/feedback#2964]
### 功能描述

macOS下，少有免费的简单图片编辑的软件，比如简单的裁切，文字标注，弄来弄去，感觉还不如snipaste截图后那种简单标注来的快，来的的方便，希望可以有这个功能，谢谢。

**Comment by liulex** [comment]
复制图片文件 -> 按贴图快捷键。

**Comment by nonozone** [comment]
多谢多谢
