### ISSUE TITLE
snipaste不跟随鼠标响应

### ISSUE THREAD

**Issue by GrahLnn** [Snipaste/feedback#2966]
### 发生了什么？

当启动截屏的时候，放大器只指向启动截屏时的光标的像素点，不显示捕捉框，也不跟随光标，在我另一台设备（平台一致）也出现同样问题，当出现此现象后点击任意位置可以取消这个放大器，但此时win键与snipaste截屏快捷键失效，需按下esc后才可用，多次重新启动程序可以恢复

不知道如何复现

![77fdd47ef7547842c88598d96150a2dc_720](https://github.com/Snipaste/feedback/assets/67181515/528c8baa-42f1-4e3e-9707-1cbafd06d36e)

### 运行平台

微软商店

### 软件版本

v2.9.1

**Comment by liulex** [comment]
用了 MyDockFinder?

**Comment by GrahLnn** [comment]
啊，是的，跟这个程序有冲突是吗

**Comment by liulex** [comment]
应该是，但我装了也没复现出来，你可以帮忙试一下是开了 MyDockFinder 的哪个选项之后就有问题。

**Comment by GrahLnn** [comment]
找到了，测试了多次，根据录屏的步骤可以稳定复现这个现象的开启和关闭

https://github.com/Snipaste/feedback/assets/67181515/e82efe3b-4776-4d6f-9b4b-d556257d1ade

**Comment by liulex** [comment]
谢谢！不过跟随着你的步骤，我这边还是没能复现...
不过你应该可以在这里将 Snipaste 添加到禁止列表来解决这个问题：
![image](https://github.com/Snipaste/feedback/assets/2010459/91ca1217-a173-4d1f-982a-07d7731980ee)

**Comment by GrahLnn** [comment]
好的，感谢

**Comment by liulex** [comment]
提供下微软帐号邮箱到 <snipaste.app@gmail.com>? 我发个测试版你试一下。
