### ISSUE TITLE
快捷键'C'复制颜色问题

### ISSUE THREAD

**Issue by QB61113** [Snipaste/feedback#2967]
### 联系方式

qb61113@qq.com

### 发生了什么？

内置快捷键'C'被标记为复制颜色，导致编辑图片时文字编辑无法打出'C'的拼音。而且按下'C'也没有复制出颜色值。不知道是不是我一个人的问题

### 运行平台

Windows 桌面

### 软件版本

2.8.3 Beta

**Comment by QB61113** [comment]
【这是一条自动回复的邮件】您好，已经收到您的邮件，感谢您的来信！
***@***.***   网站：https://baishitongpro.cn/微信公众号：只为早日退休微信小程序：只为早日退休

**Comment by Geeyun-JY3** [comment]
先试试这个行不行？
https://github.com/Snipaste/feedback/issues/640#issuecomment-346732910
https://github.com/Snipaste/feedback/wiki/%E9%AB%98%E7%BA%A7%E8%AE%BE%E7%BD%AE/d69cbd063f8d669ceefe4a7d498f2e0a4126406b#snip

**Comment by QB61113** [comment]
修改了还是不行，但是不排除我的电脑是被远程控制导致的原因，稍后我再研究一下，谢谢您的回复。



祝好！

老企鹅
***@***.***     
网站：https://baishitongpro.cn/
微信公众号：只为早日退休
微信小程序：只为早日退休
 
发件人： Geeyun-JY3
发送时间： 2024-06-03 12:36
收件人： Snipaste/feedback
抄送： QB61113; Author
主题： Re: [Snipaste/feedback] 快捷键'C'复制颜色问题 (Issue #2967)
先试试这个行不行？
#640 (comment)
https://github.com/Snipaste/feedback/wiki/%E9%AB%98%E7%BA%A7%E8%AE%BE%E7%BD%AE/d69cbd063f8d669ceefe4a7d498f2e0a4126406b#snip

**Comment by Geeyun-JY3** [comment]
远程就应该是这个解决方法：#2078、#2254、#2762
你确定的你设置方法是跟着文档来的吗：https://github.com/Snipaste/feedback/wiki/%E9%AB%98%E7%BA%A7%E8%AE%BE%E7%BD%AE/d69cbd063f8d669ceefe4a7d498f2e0a4126406b#设置方法

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/640#issuecomment-346732910 的配置项已经被删掉了。
对于最新版可以取消勾选这里：
![image](https://github.com/Snipaste/feedback/assets/2010459/405d144d-54c8-44ad-ba09-5a67302ace12)

**Comment by QB61113** [comment]
按照这个步骤解决了，谢谢



祝好！
 
发件人： Le Liu
发送时间： 2024-06-10 23:13
收件人： Snipaste/feedback
抄送： QB61113; Author
主题： Re: [Snipaste/feedback] 快捷键'C'复制颜色问题 (Issue #2967)
#640 (comment) 的配置项已经被删掉了。
对于最新版可以取消勾选这里：
image.png (view on web)
