### ISSUE TITLE
[Feature] 在截图对话中，【工具】支持自定义快捷键？

### ISSUE THREAD

**Issue by xianghongai** [Snipaste/feedback#2969]
### 功能描述

| Description | CN | Key |
|--------|-------|----|
| Pencil | 钢笔 | `P` |
| Line | 线条 | `L` |
| Arrow | 箭头 | `A` |
| Selection | 选框 | `S` |
| Rectangle | 矩形 | `R` |
| Circle | 圆形 | `C` |
| Highlighter | 荧光笔 (半透明画笔，边颗料状模糊) | `H` |
| Number | 数字序号 | `N` |
| Mosaic | 马赛克 | `M` |

**Comment by Geeyun-JY3** [comment]
请善用搜索：#106、<https://github.com/Snipaste/feedback/issues/492#issuecomment-307675232>、#664
#1859

**Comment by Geeyun-JY3** [comment]
Duplicate of #1859
