### ISSUE TITLE
贴图模式下无法记忆各种工具的颜色和粗细

### ISSUE THREAD

**Issue by andyf1111** [Snipaste/feedback#2973]
### 【BUG】贴图模式下无法记忆各种工具的颜色和粗细
描述：复制图片文件然后F3进入贴图模式下，调整了工具的颜色粗细等参数后保存不下来，只有截图模式下的调整才能有效保留
### 【功能请求】希望支持文本框调节宽度，避免长文本手动换行
关联：#515 #558 #2200
描述：长文本手动换行太麻烦了，可以考虑文本框默认为图片最大宽度，手动可以调整宽度，高度自适应

## 运行平台

微软商店

## 软件版本

PRO 2.9.1

**Comment by Geeyun-JY3** [comment]
Duplicate of https://github.com/Snipaste/feedback/issues/1576#issuecomment-648137710
