### ISSUE TITLE
希望添加多桌面支持

### ISSUE THREAD

**Issue by ling921** [Snipaste/feedback#2976]
### 功能描述

目前贴图会在多桌面共享，即一个桌面上贴的图，在另一个桌面上依然存在

希望添加一个选项，可以使得贴图不在多个桌面之间共享

**ps**: 使用快捷键 `Win + Tab` 激活多桌面, `Win + Ctrl + ←` 和 `Win + Ctrl + →` 快速切换桌面

**Comment by Geeyun-JY3** [comment]
请善用搜索，需要专业版：https://github.com/Snipaste/feedback/issues/2664#issuecomment-1707501501

**Comment by Geeyun-JY3** [comment]
Duplicate of #328
