### ISSUE TITLE
 /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found 

### ISSUE THREAD

**Issue by winterxx** [Snipaste/feedback#2978]
### 问题描述

环境：ubuntu18.04 gcc version 7.5.0
./Snipaste-2.9-Beta2-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./Snipaste-2.9-Beta2-x86_64.AppImage)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./Snipaste-2.9-Beta2-x86_64.AppImage)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_SnipaskwpAEx/usr/bin/../lib/libQt6Widgets.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_SnipaskwpAEx/usr/bin/../lib/libQt6Widgets.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /tmp/.mount_SnipaskwpAEx/usr/bin/../lib/libQt6Widgets.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_SnipaskwpAEx/usr/bin/../lib/libQt6Multimedia.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_SnipaskwpAEx/usr/bin/../lib/libQt6OpenGL.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_SnipaskwpAEx/usr/bin/../lib/libQt6Gui.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_SnipaskwpAEx/usr/bin/../lib/libQt6Gui.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /tmp/.mount_SnipaskwpAEx/usr/bin/../lib/libQt6Gui.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /tmp/.mount_SnipaskwpAEx/usr/bin/../lib/libQt6Xml.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_SnipaskwpAEx/usr/bin/../lib/libQt6Xml.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_SnipaskwpAEx/usr/bin/../lib/libQt6Core.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /tmp/.mount_SnipaskwpAEx/usr/bin/../lib/libQt6Core.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_SnipaskwpAEx/usr/bin/../lib/libQt6Core.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_SnipaskwpAEx/usr/bin/../lib/libQt6Core.so.6)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_SnipaskwpAEx/usr/bin/../lib/libpulse.so.0)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_SnipaskwpAEx/usr/bin/../lib/libglib-2.0.so.0)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_SnipaskwpAEx/usr/bin/../lib/libpulsecommon-13.99.so)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_SnipaskwpAEx/usr/bin/../lib/libsystemd.so.0)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /tmp/.mount_SnipaskwpAEx/usr/bin/../lib/libsystemd.so.0)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_SnipaskwpAEx/usr/bin/../lib/libsndfile.so.1)
./Snipaste-2.9-Beta2-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_SnipaskwpAEx/usr/bin/../lib/libFLAC.so.8)

### 运行平台

Linux

### 软件版本

Snipaste-2.9-Beta2-x86_64.AppImage

**Comment by jiekeqiong** [comment]
Same question, can't lower versions of Ubuntu use this software?

**Comment by winterxx** [comment]
Is there no compatibility with lower versions?

**Comment by only-wen** [comment]
same question, same ubuntu 18.04, hope it can be solved

**Comment by liulex** [comment]
Sorry, no plan for compatibility with Ubuntu 18.04.
