### ISSUE TITLE
Arch Linux下配置文件无法持久化

### ISSUE THREAD

**Issue by HinataKato** [Snipaste/feedback#2979]
### 发生了什么？

配置选项后 退出并重新启动应用/使用重新启动选项 后会导致config.ini被 恢复默认配置/被清除

### 运行平台

Linux

### 软件版本

2.9-Beta2

**Comment by SakuraPuare** [comment]
same issue

发现是软件每次打开在读取完配置文件后，会直接清空 `config.ini`。但是每次配置更新是增量更新

不知道代码怎么写的

**Comment by SakuraPuare** [comment]
先把配置修改好，在把配置文件的写权限删掉能曲线救国

**Comment by FranklinCao** [comment]
一样的问题，只能先禁用 config.ini 的写权限

**Comment by SakuraPuare** [comment]
> 一样的问题，只能先禁用 config.ini 的写权限

禁用 config.ini 的写权限 会导致无法截图

看了下 log 好像是剪贴板的mime类型有问题

**Comment by jesHrz** [comment]
我禁用config.ini的写权限后，只是在snipaste启动的时候报一下错，但是不影响正常使用（截图+贴图）

**Comment by yueziii** [comment]
一样的问题，我禁用config.ini的写权限后，截图无法复制到剪贴板

**Comment by Bryan2333** [comment]
2.10.2仍然存在这个问题

**Comment by liulex** [comment]
同 https://github.com/Snipaste/feedback/issues/3129 ，会在下周发新版修复，谢谢各位反馈！
