### ISSUE TITLE
Win11 64 位 snipaste 无法打开

### ISSUE THREAD

**Issue by zwyyy456** [Snipaste/feedback#2986]
### What happened?

我是通过  `scoop install snipaste` 安装的 snipaste，打开 snipaste 时，鼠标会转一下圈，然后就没有任何反应，托盘处没有 snipaste 的图标；从官网下载 64 位的便携版也是一样的表现，只有官网下载的 32 位便携版能正常打开，托盘处会有 snipaste 的图标；

### Platform

Windows Desktop

### Version

1.16.2

**Comment by Geeyun-JY3** [comment]
Duplicate of #2174
