### ISSUE TITLE
邊框無法取消

### ISSUE THREAD

**Issue by kin30528** [Snipaste/feedback#2990]
### 联系方式

kin30528@gmail.com

### 发生了什么？

輸出選項的邊框陰影都沒打勾，但截圖會莫名出現白邊，請問該如何解決？
![♜ 1-1c 利用在插圖：研究人體](https://github.com/Snipaste/feedback/assets/121107652/65048800-8eec-4ea8-aae2-76392ba73efa)
![寰椎_4](https://github.com/Snipaste/feedback/assets/121107652/f2f0a670-2656-49f0-bdfc-20800d8d624d)

### 其他建議
1. 希望鎖定長寬比的按鈕能根據上次的使用情況自己開啟，不然每次截圖都要開啟一次🤣

最後謝謝您開發這款好用的軟件

### 运行平台

Windows 桌面

### 软件版本

2.9.1(2024.05.08) x64 微軟商店版

**Comment by liulex** [comment]
> 輸出選項的邊框陰影都沒打勾，但截圖會莫名出現白邊，請問該如何解決？

录个屏看看？

> 希望鎖定長寬比的按鈕能根據上次的使用情況自己開啟

好的，谢谢建议。

**Comment by kin30528** [comment]
> > 輸出選項的邊框陰影都沒打勾，但截圖會莫名出現白邊，請問該如何解決？
> 
> 錄個屏看看？從截圖來看就是輸出選項的陰影。還有一種情況是，即使輸出選項裡沒勾選邊框/陰影，如果在點選工具列的**複製按鈕**時，按住了 Ctrl 鍵，那麼截圖也會有邊框/陰影。
> 
> > 希望鎖定長寬比的按鈕能根據上次的使用情況自己開啟
> 
> 好的，謝謝建議。

不好意思太晚回覆了，突然邊框的問題已經好了，也不知道動到什麼，因此我先關閉問題，謝謝~
