### ISSUE TITLE
多块屏幕时，只能在主屏幕进行截图

### ISSUE THREAD

**Issue by yyq2215986391** [Snipaste/feedback#2993]
### 联系方式

2215986391@qq.com

### 发生了什么？

多块屏幕使用时，F1快捷键截图或点击图标进行截图只能在主屏幕区域进行截图，副屏则完全不能使用

### 运行平台

Windows 桌面

### 软件版本

2.9.1-Beta(2024.05.08) x64 Windows桌面版

**Comment by Geeyun-JY3** [comment]
#1732、#2646
