### ISSUE TITLE
希望能够添加OCR识别功能，这个功能对于网页内容提取具有非常大的意义，截屏的出现解决了画面分享的问题，但是分享不应仅仅是图片，文字分享也是不可获取的一部分，因此强烈建议添加OCR文字识别功能。

### ISSUE THREAD

**Issue by sunbirdhao** [Snipaste/feedback#2994]
### 功能描述

希望能够添加OCR识别功能，这个功能对于网页内容提取具有非常大的意义，截屏的出现解决了画面分享的问题，但是分享不应仅仅是图片，文字分享也是不可获取的一部分，因此强烈建议添加OCR文字识别功能。

**Comment by foreveruand** [comment]
提issue之前，能自己搜索一下吗。同一个东西翻来覆去开issue

**Comment by Geeyun-JY3** [comment]
Duplicate of #188
