### ISSUE TITLE
打开后内存就占用2.29g 合理吗

### ISSUE THREAD

**Issue by fanmingfei** [Snipaste/feedback#2999]
### 问题描述

<img width="712" alt="image" src="https://github.com/Snipaste/feedback/assets/4632277/10a099b6-4b8d-40dc-a47d-af5eb71c3378">

### 运行平台

macOS

### 软件版本

2.9.2 以及以前版本

**Comment by fanmingfei** [comment]
<img width="625" alt="image" src="https://github.com/Snipaste/feedback/assets/4632277/38bc53c7-fc2a-4f2e-9f46-3eed070bfa19">
已经占用4.56G了

**Comment by liulex** [comment]
有用贴图吗？重启 snipaste 还是这样吗？

**Comment by fanmingfei** [comment]
> 有用贴图吗？重启 snipaste 还是这样吗？

打开以后直接是2.26g。没有用贴图。 电脑也重启过

**Comment by liulex** [comment]
可以将 ~/.snipaste 这个目录打个包后将这个目录删掉，如果内存正常了，说明这个目录内的某个配置文件/历史记录造成的，届时希望能将这个压缩包发到 <snipaste.app@gmail.com> (发送前可以将压缩包内的 history/snip 文件夹删掉)。

**Comment by fanmingfei** [comment]
删除以后就好了，不过删除的时候压缩出了问题。。。没压缩成功 数据丢失了。

**Comment by fanmingfei** [comment]
下次可以直接换个名字。。。
