### ISSUE TITLE
贴图都无法拖动超过顶部，导致无法查看下半部分的图片细节

### ISSUE THREAD

**Issue by whtcgh** [Snipaste/feedback#3007]
### 发生了什么？

win11系统
所有图片都无法拖动超过顶部

<img width="1280" alt="Snipaste_2024-07-08_22-28-12" src="https://github.com/Snipaste/feedback/assets/24699872/2fa6625a-d208-451e-9888-141033b42ebc">

### 运行平台

Windows 桌面

### 软件版本

2.5.6-Beta

**Comment by whtcgh** [comment]
<img width="1280" alt="Snipaste_2024-07-08_22-28-12" src="https://github.com/Snipaste/feedback/assets/24699872/7addc6d1-0466-4e46-bc96-d3f3ded4b026">

**Comment by Geeyun-JY3** [comment]
https://docs.snipaste.com/zh-cn/faq

> 16. 贴图无法拖出屏幕上边界？
> 
>     需作如下设置：
> 
>     系统属性 - 高级 - 性能设置 - 视觉效果 - 勾选"拖动时显示窗口内容" - 确定

另外建议先升级至最新版。
