### ISSUE TITLE
在开启显示器HDR的情况下，会出现截图过度曝光的问题。

### ISSUE THREAD

**Issue by uncercid** [Snipaste/feedback#3008]
### 联系方式

wargaminglos05@gmail.com

### 发生了什么？

在浏览器模式下，只要进行截图操作。就会出现过度曝光。因为我开启了HDR。这个问题会导致截图异常不正确。曝光过度到了影响图像的程度。虽然偶尔也可以不发生曝光问题。但是我不理解这是为什么。就在按下ctrl+F1的时候，只要曝光问题复现。不需要把图像保存就会曝光。原理未知。
如果专业版没有此问题，我会考虑购买专业版，如果专业版有同样的问题，我不会购买专业版。

### 运行平台

Windows 桌面

### 软件版本

2.9.1

**Comment by Geeyun-JY3** [comment]
Duplicate of #1112
