### ISSUE TITLE
支持设置多个截图区域，在截图时可快速选择

### ISSUE THREAD

**Issue by goomoon** [Snipaste/feedback#3009]
### 功能描述

目前功能：

在截屏时，可以通过 R，快速将截屏区域设置为上次区域，但无法支持多个选择。

使用需求：
在学习过程中，视频里面的 ppt 和实际操作的截屏，需要的是2个不同的截屏区域，此时交叉截屏时，就没法复用截屏区域，导致截取出来的 ppt 无法对齐，很苦恼。

期望功能：

希望可以提前录制几个截屏区域，在截屏时可以通过不同按键快速复用对应的截屏区域。

**Comment by Geeyun-JY3** [comment]
你这个需求完全可以通过专业版的全局快捷键 与 命令行调用 绑定实现：[https://docs.snipaste.com/zh-cn/pro?id=b-更自由的定制化](https://docs.snipaste.com/zh-cn/pro?id=b-%E6%9B%B4%E8%87%AA%E7%94%B1%E7%9A%84%E5%AE%9A%E5%88%B6%E5%8C%96)
