### ISSUE TITLE
Mac 系统下如何设置截图后工具的快捷键

### ISSUE THREAD

**Issue by Thesoul20** [Snipaste/feedback#3010]
### 问题描述

在使用Snipaste 截图后，只能使用默认的截图工具快捷键，如CMD+1 画出来一个矩形。怎么样才能设置己选定区域后，使用不同截图工具的快捷键呢？

在Snipaste 的设置中，只能够查看内部快捷键（并不能够个性化设置），全局快捷键可以进行个性化设置，但是能够调整的幅度很小。
![image](https://github.com/Snipaste/feedback/assets/49742133/8faced4e-40ce-4ac0-88a9-d90f55dbed90)
![image](https://github.com/Snipaste/feedback/assets/49742133/446a32fd-8841-4ae3-96f8-2bb6dd13247c)

### 运行平台

macOS

### 软件版本

2.9.2Beta

**Comment by Geeyun-JY3** [comment]
Duplicate of #1859
