### ISSUE TITLE
需求:希望新增录屏功能

### ISSUE THREAD

**Issue by JasonsWang** [Snipaste/feedback#3014]
### 功能描述

建议新增录屏功能,可接受付费,目前截图使用的snipaste录屏使用的FastStone Capture,两个工具来回用,不方便.
希望可以支持轻量化录屏功能,本人可接受的价格20-50之间.希望作者可以考虑一下.
录屏:
1.自定义区域录屏
2.整体窗口录屏(不包括任务栏)
3.整个桌面

**Comment by Geeyun-JY3** [comment]
Duplicate of #2130
