### ISSUE TITLE
托盘图标左键与中键冲突

### ISSUE THREAD

**Issue by arst1010** [Snipaste/feedback#3022]
### 问题描述

在托盘图标中，点击中键与点击左键的反馈结果一致。通过首选项修改左键点击后，确认为左键点击影响中键点击的结果，而首选项中的中键点击修改后没有起到相应作用或者发生改变。以上测试过程鼠标左键、中键没有修改。想请问一下如何处理来该解决？
![image](https://github.com/user-attachments/assets/0396c739-dd5a-4353-9089-64bf0d1afc18)
![image](https://github.com/user-attachments/assets/529f6b76-c736-4ca9-9127-834abab903ec)

### 运行平台

Windows 桌面

### 软件版本

2.9.2

**Comment by liulex** [comment]
这个是 Windows 11 系统的 bug，听说在 Windows 11 24h2 26100 以上版本已修复。

**Comment by arst1010** [comment]
试了下还真是。:>
