### ISSUE TITLE
输出到剪贴板中的图片质量应该保持与输出文件的质量一样或可以单独设置质量

### ISSUE THREAD

**Issue by xucongli1989** [Snipaste/feedback#3023]
### 发生了什么？

1、输出至文件的图片质量可以在下方截图的位置中修改设置
2、输出至剪贴板中的图片质量是原始质量，也就是剪贴板中的内容未经压缩

考虑到很多场景需要直接粘贴剪贴板中的内容至各个应用软件中，因此要么将剪贴板中的图片质量与下方设置中的质量一样，要么允许分开设置质量。

![image](https://github.com/user-attachments/assets/80b06745-1577-46ea-b636-8aa49055e187)

![image](https://github.com/user-attachments/assets/c9cafb6e-5489-4bb0-a07c-97177163bdd4)

### 运行平台

Windows 桌面

### 软件版本

2.9.2

**Comment by Geeyun-JY3** [comment]
Duplicate of #2171
