### ISSUE TITLE
SSL certificate outdated

### ISSUE THREAD

**Issue by TheSnowfield** [Snipaste/feedback#3027]
### 问题描述

![image](https://github.com/user-attachments/assets/378c0c13-7472-4423-b254-bc25cc1a3c7b)
![image](https://github.com/user-attachments/assets/5bd17dba-d4a3-42a8-95d6-852e532c2ccb)

### 运行平台

Linux

### 软件版本

N/A

**Comment by liulex** [comment]
Fixed. Thanks for reporting!
