### ISSUE TITLE
功能请求：线条曲线

### ISSUE THREAD

**Issue by XHXIAIEIN** [Snipaste/feedback#3029]
### 功能描述

建议线条标注可以设置弯曲的线条，这样可以更好的应对不同的标注场景。

https://excalidraw.com/
![image](https://github.com/user-attachments/assets/f40d9230-4078-4c29-9bd4-81ff1a4c2724)

https://www.tldraw.com/
![image](https://github.com/user-attachments/assets/ce3bcb9a-5fe4-416f-b30b-75554aa8be08)

**Comment by Geeyun-JY3** [comment]
关联：#1513
