### ISSUE TITLE
改善触摸板使用操作

### ISSUE THREAD

**Issue by no-fish-in-pot** [Snipaste/feedback#3043]
### 功能描述

使用笔记本触摸板控制贴图时双指放大是修改透明度，上下滑动才是修改大小，这样并不方便，希望能优化笔记本触摸板的操作，使得双指放大即可放大贴图

**Comment by Geeyun-JY3** [comment]
Duplicate of #1263

**Comment by liulex** [comment]
要你的触摸板支持双指放大这个手势才行，Macbook 的 trackpad 支持这个手势，贴图可以双指放大缩小。
