### ISSUE TITLE
功能请求：比 PowerToys 更高效的窗口裁切

### ISSUE THREAD

**Issue by PaperStrike** [Snipaste/feedback#3046]
### 功能描述

[PowerToys 窗口裁切介绍](https://learn.microsoft.com/en-us/windows/powertoys/crop-and-lock)

非常适合把后台企微截个只有最近几条聊天的小窗，有消息瞟一眼就知道和自己有没有关系。（查看模式）
![image](https://github.com/user-attachments/assets/72cccfff-d0ca-4977-b1e8-5d6bc1a7ef8a)

查看模式（Thumbnail mode）就像一张动态贴图一样，但不支持 点击穿透，不支持半透明，不支持按住拖动（只能按顶部 tab），不支持锁比例缩放，这些 Snipaste 已经有的功能。

编辑模式（Reparent mode）兼容性很差，几乎不能用，Snipaste 大佬有时间的话也期望考虑支持下。不替换掉原窗口，仅在查看模式的基础上，把鼠标键盘事件传递过去，即可覆盖绝大多数场景，这样兼容性可能更好一些，功能表现上感觉也更符合 Snipaste 的定位。

**Comment by Geeyun-JY3** [comment]
可这与截图贴图没什么关系吧……

**Comment by PaperStrike** [comment]
> 可这与截图贴图没什么关系吧……

截和贴的操作统一放在一个软件里更符合直觉。Snipaste 局限在图里会不会有点可惜

**Comment by kabeep** [comment]
> > 可这与截图贴图没什么关系吧……
> 
> 截和贴的操作统一放在一个软件里更符合直觉。Snipaste 局限在图里会不会有点可惜

个人是非常抵制技术产品既要又要，计算器app里加短视频加金融那一套。

上链接了，去吧。
https://github.com/microsoft/PowerToys/issues/new/choose

**Comment by PaperStrike** [comment]
> 计算器app里加短视频加金融那一套

Snip + paste 翻译本来就是 截 + 贴，哪有扯那么远。

> 个人是非常抵制技术产品既要又要
> 上链接了，去吧。
> https://github.com/microsoft/PowerToys/issues/new/choose

你看 PowerToys 不就很像既要又要吗，所以我没在那提

---

没精力追踪这个建议，维护开发者肯定都已经看到了，没兴趣做就算了。
