### ISSUE TITLE
mac版本单击 鼠标左键 单击托盘图标 无法直接启动截屏

### ISSUE THREAD

**Issue by lemon-ustc** [Snipaste/feedback#3049]
### 问题描述

您好，之前一直在win上使用snipaste软件，体验极佳，单击底部托盘图标就能启动截图

最近在macbook上安装了snipaste，单击顶部托盘图标只会进入下拉菜单，并不能直接启动截图，使用不是很方便。不知是否是我设置的问题呢？
<img width="97" alt="截屏2024-09-07 12 24 15" src="https://github.com/user-attachments/assets/d4844871-4084-41dc-abb6-b41939cf8979">

### 运行平台

macOS

### 软件版本

2.9.2-Beta（2024.07.02）

**Comment by liulex** [comment]
是这样的，macOS 不支持单击图标触发截图。
