### ISSUE TITLE
Windows 10 開啟snipaste出現屏幕黑點

### ISSUE THREAD

**Issue by MoriartOMO** [Snipaste/feedback#3050]
### 联系方式

moriartaddress@gmail.com

### 发生了什么？

這個問題時不時發生, 主要是屏幕的左上方會有一個奇怪的黑點, 有時候是靠近中間上方有黑點, 一旦閉關snipaste後就會消失, 可以查看圖片(這次是靠中間有一個小黑點，我再附上一張是用紅框標出黑點的截圖）
![Snipaste_2024-09-08_12-37-40](https://github.com/user-attachments/assets/2e2315ba-d5ed-4424-bd88-b55200c58e29)
![Snipaste_2024-09-08_12-38-39](https://github.com/user-attachments/assets/b218ae81-8534-4946-883b-c0f1c709f3f8)

### 运行平台

Windows 桌面

### 软件版本

2.8.8-Beta (2023.09.25)

**Comment by Geeyun-JY3** [comment]
之前的相似反馈：#2981

**Comment by liulex** [comment]
就是你贴出来的很小的图片，双击就关闭了。
