### ISSUE TITLE
Ubuntu下超级截屏无法使用

### ISSUE THREAD

**Issue by whoiszzj** [Snipaste/feedback#3054]
### 发生了什么？

购买专业版后发现超级截屏无法使用，呈现为灰色状态。
![image](https://github.com/user-attachments/assets/45dc2846-1ed3-4dbe-9ce3-3620397da179)

### 运行平台

Linux

### 软件版本

v2.10 (Linux Pro version)

**Comment by liulex** [comment]
这是要被暂时还未适配，后续版本会尝试实现。

**Comment by liulex** [comment]
2.10.2 已支持。
