### ISSUE TITLE
無法啟動程式，電腦遺失 api-ms-win-core-path-l1-1-0.dll

### ISSUE THREAD

**Issue by windvane** [Snipaste/feedback#3055]
### 发生了什么？

啟動Snipaste.exe出現下圖錯誤。(Win 7 x64)
![2024-09-11_105946](https://github.com/user-attachments/assets/968b2ce3-9c8a-496d-9a02-64fb44b2e4f2)

### 运行平台

Windows 桌面

### 软件版本

2.10

**Comment by liulex** [comment]
谢谢反馈，近两天会发布新版解决这个问题。

**Comment by liulex** [comment]
2.10.1 已修复。
