### ISSUE TITLE
windows贴图不能移动到屏幕上边缘以外(图片上边缘不能超出屏幕)

### ISSUE THREAD

**Issue by iamqiz** [Snipaste/feedback#3056]
### 发生了什么？

贴图后,向上拖拽图片,使其上半部分超过屏幕上边缘,松开鼠标之后,贴图会自动调整,使图片上边缘不超出屏幕
和 https://github.com/Snipaste/feedback/issues/2836 差不多

### 运行平台

微软商店

### 软件版本

2.9.2 pro

**Comment by Geeyun-JY3** [comment]
请认真阅读文档：https://docs.snipaste.com/zh-cn/faq

> 16. 贴图无法拖出屏幕上边界？
> 
>     需作如下设置：
> 
>     - 系统属性 - 高级 - 性能设置 - 视觉效果 - 勾选"拖动时显示窗口内容" - 确定
> 
>       ![](https://i.v2ex.co/96N4D4hJ.png)

**Comment by iamqiz** [comment]
@Geeyun-JY3 谢谢!
