### ISSUE TITLE
开启默认标注为矩形，截图之后导致软件退出

### ISSUE THREAD

**Issue by d6ren** [Snipaste/feedback#3065]
### What happened?

开启默认标注为矩形，然后截图，点击工具栏中的矩形标注按钮来取消选择矩形标注工具，随后移动截图的选中区域，会导致软件崩溃退出。macOS 15。

### Platform

macOS

### Version

2.10

**Comment by liulex** [comment]
谢谢反馈，明天就发个版本修复。

**Comment by JC-Yang-wow** [comment]
so fast! 👍

**Comment by JC-Yang-wow** [comment]
> so fast! 👍

![image](https://github.com/user-attachments/assets/c3bcbba1-03e8-4c7f-994b-a7cd4ed6b35c)
