### ISSUE TITLE
截图时点击复制按钮并粘贴到其他软件时截图像素有偏移

### ISSUE THREAD

**Issue by wenq1217** [Snipaste/feedback#3069]
### 发生了什么？

截图时点击复制按钮并粘贴（Ctrl+V）到其他软件时（微信、QQ、Photoshop等），所选区域最右侧会有3像素宽的纵向区域自动被移到最左边；但使用Win+V开启剪贴板并双击粘贴则不会出现此问题。
下图最左侧的3像素宽的区域应当在图片的最右侧。

![微信图片_20240914171754](https://github.com/user-attachments/assets/26e78f43-ec1e-4ca5-b3d7-6bbe507fe4f7)

![QQ图片20240914172106](https://github.com/user-attachments/assets/6675271b-92ac-4679-879e-b14fda480ac7)

### 运行平台

微软商店，Windows 10

### 软件版本

2.9.2

**Comment by liulex** [comment]
2.10.2 已修复。
