### ISSUE TITLE
更新窗口的 Retrying... 等日志错误添加了超链接

### ISSUE THREAD

**Issue by muzimuzhi** [Snipaste/feedback#3070]
### 发生了什么？

在从 2.9.2-Beta 向 2.10.1 更新时，"Retrying...\nRedirecting..." 日志也添加了超链接，点击后跳转到 https://github.com/Snipaste/feedback/issues/3065 ，也即 2.10.1 更新日志里的第二个、也是最后一个链接。

![image](https://github.com/user-attachments/assets/fcd72cd8-03fd-4849-b487-9eab4aee3299)

### 运行平台

macOS

### 软件版本

2.9.2-Beta

**Comment by muzimuzhi** [comment]
（补充复现条件。问题可能已经修复，不过要等下一次升级时才能验证了）

在从 2.10.1 升到 2.10.2 时，我做了更多尝试，现在知道复现条件了：

1. 任意点击一个更新日志里的超链接，能看到刚点击的文字有虚线框。
<img width="600" alt="image" src="https://github.com/user-attachments/assets/a9fdf08d-9806-40ef-a6fe-2181e982d72f">

2. 从浏览器回到更新窗口，直接点 "Download updates" 按钮（此时如果点文本框空白处，虚线框会消失），能看到 "Retrying...\nRedirecting..." 的更新日志也加了超链接，点击后跳转到刚才打开的链接。
<img width="600" alt="image" src="https://github.com/user-attachments/assets/d44f32ec-fd4c-48a9-9313-193163356c82">

**Comment by liulex** [comment]
非常感谢，已复现，我试了下新版还有这问题。。

**Comment by liulex** [comment]
下个版本会修复，再次感谢帮忙复现！
