### ISSUE TITLE
请求增加截图区域切换时的动态效果关闭按钮

### ISSUE THREAD

**Issue by KangShengYu** [Snipaste/feedback#3074]
### 功能描述

激活 Pro 版前，切换截图区域时，自动识别的框不会有动态效果。激活 Pro 版后，切换截图区域时，自动识别的框会有提示窗口移动的动态效果，尝试不设置“平滑缩放”仍然有动态效果，希望增加关闭动态效果的按钮。

**Comment by Geeyun-JY3** [comment]
Duplicate of #3057
