### ISSUE TITLE
截图后标注，无法保存相应设置

### ISSUE THREAD

**Issue by ltanzyh** [Snipaste/feedback#3075]
### Feature Description

比方我常用的两个功能：

插入文本，每次需要重复找到相应字体及调节大小
荧光笔，每次会默认变成圆形，而我常用方形，颜色透明度也是每次要重调

不知道是不是我的配置有问题，还是默认功能如此？很困惑

**Comment by Geeyun-JY3** [comment]
勾选了首选项中的「自动备份」没有？

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/2631#issuecomment-1695821858

**Comment by ltanzyh** [comment]
> [#2631 (comment)](https://github.com/Snipaste/feedback/issues/2631#issuecomment-1695821858)

确实解决问题了，感谢，苦恼很久了，原来是这样，因为一直用的都是快捷键【截屏、复制并贴图】，所以没有发现解决方法。
