### ISSUE TITLE
希望可以有一个截图完后数据粘贴到本地文件夹（我很清楚截图后有一个保存的按钮）

### ISSUE THREAD

**Issue by imjohngu** [Snipaste/feedback#3080]
### 功能描述

我很清楚截图后有一个保存的按钮，可以选择目录保存，但是我有时候需要经常截图，每次保存都要选择目录，然后选择保存，如果目录深度过于多，操作步骤太多，也容易选错目录，
如果有一个复制之后，数据在内存中，在某一个目录 ctrl+v就将图片粘贴在本地，这样会更加方便很多
或者有一个一键将截图拖到目录也会很方便

**Comment by Geeyun-JY3** [comment]
请认真阅读文档，专业版有这功能：https://docs.snipaste.com/zh-cn/pro?id=其他
