### ISSUE TITLE
增加填充底色功能

### ISSUE THREAD

**Issue by XHXIAIEIN** [Snipaste/feedback#3083]
## 功能请求

我希望对标注截图添加 '聚光灯' 效果，帮助其他人将视线聚焦到我想要他关注的地方。

例如，在 Google 搜索页的帮助反馈中，就有这样一个简单的高亮标注、减淡背景的聚焦功能。

<img width="400" alt="Snipaste_2024-09-29_04-55-30" src="https://github.com/user-attachments/assets/af78e081-67a9-45e0-8617-3dd4bd9520fe">

<img width="400" alt="Snipaste_2024-09-29_04-53-56" src="https://github.com/user-attachments/assets/ede703a4-12cd-4ca0-88e9-81bac248b637">
  
<br><br>

在 FastStone 里，也有聚光灯工具。画出一个选区，保留其可见度。在其他的地方填充一个覆盖整个画面的，半透明的纯色块。还可以调整背景的亮度(变亮/变暗)，背景的模糊，背景去色(黑白), 边缘模糊。也非常方便

<img width="800" alt="Snipaste_2024-09-29_04-56-27" src="https://github.com/user-attachments/assets/cc8455ce-e657-4265-bc1e-3a3cf959ba80">

**Comment by Geeyun-JY3** [comment]
Duplicate of #2426
