### ISSUE TITLE
自定义截屏快捷键每次调用还需要手动点击一下“确定”

### ISSUE THREAD

**Issue by liyangzbx** [Snipaste/feedback#3084]
### 发生了什么？

如题，我定义了一个自定义截屏快捷键。
![image](https://github.com/user-attachments/assets/1d876115-71f7-4ce5-97a6-6d22ba182b06)
每次执行这个快捷键时都会弹出这个弹窗，需要我手动点击一下“确定”才会按照我设定的大小截屏。有没有办法跳过这个确定点击，直接调用快捷键就按照我已经预设的大小，位置截屏？
![image](https://github.com/user-attachments/assets/686c813d-9c19-48ab-917d-c1c319204eea)

### 运行平台

Windows 桌面

### 软件版本

2.9.1

**Comment by Geeyun-JY3** [comment]
当然有，专业版的全局快捷键 与 命令行调用 绑定：https://docs.snipaste.com/zh-cn/pro?id=b-更自由的定制化
