### ISSUE TITLE
能否添加一个应用识别功能

### ISSUE THREAD

**Issue by wstc1997** [Snipaste/feedback#3087]
### 功能描述

例如，F1在很多游戏中是功能快捷键，在运行游戏时，按F1会直接启动截图
能否添加一个功能，设置对应的应用程序，在设置后的应用程序启动时，自动禁用快捷键

**Comment by Geeyun-JY3** [comment]
请认真阅读文档，专业版有这功能：https://docs.snipaste.com/zh-cn/pro?id=b-更自由的定制化

> 此外，用户可以为每个快捷键指定“忽略程序列表”，支持模糊匹配。如上图所示，若活动窗口所属程序的文件名为 a.exe 或程序路径中包含 games 文件夹，该快捷键对应的命令不会生效。例如，用户可以将游戏程序的 exe 文件名填入，避免在游戏时误激活 Snipaste.
