### ISSUE TITLE
我在Chrome里面截图网页发现色彩过曝，而桌面、word等其他软件截图正常

### ISSUE THREAD

**Issue by wzhb** [Snipaste/feedback#3089]
### 发生了什么？

![Snipaste_2024-10-07_00-06-55](https://github.com/user-attachments/assets/95d821fd-69fd-408a-b25e-c4dbbb52968a)
zhe
这个是截图的画面

### 运行平台

Windows 桌面

### 软件版本

v2.10.2

**Comment by Geeyun-JY3** [comment]
Duplicate of #1112
