### ISSUE TITLE
希望能够在使用全局快捷键那里添加游戏模式，检测到是游戏状态时禁用一些快捷键 现在我玩战地系列，如果使用载具，F1~F4会被SNIPASTE占用，导致无法更换座位

### ISSUE THREAD

**Issue by FENBIANKELI** [Snipaste/feedback#3090]
### Feature Description

希望能够在使用全局快捷键那里添加游戏模式，检测到是游戏状态时禁用一些快捷键
现在我玩战地系列，如果使用载具，F1~F4会被SNIPASTE占用，导致无法更换座位

**Comment by Geeyun-JY3** [comment]
专业版有相关功能，忽略掉你玩的游戏就行了：https://docs.snipaste.com/zh-cn/pro?id=b-更自由的定制化


> 此外，用户可以为每个快捷键指定“忽略程序列表”，支持模糊匹配。如上图所示，若活动窗口所属程序的文件名为 a.exe 或程序路径中包含 games 文件夹，该快捷键对应的命令不会生效。例如，用户可以将游戏程序的 exe 文件名填入，避免在游戏时误激活 Snipaste.
