### ISSUE TITLE
能否提供文本提取功能

### ISSUE THREAD

**Issue by sinianluoye** [Snipaste/feedback#3091]
### 功能描述

现在我都是复制一下再扔到azure的OCR页面上的，有点麻烦

使用场景基本就是贴图一个文档里几个相关部分的时候处理起来会比较方便

![image](https://github.com/user-attachments/assets/63d1c8ad-b6fd-4522-ae12-6aae31e282c9)

现在的OCR模型做的好像都挺好的了，基本很快就能返回，而且返回的格式也很容易处理

**Comment by Geeyun-JY3** [comment]
Duplicate of #188
