### ISSUE TITLE
找半天没有找到类似win+printscreen/alt+printscreen的功能，想着可以用title命名更好，是还不支持吗？

### ISSUE THREAD

**Issue by atkdefender** [Snipaste/feedback#3092]
### 问题描述

Ctrl + Shift + S是在F1唤出截图之后才好使

### 运行平台

Windows 桌面

### 软件版本

2.10.2

**Comment by Geeyun-JY3** [comment]
类似 <kbd>Win</kbd>+<kbd>Print Screen</kbd> 的是指按下快捷键后截全屏并自动保存至指定文件夹，类似 <kbd>Alt</kbd>+<kbd>Print Screen</kbd> 的功能是指按下快捷键后截取当前活动窗口并复制至剪贴板，还有用窗口 title 命名，都完全可以通过专业版的全局快捷键 与 命令行调用 绑定实现：https://docs.snipaste.com/zh-cn/pro?id=b-更自由的定制化
