### ISSUE TITLE
Development progress of Snipaste 3 | Snipaste 3 开发进度

### ISSUE THREAD

**Issue by amaoo** [Snipaste/feedback#3093]
Hope the author updates the development progress of Snipaste 3 :dog:
期望作者更新下 Snipaste 3 的开发进度 :dog:

Snipaste 3 development progress:

- New Folder
- 1%
- 5%
- ...

---

Snipaste 3 开发进度:

- 新建文件夹
- 1%
- 5%
- ...

**Comment by Geeyun-JY3** [comment]
v2 桌面正式版才出来刚一个月，咋这么着急呢🌚

**Comment by amaoo** [comment]
> v2 桌面正式版才出来刚一个月，咋这么着急呢🌚

去年12月份就说要搞 3 了 😂

**Comment by Geeyun-JY3** [comment]
> 去年12月份就说要搞 3 了 😂

原文在这，自己阅读理解：https://github.com/Snipaste/feedback/issues/19#issuecomment-1846413616

2 之后肯定会有大版本更新，但 Snipaste v2 更新持续的时间跨度有目共睹，反正我是觉得你不用指望 3 很快能出来。
别忘了现在购买的专业版不包含大版本更新，在桌面专业版出来后没多久就搞大版本更新，你觉得刚买了桌面专业版的用户会怎么想呢？

**Comment by Geeyun-JY3** [comment]
Duplicate of #2750

**Comment by amaoo** [comment]
已经 2026 年了，v3 还没有影

**Comment by Dhy827** [comment]
别急，已经新建文件夹了

**Comment by styuanqn2022** [comment]
没事 不更新 都被隔壁PixPin抢走用户了
