### ISSUE TITLE
默认快捷键F1截屏，当使用鼠标拖拽截屏窗口以获得合适截屏大小，会退出截屏功能

### ISSUE THREAD

**Issue by invain1218** [Snipaste/feedback#3095]
### 问题描述

默认快捷键F1截屏，当使用鼠标拖拽截屏窗口以获得合适截屏大小，会退出截屏功能
更改快捷键之后，出现一样的问题，**不能使用鼠标拖动大小，否则截屏功能推出**
<span style="color: red;">但是，win+鼠标拖动是可以截屏成功的</span>

### 运行平台

Windows 桌面

### 软件版本

2.10.2 专业版

**Comment by Geeyun-JY3** [comment]
建议上个录屏，没看懂……

**Comment by liulex** [comment]
勾上这个呢？
![](https://github.com/user-attachments/assets/b9b1292e-1fea-4738-805d-a6406100e66b)

**Comment by invain1218** [comment]
勾选 忽略其他程序模拟的“复制”命令 之后 可以了！！！感谢🙇‍

> 勾上这个呢？ ![](https://private-user-images.githubusercontent.com/2010459/375218325-b9b1292e-1fea-4738-805d-a6406100e66b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MzU0MTMsIm5iZiI6MTcyODUzNTExMywicGF0aCI6Ii8yMDEwNDU5LzM3NTIxODMyNS1iOWIxMjkyZS0xZmVhLTQ3MzgtODA1ZC1hNjQwNjEwMGU2NmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTBUMDQzODMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzg0ZGYyOGNmZDAyOTQ3OGI4MzljY2Q1NmZlMmZiNWY2NWY0MTIyNmY1YmIyOTRkMjZjM2Y4YTIzMWE5ZGFmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.IsFJIYERJUzWMlWnLDYoO3gTzEjMPLX-BpnaEMJF5U8)

**Comment by liulex** [comment]
可以帮忙排查一下是哪个程序影响的吗？一般是屏幕取词软件。

**Comment by invain1218** [comment]
这个我启动Qtranslate导致的，不好意思，现在才回复
