### ISSUE TITLE
建议增加剪贴板画质设置功能

### ISSUE THREAD

**Issue by nlexer** [Snipaste/feedback#3096]
### 功能描述

很多用户经常截图后双击保存到剪贴板，然后直接在微信QQ等聊天工具中直接粘贴发送，但目前的版本双击后保存的是未压缩的图片，体积非常大，一张图片动辄十多MB，我现在的做法是截图的时候点右键另存之后再发生，体积会小很多，只有几百KB。希望能增加一个双击保存到剪贴板时的画质设定，能够双击后保存压缩的图片。

**Comment by Geeyun-JY3** [comment]
Duplicate of #2171
