### ISSUE TITLE
Color Picker only selects anchor color

### ISSUE THREAD

**Issue by ChrAlpha** [Snipaste/feedback#3100]
### 发生了什么？

Turn on "Preferences > Snip >Display > Show anchors"

And the color picker will only pick the color of anchor, which is quite unconvenient for manual border postioning.

https://github.com/user-attachments/assets/acf1e698-b0ee-483d-80ed-5118c0cd1c0f

Wanted behaviour: maybe similar to the case without showing anchors when anchor is actived/selected.

https://github.com/user-attachments/assets/37df880b-5dab-471e-b6c5-acf4cbabc08a

### 运行平台

Windows 桌面

### 软件版本

2.10.2

**Comment by Geeyun-JY3** [comment]
If I am not mistaken, anchors would not be shown in the magnifier when you turn off this option. When you turn on this option, anchors would still be shown in the magnifier in the case of your second video.
![image](https://github.com/user-attachments/assets/dc3f3185-1236-4165-9e71-244bbc74b9a2)

**Comment by ChrAlpha** [comment]
> If I am not mistaken, anchors would not be shown in the magnifier when you turn off this option. When you turn on this option, anchors would still be shown in the magnifier in the case of your second video. ![image](https://private-user-images.githubusercontent.com/49396421/377055278-dc3f3185-1236-4165-9e71-244bbc74b9a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMDI4NzQsIm5iZiI6MTcyOTMwMjU3NCwicGF0aCI6Ii80OTM5NjQyMS8zNzcwNTUyNzgtZGMzZjMxODUtMTIzNi00MTY1LTllNzEtMjQ0YmJjNzRiOWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDAxNDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZmQ4MzI5MDE3NjhjYjA5OTM5ZTJmZTY4NWUxYmYxMWJmYjU3ZDY0ZTQ2MTJkMmRkNTA1Y2VhMjg0YTYzZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mYGarNv9IqoSD9OC5lImEEtLIXZpa_j69_-gx5yDuso)

That's absolutely what I want. Thanks a lot!
