### ISSUE TITLE
win11多屏幕对应关系修改后，截图还在，但是看不到了

### ISSUE THREAD

**Issue by dawnset** [Snipaste/feedback#3102]
### 联系方式

dawnset@163.com

### 发生了什么？

win11多屏幕对应关系修改后，重新打开保存的分组，屏幕不存在了，而截图仍然在原来的位置，结果就都看不到了

### 运行平台

Windows 桌面

### 软件版本

1.16.2

**Comment by Geeyun-JY3** [comment]
https://github.com/Snipaste/feedback/issues/2616#issuecomment-1554646034
https://docs.snipaste.com/zh-cn/pro?id=专业版
> Snipaste 1.x 版将停留在 1.16.2，不再更新

**Comment by liulex** [comment]
再按几次贴图键，屏幕范围外的贴图会回到屏幕内。
