### ISSUE TITLE
希望加一个配置设置，关闭工具栏右侧三个点

### ISSUE THREAD

**Issue by wilsendd** [Snipaste/feedback#3105]
### 功能描述

希望加一个配置设置，关闭工具栏右侧三个点，容易误触
`output_options=off`
<img width="457" alt="2024-10-18_09-25-36" src="https://github.com/user-attachments/assets/6436a746-3a58-40f8-bd4d-c9183ac35a87">

**Comment by Geeyun-JY3** [comment]
之前群里说是下个版本加：
![](https://github.com/user-attachments/assets/de6173d6-2d0e-43f3-b666-e0bff63d6c47)
