### ISSUE TITLE
实心/空心 按钮无法复原

### ISSUE THREAD

**Issue by wehoon** [Snipaste/feedback#3109]
### 发生了什么？

某一次截图操作点击了实心按钮，然后就再也无法复原了，无法使用空心模式
![image](https://github.com/user-attachments/assets/479cf0a1-d842-42bb-b907-e8341a005912)

### 运行平台

macOS

### 软件版本

2.10.2

**Comment by wilsendd** [comment]
点左边的点.不就好了

**Comment by wehoon** [comment]
> 点左边的点.不就好了

是我无知了哈哈
