### ISSUE TITLE
画笔注释缩放时会错位

### ISSUE THREAD

**Issue by byzod** [Snipaste/feedback#3113]
### 发生了什么？

1. 随便截一张图，选择画笔功能（ctrl+3），将其缩放到400%，然后随便涂点什么东西。以下图为例，将issue前的小圈涂成红色
    
![Snipaste_2024-10-27_11-51-41](https://github.com/user-attachments/assets/cf0b3a47-284b-48a4-abe4-6103b14889a8)

2. 将涂改好的图缩回原来尺寸或者更小，出现严重错位（注：折线功能ctrl+2不会错位，其余未测试）

![An1](https://github.com/user-attachments/assets/5ba153b0-f927-4b15-afc0-144eaf4dd22e)

### 运行平台

Windows 桌面

### 软件版本

2.10.2（2024.09.23）

### 其他
不会错位的折线demo
![An2](https://github.com/user-attachments/assets/454a1555-dced-485e-a9dd-cc451dba4b58)

**Comment by liulex** [comment]
谢谢反馈，下个版本会修复。
