### ISSUE TITLE
输入激活码,点激活,timeout..

### ISSUE THREAD

**Issue by uniquejava** [Snipaste/feedback#3114]
### 发生了什么？

<img width="601" alt="image" src="https://github.com/user-attachments/assets/e28a945a-7b78-40d9-a8ed-67a0f7899e4f">

然后提示 timeout.. 激活服务器在哪., 开不开代理都timeout

<img width="317" alt="image" src="https://github.com/user-attachments/assets/def7d6e5-c429-4fc8-bfa6-c3818cea3597">

### 运行平台

macOS

### 软件版本

2.10.2

**Comment by liulex** [comment]
代理是在 首选项 - 更新 里面设置的吗？
另外，确保 app 没有被禁止联网。

**Comment by uniquejava** [comment]
谢谢! 没注意snipasted自身还有代理设置, 我从system proxy改成no proxy就好了..

<img width="596" alt="image" src="https://github.com/user-attachments/assets/d7b4d16c-30c2-4d5d-8f0e-552215b2b38c">
