### ISSUE TITLE
希望付费专业版能添加HDR截屏功能

### ISSUE THREAD

**Issue by kamio1980** [Snipaste/feedback#3115]
### 功能描述

如题，目前HDR下windows平台符合要求的HDR截图工具稀缺，如果Snipaste可以添加较为完善的HDR相关功能，一定会为团队带来可观的收入，因为越来越HDR生态内的设备有加入，刚需，市面上满意的工具太少。

希望考虑，并盼望得到官方开发团队回应。

**Comment by Geeyun-JY3** [comment]
Duplicate of #1112
