### ISSUE TITLE
截图如何设置长边最大2000px？

### ISSUE THREAD

**Issue by susetpresent** [Snipaste/feedback#3118]
### 问题描述

比如截图原尺寸4000×3000px，那么自动帮我压缩成2000×1500px。如果截图原尺寸1000×500px，那么就保持1000×500px不变

### 运行平台

Windows 桌面

### 软件版本

2.9.2

**Comment by Geeyun-JY3** [comment]
暂无相关功能，见：#357、#2095、#2171
