### ISSUE TITLE
HDR模式截图色彩异常

### ISSUE THREAD

**Issue by QXN173** [Snipaste/feedback#3119]
### 发生了什么？

![image](https://github.com/user-attachments/assets/681ac044-88de-4ea8-a2e4-e9f0f7955474)
HDR模式截图色彩异常（如上图：过高亮度）
![image](https://github.com/user-attachments/assets/cd8946d1-c0b4-433d-8d2c-1020417a368a)

### 运行平台

微软商店

### 软件版本

2.10.2（20240923）微软商店版

**Comment by Geeyun-JY3** [comment]
Duplicate of #1112
