### ISSUE TITLE
建议新增高亮选区弱化背景功能

### ISSUE THREAD

**Issue by magicds** [Snipaste/feedback#3120]
### 功能描述

QQ截图中有如下功能：

![image](https://github.com/user-attachments/assets/abefc1bd-c90f-4218-a565-3997e3e882e8)

效果：

![image](https://github.com/user-attachments/assets/63986d28-58c2-48dd-8bce-72e9f50a2c40)

感觉这个功能很好用。

在issue里面搜了下，发现有提过类似的，eg： #1075  #3083  #3099 但似乎没有响应。希望这个功能能得到支持

**Comment by Geeyun-JY3** [comment]
Duplicate of https://github.com/Snipaste/feedback/issues/2426
