### ISSUE TITLE
截图时无法用鼠标画自由大小的矩形截图，按贴图后发现实际上截取了一个边框，同时还无法选中和删除

### ISSUE THREAD

**Issue by geniusxxx** [Snipaste/feedback#3122]
### What happened?

截图时无法用鼠标画自由大小的矩形截图，按贴图后发现实际上截取了一个边框，同时还无法选中和删除
![image](https://github.com/user-attachments/assets/c5a47ace-64e9-4329-adae-abde772fe911)

### Platform

Windows Desktop

### Version

2.10.2

**Comment by Geeyun-JY3** [comment]
https://github.com/Snipaste/feedback/issues/3110#issuecomment-2430625133
> 双击边框。

**Comment by geniusxxx** [comment]
关闭鼠标穿透可以选中了
