### ISSUE TITLE
在谷歌浏览器上截图时界面会变糊

### ISSUE THREAD

**Issue by zzz-522** [Snipaste/feedback#3127]
### 问题描述

![屏幕截图 2024-11-03 200529](https://github.com/user-attachments/assets/0826d377-6ee1-428a-a2d4-bf48680dc9cd)
![Snipaste_2024-11-03_20-09-34](https://github.com/user-attachments/assets/a16ad5a7-7d5c-4965-a3ce-a81ac4623ac4)

用snipaste在谷歌上截图就是模糊的，用系统自带截图就是清楚的。

### 运行平台

微软商店

### 软件版本

2.10.2（2024.09.23）64位

**Comment by Geeyun-JY3** [comment]
Duplicate of #1112
