### ISSUE TITLE
Snipaste每次启动自动删除配置文件

### ISSUE THREAD

**Issue by wanqian-windrunner** [Snipaste/feedback#3129]
### 发生了什么？

每次启动 `Snipaste` 的 AppImage 后会自动删除 `~/.snipaste/config.ini` ，然后在首选项中改变任意选项后重新创建一个配置文件。
~~目前解决方法是手动 `chmod 444 config.ini` ，之后需要更改选项就再改权限。~~
上面这个方法会导致qq,tg等软件无法粘贴截图。所以此方法不行
后续发现好像是启动appimage,然后读取config.ini，再创建.desktop自启动文件，然后清空config.ini，因此导致有人设置自启动后重启有效，但是第二次重启不自启动的现象。
我的解决方案是更改.desktop文件，变为执行一个sh文件，并且修改权限为444防止被覆盖，然后sh文件中这么写：
```bash
cp ~/.snipaste/config.ini.bak ~/.snipaste/config.ini
Snipaste-2.10.2-x86_64.AppImage
```
算是最笨的办法了，毕竟要保证config.ini有读写权限的同时不被清空，如果各位有好办法麻烦告知我一下QAQ
<img width="600" alt="image" src="https://github.com/user-attachments/assets/21582f64-00fb-4f07-b659-6caf61a90e29">

### 运行平台

Linux

### 软件版本

Snipaste-2.10.2-x86_64.AppImage

**Comment by MrZ626** [comment]
同，我也是写了个一样的脚本解决的，不过没改desktop文件，只是把脚本加到自启动项里了，反正平时也不会需要开关它

**Comment by liulex** [comment]
确实是 bug，会在 wayland 下触发。下周会发新版修复，谢谢反馈！
