### ISSUE TITLE
Windows 10 多桌面情况下捕获窗口边界有bug

### ISSUE THREAD

**Issue by DNACore** [Snipaste/feedback#313]
Bug report?
**比如说，开启了两个虚拟桌面，1和2。此时获取到的窗口边界，混合了1和2中所有的窗口边界。**

**Comment by EMLVIRUS** [comment]
能描述准确一点吗。我无法整理出一个完整的STR

**Comment by DNACore** [comment]
@EMLVIRUS 这个语言可能不好表达。
按照如下方法，可能比较容易复现这个bug。
1. windows 10系统下，建立两个虚拟桌面，1 和 2.
2. 在虚拟桌面1中随便打开一些窗口，最好不要最大化，这样更容易看出问题。
3. 虚拟桌面2中不要打开任何窗口。
4. 切换到虚拟桌面2，此时按快捷键 F1 截图。

现象：随意移动鼠标，可以发现 Snipaste 错误地在虚拟桌面2捕获了虚拟桌面1的窗口界面元素。

**Comment by EMLVIRUS** [comment]
已经确认这个bug 召唤 @liulex

**Comment by liulex** [comment]
@DNACore @EMLVIRUS 
谢谢反馈，这个是已知 bug，一年前尝试修过一次，好像是没找到相应的 API 所以没修成……
虚拟桌面用户也比较少，先放着吧 :sweat_smile:

**Comment by phtwo** [comment]
表示日常工作非常依赖虚拟桌面，编辑器、浏览器、文档、文件夹 各种各样 不同线上分支

**Comment by wdhwg001** [comment]
https://stackoverflow.com/questions/31801402/api-for-windows-10-virtual-desktops

最近也遇到了这个问题，查了一下这里有一些说明，或许会有帮助。

**Comment by liulex** [comment]
@phtwo 谢谢你提供的帮助 👍

**Comment by liulex** [comment]
该问题在早些版本已经修复。
