### ISSUE TITLE
Win11从休眠中恢复后，贴图上右键引发崩溃

### ISSUE THREAD

**Issue by HaleShaw** [Snipaste/feedback#3131]
### 发生了什么？

从休眠中恢复后，开始截图然后贴图，然后在贴图上右击，软件就直接崩溃了。
Win11 24H2 26100.2161

### 运行平台

Windows 桌面

### 软件版本

2.10.2

**Comment by liulex** [comment]
软件的 crashes 目录下有 dump 文件吗？

**Comment by HaleShaw** [comment]
[crashes.zip](https://github.com/user-attachments/files/17679140/crashes.zip)
有好几次的，我全上传来了。

**Comment by liulex** [comment]
感谢，已定位到原因，会在下个版本修复。
