### ISSUE TITLE
复制到剪贴板的图片强制为bmp，不受软件首选项的设置所影响。

### ISSUE THREAD

**Issue by Misaka2298** [Snipaste/feedback#3132]
### 联系方式

Misaka2298@outlook.com

### 发生了什么？

如题。复制为bmp文件会占用很大的空间，我尝试在Snipaste→首选项→输出→剪贴板→禁用以Windows Bitmap格式复制图片（贴图和截图都禁用），但是无果，在截图界面复制后仍然复制的是.bmp文件，这样我截一张2k的照片就会达到14MB~的大小，实在是太大了hh

### 运行平台

Windows 桌面

### 软件版本

2.10.2

**Comment by liulex** [comment]
粘贴到哪里获得了 bmp 文件？
实际上这跟剪贴板里的格式无关，最终获得什么文件，取决于你粘贴图像到哪个应用程序。

**Comment by Misaka2298** [comment]
> 粘贴到哪里获得了 bmp 文件？
> 实际上这跟剪贴板里的格式无关，最终获得什么文件，取决于你粘贴图像到哪个应用程序。

几乎所有的软件。微信、QQ、Localsend等等剪贴进去都是bmp。

**Comment by liulex** [comment]
1. 粘贴到电脑端微信，再另存为是 png.
2 .不管用什么软件截的图，到了 LocalSend 都是 bmp.

**Comment by Misaka2298** [comment]
> 1. 粘贴到电脑端微信，再另存为是 png.
> 2. 不管用什么软件截的图，到了 LocalSend 都是 bmp.
> 
> 

原来是这样，感谢，这就去找localsend提issue
