### ISSUE TITLE
希望输出选项里 能添加 快捷调节 输出图像质量 的功能

### ISSUE THREAD

**Issue by wilsendd** [Snipaste/feedback#3133]
### 功能描述

<img width="172" alt="2024-11-10_15-43-31" src="https://github.com/user-attachments/assets/4424cd39-29d9-40ac-ade8-984a7688d735">

希望这里能添加快捷调节输出质量的滑动条，**截取的图片不一样，输出的图片大小也就不一样**，截取不同的图片，**需要频繁去设置里调节**，很麻烦。。。

**Comment by Geeyun-JY3** [comment]
你已经开过相关 issue 了……：#2604

**Comment by Geeyun-JY3** [comment]
Duplicate of #2604
