### ISSUE TITLE
能否像飞书一样，支持滚动截屏，录制mp4或者gif。

### ISSUE THREAD

**Issue by nezaking** [Snipaste/feedback#3141]
### 联系方式

nezaking@qq.com

### 发生了什么？

# 功能建议
##  一直使用snipaste，软件轻便，贴图对于数据处理太实用了，后来公司用了飞书，便两者同时使用，但是我的一些朋友没有飞书的，还是一直使用snipaste,作为一个多年老用户，希望增加如下功能：
1. 滚动截图，这个对截微信公众号文章或者其他的长文太实用了
2. 增加录制mp4或者gif功能
3. OCR识别，这个可能有点难，因为估计占用服务器资源，但是可以付费使用

### 运行平台

Windows 桌面

### 软件版本

2.10.2

**Comment by Geeyun-JY3** [comment]
Duplicate of #2130

**Comment by Geeyun-JY3** [comment]
Duplicate of https://github.com/Snipaste/feedback/issues/19#issuecomment-1846413616
