### ISSUE TITLE
[Mac][PRO] 截屏后进行框选，在点击 command + c 的一瞬间，之前的框会飞掉

### ISSUE THREAD

**Issue by A1aM0** [Snipaste/feedback#3142]
### 发生了什么？

比如，我现在希望截图，并精确的框选到“发生了什么”这几个字，理想情况下，结果就是如下这样

<img width="500" alt="image" src="https://github.com/user-attachments/assets/0afc90e7-73fb-449a-b09f-3834c25c59a3">

但是，有时候在我按下“command + c”的一瞬间，红框会先被拉伸，再保存。最后就变成了下图这样

<img width="500" alt="image" src="https://github.com/user-attachments/assets/daf873e3-29c6-4177-a67e-816f6258ce90">

我认为我的使用习惯没有发生改变，让我在意的是，以前并未遇到这种情况，但是自从升级到pro之后，就会时有发生

### 运行平台

macOS

### 软件版本

2.10.2(2024.09.23)

**Comment by liulex** [comment]
这应该是你按下 cmd+c 的瞬间还没有释放鼠标。我会在下周发布的新版修复这个问题，谢谢反馈。

**Comment by A1aM0** [comment]
> 这应该是你按下 cmd+c 的瞬间还没有释放鼠标。我会在下周发布的新版修复这个问题，谢谢反馈。

了解，在后续使用中我会留意一下这点
