### ISSUE TITLE
放大镜功能失效

### ISSUE THREAD

**Issue by ChaceB** [Snipaste/feedback#3145]
### 问题描述

截图时，自动显示的放大镜出现了严重的问题：
重新启动软件后，第一次截图使用正常。接着，按一下shift键（切换RGB/HEX）后，放大镜就会卡住。如图：
![Snipaste_2024 11 27_17-52-03](https://github.com/user-attachments/assets/4904c0c5-ab41-465a-9e25-021b885e69cf)

### 运行平台

微软商店

### 软件版本

版本2.10.3(2024.11.28)微软商店版

**Comment by liulex** [comment]
无法复现，录个屏看看？

**Comment by ChaceB** [comment]
感谢回复！今天到家太晚，没有精力录屏。明天空闲时上传。

Le Liu ***@***.***> 於 2024年11月27日週三 下午7:37寫道：

**Comment by ChaceB** [comment]
## [使用问题]放大镜功能失效

### 1. 环境和版本：

* windows11 24H2 26100.2454
* snipaste 微软应用商店版 2.10.3

### 2. 问题描述

我在使用过程中遇到了放大镜失效的问题。经过实验，我发现在同一块4k分辨率的屏幕上，使用1920×1080的分辨率时一切正常，但是使用3840×2160时就会出现问题，下文详述：

#### ①. 重启软件后第一次使用正常，在按下两次shift键切换色值格式后，放大镜就会卡住，附上gif：

![1](https://github.com/user-attachments/assets/10675500-80d1-47da-836b-e1f6e504c09d)


#### ②. 重启软件后第一次使用正常，但是退出后再次截图时，放大镜就会失效，附上gif：

![2](https://github.com/user-attachments/assets/7726f760-95b9-41e8-9e03-f0a25699c25e)

上述问题均出现在3840×2160分辨率下。

**Comment by liulex** [comment]
太奇怪了，我也是 3840×2160 啊……  🥹
我再查查……

**Comment by the1812** [comment]
> 试试这里下载的桌面免费版看有没有这个问题？
> https://bitbucket.org/liule/snipaste/downloads/

@liulex 遇到了完全一样的问题，这个链接里已经是空的了，历史版本在哪里还可以下载？

环境和版本：
Windows 10 IoT 企业版 LTSC 21H2
Snipaste 微软应用商店版 2.10.8

录屏：
https://github.com/user-attachments/assets/953db84b-9f8f-4b3b-b09a-ce7946de2501
