### ISSUE TITLE
更换界面字体时崩溃

### ISSUE THREAD

**Issue by MirionQs** [Snipaste/feedback#3155]
### 发生了什么？

更换界面字体时崩溃。
我曾经选择了霞骛文楷作为界面字体，但后来更换成英文系统再尝试更换就会卡死崩溃。（可能是英文系统下字体名变了？）

### 运行平台

Windows 桌面

### 软件版本

2.10.3

**Comment by liulex** [comment]
软件目录下的 crashes 文件夹里面有内容么？有的话麻烦打包发送到 <snipaste.app@gmail.com>.

**Comment by liulex** [comment]
感谢反馈，下个版本会修复。
