### ISSUE TITLE
我需要截取长图的功能

### ISSUE THREAD

**Issue by wangsvip** [Snipaste/feedback#3168]
### 功能描述

我购买了pro版本，经常使用网页截图，需要截取长图，能添加这个功能吗

**Comment by Geeyun-JY3** [comment]
Duplicate of https://github.com/Snipaste/feedback/issues/19#issuecomment-1846413616

**Comment by wangsvip** [comment]
2016年已经有人提出来这个功能了，到现在还不支持的话，那我只能放弃这个软件，重新购买pixpin的会员了。

**Comment by Anufether** [comment]
额，我刚买会员，逛了逛issues，原来这个以及拖这么久了吗
而且好像升级到3还要再花钱。。。
早知道买pixpin会员了

**Comment by wangsvip** [comment]
> 额，我刚买会员，逛了逛issues，原来这个以及拖这么久了吗 而且好像升级到3还要再花钱。。。 早知道买pixpin会员了

感觉49年入国军了吧，就这么一个小功能开发了8年了

**Comment by Anufether** [comment]
> > 额，我刚买会员，逛了逛issues，原来这个以及拖这么久了吗 而且好像升级到3还要再花钱。。。 早知道买pixpin会员了
> 
> 感觉49年入国军了吧，就这么一个小功能开发了8年了

只是觉得很失望，因为免费用了很久觉得不错就付费支持了，但是作者似乎并不想理会用户的需求。即使 `长截图` 或者 ocr 平常我用不到。
