### ISSUE TITLE
希望支持截图后的组合动作，复制到剪贴板并且贴图

### ISSUE THREAD

**Issue by zhanggang807** [Snipaste/feedback#3173]
### 功能描述

截屏 --> 按键 --> 动作，支持组合动作，复现到剪贴板且贴到屏幕
<img width="503" alt="image" src="https://github.com/user-attachments/assets/35966893-7a1a-4e98-bcb7-38005146d9b8" />

**Comment by Geeyun-JY3** [comment]
请使用专业版的全局快捷键 与 命令行调用 绑定实现：https://docs.snipaste.com/zh-cn/pro?id=b-更自由的定制化
