### ISSUE TITLE
ctrl+T快捷键有时可以有时不行

### ISSUE THREAD

**Issue by DmalKiKi** [Snipaste/feedback#3174]
### 问题描述

我在公司电脑上用ctrl+T可以把某个程序窗口钉在最前端，最上层。但是在家里的电脑用却没有反应。但我查看ctrl+T的快捷键解释是“直接将截图贴到屏幕”，和把窗口固定在最上层又无关。

### 运行平台

Windows 桌面

### 软件版本

2.10.3

**Comment by liulex** [comment]
> 我在公司电脑上用ctrl+T可以把某个程序窗口钉在最前端

Snipaste 的 Ctrl+T 没这个功能。

**Comment by DmalKiKi** [comment]
> > 我在公司电脑上用ctrl+T可以把某个程序窗口钉在最前端
> 
> Snipaste 的 Ctrl+T 没这个功能。

难道是用了有其他软件在运行我不知道？我回去再看看，谢谢

**Comment by Geeyun-JY3** [comment]
是不是开了 PowerToys 的 Always on Top？不过其默认快捷键是 <kbd>⊞ Win</kbd>+<kbd>Ctrl</kbd>+<kbd>T</kbd>。
