### ISSUE TITLE
按Shit+F3隐藏所有贴图后，按F1截图后再次贴图时，会自动显示所有隐藏的贴图，这是我的设置问题，还是软件设置就是这样呢？

### ISSUE THREAD

**Issue by LiHai-26** [Snipaste/feedback#3178]
### 问题描述

久仰Snipaste的大名，今天安装用了以下，确实神器，赞赞赞。
只是我用的时候发现一个问题，当我将多张贴图使用Shit+F3组合键全部隐藏后，继续按F1截图，并将新截的图片变成贴图后，之前隐藏的贴图就会全部被显示出来；
但我此时没有按Shit+F3，只是截取新的图片并贴图，就会把之前所有隐藏的贴图全部显示出来；
而我并不想在每次贴新图时，就会显示之前我隐藏的所有贴图，而是在我需要时，通过再次使用Shit+F3组合键才让它们显示；
不知道是否需要设置一下，我在快捷键设置里没有看到哪里可以设置，或者软件设置就是这样的，贴新图时会自动显示所有被隐藏的贴图，请问大家有这样的使用情况吗，有什么好的建议吗？

### 运行平台

Windows 桌面

### 软件版本

2.10.3

**Comment by liulex** [comment]
对于免费版，同一个贴图组的所有贴图只能同时显示或同时隐藏，所以有新贴图贴出来的时候，其它隐藏的贴图也会显示出来。

在免费版，可以通过切换贴图组来近似实现你的需求。

专业版会有"暂时隐藏其它贴图"的功能。比如已有贴图 12345，你可以选中 1 和 2，右键菜单选择"暂时隐藏其它贴图"，那贴图 345 会被隐藏，再贴出新贴图，它会和贴图 1 和 2 一起显示。这时候 Shift+F3 只对贴图 345 之外的贴图起作用，直到从任意贴图右键菜单选择"显示已隐藏贴图"，或者贴图 345 之外的所有贴图已被关闭。

**Comment by LiHai-26** [comment]
@liulex 好的，谢谢作者大大回复，等后面购买专业版支持一下

**Comment by LiHai-26** [comment]
@liulex 好的，谢谢作者大大回复，等后面购买专业版支持一下
