### ISSUE TITLE
关于「Core + Plugins」的一些想法

### ISSUE THREAD

**Issue by ZetaoYang** [Snipaste/feedback#327]
我觉得 「Snipaste」可以做成 「Core + Plugins」这样的架构，Core 依然是截图、贴图和标注 功能。Plugins 提供一些除 截图、贴图和标注 之外的但和 图像 相关的功能（对「Snipaste」的功能相关扩展）。
「Snipaste」提供**插件接口**，插件**编写规范文档**和简单**教程示例**，让用户自己（或者「Snipaste」社区）来实现相关需求（插件形式）。「Snipaste」可以在官网上线一个 **插件商店**，插件可分为免费版和专业版。在免费版和专业版的「Snipaste」核心上亦可设置不同的插件使用**数量上限**。

**Comment by septs** [comment]
对于用户而言即使开放 API 也很难交互
因为 Snipaste 是基于 Qt 开发的
因此采用插件方案会要求插件开发者至少具有 C++ 及 Qt 基础

然而根据现有 issues 整体来看更多的是重新组合现有功能逻辑或流程
因此 #250 更为合适

而非要 插件 的需求则是 #188 OCR 这类型

**Comment by ZetaoYang** [comment]
插件的编写可以放给 Snipaste 社区 https://github.com/snipaste 。
Snipaste 的用户群体有 小白，修图专业人员，程序员，写作者等等，这里面有提需求的，也有具备一定编程能力的，Snipaste 社区 可以吸纳其中具备编程能力的人来参与 各种插件 的实现。
核心则依然由刘大大和你们这些人来维护，插件交给社区。
插件可以由脚本语言和  C++ 的绑定库或者直接 Lua 脚本语言。

**Comment by septs** [comment]
@ZetaoYang 您所理想的 用户社区 显然是很不现实的
另外我在这里引用下 clowwindy 的一段 comment https://github.com/shadowsocks/shadowsocks-windows/issues/293#issuecomment-132253168

**Comment by ZetaoYang** [comment]
@septs 你引用的内容放在这显然不合适。这里我举个人认为比较成功的例子 「Leanote」（蚂蚁笔记 https://leanote.com/）
这是它的插件机制：[如何开发Leanote桌面端插件](https://github.com/leanote/desktop-app/issues/110)。

**Comment by septs** [comment]
我认为引入面向用户的 插件系统 需要可观的用户积累
然而现在更多的是 用户单方面 的要求更多

自认为有能力参与并不多 #245

**Comment by liulex** [comment]
谢谢，很好的建议~
Snipaste 目前的状态我比较满意了，近期准备只修修 bug。
有空的时候会弄弄 Mac 版、插件系统以及专业版。

插件系统需要我慢慢将代码整理一下，请静待消息。
插件自然是面向开发者而不是用户，但开发门槛不会高，会 C++ 就行了~

User Script 的话，因为我个人没有接触过，所以相对会再延后些。

**Comment by ZetaoYang** [comment]
1. User Script 是针对浏览器平台的，Javascript 语言。比如 Chrome 插件「Tampermonkey」，它的**用户脚本源** 在这 http://tampermonkey.net/scripts.php 。
2. 插件系统 一定要有  **插件开发文档**，插件的**示例**，**教程**，**安装使用说明**。
这里有一个 PyQt 项目的插件说明，可供参考： https://github.com/cosven/FeelUOwn/issues/148 
3. 我有一个问题，会不会因为平台的不同，Snipaste 在不同的平台上会有功能或者外观上的明显差异？

**Comment by septs** [comment]
@ZetaoYang UserScript 是一种概念
see https://www.google.com/intl/zh-CN/ime/pinyin/api.html

**Comment by ZetaoYang** [comment]
@septs I got it.

**Comment by ZetaoYang** [comment]
@liulex 这里我给作者提供一个关于 OCR 的线索 Free OCR API : https://ocr.space/ ，已经在开源项目 ShareX 中使用了。
![image](https://cloud.githubusercontent.com/assets/10769951/24249250/831e01de-100d-11e7-8e4f-eb3abcd6879d.png)

**Comment by EMLVIRUS** [comment]
> User Script 是针对浏览器平台的，Javascript 语言。比如 Chrome 插件「Tampermonkey」，它的用户脚本源 在这 http://tampermonkey.net/scripts.php 。

一句题外话 这似乎是在指油猴子脚本 Grease monkey Scripts
