### ISSUE TITLE
希望在win10多桌面的情况下，贴图也能支持多桌面。

### ISSUE THREAD

**Issue by fxy147** [Snipaste/feedback#328]
希望能够实现只将部分贴图贴到特定的桌面上。比如在桌面1进行工作一，贴了两张图AB；桌面2进行工作二，贴了两张图CD。希望在桌面1上只显示AB贴图，切换到桌面2时AB都隐藏，只显示CD贴图。因为 不同的工作可能需要不同的贴图，而把ABCD全显示占用很多屏幕空间。手动切换贴图组有些麻烦，希望能将此操作变得自动化。

**Comment by liulex** [comment]
会支持多桌面的~

**Comment by YXH-YXH** [comment]
遇到同样的需求，准备提出，发现已有，来插个眼

**Comment by liulex** [comment]
将在 v2.2.2 专业版支持。
