### ISSUE TITLE
无法开机启动

### ISSUE THREAD

**Issue by bylane** [Snipaste/feedback#348]
环境：win10 64位专业版
软件版本：1.11.3  （2017.01.27）

勾选开机启动的时候提醒
错误：无法在启动文件夹中创建快捷方式

管理员模式打开也是一样

**Comment by liulex** [comment]
<kbd>Win</kbd> + <kbd>R</kbd>，输入 `shell:startup`，回车，打开的文件夹的路径发一下。

**Comment by BianChengNan** [comment]
我这边也是不能自动启动，Snipaste版本：**1.12（2017.03.09）32位 64位**  操作系统版本：**win10x64专业版 10.0.14393**

startup路径下确实有对应的shortcut，但是貌似没起作用，对应的路径是
*C:\Users\BCN\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup*

我的解决方案（亲测有效，貌似Listary就是这么搞的，Listary的启动很稳定）：
```
SCHTASKS /Create /RL HIGHEST /TN Snipaste_x64(admin) /TR "C:\My\Tools\Snipaste-1.12-x64\Snipaste.exe" /SC ONLOGON
```
具体参数意义可以参考[SCHTASKS官方帮助](https://msdn.microsoft.com/en-us/library/windows/desktop/bb736357(v=vs.85).aspx)
@liulex 可以考虑这么搞下

by the way: 很久没更新了哈:)

**Comment by BianChengNan** [comment]
@liulex 我把 **任务计划程序配置工具** 给禁用了,开启后就可以了！@bylane应该也是同样的问题

期待期待期待

**Comment by liulex** [comment]
@BianChengNan  @HahnSC 
没找到在哪里可以禁用 **任务计划程序配置工具**……请问是怎么操作的？

**Comment by elliot-bia** [comment]
> @liulex 我把 **任务计划程序配置工具** 给禁用了,开启后就可以了！@bylane应该也是同样的问题
> 
> 期待期待期待

thx！ the same

**Comment by elliot-bia** [comment]
> @BianChengNan @HahnSC
> 没找到在哪里可以禁用 **任务计划程序配置工具**……请问是怎么操作的？

在“任务管理器”里的“启动”，最下面
