### ISSUE TITLE
三项小的改进建议

### ISSUE THREAD

**Issue by PaperFlu** [Snipaste/feedback#364]
**截图后的操作栏位置**

一般截图从左上至右下，So 操作栏放右下角挺方便。但不排除有例外的，右下至左上，左下至右上……建议随机应变。

**右键—帮助**

里面点击后的弹框在任务栏显示的图标有点大。

**鼠标悬浮在 Snipaste 上面后的显示框里的 “贴图: 0” 是什么鬼？**

**Comment by liulex** [comment]
Hi,

1. 截图的拉取方向和工具栏位置有什么关系……？

1. 没看出哪里大：
![default](https://cloud.githubusercontent.com/assets/2010459/23583900/1636707c-018c-11e7-91d6-107a5663aa6b.png)

1. 当前贴图组的贴图总数。

**Comment by H-KZ** [comment]
拉取方向决定鼠标最终位置，若从右下到左上，鼠标最后在左上角，而工具栏在右下就远了

win7 上是大了一点。和 chrome 及资源管理器对比的。

**Comment by liulex** [comment]
虽然有一些道理，但鼠标释放点不代表用户想要开始标注的区域，所以还是固定一个相对位置较好，至少每次要点工具栏的时候不用先看清工具栏在哪个方位。

**Comment by H-KZ** [comment]
![image](https://cloud.githubusercontent.com/assets/22674396/23584494/6ec99d56-019e-11e7-8c02-01317aeebcc0.png)

大了那么一丢丢，主要是顶部

**Comment by liulex** [comment]
Hmm... win7 图标问题还是算了……
