### ISSUE TITLE
Improve latency. | 改善截图的延迟。

### ISSUE THREAD

**Issue by wdhwg001** [Snipaste/feedback#374]
在我的使用过程中，我发现Snipaste并不能准确的进行“实时截图”，按下截图键后，屏幕展现的内容常常是一刹那前的屏幕图像，延迟可能在200ms左右。

有计划改善这一点吗？

**Comment by liulex** [comment]
获取全屏图像总是需要一些时间的……还有获取光标等等，我已经尽量优化了，以后有新想法也会尽可能去优化。
具体的延迟耗时就取决于机器配置啦，看 log 可以得知具体延迟：

```
[2017-03-10 xxx] [info] Preparing to snip...
...
[2017-03-10 yyy] [info] Ready to snip
```
xxx 和 yyy 之间的时差即是截图准备过程的耗时。

**Comment by wdhwg001** [comment]
好吧orz，虽然觉得按下截图键之后截图界面出现的速度有些慢，获取图像也稍有点延迟，但也并非完全不能接受……毕竟Snipaste不开源，也没有太好的办法做细致的profiling。

**Comment by gongnl** [comment]
首次按F1启动截图时很慢有5秒左右的延迟，第二次开始就正常了，请问是我系统问题还是软件问题，有没有办法优化
我的系统配置如下
制造商：Hewlett一packardCompany
型号：Hp pro 3380MT
分级：4.6 Windows体验指数
处理器：Intel(R)Core(TM)i3-3240 CPU @ 3.40GHz 3.40GHZ
安装内存（RAM):4.00GB(3.39GB可用）
系统类型：32位操作系统

**Comment by wdhwg001** [comment]
同，我其实考虑重新打开这个Issue了， @liulex 有什么办法可以避免Snipaste被放入虚拟内存吗？

**Comment by septs** [comment]
@wdhwg001 有的叫 `"Lock pages in memory"` 该特性似乎是给 SQL Server 专用的
see https://docs.microsoft.com/en-us/windows/device-security/security-policy-settings/lock-pages-in-memory
see https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-the-lock-pages-in-memory-option-windows

**Comment by liulex** [comment]
@wdhwg001 换个大内存，禁用虚拟内存…… 😅 
或者多用贴图功能啊~

@wdhwg001 @gongnl 
https://github.com/liulex/Snipaste-Feedback/issues/360#issuecomment-291495337
这里提到[设置](https://github.com/liulex/Snipaste-Feedback/wiki/%E9%AB%98%E7%BA%A7%E8%AE%BE%E7%BD%AE) `General/high_process_priority` 为 `true` 有一些作用，你们可以验证一下。

**Comment by septs** [comment]
禁用虚拟内存 可能导致有些副作用
例如在“拥有”充足 **物理** 内存的状态下无法 **分配** 内存

**Comment by wdhwg001** [comment]
@liulex 或者，要不要试着用一些不干净的办法，比如定期在前台跑点什么一类的。
事实上，鉴于Snipaste经常需要起到“偶尔的抓拍”的作用，所以维持Snipaste的触发速度还是很关键的。
在这方面上，QQ截图因为一直启动于前台所以很少会遇到Snipaste的“硬盘嘎吱嘎吱叫一会才启动截图”的问题。

**Comment by wdhwg001** [comment]
更进一步的话，或许可以利用贴图功能，创建一个1px、透明、点击穿透、无框的贴图一直在前台？
没有尝试过，仅仅作为提议。

**Comment by Princezhu** [comment]
win10 64bit 同样遇到启动慢的问题  由于是不定时会使用  首次启动时确实会很慢   有个10几20S吧  看了上边的回复   知道跟配置有关   但QQ或者微信的截图  不会有延时   所以还是觉得  如果能改进下会更好

**Comment by BianChengNan** [comment]
貌似最新版1.13.2对这方面有改进？之前版本确实初次启动比较慢的，这个版本貌似没这问题？有待进一步验证。

**Comment by StarryVoid** [comment]
任务管理器中的优先级改成高，，从来没见过这个情况了。。

**Comment by wdhwg001** [comment]
#498 
同时这个Issue的内容没有上述Issue描述的完整，我关掉这边吧，去那边讨论好了。
