### ISSUE TITLE
希望支持保存文件到指定目录的同时自动保存到剪切板

### ISSUE THREAD

**Issue by idenpa** [Snipaste/feedback#38]
RT，有的时候截图是想马上发给朋友，自己也希望保存一份，所以希望可以设置为截图完成后自动保存到指定目录和剪切板，类似FSCapture。

**Comment by GregAMO** [comment]
> 有的时候

那么当这个“有的时候”出现的情况下，可以多按一次Ctrl+C就行
不是这个“有的时候”，就只需要按Ctrl+Shift+S
就可以啦~也不是次次都需要进剪贴板不是？

而且贴图功能会把剪贴板里的图贴出来
这就可能：
截图-贴上，不要了，Shift+ESC销毁，
再贴，怎么又贴出来了？哦，剪贴板还有一份QAQ

**Comment by liulex** [comment]
感谢 @GregAMO 帮忙回答。
需要这个功能的人太少，所以优先级低，以后有空再添加吧。

**Comment by liulex** [comment]
需要的同学可以给楼主点赞投票

**Comment by septs** [comment]
建议将该功能作为手动配置文件项

**Comment by wurenny** [comment]
我更喜欢【复制文字/代码——>按下某快捷键——>粘贴的直接就是文字/代码对应的贴图】

**Comment by StarryVoid** [comment]
此功能已支持，建议关闭 issues
