### ISSUE TITLE
几点小建议

### ISSUE THREAD

**Issue by chenjrx** [Snipaste/feedback#380]
1.标注能直接再次编辑。
2.可以自主开启或关闭右下角放大镜。
3.在截图区域双击可保存截图。
4.输出格式能直接选择，而不用输入。
5.开放更多热键自定义。
6.软件配置可导出，下次更新后可导入自己的配置，不用每次都设置。
7.自动保存标注记忆副本，图片保存或意外退出后，可以打开副本再次回到编辑模式，类似PS中的PSD文件。

**Comment by chenjrx** [comment]
1.标注能直接再次编辑。
2.可以自主开启或关闭右下角放大镜。
3.在截图区域双击可保存截图。
4.输出格式能直接选择，而不用输入。
5.开放更多热键自定义。
6.软件配置可导出，下次更新后可导入自己的配置，不用每次都设置。
7.自动保存标注记忆副本，图片保存或意外退出后，可以打开副本再次回到编辑模式，类似PS中的PSD文件。

**Comment by chenjrx** [comment]
1.标注能直接再次编辑。
2.可以自主开启或关闭右下角放大镜。
3.在截图区域双击可保存截图。
4.输出格式能直接选择，而不用输入。
5.开放更多热键自定义。
6.软件配置可导出，下次更新后可导入自己的配置，不用每次都设置。
7.自动保存标注记忆副本，图片保存或意外退出后，可以打开副本再次回到编辑模式，类似PS中的PSD文件。

**Comment by GregAMO** [comment]
1. 文字可以了，其他形状的二次编辑将在专业版提供
3.可以将回车设为保存截图并退出
6.软件能更新不应该丢失软件配置啊

**Comment by liulex** [comment]
1\. #79 
2\. 3\. 5\. 会考虑在专业版提供。
4\. ？？？
6\. 配置**全**在 config.ini，另建议使用在线自动更新。
7\. 现在不是可以？

**Comment by Geeyun-JY3** [comment]
1. https://github.com/Snipaste/feedback/issues/79#issuecomment-263239139
2. 需要专业版：https://github.com/Snipaste/feedback/issues/1679#issuecomment-714527302
3. [v2.1.1](https://docs.snipaste.com/zh-cn/changelog?id=%e6%96%b0%e5%a2%9e%ef%bc%9a-1) 已实现：
   <img src="https://github.com/Snipaste/feedback/assets/49396421/d6990e16-2131-4637-8671-3fa4b9ba6d18" width="50%" height="50%">
4. 这个直接在 Windows 的原生保存对话框的下拉菜单里选不就行了？
   <img width="550" alt="image" src="https://github.com/Snipaste/feedback/assets/49396421/68e39b51-db3f-4fe4-8341-f256f095a801">
5. 专业版可以为 Snipaste 的任意功能指定全局快捷键：https://docs.snipaste.com/zh-cn/pro?id=b-更自由的定制化
6. 如 https://github.com/Snipaste/feedback/issues/380#issuecomment-286379543 所述
7. 自动备份如 https://github.com/Snipaste/feedback/issues/380#issuecomment-286379543 所述，这种副本文件讨论合并至 #1654
