### ISSUE TITLE
更符合直觉的快捷键操作

### ISSUE THREAD

**Issue by ZeppLu** [Snipaste/feedback#387]
- 截完图后，Ctrl-S 快速保存，Ctrl-Shift-S 弹出提示框选择保存位置。操作更方便
- 贴图后，Ctrl-+/- 的操作改为缩放图片，而非更改透明度，更符合操作习惯，而且也能支持触摸板手势（我的笔记本触摸板双指缩放的手势默认发送这两个键）

**Comment by ZeppLu** [comment]
刚刚又想到了一个：增加一个复制 hex 颜色值时使用大写还是小写的选项

**Comment by septs** [comment]
Color Hex 大小写不影响使用
该需要我认为无效

**Comment by ZeppLu** [comment]
使用上是不影响没错，但编程时可能会有 coding style 的要求
不妨放到 `config.ini` 里面，有需要的人自行设置？

**Comment by septs** [comment]
code style 要求请使用 formatter 解决

**Comment by liulex** [comment]
我倒是觉得大小写这个设置可以提供。 😅 

至于快捷键：
* <kbd>Ctrl</kbd> + <kbd>S</kbd> 的一般含义是保存当前文件（如无文件名则弹出对话框），<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>S</kbd> 一般是另存为，所以我觉得当前的设置挺合理的。你希望调换只是因为你用快速保存多一些，但实际是反直觉的。
* 至于缩放图片，我试了 Windows 自带的图片查看器，确实是 <kbd>Ctrl</kbd> + <kbd>+</kbd> <kbd>-</kbd> 为缩放图片，但 MassiGra 是用 <kbd>+</kbd> <kbd>-</kbd> 的，算作打平，那么就是都可以。但是呢，Snipaste 中 <kbd>鼠标滚轮</kbd> 是缩放图片，<kbd>Ctrl</kbd> + <kbd>鼠标滚轮</kbd> 是调整透明度，所以对应地，<kbd>+</kbd> <kbd>-</kbd> 为缩放图片，<kbd>Ctrl</kbd> + <kbd>+</kbd> <kbd>-</kbd> 为调整透明度更为合理。

**Comment by ZeppLu** [comment]
我觉得 @septs 说得也在理，加不加这个功能其实对我自己没多大影响，只是突然冒出来的一个想法而已。

至于快捷键：
* 仔细想想，Ctrl-S 确实才是更符合直觉的，原先的想法受到了自己操作习惯的影响。
* 事实上，几乎在所有浏览器、看图软件、文本编辑器、查看器、办公软件中，缩放的快捷键都是 Ctrl-+/-，而且 Ctrl-滚轮 也是同样通用的缩放快捷键，我敢保证默认用滚轮缩放的软件只是少数。

**Comment by liulex** [comment]
那是因为浏览器、文本编辑器等都需要滚轮滚动页面，而 Snipaste 目前是没有这个操作的（[以后可能有](https://github.com/liulex/Snipaste-Feedback/issues/282#issuecomment-271213867)），所以把不带 <kbd>Ctrl</kbd> 的分配给了更常用的图片缩放。
以后加了滚动条之后再重新分配吧。

**Comment by ZeppLu** [comment]
所以我说关键是符合直觉啊，在两种快捷键不同的软件之间换来换去的话，脑子会变成浆糊的。
而且一只手按 Ctrl，另一只手用滚轮，也不是很麻烦吧，个人认为。

**Comment by misybing** [comment]
Ctr + Shift + S 快捷键失效，不知道怎么回事，按下后会闪烁，叮地响一下，但是没保存，且仍在截图状态。

**Comment by liulex** [comment]
@ZeppLu 
下个版本会将 <kbd>Ctrl</kbd> + <kbd>鼠标滚轮</kbd> 以及 <kbd>Ctrl</kbd> + <kbd>+</kbd> / <kbd>-</kbd> 对应到贴图缩放，再加个 <kbd>Shift</kbd> 则是调节透明度。
