### ISSUE TITLE
希望能够旋转椭圆标记

### ISSUE THREAD

**Issue by nickxsc** [Snipaste/feedback#402]
目前可以通过按住ctrl再点击四角旋转文字，可是无法旋转椭圆和长方形，偶尔会需要标注斜的椭圆，能否为形状标注增加旋转功能，类似旋转文字。

**Comment by HeDonglin** [comment]
好期待

**Comment by cable-zhu** [comment]
我遇到同样的问题，矩形/椭圆标记不能旋转，斜的矩形只能一笔一笔的画，希望尽快增加矩形/椭圆的旋转功能 @liulex
