### ISSUE TITLE
请求增加，截图之后插入文本时竖排排版功能

### ISSUE THREAD

**Issue by caiyuepei** [Snipaste/feedback#404]
截图之后插入文本时，好像只有横排排版，要是您能增加竖排排版就好了。

**Comment by septs** [comment]
该需求更像后期制作
通常截图/贴图中文本插入注重的更多是“备注“或“补充”信息
而不是“艺术”视觉呈现

**Comment by wyghthy** [comment]
同求该功能！楼上所说的“备注“或“补充”信息也是一种后期制作，也是“艺术”视觉呈现，这跟横排竖排似乎并没有什么关系。而且中文传统就是竖排，如果按你的说法那汉字本身就是一种“艺术”视觉呈现。试问当你截一个竖长条时，你觉得横排还是竖排方便？

**Comment by sepwolves** [comment]
同求此功能。因为有些留白部分是竖长条的，旋转固然可以部分实现这个需求。但是转过90度的文字对阅读来说很不友好。如果能够竖排的话就很好了。

**Comment by septs** [comment]
Duplicate of #159
