### ISSUE TITLE
问题：快速保存快捷键冲突

### ISSUE THREAD

**Issue by misybing** [Snipaste/feedback#432]
PS另存为快捷键与Snipaste快捷键冲突，在使用PS的时候，本来不需要截图，按了Ctrl+Shift+S，Sinipaste触发并报错，然额PS的快捷键也用不了。

正常应该是截图过程中可以用Ctrl+Shift+S快速保存，没截图的时候不触发才对，应该是个bug。

<img src="http://wx2.sinaimg.cn/large/a51f1b45gy1fey9h5nvv4j20es0iqwh3.jpg">

**Comment by liulex** [comment]
请提供出错的操作步骤。
除了截图，<kbd>Ctrl + Shift + S</kbd> 在贴图上也起作用的。

**Comment by misybing** [comment]
你可以打开PS，用这个快捷键另存图谱片，问题就会出来。

**Comment by liulex** [comment]
@misybing 并没有问题……

**Comment by misybing** [comment]
验证了，确实没问题了。
