### ISSUE TITLE
有考虑直接打开指定路径的图片吗

### ISSUE THREAD

**Issue by wolfsilver** [Snipaste/feedback#44]
图片可以直接用snipaste打开
类似图片查看器了

**Comment by GregAMO** [comment]
@wolfsilver 
如果剪贴板里面的文件路径，对应的是图片（们）
比如说：文件管理器里面，单选或者多选图片，然后点复制（按Ctrl+C）

然后，按贴图快捷键，就会全部贴出来了~
（我就是这样摘录好PDF里面所有要点，以后全选文件夹里的图片，一齐贴出来~）

>贴图可以贴以下：
Snipaste截的图、剪贴板里的图、
剪贴板里的文字、剪贴板里文件路径所对的图片（们）

**Comment by wolfsilver** [comment]
这个我知道，我现在用的聊天工具，查看图片用的默认图片查看工具（windows 图片查看器），很不方便，所以才。。。


2016-08-10 20:50 GMT+08:00 GregAMO <notifications@github.com>:

**Comment by liulex** [comment]
咦，我记得这个 issue 我回答过了啊，回答去哪了 -.-
图片浏览器我个人用 MassiGra，推荐使用。
另如果需要快速预览图片，可以试试 [Seer](https://sourceforge.net/projects/ccseer/)。

**Comment by liulex** [comment]
“选中文件的时候，按贴图键直接贴出选中文件”
需要这个功能的用户，可以给我这个回复点赞投票

**Comment by toryln** [comment]
非常喜欢Snipaste显示图片的风格，只显示图片内容，需要编辑的时候再按空格调出。
试用过Seer，不支持点击图片本身来拖动图片，支持的编辑操作也相当有限。
如果Snipaste可以作为windows默认的图片查看器，肯定会扩大用户群，
让那些很少截图或贴图的人也享受到Snipaste的简洁与便利。
强烈建议作者添加这个功能~~~~

**Comment by wolfsilver** [comment]
没人有这种需求吗 
(┬＿┬)

**Comment by StarryVoid** [comment]
我不太需要这个功能。。复制一下又不会废多少时间。

**Comment by wolfsilver** [comment]
一次两次是无所谓，但是整天这样搞就烦了

**Comment by StarryVoid** [comment]
@wolfsilver 你要贴多少东西啊。。。。

**Comment by wolfsilver** [comment]
用的聊天工具，查看图片是默认的图片查看器，现在用的是Window自带的，
习惯这种esc直接关闭的

**Comment by GregAMO** [comment]
@wolfsilver 所以说不是从资源管理器打开图片，
而是从其他软件打开？
所以必须去占用一下默认图片打开软件
（其实一直用Picasa做这事，也是ESC就关了）

**Comment by wolfsilver** [comment]
从资源管理器打开也要占用默认图片吧

2016年9月21日星期三，GregAMO <notifications@github.com> 写道：

**Comment by GregAMO** [comment]
@wolfsilver 怎么开始循环问题了，看这问题的二楼。

**Comment by wolfsilver** [comment]
你说的是贴图源文件从剪贴板里取，
我说的是从参数里取

**Comment by Jessieca** [comment]
从指定文件夹读取，可以配置就好了

**Comment by wocala** [comment]
建议楼主自学autohotkey，结合autohotkey可以满足大部分奇怪的需求

**Comment by wolfsilver** [comment]
好久没来了，需求没描述清楚
我意思是，直接双击图片，可以直接贴图出来，类似图片查看器

**Comment by taroxd** [comment]
@wolfsilver 使用 --paste-files 命令行选项，详情请参考帮助文档都
