### ISSUE TITLE
贴图在alt+tab视图中不占位置，但实际使用时会占用位置

### ISSUE THREAD

**Issue by wocala** [Snipaste/feedback#451]
不能算bug吧。场景如下：
场景1.未点击贴图，alt+tab中没有贴图，也不会跳转到贴图
场景2.点击贴图，alt+tab后会回到被截图程序，再次alt+tab转到其他程序。
这样设计使用起来会有不连贯的感觉。

**Comment by liulex** [comment]
没懂你的意思。。贴图因为没有任务栏图标，所以始终不会出现 <kbd>Alt</kbd> + <kbd>Tab</kbd> 里，不连贯体现在哪里？

**Comment by wocala** [comment]
@liulex 
场景:
比如说我有程序a和b，以及贴图c。
按下alt+tab会从a转到b，或b到a
而当贴图获得焦点时，再按下alt+tab，会习惯性地以为从a到b，但真实效果是从c到a。

结果就是需要经常注意焦点是不是在贴图上，如果在的话需要按两次alt+tab才能转到b。

不知道这次解释清楚了吗？没有的话我再想想怎么描述~

**Comment by liulex** [comment]
我觉得”习惯性地以为从a到b“这里是说不通的，焦点已经在 c，所以怎么会以为按下之后是从 a 到 b 呢，不管是 *到* 哪里，总是 *从 c* 的。

**Comment by wocala** [comment]
@liulex 应该是个人习惯吧。
我已经用autohotkey解决了，所以关掉吧。
