### ISSUE TITLE
自动保存到剪切板

### ISSUE THREAD

**Issue by xuyinghaha** [Snipaste/feedback#456]
截图或编辑完成后希望可以自动保存到剪切板，
一般截图后都是编辑文档或者发邮件，现在还需要ctrl+c才能到剪切板...原谅我很懒，这个工具真的很不错，和我以前用的那个截图工具就差这一个功能了

**Comment by EMLVIRUS** [comment]
![image](https://cloud.githubusercontent.com/assets/16912240/26274130/c086920e-3d74-11e7-9e0c-2da31125c811.png)

至于编辑，很难确定完成哪一步后自动保存（交互设计难度过大）

**Comment by xuyinghaha** [comment]
好的十分感谢。

发自我的 iPhone

**Comment by EMLVIRUS** [comment]
此外 （据owner）这是个贴图软件 这是个贴图软件 这是个贴图软件
