### ISSUE TITLE
This application failed to start because it could not find or load the Qt platform plugin "windows"

### ISSUE THREAD

**Issue by FreemanZ** [Snipaste/feedback#457]
win10 x64 专业版 1703
由于学习原因安装了Python2.7和3.5，并分别安装了PyQt
开机显示

![image](https://cloud.githubusercontent.com/assets/7681383/26281113/65cb7658-3e1f-11e7-9a5b-c851bdcc73c2.png)

在官网重新下载zip，放置在D盘，或使用管理员身份运行，皆无法启动程序。

**Comment by ysc3839** [comment]
看看环境变量

**Comment by FreemanZ** [comment]
![image](https://cloud.githubusercontent.com/assets/7681383/26289873/e13fe060-3ed5-11e7-98a0-efa933ebcf58.png)

系统环境变量

**Comment by liulex** [comment]
@FreemanZ 不是 `Path`，请找到包含有 `C:\Python35\Lib\site-packages\PyQt5\plugins` 或 `C:\Python35\Lib\site-packages\PyQt5` 的那个环境变量（变量名称应该是 `QT_` 开头的），这样我这边应该就可以重现一下。

**Comment by septs** [comment]
麻烦您在 cmd 中输入 set 将结果全部拷贝发送到该 issue

**Comment by babopo** [comment]
@liulex ![](http://i1.piimg.com/1949/ed3fcd9a9a7fcdc2.png)
是这个吗

**Comment by liulex** [comment]
@babopo 是的，谢谢。
我会在近日发布新版。
