### ISSUE TITLE
「功能建议」建议增加固定尺寸截图

### ISSUE THREAD

**Issue by ShynHan** [Snipaste/feedback#461]
我经常需要截一些固定尺寸的图，比如说正方形 300px * 300px
或者不限定大小，但是一定要是正方形的图，具体大小截出来之后再调整

或者是一些其他固定尺寸的图，现在我每次截图都要一点一点调整，真的很痛苦

**Comment by liulex** [comment]
#28

**Comment by liulex** [comment]
#28 就是指的`指定尺寸截图`这个功能，至于`指定比例截图`，#198 也已提出。

你的想法只是在实现方式上和原帖不同，没有必要再开一个 issue，直接在相关帖子下讨论即可。

**Comment by clyde3** [comment]
我觉得这个建议很棒，我也很需要

**Comment by alanhg** [comment]
I have the same needs
