### ISSUE TITLE
文本框进入移动模式后，光标没有消失

### ISSUE THREAD

**Issue by Frozen-Shadow** [Snipaste/feedback#462]
重现步骤：
1. f1 进入截图界面
2. 点击添加文本框
3. 输入文字
4. 点击鼠标移动到文本框边缘，鼠标指针变为“十字星”，点击左键进入移动文本框模式
5. 输入框中光标变为一条黑色竖线 “ | ”

**Comment by liulex** [comment]
谢谢你的描述，描述很清晰。
但这是一个 feature，不是 bug……

当光标闪动的时候，方向键是移动光标的位置；
当它没有闪动的时候，方向键是对文字进行整体移动，同时也可以继续输入文字（无需先点击文字使光标先闪动）。

我在实现的时候试了一下 PPT 的，它的做法是进入移动状态时隐藏光标，当输入文字的时候总是在文字最末输入，但我觉得还是保持光标当前的位置更方便，所以有了现在的实现。
