### ISSUE TITLE
系统是windows service 2016 64位的不能运行。 

### ISSUE THREAD

**Issue by mosade** [Snipaste/feedback#466]
32位和64位的都试过，点击了什么反应都没有。没道理啊

**Comment by septs** [comment]
Windows Server 2016？

**Comment by mosade** [comment]
对

**Comment by liulex** [comment]
Snipaste 版本？如是 1.13.2，Snipaste 目录下的 crashes 文件夹是否有 .dmp 文件？

**Comment by mosade** [comment]
Snipaste 版本是 1.13.2。但是目录下没有crashes 文件夹。

**Comment by liulex** [comment]
那么 splog.txt 呢？

**Comment by mosade** [comment]
解决了。貌似是Windows defender的问题。我关了就行了。这个杀毒一点提示没有我也是醉了。
