### ISSUE TITLE
4个建议=滚动截屏+增加截图时下面工具的快捷键+在画图工具栏里添加 “选择工具”+添加类PS里的套索选择工具

### ISSUE THREAD

**Issue by ToBeGeekBoy** [Snipaste/feedback#467]
Tips for Snipaste
1.	添加滚动截屏

2.	截图界面，对下面的画图工具，增加快捷键。如下图所示：
 
![qq 20170528012711](https://cloud.githubusercontent.com/assets/11906842/26525692/3aa39f00-4392-11e7-85cd-bcf70f4a20e7.png)

-	快捷键支持自定义。
-	建议快捷键：正方形（alt/ctrl+1），圆型（alt/ctrl +2）….
-	快捷键仅在截图中有效

3.	在截图下面的画图工具中，添加 选择工具。
选择工具的功能：单击选择工具后，可以单击之前 画过的框或者直线等，然后可以移动/删除选中的目标。
需要该功能的是由于：编辑半天，发现很早多画了几个宽或者几条线，这时候，就悲剧了，只有单步的撤销或者重来。如果撤销，后面编辑的就白弄了，重来就更惨。
添加该功能就是一个后悔药。

4.	在截图下面的画图工具中添加 “任意选择工具”。类似于PS 的套索

工具。

Pillar Peng
一个很喜欢这款截图工具的人（只给了你（们）5块钱）

**Comment by septs** [comment]
1. see #19
2. @liule
3. @liule 
4. @liule

**Comment by GregAMO** [comment]
@ToBeGeekBoy 补充
2. 在能看见工具栏的状态下，可以按 Ctrl + Tab 切换各类工具
3. 二次编辑将在未来专业版中出现
目前你可以用橡皮擦擦掉他
