### ISSUE TITLE
弱弱的问一下：支持截图鼠标右键时的图吗？

### ISSUE THREAD

**Issue by nottellyou** [Snipaste/feedback#468]
弱弱的问一下：支持截图鼠标右键时的图吗？

我操作了好几次都没有成功。是我的姿势不对吗？

**Comment by Genteure** [comment]
没记错的话，这个是由你使用的快捷键决定的。我用的快捷键是 PrtSc ，没有任何问题，。

**Comment by nottellyou** [comment]
原来是我的使用姿势不对，谢谢楼上的。

**Comment by liulex** [comment]
https://docs.snipaste.com/#/zh-cn/troubleshooting?id=%e6%97%a0%e6%b3%95%e6%88%aa%e5%8f%96%e8%8f%9c%e5%8d%95%ef%bc%8c%e4%b8%80%e6%8c%89%e6%88%aa%e5%9b%be%e5%bf%ab%e6%8d%b7%e9%94%ae%e8%8f%9c%e5%8d%95%e5%b0%b1%e6%b6%88%e5%a4%b1%e4%ba%86

**Comment by nottellyou** [comment]
呵呵，这个文档你都找出来了。我把快捷键修改成和QQ的一样了，用于替换QQ截图。主要是生成的图片体积大小比QQ的要小。后来发现怎么也截不了菜单的图。原来是alt的问题。已经换了截图的快捷键了。

**Comment by Genteure** [comment]
@liulex 就是作者本人，当然能“找出来”了

**Comment by nottellyou** [comment]
谢谢 @liulex 在百忙之中解答我的问题。
