### ISSUE TITLE
贴图复制图像后无法在UWP QQ中粘贴

### ISSUE THREAD

**Issue by codehz** [Snipaste/feedback#470]
发现了 bug？
* 请描述一下重现的步骤，越详细越好
  1. 创建贴图
  2. 复制图像
  3. 打开UWPQQ
  4. 打开某个会话
  5. 粘贴
  6. 什么都没有发生┑(￣Д ￣)┍
* 注：自带“截图工具”复制后可以正确的粘贴

**Comment by liulex** [comment]
试试
![default](https://cloud.githubusercontent.com/assets/2010459/26536732/93158e8e-446c-11e7-98ea-04afe2a46219.png)

**Comment by taroxd** [comment]
![image](https://cloud.githubusercontent.com/assets/6070540/26536757/d2a9e266-446c-11e7-9b72-c86e82eee15e.png)

**Comment by codehz** [comment]
这个选项不开的时候复制的是什么形式的东西，压缩格式的吗？如果这样的话，那我建议可以两个功能都放在菜单里。。。毕竟有时复制图片是为了上传图床，bitmap格式不仅自己传好久，别人看也很慢。。。

**Comment by liulex** [comment]
@codehz 我觉得应该给 UWP QQ 提这个问题，而不是让 Snipaste 增加菜单项，毕竟没有哪个软件会在菜单中加上“复制图片”和“以 xx 格式复制图片”。
