### ISSUE TITLE
希望增添滚动截图功能

### ISSUE THREAD

**Issue by mdc9** [Snipaste/feedback#471]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by mdc9** [comment]
比如再使用word时，希望将多页内容截图成一长图，这时候大多数截图工具都不能实现，需要利用其他软件拼图，这就比较麻烦了。故希望snipaste有此功能。另外最好可以拼图

**Comment by septs** [comment]
see #19

**Comment by septs** [comment]
@mdc9
如果是 浏览器 请自行寻找合适的截图拓展使用
如果是 Office 请打印成 PDF 文档传播
