### ISSUE TITLE
希望能添加自动识别网页图片的功能

### ISSUE THREAD

**Issue by 23330** [Snipaste/feedback#472]
移动到网页图片自动调整到网页图片的大小

**Comment by taroxd** [comment]
@23330 要网页上的图片为什么不直接右键？

**Comment by septs** [comment]
针对浏览器的截图，请去浏览器中商店寻找解决方案。

**Comment by liulex** [comment]
@23330 
https://docs.snipaste.com/#/zh-cn/troubleshooting?id=%e6%88%aa%e5%9b%be%e6%97%b6%e6%97%a0%e6%b3%95%e8%87%aa%e5%8a%a8%e9%80%89%e5%8f%96-chrome-%e6%b5%8f%e8%a7%88%e5%99%a8%e7%aa%97%e5%8f%a3%e7%9a%84%e9%a1%b5%e9%9d%a2%e5%85%83%e7%b4%a0
