### ISSUE TITLE
alt+w移动失效

### ISSUE THREAD

**Issue by forever91** [Snipaste/feedback#473]
在截图时, alt+a +d +s 都可以移动1像素, alt + w失效了,希望尽快解决, 这个功能特别好用

**Comment by EMLVIRUS** [comment]
>在截图时, 移动 1 像素

您说的是这个嘛？
![image](https://cloud.githubusercontent.com/assets/16912240/26611972/5a592a3c-45e4-11e7-8c96-9eb3a3f51764.png)

**Comment by forever91** [comment]
就是这个截图时移动一像素，但是我习惯用左手操作键盘，在没有改过这个设置前提下，亲测alt+wasd也可以，但是就是alt+w不行

发自我的 iPhone

**Comment by forever91** [comment]
不好意思，我根据你发的图找到了设置里面的热键，才发现我所说的是移动鼠标，才知道不需要按alt，因为之前是同事在教我用的，我一直用的是alt＋，现在看来alt＋也是可以不过就alt＋w时热键冲突了，我现在完全明白了不是bug而是我操作失误了，我会告知同事们纠正，感谢你的解答

发自我的 iPhone
