### ISSUE TITLE
高分屏设置DPI缩放后宽高计算不准确

### ISSUE THREAD

**Issue by hooray** [Snipaste/feedback#474]
我的笔记本是 3000 * 2000 的分辨率，DPI 设置为 200% 缩放，所以实际宽高是 1500 * 1000，但截图的时候显示还是 3000 * 2000 下的宽高，并且框选的位置定位也不对，这一点和 #388 描述的问题一样

**Comment by septs** [comment]
请将该问题请在 #388 下合并讨论
