### ISSUE TITLE
怎么没有一个截屏软件能直接画数字图章的

### ISSUE THREAD

**Issue by wskia161** [Snipaste/feedback#475]
做教程的时候，能直接画线或画框时就出现对应顺序的数字图章能让别人一看就知道步骤的顺序，真是太方便了，但没有一个截屏软件有这个功能。
![1212](https://cloud.githubusercontent.com/assets/4724317/26642393/265a587e-4660-11e7-9f01-d03fee802eff.JPG)
![6462d00fgw1end5u26414j20dw0btgmo](https://cloud.githubusercontent.com/assets/4724317/26642394/26700660-4660-11e7-9e85-f7011d45ce1f.jpg)

**Comment by septs** [comment]
该问题请合并至 #227 讨论。

**Comment by EMLVIRUS** [comment]
@wskia161 请尝试shareX
