### ISSUE TITLE
高DPI 1.13.3 鼠标指针异常

### ISSUE THREAD

**Issue by kenzen** [Snipaste/feedback#481]
发现了 bug？
* 高DPI 1.13.3 鼠标指针异常

鼠标指针位置，和计算出的截图区域偏移

见截图
![screenshot](https://cloud.githubusercontent.com/assets/824925/26769967/a0fafe16-49e5-11e7-8c95-0de221b6813a.png)

**Comment by septs** [comment]
see #338

**Comment by liulex** [comment]
这应该是一个新的问题。
@kenzen 请下载[旧版](https://bitbucket.org/liule/snipaste/downloads/Snipaste-1.13.2-x64.zip)，解压后将新版的 exe 替换进去运行（即新版 exe + 旧版 dll），看问题是否还存在。这是为了确认问题是否和 Qt 5.9 有关。

**Comment by kenzen** [comment]
新版exe+旧版dll，测试
![screenshot2](https://cloud.githubusercontent.com/assets/824925/26770341/92507e4c-49e8-11e7-841c-99f1e5c3916b.png)
正常

**Comment by liulex** [comment]
@kenzen 谢谢，问题已重现，会尽快解决。
