### ISSUE TITLE
截图状态下，按住 ALT+W 使鼠标指针往上移动失效

### ISSUE THREAD

**Issue by toryln** [Snipaste/feedback#484]
1、按快捷键进入截图
2、按住ALT，调出十字线
3、按AWSD移动指针，其中ASD均可左移/下移/右移指针，而 ALT+W无法上移指针

多台win10 x64位电脑下，snipaste版本 1.13.4，均有问题
详情见动态图

![aaa](https://user-images.githubusercontent.com/2637718/26873283-e11069d8-4bab-11e7-89b1-313b503f5b5e.gif)

**Comment by EMLVIRUS** [comment]
@toryln 已复现。。。。

**Comment by toryln** [comment]
OK，你们能重现就可以了^.^

**Comment by liulex** [comment]
@toryln @EMLVIRUS 
我复不了啊，只是 Alt + W 被占用了吧，见 #473

**Comment by EMLVIRUS** [comment]
@toryln 我这里是 QQ 语音输入默认占用 Alt+W

**Comment by toryln** [comment]
这是偶现的，但概率非常高。我自己的电脑也有时可以，有时不行。
我以前一直用也是没问题的，好像是最近几个版本才出现的。
开始我也怀疑是热键被占用，但我在几个同事的电脑上试了都有问题。
#473 的单就是我让我同事提的 ;)

**Comment by toryln** [comment]
@EMLVIRUS 还真是，把QQ退了就行了
原来我之前一直没开QQ，所以没问题，最近开了几次QQ才有问题

**Comment by toryln** [comment]
单结了吧
