### ISSUE TITLE
【bug】截图时编辑选择字体/调节模糊时退出截图

### ISSUE THREAD

**Issue by zwt-ss** [Snipaste/feedback#485]
问题：
1、截图
2、在编辑框中选择文字
3、点击选择字体的框框
就会自动退出截图
在调节模糊度（就是马赛克旁边那个滑块）的时候也会出现相同问题
只在截图时会导致退出截图，编辑贴图时使用正常
win7，64位，1.13.4

**Comment by liulex** [comment]
谢谢反馈，该 bug 是 v1.13.4 不小心引进的，会在下一版修复。
