### ISSUE TITLE
历史纪录管理功能

### ISSUE THREAD

**Issue by gameclamp** [Snipaste/feedback#486]
可以按照日期分类、截图时目标程序分类、最近截图等等管理历史纪录。

**Comment by liulex** [comment]
这些功能似乎一般的图片管理软件即可胜任，没必要由 Snipaste 来做。
有价值的截图通过贴图进行管理即可，以后会增强贴图管理。

**Comment by gameclamp** [comment]
主要是按目标程序分类有用，找起来很有目的性，这个普通图片管理软件做不到

**Comment by liulex** [comment]
有计划在文件命名规则里加入程序名称或窗口标题作为变量，应该可以满足你的需求。

**Comment by kerhbal** [comment]
@liulex 附议一下这一点，希望支持统筹管理的历史记录界面。
原因：虽然别的软件可以达到此效果，但是无法联通到snipaste中来，尤其无法读取snipaste截图的过程。因snipaste的历史记录并不只是一张图片，而是截图范围内外的原始图像以及当初编辑的可撤销操作。

举例：我认为在截图方面snipaste最好的一点是用 `,` `.` 可以看到以前的记录，并且可以撤销某些编辑操作然后重新编辑。因为我经常会对截图进行很多标注，用别的软件如果标注结束保存关闭后发现有一点标错了就得重来，而用snipaste完全可以读取到这个历史记录然后撤销到错误的那步重新来过。

现在我想要看到以前的历史记录需要的是一直按 `,` 直到它出现为止，实在效率有些低。而如果只是在自动保存目录中翻找文件又无法还原以及重做当初的标注过程。

希望能考虑一下，谢谢！
