### ISSUE TITLE
希望增加桌面贴图的透明图调整

### ISSUE THREAD

**Issue by ekin1106** [Snipaste/feedback#489]
希望能增加截图后贴图能够调整下透明度，这样的话有时候在做参考图的时候，能够叠加，相比放在旁边参考的话，又多了一种参考方式
谢谢有这么好的软件，真的非常棒～

**Comment by GregAMO** [comment]
@ekin1106 桌面贴图已有透明度调整功能：
Ctrl + 鼠标滚轮 或 Ctrl + +/-增加/减少贴图的透明度
请至少仔细阅读内置快捷键列表
