### ISSUE TITLE
能否给矩形输入固定的宽高及圆的直径呢

### ISSUE THREAD

**Issue by HeDonglin** [Snipaste/feedback#491]
有时候画图我需要两个相同的宽高的矩形,不得不在第一个矩形上画出然后拖动,感觉很不方便,不知能否实现该功能
来自一个强迫症的需求!
非常感谢你!

**Comment by HeDonglin** [comment]
如果宽高可以设置值了,能否对该矩形进行再次编辑,或者能否复制一份该矩形从而进行下一次的拖动;
原来我有着各种奇葩的需求

**Comment by StarryVoid** [comment]
想要的属于图片编辑了。。如果强迫症比较厉害可以用WASD微调大小。。至于复制和再次编辑肯定需要图层相关的东西了。。

**Comment by HeDonglin** [comment]
微调太不好使了...

**Comment by liulex** [comment]
画图形状的复制、剪切、粘贴和删除在专业版的计划中。

指定形状宽高应该不会考虑，这个不是用来做设计的。。 🌚

**Comment by HeDonglin** [comment]
有了复制，剪切，粘贴和删除这几个功能以后将会更加方便，顺便问一下对矩形再次编辑是否有考虑，有时候需要重新对画图拖动位置，我一般是先撤销然后再进行恢复就可以拖动了

**Comment by liulex** [comment]
见 #79
