### ISSUE TITLE
Feature request: save tool options

### ISSUE THREAD

**Issue by rolandtoth** [Snipaste/feedback#493]
It would be great if Snipaste would save previously set tool options, eg. color, tool type (ie type of arrow), blur size and so on. Now I have to manually re-set each setting when I create screenshots with the same style, which is very inconvenient.

**Comment by liulex** [comment]
For sceenshot's in-place edit, the options are actually saved, which means you can use the same setting for this screenshot and the next screenshots. They remain the same even after you restart Snipaste.

The default settings are only used on newly created image windows, i.e., those pasted by <kbd>F3</kbd>.

**Comment by rolandtoth** [comment]
Thanks for clarifying. What I would need is a "global" setting, if I get it right this is not available atm.

However I think I can use "snip" instead "paste" in the future.

**Comment by liulex** [comment]
But there could be mutiple toolbars at the same time (the snipping window has one and each image window has one). All the toolbars use one set of settings would be unreasonable I think. They should be independent on deach other.

However, I do plan to offer an option to set the toolbar settins of the newly created image window.
The options could be 'Use the fixed customized settings', 'Use the settings of the snipping window', 'Use the settings of the last active toolbar'.

**Comment by rolandtoth** [comment]
I see, thanks. These new options would come handy.
