### ISSUE TITLE
Chrome不支持开启右键菜单的情况下截图

### ISSUE THREAD

**Issue by wang93wei** [Snipaste/feedback#495]
发现了 bug？
* 请描述一下重现的步骤，越详细越好

在Chrome里开启了右键菜单时，按F1无法截图。

Chrome版本 61.0.3128.0（正式版本） （64 位）

**Comment by septs** [comment]
see #468

**Comment by wang93wei** [comment]
延时截图SHIFT+F1没效果啊？？？？

**Comment by septs** [comment]
请不要使用 Fn 按键

**Comment by wang93wei** [comment]
没用FN，我是PC，不是笔记本

**Comment by wang93wei** [comment]
按F1和Shift+F1都不好使。

啥提示也没有，默认按键，也没设置其他的带ALT的截图按键，桌面右键按F1截图都好使。

**Comment by liulex** [comment]
@wang93wei 文档里说的很明白，目前为止快捷键相关的问题，没有一个是文档没覆盖到的。
https://docs.snipaste.com/#/zh-cn/troubleshooting

**Comment by ysc3839** [comment]
@wang93wei
