### ISSUE TITLE
Chrome不支持右键截图

### ISSUE THREAD

**Issue by wang93wei** [Snipaste/feedback#496]
按F1和Shift+F1都不好使。

啥提示也没有，默认按键，也没设置其他的带ALT的截图按键，桌面右键按F1截图都好使。

**Comment by wang93wei** [comment]
我反馈问题呢，不是闹着玩，认真点可以吗？

**Comment by wang93wei** [comment]
关了吧关了吧，才发现没有管理员权限无法截图。敢不敢在没有管理员权限的时候给个提示，部分高级功能不可用。

**Comment by wang93wei** [comment]
关了吧关了吧，才发现没有管理员权限无法截图。敢不敢在没有管理员权限的时候给个提示，部分高级功能不可用。

**Comment by septs** [comment]
see #495 请不要重复创建相同问题

**Comment by GregAMO** [comment]
@wang93wei 你可以通过如下方式查看 Snipaste 是否获得管理员权限：
鼠标悬停在 Snipaste 图标上
版本号后显示 # 则已获得管理员权限
