### ISSUE TITLE
建议：可以根据使用工具的频率来自动调整工具的位置

### ISSUE THREAD

**Issue by nottellyou** [Snipaste/feedback#497]
建议：可以根据使用工具的频率来自动调整工具的位置

比如说：我经常使用矩形，箭头、文字标注，那么是不是可以将这三项放到最前面呢？？

谢谢。

**Comment by liulex** [comment]
没有必要自动调整，位置频繁变动反而会降低操作效率吧。
以后可以考虑自定义工具图标顺序。

**Comment by nottellyou** [comment]
对，你说自定义也行。

**Comment by EMLVIRUS** [comment]
@nottellyou 个人感觉自动调频功能只有当待调位元素数量较大时才有意义 比如输入法的单字单词等 snipaste工具栏按钮的数量就很尴尬
