### ISSUE TITLE
快捷键没有使用到但是跟VS的有冲突

### ISSUE THREAD

**Issue by msccreater** [Snipaste/feedback#499]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好
在开启snipaste的时候无法在VS中使用ctrl+F3查找内容,在snipaste中也没看到有占用这个快捷键,关掉snipaste之后就可以正常在vs中查找内容了,希望修改掉这个快捷键的占用问题

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by septs** [comment]
请明确指出是什么快捷键冲突 并且请附上 splog.txt

**Comment by septs** [comment]
Snipaste 的快捷键 您可以自行设置

**Comment by liulex** [comment]
请贴出 `首选项` - `快捷键` 的截图。

**Comment by msccreater** [comment]
@liulex [其他的内置快捷键都没有修改过,只修改了截图部分的,平时使用VS,C++默认开发环境的快捷键](https://drop.me/M0g0Ea),不知道怎么上传截图,我放到这个链接上了
![snipaste_20170620_101034](https://user-images.githubusercontent.com/1811267/27313626-6bd3cb9c-55a1-11e7-9103-7198d218852c.png)

**Comment by liulex** [comment]
1.13.6 的日志文件（splog.txt）中有记录快捷键的绑定和解绑，请问其中是否有提到 Ctrl+F3？

**Comment by msccreater** [comment]
@liulex 我一直在公司的内网使用,刚更新了新最新的版本,快捷键冲突解决了,原来出问题的版本是1.13.1,感谢你的热心回复,很喜欢这款软件不知道什么时候回开源吗

**Comment by liulex** [comment]
暂时不会。

**Comment by msccreater** [comment]
用了一段时间,快捷键冲突问题再次出现,很莫名,我查看了日志文件,没有一条有关快捷键绑定的日志信息,但是可以正常实用快捷键进行截图,关掉软件后VS的查找功能快捷键恢复正常,,打开软件就会导致VS的查找功能快捷键失效,

**Comment by liulex** [comment]
请把日志等级改为调试或追踪。

**Comment by StarryVoid** [comment]
@liulex .\powercfg.exe /energy /duration 10  试着运行一下这个命令看看电源选项有什么差别？

**Comment by msccreater** [comment]
@liulex  改了下日志模式,看到有快捷键绑定了,但是我没有设置过这个快捷键
![snipaste_20170810_123604](https://user-images.githubusercontent.com/1811267/29154681-c14b681a-7dc8-11e7-9d7a-c8c4747e0887.png)

**Comment by liulex** [comment]
@msccreater 这其中应该有个 bug…… 请贴出你 config.ini 中 [Hotkey] 下面的所有内容（暂时不要手动更改），以及你现在用的 Snipaste 版本是？

**Comment by msccreater** [comment]
@liulex 暂时还没有更新,我估计也是bug,但是不知道怎么出现的,以前就出现过一次
![snipaste_20170811_160631](https://user-images.githubusercontent.com/1811267/29205410-40854a9c-7eaf-11e7-8302-db28e1849720.png)
![snipaste_20170811_160658](https://user-images.githubusercontent.com/1811267/29205413-4409b05e-7eaf-11e7-8cf8-4a506c1d301b.png)

**Comment by liulex** [comment]
啊，我明白了，因为你关闭了贴图的自动备份，所以快捷键那里“隐藏/显示所有贴图”就被隐藏了，但实际上它还是被注册了。
这是个 bug，我会在下版本修复。
现在你只需要把上面 `switch=` 的那一行删掉再启动 Snipaste 就行。

**Comment by msccreater** [comment]
@liulex 非常感谢你的热心回复,很喜欢这款软件,因为平时工作要开2个VS,然后实用截图的时候就会很卡,尤其是每次启动开始截图的时候,然后我把元素识别关掉了,貌似好点

**Comment by liulex** [comment]
修改 `config.ini` 之前要先关掉 Snipaste.
