### ISSUE TITLE
贴图拖动到超出上方屏幕时，贴图的下方内容会被裁剪

### ISSUE THREAD

**Issue by miaowm5** [Snipaste/feedback#500]
win7系统，如图所示，这样一个贴图
![image](https://user-images.githubusercontent.com/7985604/27266721-d262dc80-54d5-11e7-99f5-f2d88cc5c738.png)
我将它拖动到超过屏幕上方时，贴图下方就被裁掉了
![image](https://user-images.githubusercontent.com/7985604/27266745-fe6be95c-54d5-11e7-9727-ef826ecb77bd.png)
重新拖回屏幕内，被裁掉下方的贴图也没有变化
![image](https://user-images.githubusercontent.com/7985604/27266765-1b5185a4-54d6-11e7-9e95-d4b75e61a4e2.png)
调整贴图缩放之后，贴图被裁剪掉的下方内容才会重新出现

**Comment by liulex** [comment]
这个问题有用户跟我说过，当时和他一起测试了很久也没找到解决办法，而且只有他的系统（和你一样是 Win 7）有问题。
最后他是通过重装 Win 7 解决的……
下次我试试另一个实现方法再联系你测试一下~

**Comment by ZeronoFreya** [comment]
win7有一个坑爹的功能，将标题栏拖出屏幕顶部后会缩回来，但坑的是只有标题栏缩回来，导致窗口高度缩小...问题是贴图是整体拖动的（相当于拖动标题栏），结果就是高度缩水了
此功能可以默认禁用
但遗憾的是，我不知道怎么搞，毕竟不是这个专业的

**Comment by StarryVoid** [comment]
请尝试一下注册表中找到以下键值：HKEY_CURRENT_USER\Control panel\Desktop\WindowsArrangementActive
并将此键值设置为 1 ，保存后重启，查看一下此问题是否解决

**Comment by liulex** [comment]
@miaowm5 @ZeronoFreya 
按照 @StarryVoid 的办法应该可以解决。
