### ISSUE TITLE
請問之前原本有的截圖後畫框可以調整線寬的選項不見了?

### ISSUE THREAD

**Issue by wujer** [Snipaste/feedback#501]
Bug report?
* 請問之前原本有的截圖後畫框可以調整線寬的選項不見了?

Feature request?
* 希望可以調整線寬  , sorry if I missing configuration
https://github.com/liulex/Snipaste-Feedback/issues/282

---

**Comment by septs** [comment]
see https://docs.snipaste.com/#/zh-cn/changelog?id=v113
see #276

**Comment by wujer** [comment]
sorry , that's my missing :( 
I found that.
