### ISSUE TITLE
希望增加截图边界微调功能

### ISSUE THREAD

**Issue by CrabAss** [Snipaste/feedback#503]
【请求新功能】希望能增加截图边界微调功能：
截图编辑模式时，拖拽截图边界时按住 Ctrl（或其他键）可以进行精细调整（例如鼠标移动 10 像素 = 边界移动 1 像素，而非普通的 1:1 拖拽）。
因为平时使用电脑时鼠标灵敏度设置比较高，而截图时又需要精细调整截图边界，所以希望增加此功能。多谢开发者的努力！

**Comment by septs** [comment]
see https://docs.snipaste.com/#/zh-cn/key-bindings?id=%e9%80%9a%e7%94%a8
