### ISSUE TITLE
建议添加关闭放大镜功能

### ISSUE THREAD

**Issue by Summving** [Snipaste/feedback#504]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

目前在贴图上截图经常把放大镜也截进去了。在设置项里面找不到关闭放大镜的选项。截图我基本不用放大镜功能，该功能对于我来说只是阻碍作用。

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by septs** [comment]
能简单描述下使用场景吗？

**Comment by Summving** [comment]
如gif，我贴了图之后再次截图。还有，本身不习惯使用放大镜，太碍眼太占地方，而且很多时候截图不好精确截图，进行粗略截图的时候就根本不需要放大镜了。
![101](https://user-images.githubusercontent.com/23720634/27526171-ab23ed70-5a76-11e7-8e62-0cb784747a2a.gif)

**Comment by ZeronoFreya** [comment]
我猜你截图的快捷键应该是ALt+...
导致响应了内置快捷键Alt（显示放大镜）

**Comment by Summving** [comment]
是的，我设置了快捷键ctrl+alt+a。

**Comment by blackdog2021** [comment]
这个问题困扰了我好久了，强烈建议增加这个功能。除了这个问题，其他的都很完美~
