### ISSUE TITLE
希望可以自动调整界面元素的位置

### ISSUE THREAD

**Issue by SilentDepth** [Snipaste/feedback#505]
选择截图区域时，放大镜默认显示在鼠标位置的右下角，这在需要较大范围参考画面其他内容进行定位时比较困扰（因为放大镜刚好遮盖住了一部分画面内容）。如果可以自动调整放大镜的位置，例如在用户开始拖拉选区时始终保持放大镜显示在选区外侧，或通过某种快捷键切换放大镜的显示位置，应该会好一些。

类似的问题在工具栏上也存在。进行全屏截图并想在右下角进行标注时，无法移动的工具栏是一个明显的困扰。像输入法候选栏那样可以拖动就能解决这个问题。

感谢作者的开发。

**Comment by liulex** [comment]
见 #255
