### ISSUE TITLE
快捷键冲突的一些问题

### ISSUE THREAD

**Issue by yhnmj6666** [Snipaste/feedback#506]
你好！我非常喜欢这个软件。以前我是用Ctrl+Shift+S作为截图快捷键的，但是更新到Win10 Creator之后这个快捷键就与系统的截图快捷键冲突了。我想重新让Snipaste拿下这个快捷键，但是我找不到解除系统快捷键的方法。
我现在是使用AutoHotKey来运行“Snipaste.exe --snip”命令来截图，但是我注意到
1.通过命令行方式拉起的Snipaste需要重新启动进程，伴随着总计约20M左右的磁盘I/O
2.如果磁盘比较忙，那么Snipaste的响应时间就比较长，启动速度也随之直线下降，对于我来说体验很不好。

我的Snipaste程序是随系统启动、常驻内存的。我希望通过命令行方式拉起的Snipaste可以检测一下系统中是否有Snipaste已经在运行，如果有的话就让另一个来执行截图的动作。

我知道我这个问题十分罕见，但是我十分喜欢这个软件，也希望它能越做越好。我希望能够实现这个功能：在系统中已经有Snipaste的情况下，不再启动新进程，让已有的进程直接执行截图操作。
这是今天的log，希望有所帮助。
[splog-2017.6.23.txt](https://github.com/Snipaste/feedback/files/1098297/splog-2017.6.23.txt)

**Comment by liulex** [comment]
系统的是 Win + Shift + S 吧？

**Comment by liulex** [comment]
运行 `Snipaste.exe --snip` 的时候，实际就是由已有的进程进行截图的。
第二个进程在通知第一个进程就自动退出了，但这其中的进程启动和“通知”过程造成的延迟总是不可避免的。

**Comment by liulex** [comment]
如果想要使用已经被系统占用的快捷键，如 <kbd>Win + d</kbd>，AHK 是可以做到的。

首先将 Snipaste 的截图快捷键设置为一个不常用的组合键，如（<kbd>Ctrl + Alt + Shift + S</kbd>，或者 <kbd>F20</kbd>），然后将你想要的快捷键映射到这个按键就行了。

需要注意的是，不能使用这种方式进行映射：
> #d::F20
这样不会触发 <kbd>F20</kbd> 所注册的快捷键，需要用 `Send` 或者 `SendInput`，如：
> #d::SendInput {F20}

至于如何将截图快捷键设置为 <kbd>F20</kbd>：关闭 Snipaste，在 `config.ini` 找到 `Snip=`这一行，改成 `Snip=F20`，保存，重启 Snipaste 即可。

**Comment by yhnmj6666** [comment]
感谢，这个解决方案非常好！希望Snipaste能越做越棒！
