### ISSUE TITLE
关于边框宽度、手写宽度、设置生效时间的建议

### ISSUE THREAD

**Issue by enswing** [Snipaste/feedback#510]
1、希望可以设置正方形边框的宽度，目前的这种标注出来太细了，有时候根本看不清楚
2、希望可以设置写字的宽度
3、设置颜色和标注形状（正方形与圆形）的功能，在设置之后生效

**Comment by septs** [comment]
1. #282 
2. #282 
3. ？？？

**Comment by enswing** [comment]
我觉得应该可以设置粗细
3、现在是我标注了一个正方形，然后设置颜色，之前画的正方形就变了颜色，可是我是想让这个设置在接下来起作用

**Comment by septs** [comment]
3. Snipaste 逻辑并没有问题
因为您对于此操作的焦点并没有丢失
此时可以认为您要对当前操作修改颜色
