### ISSUE TITLE
截图瞬间与NOD32有冲突

### ISSUE THREAD

**Issue by riverai** [Snipaste/feedback#511]
只要用Snipaste截图，按下Ctrl+C的一瞬间，就会弹出窗口，ESS需要你的注意。

保存文件的时候也是一样的道理，就是截图的那一瞬间，必然会弹出提示。

Bitedefender，AVG，MSE没有发现这一个个问题，ESS10有。_

但是， Bitedefender虽然不会在截图瞬间如何，却会自动屏蔽删除Snipaste.exe文件。

**Comment by ysc3839** [comment]
添加信任

**Comment by septs** [comment]
请自行联系 杀软 厂商沟通处理
该问题与 Snipaste 无关

**Comment by liulex** [comment]
@riverai 我有空会试试看，但正如楼上所说，这是杀软的检测策略或者设置问题，我不觉得 Snipaste 应该迁就杀软。

**Comment by liulex** [comment]
从官网下载并安装 BitDefender 试了一下，不管是运行 32 位还是 64 位 Snipaste，并没有看到 BitDefender "自动屏蔽删除 Snipaste.exe 文件" ……
手心输入法的 PalmInputConfig.exe 倒是被它干掉了 😂

**Comment by liulex** [comment]
![default](https://user-images.githubusercontent.com/2010459/27768548-29f4e614-5f49-11e7-8b22-705a1e72a14e.png)

**Comment by EMLVIRUS** [comment]
@liulex NOD32 的启发式扫描规则是非常 奇葩 的 早在去年我还用的时候甚至把自己家的另一个免费工具杀掉了

**Comment by riverai** [comment]
@liulex 确实是这样不是立即的。

我是用了好几天Bitedefender，突然就给我把snipaste.exe干掉了，然后我添加排除。
几天之后更牛逼的事情发生了，我明明添加了排除，再次没有任何提示的把snipaste.exe干掉了，还直接干掉了老版本everything.exe。

对了，我也是用的Bitedefender免费版，就前半个月的事情。

**Comment by liulex** [comment]
@riverai 
我这 NOD32 也没事……
![default](https://user-images.githubusercontent.com/2010459/27769628-acbcd14e-5f60-11e7-8a27-4e23a0b57bac.png)
这次是把 Syncthing 干掉了…… 😂

**Comment by liulex** [comment]
所以这些杀软我没办法了，只盼 MSE 别报就好了……
也可以等等即将发布的 Windows Store  版本。

**Comment by riverai** [comment]
@liulex  这就尴尬了..
我把什么潜在不安全扫描都打开了。Windows store版本不错啊。。

刚刚我本来想录像的，结果打开了bandicam录制了一会儿，发现录制的时候截图就不会弹出ESS需要你的注意，然后退出bandicam，现在也不会弹ESS需要你的注意了，奇怪？

当时还断网了一下.....

**Comment by liulex** [comment]
刚刚试了 ”启用潜在不安全应用程序检测功能“，也没反应啊。

算了，玄学…… ╮(╯▽╰)╭

**Comment by riverai** [comment]
@liulex  玄学..
总结下这个玄学闪人了..

ESS:
ESS主窗口在桌面的时候，截图瞬间这个窗口就会突然变黄色，然后变回正常颜色。
如果ESS窗口是关闭的，那么就会弹出一个通知需要你的注意。
在这个问题还存在的时候，关闭了三个潜在的不安全扫描选项，结论是无效。
常识在hips里面添加规则允许snipaste.exe的所有操作，无效（缺乏经验，不确定是不是完全正确）。

打开bandicam录制了会儿之后现在又不弹出了，就好像物理定律突然改写了一样。

Bitedefender:
开始没事，用几天之后会突然屏蔽删除文件。
添加排除之后可以用几天，然后还是会被突然删除文件。
