### ISSUE TITLE
切换分辨率后托盘图标变模糊

### ISSUE THREAD

**Issue by autodotua** [Snipaste/feedback#512]
![image](https://user-images.githubusercontent.com/26277009/27782799-87ab9b96-6006-11e7-88b3-4ad214203458.png)

如图，因为进游戏、远程桌面导致分辨率变动后，托盘图标会变模糊。
Win10x86最新Update。

**Comment by septs** [comment]
Snipaste 是否为最新版本？

**Comment by autodotua** [comment]
是最新的版本，1.13.6（2017.06.09），64位

**Comment by autodotua** [comment]
在我的程序里就这个和ssr有此问题，两个都是.Net开发的，可能有关系

**Comment by ysc3839** [comment]
@autodotua Snipaste 是用 C++ 的 Qt 框架开发的。

**Comment by autodotua** [comment]
看来我记错了，谢谢提醒

**Comment by Athrob** [comment]
我也遇到了, 可能跟图标文件有关系.

**Comment by liulex** [comment]
在下个版本会修复，但还是有一定几率会模糊，没有找到 100% 修复的方法。

**Comment by autodotua** [comment]
十分感谢

**Comment by autodotua** [comment]
对不起不小心点到了close

**Comment by septs** [comment]
http://chinese.engadget.com/2017/07/09/latest-windows-10-preview-takes-the-headache-out-of-high-dpi/

或许在 1709 的更新中会有间接性改善 但目前没有收到相关报告 该新闻仅供参考

**Comment by Skimige** [comment]
21H2，仍未修复，部分其他应用没问题

![Snipaste_2021-11-25_17-08-22](https://user-images.githubusercontent.com/9017470/143412428-6578f940-04ae-4df2-8553-83d71da27232.png)

图上 Listary 6、QuickLook 和 Snipaste 的图标糊了。
~~Rolan 那个圈本来就那么糊~~
QQ 图标是自己替换的，也没有糊。

**Comment by autodotua** [comment]
看到又有人回复了，我这里分享一下我自己写程序时碰到这个问题的解决办法，就是检测到DPI变化时，将托盘图标隐藏，然后再显示。我用的是C#，只要`Hide();Show();`就行，不知道C++是否可以。

**Comment by ysc3839** [comment]
@autodotua 微软官方做法是接收到 `TaskbarCreated` 消息时先 update，update 失败的话再 add。

**Comment by Skimige** [comment]
@liulex 现在能重开一下这个 issue 修复下 bug 吗，讨论见上

**Comment by liulex** [comment]
@Skimige 请提供重现步骤。对于 4k 屏，在系统显示设置里，我在 100% - 125% - 150% - 175% - 200% 之间进行切换都没有发现糊的情况。

**Comment by Skimige** [comment]
2.7.0，系统 21H2
以 1080p 分辨率 全屏 启动 CS:GO，来回切换游戏和游戏外

Before
![Snipaste_2021-12-11_13-15-49 before](https://user-images.githubusercontent.com/9017470/145665063-899914de-21b1-47a2-a978-61332e08009a.png)

After
![Snipaste_2021-12-11_13-19-32 after](https://user-images.githubusercontent.com/9017470/145665068-2af86502-8bb9-4959-ad91-76cd2bc8200f.png)

更改缩放比率似乎是个错误操作，重现本 issue 的正确操作应该是更改分辨率：如在 4K 和 1080p 之间来回切换：

![image](https://user-images.githubusercontent.com/9017470/145665110-2d50b49c-6c90-48c8-a446-dee866c932da.png)

不过我也测试了一次您说的，切换缩放（200 - 175 - 150 - 125 - 100 - 125 - 150 - 175 - 200），结果如下（糊的效果和切换分辨率还不太一样）：

![image](https://user-images.githubusercontent.com/9017470/145665161-7a82916e-a3a8-4cb3-955b-20cbeec7f43e.png)

**Comment by liulex** [comment]
请下载 https://dl.snipaste.com/alpha/qwindows.dll 后替换 Snipaste 64 位桌面版 platforms 文件夹内的同名文件，再试试。 @Skimige

**Comment by Skimige** [comment]
@liulex 2.7-Beta，测试了分辨率和缩放，没什么毛病。坐等商店版更新 :D

**Comment by 1tonsilla** [comment]
> 请下载 https://dl.snipaste.com/alpha/qwindows.dll 后替换 Snipaste 64 位桌面版 platforms 文件夹内的同名文件，再试试。 @Skimige

请问有什么办法自己换成喜欢的ico，我用iconsext提取qwindows.dll没找到图标文件，不知道咋换~
