### ISSUE TITLE
问题：截图边缘锚点不好用

### ISSUE THREAD

**Issue by misybing** [Snipaste/feedback#513]
之前提过一个建议，建议在下图(a)处添加四个锚点，(b)处不用，反馈后很快做了修改，但效果不理想。
<img src="http://wx3.sinaimg.cn/mw690/a51f1b45gy1fh841jddiqj20de06fq4f.jpg" >

请对比这两个图片，看看效果：
<img src="http://wx2.sinaimg.cn/mw690/a51f1b45gy1fh841jjx66j20de05t401.jpg" >
<img src="http://wx4.sinaimg.cn/mw690/a51f1b45gy1fh841jb02bj20de06gtbh.jpg" >

问题：
1. 添加锚点的作用是定位，使上下左右对称，团点太大，不精确，起不到定位作用，看起来也挺丑。
2. (a)处做4个就行，(b)处是拐角，两条边线相交就确定一个点了，再弄锚点没必要。
3. 或者可以用横竖两条浅色虚线连接(a)处4个点，会更能起到定位作用，就像PPT参考线：
<img src="http://wx3.sinaimg.cn/mw690/a51f1b45gy1fh84aqu5cej20fh08hwf6.jpg">

**Comment by misybing** [comment]
另外这个锚点在图片尺寸任何一边小于80的时候就没了，也是个问题，QQ截图则可以的。

**Comment by misybing** [comment]
意外发现截图时按Alt键会出现四条虚线，非常好用啊，辣么这个问题其实再加两条虚线就行了，这个圆圈圈锚点不要都行的，你们参考啦，期待改进

**Comment by liulex** [comment]
> 另外这个锚点在图片尺寸任何一边小于80的时候就没了，也是个问题，QQ截图则可以的。

在增加锚点的那个版本，就已经提过了相关的控制选项。

> 辣么这个问题其实再加两条虚线就行了

Good idea，以后会加上~

> 看起来也挺丑

> 这个圆圈圈锚点不要都行的

你可以在选项里关掉的……
至于美丑，我只能说我个人觉得还不错，如果觉得不好，那就拿出你觉得好看的方案出来…… 😅

**Comment by misybing** [comment]
所以结论是：1. 中间原点可以在选项里关掉，OK 2. 按Alt键会出现四条虚线，再加上两条，期待加上后的版本
