### ISSUE TITLE
请求增加GIF图片预览时（ctrl+c 再F3时），可调大小 功能

### ISSUE THREAD

**Issue by tubaozi2** [Snipaste/feedback#514]
请求增加GIF图片预览时（ctrl+c 再F3时），可调大小 功能

详细描述： 当我在使用ctrl+c 再按F3时调出的GIF图片 预览时  图片大小总是固定的，不能调整大小。可否增加使用快捷键进行缩放功能？  目前sinipaste仅支持JPG和PNG图片的缩放。对GIF还不支持。

**Comment by septs** [comment]
CC @liulex

**Comment by liulex** [comment]
因为 GIF 文件好像没有缩放的必要。。。缩放之后再保存的话，我也无法按照缩放后的给你保存，所以不如不做 GIF 的图片缩放。
