### ISSUE TITLE
Missing real auto-save capture without any further prompts

### ISSUE THREAD

**Issue by bsto** [Snipaste/feedback#516]
Assume I mark a rectangle region (on Windows 7) and release the mouse button then in the lower right corner all the tiny icons appear.
When I click on the floppy icon then I am asked for the output save directory.
After selection the current capture is saved 2 (!) times.

Why is it save two times?

Yes, I enabled auto-save and specified a Quick-save and Auto-Save directory in Tab "Output".

What I miss is a real auto-save:

After dragging a rectangle region and releasing the mouse button the content should be automatically saved into the pre-defined directory without any further prompts.

Could you add this feature in the next  release.

Thank you

**Comment by liulex** [comment]
Well... You may achieve that by enabling Auto-Save and then use the 'Snip and copy' hotkey. The only 'drawback' is that the screenshot will also be copied to your clipboard.

For higher degree of customization, please wait for the Pro version patiently.
