### ISSUE TITLE
全屏游戏截图时会出现问题

### ISSUE THREAD

**Issue by BlueSplash** [Snipaste/feedback#517]
全屏游戏截图时会出现问题，即使使用管理员权限也不行。
比如LOL用热键不会呼出截图；尼尔中呼出截图后并不会覆盖屏幕，截图也是白屏。

**Comment by Genteure** [comment]
游戏全屏的时候独占显示，所以我不认为实现这个功能很现实。
参考 https://github.com/Snipaste/feedback/issues/282#issuecomment-268239624 
> 游戏截屏
无计划。请使用游戏自带的截屏功能。
