### ISSUE TITLE
Missing storage of images when using more accounts on a Windows system in their own folder

### ISSUE THREAD

**Issue by Cobra045** [Snipaste/feedback#518]
Hoi,
Missing storage of images when using more accounts on a Windows system in their own folder.
Or is it possible for each user to set the path with% user% ?

Sorry for my bad english I'm 72 and never learned English

Thank you

**Comment by liulex** [comment]
What kind of storage of images do you mean?  Quick Save, Auto Save or ?

The variables (for example, %username%) in the File Name Patter can also be used in the Folder path:
![snipaste_20170720_192332](https://user-images.githubusercontent.com/2010459/28415090-d5354e34-6d80-11e7-9494-918d24ecadbb.png)

**Comment by Cobra045** [comment]
Thanks for the information, it works.

Kind regards.
