### ISSUE TITLE
Mac 版什么时候发布

### ISSUE THREAD

**Issue by tanlee** [Snipaste/feedback#519]
Dec 20 2016 就80%了，如今17年过半，何时发布 MAC 版？

**Comment by mpco** [comment]
何时 mac 版啊，好歹有个计划吧

**Comment by septs** [comment]
CC @liulex 
（但是根据作者目前披露状态来说 主要维护精力在 Windows 平台）
（并且作者本身表示过 "不要催更" 来自于 Snipaste Mac 版本内测群组）

**Comment by tanlee** [comment]
哪怕功能不全不稳定，放基本功能出来用着啊，MAC 下实在没有好用的

**Comment by mpco** [comment]
求内测

**Comment by Megasu** [comment]
求内测MAC版 snipaste。

**Comment by tanlee** [comment]
一年了……80%

**Comment by SJTUboy** [comment]
希望参与Mac版内测，刚才RSS看到有人发出截图在内测le
