### ISSUE TITLE
希望增加在桌面(资源管理器)ctrl+v的时候没有任何提示直接另存为图片到桌面的功能

### ISSUE THREAD

**Issue by 23330** [Snipaste/feedback#521]
截图后还要在贴图里点两下才能导出来图片
自带的另存为快捷键也要确认一下才导出
感觉有这个功能后导出图片会效率很多

**Comment by septs** [comment]
桌面 / 资源管理器 属于操作系统的东西
对于 Snipaste 来说无法感知您的行为
