### ISSUE TITLE
拔掉笔记本电源后Snipaste崩溃，非必现，但很常见

### ISSUE THREAD

**Issue by sunx1532** [Snipaste/feedback#522]
设备
Dell XPS15 9530
系统
Windows 10 Pro (1703) OS reversion 15063.413
软件版本
Snipaste 1.13.6(2017.06.09) 32bit（64bit 也可以复现）

问题描述
预设条件：
设置Snipaste为开机启动

重现步骤：
1. 正常使用Snipaste截图贴图
2. 偶尔合上笔记本盖子，使系统待机（午睡）
3. 断开笔记本电源（去开会）
4. 发现Snipaste崩溃

重新打开Snipaste后，再重复上面的步骤，无法立刻复现，但使用一段时间后任然可以复现

没有总结出100%必现的步骤，请谅解

**Comment by liulex** [comment]
谢谢你的描述。
该问题有较多用户遇到，但一直没找到重现办法，只知道和休眠/睡眠有关。

请问你的笔记本合盖是休眠还是睡眠？
我之前的笔记本一直是睡眠+不拔电源的，似乎没遇到过问题。
能否测试一下如果不拔电源，是否还有机会出现崩溃？

**Comment by septs** [comment]
@liulex 你有对于 ACPI 的 S0ix / S3 模式做过管理吗？

**Comment by septs** [comment]
@sunx1532 请求后续细节

**Comment by sunx1532** [comment]
您好，最近一直出差，刚回来

**Comment by liulex** [comment]
这种情况恐怕无法从软件自身进行排查了，可以尝试从系统日志里看看是否有所发现，以及从控制面板里更改一些电源设置试试？

**Comment by EMLVIRUS** [comment]
我这里尝试了不拔电源/拔电源睡眠混合，都未复现（64位同样环境），并且是拔电源睡眠几小时然后通电 ~（其实是寝室晚上11点断电前我睡眠第二天下午5点回来，早上6点就有电）~

**Comment by ClassicOldSong** [comment]
@liulex 可能大家都忽略了一个问题，拔掉电源的时候可能会导致独立显卡关闭

**Comment by ysc3839** [comment]
@ClassicOldSong 我觉得双显卡设计时就要考虑这种问题的。再说了，为什么其他程序没出现崩溃的问题？

**Comment by ClassicOldSong** [comment]
@ysc3839 我认为正常的兼容方案应该是程序兼容显卡而不是显卡兼容所有程序。一般程序不会出问题是因为

1. 程序本身不需要操心与显卡的通讯，绘图/截图由底层/系统API代劳
2. 需要自己操心的也已经解决了切换问题

在这里我只是提出一个可能方向，具体问题原因还得按实际情况分析

**Comment by ysc3839** [comment]
@ClassicOldSong 本来电脑就只有一个显卡的，双显卡是后面出的。程序兼容显卡的话，那么多显卡怎么测试？要求开发者每个都买回来测试？
DOS 时代其实就是这样的，不同显卡接口不同，游戏开发者得针对不同的显卡来适配。所以后来才有了 DirectX。DOS 时代的声卡也是这样的。

**Comment by ClassicOldSong** [comment]
@ysc3839 请仔细回顾你的这两条回复，其中包含逻辑冲突。而且我的回复中已经包含了你第二条回复所表述的内容。

具体情况请等待问题报告/开发者给出答复。

**Comment by ysc3839** [comment]
@ClassicOldSong 你可能是理解错了我的意思。我想表达的是以前的电脑只有一个显卡的，近几年才出现了双显卡。

**Comment by ClassicOldSong** [comment]
@ysc3839 这是事实，然而当前的问题案例使用了双显卡，所以这个问题的产生与双显卡是否近几年才出现关联不大。除非出现了一个相同症状而没有使用双显卡的案例，那么双显卡切换可能导致崩溃在当前应当作为一个可能的考虑方向。

**Comment by EMLVIRUS** [comment]
我这里电源设置改成切换到电池供电会使用集显，但是仍未复现

**Comment by liulex** [comment]
感谢以上各位 @septs @EMLVIRUS @ClassicOldSong @ysc3839 
另外 @septs 提到可能和日志记录有关系， @sunx1532 请你试试 xp 版或者 Windows Store 这两个完全不带日志记录的版本，看看是否还存在问题。

**Comment by wurenny** [comment]
我觉得这个可能跟睡眠没有必然关系，因为我的电脑从来都是设置成永不休眠、睡眠，包括硬盘，而且我自己实验了，手动休眠并不会触发程序退出，但是我机器上的其它程序并没有出现这个情况，可能得换个思路思考这个问题，不一定和休眠有关
![Image of Yaktocat](https://user-images.githubusercontent.com/6622574/29737914-86afda46-8a49-11e7-8478-86ff5a988b82.png)
![Image of Yaktocat](https://user-images.githubusercontent.com/6622574/29737910-79d6aac0-8a49-11e7-911a-2908bfb425ff.png)

**Comment by liulex** [comment]
@wurenny 非常感谢你提供的信息。不过大多数遇到该问题的用户都反应确实和睡眠有关系…… 所以有可能你们遇到的其实是两个不同的问题。

就我个人来说，长期不关机不睡眠不休眠的台式机，以及每天合盖睡眠的笔记本，都没能重现你们的问题……

**Comment by mokeyjay** [comment]
我 #565 跟拔电源无关，我不插电源，合上盖子一定几率（很大）也会导致自动退出。我是XPS 9560，系统Win10企业版

**Comment by liulex** [comment]
@mokeyjay 谢谢提供信息！

**Comment by kongwy** [comment]
有同样的现象，硬件联想 Y50-70，此前使用 64 位版本运行于 Win10 企业版，很长一段时间之前就开始存在崩溃现象，最近重装系统（Win10 Pro）并顺便更换 32 位版本 Snipaste 尝试避免崩溃问题，结果今天又重新出现，看 splog.txt 似乎没有什么特别的地方，也[顺便丢上来](http://momok.link/t02Xjw)吧。

**Comment by mokeyjay** [comment]
补充一下。我发现并非每次都会自动退出，但如果有贴图存在的话，100%会导致自动退出。是否检查下贴图功能？

**Comment by phtwo** [comment]
我这里有一个基本必重现的方法，电脑连接外接显示屏（扩展），拔掉，连上另一个显示器（复制，这里什么方式可能无关），然后再连回第一个显示屏，发现崩了。具体在哪一步崩的不清楚，因为每次都是拿去会议室投影回来后，发现的。

**Comment by solxnp** [comment]
我的笔记本能重现问题，而且是必现 ！
只要拔掉电源   程序就会退出
曾经我以为是休眠的问题   因为我的习惯是不用的情况下就休眠  每次再打开的时候  程序就退出了   直到今天我发现是电源断掉就会退出  我尝试了下   不拔掉电源情况下休眠  再次启动后   程序正常没有退出  所以我这边必现的就是拔掉电源

**Comment by liulex** [comment]
@solxnp Hi, 可否发个邮件到 <snipaste.app@gmail.com>，我们来做一些进一步的测试。

**Comment by EtaoinWu** [comment]
拔掉电源程序退出，本地复现成功
1.15.1，Windows 16299.19(insider slow)，Lenovo L440 20AS.

**Comment by liulex** [comment]
感谢以上各位提供的信息，特别感谢 @mokeyjay 和 @EtaoinWu 配合做了许多测试，终于发现是跟计划任务的设置有关。虽然根源还不太清楚，不过已经可以在下个版本修复了 🎉

**Comment by ysc3839** [comment]
@liulex 有更详细的信息吗？

**Comment by liulex** [comment]
@ysc3839 就是在**某些**电脑上，这个父选项没勾的灰掉的选项，会起作用……
![default](https://user-images.githubusercontent.com/2010459/32184520-6e3dfa4e-bdd7-11e7-84c4-6a05eefc771e.png)
