### ISSUE TITLE
销毁贴图的时候能否清除剪贴板信息？

### ISSUE THREAD

**Issue by fyitahz** [Snipaste/feedback#523]
如果销毁贴图的时候能清除剪贴板信息，就能避免按贴图键时再次被贴出，这个功能有点烦人。

**Comment by septs** [comment]
我认为该问题属于 个人使用习惯范畴

**Comment by liulex** [comment]
1. 被销毁的贴图不一定就是剪贴板当前的内容。
2. 如果先比较贴图与剪贴板内容，那用户旋转或编辑后的贴图是否应该视作与剪贴板内的原图像相同。
3. …

所以你的提法明显是有欠考虑的。
下面的话对事不对人：
如果你从有了想法到发完 issue 只用了五分钟，我觉得它不会值得我花几十分钟或者几个小时去实现。
所以如果你真的希望解决某个问题，我觉得先展示自己的思考会省掉开发者很多的时间，从而让它更可能或者更快被实现。

**Comment by fyitahz** [comment]
从剪贴板贴出贴图是个很好的功能，但如果有时候复制了比较隐私的内容，按下贴图键时可能会泄露用户隐私，特别是用于工作的时候。我作为用户只是想提一点意见帮助你的软件变得更完美，我觉得作者可能想得太复杂了，其实我的意思，不管我销毁哪个贴图，都可以清除剪贴板内容，也可以在右键菜单或者增加一个快捷键，让用户手动清除剪贴板内容。

**Comment by septs** [comment]
@fyitahz 您关于 隐私安全 的考虑对于 Snipaste 主要受众是多虑的 （我觉得 @liulex 不因予以考虑）

**Comment by liulex** [comment]
@fyitahz 不知你之前的留言怎么没了……
“不管我销毁哪个贴图，都可以清除剪贴板内容” 我觉得这是不合理的，并且容易导致用户丢失重要数据。即使从隐私方面考虑，也不应该这样设计。

在将来 Snipaste 也会设计成轻量的剪贴板管理工具，但目前它还不是……
