### ISSUE TITLE
winOS 版本15063.413 无法勾选开机启动--错误,启动文件夹中的快捷方式似乎出错了,已自动取消开机启动

### ISSUE THREAD

**Issue by xingcxb** [Snipaste/feedback#524]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by septs** [comment]
请检查您的当前用户是否拥有权限配置开机启动
如果您加入了域 请联系您所在的 IT 部门协助
