### ISSUE TITLE
问题：怎样拼凑多个截图到一个图

### ISSUE THREAD

**Issue by tanglianggithub** [Snipaste/feedback#525]
截了多个图，想把这些图整合到一个图中，该怎样处理呢？

**Comment by septs** [comment]
如果是期望 #19 目前没有
如果是针对连续的图片合成可以参考使用 https://helpx.adobe.com/photoshop/using/create-panoramic-images-photomerge.html

**Comment by tanglianggithub** [comment]
先用Snipaste截了一个图并做一些添加文字等处理，再用Snipaste截了另外一个图并标记。
之后把这两个图放到一张图上。

**Comment by liulex** [comment]
#45
