### ISSUE TITLE
When zooming vector picture, picture is blur

### ISSUE THREAD

**Issue by WanpengQian** [Snipaste/feedback#529]
Ctrl+C一个svg图片，然后F3置顶到桌面之后，对图片进行扩大显示。
扩大后的SVG图片很模糊。

下面是100%大小的redhat.svg图片。
![image](https://user-images.githubusercontent.com/6359418/28347344-7cb51a9c-6c71-11e7-851a-9c4ab7515b10.png)

zoom到200%之后，变模糊了。
![image](https://user-images.githubusercontent.com/6359418/28347361-902fdce2-6c71-11e7-8f42-d89887faf5ff.png)

或许应该分别对待矢量图和位图。

**Comment by EtaoinWu** [comment]
不仅仅是svg，
尝试贴图一段html的时候
![image2](https://user-images.githubusercontent.com/22369305/28349495-c1404764-6c75-11e7-84ac-356f1f29185c.png)
贴图一个颜色的时候
![image1](https://user-images.githubusercontent.com/22369305/28349445-85c1f8a4-6c75-11e7-930a-d61da6009edf.png)
放大之后都会导致模糊

**Comment by liulex** [comment]
@WanpengQian @EtaoinWu 
目前来说，贴图是将剪贴板中的信息转换为图片，因此在被创建的那一刻转换图像就被确定了，之后的所有调整都是基于这张图像，不再和贴图来源相关，这可以解释你们提到的行为。

不过对非图像的来源（如 svg，文字，颜色信息等）提供矢量的缩放是在计划中的。

**Comment by liulex** [comment]
dup of #1322.
