### ISSUE TITLE
Skype UWP: pasting screenshots from snipaste not working

### ISSUE THREAD

**Issue by jhoefler** [Snipaste/feedback#531]
Snipaste is working really great. However, with the latest Skype UWP it is not possible to paste screenshots in to the app. Any idea? It seems to be related to the Skype UWP. If I use the x86 version of skype it works  without problems.

Is there a way to fix this issue?

**Comment by liulex** [comment]
Check this:
![default](https://user-images.githubusercontent.com/2010459/28445634-298e65ca-6df8-11e7-9517-6806fec904c8.png)
And if necessary, check this too:
![default](https://user-images.githubusercontent.com/2010459/28445644-41a15942-6df8-11e7-9e1d-fa95db0b761f.png)

**Comment by jhoefler** [comment]
Thank you very much for your fast response. This resolved the issue.
