### ISSUE TITLE
贴图功能希望可以二次修改文字，使便签功能更完美

### ISSUE THREAD

**Issue by wurenny** [Snipaste/feedback#534]
真是一个奇葩又好用的Geeker软件，提几个建议：

1、复制文字贴图可以考虑再做二次编辑文字（这个功能实现可能比较难），这样就完全可以当便签使用了
2、复制文字后如果是非HTML格式的，比如我copy了代码，背景是白色的，希望可以自动拾取当前窗口的背景色，亦或者可以自定义修改背景色，这样看起来更加逼真一点，这点应该比较好容易实现，当然有人说直接显示为像vim/sublime语法高亮，那样big更高，但实现起来可能比较难
3、内存使用及回收可以再优化下，毕竟是常驻软件
滚屏支持我就不提了，肯定很多人已经提了，不过这些都算是小众需求吧

**Comment by kookxiang** [comment]
@wurenny 用 VScode 复制出来就是带高亮的

**Comment by wurenny** [comment]
@kookxiang 多谢，机器上只有VIM，用了VIM就不想用其它编辑器了，就像用snipaste就不想用其它截图软件了一样

**Comment by septs** [comment]
@wurenny 
1. 由于 Snipaste 没有图层，并且作者也没有引入计划（就目前的信息来看）
2.1. 背景颜色取决于拷贝的源头是否携带背景
2.2. 如果引入代码高亮不可避免的在 Snipaste 引入一个子系统代价过高
3. CC @liulex 
4. 如果想关注请持续跟进 #19

**Comment by liulex** [comment]
1. #301
2. 只是纯文本的背景色的话，选项里有。
3. 具体表现是？

**Comment by wurenny** [comment]
刚找时间仔细研究了下：
1、目前文字生成的贴图，右键提供了“复制纯文本”功能，可以勉强算支持编辑功能；
不过我想下还是可以做到更加完美的直接编辑贴图文字功能，也不需要多图层就可以实现，因为既然都可以取出图片里面的文字（应该是持久化到了本地文件数据库），那也可以内嵌一个很小的编辑器弹出来完成修改，再动态生成新的贴图就完事了
2、修改背景功能确实是已经实现了的
3、内存占用情况，我刚才对比了几个主流的图片软件，包括微软默认图片查看器，光影看图发现Snipaste对内存的控制还是比较好的

**Comment by septs** [comment]
关于问题 1 建议合并至 #301 讨论

**Comment by wurenny** [comment]
顺便我想问下 ：
双击关闭贴图和右键销毁贴图是否有什么不同，我看好像都是从history里把图片给删了
有没有更快捷的办法直接 [文字——>生成贴图] 复制到内存里，不用经过F3，这个操作感觉比较黑科技
