### ISSUE TITLE
关闭贴图和右键销毁贴图是否有什么不同；是否有 [文字——>生成贴图] 复制到内存一步到位的操作？

### ISSUE THREAD

**Issue by wurenny** [Snipaste/feedback#535]
两个疑问，开个新的Issue：
1、双击关闭贴图和右键销毁贴图是否有什么不同，我看好像都是从history里把图片给删了
2、有没有更快捷的办法直接 [文字——>生成贴图] 复制到内存里，不用经过F3，这个操作感觉比较黑科技

**Comment by GregAMO** [comment]
回复1：关闭贴图可以通过反复按下贴图键找回，销毁贴图不可找回
回复2：这种几个快捷键拼成一个快捷键的需求，目前可以用 AutoHotKey 哒，
「自定义进入截图的组合动作」和「自定义截图完成的动作组合」都已收入 #282 已收集建议

**Comment by wurenny** [comment]
2、也行吧，不过总感觉如果需要两个软件配合总会增加BUG发生的概率，之前用winhotkey就会在很多软件里全局快捷突然失效，而且这个组合动作要开发出来也是很简单的吧，不涉及特别大的改动，但用起来却很Cool:
【复制文字/代码片段——>按下某快捷键——>粘贴的直接就是文字/代码对应的贴图】

**Comment by liulex** [comment]
1. https://docs.snipaste.com/zh-cn/getting-started?id=%E5%85%B3%E9%97%AD%E5%8D%95%E5%BC%A0%E8%B4%B4%E5%9B%BE
简单来说，关闭是你看不见它了，但它还在 Snipaste 的内存里，有机会再让你看见它；销毁是 Snipaste 已经完全不记得它了。

2. 可以考虑作为专业版的特性~
