### ISSUE TITLE
Cannot use onscreen keyboard

### ISSUE THREAD

**Issue by koppor** [Snipaste/feedback#536]
1. Open Windows onscreen keyboard
2. Go to "emojis"
3. Activate Snipaste
4. Select text tool
5. Try to add text
6. Hardware keyboard works
7. Selecting an emoji from the on-screen keyboard does not. One cannot click on the onscreen keyboard to select an emoji. The area of Snipaste just extends.

I think, this could be intended. I could copy and paste the emojis before, but directly allowing inputting them would be of higher value.

**Comment by liulex** [comment]
Yes, that is intended.
As a workaround, you may pin the screenshot to the screen first before you input the emojis on it.
