### ISSUE TITLE
关于开机自启

### ISSUE THREAD

**Issue by AronLL** [Snipaste/feedback#538]
**已经按照故障排除的方法尝试修复，但是修复失败**

Win10系统，无法知道是什么操作之后无法开机自启了。

但是发现，我用火绒的启动项管理工具时，其它的自启项打开文件所在位置都能准确定位，但是打开snipaste所在位置显示的是我的电脑的根目录。不知道是不是这个有影响。

**Comment by ysc3839** [comment]
删掉这一项，然后再添加一次

**Comment by AronLL** [comment]
之前就尝试过了，不过并没有解决问题。删除之后依然是指向我的电脑的根目录。
不知道是不是我的电脑的问题~

**Comment by StarryVoid** [comment]
@AronLL 可以尝试一下使用管理员权限运行snipaste后，取消并重新勾选开机启动。
火绒启动项管理工具那边还原一下和Snipaste有关的历史操作痕迹

**Comment by AronLL** [comment]
不知道怎么看历史操作痕迹~.~尴尬...
不过不知道是不是我描述的不准确给你们带来了误导：
在火绒的启动项管理里面，只在任务计划里面出现了一个跟snipaste有关的项，启动项和服务项里都没有。
另外用火绒剑看启动项发现，取消和重新勾选开机启动，就会生成下面这个文件
![image](https://user-images.githubusercontent.com/17673305/28752953-83d38a76-755d-11e7-8887-397f42aa6b81.png)

**Comment by StarryVoid** [comment]
@AronLL

**Comment by liulex** [comment]
启动路径是正常的，勾了管理员权限就是那样。
如果你确定按照文档里的方法尝试过之后仍然无效，那就去掉管理员权限的勾吧。。

**Comment by AronLL** [comment]
找到原因了~不知道为什么snipaste的启动项在我电脑里变成这个了。
我在之前忽略的项目中恢复它就好了。
![image](https://user-images.githubusercontent.com/17673305/28753973-d3a0a320-756e-11e7-9b9a-74238c5729cf.png)
感谢之前所有人的帮助哈~
@ysc3839 @StarryVoid @liulex

**Comment by ysc3839** [comment]
@AronLL 删除后手动创建快捷方式
