### ISSUE TITLE
直动把图片上传到图片，并返回图片地址

### ISSUE THREAD

**Issue by Juddd** [Snipaste/feedback#540]
我用你这小软件已经很久了，由于经常写markdown，所以需要用到图片的网址，目前是通过你这小软件截图到剪贴板，然后写了个小脚本，通过快捷键上传到图传云，再把图片地址返回到剪贴板。我运行这小脚本需要启动一个巨大的内核，所以耗时接近10s，如果你愿意做这么个功能就好了

**Comment by StarryVoid** [comment]
似乎将图片自动上传有人提过issue了，具体编号[#60](https://github.com/Snipaste/feedback/issues/60)
