### ISSUE TITLE
BUG：复制颜色值，将颜色值贴图出来，不知什么操作后，这个贴图无法关闭

### ISSUE THREAD

**Issue by iuuunlyk** [Snipaste/feedback#541]
1. 用c复制了一组颜色值
2.贴图到桌面
3.其他操作（不记得了具体内容了）
4.颜色这个贴图框失灵了——不能：选中、操作、关闭，右键无效
5.重启snipaste，那个贴图自动贴出来，但问题依旧。

**Comment by iuuunlyk** [comment]
呃 在simpaste菜单里，“隐藏所有贴图”解决。

**Comment by liulex** [comment]
3 的操作是是在贴图上双击 <kbd>X</kbd>，解除方法：
![default](https://user-images.githubusercontent.com/2010459/28774975-53044870-7622-11e7-9988-e6bbacf61d9a.png)

**Comment by StarryVoid** [comment]
@liulex 作者都无奈了。。。。
