### ISSUE TITLE
画笔十字能否调整为不同颜色？

### ISSUE THREAD

**Issue by SicL** [Snipaste/feedback#544]
作者你好，

在截图并使用画笔涂抹时，画笔的十字准心跟画笔颜色一致，在涂抹范围较大又有细部需要调整时，很难找到画笔的位置，能否将画笔十字调整为跟画笔不同的颜色以便定位呢？

Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by gloomy-ghost** [comment]
这个需求的另一种实现思路：

![default](https://user-images.githubusercontent.com/13086421/28950519-a5cfe71e-7918-11e7-86e7-c0f9619b4aac.png)
利用已经实现的截图选择器，加个选项使其在使用编辑工具时也可用，相比改颜色更直观也有通用性（局部涂抹模糊需要修整什么的）

**Comment by liulex** [comment]
@gloomy-ghost 按下 <kbd>Alt</kbd> 就可以了

**Comment by SicL** [comment]
按住alt键能解决问题但还是不太方便。我的应用场景一般是例如网页这种白底黑字，截图需要涂抹掉部分文字，用白色画笔显得自然一点，不会有打码的痕迹。然而白色画笔在白色背景下，鼠标稍微动一下就找不着了，很蛋疼的。

**Comment by gloomy-ghost** [comment]
![default](https://user-images.githubusercontent.com/13086421/29165391-a17bafc4-7e16-11e7-9e8f-7cf0b45c0d9d.png)
试试用马克笔直接覆盖？
