### ISSUE TITLE
是否可以在编辑截图时增加字体大小的选择, 方便编辑

### ISSUE THREAD

**Issue by cnsheds** [Snipaste/feedback#545]
有时候想在截图上用大小不一样的文字, 现在只能选择字体, 无法选择大小, 很不方便
---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by GregAMO** [comment]
@cnsheds 和 PPT 类似，用鼠标对文本框调节大小即可
