### ISSUE TITLE
 Screenpresso 可以借鉴一下

### ISSUE THREAD

**Issue by evonli** [Snipaste/feedback#546]
是否可以借鉴一下 Screenpresso 的功能

- 更好看的箭头和文字
- 好看的数字样式
- 各种框框圈圈应有尽有
- 扩大镜功能
- 等等

这里有[介绍](https://segmentfault.com/a/1190000010496908)

**Comment by septs** [comment]
Snipaste 不是您其他的软件代替。
Snipaste 注重的是 Snip + paste

**Comment by liulex** [comment]
标注功能会在合适的时候改进样式和加入新功能，但不是现在。

截图软件有很多，各有特色和侧重点，对个人用户来说，我觉得没有必要一定只留下一个吧。
