### ISSUE TITLE
能否添加两个截图对比功能

### ISSUE THREAD

**Issue by xhufo** [Snipaste/feedback#547]
因为经常要对图像进行处理对比，有些变化细微的左右对比没有重叠起来对比能发现变化，能否考虑添加两个贴图的对比功能。
实现例子：
![image](https://user-images.githubusercontent.com/11385342/28995653-6436e686-7a21-11e7-91e6-7107dd95dcae.png)

http://www.daimabiji.com/imgview/3930.html

**Comment by ysc3839** [comment]
@septs 
> Snipaste 不是您其他的软件代替。
Snipaste 注重的是 Snip + paste

**Comment by GregAMO** [comment]
目前的 Snipaste 做重叠对比……可以调整其中一张贴图的透明度吧，鼠标穿透也可以用上

**Comment by liulex** [comment]
看不出你的文字描述和图片描述有什么关联……
正如 @GregAMO 所说，Snipaste 一早就可以将贴图进行重叠对比。

**Comment by liulex** [comment]
抱歉刚刚没有点进你给的链接，现在我明白了。
这个功能需要在一个贴图窗口上显示和控制两张图片，改动代价太高，且该功能不够通用，所以应该不会考虑。
