### ISSUE TITLE
双击截图区域，很大几率截图不成功

### ISSUE THREAD

**Issue by refine706** [Snipaste/feedback#548]
你好，
使用快捷键（自定义 <kbd>Ctrl</kbd> + <kbd>E</kbd>）截图，选好截图区域后，双击截图区域，有时不成功（ <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>V</kbd> 贴图出来是上一次的剪切板内容）。
[问题图示](http://i4.bvimg.com/1949/a0cbebbf8f6cf570.png)

希望可以在双击截图区域时，也能成功截图。

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by refine706** [comment]
已补充图

**Comment by StarryVoid** [comment]
方便贴一下程序日志么

**Comment by refine706** [comment]
文件在哪里？

**Comment by refine706** [comment]
贴不全，太多了

**Comment by refine706** [comment]
[图在此](http://i4.bvimg.com/1949/a0cbebbf8f6cf570.png)

**Comment by refine706** [comment]
[splog.txt](https://github.com/Snipaste/feedback/files/1214634/splog.txt)
![a0cbebbf8f6cf570](https://user-images.githubusercontent.com/10571598/29167765-4e6f0762-7dfe-11e7-8072-891a8d2d72a4.png)

**Comment by liulex** [comment]
看日志你有开自动保存，那么你可检查一下，当双击没有复制成功的时候，这张截图是否有自动保存到你设定的目录？

**Comment by refine706** [comment]
明天去了我试一下 太感谢了 深夜解决问题 棒棒的

**Comment by refine706** [comment]
在自动保存的目录里找到了没贴出来的图
但是我把自动保存关掉了后，问题依然存在

**Comment by refine706** [comment]
[我把日志也传上来了splog.txt](https://github.com/Snipaste/feedback/files/1216974/splog.txt)

**Comment by liulex** [comment]
如果截图内容和屏幕上已有的贴图一样，也是不会贴出来的。
请双击后在其他地方粘贴，以确认确实没有复制到剪贴板。

**Comment by refine706** [comment]
确定不一样

**Comment by liulex** [comment]
那参照 #413 给管理员权限吧，我觉得是其他什么程序的干扰……

**Comment by refine706** [comment]
使用管理员权限好了，非管理还是不行，希望这个视频能对你有所帮助
![gif图片下载下来，后缀改成mp4](https://user-images.githubusercontent.com/10571598/29202104-4fadafd6-7e97-11e7-858d-45053aee5cd9.gif)

**Comment by liulex** [comment]
谢谢，问题的表现我了解了，但原因还是谜……

双击和点击按钮调用的是同一个函数，从日志来看，双击的时候这个函数已经成功调用了；自动保存目录里有这张图片，也说明截图的生成没有出错，排除了双击导致生成空截图于是复制没有成功这个可能性。

给了权限问题就消失，这就更谜了……我只能想到是另一个不具有管理员权限的程序在全局检测鼠标双击事件并且也在操作剪贴板，或者是有什么安全软件在保护剪贴板…… 🌚

**Comment by refine706** [comment]
有时间我一个个程序关掉试一下再回来告诉你，多谢了
