### ISSUE TITLE
无法更改“开机启动”选项

### ISSUE THREAD

**Issue by duiii** [Snipaste/feedback#551]
![snipaste_2017-08-10_20-41-42](https://user-images.githubusercontent.com/28379772/29170961-51f0486a-7e0d-11e7-97e8-743eb0efb1bc.png)
如图，无法更改开机启动的选项。
从微软应用商店安装的，版本1.14（2017.08.04）。
系统为Win10 64位专业版1703。

**Comment by ysc3839** [comment]
注：
1. 商店版本默认开机启动且暂未提供开关，如需取消开机启动，请在“任务管理器 - 启动”中找到 Snipaste 并将其禁用即可。

**Comment by duiii** [comment]
@ysc3839 感谢。
我以为是bug或是我系统权限问题，特来一问。
