### ISSUE TITLE
是否可以设定在某些程序内使快捷键不起作用？

### ISSUE THREAD

**Issue by Akelio-zhang** [Snipaste/feedback#553]
请求新功能？

在进行DOTA2这类游戏时，需要用到F1 F3等按键，会被软件的快捷键OVERRIDE导致不能使用游戏中的功能。是否可以提供在某些程序内禁用贴图等快捷键？

**Comment by linzyjx** [comment]
可以修改相关快捷键

**Comment by Akelio-zhang** [comment]
@linzyjx 谢谢，刚刚发现了有提供禁用hotkey的功能，谢谢！
