### ISSUE TITLE
希望增加探照灯功能

### ISSUE THREAD

**Issue by yylyyl** [Snipaste/feedback#554]
对截图区域增加探照灯功能，以便在图片中突出重点。

使用圆圈或者箭头也能突出重点，但有时眼花缭乱，没有探照灯来的清晰。

效果就类似于，截图时非截图区域的加深效果。

**Comment by liulex** [comment]
使用马赛克/高斯模糊/马克杯工具配合橡皮擦工具可以实现：
![default](https://user-images.githubusercontent.com/2010459/29323131-7e224d26-8212-11e7-8f73-be747319a1c4.png)

**Comment by StarryVoid** [comment]
矩形选框+透明度160+橡皮擦，你值得拥有。
