### ISSUE TITLE
更新：建议在更新界面显示下载程序的大小

### ISSUE THREAD

**Issue by ZetaoYang** [Snipaste/feedback#557]
![image](https://user-images.githubusercontent.com/10769951/29393009-f8b6df44-8333-11e7-8917-e8e9b088ca34.png)

**Comment by EMLVIRUS** [comment]
我看不出这个feature意义何在。即使完整下载，那点流量也是忽略不计。

**Comment by MichaelHu55** [comment]
逼死强迫症

**Comment by StarryVoid** [comment]
程序更新包很小的。。这个没必要一定写上。

**Comment by septs** [comment]
我认为意义不大，因为 Snipaste 的体积很小，并且 执行更新时间很短。
