### ISSUE TITLE
建议把使鼠标无法被点击，改成鼠标穿透

### ISSUE THREAD

**Issue by MichaelHu55** [Snipaste/feedback#559]
f4里写的是取消鼠标穿透，但是双击x却写着鼠标无法点击，这样让新用户很费解啊。一开始更本不知道双击x就是鼠标穿透。你看issue里有多少人因为这个提issue了。原因就是用的时候根本没有理解双击x是和f4对应的。

**Comment by ZeronoFreya** [comment]
赞一个，的确最初不知道干啥的，偶然间发现才会的。
