### ISSUE TITLE
为什么占这么多cpu？

### ISSUE THREAD

**Issue by Juddd** [Snipaste/feedback#560]
win10,8G电脑

![](http://i.stack.imgur.com/YWoE0.png)

都在干啥？

**Comment by liulex** [comment]
你得告诉我你当时在用 Snipaste 干啥……
如果只是后台运行，应该是 0% 的，元素检测、画马赛克之类的当然就会瞬时占 CPU 啊~

**Comment by Juddd** [comment]
我啥也没干，不是瞬间，是长期占用，现在也还是这情况，而且你看我的截图是按cpu占用来排序的，另外，其实我同时还开了期它大型应用，都没它占用得多。。

**Comment by StarryVoid** [comment]
@Juddd 可以发一下cpu主频和型号以及任务管理器截图么

**Comment by liulex** [comment]
@Juddd 重启 Snipaste 依旧？是偶尔还是总是？
另外还可以试试将日志等级设成“关”试试。

**Comment by Juddd** [comment]
我平时不怎么注意cpu占用，即使是偶尔也有问题吧？我可以帮你收集一下证据你排查一下

**Comment by Juddd** [comment]
这是我的cpu信息
[cpuinfo.txt](https://github.com/Snipaste/feedback/files/1244300/cpuinfo.txt)

**Comment by liulex** [comment]
下次发生这种情况的时候你可以使用 [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) 监控一下 Snipaste 正在干什么。
之前没人报告过这种情况，我也想象不出来是什么原因导致的。

**Comment by septs** [comment]
后续讨论请合并至 #498
