### ISSUE TITLE
能否实现快速全屏截图并保存（win7）？

### ISSUE THREAD

**Issue by bydx** [Snipaste/feedback#561]
目前：截图→Ctrl+A→回车，需要三步。

**Comment by septs** [comment]
为何不使用 PrScr 按键

**Comment by bydx** [comment]
只能保存到剪贴板，我想一键保存成文件。改用picpick解决了

**Comment by StarryVoid** [comment]
@bydx 命令行版的snipaste可以完成你的需求

**Comment by kookxiang** [comment]
Why not use <kbd>Win</kbd>+<kbd>PrScr</kbd>?

**Comment by bydx** [comment]
@StarryVoid 请问命令行能一键保存么？不太会用，看了看文档好像至少也得两步。

**Comment by bydx** [comment]
@kookxiang win7，请看清题意。

**Comment by liulex** [comment]
下个版本可以通过命令行调用实现。
