### ISSUE TITLE
Undo press of Escape

### ISSUE THREAD

**Issue by koppor** [Snipaste/feedback#562]
When pressing <kbd>Esc</kbd>, Snipaste closes. How can I undo this behavior?

This happens accidentally when working at Snipaste. This is muscle memory, which I cannot stop to happen 😇 . For instance, when I want to leave the edit mode of a text field: Pressing <kbd>Enter</kbd> leads to a new line (which is OK). I just want to press <kbd>Esc</kbd> to leave it and then <kbd>Enter</kbd> to enable copy to the clipboard.

**Comment by liulex** [comment]
So if pressing <kbd>Enter</kbd> finishes the current text edit instead of quitting snipping, is that OK for you? It looks reasonable to me.

**Comment by koppor** [comment]
Pressing <kbd>Esc</kbd> should finish the current text edit instead of quitting snipping.

NOT: <kbd>Enter</kbd>. -- That should be new lines.

**Comment by liulex** [comment]
Oh, sure. That's my typo. I mean <kbd>Esc</kbd>, and I have got it implemented. 😉

**Comment by koppor** [comment]
Thank you!
