### ISSUE TITLE
基本上隔一两天程序就会自动退出

### ISSUE THREAD

**Issue by wurenny** [Snipaste/feedback#564]
相比以前，现在win10的性能已经大大改善，所以我的电脑基本上不会关机，但发现基本上隔一两天我按截屏快捷键就失效了，然后在任务栏托盘上查看是由于snipaste自动退出了，这个现象应该是可以重现的，我觉得稳定性还有待提升

**Comment by septs** [comment]
see #522

**Comment by wurenny** [comment]
我觉得这个可能跟睡眠没有必然关系，因为我的电脑从来都是设置成永不休眠、睡眠，包括硬盘，而且我自己实验了，手动休眠并不会触发程序退出，但是我机器上的其它程序并没有出现这个情况，可能得换个思路思考这个问题，不一定和休眠有关
![image](https://user-images.githubusercontent.com/6622574/29737910-79d6aac0-8a49-11e7-911a-2908bfb425ff.png)
![image](https://user-images.githubusercontent.com/6622574/29737914-86afda46-8a49-11e7-8478-86ff5a988b82.png)

**Comment by septs** [comment]
@wurenny 该问题请合并至 #522 进一步讨论
