### ISSUE TITLE
XPS 9560合上盖子3小时（休眠）后Snipaste自动退出

### ISSUE THREAD

**Issue by mokeyjay** [Snipaste/feedback#565]
![Snipaste_2017-08-26_13-37-15.png](https://i.loli.net/2017/08/26/59a109b2a3cbd.png)
![Snipaste_2017-08-26_13-36-15.png](https://i.loli.net/2017/08/26/59a109b2a631e.png)
系统配置如图

3小时候再打开盖子进入桌面，之前的软件、窗口全都还在，唯独Snipaste自动退出了

**Comment by septs** [comment]
请合并至 #522 讨论
