### ISSUE TITLE
截图后固定在屏幕上，第一次拖动无效

### ISSUE THREAD

**Issue by i5baobao** [Snipaste/feedback#569]
如图所示，是故意设置成这样还是BUG？
第一次拖动是无效的，总会回到原来的位置，只有第二次才行

![gif](https://user-images.githubusercontent.com/26620196/29857505-938287f6-8d8b-11e7-93aa-e13280a3f982.gif)

**Comment by liulex** [comment]
Bug. 请按照这个设置：
![](https://cloud.githubusercontent.com/assets/2010459/18747273/018a85c2-80ff-11e6-9e84-9c42348ffd77.png)

**Comment by liulex** [comment]
已在 1.14.1 修复，谢谢。

**Comment by i5baobao** [comment]
您好，
        抱歉没有及时回复您！
        我是win7用户，用这个设置可以改善我之前描述的问题，但是会导致主题失效，电脑字体被更改。因为有一部分勾没有勾上，之前一直用的“调整至最佳性能”选项，所以还是建议一般用户不要这样设置。



From:17610063903@qq.com (leeton@foxmail.com)

Best Wishes !
 
发件人： Le Liu
发送时间： 2017-08-30 14:31
收件人： Snipaste/feedback
抄送： LeeTon; Author
主题： Re: [Snipaste/feedback] 截图后固定在屏幕上，第一次拖动无效 (#569)
Bug. 请按照这个设置：
