### ISSUE TITLE
Undo pressing of Enter

### ISSUE THREAD

**Issue by koppor** [Snipaste/feedback#570]
When pressing <kbd>Enter</kbd>, Snipaste closes. How can I undo this behavior? - This is a similar issue as  https://github.com/Snipaste/feedback/issues/562, but still slightly different:

I am so used to press Enter to have the current image in the clipboard. In 10% of the cases, I want to have a file saved. It is only possible with a graphics program (like mspaint) to "convert" the clipboard to an image file.

If it was possible to return to the previous Snipaste screen, where I have the "save" button available, I could undo my press of Enter. Is this possible somehow?

I am aware that implementing the feature https://github.com/Snipaste/feedback/issues/416 would also solve the issue, but I fear that the "drag'n'drop" functionality won't be implemented soon.

**Comment by liulex** [comment]
Two ways:
1. Use `Paste`. Snipaste also has a great feature called `Paste`. When you have an image in your clipboard, you could paste it onto the screen (default <kbd>F3</kbd>, or <kbd>F2</kbd> if you are an early user of Snipaste). Then you can save the image to file by pressing <kbd>Ctrl</kbd> + <kbd>S</kbd> or from its context menu.
2. Use the history playback functionality of snipping. Start snipping again, then press <kbd>,</kbd> or <kbd>.</kbd> to review your previous successful screenshots and do whatever you want with them.

**Comment by koppor** [comment]
`Paste` solved my issue. Thank you.
