### ISSUE TITLE
截图时十字旁边的放大镜很讨厌

### ISSUE THREAD

**Issue by caoohbao** [Snipaste/feedback#571]
截图时十字旁边的放大镜根本不好用, 软件再更改时最好去掉, 或自己可设定.

**Comment by septs** [comment]
快捷键中请不要包含 Alt

**Comment by caoohbao** [comment]
截图快捷键设置中我没设置用alt键.
截屏用的是F1
截屏并自动复制什么快捷键都没用
贴图用的是F3.

**Comment by liulex** [comment]
请勿以自己的喜恶去否定一个功能。谁会乐意满足使用这种语气提出来的要求？
