### ISSUE TITLE
能不能和 Deepin 合作增加Linux版？

### ISSUE THREAD

**Issue by initlinux** [Snipaste/feedback#573]
基于Qt 的程序，转到Linux系统难度应该相对较小，希望在 Deepin Linux 早日用上。

**Comment by hosiet** [comment]
@gzucode 不太清楚为什么会出现 deepin 的名字，不过可以去尝试一下 deepin-screenshot，功能不算多但是也不少，而且是开源的

**Comment by liulex** [comment]
Deepin 有自己的开源截图软件。

**Comment by leafmark** [comment]
请删除这个issue
