### ISSUE TITLE
关于截图时的放大镜十字线的建议

### ISSUE THREAD

**Issue by cangyuyao** [Snipaste/feedback#576]
可以看出现在十字线的粗细为一像素，而从使用画面中很难看出十字线所占据的这一像素的部分是否被包含在截图范围中（经过几次试验后可以得知是包含的）。
![-2](https://user-images.githubusercontent.com/3854729/30328037-c3f692e0-9800-11e7-8857-7fdd0f78053c.jpg)
![-3](https://user-images.githubusercontent.com/3854729/30328047-cb17e1be-9800-11e7-8720-9473dfa86657.jpg)

下图是Snagit的十字线放大镜，十字线处在像素和像素之间的分界线上，很容易判断截图起始和终点的位置。
![snag- 2017-9-12 21 27 51](https://user-images.githubusercontent.com/3854729/30328226-4de8395e-9801-11e7-9839-f8699de222dd.jpg)

**Comment by liulex** [comment]
Snagit 这种方式无法指示光标所在像素点的颜色（中心点同时指到了四个像素）。
其实只要记住光标所在点一定是在截图范围内就好了。
以后也会有更美观的显示：
![default](https://user-images.githubusercontent.com/2010459/30330851-c3524818-9808-11e7-86ba-b9b5159594e9.png)

**Comment by cangyuyao** [comment]
我现在当然记住啦。在新手教程里稍微说明一下包含在截图内也可以，不然每个和我掐像素的人都要自己试也太……。

**Comment by liulex** [comment]
但实际没多少人会在意这个，而在意每个像素的人自然能够发现这个规则。
