### ISSUE TITLE
高亮效果不够明显

### ISSUE THREAD

**Issue by wseven7677** [Snipaste/feedback#580]
高亮的功能（或者叫做荧光笔）
请问现在的实现方式是对黄色区域做半透明的处理吗？
希望能够使用“正片叠底”效果，
因为感觉目前高亮一段黑色的文字会使黑色字体变得灰秃秃的的，没有起到高亮效果。
~
望采纳，谢谢

**Comment by zhaiyusci** [comment]
I just opened a issue talking about the same problem ;-)
#596 

But since I add a picture there so I refer it here.  I will close that issue.

**Comment by liulex** [comment]
@zhaiyusci @wseven7677 谢谢你们的详细描述。
Snipaste 的高亮功能就是简单的半透明颜色叠加，因为现实生活中的马克笔就是这样的。
由于我们并不总是使用半透明亮黄色作为马克笔颜色（实际上使用马克笔的时候用户甚至可以设置成不透明的颜色），如果使用其他图片处理效果，恐怕在使用其他颜色的时候，效果会不好/难以预测？

**Comment by liulex** [comment]
😅 我在 [#616](https://github.com/Snipaste/feedback/issues/616#issuecomment-341783681) 改变了想法…… 你们的提议会在 1.15.2 中实现~
