### ISSUE TITLE
与Sticky Notes兼容性问题

### ISSUE THREAD

**Issue by kuretru** [Snipaste/feedback#581]
系统环境
Win10 x64 专业版 1703
Snipaste x64 1.14
Sticky Notes 1.8.0.0

当Snipaste在后台运行的情况下,从Sticky Notes中复制文本时，会发生无法复制的情况。表现形式为Sticky Notes 无响应，30秒后Sticky Notes崩溃退出，无响应期间操作系统剪切板功能失效，任何复制粘贴操作(文本、图片、文件)均无法完成。Snipaste未运行时正常，向Sticky Notes粘贴文本时正常。

**Comment by liulex** [comment]
刚从商店下载安装了 Sticky Notes，开着 Snipaste 复制文本没有遇到什么问题。
从商店的评论来看，是 Sticky Notes 自身的问题。
