### ISSUE TITLE
建议增加通过方向键 + Enter 选取截图区域

### ISSUE THREAD

**Issue by gitczk** [Snipaste/feedback#582]
用了一阵子这个软件，感觉很不错，尤其是贴图功能，对于看文档很方便，不用翻来翻去看上下文。

之前用 FSCapture 可以通过方向键+Enter精准到像素点的截图，希望这个软件也可以支持。

**Comment by Genteure** [comment]
@gitczk 试一下按 W S A D

**Comment by gitczk** [comment]
W S A D也是一样的效果，一回车就完成截图，不能选取起始点，结束点

**Comment by liulex** [comment]
你需要的其实是类似于 回车键执行鼠标左键点击 的功能，这个功能似乎太小众吧。
Snipaste 是无法满足所有用户在其他截图软件的习惯的，实际上，相比其他软件，Snipaste 已经有多种方式（快捷键或鼠标操作）可以实现精确调整选区的目的，我认为已经足够多啦。

**Comment by gitczk** [comment]
是的，方向键以一个像素点移动，回车键用于确定起始点、结束点，用能鼠标操作没有办法精确到一个像素点。
