### ISSUE TITLE
建议增加功能：将截图保存至七牛云存储或微博图床

### ISSUE THREAD

**Issue by shuaiyy** [Snipaste/feedback#583]
请求新功能？
* 功能：截图后，可以选择将图片保存到七牛云或微博图床，然后复制七牛云返回的外链到剪切板
* 因为经常用markdown写博文，图片存储是用的七牛云存储。每次插入图片都是先截图保存到桌面，然后通过chrome插件极简图床上传图片，得到图片外链后再插入我的markdown文档中。
* 如果可以一键上传图片，就会节省很多处理图片的时间，而专注于写作本身。
* 另外在贴吧/论坛回帖时，使用图床链接也比** 截图-保存-上传-引用图片 ** 要省时省力很多

**Comment by shuaiyy** [comment]
七牛云的免费用户有10GB的存储空间，对于个人博客完全够用。
[官方有api文档和sdk工具](https://developer.qiniu.com/kodo/sdk/1242/python)，用户只要提供secret_key, access_key, bucket_name就可以通过HTTP Post将图片文件上传至云空间。

**Comment by Rictusempra** [comment]
@shuaiyy out of scope?

**Comment by shuaiyy** [comment]
@Rictusempra 保存图片是很正常的需求呀，保存到本地可以，保存到云就不行吗？个人希望能够作为可选功能或插件提供给用户，或者提供接口，至于怎么上传/传到哪里可以让需要的人去实现代码

**Comment by shuaiyy** [comment]
在 #188 有人提出过类似建议，作者是没打算实现这个功能吗？
我找到了一个替代方案，现在这个问题可以关闭了。
使用Mpic图床神器，这个工具有截图/复制图片后自动上传到七牛云，
上传成功后，外链自动进入剪切板。
下面的图片是用Snipsate截取，然后粘贴到此处。
![mark](http://o8i01ajlj.bkt.clouddn.com/blog/170920/Jc3K8g77Ch.png?imageslim)

**Comment by liulex** [comment]
@shuaiyy 谢谢你提供的解决方案。
Snipaste 不打算往这方面发展，但以后会提供相关的插件接口。
