### ISSUE TITLE
双屏时无法正确检查第二屏下全屏模式的浏览器的截取区域

### ISSUE THREAD

**Issue by zlowly** [Snipaste/feedback#584]
我的操作系统是64位WIN10，使用双屏，Snipaste 1.14(2017.08.04)。
如果在第二个屏幕上开启浏览器（IE、Chrome或Firefox）全屏模式，再按F1截图，Snipaste在第二屏上检测出的区域会不完整，缺少了底部任务栏大小的一块区域。例如全屏是1920x1080的话，Snipaste就只选择了1920x1040大小。

**Comment by liulex** [comment]
谢谢反馈，已经修复。
