### ISSUE TITLE
希望增加重复上一次截图的快捷键

### ISSUE THREAD

**Issue by Alextan771** [Snipaste/feedback#585]
功能：希望增加重复上一次截图的快捷键，以及修改上一次截图区域的快捷键。

用法：点击快捷键之后，可以重复对上一个区域的截图，或是移动上一次截图的区域。

原因：视频截图中经常需要对同样一个区域进行重复截图，比如视频区域或者字幕区域。

**Comment by Rictusempra** [comment]
![image](https://user-images.githubusercontent.com/16912240/30779089-d3cd1baa-a118-11e7-8d0d-c06908d594fb.png)

**Comment by kmcbest** [comment]
这个还是不够一步到位，相当于要发起截图，设置区域，截到图再操作保存，需要按至少三个快捷键。能不能就一键把这几个步骤做了，连续截电影对话很有用。

**Comment by liulex** [comment]
![Image](https://github.com/user-attachments/assets/13ee8c53-f967-4e80-9598-88a6e5d6b6ed)
