### ISSUE TITLE
贴图的标注中存在问题

### ISSUE THREAD

**Issue by funshioner** [Snipaste/feedback#587]
贴图中标注时文字等的颜色总是默认的红色，应该改成用户上次使用的颜色。

贴图中标注时的文字内容中不能输入标点符号，而截屏时就能正常输入。

希望改进。

**Comment by funshioner** [comment]
我说的不能输入标点符号是在中文输入法的时候，在英文输入法时可以。希望能解决一下。

**Comment by liulex** [comment]
[工具条设置问题](https://github.com/Snipaste/feedback/issues/420)

[输入法问题](https://github.com/Snipaste/feedback/issues/358#issuecomment-284138836)
