### ISSUE TITLE
能否增加选取像素点自动切换16进制和RGB

### ISSUE THREAD

**Issue by liangjian1995091** [Snipaste/feedback#588]
现在的软件似乎只能通过设置首选项来固定选取像素点时按C键获得的是16进制还是RGB,能否直接在截图区通过键盘快捷键切换获得的是RGB还是16进制,因为平常用到PS会使用16进制,而用到其他软件用的却是RGB呢!谢谢

**Comment by liulex** [comment]
![default](https://user-images.githubusercontent.com/2010459/30946199-24dd1a58-a435-11e7-9d82-25b7a2233d86.png)
