### ISSUE TITLE
希望增加文本快速复制

### ISSUE THREAD

**Issue by jadedrip** [Snipaste/feedback#589]
非常好用的软件，感谢作者。

对于文本转的贴图，希望有一个能快速将之复制到令一个窗口的操作 （比如按着 Ctrl 右键从贴图拉去窗口）
以替代——点贴图，按 Ctrl-Shift-C，点目标窗口，按 Ctrl-V 这一系列操作，这样可以作为一个简单的剪贴板管理软件使用，谢谢。

**Comment by liulex** [comment]
这个问题的关键在于，修饰键不太够用了。。<kbd>Ctrl</kbd> 已经用在贴图多选操作了。

**Comment by jadedrip** [comment]
所以用右键拉啊，当然我只是个建议，按什么可以商量，或者可以设置。
PS: 图片也应该可以粘贴，比如要贴去 QQ 群这种支持图片粘贴的地方。

**Comment by gongnl** [comment]
这个功能确实很常用和必要，我以前也向作者提过新增建议。如果贴图是从选中文本(Html文本、Word和Exce等选中的文本块)生成的，可以考虑只要在贴图左上角 和 右上角 指定区域按下鼠标，鼠标形状发生变化即可进行拖拉完成粘贴，左上角 和左下角 按下分别表示拖拉粘贴纯文本和带格式文本。
