### ISSUE TITLE
无效的文件命名规则！文件名不能为默认的Snipaste_$yyyy-MM-dd_HH-mm-ss$.png

### ISSUE THREAD

**Issue by ImFengLala** [Snipaste/feedback#593]
默认的文件名不能自动保存，手动保存也不行，改文件名就行
这里有日志，我打开到跟踪模式，还是没看到什么有关的东西
![_o 1 wv3w2 ansc_gns u](https://user-images.githubusercontent.com/24974976/31067474-a78a054e-a785-11e7-8c21-bbc033b672fc.png)
Ctrl + C时(或者鼠标点那个复制，都一样，能成功把截图复制到剪切板)只有 无效的文件命名规则 这一个报错
Ctrl + Shift + S时有俩报错 如下图
![2rzngw1 kpxl t3 q 8](https://user-images.githubusercontent.com/24974976/31067517-dcd5a938-a785-11e7-9626-1eac6fee3aea.png)
Ctrl + Shift + S前确定目录地址正确并且是以管理员身份启动的
![1fe_shb7lk zj4fwlc 9y 7](https://user-images.githubusercontent.com/24974976/31067560-13fa8136-a786-11e7-86ae-8c423016f847.png)
开到跟踪模式，还是没看到什么有关的东西
![_o 1 wv3w2 ansc_gns u](https://user-images.githubusercontent.com/24974976/31067474-a78a054e-a785-11e7-8c21-bbc033b672fc.png)
Ctrl + C时只有 无效的文件命名规则 这一个报错
Ctrl + Shift + S时有俩报错 如下图
![2rzngw1 kpxl t3 q 8](https://user-images.githubusercontent.com/24974976/31067517-dcd5a938-a785-11e7-9626-1eac6fee3aea.png)
是以管理员身份启动的，权限不存在问题
![1fe_shb7lk zj4fwlc 9y 7](https://user-images.githubusercontent.com/24974976/31067560-13fa8136-a786-11e7-86ae-8c423016f847.png)
我把文件名改成Snipate_$yyyy-MM-dd_HH-mm-ss$.png就能用了，就是去掉snipaste中的s，并不知道为什么，改成其他的也行，反正就是不能用默认的

**Comment by liulex** [comment]
Hi，这是 1.15 的问题，升级到 1.15.1 就好了。谢谢你的详细描述！
