### ISSUE TITLE
Maybe a bug: Marker highlighting may use the wrong blend mode

### ISSUE THREAD

**Issue by zhaiyusci** [Snipaste/feedback#596]
I am not sure if I use the right words.  The marker tool is great but I find that when I use marker, the pattern under it may look wild.  You can compare the result of the marker in Snipaste and Adobe reader.

In real world we use a marker or highlighter to make the words more easy to be find and read.  In Snipaste, however, the black test is more hard to read because it is also "lighter".

I paste a image to help explain what I said above.

![image](https://user-images.githubusercontent.com/3461548/31425099-5c204f16-ae90-11e7-98b7-49d6ce0de2af.png)

**Comment by zhaiyusci** [comment]
In the old issue this problem has been mentioned.  Issue closed.  May be we should discuss about this in that issue.

**Comment by liulex** [comment]
Thank you very much for your detailed desciption. 👍
