### ISSUE TITLE
发现bug，chrome浏览器中截图时候自动识别边框失效了

### ISSUE THREAD

**Issue by zhFengXiao** [Snipaste/feedback#597]
#发现bug
环境：win10 专业版
描述:
1，在chrome【61.0.3163.100（正式版本） （64 位）】中自动识别边框是错乱的；
      频率：必现；
2，在eage中非全屏边框识别正常，全屏的时候会偶现出现识别失效；
3，ie中识别一切正常

**Comment by Rictusempra** [comment]
![image](https://user-images.githubusercontent.com/16912240/31482890-c0aefbae-af5c-11e7-92dc-42b67c192f95.png)

**Comment by zhFengXiao** [comment]
谢谢回复，知道了
