### ISSUE TITLE
新功能建议：增加一个录制功能

### ISSUE THREAD

**Issue by lzp00** [Snipaste/feedback#599]
录制一段屏幕操作。比如演示一些复杂的设置什么的。这个会比较有价值。软件企业客服应该会需要这个功能。
最好能把录制结果存成gif等格式。还可以进一步考虑同时保存声音。

这是个很不错的软件。希望你们越做越好！

**Comment by septs** [comment]
see https://github.com/Snipaste/feedback/issues/282#issuecomment-268239323
