### ISSUE TITLE
自动检测界面元素在twitter上多图tweets无法正确识别边框

### ISSUE THREAD

**Issue by MaiTestarossa** [Snipaste/feedback#604]
一个tweet如果只有一个图片都可以正确识别边框
但是如果有多个图片，在点开图片后，用snipaste截图就会识别成左右2边，不管一个tweet里有2图还是3图、4图都这样

_https://twitter.com/houseki_anime/status/921734217339252736
_https://twitter.com/hobby_magazine/status/921737853167472640

就像截图这样
![snipaste_20171021_221441](https://user-images.githubusercontent.com/20226906/31852628-7a3cabfa-b6ad-11e7-9809-49827475b65f.png)

**Comment by Rictusempra** [comment]
@MaiTestarossa 有一个临时的替代方案是FIrefox Screenshot或者一些浏览器扩展（如果元素边界检测对你来说很重要的话）

**Comment by MaiTestarossa** [comment]
@Rictusempra Firefox Screenshot 试了下竟然和snipaste一样，识别成2半，看来twitter的边界检测是个难题

**Comment by Rictusempra** [comment]
@MaiTestarossa 这并不意外
在F12上看看Twitter的脚本内联了多少圈就知道了

**Comment by septs** [comment]
@MaiTestarossa 
你所看到的识别区域是 Twitter 对于 tweets 图片上下翻页设计的
原则上来说 Snipaste 不应对于任何浏览器及站点做出特殊处理
如果您是只是在乎您所使用的特定浏览器下的问题请寻找其他的第三方拓展解决方案

因此该问题无效
