### ISSUE TITLE
桌面版下自动安装更新

### ISSUE THREAD

**Issue by Rictusempra** [Snipaste/feedback#605]
如有必要，使用一个选项来切换启用这个行为

**Comment by septs** [comment]
请使用 https://www.microsoft.com/store/productId/9P1WXPKB68KX 版本作为代替

**Comment by Rictusempra** [comment]
@septs 您误会我的意思了 我的意思就是在桌面版加上自动安装更新的功能（我自己也用的商店版

**Comment by liulex** [comment]
@Rictusempra 桌面版的在线更新以后应该会使用第三方的实现，所以暂不考虑做进一步改进了。
