### ISSUE TITLE
●●●●●●●●建议坐标从1，1开始●●●●●●●●

### ISSUE THREAD

**Issue by JJJZ** [Snipaste/feedback#606]
■进入截图功能后，会自动选择1x1像素，此时提示是0，0。可能对于程序员来说数值是从0开始，单我相信对于大众来说都是从1开始的，这样也好照应截全屏的时候不会-1。
■或者可以把坐标值改为截图的像素大小，仅仅只是显示鼠标的坐标值对于截图来说意义不大。

**Comment by EtaoinWu** [comment]
* 请问一下显示-1是什么情况？
* 截图的像素大小是有显示的。

**Comment by JJJZ** [comment]
首先抱歉，我之前没有注意到左上角有像素大小显示。
-1就是像素的位置，例如F1截图的时候，把鼠标移动到桌面左上角顶端，此时显示0，0。按F3后贴图，可以得到一张1x1px的图片，把鼠标移动到桌面右下角的时候我1920x1080的屏幕会显示坐标值1919x1079，此时所有的数值都是“-1”的。
我的建议是既然截图的时候默认就有1px了，何不就从1开始，对于大众来说从0开始得绕一下弯。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Wu Yue<mailto:notifications@github.com>
发送时间: 2017年10月22日 下午 5:29
收件人: Snipaste/feedback<mailto:feedback@noreply.github.com>
抄送: 踽踽家族<mailto:ixixixixixixi@live.com>; Author<mailto:author@noreply.github.com>
主题: Re: [Snipaste/feedback] ●●●●●●●●建议坐标从1，1开始●●●●●●●● (#606)


  *   请问一下显示-1是什么情况？
  *   截图的像素大小是有显示的。

―

**Comment by liulex** [comment]
坐标值和选取大小的逻辑是不一样的，我认为没有必要让屏幕坐标从 1 开始，那样甚至是不合理的。
例如，当你使用多屏，并且副屏在主屏左边或上面的时候，屏幕坐标在副屏上会出现负值。这时候如果使用 1-based 的坐标，副屏的坐标就会让人很费解了。

**Comment by JJJZ** [comment]
恩，看来是我考虑欠妥。另外，很喜欢这个软件，祝越来越好。

IOS Outlook<https://aka.ms/qtex0l>客户端
________________________________

**Comment by ysc3839** [comment]
@JJJZ 操作系统都是 (0, 0) 开始的，各种绘图软件也是，所以我觉得没必要……

**Comment by JJJZ** [comment]
的确是这样。还有一点让人很疑惑，程序运行久了后会对截图表现的迟钝吗？我要等4s或以上才会进入截图操作。配置文件没有那个x时间后运行一次的代码设置，我私自加上那段代码后也未得到感觉上的提升，然后我有把那段代码删除了。（检查过更新）

IOS Outlook<https://aka.ms/qtex0l>客户端
________________________________

**Comment by liulex** [comment]
@JJJZ #360 #373
