### ISSUE TITLE
UWP版本在开机启动时，会启动两个相同实例

### ISSUE THREAD

**Issue by Blacktea2333** [Snipaste/feedback#607]
### 问题描述

当前使用的版本是UWP 1.15.1，在 Windows 1709更新以后，下次开机时发现同时启动了两个相同的实例，并导致两个实例中随机一个在绑定同一个快捷键时失败。两个实例指向的是同一个可执行文件。并且无法通过开始菜单来创建第三个实例。
![image](https://user-images.githubusercontent.com/13018564/31860400-f515183c-b74b-11e7-8c01-a051f4517432.png)
![image](https://user-images.githubusercontent.com/13018564/31860401-07535f04-b74c-11e7-9950-25c4a7f191ec.png)

![image](https://user-images.githubusercontent.com/13018564/31860243-eacca0e0-b749-11e7-99c7-4dd49487c6c5.png)

![image](https://user-images.githubusercontent.com/13018564/31860390-af05907e-b74b-11e7-8894-e5eafce26e30.png)

任务管理器的启动选项页中只显示一个 Snipaste，在禁用以后，下次开机就一个实例都没有启动。
在尝试通过系统商店重装多次后，问题依旧存在。

#### Windows
版次： Windows 10 专业版
版本：1709
OS内部版本：16299.19

#### Snipaste
版本 1.15.1 (UWP 64位)

**Comment by liulex** [comment]
谢谢你详细的描述。
再问两个问题：
1. 电脑上是否还有 Snipaste 的桌面版并启用了开机启动？
2. 在升级到 1709 之前是否存在这个问题？

**Comment by Blacktea2333** [comment]
1. 没有安装桌面版
2. 之前没有问题，是在升级到1709以后的第一次启动就出现了这个问题

**Comment by liulex** [comment]
谢谢，我会尽快升级系统试试。

**Comment by Rictusempra** [comment]
我这里环境一致
但是仅仅是提示已有运行实例

**Comment by liulex** [comment]
@Blacktea2333 我测试了下，1709 会在开机后恢复部分应用的状态，比如程序 A 在关机前是打开状态，那么下次开机后系统会自动打开它。
这就让`开机启动`这个选项比较尴尬了……

不过我测试了好多次，没法重现双开的情况（出现两个托盘图标），我这边和 @Rictusempra 的情况医院，只会提示 Snipaste 已经在运行。

另外，如果在任务管理器中禁用掉商店版 Snipaste 的开机启动，并且在关机前保持商店版 Snipaste 还在运行，那么下次开机后 Snipaste 会被系统恢复，而不是像你那样一个都启动不了……

**Comment by Blacktea2333** [comment]
@liulex 不好意思，是我之前测试的时候记错了。在任务管理器中禁用掉商店版 Snipaste 的开机启动，并且在关机前保持商店版 Snipaste 还在运行的情况下，的确 Snipaste 会在下次开机时被恢复。
现在暂时禁止开机启动，作为一个折衷方案

**Comment by kawori** [comment]
更新 OS 到 1709 之后，我也出现了与 Blacktea2333 相同的情况，但是在 1703 版本是正常的。

**Comment by uitra110** [comment]
两个启动我也遇到过  不过我把商店版的卸载了
