### ISSUE TITLE
更新pc之后有两个图标

### ISSUE THREAD

**Issue by Cyan-Coco** [Snipaste/feedback#608]
开发者你好，问题是这样的
我的机子前几天更新了1709
更新完以后任务栏右下角小图标区域同时出现两个snipaste图标
我以前先是用的exe版本，后来在商店发现有uwp版本就下载了uwp版本
exe我设定了开机自启
uwp我也设定了开机自启
但是
在升级1709之前我没有遇到两个图标的情况
现在却有这个情况

**Comment by liulex** [comment]
谢谢反馈，该问题会在 #607 跟踪解决。
