### ISSUE TITLE
截图时怎样能够截取二级菜单啊？

### ISSUE THREAD

**Issue by canbaojun** [Snipaste/feedback#609]
截图时怎样能够截取二级菜单啊？让二级菜单不消失！

**Comment by liulex** [comment]
[故障排除](https://github.com/Snipaste/feedback/wiki/%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4#%E6%97%A0%E6%B3%95%E6%88%AA%E5%8F%96%E8%8F%9C%E5%8D%95%E4%B8%80%E6%8C%89%E6%88%AA%E5%9B%BE%E5%BF%AB%E6%8D%B7%E9%94%AE%E8%8F%9C%E5%8D%95%E5%B0%B1%E6%B6%88%E5%A4%B1%E4%BA%86)
