### ISSUE TITLE
[feature request] 配置云同步

### ISSUE THREAD

**Issue by Rictusempra** [Snipaste/feedback#610]
比如 OneDrive, Dropbox, Yandex, Google Dive 这些具备公开 API 的云盘
比较起来 OneDrive 或者 Dropbox 比较容易实现？

**Comment by Rictusempra** [comment]
也许，连同贴图一起同步更有意义?

**Comment by liulex** [comment]
see #445 
不过目前只能单向同步配置，双向同步会在专业版加入。
