### ISSUE TITLE
2K分辨率下无法高清截屏

### ISSUE THREAD

**Issue by Git2Frank** [Snipaste/feedback#611]
如图，2K分辨率下截屏，内容区域会自动缩小变成屏幕左上角的一块，截出来的就很模糊。QQ带的截图也是这样，不懂是为啥。

![image](https://user-images.githubusercontent.com/21982381/31875126-5707dda0-b7ff-11e7-8cf7-d3d6b4f652f4.png)

![image](https://user-images.githubusercontent.com/21982381/31875239-caefb1fc-b7ff-11e7-85d8-d9c409b061a4.png)

**Comment by liulex** [comment]
Hi, 请把日志文件 `splog.txt` 发送到 <snipaste.app@gmail.com>.

**Comment by Git2Frank** [comment]
@liulex 已发送。

**Comment by liulex** [comment]
@Git2Frank log 看起来一切正常，对你屏幕的检测都是正确的。。试试升级下显卡驱动？

**Comment by Git2Frank** [comment]
@liulex 测试了下，是多显示器且系统设为复制状态才出现的问题。。
![image](https://user-images.githubusercontent.com/21982381/32034376-dcd767ec-ba44-11e7-8142-b0ed94d835b0.png)
显示器1是1920*1080，2是2560*1440
改成扩展或者仅在2上显示就没问题了。

**Comment by liulex** [comment]
复制的话肯定是没办法处理的吧。

**Comment by Git2Frank** [comment]
@liulex 嗯，甭管这个了~
