### ISSUE TITLE
拨掉 HDMI 线后 Snipaste 崩溃

### ISSUE THREAD

**Issue by phtwo** [Snipaste/feedback#612]
发现了 bug
* 电脑扩展方式连接外接显示器，拔掉 HDMI 线，Snipaste 崩溃了，基本都能重现
* version: 1.15.1

**Comment by phtwo** [comment]
曾经在这里提到 https://github.com/Snipaste/feedback/issues/522#issuecomment-338971708

**Comment by liulex** [comment]
这个我无法重现……
请问如果是手动双击打开 `snipate.exe`，还能重现吗？

**Comment by phtwo** [comment]
@liulex 已发邮件
