### ISSUE TITLE
希望能够通过编辑框输入的方式自定义截图的的尺寸

### ISSUE THREAD

**Issue by krisnotepad** [Snipaste/feedback#614]
因为经常需要对比软件修改后不同的显示效果（比如右下方的一个标志），因此需要在屏幕固定的位置截取固定大小的图（如300x400位置截取一个450x500的图）。然而周围没有满意的光标锚定的区域，因此每次都需要操作鼠标到指定位置和拖动区域到固定大小。

希望截图的时候能够增加以下功能：
1 通过编辑框的方式修改截图的尺寸，而不仅仅是通过拉动边框（比如说，截图左上方显的尺寸可以通过单击来修改）；
3 截图框左上角尺寸显示附近也显示截图的位置（如左上角的坐标），同时截图位置也可以通过点击修改；
2 下次截图时能够默认为上次操作成功时的截图位置和尺寸（用户可以勾选是否需要）；

非常感谢！

**Comment by liulex** [comment]
你可以通过在截图时按 <kbd>R</kbd> 键实现你的需求。
事实上，这种方式完全能满足我对相同区域/大小多次重复截图的需求，手动输入截图大小我觉得没有必要。

不过，这一项还是放进 TODO 里了…… #28
