### ISSUE TITLE
SniPaste Windows Store version not working

### ISSUE THREAD

**Issue by niceke** [Snipaste/feedback#615]
When install Snipaste from the windows store i always get an error when i try to start, also try on other computers but same problem

Windows 10 enterprise

![naamloos](https://user-images.githubusercontent.com/33277859/32264392-c94151ae-bede-11e7-8acc-cbb3f4e28d81.png)

https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by liulex** [comment]
Try reinstalling Snipaste?
This should be a bug of Windows or Windows Store. I am afraid I can do nothing about it.

**Comment by niceke** [comment]
did try many times. The problem is that it happens on all corporate PC's
where i did try it on. One PC ok can happen, all PC's then there is some
conflict with the OS i think. Windows 10 enterprise!

Op 1 nov. 2017 6:07 p.m. schreef "Le Liu" <notifications@github.com>:

Try reinstalling Snipaste?
This should be a bug of Windows or Windows Store. I am afraid I can do
nothing about it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Snipaste/feedback/issues/615#issuecomment-341171154>,
or mute the thread

**Comment by liulex** [comment]
Does it happen with other converted apps? For example, [ditto-cp](https://www.microsoft.com/en-us/store/p/ditto-cp/9nblggh3zbjq)?

**Comment by niceke** [comment]
Yes also same problem so will be some restriction from the IT department

Op 1 nov. 2017 6:49 p.m. schreef "Le Liu" <notifications@github.com>:

Does it happen with other converted apps? For example, ditto-cp
<https://www.microsoft.com/en-us/store/p/ditto-cp/9nblggh3zbjq>?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Snipaste/feedback/issues/615#issuecomment-341185139>,
or mute the thread

**Comment by liulex** [comment]
Thanks for the info. So the problem is not app-specific. Issue closed.
