### ISSUE TITLE
建议增加Chrome浏览器网页窗口的识别

### ISSUE THREAD

**Issue by Sostay** [Snipaste/feedback#617]
希望可以识别到完整的网页窗口内容边缘（不包括浏览器边框 标题栏等）经常网页全屏看视频的时候可以直接截取视频部分 而不需要手动裁剪 望考虑加入支持 感谢！！！

**Comment by septs** [comment]
see https://docs.snipaste.com/zh-cn/troubleshooting?id=%E6%88%AA%E5%9B%BE%E6%97%B6%E6%97%A0%E6%B3%95%E8%87%AA%E5%8A%A8%E9%80%89%E5%8F%96-chrome-%E6%B5%8F%E8%A7%88%E5%99%A8%E7%AA%97%E5%8F%A3%E7%9A%84%E9%A1%B5%E9%9D%A2%E5%85%83%E7%B4%A0

**Comment by Sostay** [comment]
按照这个操作 没有任何效果呀？我的打开方式不对么~

**Comment by liulex** [comment]
我发现 Chrome 辅助功能的设置页面发生了改版，现在应该是勾这个：

![default](https://user-images.githubusercontent.com/2010459/32494426-9679f51e-c3fc-11e7-9a36-358ef3c345b9.png)

在线文档已更新。

**Comment by liulex** [comment]
我这是有效的，刚测试过。启动参数无误的话，全部勾都会勾上。

**Comment by Sostay** [comment]
嗯 刚刚试了 关键操作是勾选 
Web accessibility

**Comment by tongluyang** [comment]
弱弱的问一下，微信PC端截图是怎么识别chrome网页区域的，chrome未做任何设置
![image](https://user-images.githubusercontent.com/25279149/61363665-fdf95180-a8b6-11e9-9383-b08a1ef2aa15.png)
能借鉴一下吗

**Comment by septs** [comment]
@tongluyang 目前并不清楚 WeChat 是如何实现，无法借鉴。

**Comment by liulex** [comment]
@tongluyang 
https://docs.snipaste.com/zh-cn/advanced-configs

>[Snip]
crashes=chrome.exe
