### ISSUE TITLE
Caputure Mouse Pointer

### ISSUE THREAD

**Issue by koppor** [Snipaste/feedback#620]
Feature request

I neither found a [FAQ](https://www.snipaste.com/faq.html) nor did I found an issue: Is it possible to capture the mouse pointer? Currently, at all screenshots, the mouse is not captured. What if I'd like to capture it, too?

For instance, for showing the position of the mouse - maybe highlighted using http://www.rw-designer.com/cursor-maker

**Comment by liulex** [comment]
Already implemented. Two ways to do it:
![default](https://user-images.githubusercontent.com/2010459/32482403-8102c280-c3d2-11e7-824b-d1f652d1df90.png)

**Comment by koppor** [comment]
Cool! Could you add that to the FAQ please? With the word "mouse cursor" so that one finds it when searching for "mouse"?

**Comment by liulex** [comment]
Hmm... But this question may be not frequently asked enough to be included in FAQ ...
FAQs only contain a small portion of user questions. For more info, use https://docs.snipaste.com. It has a search tool, though not very good. 😅
