### ISSUE TITLE
希望增加一个标记序号的功能

### ISSUE THREAD

**Issue by IceWeet** [Snipaste/feedback#622]
功能描述：设定好背景色和文字颜色之后，可通过在截图的不同位置点击，来自动在点击位置生成序号增加的小标记，如 ①、②、③ 这种（实际效果最好是实心背景），由于可能涉及误点击需要删除的情况，标记上的序号最好能编辑

将来可进行的扩展：可设置圆形、菱形、方形等不同形状的标记，可通过滚轮调整标记大小

**Comment by liulex** [comment]
请合并至 #227 讨论。
