### ISSUE TITLE
能否实现滚动截图的功能？

### ISSUE THREAD

**Issue by Foutlook** [Snipaste/feedback#623]
请求新功能：
* 有点时候代码或者文章太多，一个屏幕根本装不下，如果想全部截下来，只能截一半然后F3贴图到屏幕，再去截另一半，实在是麻烦。我想这能不能实现一个功能，截图的时候可以实现页面的滚动，把所有内容截下来，也就是我们常说的截取长图片。谢谢！

**Comment by liulex** [comment]
代码：
![](http://ww2.sinaimg.cn/large/840a8430jw1f68ofsdw0ug20qv0hi1kx.jpg)

网页请使用浏览器插件。

其他讨论：#19
