### ISSUE TITLE
v1.15.2 截图后的标注状态下，除了记号笔之外无法更改颜色

### ISSUE THREAD

**Issue by xjacks** [Snipaste/feedback#624]
版本：v1.15.2
操作系统：Win7
用着用着发现，截图时的标注状态下，除了记号笔之外无法更改颜色，不论是选取面板上的颜色还是自己输入RGB都无法更改，一直处于透明颜色的状态。
贴图时的标注状态下一切正常。
重启后也无法改善。
附件是目录下的splog.txt和config.ini
[log.zip](https://github.com/Snipaste/feedback/files/1456406/log.zip)

**Comment by liulex** [comment]
就是因为你把 Alpha 值设成了 0 吧……
![default](https://user-images.githubusercontent.com/2010459/32615393-aa6afa32-c5aa-11e7-86dc-098b18249eab.png)

**Comment by xjacks** [comment]
果然是这个问题，我的Alpha通道是25……
估计是什么时候不小心修改了，谢谢！
