### ISSUE TITLE
Snipaste 快速保存和自动保存的路径无法设置 旧版本至1.15.2 (2017.11.06)

### ISSUE THREAD

**Issue by ZhLong-473811012** [Snipaste/feedback#626]
如图…都是按'更改'按钮来改变路径。
![image](https://user-images.githubusercontent.com/20869871/32687933-131779e0-c702-11e7-9a5c-323d0b01fe42.png)
![image](https://user-images.githubusercontent.com/20869871/32687934-186a882e-c702-11e7-93f2-b6d1ed0c0475.png)

实测是路径'$'符号所导致的, 去掉即可…

**Comment by liulex** [comment]
意思是通过“更改”按钮得到的路径会带有 ‘$' 符号？

**Comment by ZhLong-473811012** [comment]
不, 是 如果路径带有'$'符号就一定会出错。

**Comment by liulex** [comment]
嗯……并没有考虑路径自带 '$', '%' 符号的情况。。下版本修~
