### ISSUE TITLE
希望添加触摸屏和Surface Pen支持

### ISSUE THREAD

**Issue by Bimos** [Snipaste/feedback#627]
触摸屏体验已经很棒了，希望能够在贴图上添加两指放缩的功能。
希望Surface Pen在贴图上画的时候能自动转到笔的功能。如果能识别橡皮就更好了。压感倒是不一定需要。

**Comment by liulex** [comment]
两指缩放会在下个版本加上，见 #387 .
至于 Surface Pen，由于我没有设备，因此无法理解你的需求……

**Comment by drpmma** [comment]
他的意思可能是surface pen标注时的笔的压感

**Comment by drpmma** [comment]
然后用surface pen背后的“橡皮”触摸屏幕会有橡皮的效果

**Comment by drpmma** [comment]
另外能否让截图后的出现的功能图标更大一些，方便触屏交互

**Comment by septs** [comment]
Duplicate of #509
