### ISSUE TITLE
最新版本更新导致win10蓝屏

### ISSUE THREAD

**Issue by lufeibing** [Snipaste/feedback#628]
20171113
使用的是x64版。
推送版本没有留意，不知是不是官网最新的1.15.3
操作步骤：
（0）截图并粘贴至ONENOTE；
（1）在win10通知栏点击更新提示（单次一次未消除，双击一次提示消除），无反应；
（2）通过任务栏图标右键检查更新，正常进入更新检查（中途有个重定向）；
（3）更新窗口已关闭，等待跳出更新日志；
（4）win10蓝屏
（5）重启后点击原来的图标启动程序时提示“文件或目录损坏且无法读取”。
当时主要运行程序如下：
（1）VS2013 Update5
（2）蓝叠（BlueStacks)
（3）邮件客户端YoMail
（4）Wallpaper Engine
（5）QTTabbar
（6）Listary
（7）Free Download Manager
（8）其他一些显示驱动，蓝牙，系统自带程序
---

**Comment by liulex** [comment]
…………
重新下载 [1.15.2](https://bitbucket.org/liule/snipaste/downloads/)，然后尝试在线更新到 1.15.3 看看是否能重现？

**Comment by liulex** [comment]
搜了下 "“文件或目录损坏且无法读取”"，似乎是硬盘的错误？确定只有 snipaste.exe 出错吗？
另外，蓝屏相关的原因应该在系统的事件查看器有记录？

**Comment by lufeibing** [comment]
你提供的地址无法下载，snipaste没有更新完成，exe程序显示的是应用程序图标，并且有一个.old文件，刚刚已经被我用最新版本覆盖了。

**Comment by lufeibing** [comment]
现在无法确定是不是snipaste导致蓝屏。
在那个时候阿里安全软件也在更新，并且出现服务意外终止的错误。
系统Windows Defender 也在此前进行了更新。
有时间再重试一下升级过程。

**Comment by liulex** [comment]
那就只是巧合啦，其他原因导致硬盘出错，然后连累了 Snipaste...
Snipaste 的在线更新模块已经很久没改动了：
![default](https://user-images.githubusercontent.com/2010459/32717106-6d470042-c893-11e7-83e4-494fb2697f24.png)
