### ISSUE TITLE
抓图后如果在文件名栏重新输入新的文件名，则在目录会有2个重复的抓图文件（默认文件名+重命名的）

### ISSUE THREAD

**Issue by im0khu** [Snipaste/feedback#629]
--
* 抓图后如果在文件名栏重新输入新的文件名，则在目录会有2个重复的抓图文件（默认文件名+重命名的）

100%重现。

查了下历史的issue提交，发现没有反馈过。
难道这么明显的问题，没人遇到过？

**Comment by liulex** [comment]
另一个是自动保存的吧。
你勾了自动保存，又手动将截图保存到自动保存所在的文件夹，出现两个文件有什么问题？

**Comment by im0khu** [comment]
哦。确实是因为这个选项引起的。

不过，话说回来，我没看到“自动保存”的意义在哪里：

勾上后， 如果不重命名，则保存一份，这也是我要点一下保存按钮。
不勾，也是弹同样的保存对话框，我也要点一下保存按钮。

所以
1.如果你要重命名，则多一份文件给你
2.如果你不重命名，勾与不勾没有什么差别。

**Comment by liulex** [comment]
你的所有疑问都来自于没有理解好自动截图：
启用**自动保存**之后，所有**成功的截图**都会被自动保存。至于什么是成功的截图，请查看文档。

所以保存图片时是否重命名，对自动保存不会有影响。
自动保存一般只用来做备份或记录。
