### ISSUE TITLE
色彩信息的缩略图模式无法预览颜色

### ISSUE THREAD

**Issue by bestvow** [Snipaste/feedback#630]
常规色彩贴图
![snipaste_2017-11-16_11-34-20](https://user-images.githubusercontent.com/24888709/32872618-8cf9d1f4-cac2-11e7-95ed-7e6ca7c5a0fb.png)
缩略图状态的色彩贴图
![snipaste_2017-11-16_11-35-09](https://user-images.githubusercontent.com/24888709/32872621-935dee54-cac2-11e7-823c-359f196ac704.png)

貌似，无法通过缩略图看出来这是什么颜色。。。
比如目前的彩色边框以色彩本身的颜色来包边呢
像是这样
![snipaste_2017-11-16_11-35-09](https://user-images.githubusercontent.com/24888709/32872694-e1354b5e-cac2-11e7-9832-d367af18ee33.png)

**Comment by bestvow** [comment]
或者这样？
![snipaste_2017-11-16_11-35-09](https://user-images.githubusercontent.com/24888709/32875188-7669a928-cad1-11e7-97db-c2b3e4694e50.png)

**Comment by liulex** [comment]
第一个建议不错，第二个不行，不应该强行改变缩略图的内容，比如用户只需要 RGB，于是手动缩小成这样：
![default](https://user-images.githubusercontent.com/2010459/32890381-813bff94-cb09-11e7-864b-4b34d505dc02.png)
你再给他弄成正方形的的话……

**Comment by bestvow** [comment]
抱歉，能力有限，也就能提个建议了。。。
已经很感谢你制作这么好用的软件了，我和我的同事都非常喜欢

**Comment by liulex** [comment]
@bestvow 建议很棒啊~已经实现好了 😄
