### ISSUE TITLE
考虑下贴图增加桌面模式么，就是类似便签一样贴到桌面

### ISSUE THREAD

**Issue by mengppoo** [Snipaste/feedback#632]
一个程序员，日常开发对贴图用到很多，但是经常遇到，这个贴图是用来做个记录的，不需要置顶显示，想象，如果贴图可以类似便签应用一样贴在桌面上，那就很方便了

**Comment by liyidi33** [comment]
这个现在可以的吧

**Comment by mengppoo** [comment]
现在贴图不是置顶的么，我的意思是，只贴到桌面上，不遮挡其它窗口，只是在最底层

**Comment by liulex** [comment]
贴图选择性不置顶其实已经实现，打算作为 Pro only...
不过我自己使用的时候发现一点都用不上，对便签来说文本编辑更重要，所以 Snipaste 目前还是替代不了专门的便签软件，推荐 [Stickies](http://www.zhornsoftware.co.uk/stickies/index.html) ~
