### ISSUE TITLE
请求新功能：增加复制选区宽高功能。

### ISSUE THREAD

**Issue by Megasu** [Snipaste/feedback#633]
## 请求新功能

> 作为前端重构师，每天工作场景如下：
```
1. 打开Snipaste截取设计图的某一部分，贴到桌面，
2. 打开代码编辑器，然后按照Snipaste贴图准备写布局，
3. 测量模块的宽高，按快捷键C吸取颜色，手动输入宽高，粘贴颜色。
```
> 问题：每次都要手动输入宽高，若测量出来的宽高忘记了，还需要再按F1，再重新去测量一遍。
 
## 所以我们想要的功能是
>增加复制宽高需求，应用场景如下：
```
1. 打开Snipaste，按下F1，开始划选区截图(测量宽高)，
2. 按下快捷键D (Design的意思，Snipaste快捷键D暂时也一直保留没被占用)，
3. 自动复制当前选区的宽高，
4. 粘贴到项目中使用，(或把数值贴到屏幕上，记录下来，方便后续使用)
```
> 注：程序员同事，设计师同事，都有同样测量宽高需求。

### 建议提供两种可选格式：
格式1：
```
width:520px;
height:520px;
```
格式2：
```
width:520, 
height:520,
```
> 暂时想到这两种格式，其他小伙伴或者还有其他格式需求，或开放自定义格式。

# 感谢
感谢Snipaste作者，风间诗音(Sion Kazama)，以及给Snipaste提建议，上报Bug，推荐朋友使用等各位小伙伴。

**Comment by liulex** [comment]
谢谢，很用心的 issue 👍 
我会在下个版本加上这个功能，按键就用 <kbd>V</kbd> 吧（你提到的 <kbd>D</kbd> 实际已被占用，<kbd>A</kbd> <kbd>D</kbd> <kbd>S</kbd> <kbd>W</kbd> 是用于光标移动）。
将来专业版再提供自定义按键/文本格式。

**Comment by cooper1x** [comment]
现在按F3贴图，右键就能看到宽高了，很方便！
