### ISSUE TITLE
增加截图阴影特效.这样就超级省事了,不用再放到PS里面操作了

### ISSUE THREAD

**Issue by eluotao** [Snipaste/feedback#634]
朋友介绍才知道这么好用的截图软件....非常感谢您的提供.

在此有一个小小的建议..可能这个建议要若干年后才会有,不过那也不会影响我对这个小工具的喜爱....接下来的日子,我应该会用很久很久...并且频繁的使用.

我希望截图之后,增加一些图片的边框特效,比如阴影.这个在博客发文,微信发文竟然用的小特效.

https://wx2.sinaimg.cn/large/5e4ed30dgw1fbjeaswfr9j20ok0fsn2f   类似这个效果就行.

**Comment by liulex** [comment]
谢谢，也不用若干年，最多明年…… 😅  #83
