### ISSUE TITLE
截图时双击鼠标进行快速保存,快捷键关闭软件,关闭右下角的文件保存通知

### ISSUE THREAD

**Issue by shinji-ikari** [Snipaste/feedback#636]
情况如题.
知道可以设置ENTER 进行快速保存,以及CTRL+SHIFT+S可以快速保存.

就是想着能不能一只鼠标就搞定.不过翻来翻去也只看到"关闭贴图"这里有个左键双击,

快捷键关闭软件,是因为截图完了之后就不要了.貌似只能右键托盘退出? 习惯了软件都是用完就关....

快速保存保存了文件之后,发现右下角过几秒钟会弹框提示文件已经保存.因为已经设置了保存图片有声音.所以就有烦这个通知.可是没看到哪里关闭.是漏看了什么设置吗?

系统WIN7

**Comment by oott123** [comment]
@shinji-ikari 话说…用完就关不累么…

**Comment by shinji-ikari** [comment]
这个....还真不觉得累.
习惯了东西目前不用或者暂时不需要用的话就会关掉.不管是什么软件都这样....

**Comment by liulex** [comment]
那下次加个选项……

**Comment by shinji-ikari** [comment]
哦哦.那就辛苦了.
