### ISSUE TITLE
win10磁贴

### ISSUE THREAD

**Issue by guobing1993** [Snipaste/feedback#637]
请求新功能
 希望固定到win10开始屏幕的磁贴可以变成彩色的。至于左上那一块的颜色可以将颜色值调整，或者白色透明，这样就不会和原来的磁贴颜色重了。
![Snipaste_2017-11-21_16-42-57.png](http://upload-images.jianshu.io/upload_images/6191737-41bf0780a39f38c9.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
另外加个磁贴名吧

**Comment by liulex** [comment]
没理由只在这里改左上角颜色的……
何况蓝色只是系统默认的主题色，用户如果主题色是黄色呢？所以只有和系统其他图标一样用白色咯~

**Comment by liulex** [comment]
磁贴名会在下个版本加上~谢谢
