### ISSUE TITLE
我这个插件好像不能截图

### ISSUE THREAD

**Issue by Charltsing** [Snipaste/feedback#638]
http://www.cnblogs.com/Charltsing/p/DNATools.html    下载2.04版https://files.cnblogs.com/files/Charltsing/DnaToolsforExcelv2.04.rar

在Win10 64bit， office2013/2016 32bit下，运行2.04版的xll文件，点击DNA Tools选项卡，点击Active Cell Light，点击单元格，会在屏幕dc上画一个十字线。由于excel 2013及以后版本的特殊性，这个功能会在Excel窗口非激活状态去掉十字线，所以不能点击截图软件截图。按道理可以使用快捷键方式截图，但是截下来的没有十字线，只有背景excel单元格。
我在64位office下做的测试。32位的据别人测试可以使用Snagit截图，但我在64位office下使用snagit截图也没有成功。不知道是什么原因。
因为插件链接是32位的，如果需要64位的xll插件做测试，可以联系我的QQ：564955427。

32位excel2013可以截图，但是64位的excel2013好像不可以。而且我测试了很多软件都不行。

**Comment by liulex** [comment]
抱歉，我近期没有时间为你做测试……
不知道你的十字线是否是设置成了光标图案？如果是光标图案，截图时按下 <kbd>`</kbd> 补上光标图案即可。
另外，获取屏幕截图我是直接使用 Qt 的 'QGuiApplication::primaryScreen()->grabWindow()' 接口，所以也没什么能修的……
