### ISSUE TITLE
[需求]能否使用橡皮擦擦除原图的图像

### ISSUE THREAD

**Issue by jacquen** [Snipaste/feedback#639]
请求新功能？
*能否增加橡皮擦擦除原图功能，这样可以修改截图原图的内容

**Comment by codehz** [comment]
话说擦除原图想变成啥？

**Comment by StarryVoid** [comment]
相似功能，使用白色笔刷刷掉原图。

**Comment by Kiey1** [comment]
原PO的意思應該是希望可以用橡皮擦將原圖去背吧。
這樣就可以看見後面的背景。
比如說，截一個人物的頭像，將頭像依輪廓去背後，移到自己想要的位置
弄出有趣或可以再進一步截圖的畫面。
