### ISSUE TITLE
Windows 10 下，在截图输入文字时，C 键无效

### ISSUE THREAD

**Issue by zcdll** [Snipaste/feedback#640]
Windows 10 下，在截图输入文字时，C 键无效。

确认不是键盘的问题。

每次截图后需要输入文字的时候都很纠结。。。

怀疑可能跟内置快捷键 “C --- 放大镜可见时，复制颜色值” 有关系。

不过也有可能是因为我是在 Ubuntu 下，通过 VNC 连接  Windows 10 的原因。但是，我如果不打开截图，输入文字的话，C 键 是可用的。

谢谢！

**Comment by liulex** [comment]
see [高级设置](https://github.com/Snipaste/feedback/wiki/%E9%AB%98%E7%BA%A7%E8%AE%BE%E7%BD%AE)，增加：
```
[Snip]
do_not_omit_synthesized_c=true
```

**Comment by zcdll** [comment]
@liulex Problem solved! THX!!!
