### ISSUE TITLE
希望可以增加屏幕贴图收纳功能

### ISSUE THREAD

**Issue by AUGUSTDzw** [Snipaste/feedback#643]
请求新功能？

希望可以增加屏幕贴图收纳功能.
在创建了多个贴图的时候, 会发现整个屏幕看起来非常乱,  如果可以有个收纳功能,  比如 在屏幕的侧边/或其它地方 ,放置一个收纳框 ,然后把贴图都放在里面, 这样一来既美观又方便查看 ,还不影响其它应用的使用.
就像下面图片这样 , 如果这个收纳框还能自动贴边隐藏 , 鼠标悬浮再显示出来 就完美了

![image](https://user-images.githubusercontent.com/10017942/33356380-2081f86e-d4f7-11e7-8220-882e7414f17c.png)

**Comment by GregAMO** [comment]
@AUGUSTDzw 不影响其他应用使用：可以通过快捷键显示/隐藏贴图
贴图太多很乱：可以为贴图创建分组，可以直接缩小贴图，
可以选择贴图中标志性部分作为缩略图缩小贴图面积。

**Comment by liulex** [comment]
专业版会有触发角功能，方便显示/隐藏所有贴图。
