### ISSUE TITLE
win10 1709 下每次开机自启动 snipaste 都会有个新通知提示 snipaste 在后台运行

### ISSUE THREAD

**Issue by LuoDiKaiHua** [Snipaste/feedback#644]
RT
这个能不每次运行都弹出来吗？就是托盘的气泡消息~

**Comment by oott123** [comment]
@LuoDiKaiHua 关掉软件内的「开机启动」功能即可，亲测好使而且还是会正常开机启动，可能是 Windows 10 自动恢复应用的特性有关。
