### ISSUE TITLE
关于做笔记的时候用Snipaste复制图片到笔记本是默认PNG格式，造成笔记大小太大。

### ISSUE THREAD

**Issue by lifenots** [Snipaste/feedback#646]
默认截图模式下复制到剪切板是PNG格式的(体积大)，设置中的“输出”修改只能影响保存的格式结果，
但是操作中坐笔记截图是直接粘贴上笔记本的，造成笔记本体积庞大，保存缓慢。
问：如何设置“复制到剪切板”里的格式为JPG，(设置图像质量也行)。
五体投地式求助。

**Comment by lifenots** [comment]
做OneNote笔记经常用到各种截图，因为PNG格式，一个500M大小的笔记往往就变成1G了。

**Comment by lifenots** [comment]
设置里的输出后缀无论设置什么格式，截图的时候直接复制到笔记本QQ里另存出来都是PNG格式的，设个设置是截图的时候选择保存，默认的输出格式，但是截图的时候选择复制到剪切板就设置不了了。

**Comment by lifenots** [comment]
https://zh.snipaste.com/faq.html
好像说明了原因，13项，老大请尽快帮助下=  =一个笔记500M就变1G，1G变2G大小了。

**Comment by Rictusempra** [comment]
@lifenots 请勾选 以bitmap格式复制

**Comment by lifenots** [comment]
http://blog.sina.com.cn/s/blog_46dac66f010004ox.html
学习了这个文章，但是实际存在JPG和PNG大小差异还是很大。可以修改PNG的保存率吗》？

**Comment by lifenots** [comment]
https://www.binarization.com/archive/2016/jpg-gif-png/

**Comment by dlsdgj** [comment]
你可以暂时用WinSnap 替代 (自带阴影) 可以自动复制,调整图片质量 ,   配合WGestures的触发角功能(鼠标移动到屏幕一角匹配自定义的快捷键)

**Comment by dlsdgj** [comment]
![image](https://user-images.githubusercontent.com/20112812/33697045-f13c6572-db3f-11e7-8bda-25345f3c37ae.png)

**Comment by dlsdgj** [comment]
![155109](https://user-images.githubusercontent.com/20112812/33704201-805573c2-db66-11e7-913f-df58e01f45a3.png)

**Comment by dlsdgj** [comment]
FastStone可以完成所需功能,配合WGesture的按键序列
![image](https://user-images.githubusercontent.com/20112812/33793425-d612f630-dcf2-11e7-8905-340a3a49ae38.png)

![image](https://user-images.githubusercontent.com/20112812/33793428-dec4e5d6-dcf2-11e7-9e71-f7958d52ecfa.png)

![image](https://user-images.githubusercontent.com/20112812/33793436-f26b1542-dcf2-11e7-91c2-32a4dc3a4fb1.png)
![image](https://user-images.githubusercontent.com/20112812/33793442-19e4a138-dcf3-11e7-9adb-6271cef24081.png)

**Comment by dlsdgj** [comment]
![image](https://user-images.githubusercontent.com/20112812/33793464-797fa19c-dcf3-11e7-9f00-7dbd9ee0ec8b.png)

**Comment by dlsdgj** [comment]
![image](https://user-images.githubusercontent.com/20112812/33793528-f791838e-dcf3-11e7-8991-5326cac30e2c.png)

**Comment by dlsdgj** [comment]
如果WGestures 能匹配Windows徽标键那就又能省下不少步骤

**Comment by dlsdgj** [comment]
autoHotKey
![image](https://user-images.githubusercontent.com/20112812/34091989-ec9720b0-e3fb-11e7-9992-2f57e8447225.png)

**Comment by StarryVoid** [comment]
你的需求是指，在复制贴图时，复制到内存的文件能否改为jpg.
这个主要问题在于snipaste截图时有alpha通道，jpg没有此通道所以使用png格式。
暂且使用其他软件达成此效果吧。或者你先自动保存 并降低质量，然后在Onenote添加图片
