### ISSUE TITLE
[小强] 点击[截图>行为]页面[音效]选项下试听用的[播放]按钮时会调用系统文件关联程序

### ISSUE THREAD

**Issue by mtcw** [Snipaste/feedback#647]
小bug:点击[截图>行为]页面[音效]选项下试听用的[播放]按钮, Snipaste正常播放的同时还会调用系统文件关联的播放器.
snipaste版本: 1.15.2/ 1.15.3/x64
系统版本: Win10

**Comment by liulex** [comment]
谢谢反馈，已修复。
