### ISSUE TITLE
更新后还是会有两个图标

### ISSUE THREAD

**Issue by ExpPatronum** [Snipaste/feedback#648]
系统版本是秋季更新1709专业版，软件版本是1.15.3（2017.11.12）。开机出现两个图标，并有提醒快捷键注册失败。

**Comment by StarryVoid** [comment]
软件来源在哪？windows商店？官网下载？

**Comment by liulex** [comment]
见 #702

**Comment by ExpPatronum** [comment]
windows商店 @StarryVoid
