### ISSUE TITLE
建议：希望增加网页滚动截图的功能

### ISSUE THREAD

**Issue by April-BOY** [Snipaste/feedback#649]
建议：希望增加网页滚动截图的功能。
具体需求：在网页上进行截图，想截取网页不在屏幕中的那部分时，无法截到。希望增加这个功能，就是可以截到滚动条滑下去的部分。
理由：snipaste非常强大，它现有的功能可以说非常优秀了，但是，我在使用中，网页滚动截图是比较多的，而在浏览器中需要额外添加一个扩展，如果能使用snipaste实现这个操作，snipaste 就更加强大了，有点 Snipaste can get a screenshot from anywhere 的意思

**Comment by KazamaSion** [comment]
@April-BOY 作者并无开发此功能的意向，请转用其它浏览器插件。

**Comment by liulex** [comment]
浏览器插件能做到的，桌面软件做不到。
