### ISSUE TITLE
希望软件贴图不要总是前端显示

### ISSUE THREAD

**Issue by themechanicgithub** [Snipaste/feedback#650]
作者的软件确实给我不小帮助，但个人感觉有美中不足的地方就是软件的贴图功能总是前端显示。
使用贴图时会遮挡其他窗口的显示，不知作者是否有意愿，在以后的更新中，在贴图窗口右键菜单栏中加个“是否总是前端显示的功能”？

**Comment by GregAMO** [comment]
@themechanicgithub 通过快捷键可一键显示/隐藏所有贴图啊

**Comment by liulex** [comment]
会有的：
![default](https://user-images.githubusercontent.com/2010459/33513661-1d606e6c-d782-11e7-9615-d2ccef6e9ae3.png)
