### ISSUE TITLE
建议可以直接粘贴图片到其他文件夹

### ISSUE THREAD

**Issue by hwjllp123** [Snipaste/feedback#651]
目前只能快速保存到指定文件夹 ，如果我要截图到不同文件夹还需要一个个拖。 
比如我看电影时，想把某一个画面截图下来保存在某一个文件夹里。
现在的操作是， 按F1，然后F3，然后右键选路径保存。
我想实现的是， 按F1，然后ctrl+c复制，到我要的那个文件夹，然后ctrl+v粘贴。 
这样能省掉选路径的步骤 ， 如果保存很多不同路径的图片时能快很多

**Comment by GregAMO** [comment]
@hwjllp123 建议已收录
建议收集总目录见#282
该建议具体相关见#78
