### ISSUE TITLE
开机后第一次截图会卡顿几秒钟才出现截图界面

### ISSUE THREAD

**Issue by jacoii** [Snipaste/feedback#652]
我设置了“F1”键作为截屏快捷键，每次开机后第一次使用使用快捷键截屏（即F1），会卡顿几秒钟才能正常使用，往后就正常了，包括关闭并重启软件都没问题。
唯独每次重新开机以后的第一次才会发生上述情况。
附上日志文件，麻烦开发者帮忙看看究竟是为什么……
[Snipaste卡顿日志文件.txt](https://github.com/Snipaste/feedback/files/1523704/Snipaste.txt)

**Comment by zhuzhuhuawk** [comment]
## 卡顿问题

### 我也遇到同样的卡顿问题，第一次按 ` F1` 按键，就卡顿很久

**Comment by l317450813** [comment]
卡顿问题最新版本依然存在,不仅第一次使用,只要是隔一段时间没有使用,再次使用依旧反应很慢

**Comment by liulex** [comment]
2.0 已修复。

**Comment by gdh1995** [comment]
@liulex 您好，我换新电脑（从15-11300H到 R7-6800H）后遇到了同样的问题，一般是第一次进入截图界面时卡好几秒，偶尔是截完图点钉住时卡一会。

这是手动测试的详细版的日志：[splog - 20220619-0003.txt](https://github.com/Snipaste/feedback/files/8933929/splog.-.20220619-0003.txt)，操作过程是，正常退出后，从任务计划里启动 `Snipaste (Run As Admin) @4D20`，需要10秒才能在任务栏显示出图标；不出图标时印象中不能截图；出图标之后截图响应速度是正常的。

如果是开机自动启动的 snipaste，那么开机很久后第一次截图时都会卡几秒钟，但没10秒这么多。
