### ISSUE TITLE
关闭贴图和销毁贴图什么区别，关闭的还能再打开吗？

### ISSUE THREAD

**Issue by 1339510704** [Snipaste/feedback#654]
关闭贴图和销毁贴图什么区别，关闭的还能再打开吗？

**Comment by GregAMO** [comment]
@1339510704 能再打开
见用户手册-基础操作
https://docs.snipaste.com/zh-cn/getting-started

**Comment by 1339510704** [comment]
嗯嗯，首先谢谢您的回复，那请问，“关闭”以后可以再贴出来的图片数量 在哪儿设置啊，没找到呢，

**Comment by liulex** [comment]
@1339510704 
![default](https://user-images.githubusercontent.com/2010459/33615982-7f615d38-da16-11e7-9ecc-298cf6202ca0.png)

**Comment by 1339510704** [comment]
@liulex @GregAMO   嗯嗯，了解了，谢谢你们的回答，万分感谢~~
