### ISSUE TITLE
Chrome浏览器中界面元素检测不准确

### ISSUE THREAD

**Issue by mengzilym** [Snipaste/feedback#655]
发现了 bug
1. 平台：
![image](https://user-images.githubusercontent.com/8400019/33535520-00a320d6-d8e9-11e7-9d0e-185ce2f811fe.png)
2. BUG情况：使用chrome浏览器，利用Snipaste截图时，自动检测界面元素区域的功能出现问题，识别不准确，如下图所示：（其他程序都在最小化的状态）
![image](https://user-images.githubusercontent.com/8400019/33535631-ab5baa70-d8e9-11e7-8dab-e154623585ab.png)

chrome浏览器版本：62.0.3202.94（正式版本） （32 位）

测试其他软件并无上述问题。

**Comment by codehz** [comment]
@mengzilym 应该是dpi缩放的问题，你可以试试切换缩放回100%试试。。。话说这个问题似乎已经好久没见完美解决了

**Comment by liulex** [comment]
https://docs.snipaste.com/zh-cn/troubleshooting
