### ISSUE TITLE
经常进入假死状态！

### ISSUE THREAD

**Issue by totodata** [Snipaste/feedback#656]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

经常进入假死状态，主程序也调不出来，按快捷键截图也没用，有时候，按下快捷键，要等几分钟才反应。
32位／64位都测试过。都是这个情况。
我的环境：win10 64位 

再这么下去，真的要抛弃了。太难受了。

**Comment by liulex** [comment]
试试微软商店版？
