### ISSUE TITLE
加个OCR文字识别功能吧

### ISSUE THREAD

**Issue by aogg** [Snipaste/feedback#657]
最近V2各种OCR文字识别
https://www.v2ex.com/t/412363
https://www.v2ex.com/t/411218
https://www.v2ex.com/t/405827

**Comment by septs** [comment]
see #188

**Comment by jerry011235** [comment]
https://www.v2ex.com/t/412546
这次是 JS 版的 OCR 识别文字
https://gongpeione.github.io/quick-js-ocr/example/
