### ISSUE TITLE
是否可以添加 反色 的功能呢

### ISSUE THREAD

**Issue by Tintin-404** [Snipaste/feedback#660]
遇到电路设计的截图常常需要
ps：感谢您做出这么好的软件

**Comment by lumanegi233** [comment]
附议，还是很有用的（

**Comment by dlsdgj** [comment]
可以暂时用 WinSnap, 它有反色功能, 配合WGesture的 [按键序列]功能 应该能满足需求

**Comment by balalaXD** [comment]
+10086

**Comment by balalaXD** [comment]
比如截完一个图之后，比如命令行， 然后区域选中某一块然后反色

**Comment by Delete56** [comment]
+1  CAD截图经常需要用到反色

**Comment by liulex** [comment]
下个版本（v2.3.2）专业版会增加反色功能。
