### ISSUE TITLE
win10打开浏览目录崩溃

### ISSUE THREAD

**Issue by chenweinao** [Snipaste/feedback#661]
只要进入选择目录的页面，就会崩溃

**Comment by liulex** [comment]
商店版？版本号？

**Comment by chenzhuo1997** [comment]
1.15.3

**Comment by StarryVoid** [comment]
请补充以下信息，方便作者排查故障
1、您所使用的windows10版本号，例如1703-15063.786
2、您所使用的Snipaste安装源，例如官网下载
3、是否尝试使用管理员打开Snipaste并执行您所报故障的操作？

额外，请尽量更新到最新版本后查看故障是否存在。
