### ISSUE TITLE
新功能： 高亮选择区域

### ISSUE THREAD

**Issue by rickdgit** [Snipaste/feedback#662]
请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

截图后，能否像Snagit那样有一个功能，区域选择一块区域（就像画一个长方形那样）然后这个区域内填充半透明颜色，这样就把这个区域高亮了。这样就不需要再画一个空心长方形然后再画个箭头指出想选择的区域了。这个功能就可以简单明了的突出重点，特别是在excel或者code中，一下子用半透明红色长方形覆盖在我想高亮的几个数据/代码上，让人一眼就知道我想让他们看哪里

**Comment by Genteure** [comment]
调整颜色里可以修改透明度
![image](https://user-images.githubusercontent.com/11240579/33802457-b386e872-ddb2-11e7-8d0e-77fd3c6e6510.png)
![image](https://user-images.githubusercontent.com/11240579/33802465-dde635d2-ddb2-11e7-987a-d9fba9f1963a.png)

**Comment by OscarGong** [comment]
或者用高亮笔也可以。

不过 Snipaste 缺少 Spotlight 工具。效果像这样: ![](https://cl.ly/oFQF/download/Capto_Capture%202017-12-10_15-34-02_.png)

**Comment by Genteure** [comment]
@OscarGong 
![image](https://user-images.githubusercontent.com/11240579/33803113-d73df28c-ddc2-11e7-8ba3-6b38941b4091.png)
![image](https://user-images.githubusercontent.com/11240579/33803121-f0840ce0-ddc2-11e7-88c1-cb70072498a3.png)

### Workaround:

1. 选择马赛克矩形模式
2. 填充整个截图区域
3. 使用矩形橡皮擦工具
4. 擦除需要高亮的地方

**Comment by rickdgit** [comment]
谢谢！
