### ISSUE TITLE
【请求新功能】更丰富的快捷键支持

### ISSUE THREAD

**Issue by oscargong** [Snipaste/feedback#664]
请求新功能：

希望在截屏状态时，为每一个工具分配一个快捷键，可以通过特定的按键切换到特定的工具。
如 Sketch 里，`T` 是文本工具，`P` 是画笔工具。

**Comment by fluxonxxx** [comment]
复议，强烈希望增加图片标注快捷键

**Comment by StarryVoid** [comment]
参见https://github.com/Snipaste/feedback/issues/282
可以去参与点赞支持

**Comment by OscarGong** [comment]
@StarryVoid 然而 #282 中目前还没有相关 proposal。

**Comment by kuangshengyu** [comment]
强烈建议增加快捷键功能，支持配置，默认配置建议参考Photoshop

**Comment by liulex** [comment]
按键不太好分配，会在以后提供自定义。

**Comment by liulex** [comment]
不用纯字母键/数字键了，用 Ctrl+数字键 切到特定标注，暂不支持配置（v2.2）。
