### ISSUE TITLE
[优化需求]Mac版增加类似原生截图的阴影背景

### ISSUE THREAD

**Issue by copriwolf** [Snipaste/feedback#665]
希望增加类似原生截图的阴影背景。如下图所示。
![2017-12-11 9 47 02](https://user-images.githubusercontent.com/10501324/33812436-5635dac4-de58-11e7-991c-da044312adda.png)

我看到需求贴有一个增加外框的，那个只是说在外有一个1px(或者n px)的颜色款，我的需求是希望类似Mac原生的边框。

谢谢。

**Comment by zlren** [comment]
我也希望能有这个功能

**Comment by liulex** [comment]
重复啦 #197
