### ISSUE TITLE
任务栏与工作区域的问题

### ISSUE THREAD

**Issue by poerin** [Snipaste/feedback#666]
当任务栏不在下方时，首次截图会导致以下问题。
![bug 1](https://user-images.githubusercontent.com/12772646/33812542-2be65fc2-de59-11e7-98f7-cbda469fc6e8.png)
取消截图后，再次截图则正常。若用其他工具将任务栏隐藏，再显示，再截图，问题将再次出现。

把任务栏再调至右侧，将出现以下问题。
![bug 2](https://user-images.githubusercontent.com/12772646/33812611-941f4f68-de59-11e7-898d-5d5218ef00aa.png)

在发生以上情况下截图，截出的图片也将发生偏移。

**Comment by StarryVoid** [comment]
您好，我似乎没太理解，您说的问题是什么样子？
是指当首次启动截图时，Snipaste获取的截屏底层图片与真实桌面有不同？
顺便，可以提供系统，软件来源，软件版本的相关信息么

**Comment by liulex** [comment]
我使用 Win 10 自带的任务栏位置调整功能仔细测试了下，没发现什么问题。

**Comment by poerin** [comment]
我找到这个问题的原因了，不能算是 Snipaste 的问题。其实就是有另一个软件能够使用快捷键来隐藏任务栏，然后在任务栏显示的状态下，若有窗体首次显示出来并且它的位置和 `SystemParametersInfo(47, 0, ref rect, 1)` 的位置一样，就会被认为是在隐藏任务栏的时候被最小化的（或者上次关闭它时任务栏被隐藏了），所以需要把它调整到 `SystemParametersInfo(48, 0, ref rect, 1)` 的位置，否则这个刚刚显示出来的窗体就会遮挡任务栏了。由于 Snipaste 第一次显示出来的时候的位置刚好和 `SystemParametersInfo(47, 0, ref rect, 1)` 一样，所以就被调整到了没有遮挡任务栏的位置。不过我试了下系统的截图工具，并没有这个问题。

**Comment by liulex** [comment]
@poerin 谢谢，明白了。也正如你所说，第三方软件的强行干预不该由 Snipaste 来规避哦。
