### ISSUE TITLE
【mac公测版的问题】将截图置顶后会出现无法关闭的窗口

### ISSUE THREAD

**Issue by JayShna** [Snipaste/feedback#667]
步骤
1. F1截图
2. 按截图置顶按钮
3. 出现两个窗口，一个是「Do not localize」没有关闭按钮，点其他按钮也无反应；另一个是「存储为」的窗口，点击存储之后图片并不会储存下来
4. 之后关闭应用才可以关掉窗口

![Uploading 屏幕快照 2017-12-11 11.47.34.png…]()

**Comment by JayShna** [comment]
机器是MacBook Pro，10.13.2

**Comment by mTerminal** [comment]
我也是这个框，请问你在首选项里输出一栏里进行目录更改了吗？
我发现使用默认目录没有问题，如果更改就会出现这个框。

**Comment by JayShna** [comment]
我用的也是默认的目录。还是出现这样的问题，目前已经没有使用了。等更新吧

**Comment by liulex** [comment]
似乎都是 10.13 …… 我这还没升级，等升级后试试。

**Comment by liulex** [comment]
1.16-Beta2 已修复。
