### ISSUE TITLE
macOS 无法拖动截图

### ISSUE THREAD

**Issue by CarlosEvo** [Snipaste/feedback#670]
感谢 dalao 出 Snipaste macOS 版 

1. 打开 Snipaste 后按 F1 截图

2. magnifier 会在每次鼠标点击时更换位置，但是无法拖动截图，只能截全屏

我装了[chunkwm](https://github.com/koekeishiya/chunkwm)，但是不在运行的时候一样截不了图。
OS: macOS 10.13.2

![demo](https://user-images.githubusercontent.com/11689106/33845176-6fcc08f6-de57-11e7-8abd-f0b572842757.gif)

**Comment by liulex** [comment]
是有一些人遇到这个问题呢，正在努力升 10.13 中。。

**Comment by YouZhengChuan** [comment]
我的MacOS按F1，是调整亮度，怎么整？

**Comment by YouZhengChuan** [comment]
还有文字转截图这个，我在MacOS上，也没使出来～

**Comment by CarlosEvo** [comment]
@YouZhengChuan 用 `Fn` + `F1`，或者在 keyboard 设置里面把 `F*` 调成标准键，当然 `osascript` 也可以调。。。

**Comment by CarlosEvo** [comment]
目测不能截图的这个bug 在menubar 隐藏的时候没有了： #693 
我亲自试过，的确是这样

**Comment by liulex** [comment]
已经修复，近日更新~ #687
