### ISSUE TITLE
[请求新功能] 从剪切板读取刚刚拷贝的图片然后编辑并复制

### ISSUE THREAD

**Issue by zhangchioulin** [Snipaste/feedback#671]
1. 我觉得可以新增一个从剪切板读取刚刚拷贝的图片文件，然后打开编辑界面加以编辑，编辑完成后再复制到剪切板。
> Annotate(macOS) 有一个类似的功能可以看下，我认为很实用。

场景：
1. 朋友在聊天软件中给我发了个图，我想编辑下再发给他。
2. 看网页的时候拷贝了图片，想编辑下发给朋友

**Comment by oott123** [comment]
@zhangchioulin 复制-贴图-右键-标注
