### ISSUE TITLE
如何进行命令行调用呢？

### ISSUE THREAD

**Issue by Madao-3** [Snipaste/feedback#672]
* windows 下有相关功能，尝试直接调用unix 可执行文件失败。

**Comment by liulex** [comment]
![default](https://user-images.githubusercontent.com/2010459/34003085-5667c28a-e12f-11e7-8bc1-3164949ad3d9.png)

**Comment by StarryVoid** [comment]
该功能在MAC平台尚未支持，请阅读官方说明文件。
Close
