### ISSUE TITLE
打开snipaste的界面后上次的截图无法销毁

### ISSUE THREAD

**Issue by franktianyirenjian** [Snipaste/feedback#673]
如题，我第一次使用，截了图。
但是第二次打开的时候，
上次截图无论如何也无法关闭或者销毁。
![1](https://user-images.githubusercontent.com/13623595/33924145-aac7533e-e00f-11e7-9682-49772aedd7ea.png)
如图。
点击右键直接是原来桌面的右键，但是这个图片自从我第二次打开app就一直在桌面存在，
怎么也关闭不掉了。
忘了说了，我用的是mac os 公测版。

最新进展，当我新建了一个分组之后，选中新建的分组，这个消失不了的截图，竟然消失了，
然后我删除了新建的分组，之后，这个截图就再也没出现了。
再次，重新启动，也没有出现。

不知道这是什么bug，没有新建分组之前，重新启动电脑也消除不了这个第一次的截图。
这个截图，点击右键没有反应，也无法拖动，只要启动app，它就会出来，不知道什么原因。

**Comment by liulex** [comment]
……建议看看文档先，要么是开启了鼠标穿透模式，要么是进入了贴图的编辑模式并（空格）隐藏了工具栏。

**Comment by qiyanrui321** [comment]
我也出现了这个问题，刚刚按照你的方法解决了

**Comment by sonderwoo** [comment]
是的，出现 2 次了，只好重装软件

**Comment by xiaolou023** [comment]
> ……建议看看文档先，要么是开启了鼠标穿透模式，要么是进入了贴图的编辑模式并（空格）隐藏了工具栏。

thanks a lot
