### ISSUE TITLE
能否销毁全部分组的贴图。

### ISSUE THREAD

**Issue by wgf4242** [Snipaste/feedback#675]
比如我使用一次后会新建5个分组，每个分组都是10多条贴图。
但是每次清空都很麻烦要一组一组清空。（右键每一个分组依次关闭，）

建议添加一个快捷键清空当前分组，
添加一个菜单清空全部分组。

**Comment by StarryVoid** [comment]
不是办法的办法，去Snipaste的history目录中找到你所创建的贴图组，直接删除掉，然后重启Snipaste即可

**Comment by liulex** [comment]
将来会有专门的贴图组管理功能。
