### ISSUE TITLE
请求新功能：画图/标注时调用数位板或Surface笔的橡皮及压感

### ISSUE THREAD

**Issue by Dekirumonka** [Snipaste/feedback#678]
笔尾橡皮或笔侧橡皮，如图
![default](https://user-images.githubusercontent.com/17879091/33979193-3ca8ca2a-e0de-11e7-8236-dfe27ef2a340.png)
该功能在其他软件上的行为是：按下橡皮擦按键时将当前笔刷临时改为橡皮擦，放开橡皮擦按键时恢复原本笔刷。

**Comment by StarryVoid** [comment]
补完一下您的需求，不知道您想说的是哪种
1、wacom内的笔按键中的功能，如"右键单击"，"橡皮擦"，可以在Snipaste使用等价功能
本人觉得这个功能你可以在wacom中模拟快捷键达到效果
2、wacom内的笔按键中的功能，直接调用到Snipaste中对应的功能并作用
本人觉得让Snipaste强行支持这个功能，作者时间有限，并且数控板不仅仅只有Wacom牌子。

**Comment by Swanfal** [comment]
@StarryVoid 我想说的是在标注时按下橡皮擦按钮时像OneNote、PS、Drawboard PDF等软件一样将当前的笔刷改为橡皮擦，放开时变回原本笔刷的功能。
如果Wacom中模拟快捷键可以达到相同或类似效果，能否给出具体的实现方式？因为据我所知Snipaste中没有关于更换笔刷的快捷键。
最后，我仅仅是使用Issue功能提出我认为可以加入、并可以让软件在目前的框架内体验更好的功能建议而已，因为在其他类似支持绘图的软件中都有相应的支持（包括Wacom板和Surface笔）。至于判断能否实现、是否进行实现我认为是作者和其他Contributer的事。

**Comment by liulex** [comment]
@Swanfal 感谢你的详细说明，我理解你的意思，该请求也曾在 #627 提过。
我也很愿意添加此类支持，只是……我没有相关设备 😂

**Comment by StarryVoid** [comment]
唔。我理解错误。
我使用触摸板的模拟按键+按键精灵+按键精灵全屏扫描指定像素并模拟鼠标移动和点击达到效果。
触摸板半年没用，按键精灵卸载掉了。。尴尬。。

**Comment by septs** [comment]
Replaced by #1261
