### ISSUE TITLE
Mac版 F3生成剪贴板中文字图片版出现无法关闭的 Do not localize 窗口

### ISSUE THREAD

**Issue by Meowzz95** [Snipaste/feedback#679]
重现：
复制一段文字
按F3
这个时候就会弹出一个 Do not localize 的窗口 左边两个按钮没有文字 最右边的OK按钮点了也没反应 只有Force quit 可以解决

![image](https://user-images.githubusercontent.com/22430379/33980722-0ada52a0-e0e5-11e7-9836-9a786a3698de.png)

**Comment by liulex** [comment]
1.16-Beta2 已修复。
