### ISSUE TITLE
“穿透”的快捷键，无法正常使用来打字

### ISSUE THREAD

**Issue by swun90** [Snipaste/feedback#681]
指定“穿透”的快捷键，假设为`X`，那么在其他地方要输入 x 或这一字符时，x 是不可用的。就是怎么敲键盘，都不会出现 x 。
删除这一快捷键就恢复正常。推出 snipaste 也恢复正常。

**Comment by StarryVoid** [comment]
建议您了解一下"快捷键"
Snipaste的快捷键是系统级快捷键，全局有效，不论当前焦点在哪里、运行什么程序，按下时都能起作用；
相似的例子如：老款笔记本键盘的数字键等同于 789uiojkl = 789456123 当你开启小键盘时无法输入对应英文字符
所以，当你输入X这个字符的时候，系统判定您想执行的是穿透，所以不会输入文字X
所以建议您以下方法
1、如果输入文字，请不要仅使用字母，数字，符号作为全局快捷键
2、可以尝试携带Ctrl Alt Shift等功能按键+X的方式激活快捷键
3、期待作者制作应用程序级快捷键，不过这个肯定不会作为主力方向。
