### ISSUE TITLE
Mac下截图不支持中文输入

### ISSUE THREAD

**Issue by wangdon0475cn** [Snipaste/feedback#686]
mac下截图不支持中文输入

**Comment by mTerminal** [comment]
#663

**Comment by snooprat** [comment]
@mTerminal 我试了重启系统，好像没有改善，还是无法切换到中午输入法

**Comment by hotbain** [comment]
我也遇到了.

**Comment by kunx-edu** [comment]
同样遇到了，并且输入文字的时候会把编辑的竖线光标闪烁保存下来

**Comment by sdtm1016** [comment]
最新版，第一次可以，但再用就不能输入中文了，退出重打开，还是第一次可以，后面都不行，搜狗五笔

**Comment by yh821** [comment]
macOS 10.14.4，自带输入法也是输入不了中文
