### ISSUE TITLE
请求新功能——“重复截图”

### ISSUE THREAD

**Issue by Alan-LiuHan** [Snipaste/feedback#688]
希望添加一个能够快捷截取上一次截图位置图像的功能。

比如我在网页上截取了一个视频画面，他在播放后我想原地重新截取一张，这时候只需按下快捷键就好，不必重新手动截图。

感觉再加上这个功能软件就完美了~

**Comment by Rictusempra** [comment]
@Alan-LiuHan 右键→帮助→内置快捷键

**Comment by StarryVoid** [comment]
参见https://docs.snipaste.com/zh-cn/key-bindings
按R可恢复上次截图位置
