### ISSUE TITLE
Ctrl+C to copy snipped area doesn't work when language is set on Hebrew

### ISSUE THREAD

**Issue by GbeTech** [Snipaste/feedback#689]
Hi,
I love keyboard shortcuts. One of the most-used shortcut is Ctrl+C after snipping, to send the picture itself to the clipboard.
Unfortunately the shortcut doesn't work when the language is set to Hebrew. My guess is that it works with any Latin based language, but since Hebrew doesn't have the C letter at all, it doesn't register. 
Basically it sends Ctrl+ב.

Maybe sending Virtual Keys instead of the letter themselves will do the trick? If I'm not mistaken, the relevant VK is 0x43.

Thanks for the awesome product,

Gilad

**Comment by liulex** [comment]
No problem. You will see it in v1.16.
