### ISSUE TITLE
windows下线框工具颜色不准问题.

### ISSUE THREAD

**Issue by summarychm** [Snipaste/feedback#690]
在截图时,想使用矩形来高亮标识出重点,
但snipaste无法正确应用为纯红.每次的红色都不纯.
手动设置为#ff0000也不行.应该是软件的小bug,希望可以修正.
版本 v1.15.3
![bug图片](http://wx2.sinaimg.cn/mw690/7a72286bly1fmn5m2ux6hj20mo0c5ta7.jpg)

**Comment by StarryVoid** [comment]
@summarychm alpha通道是255么？

**Comment by summarychm** [comment]
@StarryVoid  
我刚测了下是alpha通道的问题,alpha值不是255,
软件的预设就是这样么?如果是的话希望可以软件默认可以设为255.

**Comment by StarryVoid** [comment]
@summarychm 记号笔预设不是255，其他都是255
