### ISSUE TITLE
请求新功能：截图后输出固定分辨率图片功能与标记时快速添加数字功能

### ISSUE THREAD

**Issue by BigWanGa** [Snipaste/feedback#692]
我是一个游戏策划，我经常用snipaste截取游戏图片并贴在excel表格里制作成策划文案
但有两件事让我很苦恼：
1.每次为了说明在图片中圈出的地方我都不得不手动写上数字序号
2.将图片粘贴到excel里后我还得一次次手动调整图片大小让它能符合我在excel中的排版，但事实上一个文案中上百张截图我都需要它们有统一的分辨率

希望作者能为这两点推出新功能

**Comment by StarryVoid** [comment]
参见https://docs.snipaste.com/zh-cn/command-line-options
水印功能暂时没有，你可以在以后功能列表里支持以下水印。

**Comment by BigWanGa** [comment]
感谢回复
但可能是我没描述清楚，我需要的不是每次以固定分辨率截图的功能，而是截图后【以固定分辨率输出图片】的功能。
举个例子，我截图时图片可能是1920*1080的分辨率，也可能是1280*720的分辨率，但由于排版的原因，我希望它们被粘贴到文档中时统统都是960*540的分辨率。而现在我只能每次粘贴图片后再手动拖动缩放把它们变成目标分辨率，很繁琐。

**Comment by liulex** [comment]
。。。做不到，这是你的文档软件的工作。
