### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by ZeronoFreya** [Snipaste/feedback#693]
看到大家都需要添加各种各样的需求，证明这个软件的发展空间很大，但作者的精力有限，恐怕无法满足所有需求，即使满足了，大家的需求不是我的需求，软件会变得臃肿——即，“我”不需要这么多“无意义”的功能。
那么，可否设计插件系统？并开放接口。
比如 [Wox](https://github.com/Wox-launcher)
最好能用Python开发，他的便捷性是有目共睹的。

希望Snipaste能保持纯粹

以上是拙见。

**Comment by ysc3839** [comment]
@ZeronoFreya 给个 C 接口，其他语言手动包装也不麻烦

**Comment by ZeronoFreya** [comment]
@CarlosEvo 不太理解给的链接什么意思

**Comment by CarlosEvo** [comment]
@ZeronoFreya 不好意思，之前refer issue的时候写错#了

**Comment by liulex** [comment]
谢谢你的意见，我很认同。我也在尽量保持 Snipaste 的存粹，一年半以来 Snipaste 增加的功能绝大多数是需要用的人会用到，不需要的人也不会受到影响。

仔细想了一下，应该只有“光标捕捉”这个功能会给不需要的人带来性能损失，原因是为了支持 <kbd>`</kbd> 随时切换，即使你没有勾选光标捕捉，我也必须每次进入截图前将光标捕捉到、存着。部分人开始截图时会卡也和这个有关。

因此 1.16 会将这个选项也交出来，用户可以选择永久禁用光标捕捉。

插件系统我会争取在 2018 实现。
