### ISSUE TITLE
请求新功能，单独显示某一张贴图

### ISSUE THREAD

**Issue by ZeronoFreya** [Snipaste/feedback#697]
我知道能分组而且也分了，但组里有十多张图，即使缩成最小尺寸也会遮挡界面，其实我只是想看其中一张而已。
建议添加组内solo功能，按下快捷键，能快速切换当前贴图solo或全部
可以避免贴图遮挡屏幕而选择一个个最小化了

**Comment by liulex** [comment]
该功能已经实现，会在专业版开放。
![default](https://user-images.githubusercontent.com/2010459/34327258-51870776-e8fa-11e7-94ae-260643ada369.png)
贴图多的时候确实很有用~

**Comment by ZeronoFreya** [comment]
原来如此，期待
顺带，贴图旋转的功能怎么样呢？

**Comment by liulex** [comment]
@ZeronoFreya <kbd>1</kbd> <kbd>2</kbd> 旋转。
