### ISSUE TITLE
1.5.3 画笔 怎么不能设置粗细

### ISSUE THREAD

**Issue by hotbain** [Snipaste/feedback#698]
1.5.3 画笔 怎么不能设置粗细？
官网图片显示是可以设置粗细的。但是实际在使用的时候 却不能设置粗细
是删除了吗？

**Comment by oott123** [comment]
@hotbain 键盘 1 2 或者鼠标滚轮都不起作用吗？

**Comment by Genteure** [comment]
@hotbain 1.5.3 ?
1.15.3 ?

**Comment by hotbain** [comment]
问题解决了 . 看来是自己不知道. 哈哈 键盘1 2 就可以解决.
