### ISSUE TITLE
请取消开机自启时的通知 Do not show a notification on automatic startup

### ISSUE THREAD

**Issue by Henrycobaltech** [Snipaste/feedback#702]
* Don't show a tray notification like "Snipaste is already running" on starting when logged on.
* Or add  a configuration option for toggling whether to show a tray notification. 

Thanks.

---

* 请不要在开机自启的时候显示 "Snipaste is already running" 这样的消息，每次开机咚的一声感觉有点奇怪。
* 或者说增加一个设置选项来设定是否显示这个通知。

谢谢！

![image](https://user-images.githubusercontent.com/5498199/34397544-e8eed008-ebb1-11e7-8212-fec76f34fdca.png)

**Comment by oott123** [comment]
@Henrycobaltech 在使用 Windows 10 商店版时，请关闭开机自启的选项。这能解决该问题。
这是因为 Windows 会自动还原上次关机时未关闭的程序，而 Snipaste 又重复地开机自启，此时重复运行了两次，Snipaste 才给出了正在运行的通知。

**Comment by Henrycobaltech** [comment]
@oott123 明白了，谢谢！
