### ISSUE TITLE
请求新功能：在命令行模式下，希望“quite snipping”，“save to file”，“copy to clipboard” 三个动作返回不同值

### ISSUE THREAD

**Issue by 1inus** [Snipaste/feedback#703]
Snipaste 提供了命令行模式，使得其他程序可以很容易和Snipaste集成。

现在有如下场景：

第三方软件**A**（比如即时通讯工具）调用snipaste 截图，如果用户做了 “quite snipping”，“save to file”操作，则**A**软件不需要做任何操作，如果点击了“copy to clipboard” 按钮，**A** 软件需要从剪切板获取图发送出去或者做其他操作。

目前 `snipaste.exe --snip` 在结束时对这三个动作未加区分，都是返回0， 希望命令在退出时返回不同的值，代表用户执行了不同的动作。

谢谢

**Comment by liulex** [comment]
没办法通过程序退出的返回值进行区分哦，以命令行调用的时候，第二个进程在通知完第一个进程就已经退出了，无法知道命令的执行结果。
你只是需要更高级一点的命令行操作，即复制截图并自动发送到指定程序，我可能会在以后加入。

**Comment by 1inus** [comment]
@liulex 我想这可能有一个办法，提供给截图君参考一下：无论是第一个进程还是第二个进程，当某个动作动作完毕之后，给标准输出流输出一些讯息，第三方程序是可以接受到的。我现在使用的大多数第三方程序是这样做的。

我现在找了个权宜之计：开启截图前将剪切板清空，截图启动之后，定时（因为不知道截图程序什么时候工作完毕）检测剪切板是否有图片，如果检测到有图片在剪切板，认为用户点击了“copy to clipboard”，我的程序做相关处理，否则，我什么也不做（用户点击了“quite snipping” 或者 “save to file”）
