### ISSUE TITLE
Windows10 将贴图复制到UWP版Onenote时，Onenote卡死崩溃

### ISSUE THREAD

**Issue by drpmma** [Snipaste/feedback#706]
截图直接复制进入UWP版Onenote不会有此问题
贴图后，复制贴图进入则UWP版Onenote卡死崩溃

Windows10:1709
UWP Onenote: 17.8827.20551.0
Snipate: 微软商店版v1.15.3

**Comment by liulex** [comment]
勾选：
![Windows Bitmap](https://user-images.githubusercontent.com/2010459/34441626-f57d08a2-ecf7-11e7-83b0-1ded702c9685.png)
