### ISSUE TITLE
菜单文字残缺

### ISSUE THREAD

**Issue by 22013xwlxwl** [Snipaste/feedback#707]
在通知区域右键单击后弹出的菜单，文字是残缺的。
仔细看是文字的很多笔画变成灰色的了，看起了就像文字残缺。
![2017-12-29_11-09-33](https://user-images.githubusercontent.com/15857203/34428536-ced5b790-ec88-11e7-91d9-da80aef2a0f0.png)

Windows7 专业版
sinpaste 64位 1.15.3(2017.11.12) 官网下载

**Comment by liulex** [comment]
系统问题/第三方渲染软件问题，和 Snipaste 无关。
