### ISSUE TITLE
Windows下Firefox58无法识别页面元素

### ISSUE THREAD

**Issue by Swanfal** [Snipaste/feedback#708]
FireFox版本
![default](https://user-images.githubusercontent.com/17879091/34449985-78e510a8-ed3a-11e7-93f0-76fe2b6198b1.png)
Windows版本为1709
设备为Surface Pro4
表现为整个Firefox窗口识别为一个大元素，无法识别包括标签页和网页元素在内的所有元素，但可以识别菜单

**Comment by Rictusempra** [comment]
联想笔记本同样系统软件环境已复现

**Comment by Rictusempra** [comment]
@Swanfal 
![image](https://user-images.githubusercontent.com/16912240/34451261-f8f5915c-ed5b-11e7-9613-42c8e2340869.png)

请确保该项值为 0

**Comment by Rictusempra** [comment]
或者在 about:preferences#privacy 中取消勾选

![image](https://user-images.githubusercontent.com/16912240/34451280-5382957a-ed5c-11e7-8e52-542c976a6796.png)
