### ISSUE TITLE
愿意高价购买软件!!!希望能为截图后的常用编辑功能,添加快捷键

### ISSUE THREAD

**Issue by wzxdi1** [Snipaste/feedback#710]
你好,我是snipaste的重度用户,很喜欢这款软件,但一直有一些重复性操作困扰我.

建议和统计：
![default](https://user-images.githubusercontent.com/34977120/34459788-22a1ccc6-ee35-11e7-88b0-9ed5bf4a50fb.jpg)

常用操作和困扰：
①截图后,我们常用的操作有文本框、箭头、画笔,每次都要去右下角点击很麻烦
②上述操作之间我们常常会切换使用——这样每次都要去右下角点击就更麻烦了

我个人统计过：以上这些都是常用操作
平均每三次截图,都会用到一次,一旦用到,又会多次使用,如果你们添加快捷键功能——我愿意付费使用,支付50rmb

**Comment by stevenzhu25** [comment]
请问是50人民币一个月咩？😅

**Comment by liulex** [comment]
按键不太好分配，会在以后提供自定义，相关讨论：#106 #492 #664
