### ISSUE TITLE
[Linux] 截图工具与 Xorg / Wayland 之间的关系

### ISSUE THREAD

**Issue by hosiet** [Snipaste/feedback#711]
在 Linux 桌面上开发截图工具面临一个尴尬的局面，因为 Linux 桌面的图形栈这两年正在经历大变化，其显示管理器/协议正在从经典的 X11/Xorg 迁移到下一代的 Wayland。虽然新的 Wayland 尚未完全成熟，但迁移已经开始，如主流的 GNOME 桌面环境已经默认启用 GNOME on Wayland 的搭配。

在原有 Xorg 基础上开发截图工具是不难的，因为在原情况下 Xorg 允许任何用户程序读取整个桌面的显示内容，也已有许多成熟的截图程序；在 Wayland 下问题则变得复杂，一是为安全起见不允许程序任意地读取显示内容，二是尚未出现**跨桌面环境** / **跨 compositor** 的统一截图 API。

所以大概有这些工作要做：

* 基于传统 X11 协议实现截图功能（用户旧系统和传统桌面，使用 Xlib/Xcb 开发）
* 研究 Wayland 下面的正确截图方式

参考链接：

* Fedora 对 Wayland 下截图的情况说明 https://fedoraproject.org/wiki/How_to_debug_Wayland_problems#Screen_capture_is_not_available_with_usual_apps
* 一个未来可能可用的跨平台 API 介绍 https://www.phoronix.com/scan.php?page=news_item&px=GIMP-FreeDesktop-Screenshot-API

**Comment by gloomy-ghost** [comment]
Wayland API tracking: https://bugs.freedesktop.org/show_bug.cgi?id=98894

说实话我很好奇是 wayland 先填完坑还是 snipaste 先出 linux 版…如果前者的话都不用管 Xorg 了

另外很希望 linux 版可以开源，毕竟大部分 linux 用户多少有点软件自由的信念（雾

**Comment by acgtyrant** [comment]
@liulex 如果 Linux 版有任何更新动态就在这里发布吧，好让我第一时间收到消息。

**Comment by xy-ly** [comment]
+1 hope
给个参考，这几天刚上manjaro kde，装qq没找到合适的方法，偶然发现linuxqq又复活了：
    在2019年10月24日这个特殊的日子，Linux QQ全新回归，从心出发·趣无止境
官网：https://im.qq.com/linuxqq/
- 不知道能不能为作者提供帮助，毕竟很多第三方也都有截图功能。
小白，说错还请多批评，linuxqq的截图真差劲

**Comment by chen462488588** [comment]
+1 hoped

**Comment by Jamie-obj** [comment]
什么时候出linux版本呢

**Comment by user1121114685** [comment]
其实大佬们可以利用系统自带的截图，然后再处理图片即可。。何必在乎api

**Comment by wangkerong** [comment]
有计划出linux版吗

**Comment by phyzhenli** [comment]
+1

**Comment by wangzishi** [comment]
现代浏览器（Chrome/Edge/Firefox）都提供了 [Screen Capture API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture)，都是开源跨平台的解决方案，是否可以参考其实现？

**Comment by Pinghigh** [comment]
其实可以考虑下类似 flameshot on wayland 的方案？（指用 grim 截图之后处理）

**Comment by FengZhongShaoNian** [comment]
请问作者计划什么时候推出Linux版的Snipaste？我在windows上用惯了它，最近切换到Linux，没有它我很不习惯。我自己使用Wine在linux上运行它，倒是勉强可用，但是剪切板间歇性不可用。这个软件似乎是基于Qt开发的，作者若是能兼容一下Linux平台就太好了

**Comment by Tiakon** [comment]
期待Linux版本的 Snipaste ，作者加油ヾ(◍°∇°◍)ﾉﾞ

**Comment by liulex** [comment]
Linux 首版已发布，可从[官网](https://zh.snipaste.com)下载。
不过目前仅在 Ubuntu 20.04 系统上测试过，遇到问题请另发 issue 反馈，感谢大家的支持与耐心等待。

**Comment by khailifz** [comment]
5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux    ubuntu 2004 上面直接无法启动。。。很奇怪
