### ISSUE TITLE
【建议】关于复制到剪切板和保存为图片

### ISSUE THREAD

**Issue by mrujowfi** [Snipaste/feedback#712]
可否点击“复制到剪切板”后，在文件浏览器中，右键粘贴成图片文件？

这样不用在保存的时候重新找一遍路径，会爽快很多。

**Comment by Rictusempra** [comment]
目前而言 你可以尝试 listary

**Comment by mrujowfi** [comment]
感觉文件搜索没everything好用，其他功能有点杂乱，现在可以截图了？

**Comment by ZhLong-473811012** [comment]
我觉得可以在贴图窗口搞一个拖放对象。
按住Ctrl(或者是其他的功能键)，鼠标左键按下拖动贴图窗口的时候, 贴图窗口就以 低透明度+鼠标穿透 的形式显示, 此时鼠标相当于拖动着这张贴图的图片文件。松开鼠标左键后根据用户设置来复制还是移动图片文件, 然后贴图窗口要不要销毁还是重新显示出来。
这样我觉得就比较容易实现了。(虽然我不需要这功能…)

**Comment by liulex** [comment]
专业版已实现。
