### ISSUE TITLE
Enable ctrl+v at Windows Explorer

### ISSUE THREAD

**Issue by koppor** [Snipaste/feedback#769]
It should be possible to paste the current image into Windows explorer.

![grafik](https://user-images.githubusercontent.com/1366654/34499543-d789a6e0-f006-11e7-8a3a-e2033babe752.png)

My "muscle memory" is to press <kbd>Enter</kbd> to copy the image and then paste it into apps. When I want to paste the image into a hard drive, I need to change this workflow. It feels unnatural to treat the Windows Explorer app different from other apps.

This also would be a workaround for #416. Workaround:

1. Paste into Windows Explorer
2. Drop into application
3. Delete in Windows Explorer

**Comment by koppor** [comment]
I sent a donation (1N7984874S741763L) with the hope that it motivates to work on this issue. 😇

**Comment by liulex** [comment]
Thank you very much for your generous donation. Do you mean by pressing <kbd>Enter</kbd>, an image file is copied to the clipboard? Or, an image and an image file are both copied to clipboard?

**Comment by ysc3839** [comment]
@liulex I think he means the latter one.
And I think there's some problems. The file won't be deleted after pasting. Maybe there's some way to "cut" the image file?

**Comment by koppor** [comment]
I think, BOTH are copied to the clipboard. This enables that I can

- paste into GitHub, Skype, Microsoft Outlook, ... (as it is currently)
- paste into Windows Explorer (which is currently not possible)

**Comment by liulex** [comment]
@koppor Implemented! It really looks very convenient! I love it. This feature will be available in the next release (should be Pro then). You will get it for free of course. : )

@ysc3839 That file should not be 'cut', as the user may want to paste it to multiple places. Instead, it will be kept in a temporary place, e.g. 'history/tmp/', which will be cleared on app exit.

**Comment by koppor** [comment]
@liulex Good to hear. Thank you! Regarding the pro version, I did not find it on the homepage and the only issue seems to be https://github.com/Snipaste/feedback/issues/287. I am curious where to get it 😇

**Comment by liulex** [comment]
@koppor It will be released in a month or so.

**Comment by koppor** [comment]
I checked it today, it is not working

![image](https://user-images.githubusercontent.com/1366654/212261562-dbb1f7bd-14fa-4dab-b83f-5e4fd0a6b36f.png)

![image](https://user-images.githubusercontent.com/1366654/212261633-40935d11-f0e0-4757-ad9e-fe235ac49933.png)
