### ISSUE TITLE
编辑图片文字光标会残留下来和无法输入中文

### ISSUE THREAD

**Issue by kunx-edu** [Snipaste/feedback#771]
全平台版本：输入文字时，光标闪烁，点击复制或者完成，光标不丢失，也就是说截图上会显示编辑截图的输入光标竖线

mac版本：无法输入中文

**Comment by myoss** [comment]
macOS 10.13.2 无法输入中文，标注文字的时候

**Comment by liulex** [comment]
@kunx-edu @myoss 
Hi, 都已经修复了，近日会更新。
