### ISSUE TITLE
一个截图贴图软件的默认快捷键竟然与 Print Screen 键没有一点关联，不可理喻。

### ISSUE THREAD

**Issue by szzhiyang** [Snipaste/feedback#775]
相比之下，ShareX 的默认快捷键设定合理太多。

![image](https://user-images.githubusercontent.com/30952626/34648428-dd0d06cc-f3d3-11e7-9f61-daa610b6611c.png)

**Comment by liulex** [comment]
那请您千万不要用这不可理喻的软件。
