### ISSUE TITLE
windows版自动选区问题

### ISSUE THREAD

**Issue by Inku** [Snipaste/feedback#778]
windows可不可以提供在截图选区时使用快捷键来调整选区的大小？
不是指真正意义的大小而是父元素那种。
平常用的时候经常想给某个软件截个图，但是经常会自动选中软件中某个元素区域，想截整个软件的时候就要在屏幕上转啊转的来找看看能不能找到整个的自动选区，结果经常还找不到最后还是要手动进行截屏。
我的想法是可不可以在截屏时使用快捷键来调整鼠标位置选区的父节点或者子节点。
以上。

**Comment by liulex** [comment]
see  #344 [#282](https://github.com/Snipaste/feedback/issues/282#issuecomment-284685511)
