### ISSUE TITLE
希望有个功能是在贴图上右键能选择电脑软件打开或编辑

### ISSUE THREAD

**Issue by David318** [Snipaste/feedback#779]
在贴图上点击右键如果能过出现一个选项可以选择用电脑软件直接打开或者编辑的话挺方便，我不知道现在能不能实现，如果能实现的话希望有人能教我怎么操作

**Comment by StarryVoid** [comment]
现在暂时不能。想问一下为什么会有这个想法？
实现上可能要实时保存成png格式然后给其他软件比如ps打开。但是举例如果这个图片是一个4K分辨率的图片，那么就会很大。

**Comment by David318** [comment]
也没什么，就是有时候突然想编辑一下贴图，比如裁剪一下之类的，要保存后再编辑，就像能不能直接在贴图上右键的时候有个选项是用其他软件打开这样

**Comment by liulex** [comment]
以后会有的 #159
