### ISSUE TITLE
希望增加右键粘贴功能

### ISSUE THREAD

**Issue by zffffff** [Snipaste/feedback#78]
希望在截图或复制文字之后，在目标文件夹窗口点右键粘贴或ctrl+v，图片会自动粘贴为png文件，文本会自动粘贴为txt文件；

**Comment by liulex** [comment]
图片粘贴为文件会加入，文本粘贴为 txt 就不是 Snipaste 应该管的了……

**Comment by zffffff** [comment]
那也很好了，多谢作者；

这个软件真的挺好用的

**Comment by zffffff** [comment]
找到一个paste as file ，两个一结合，完美了，感觉不需要别的功能了 哈哈

**Comment by StarryVoid** [comment]
可以同时复制为文件&图片么？从来没见过这么弄得。
Windows下，我的印象里，只有文件或者数据流两种剪贴板状态吧。。
