### ISSUE TITLE
请求新功能：希望可以支持滚动窗口的长截图

### ISSUE THREAD

**Issue by lebinlv** [Snipaste/feedback#783]
在进行网页截图时，有时内容较长，无法一次性截取，因此希望具有长截图功能，这样就不用再安装其他截图软件了...
已有的功能很丰富，向作者表达感谢!

**Comment by Rictusempra** [comment]
@lebinlv 网页截图请使用

1. 浏览器扩展
2. F12 开发者工具
3. Firefox内置截图
