### ISSUE TITLE
希望能增加/更改单击托盘图标的功能

### ISSUE THREAD

**Issue by fxy147** [Snipaste/feedback#785]
目前单击托盘图标会启动截图，但实际使用中我都是用快捷键启动截图，白白浪费了一个小功能。能否为单击托盘图标增加其他功能，比如“启用/禁用快捷键“，点一下禁用快捷键，再点一下启用。可以当作”特定程序禁用快捷键/检测全屏禁用快捷键“等作者暂时不考虑的功能的替代方案。

**Comment by liulex** [comment]
已实现 : )
