### ISSUE TITLE
在macOS上 cpu占用很高

### ISSUE THREAD

**Issue by LomotHo** [Snipaste/feedback#787]
macOS 10.13.2
占用cpu高，一直在50%以上
下面是截图

<img width="626" alt="01" src="https://user-images.githubusercontent.com/16211479/34934067-0c57474e-fa14-11e7-9f1e-45b50387ffd0.png">
<img width="566" alt="02" src="https://user-images.githubusercontent.com/16211479/34934071-0e1cd2b0-fa14-11e7-85a9-402c7572b806.png">

**Comment by LomotHo** [comment]
这个是在htop里面看的q情况
<img width="1440" alt="snipaste_2018-01-15_16-56-50" src="https://user-images.githubusercontent.com/16211479/34934410-5b70fb76-fa15-11e7-94d3-be1c5465868a.png">

**Comment by liulex** [comment]
Hmmm...  你只是描述了一个现象，但没有提供足够的信息让我可以重现它啊，它总不是每次一启动就占用那么多吧。

**Comment by BoomCloud-HK** [comment]
我昨天出现占用高达108%的情况，右上角状态栏鼠标挪到图标上时鼠标变为旋转等待标识，具体如何复现我也不知道为什么会出现这种情况

**Comment by mikuazusa** [comment]
我也是，macos下后台一段时间后，CPU占用非常高达到200%+

**Comment by Liam0205** [comment]
@mikuazusa 未能复现……有复现路径吗？

**Comment by LomotHo** [comment]
没找到什么原因，基本不太能复现，一般是运行了很久之后突然出现的，重启软件就又好了

**Comment by forest0** [comment]
我也出现了, cpu200%.
maxos 10.14.1

运行很久后突然出现,重启后恢复正常.
