### ISSUE TITLE
截图/编辑贴图时 马赛克功能不正常？？

### ISSUE THREAD

**Issue by xtvjxk123456** [Snipaste/feedback#789]
截图时，无法马赛克??（测试了几次都无法在截图时马赛克）
编辑贴图时，编辑好的这张贴图和内存中对应的贴图数据不匹配？？（意思是编辑好马赛克，然后再次f3,贴图就会变成未马赛克的图片了，这里我查看了下，是直接弹出了另外一份贴图，原来的马赛克贴图也在，意思是我用法不对？？）

**Comment by xtvjxk123456** [comment]
最新版

**Comment by liulex** [comment]
1.16 的 bug，会尽快修复。
