### ISSUE TITLE
建议增加标号功能，类似圈1，圈2之类

### ISSUE THREAD

**Issue by jasonshaw** [Snipaste/feedback#790]
请求新功能

建议增加滚屏截图（已经存在了）
建议增加标号，目前截图大部分是要给别人示意，如果要示意地方多，就要说 那个位置，如果有标号就可以很好的说明
建议作者能早点加上，谢谢

Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by Genteure** [comment]
![image](https://user-images.githubusercontent.com/11240579/34981282-023b62d0-fae2-11e7-9d14-8c2cf563102d.png)

**Comment by jasonshaw** [comment]
我尝试了，点击T，然后怎么操作可以有标号呢？没有看到这个功能选项

**Comment by liulex** [comment]
重复了哦 #227
