### ISSUE TITLE
建议增加文字标注时字体可以设置大小

### ISSUE THREAD

**Issue by qinxiaoxian** [Snipaste/feedback#791]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by qinxiaoxian** [comment]
对于较小的截图来说，不能设置字体有些不太好，毕竟字体大小过大了，所以建议添加字体大小设置功能

**Comment by liulex** [comment]
画笔大小的图标上面有个小红点，点一下 : )
