### ISSUE TITLE
每次打开截图，希望可以重置上次用过的颜色。

### ISSUE THREAD

**Issue by YouzhiWang** [Snipaste/feedback#792]
比如我选择了红色的调色盘做标记。
然后第二次打开应该重置成黑色，而不是上一次的红色。

**Comment by liulex** [comment]
记住颜色本来就是个 feature，如果你不满意，请：
![default](https://user-images.githubusercontent.com/2010459/35105964-f3e4427a-fca7-11e7-8490-192d3588535f.png)
