### ISSUE TITLE
命令行贴图命令无效

### ISSUE THREAD

**Issue by wolfsilver** [Snipaste/feedback#794]
`paste files FILE1 FILE2`
1.16.1版本
命令行贴图命令无效

![image](https://user-images.githubusercontent.com/2452450/35027124-d8ee9c64-fb89-11e7-9ade-88b24946b0f5.png)

命令
```
"xxx\Snipaste\Snipaste.exe" paste files "xxx\1.png"
```

**Comment by liulex** [comment]
中文文档错了，应该是 `paste --files ...`，已更新。
没想到真有人用…… 😂
