### ISSUE TITLE
希望能够显示十六进制颜色

### ISSUE THREAD

**Issue by Witype** [Snipaste/feedback#795]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 当进入截图模式后目前只显示了RGB颜色值，没有相应的16进制颜色值，作为前端开发，16进制颜色值更方便，谢谢！

请求新功能？
* 进入截图模式后，当前像素的颜色值显示16进制模式
* 按x复制16进制颜色值

**Comment by Genteure** [comment]
@Witype 如果你打开 Snipaste 的 首选项
在第一页 常规 中就可以看到有个选项 取色器使用 Hex 颜色值 和 不要复制 #

**Comment by Witype** [comment]
3Q
