### ISSUE TITLE
Feature suggestion: Let the user take repeated fixed-size screenshots across the screen

### ISSUE THREAD

**Issue by raindropsfromsky** [Snipaste/feedback#797]
Snipaste already has the ability to detect windows elements. That's great. 
But sometimes we have to take multiple screenshots of fixed size.

For example, I want to copy the artwork in the following image:
![image](https://user-images.githubusercontent.com/9047168/35082989-aced5678-fc42-11e7-8a96-3868b741b34f.png)

These are NOT windows elements. So Snipaste is not able to auto-detect the icons.
So I would have to first set the size to capture the first icon, like this-
![image](https://user-images.githubusercontent.com/9047168/35083045-0a683a70-fc43-11e7-84e8-e60ce382edef.png)
From Snipaste's readout, I know that this is 20x20 size capture.

So now I want to repeat the capturing 22 times with the same 20x20 window size.

For that I need a new mode where-

1. Snipaste first lets me configure a "m x n" pixels window. </br> (in our example, I will set it to 20x20 pixels)
2. Now I use a dedicated hotkey, to trigger the **fixed-size capture** mode.
3. Snipaste attaches a square of the required size with the mouse pointer. </br> As I move the mouse, the square moves along with the mouse-pointer.
![image](https://user-images.githubusercontent.com/9047168/35083453-42fc08f6-fc45-11e7-812e-e9ebea8137b1.png)
4. All I have to do is to align the square on the next icon, and click the left mouse button. </br> This should place the captured content on clipboard.
5. I switch to the other app (e.g. a word or ppt file) and paste the clipboard content.
6. I switch back to Snipaste, and repeat step 4+5 for all other icons.

Here's another variation of the capturing mechanism:
![image](https://user-images.githubusercontent.com/9047168/35083573-d5f066f2-fc45-11e7-978c-1bf52e9ad30b.png)

In this, the cross-hair is at the center of the capture area.

**Comment by Genteure** [comment]
Workaround:

1. Manually select first area
2. Confirm capture (by hitting enter or anything you prefer)
3. Start new capture (by hitting hotkey or taskbar icon)
4. Press key `r`, Snipate will re-select the area you chose in step 1.
5. Move the area to next icon.
6. Repeat 2 - 5

R: Set the snipping area to the same as your last successful snip
https://docs.snipaste.com/key-bindings?id=snip-only

**Comment by Genteure** [comment]
Workaround 2:

you can execute Snipate from cmd/PowerShell with an argument like `/Path/To/Snipate.exe snip --size 20 20` while Snipate already running.

https://docs.snipaste.com/command-line-options?id=snip-options
```
snip --area X Y WIDTH HEIGHT     Start snipping with the snipping area's top-left corner
                                 set to (X, Y) and size set to WIDTH x HEIGHT
snip --size WIDTH HEIGHT         Start snipping with the snipping area's size being
                                 WIDTH x HEIGHT and its center being the cursor position
```

**Comment by raindropsfromsky** [comment]
Thanks for the workarounds. My setting is to trigger a new "capture and copy to clipboard" by pressing the **PrintScreen** button (instead of **F1** button).

So I started a new capture, and then drew a rectangle of desired size. 
When I release the LMB, the capture is completed, and the content goes to clipboard.

Now I again pressed **PrintScreen** button for the second capture.
Snipaste started auto-detecting different elements of the screen (I have set it that way, so that I can capture the buttons and toolbars easily). So I pressed the r key (not SHFT+R). 

But Snipaste quits its capture mode altogether. It does not select the same area as before.
What could be wrong?

**Comment by raindropsfromsky** [comment]
oops. Got that. 
I had selected the "capture and copy" command, not the "capture" command.

**Comment by liulex** [comment]
@raindropsfromsky I think the first workaround by @Genteure should be enough for the moment. I use it too when I need to take a fixed-size/region screenshot.
In the future, there will be a dialog that allows you to input the width and height of the screenshot.

**Comment by liulex** [comment]
BTW, you can show the crosshair by holding <kdb>Alt</kbd>.
