### ISSUE TITLE
升级到1.16.1微软商店版 无法保存截图

### ISSUE THREAD

**Issue by Dy64** [Snipaste/feedback#798]
昨天从微软商店升级版本后，无法保存截图。桌面和其他盘符都不可以
提示你没有权限修改该网络位置的文件。
-----------
卸载掉，重新到微软商店安装又可以了。

**Comment by Dy64** [comment]
![20180119064412](https://user-images.githubusercontent.com/35034348/35125761-ccde20a4-fce5-11e7-99ba-13bf837939a9.png)

**Comment by liulex** [comment]
自测了下没有问题，这种应该是微软出的幺蛾子……
