### ISSUE TITLE
【快捷键反馈】VMware的默认截图快捷键F1无效

### ISSUE THREAD

**Issue by ChanglongWANG** [Snipaste/feedback#799]
VMware的默认截图快捷键F1无效，会自动跳转到VMware的帮助链接。

VMware版本：14.1.1
Windows版本：Windows10 1709 
Snipaste：1.16.1

**Comment by liulex** [comment]
[故障排除](https://github.com/Snipaste/feedback/wiki/%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4#%E6%9C%89%E6%97%B6%E5%80%99%E5%BF%AB%E6%8D%B7%E9%94%AE%E4%B8%8D%E5%93%8D%E5%BA%94)

**Comment by code4lala** [comment]
管理员身份运行的snipaste可以在别的管理员窗口触发F1截图，但是VMware中仍然不可用，请问除了点一下别的地方还有更好的解决办法吗？

**Comment by waibiwaiba** [comment]
@code4lala @asnfohsdgfbkxcv 
按ctrl+F1即可在VMware界面截图。
我发现在VMware界面，把鼠标移动到其窗口最顶端(不要在虚拟机窗口里)，使用“截屏并自动复制“(默认全局快捷键ctrl+F1)就可以在VMware界面触发截图了。
在VMware界面直接使用“截屏”(默认全局快捷键F1)还是会在浏览器打开vmware的帮助页面。
只是这样会把截图直接复制到剪切板，要自己手动按F3把剪贴板的图片贴到屏幕上(在VMware窗口界面按F3还是不能贴图，切换到别的应用的窗口才能按F3贴图)，不过至少能在VMware界面截图了。(我猜测：貌似在VMware窗口所有的Fn按键都会 *首先* 被它捕获，所以即使snipaste以管理员身份运行，你按的Fn键还是无法被snipaste捕获，无法调用相关的功能。)
Snipaste：2.7.3-Beta
VMware Workstation 15.5 PRO

**Comment by waibiwaiba** [comment]
或者把截图快捷键从F1改成alt+F1
