### ISSUE TITLE
截图时颜色选项建议

### ISSUE THREAD

**Issue by cnsheds** [Snipaste/feedback#800]
现在选择显示HEX颜色或RGB颜色, 截图时只显示一种, 建议可以同时显示, 省去有时自己计算的麻烦
比如设置了取色用Hex颜色 就显示成 #FFFFFF(255,255,255)
设置成RGB就显示成255,255,255(#FFFFFF)

当然复制的时候还是只复制主颜色格式, 或者为二种颜色提供不同的复制快捷键, 就更方便

最后还是要感谢作者提供这么好的截图软件给大家免费用

**Comment by liulex** [comment]
以后会加一下~

**Comment by StarryVoid** [comment]
此功能已支持，建议关闭 issues
