### ISSUE TITLE
进程无响应

### ISSUE THREAD

**Issue by kawori** [Snipaste/feedback#802]
商店版本，有时候按下F1截图时（有一次时在浏览器内截图，还有一次不记得了），会一直处于截图状态，按任何键均无反应，也无法切换程序，之后会出现对话框提示“进程没有响应”，有“结束进程”和“取消“两个按钮，但是按任何按钮都无效，会不断出现这个对话框，只能按电源键强制关机。
我不想再重现这个问题，所以没有截图。

**Comment by 1014856361** [comment]
win10（1709）商店版只能刚安装的时候可以启动一次，其他时候均无法启动，点击无反应。

**Comment by liulex** [comment]
@kawori 
元素检测遇到极少部分窗口/元素时会卡死，需自己进行排查，然后配置 `config.ini`, 见 #116 的讨论。
遇到卡死时，按下右 <kbd>Win</kbd> 键，出现任务栏，再点击 Snipaste 的托盘图标，可强行结束 Snipaste，无需重启系统。
如果无法确定是哪个程序引起的，可以将日志级别设为 `跟踪`，然后重现崩溃，再打开splog.txt 即可查出最后一次元素检测是落到哪个 exe.
如果 **遇到了卡死** 且 **不想排查/不想配置** 且 **不想问题再出现**，只有在选项窗口中关闭元素检测了。

@1014856361 
问题已知，今晚会提交新版到商店，一两日后审核通过再更新试试。

**Comment by liulex** [comment]
@1014856361 请问是否在选项窗口中改过配置文件的存储位置？

**Comment by 1014856361** [comment]
@liulex 没动过。更新后就出现这个问题，重新安装了几次都是这个情况。

**Comment by liulex** [comment]
@1014856361 可否将 `%LOCALAPPDATA%\Packages\45479liulios.17062D84F7C46_p7pnf6hceqser\LocalState` 中**除了 history 之外** 的其他文件/文件夹打包发到 <snipaste.app@gmail.com>？

**Comment by TGdxh** [comment]
@liulex 我是不是发了两次？

**Comment by liulex** [comment]
@1014856361 收到，是发了两次 😅
