### ISSUE TITLE
能否添加针对特定程序停用全局截图热键的功能？

### ISSUE THREAD

**Issue by lonely701** [Snipaste/feedback#803]
建议：可以做一个程序列表在设置的 Hotkey 的 tab 下，加入此列表的程序截图热键的触发方式可以自选：启用/仅当没有热键冲突时启用/禁用。

这样说起来有些抽象，举个例子：potplayer的F1是查看potplayer相关信息，Ctrl+F1是查看正在播放的文件信息。这两个热键还是比较常用的，potplayer的默认热键设置也很合理，不便于调整。同时potplayer有自己的视频当前帧输出功能，不是特别需要snipaste。所以我希望能仅在potplayer中禁用snipaste的全局热键。

“仅当没有热键冲突时启用”意思是：比如在musicbee中，默认热键设置中F1和Ctrl+F1没有被占用，这时snipaste的热键可以使用；但是当用户在musicbee中设置了这两个热键时，优先完成musicbee的命令。

以上是这个功能的使用场景。简单说就是一个程序列表，这里面的程序可以选择热键触发方式：snipaste优先/程序优先/完全禁用。不在列表里的程序自动启用全局热键，除非热键被全局禁用。

另外，我现在用的是UWP版本1.16.1

**Comment by liulex** [comment]
看你的描述，其实你只需要特殊处理截图这一快捷键，那换个和所有应用的常用快捷键不冲突的全局快捷键不是最好的方案吗……

你提到的是快捷键的黑名单机制，#160 有提过，不过目前已经实现了暂停其他快捷键的快捷键，这样的话，好像黑名单机制也没太大必要了 🤔

**Comment by lonely701** [comment]
好的 谢谢你
