### ISSUE TITLE
【新功能增加】snipaste自动保存图片语法规则为什么没有顺序数字这个规则？

### ISSUE THREAD

**Issue by colemanlee** [Snipaste/feedback#804]
请求新功能：
1. 想要什么：snipaste自动保存图片的语法规增加顺序数字这个规则
2. 具体是怎样的：snipaste自动保存的图片为PIC-001，PIC-002这样的顺序规则，不仅文件名短，也不会在将图片上传到网络时因为图片的文件名是时间而泄露一些隐私信息。
3. 为什么需要它：Winsnap截图软件有这个规则，而且我也需要这个规则，不喜欢用一长串时间来顺序保存图片，希望有一个按顺序的数字即可。

**Comment by liulex** [comment]
只是自动保存的话，你将后面那一串变量去掉就好了，比如 ‘PIC'，Snipaste 自动保存时检测到重名会自动在后面加数字。

不加数字规则的原因是，文件命名是同时应用的快速保存、自动保存和手动保存的，这个数字怎么算，就不好确定了。

**Comment by colemanlee** [comment]
> 比如 ‘PIC_'，Snipaste 自动保存时检测到重名会自动在后面加数字。
目前顺序是：PIC_.jpg   PIC_0.jpg   PIC_1.jpg   PIC_2.jpg。。。
