### ISSUE TITLE
【新功能增加】输出图片时可以增加边框

### ISSUE THREAD

**Issue by colemanlee** [Snipaste/feedback#805]
请求新功能：

1. 想要什么：输出图片时可以增加边框
2. 具体是怎样的：输出图片时可以增加边框，边框颜色可以自己指定，边框宽度的像素数也可以自己指定。
3. 为什么需要它：有时上传到网络的多个截图没有边框不便于肉眼区分边界，有边框更便于识别。

**Comment by liulex** [comment]
#197
