### ISSUE TITLE
新功能 - 滚动截屏

### ISSUE THREAD

**Issue by tomchenshanghai** [Snipaste/feedback#806]
能否实现滚动截屏？ 这个功能对于看到一篇很好的文章，但是无法保存，只能翻一屏截一屏的情况很有用。感谢您无私的奉献给大家这么好的截屏软件。

**Comment by Rictusempra** [comment]
@tomchenshanghai dup of #19

**Comment by halhaling** [comment]
同样希望增加滚动截屏功能，可以参考FSCapture的滚动截屏，非常好用，希望更新，感谢！

**Comment by StarryVoid** [comment]
参见 #282 #19  作者已回复过此类issus
