### ISSUE TITLE
截图时添加一个带圈数字工具。我用箭头标注好三个位置，此时我想用数字标注他们的先后性。

### ISSUE THREAD

**Issue by laobingm** [Snipaste/feedback#807]
我用箭头标注好三个位置，此时我想用数字标注他们的先后性。，美中不足的一点是，截图时，缺少一个可以点击鼠标自动生成数字标号的工具。比如，点击第一次，出来一个画圈圈的1，点第二次，出来一个2

**Comment by liulex** [comment]
重复了哦 #227
