### ISSUE TITLE
是否有考虑多个快捷键？

### ISSUE THREAD

**Issue by rzyq** [Snipaste/feedback#808]
常用快捷键（alt+`）的话，会有键位响应。比如想要截图正在输入的文字，点了常用的键，就没办法截图。这时候需要切换快捷键到功能键上（F1~F12）之类的。所以，就想问下。有吗？

**Comment by liulex** [comment]
没听明白……

**Comment by rzyq** [comment]
emm，简单来说，就是两个截图快捷键=-= 不好意思，扯多了。

**Comment by liulex** [comment]
专业版会有的，专业版的快捷键功能会非常强大~
