### ISSUE TITLE
贴图跑到了windows状态栏的后面去了

### ISSUE THREAD

**Issue by cnsnet** [Snipaste/feedback#810]
我的操作系统是windows 10 enterprise N 2016 LTSB
我截取了一张贴图临时使用,  然后由于在屏幕上占地方, 我就临时拖到了底下去, 然后点击切换到了另外的程序, 于是贴图就跑到了windows的状态栏后面去了, 再也点不出来了.
我查询了一下帮助,  使用shift+F3可以隐藏所有贴图再显示出来,  我想问能不能切换程序的时候不要跑到后面去.
![screenshot_20180125_161926](https://user-images.githubusercontent.com/1931457/35378287-350449cc-01ed-11e8-9e5e-9532278b8fc6.jpg)
![screenshot_20180125_161926](https://user-images.githubusercontent.com/1931457/35378351-6ef67b00-01ed-11e8-9075-79fd5397ac46.jpg)

**Comment by liulex** [comment]
这个没有办法的，点击任务栏空白处或者查看了窗口缩略图，任务栏会显示在贴图之上。

**Comment by cnsnet** [comment]
好的, 谢谢, 那以后再碰到这样的情况我就隐藏再显示来解决吧.
