### ISSUE TITLE
感觉抓图后的粘图被稍微放大了，并不是原始大小

### ISSUE THREAD

**Issue by im0khu** [Snipaste/feedback#811]
每次抓完图片，直接贴在比如Word, Outlook这些里面的时候，感觉图片变得放大了一些，模糊了一些。

在抓代码，及文字的时候非常容易能感觉出来。因为很明显看得出来字变得模糊了。

常常需要手工将图片缩小一些。

但这在之前的比如QQ抓图之类的没有这种情况。

是有意放大的？还是其它原因？
找了一下配置，没有发现可以配置之方面的地方。
望指教。

**Comment by liulex** [comment]
非常感谢你的反馈，确实是有 bug，没有设置 Bitmap 格式图片的 DPI，我会在下个版本修复。
目前你也可以先**禁用** `以 Windows Bitmap 格式复制图片`：
![default](https://user-images.githubusercontent.com/2010459/35483243-c687a24c-047a-11e8-8377-ff362d8fe775.png)
