### ISSUE TITLE
不能正常截屏了，按下截屏键就快速截屏，大概两秒左右就自动截屏了，32位和64位都是！

### ISSUE THREAD

**Issue by qq1143808278** [Snipaste/feedback#812]
这阵子突然就不好使了，我平时根本不动设置什么的，但是有一天突然就不能正常截屏了，按下F1，如果手动选框的话就两秒之内选上多少截多少，不手动选框的话就自动识别窗口截屏，而且有些时候是能正常使用的。
在网上看了一下，说是如果64位有问题建议用32位，但是删除64位下载32位之后，一开始还好，过了一会儿也是突然就不好用了。真心希望能帮我解决解决！用习惯了Snipaste，实在不想再换软件了！

**Comment by GregAMO** [comment]
@qq1143808278 这样子像是被其他东西按了Enter回车键。要么是其他软件要么是键盘卡住了？

**Comment by liulex** [comment]
Snipaste 并没有这样的设定…………看起来像是什么软件在帮你定时自动按 <kdb>Ctrl</kbd> + <kbd>C</kbd> 或者 <kbd>Enter</kbd>……

实在觉得是我最近更新的锅的话，可以试试旧版：https://bitbucket.org/liule/snipaste/downloads/

**Comment by qq1143808278** [comment]
@liulex 可能真的是软件bug，我现在用15.2三天了，软件不再出现这样的问题了。

**Comment by liulex** [comment]
@qq1143808278 但我无法重现，也没有其他用户报告类似问题。
