### ISSUE TITLE
【请求新功能】图片保存到网盘

### ISSUE THREAD

**Issue by Csrayz** [Snipaste/feedback#813]
截图后图片能否直接保存到网盘  百度网盘/onenote/gdrive/evernote之类的
现在似乎只能保存到本地后再上传
个人觉得还是蛮常用的

**Comment by Rictusempra** [comment]
@Csrayz 百度盘/OneNote/evernote现在是不可能的
因为没有公共API
鉴于百度盘的尿性 以后应该也没有
除GD之外就基本是 OneDrive Dropbox

**Comment by congcong0806** [comment]
Evernote：https://dev.evernote.com/
印象笔记：https://dev.yinxiang.com/

**Comment by GregAMO** [comment]
@Csrayz 着急的话目前来说可以利用ShareX

**Comment by StarryVoid** [comment]
参见 #282  #60 作者已回复过此类issus
