### ISSUE TITLE
谢谢 MAC上截图后贴图操作太麻烦,  谢谢

### ISSUE THREAD

**Issue by zhangenming** [Snipaste/feedback#815]
MAC上截图后贴图操作太麻烦
需要先F1截图
再CMD T贴图
可不可以像window那样截图鼠标松开后直接贴图到屏幕
谢谢

这个软件是我必用的软件
现在刚换mac系统 不太适应
谢谢
而且mac鼠标没有中键呀
谢谢

**Comment by uivtyer** [comment]
同意 我也这么觉得
可以添加一个截图后直接形成贴图的选项 鼠标中键或快捷键确实有些不顺畅 
很棒的软件 加油！

**Comment by liulex** [comment]
两个系统的操作是一样的。
