### ISSUE TITLE
部分游戏屏蔽了快捷键

### ISSUE THREAD

**Issue by QvQwww** [Snipaste/feedback#816]
部分游戏屏蔽了快捷键，游戏窗口按快捷键无效，可以加强下快捷键嘛

**Comment by ysc3839** [comment]
@QvQwww 什么游戏？游戏是否管理员身份运行？

**Comment by QvQwww** [comment]
@ysc3839 是管理员身份运行的，艾尔之光

**Comment by Genteure** [comment]
@QvQwww snipaste 是否管理员权限运行？

**Comment by QvQwww** [comment]
@ysc3839  snipaste管理员运行了也不行，而且只有焦点在游戏窗口的时候不行

**Comment by septs** [comment]
@QvQwww 该问题可能是为游戏厂商有意为之
