### ISSUE TITLE
Feature request - Print Hotkey

### ISSUE THREAD

**Issue by BentLauritsen** [Snipaste/feedback#817]
Would like a hotkey for print to default printer. Am on Windows 10.

**Comment by liulex** [comment]
Try <kbd>Ctrl</kbd> + <kbd>P</kbd>?

**Comment by BentLauritsen** [comment]
Hehe, was looking for a hot key, newer thought of trying ctrl p.. thank you for the help 

Bent

Sendt fra min iPhone
