### ISSUE TITLE
还是快捷键的问题，F1，F3跟其它软件冲突。

### ISSUE THREAD

**Issue by aricc** [Snipaste/feedback#818]
1、我用Notepad，打开一个文件，要在其中查找一段内容，我会按F3，在Snipaste运行的情况下，不管用了。
2、我还用Visual Studio，有段程序代码我想截个图，发给朋友，按F1，好了,浏览器打开了微软的帮助网页。

当然，我知道可以自定义，我只是对默认的快捷键提点意见。

**Comment by szzhiyang** [comment]
@aricc 很早我就指出过作者如此设计默认快捷键对其他软件一点礼貌都没有，但是作者直接就把我给反怼了，还立即删除了我写的 issue。

不要再抱有幻想了，转投 **ShareX** 吧。**Snipaste** 这种不尊重其他软件的截图软件是没前途的。

**Comment by Genteure** [comment]
@szzhiyang 麻烦说明一下如何在 Github 删除 issue
很想学习一下，谢谢。

**Comment by StarryVoid** [comment]
我也想学习一下，教教我，怎么能如此一本正经的
![2](https://user-images.githubusercontent.com/20756365/35859490-36ced564-0b7b-11e8-9481-f3f0e13efaa7.gif)
 #775

**Comment by StarryVoid** [comment]
@aricc Snipaste最初是帮助设计师提升生产力，就像写代码的人会用F3当查找，F1当帮助，Snipaste也是让截图贴图达到最快所以选择的F1 F2 F3。
当然，如果觉得不适合自己可以改掉，软件本身是绿色软件如果移动只需要拷贝过去，配置都会自动迁移走。
而修改默认值，您觉得，键盘上哪个按键是最快的呢？（请注意很多平板的键盘并没有小数字区和一些特殊键就比如Print）

**Comment by szzhiyang** [comment]
@Genteure @StarryVoid 我当然知道 F1 和 F3 键非常容易按下，可是如果一个软件直接将默认快捷键设置为这两个键就对其他软件不太友好了。将快捷键设置为易于按下的按键应该让用户来做，而不是让软件本身来做，**因为前者属于用户行为，而后者却属于开发者对其他软件开发者的不尊重**。


### 一个软件的默认设置，体现了软件开发者自己的态度，尤其是对其他开发者的态度。


我自己也有在做免费开源工具 [**PerfectWindows**](https://www.github.com/szzhiyang/PerfectWindows)。虽然非常简陋，但功能却个个深得人心，其中有个功能就是为 Windows 添加音量调节热键、音乐播放控制热键和 Windows 计算器热键。这个功能同样也是充分利用了大家不常用的按键，但是 **默认不启用**，因为这个功能会影响到其他软件的快捷键。纵使这个功能再好，我也要求用户根据自己的需求手动开启，因为尊重其他开发者比讨好用户更加重要。

**Comment by StarryVoid** [comment]
@szzhiyang 好吧，话说少了不够直接
来，
1，反驳你说深得人心的那个。
本人在你说的Fn我在用bios的时候被坑次数多了，按个F2还要重启2次服务器，重启一次3min，而我就想进个bios，屏幕上都傻傻的写着F2，请问耽误时间不？你说不启用FN，那么我能告诉你有2年的笔记本默认是启用的然后被用户骂到愧疚改回去的么？需要我给你补几个图吗？
还有，FN和Ctrl在Thinkpad上被人诟病多久，这些你觉得很友好？
2，默认设置觉得作者不够诚意？能改对吧，而且，为什么你觉得F3就不能用？windows快捷键那么多你开发软件去找个别人没用过你也没用过的？还有人喜欢Ctrl+Alt+A的那你去要求腾讯也改了啊，Ctrl+Shift+C你要求欢聚时代和360也改了吧。
3，按你的逻辑，F3对吧，我现在打开wordpress然后按F3，我为什么不能在编辑器中查找？因为chrome给F3劫持了变成网页查找，我是不是可以照你的，给chrome来个issue说 “你这狗屎一样的F3，为什么要劫持，我要在wordpress编辑器里F3” 你觉得如何？

**Comment by StarryVoid** [comment]
@szzhiyang CAD
F1: 获取帮助
F2: 实现作图窗和文本窗口的切换
F3: 控制是否实现对象自动捕捉
F4:数字化仪控制
F5: 等轴测平面切换
F6: 控制状态行上坐标的显示方式
F7: 栅格显示模式控制
F8: 正交模式控制
F9: 栅格捕捉模式控制
F10: 极轴模式控制
F11: 对象追踪式控制
🤨这些快捷键没有一点关联，简直无法理喻🤨我大windowsF3明明是搜索🤨F5刷新，F11全屏，cad赶紧回去重写代码写好了在发出来吧🤨

**Comment by linzyjx** [comment]
微软自家的输入法还能和VS冲突呢
之前还不给改
按键绑定这种东西方便使用就好了，你觉得默认不爽又不是没给你改的权利。说这方面不尊重其他开发者就有点扯了
我是应该尊重吃甜豆花的还是吃咸豆花的呢

**Comment by szzhiyang** [comment]
@StarryVoid 但是 **Snipaste** 本身有个很特殊的性质是，只要你不退出它，它就会长期在后台运行。如此一来，它的热键已经是 **全局热键** 了，并且会覆盖掉其他所有软件的相同热键。这种情况下，二话不说地把默认全局热键设置为 F1 和 F3 这种对于某些软件的某些功能十分关键的按键就是 **Snipaste** 的不对了。相比之下，**ShareX** 的默认热键设计就十分合理。

虽然 **Adobe** 和 **Autodesk** 全家桶的热键设计逻辑与其他软件有些区别，但是至少人家的热键不会干扰到别人家的软件啊，所以你后来的论证说服力不强。

我的电脑上的 F1 键是用来启动 Google Chrome 的。每当我需要查资料或前往某个网站时，我只需要按一下 F1 键后就可以直接输入我想查询的关键词或者我想前往的网站了，指哪打哪。F1 键是可以发挥更大的功用的，用它截图实属浪费。

**Comment by szzhiyang** [comment]
@linzyjx 你想想，当你自己辛辛苦苦编写出来的软件的热键就这样被区区一个截图软件的默认热键给霸占掉的时候，你的心里是什么滋味？

**Comment by ysc3839** [comment]
@szzhiyang 先到先得啊，如果你的软件先运行，那不也是霸占截图软件的热键？

**Comment by StarryVoid** [comment]
@szzhiyang 哥们你的勇气值得奖励，你看看QQ占用的Ctrl+Alt+A这么多年，你去帮大家解放一下快捷键吧，尤其最近语音说话按键用上了F2。

**Comment by linzyjx** [comment]
@szzhiyang 没什么滋味啊。用户喜闻乐见就行，冲突什么的很常见。我只能说自己提供修改快捷键的设置。别的开发者我又过问不了

**Comment by szzhiyang** [comment]
@ysc3839 @linzyjx @StarryVoid 总之，没有软件有资格一上来就把某几个功能键霸占掉。

**Comment by Harry-Chen** [comment]
@szzhiyang 你自己的就是“辛辛苦苦编写的软件”，Snipaste就是“区区一个截图软件”。
如此双标，恐怕不是太好吧？

**Comment by xiao201261** [comment]
@szzhiyang 按照您的逻辑 您的prefectwindoge也没资格“优化”系统哦

**Comment by ysc3839** [comment]
@szzhiyang ShareX 也没资格一上来就霸占 PrintScreen 呢，这个快捷键还是系统级的呢。

**Comment by szzhiyang** [comment]
@ysc3839 可是 **ShareX** 拿 <kbd>Print Screen</kbd>  或 <kbd>Alt</kbd> + <kbd>Print Screen</kbd> 所做的事与 **Windows** 拿 <kbd>Print Screen</kbd> 或 <kbd>Alt</kbd> + <kbd>Print Screen</kbd> 所做的事完全一致。

**Comment by xiao201261** [comment]
@szzhiyang 那您之前设定的的 F1 快捷启动 chrome 是否与系统原来的打开帮助 完 全 一 致 呢

**Comment by szzhiyang** [comment]
@xiao201261 你爸妈有没有教过你做人最起码的素质？

自始至终我都在论证 **Snipaste** 的默认热键设计不合理，可是你有见过我对这个软件进行人身攻击吗？纵使我对这款软件的默认热键设置有多么不满意，我也没有全盘否定或者污蔑这款软件，更没有故意将 **Snipaste** 的名字拼写错误。而你呢？就跟幼儿园的小朋友似的，对同学的某些方面一有不满就给他 / 她起个轻蔑的外号。都这么大个人了，连 **就事论事** 都做不到，真是悲哀啊。

你现在想改你的 **comment** 也来不及了，已经被我用 **ShareX** 截下来了。

**Comment by szzhiyang** [comment]
![default](https://user-images.githubusercontent.com/30952626/35900430-e699021c-0c0c-11e8-8fac-24a59d36287e.png)

**Comment by ysc3839** [comment]
@szzhiyang 个人认为“霸占”这个词是贬义的呢。

**Comment by szzhiyang** [comment]
@xiao201261 是不是故意的你自己心里应该很清楚。

**Comment by xiao201261** [comment]
@szzhiyang 欢迎发 zhihu/v2ex 来裱我

**Comment by szzhiyang** [comment]
@ysc3839 就是贬义的啊，我贬的就是这个不合理的默认热键设置。

**Comment by ysc3839** [comment]
@szzhiyang 所以别人不喜欢你的软件贬你又为何不可呢？

**Comment by szzhiyang** [comment]
@ysc3839 目前 **Snipaste** 还有一些短板，可是你们见我在这个讨论中提到这些短板吗？我贬了半天就是在贬 **Snipaste** 的默认热键设置，并没有贬过它的其他方面，而你们呢？

**Comment by misaka00251** [comment]
换做是我的话，我会把 <kbd>F3</kbd> 改成 <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>A</kbd>而不是到这里提 Issue

**Comment by imguoguo** [comment]
快捷键是否是所谓“霸占”不应该是相对的吗？你不用人家用，反而人家倒有了理，而我用就是对其他开发者不尊重了？其他程序也有默认使用这些个快捷键的情况啊，难不成还一个个地说别人霸占吗？
Windows被调侃成windoge也不是一天两天的事了，人家巨硬都没生气，你就觉着人家没素质了。

**Comment by Genteure** [comment]
@szzhiyang Snipaste 还有什么问题，提出来聊聊啊
