### ISSUE TITLE
蓝色的圆会挡着放大镜没法正常精准截图

### ISSUE THREAD

**Issue by Konecos** [Snipaste/feedback#820]
Bug report
在每次截图大小超过119x119
<img width="403" alt="snipaste_2018 02 08_15 02 45 548" src="https://user-images.githubusercontent.com/35402364/35959850-4bff0d42-0ce2-11e8-88fe-68a2334175fc.png">
<img width="411" alt="snipaste_2018 02 08_15 03 34 822" src="https://user-images.githubusercontent.com/35402364/35959854-5082b92c-0ce2-11e8-9dcf-3a520640927e.png">
那个蓝色的圆就会挡着放大镜没法正常精准截图

**Comment by liulex** [comment]
![default](https://user-images.githubusercontent.com/2010459/35963150-cac33bb0-0cee-11e8-8114-40b8ab6f1eb8.png)
默认就是没勾的啊……

**Comment by Konecos** [comment]
可否不在放大镜中显示这个圆点

否则[锚点]这个功能将会显得有点无用

**Comment by Konecos** [comment]
了解,多谢♪(･ω･)ﾉ
