### ISSUE TITLE
图像输出文件命名规则采用序列编号规则时，重启电脑规则又从零开始的功能需求反馈。

### ISSUE THREAD

**Issue by colemanlee** [Snipaste/feedback#823]
请求新功能：

1. 除了告诉我你想要什么：图像输出文件命名规则采用序列编号规则时（例如PIC_.png），输出的图像文件名重启电脑后依然接着上一次开机输出的最后一个文件名继续输出。
2. 它具体是怎样的：图像输出文件命名规则采用序列编号规则时（例如PIC_.png），输出的图像文件名为PIC_1.png，...PIC_5.png，重启电脑后，输出的图像文件名又从PIC_1.png开始了。
3. 你为什么需要它：每次截图后，需要上传图片到论坛，选择图片直接选择编号最后一个会很方便快捷，但是如果每次重启电脑后截图输出编号都从头开始，找图片会比较花时间麻烦（我的图片很多，使用列表方式显示的）。

**Comment by liulex** [comment]
1 和 2 好像矛盾？
