### ISSUE TITLE
windows版建议优化截图启用速度

### ISSUE THREAD

**Issue by cooper1x** [Snipaste/feedback#824]
请求新功能？
* 我习惯用快捷键F1截图，但是长时间不用的话，第一次触发截图的时间比较长，只有随后的第二次第三次会比较快。我想让它随时都能快速调用出来，就像QQ截图一样。
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by bydx** [comment]
你可以在issue里搜搜“延迟”“卡 慢”等关键词找找以前作者提出的解决方案是否奏效，目前我也被该问题困扰而不得解。
