### ISSUE TITLE
新功能：建议右键菜单选项支持快捷键

### ISSUE THREAD

**Issue by YanleLiu** [Snipaste/feedback#825]
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282
请求新功能：右键菜单中如果加入这样的快捷方式会更加方便：

![snipaste_2018-02-14_10-39-46](https://user-images.githubusercontent.com/36144685/36185608-0e0d475a-1175-11e8-8557-b6eded8645a5.jpg)

之前总是点击右键然后移动鼠标-点击想要的选项，比如“销毁”或“关闭”，如果支持快捷键，通过键盘的“右键”+字母就完全可以做到，特别方便。

**Comment by liulex** [comment]
![default](https://user-images.githubusercontent.com/2010459/36546557-b3c187f8-1826-11e8-99d5-d2cdbce10413.png)
