### ISSUE TITLE
当鼠标在贴图上时放大镜会被截图

### ISSUE THREAD

**Issue by problem233** [Snipaste/feedback#826]
1. 在左面上贴一张图；
2. 鼠标悬停在贴图上；
3. 按下截图键；
4. 移开鼠标，发现放大镜被截图截进来了。

注：如果鼠标不在贴图上，则不出现此 bug。

**Comment by GregAMO** [comment]
@problem233 未复现。请问你的截图键是什么呢？
如果包含 Alt 就会这样
因为在贴图上按住 Alt 是呼出放大镜

**Comment by problem233** [comment]
……`Ctrl+Alt+S`
