### ISSUE TITLE
【新功能请求】颜色记忆

### ISSUE THREAD

**Issue by ghost** [Snipaste/feedback#827]
请求加入颜色记忆的功能

* 举例: 箭头需要高亮的枚红色，默认色板里没有，每次都要选，而字体需要高亮的黄色，截一张图时，既需要添加箭头，又需要添加说明文字，颜色就需要换一次，如果多次重复的操作，就要换很多次。
如果能记住每次箭头对应的高亮玫红、字体对应的高亮黄色，就不需要切换颜色，从而提升效率。

**Comment by oott123** [comment]
@ppdan 这个好，虽然系统自带的也可以凑合用，不过没有自带的方便就是

**Comment by liulex** [comment]
谢谢建议，已添加选项：为不同的标注类型使用独立的颜色

**Comment by dan-hsc** [comment]
感谢！
