### ISSUE TITLE
新功能请求：在某些进程里，不响应截图快捷键。

### ISSUE THREAD

**Issue by kokutoukiritsugu** [Snipaste/feedback#828]
比如 dota2 游戏时，不响应F1截图键，
在 dota2 里面F1是选择英雄。

虽然可以把F1改成其他的。。。但是我还是挺喜欢f1作为截图键的。。。
dota2的截图有steam自带的F12。

希望能有个列表，我们自己可以维护，然后就是希望这个列表能单独作为一个exclude.ini文件。。。

**Comment by liulex** [comment]
Pro 版已实现自定义每个快捷键的程序黑名单，不过都会记录在 config.ini 里，没必要单独弄个配置文件吧。
