### ISSUE TITLE
希望文字描邊的顏色可調整

### ISSUE THREAD

**Issue by allenyllee** [Snipaste/feedback#83]
在截圖中加上文字時，可以設定文字描邊，
但是描邊的顏色總是黑色的，
我希望可以有白色邊，或其他顏色
若能再加上陰影就更好了
類似Evernote 圖片加上文字的那種效果

**Comment by liulex** [comment]
谢谢你的建议，该功能是计划中的。

以后会使得所有形状都可以描边、加阴影。
但是涉及的代码量较大，所以不会优先实现，还请耐心等待。

另，目前描边的颜色是根据文字颜色的灰度值自动设置为黑色或白色，并非总是黑色。:-)

**Comment by liulex** [comment]
2.4 已支持～
