### ISSUE TITLE
取色值请增加HSL（色相、饱和度、明度）模式

### ISSUE THREAD

**Issue by hiforrest** [Snipaste/feedback#830]
HSL模式会给设计师带来巨大的帮助，如果能以图像显示（下图）就更完美了

![screenshot_20180302_102408](https://user-images.githubusercontent.com/2953848/36880483-e10c6f7e-1e03-11e8-9309-9dfd735bc23b.jpg)

**Comment by septs** [comment]
请合并至 #419 讨论
