### ISSUE TITLE
问一下以后有没有考虑提供安装包

### ISSUE THREAD

**Issue by Dy64** [Snipaste/feedback#831]
问一下以后有没有考虑提供安装包。
因为我在软件管理的评论中发现有些人，对便携版软件不太了解，不会解压使用和卸载。
对于一些用户，可能会更方便一些。

**Comment by septs** [comment]
您可以推荐用户使用 [Windows Store](https://www.microsoft.com/store/productId/9P1WXPKB68KX) 版本

**Comment by liulex** [comment]
@Dy64 谢谢建议，以后会有的。弄起来比较麻烦，暂时不想弄……
