### ISSUE TITLE
建议移到标题栏处自动吸附整个窗口,而不是标题栏文字

### ISSUE THREAD

**Issue by genyez** [Snipaste/feedback#832]
![image](https://user-images.githubusercontent.com/13222726/37017810-f22a6652-214c-11e8-9bad-1bcc9558736d.png)

目前是这种效果,能不能移到标题栏就选中整个窗口呢?像这样

![image](https://user-images.githubusercontent.com/13222726/37017826-0180a30a-214d-11e8-8377-df7ad8f0c8b8.png)
目前想要选中整个窗口要精准放到边框像素上,非常难

**Comment by septs** [comment]
无法判断 请使用快捷键 Tab 切换 "切换检测窗口/检测界面元素" 完成
更多快捷键请参考此链接 https://docs.snipaste.com/zh-cn/key-bindings
