### ISSUE TITLE
mac 版贴图的右键菜单问题

### ISSUE THREAD

**Issue by shibang** [Snipaste/feedback#833]
平台：macOS
问题：F3 贴图后，如果图片靠近屏幕底部，右键呼出菜单后无法选择，鼠标移向菜单后菜单就消失
复现步骤：
1. F1 截图
2. F3 贴图
3. 将贴图移到屏幕底部
4. 右键呼出菜单并尝试鼠标选择菜单

**Comment by liulex** [comment]
Mac 版右键菜单确实有点问题，有空再看看哈。
