### ISSUE TITLE
关于贴图，可否钉在桌面上而不是一直置顶？专业版可以做到，哪里获取和购买呢？

### ISSUE THREAD

**Issue by landocean** [Snipaste/feedback#834]
专业版哪里获取和购买呢？

**Comment by liulex** [comment]
届时会在官网/微博/Telegram发布消息哈。

**Comment by H4M5TER** [comment]
专业版已经入了 在哪里可以钉桌面啊

**Comment by liulex** [comment]
@H4M5TER 专业版只能让窗口不置顶，并没有说过可以钉在桌面上。
请问哪个软件可以让窗口钉在桌面上呢？没了解过这种行为。。

**Comment by H4M5TER** [comment]
@liulex 
希望钉图片在桌面上只是我的预期 我看这个issue的描述还以为是可以的 是我误解了
有哪些软件我也在找 考虑rainmeter？
