### ISSUE TITLE
mac版截图粘贴到outlook通过邮件发送，对方看不到图片

### ISSUE THREAD

**Issue by clotong** [Snipaste/feedback#836]
发现snipaste截的图粘贴到邮件中发送，对方看不到图片，只有一个图片框，没图片显示，试了下腾讯的jietu软件没有这个问题，不知怎么回事

**Comment by liulex** [comment]
只是 outlook 吗？有没有试过其他邮件客户端呢？

**Comment by clotong** [comment]
以下都是在macos下测试（outlook,airmail，JieTu都是macos上的app软件）
Snipaste截图粘贴
outlook客户端发出------------Airmail邮件客户端接收，显示没问题
outlook客户端发出------------网页版邮箱接收，显示出错
Airmail邮件客户端发出--------outlook客户端接收，显示没问题
Airmail邮件客户端发出--------网页版邮箱接收，显示没问题


JieTu(腾讯产品)截图粘贴
outlook客户端发出------------Airmail邮件客户端接收，显示没问题
outlook客户端发出------------网页版邮箱接收，显示没问题
Airmail邮件客户端发出--------outlook客户端接收，显示没问题
Airmail邮件客户端发出--------网页版邮箱接收，显示没问题

看情况就是outlook发出的snipaste粘贴的图片，在mac客户端软件都能很好识别，网页版无法识别（windows系统下接收跟网页版一样）。

2018-03-24 1:08 GMT+08:00 Le Liu <notifications@github.com>:

**Comment by issuessss** [comment]
mac版outlook 16.23.1（190326）最新版，截图后粘贴到邮件正文，发送到qq邮箱，对方看不到图片。
qq自带截图可以看到图片
