### ISSUE TITLE
Bug: 打开开始菜单时无法给任务栏截图

### ISSUE THREAD

**Issue by CrabAss** [Snipaste/feedback#839]
系统版本：Windows 10 Pro 1709
软件版本：1.16.2 x64 (Microsoft Store 版本)

复现步骤：
打开 Windows 开始菜单后，**鼠标单击 Snipaste 托盘图标**开始截图，此时：
1. 整个任务栏悬浮于截图图层之上，致使此时 Snipaste 无法给任务栏截图；
2. 截图图层上的开始菜单内容消失，只剩下灰色亚克力背景；
3. 如果此时再单击一次 Snipaste 托盘图标，Snipaste 将会闪退。

以下截图为 bug 复现时通过 Windows 自带截图功能所截取的全屏图片。在图片中鼠标正位于任务栏上的 Firefox 图标，当鼠标位于任务栏时 Snipaste 无法检测到鼠标位置。
![2018-03-10 1](https://user-images.githubusercontent.com/13916997/37243237-254bfdea-24b1-11e8-911e-143178af0d25.png)

**Comment by liulex** [comment]
这种问题应该有必现的办法，我自己使用过程中没有遇过，所以没办法给你解决哦。
另外，截图过程中主动点击托盘图标 Snipaste 会退出，这是我设定的行为，防止截图时万一卡死后用户无法控制电脑，并不是崩溃哦。

**Comment by CrabAss** [comment]
这个 bug 在我的电脑上按照上述步骤是必现的，大概是任务栏浮在截图图层之上导致的？

**Comment by CrabAss** [comment]
前提是先打开开始菜单，如果不打开开始菜单的话是没问题的

**Comment by liulex** [comment]
@CrabAss OK，已复现。

**Comment by CrabAss** [comment]
感谢，希望能尽快修复
