### ISSUE TITLE
自动更新地址被ESET列为内部黑名单拦截

### ISSUE THREAD

**Issue by Mosney** [Snipaste/feedback#840]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好
![image](https://user-images.githubusercontent.com/22477230/37250077-596aabd4-252f-11e8-9973-b7eb9dd30382.png)

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by liulex** [comment]
感谢你的反馈，但这种问题我也没什么办法呢…… 😅
