### ISSUE TITLE
希望可以直接截圖

### ISSUE THREAD

**Issue by peckyh** [Snipaste/feedback#841]
你好，
工具很好用，
希望按下快捷鍵之後，可以馬上截圖，目前要先點一下隨意處才可以開始截圖，
著實有點不方便，
望改進！

感謝！

**Comment by hujy23** [comment]
@peckyh 可以试试开启“偏好设定 - 以管理员身份”

**Comment by peckyh** [comment]
@hujy23 抱歉沒寫到 我是mac版！

**Comment by hujy23** [comment]
@peckyh 😆哦哈哈当我没说~

**Comment by liulex** [comment]
按下快捷键之后是自动选择界面元素状态，点一下鼠标可以开始区域拖拽。
即使是 Mac 自带的贴图，也是按下快捷键之后点一下才开始截图啊。
