### ISSUE TITLE
请求增加些箭头的选项，最少要有双箭头

### ISSUE THREAD

**Issue by zfgith** [Snipaste/feedback#843]
如题，现有版本的箭头种类太少，所以一直没怎么用这个软件，期望增加些箭头，如双箭头的标识

**Comment by liulex** [comment]
以后会逐步增强标注功能。

**Comment by liigo** [comment]
支持自定义就OK了

**Comment by shuwn** [comment]
這些功能很常用到，在給內部或客戶說明物體的尺寸大小、範圍時都會用到
設計上建議可以參考一下 Keynote 或Powerpoint 的設置
![photo_2019-03-20_11-21-39](https://user-images.githubusercontent.com/20023822/54657005-c3e39300-4b02-11e9-9aed-b6dd42496d07.jpg)

**Comment by liulex** [comment]
Snipaste 2.5 专业版已支持。

**Comment by shuwn** [comment]
Hi, @liulex 
Mac 版無專業版購買，Beta 版也未支援
請問 Mac 什麼時候推出專業版？謝謝！

<img width="565" alt="image" src="https://user-images.githubusercontent.com/20023822/205533921-76154c9e-c35b-49bc-bcf0-b71172d23c64.png">
<img width="467" alt="image" src="https://user-images.githubusercontent.com/20023822/205534024-1ea209f5-d236-46ce-8d1e-4fa23e3d2bb7.png">
