### ISSUE TITLE
新功能请求：可编辑的屏幕文字贴图

### ISSUE THREAD

**Issue by Cirn09** [Snipaste/feedback#844]
我很喜欢贴图功能，贴张文字作为暂时的备忘非常方便。

缺点就是图中文字重复编辑比较麻烦，
希望可以添加一个屏幕笔记的功能：可以向屏幕贴一张半透明的白色图片，获取焦点时就可以对图中文字进行编辑。

**Comment by liulex** [comment]
文字笔记功能想要做得方便，其实有很多要做的。目前已经有很多很棒的这类软件，比如我自己在用的 [Stickies](http://www.zhornsoftware.co.uk/stickies/index.html).
对于完全满足我需求的软件，我不会去重复造轮子。
