### ISSUE TITLE
关于外接显示器的问题 

### ISSUE THREAD

**Issue by SilverPoker** [Snipaste/feedback#846]
Bug report
笔记本外接显示器的时候出现了问题,(笔记本在外界屏幕左边，并且上对齐的时候，只是偶尔出问题，现在显示屏在左边的时候一直出现问题·····真诚希望改进····程序员干活必备的显示屏啊)

---

**Comment by liulex** [comment]
@SilverPoker 问题消失了吗？为什么关了呀……
