### ISSUE TITLE
关于高分屏的支持（截图同比例裁剪缩放）

### ISSUE THREAD

**Issue by cfanseal** [Snipaste/feedback#848]
使用的是Mac 视网膜屏幕
beta版本也很好用哈，不过就是希望支持图片缩放，在设置里面支持缩放为1/2尺寸和缩放为1/4尺寸，甚至这个缩放可以做到截图后的编辑区域里面，在点击后默认上次的选择，这个缩放要同比例缩放哈，这样用起来就更方便了，因为高分屏截图后贴到exce或者l那是没法看的，图片太大了。。

希望针对高分屏开发这个使用的功能哈

**Comment by liulex** [comment]
可以先在贴图缩放，然后复制缩放后的图片。
视网膜屏现在应该还没有 4x 的吧……

**Comment by zxteloiv** [comment]
用贴图缩放的办法临时解决了！做PPT的时候截图实在太大了，最终尺寸实在吓人。

**Comment by Simon717** [comment]
求更新 希望加入缩放功能

**Comment by DoveAz** [comment]
> 求更新 希望加入缩放功能

同求，最好有个选项，设置截图输出尺寸比例，每次都在贴图里选太麻烦了

**Comment by septs** [comment]
Duplicate of #357
