### ISSUE TITLE
一段时间不操作电脑，电脑未响应

### ISSUE THREAD

**Issue by zhangweizhe** [Snipaste/feedback#850]
发现了 bug？
* 请描述一下重现的步骤，越详细越好

一段时间不操作电脑，5~10分钟，鼠标可以移动，但点击贴图以外的区域会死机，只有贴图可以移动。
不启动snipaste也会出现这样的问题，想问一下会不会和snipaste有关，因为死机的时候只有贴图可以移动。。。
操作系统是win10 64位，snipaste版本为1.16.2。

**Comment by liulex** [comment]
"不启动snipaste也会出现这样的问题" 所以不应该和 Snipaste 有关吧…… 😅 
我猜是卡住的时候只有当前激活的窗口可以移动。。

**Comment by zhangweizhe** [comment]
@liulex  好吧。。谢谢😁
