### ISSUE TITLE
Snipaste + Dexpot 组合出现 BUG

### ISSUE THREAD

**Issue by By2048** [Snipaste/feedback#852]
在以下环境中
Win10 专业版 + Dexpot 1.6.14 build 2349 + Snipaste 1.16.2 
贴图在虚拟桌面之间移动时 经常会出现贴图不能正常缩放的问题，偶尔会出现贴图不能关闭的问题。

**Comment by liulex** [comment]
跟这类软件的兼容性我无法保证的，也没有精力去做兼容，不过你可以试试 Windows 自带的虚拟桌面。
