### ISSUE TITLE
MAC中的截图直接粘贴到文档中，文件将非常大

### ISSUE THREAD

**Issue by sesame437** [Snipaste/feedback#854]
发现了 bug？
MAC版本10.12.6。试过1.16和1.16.2
当用snipaste进行截图时，如果完成截图后直接粘贴到文档中，文件非常大，比如数MB。如果把截图存为jpg文件则只有100KB，想问这是一个问题还是一个Bug？是否能够解决。

**Comment by liigo** [comment]
直接粘贴的应该是BMP格式，数据很大。存为png或jpg时经过压缩，数据很小。

**Comment by liulex** [comment]
dup of #881
