### ISSUE TITLE
win10 编辑环境变量窗口打开后，按 F1 截图无效。切换到其他窗口正常 

### ISSUE THREAD

**Issue by evonli** [Snipaste/feedback#855]
* win10 编辑环境变量窗口打开后，按 F1 截图无效。切换到其他窗口正常 
-----
补充：

后来发现不止这个窗口有问题，postgres 整个安装过程的窗口都无法使用快捷键。也重启过 snipaste ，没重启电脑

**Comment by ysc3839** [comment]
https://docs.snipaste.com/zh-cn/troubleshooting?id=有时候快捷键不响应
