### ISSUE TITLE
提个建议:能不能加一个快捷键例外功能呢

### ISSUE THREAD

**Issue by XXXXuan** [Snipaste/feedback#857]
比如程序全屏运行的时候禁用快捷键
或者用户可以自定义某进程运行时禁用快捷键

**Comment by liulex** [comment]
专业版可对每个快捷键设置例外：
![snipaste_2018-03-29_19-38-08](https://user-images.githubusercontent.com/2010459/38086901-b727ab5c-3388-11e8-9f86-a1f4f67729e9.png)
