### ISSUE TITLE
提个建议：希望能连续画线或折线

### ISSUE THREAD

**Issue by serenitytree** [Snipaste/feedback#858]
首先谢谢你开发的Snipaste，很棒

现在画箭头或折线时，按着左键画完一根箭头后，松开左键，想按下左键继续画第二根箭头时，发现是移动箭头，需要单击右键后，才能再按左键继续画第二根箭头。
这样的话如果想连续画几根衔接的箭头或折线时，很不方便。

能不能改成这样：
1）按着左键画完一根箭头后，松开左键，按下左键继续画第二根箭头，这样能连续不断衔接的画一组箭头或折线；
2）如果画完一根箭头后，想移动箭头，而不是连续画箭头时，可以点击一下右键，然后移动箭头方向。

这样是不是更方便连续的箭头与折线，谢谢

**Comment by serenitytree** [comment]
刚才试了一下，折线原来是这样画的，“单击左键--松开移动--再单击左键......”
哈，我以前是“按着左键--画一根折线---想再按着左键再画另一根折线”，谢谢啊

-------------------------
对了，箭头好像不能那样画是吧

能不能实现成这样：
1）按着左键画完一根箭头后，松开左键，按下左键移动左键继续画第二根箭头，连续不断、衔接的画一组箭头；
2）如果画完一根箭头后，想移动箭头，而不是连续画箭头时，可以点击一下右键，然后移动箭头方向。

因为我使用过程中，发现画完一根箭头后，接着画另一根箭头的使用率很高，
而画完一根箭头，马上编辑移动箭头的方向机会少，

为了提高画线效率，能不能考虑这种方式：
1）画完箭头或直线后，默认是已经结束，可以接着画另一根；
2）如果画完一根，想调整这根箭头或直线，单击右键转到编辑模式

或者在设置里加个参数，来控制画线模式的选择，呵
一种是画完一根后，是编辑模式
另一种是画完一根后，是结束模式，可以直接画下一根

谢谢你的回复，祝你工作顺利：）

**Comment by liulex** [comment]
> 为了提高画线效率，能不能考虑这种方式：
1）画完箭头或直线后，默认是已经结束，可以接着画另一根；
2）如果画完一根，想调整这根箭头或直线，单击右键转到编辑模式

现在的操作模式正好和你描述的相反，想要连续画，画完一根之后点一下右键就可以了，应该没有必要专做个选项，因为会影响其他标注形状的逻辑。
习惯一下当前的操作逻辑就好了。
