### ISSUE TITLE
提个建议：增加在Web网页中通过JavaScript调用。

### ISSUE THREAD

**Issue by xhanglizhu** [Snipaste/feedback#859]
首先感谢分享插件。
最近在做web端时，想通过JS调取一些截图插件，然后进行相关业务的处理，没有找到很好的解决方案。
有了解过牛牛截图，但是带有LOGO已经放弃了。

**Comment by liulex** [comment]
抱歉，软件定位不同，不会考虑。

**Comment by ysc3839** [comment]
@liulex 以后有插件系统的话，也许可以自己开发一个插件来支持。
