### ISSUE TITLE
截屏的时候 取色器选择了 hex 颜色值 但是 有时候会失效 变回原来的 rgb

### ISSUE THREAD

**Issue by MG-s** [Snipaste/feedback#860]
更改了 首选项-常规-取色器hex颜色
经常莫名其妙的失效  取色的时候又变成默认的rgb格式 (xxx,xxx.xxx)
重新去掉勾选 再打开 才会正常
但是一下午就遇到了三次了

**Comment by liulex** [comment]
![snipaste_2018-03-29_19-36-20](https://user-images.githubusercontent.com/2010459/38086831-759d0c40-3388-11e8-9f3c-31b48bf77c99.png)
