### ISSUE TITLE
贴图无法向上挪至超出屏幕。

### ISSUE THREAD

**Issue by wdhwg001** [Snipaste/feedback#861]
假设有一张特别长的图，将它贴在屏幕上后，向上拖动会发现始终与屏幕顶端维持一定距离，无法紧贴，也无法超出屏幕，这使得贴图功能在查看长图时十分不便。

![image](https://user-images.githubusercontent.com/8943519/38126310-60a635a6-3422-11e8-9ed2-03c4ed8d5344.png)

**Comment by liulex** [comment]
https://docs.snipaste.com/zh-cn/troubleshooting?id=贴图无法拖动超过屏幕上边界

**Comment by runner56** [comment]
你好，设置了“拖动时显示窗口内容”，还是一样现象。往上拖动图片，超出边界时，会自动缩小图片，截取掉贴图的内容。

**Comment by runner56** [comment]
找到问题点了
1. Windows+U快捷键，打开轻松访问中心。
2. 轻松访问中心→使鼠标更易于使用 
3. 不选中（不打勾）"防止将窗口移动到屏幕边缘时自动排列窗口" →确定
4. https://docs.snipaste.com/zh-cn/troubleshooting?id=贴图无法拖动超过屏幕上边界，再在显示性能中设置"拖动时显示窗口"
