### ISSUE TITLE
建议：直接读取、显示并按T复制窗体控件中的文字

### ISSUE THREAD

**Issue by wdhwg001** [Snipaste/feedback#862]
可以类似于在选择截图尺寸时按C复制颜色一样，当截图工具定位到一个窗体控件时，显示它所包含的文字，可以按T直接复制它。

更进一步的，可以同时显示窗体控件所在的进程名吗？可以是个可选功能，能用于快速定位国产辣鸡软件弹窗一类的。

我记得AutoIt中包含了一个窗体信息工具，提供了这个功能，还蛮实用的。

**Comment by ysc3839** [comment]
@wdhwg001 读取窗口信息的话已经有很多工具了。

**Comment by wdhwg001** [comment]
@ysc3839 是的，但是很少有人会像开着截图工具那样将窗口信息工具常驻后台，它们作为Debug和开发工具比较常见，而Snipaste支持读取文字的话，更多的用途应该是在一定程度上替代OCR，将文字快速复制出来。

**Comment by ysc3839** [comment]
@wdhwg001 “很少有人开着”不代表你不能这么做，你需要的话一直开着就好了。

**Comment by wdhwg001** [comment]
@ysc3839 即使如此，想要获取控件文字，也依然是一个需要先定位，然后回工具里复制的工作。无妨，我自认为可以直接按键复制是很方便的，由作者决定是否实现吧。

**Comment by ysc3839** [comment]
@wdhwg001 这个需求已经有现成的工具了，Textify。
