### ISSUE TITLE
更新到最新版，发现有红点不知道如何去除？

### ISSUE THREAD

**Issue by TYZRPVX** [Snipaste/feedback#863]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好
![image](https://user-images.githubusercontent.com/7645818/38130169-85be30f2-3434-11e8-8011-6369dbf07d10.png)

1. 如何去除红点呢？
2. 如何修改标注-方框的线条粗细？

**Comment by Dy64** [comment]
鼠标点击红点会有提示，确认后就消失了

线条粗细可以用鼠标滚轴调节
