### ISSUE TITLE
在 macOS High Sierra(10.13.3) 下截图的颜色不正常

### ISSUE THREAD

**Issue by run-ze** [Snipaste/feedback#865]
发现了 bug？
* 在 macOS High Sierra(10.13.3) 下截图的颜色不正常
* 版本 1.16.2-Beta

对比如图，上图为使用 snipaste 截取，下图为使用系统截图（cmd + shift + 4）截取。

![snipaste_2018-04-02_16-12-26](https://user-images.githubusercontent.com/7091451/38189177-7f27a520-3691-11e8-8f26-447ff15bf04c.png)
![2018-04-02 16 12 10](https://user-images.githubusercontent.com/7091451/38189187-87de3620-3691-11e8-8de4-0fb07c9d341e.png)

**Comment by MrJia1997** [comment]
相同的问题在Mojave上依然存在，怀疑是api没有及时更新？

**Comment by RoadToDream** [comment]
@MrJia1997 需要改的话用ColorSync Utility打开然后Assign P3 色域就好了
![image](https://user-images.githubusercontent.com/8088354/48457291-1f241280-e7fd-11e8-86d0-23ed72f1f32e.png)

**Comment by RoadToDream** [comment]
@MrJia1997 或者你直接用我写的quick action也可以
[Assign P3.workflow.zip](https://github.com/Snipaste/feedback/files/2579115/Assign.P3.workflow.zip)

**Comment by liulex** [comment]
2.2.0 Beta 已修复。
