### ISSUE TITLE
I wish to add keyboard shortcuts for changing brush size except the wheel; 希望增加改变笔刷宽度的键盘快捷键除了滚轮以外。

### ISSUE THREAD

**Issue by thomason-gh** [Snipaste/feedback#866]
Feature request：I wish to add keyboard shortcuts for changing brush size in note mode except the wheel.
*Because I'd like sketch and note on the screen with the handwriting pen and the digital pad, changing brush size is a operation using so often. but default only one way is rolling the wheel on the mouse now, and no possible give wheel in you pen you know. I prefer to use either wheel or keyboard "+, -"or "up, down"to changing the brush size, then you can change brush size on keyboard with left hand, and draw with right hand.

---

请求新功能: 希望增加改变笔刷宽度的键盘快捷键，除了滚轮以外。
* 因为我喜欢使用手写笔和手写板在屏幕上批注和绘画，经常需要改变笔宽，但现在改变笔宽只有鼠标滚轮一种方式，你知道手写笔上是不可能有滚轮的。
因此，我希望在滚轮的基础上增加键盘快捷键比如”+“、“-”或上、下箭头，这样你可以右手用笔画图，而左手可以调整笔宽，不需要再另去找鼠标。

**Comment by thomason-gh** [comment]
Feature request：I wish to add a tool for changing brush size in note bar, just with pen pick or drag.

Reason: After using a period, I found it's necessary yet, because you have neither wheel nor keyboard on the pen and writing screen( panel). 
Ways: for example, can be a pen size changing scroll bar, in the note tools bar, maybe always display, maybe display when you pick the pen size icon; of course display several icons with different pen size for you picking, is the simplest way.

请求新功能：在标注工具条中增加用笔点击就能改变笔宽的工具。
现在我使用了一阵，觉得除了鼠标滚轮和键盘以外，还是需要另外的调整笔宽的方式，因为这两种设备都不在笔和手绘屏（板）上。例如：可以在标注工具条中，增加一个改变笔宽的拖动条，可以一直显示，也可点击笔宽图标后出现；当然最简单的方式是几个显示不同笔宽的图标，直接点击即可。

**Comment by TTTPOB** [comment]
@thomason-gh 可是现在有调节笔宽的按钮啊

**Comment by thomason-gh** [comment]
![snipaste20180813_154617](https://user-images.githubusercontent.com/38025583/44019130-7cd34cec-9f10-11e8-9bea-dc097e006929.jpg)

我怎么只有这个？只能看，或者用键盘改，不能用鼠标改呀？是因为win7版本吗？

**Comment by liulex** [comment]
@thomason-gh 多个笔尖是专业版的功能。
可以用鼠标滚轮改笔宽的，跟系统版本没关系。

**Comment by thomason-gh** [comment]
谢谢您的回复！看来要了解一下专业版，既然是用手绘板，那就算是比较专业了呵呵。




 qq:104373083

在 2019-03-11 00:18:15，"Le Liu" <notifications@github.com> 写道：


@thomason-gh 多个笔尖是专业版的功能。
可以用鼠标滚轮改笔宽的，跟系统版本没关系。
