### ISSUE TITLE
UWP版本的3点建议

### ISSUE THREAD

**Issue by lightbluebokeh** [Snipaste/feedback#869]
建议
* 在重启程序后绘画工具的颜色会被设置成红色，希望能保留上一次关闭时的颜色
* 希望增加隐藏任务栏图标的开关，希望能通过热键使用截图和贴图功能就好
* 希望能区别不同绘画工具的颜色，比如线条使用绿色的同时矩形可以用蓝色，方便切换工具后使用对应的颜色

顺便说一个小问题
* 从设置里打开网址时，如果没有提前打开 Chrome，打开后会导致 Chrome 直接崩溃（不知是Chrome还是程序的原因）

最后十分感谢作者写出这款优秀的截图程序

**Comment by KazamaSion** [comment]
你或许应该爆出您使用 Chrome 的版本号，以便提供复现问题的环境。如果问题无法被复现，就算 bug 存在也无法进行修复。
我是 Version 67.0.3386.1 (Official Build) dev (64-bit)，同时 Snipaste 1.16.2(uwp version)、Windows 10 专业版 1709(16299.309)，从设置项打开网址并没有问题。已经提前将 Chrome 窗口关闭。

另外，我个人认为，您可以尝试将所有的 Chrome 插件禁用后再打开看看。看一下是否是 Chrome 扩展的问题。

**Comment by liulex** [comment]
Hmmm..

> 在重启程序后绘画工具的颜色会被设置成红色，希望能保留上一次关闭时的颜色

#420 

> 希望增加隐藏任务栏图标的开关，希望能通过热键使用截图和贴图功能就好

 #169 #777 #851 

> 希望能区别不同绘画工具的颜色，比如线条使用绿色的同时矩形可以用蓝色，方便切换工具后使用对应的颜色

#827

**Comment by KazamaSion** [comment]
Windows 版本应通过“[运行](https://jingyan.baidu.com/article/c85b7a645138a3003bac959b.html)”，输入"winver"后，在打开的窗口中寻找的当前系统版本，才是完整的版本。

当然即便这么说，也很可能是留这么个 issue 在这里，可能无果而终。这类问题还是比较“玄学”的。

**Comment by lightbluebokeh** [comment]
感谢提醒，
Windows 10 专业版 版本1709（OS内部版本 16299.309)

**Comment by liulex** [comment]
@lightbluebokeh 
我测试过 UWP 版本的颜色保存也是没有问题的……如果说颜色保存无效的话，进入截图后按 <kbd>R</kbd> 使用上一次的截图区域应该也是无效的，请问是这样的吗？

关于另一个问题，请问具体是设置窗口里哪个页面的哪个网址呢？

**Comment by lightbluebokeh** [comment]
1. 刚刚测试了，过程：
打开程序 - 截一张图 - 为了验证功能再打开截图一次 - 按R - 恢复了第一次截图的区域 - 退出程序 - 从开始启动 - 打开截图 - 按R - 无反应并且听到一声提示音（即调节音量时候的提示音）

2. 在首选项中“关于”栏下方“主页”“文档”等蓝色部分网址。

**Comment by lightbluebokeh** [comment]
刚刚找到原因了，首选项 - 贴图 - 行为 - 自动备份我手动取消了，于是便出现了上面的问题。

虽然不太理解自动备份是什么实现，但还是觉得“贴图”的设置影响到了“截图”是不是不太对…

**Comment by liulex** [comment]
@lightbluebokeh 逻辑上确实有问题，之前没注意到，谢谢指正，下次会调整。
