### ISSUE TITLE
长截图

### ISSUE THREAD

**Issue by ypli0629** [Snipaste/feedback#870]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？

请求新功能？
希望能加入滚动截图，平时经常查看日志，能有滚动截图就方便多了

**Comment by huihuimoe** [comment]
#19 duplicate
