### ISSUE TITLE
请求新功能：在截图上添加框批注时，希望可设置笔触的粗细程度～

### ISSUE THREAD

**Issue by aoxu** [Snipaste/feedback#874]
这个功能的具体实现可以参照QQ自带的截图功能，在截图后，拉出一个红框时，可以选取3种不同粗细程度的笔触。
需要这个特性的原因是，我发现Mac版的红框线条过于细，以至于看不太清楚红框在哪，而Windows版没有这个问题（粗细程度刚好），两者不一致。我是两个平台都在使用的用户，Mac版这一点让我很头疼。
建议要么把Mac版的粗细程度调整为与Windows版一致，要么增加可选粗细程度，都可以解决这个问题。

**Comment by KazamaSion** [comment]
@aoxu 请尝试使用鼠标滚轮调整。

**Comment by aoxu** [comment]
@KazamaSion 试了一下可以，谢谢～
Mac下使用触摸板，没有鼠标滚轮，所以这个操作也许过于隐蔽～
