### ISSUE TITLE
【优化】希望绘制的形状能够进行旋转调整

### ISSUE THREAD

**Issue by David318** [Snipaste/feedback#877]
绘制的矩形形状，包括马赛克/模糊的填充，绘制完区域以后，希望能够进行旋转调整，现在只能调整大小、边缘之类的

**Comment by Franinc** [comment]
确实需要旋转功能，对截图里杂乱信息进行遮罩/圈选时，有时只需一个旋转的框就能搞定，但目前只能多画几个框，像狗啃了似的😂

**Comment by liulex** [comment]
2.2 版可以旋转的。
