### ISSUE TITLE
[新功能]截图保存为webp格式

### ISSUE THREAD

**Issue by nottellyou** [Snipaste/feedback#878]
对于普通用记来说，无非就是截图保存到电脑上或者临时截图用一下。但仅仅是用于截图，只是要求方便，好用而已。

不过，对于一些做网站类的可能要经常截图放到网站当中，图片一多，流量也就大了。如果能保存为webp格式图片，那么，同样清晰度的图片会比jpg格式会小好多。网站的整体体积也会变小、网站流量也会变少。对于站长来说也是一个福音。

**Comment by hoohyaIII** [comment]
这个非常支持，确实应该有这个功能。

**Comment by WangZishi** [comment]
webp 在浏览器中已经广泛部署使用 。

https://www.caniuse.com/webp

![image](https://user-images.githubusercontent.com/8288105/95935416-ca80dc00-0e05-11eb-8073-542dd4fe7275.png)


同时 avif 作为 webp 的替代者也应该被考虑加入。

https://www.caniuse.com/avif

**Comment by xugaoxiang** [comment]
请问下现在是什么情况了？

**Comment by CHxCOOH** [comment]
想开issue，发现这个问题已经提了三次了，理论上qt对webp的支持不存在问题，希望尽快～

**Comment by Limourli-liu** [comment]
> 想开issue，发现这个问题已经提了三次了，理论上qt对webp的支持不存在问题，希望尽快～

[ShareX + imagemagick](https://x.limour.top/WEBP-jie-tu-gong-ju-ShareX--imagemagick) 曲线救国😏

**Comment by mzihen** [comment]
现在webp用的很广泛了，同样的画质文件量更小，希望能尽快添加进去。

**Comment by liulex** [comment]
下个版本 2.8.6 就会支持了。
