### ISSUE TITLE
文字颜色及不透明度可以单独存储吗?

### ISSUE THREAD

**Issue by BianChengNan** [Snipaste/feedback#879]
有几个feature,请考虑下
1. 颜色配置对每一个都有独立的配置,因为会记住用户上次的选择,所以不会有大问题,反而更灵活.比如下图
![default](https://user-images.githubusercontent.com/5259514/39026871-e61ea104-4481-11e8-9df1-55cce7a232ac.png)

2. 延时截图的超时设定限制,现在最大是10秒,有些情况下可能不太合适.能否去掉这种限制,或者放宽一些.个人觉得没必要做这种限制. 同样的还有笔宽的设定,希望也能放宽,或去除.

3. mark pen是否可以随意画? 用户想自由的高亮某个区域的时候会比较有用
![default](https://user-images.githubusercontent.com/5259514/39026963-4c6c9092-4482-11e8-910a-45fa5acc8c31.png)

**Comment by liulex** [comment]
1. #827

2. 谢谢建议，已放宽限制到 60s.

3. 马克笔如果可以随意画，那和画笔工具还有什么区别呢？画笔工具同样可以指定半透明颜色当作马克笔用。

**Comment by StarryVoid** [comment]
此功能已支持，建议关闭 issues
画笔可以调整透明度间接达到伪马克笔效果
