### ISSUE TITLE
Feature request - Editing existing screenshots

### ISSUE THREAD

**Issue by Co-ords** [Snipaste/feedback#883]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* The ability to edit existing images/saved screenshots would be outstanding. Sometimes it handy to be able to open a previosly made screenshot, to be able to add an after effect that was not thought of at the time op creating the screenshot, or that the screenshot was made by another tool or on another device for example a mobile device (iPhone) etc. 

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by Kaedin** [comment]
Thumbs up also for this excellent request!
In addition, I would like to add a critical feature missing from screenshot editor:

- It is not possible to edit any graphical objects once they're placed and selection has been lost! -> **Please, at minimum implement a possibility to edit graphical objects which have been added during the current editing session**

Thanks in advance!

**Comment by Kaedin** [comment]
@liulex Nice to hear! I will definitely be interested about the upcoming Pro version. Would you possibly have any ETA at the moment?

**Comment by liulex** [comment]
@Kaedin It's really hard to tell... But I would say weeks. 😅
