### ISSUE TITLE
Feature request - add option to disable magnifier

### ISSUE THREAD

**Issue by Weafyr** [Snipaste/feedback#885]
Feature request
In office we have all started using this great app, but one of our colleague don't like magnifier.
Can you please add option to disable magnifier?
Thanks!

**Comment by liulex** [comment]
More options will be available for the magnifier in the coming Pro version, including the option to disable it.

![snipaste_2018-05-03_17-14-18](https://user-images.githubusercontent.com/2010459/39568638-702bd2d6-4ef5-11e8-9964-96a77db340f3.png)

**Comment by Dave3848** [comment]
This option is now gone? 😨
