### ISSUE TITLE
新功能请求：标注序号

### ISSUE THREAD

**Issue by wanlihong** [Snipaste/feedback#887]
截图经常是要标注操作步骤，如果可以增加一个标注序号：圆圈+数字，截图效果就更好了。

**Comment by whaohao15463** [comment]
![222](https://user-images.githubusercontent.com/35392271/42252980-0f4f246a-7f72-11e8-9454-35491a91c620.jpg)
 类似这样

**Comment by karsion** [comment]
emmm，这个很使用，Greenshoot的编辑是有这个功能的，建议增加

**Comment by karsion** [comment]
emmm，这个功能是很实用的，请求增加（注：Greenshoot的编辑是有这个功能的）

**Comment by septs** [comment]
请合并至 #227 继续该话题
