### ISSUE TITLE
希望加入“重复上次截取区域”的功能

### ISSUE THREAD

**Issue by wer5lcy** [Snipaste/feedback#891]
请求新功能：
* 希望加入“重复上次截取”的功能，即按照上一次截图的截取范围再次进行截图；并且，这个功能需要有一个可自行绑定快捷键。
* 这一功能的后续（自动复制到剪贴板、自动保存）可以不固定，只需要能够自动切换到上一次的矩形范围即可。
* 应用场景：有限元软件后处理过程中，会对同一个位置的N个工况连续进行图像输出，然后另存，或在剪贴板中直接粘贴到Word里。当软件能够保持截取范围时，获得的图像是对齐的。由于软件的窗口空白区域太多，往往在第一次需要手动选取一个矩形的范围，不然如按窗口进行截图，后期需要批量裁剪，更费工夫。
* 我是从PicPick软件切换过来的，这是我最依赖PicPick的一个功能，但它在Win10 1703的某个更新后会复制粘贴会持续崩溃。Snippaste的自带编辑功能非常实用，感谢作者持续更新~！

**Comment by StarryVoid** [comment]
@wer5lcy 有这个功能，windows版默认R键，谢谢

**Comment by wer5lcy** [comment]
哦哦  原来是这样，谢谢~！
那这个问题可以关闭了。
---
我之前没有发现这块说明在“首选项”-“快捷键”-“内置快捷键”里。
因为“全局快捷键”和我的专业软件冲突，默认值我都清理掉了，就没有进入下面的入口。
