### ISSUE TITLE
Feature request: Advanced Key Bindings

### ISSUE THREAD

**Issue by Kaedin** [Snipaste/feedback#892]
**Feature request: Advanced Key Bindings**

Minimum: Add a Snip only Key Binding for "Set the snipping area to **full window**"
- It is sometimes hard to set the snipping area to full window of an application, e.g. File Explorer, because Snipaste is snipping to toolbars and individual action icons. This hotkey, for example "A", would allow user to swiftly lock snipping to capture targeted full window instead of snapping to individual elements inside of a window.

Maximum: Allow user to customize Key Bindings. Also add a button to restore recommended defaults.

**Comment by liulex** [comment]
Press <kbd>Tab</kbd>. See [here](https://docs.snipaste.com/key-bindings).
