### ISSUE TITLE
1箭头类型和2文字加粗与描边不能自动记忆，另：快捷键增强建议

### ISSUE THREAD

**Issue by moonhuahua** [Snipaste/feedback#896]
1箭头类型和2文字加粗与描边不能自动记忆，在另外的截图里面就恢复原始的了，选项里面也没这个设置。

快捷键增强建议如下：：
![1](https://user-images.githubusercontent.com/15684037/40226532-7cf4cb6a-5abe-11e8-8ad1-e32eb58c7b01.gif)

**Comment by StarryVoid** [comment]
@moonhuahua 截图记忆和贴图记忆分开的。

**Comment by moonhuahua** [comment]
@StarryVoid 谢谢，测试截图的确没问题，但贴图时，是不能记忆的，你的贴图可以记忆吗，谢谢

**Comment by liulex** [comment]
https://github.com/Snipaste/feedback/issues/420#issuecomment-294103121
