### ISSUE TITLE
win7自启间歇性失败

### ISSUE THREAD

**Issue by asian2017** [Snipaste/feedback#897]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282
,
不知是第几次要手动找到安装目录来启动它了,至少6次,
虽然不是很清楚为什么借助别的exe来执行启动,但是杀毒软件和防火墙都没拦截,还是不会自启,

C:\Windows\System32\schtasks.exe /run /tn "Snipaste (Run As Admin) @28BC"
.
对比一下另一个一直在用的networx的启动方式,一次设置,永久正常
"D:\XiTong\networx\64-bit\networx.exe" /auto

.
.===不过,当我删了1.16,解压出1.15,然后在首选项,
取消了以管理员方式,之后启动又正常了
.
.
.
发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by Genteure** [comment]
@asian2017 如果同时选择 开机启动 和 以管理员身份 就会这样启动。
划重点：以管理员身份
