### ISSUE TITLE
How to take another snip with the same area as previous snip?

### ISSUE THREAD

**Issue by raindropsfromsky** [Snipaste/feedback#902]
Hi

The help doc mentions that R sets the snip area to the last successful snip. 
However, it does not specify what are the options for the next operation.

Logically, there are two different options:
1. Take another snap of the same area once again.
2. Copy the HxW dimensions of the last snip, and let the user capture that area anywhere on screen.

The first is useful if we want to capture a slideshow (for example). Just go to the next slide and snip again.

The second method is useful if we want to capture the buttons of a toolbar: they are same size. 
Therefore we have to set the size only one. Then point to the next buttons and snap them one by one.

The help documentation does not explain if such features are there...

BTW I tried using the R hotkey, after taking a snip. 
But after that, when I tried to take the next snip, Snipaste does not remember that last capture size.

**Comment by liulex** [comment]
Sorry for the late response...
You are not supposed to press the <kbd>R</kbd> key after taking a snip. You shall press <kbd>R</kbd> right after you start a new snip, i.e. after pressing <kbd>F1</kbd>, then press <kbd>R</kbd>. The snip area will be set to the last area you take. You are free to decide whether to take the same area again, or move the area to another position.

**Comment by raindropsfromsky** [comment]
I think this hint is not available to the user.
A tip should be provided, just like how a tip says that the user can capture color by pressing C.

**Comment by liulex** [comment]
You are right. I will find a way to add such tips.

**Comment by liulex** [comment]
Tips has been added in Snipaste 2.5.
