### ISSUE TITLE
【贴图缩放问题】如果关闭了使用鼠标进行缩放，就不能用键盘的快捷键缩放了

### ISSUE THREAD

**Issue by kukuhuihao** [Snipaste/feedback#903]
https://ws4.sinaimg.cn/large/006tKfTcgy1frtlf48xlwj30zi0p2jt3.jpg
https://ws3.sinaimg.cn/large/006tKfTcgy1frtlhge23mj315q0usmyc.jpg

如果关闭了使用鼠标进行缩放，就不能用键盘的快捷键缩放了，这个能解决吗？因为平时我是用触控板的，开了鼠标缩放后会出发双指缩放 经常和三指移动冲突，所以需要关掉。

**Comment by liulex** [comment]
这个和你关闭鼠标缩放没关系啦，贴图快捷键缩放无效是个 bug，会在[下版本](https://github.com/Snipaste/feedback/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97)修复。
