### ISSUE TITLE
How can I set history path to `C:\Users\xxx\AppData\Local`, that xxx here can be replaced by current username. 

### ISSUE THREAD

**Issue by TYZRPVX** [Snipaste/feedback#904]
How can I set history path to `C:\Users\xxx\AppData\Local`, that xxx here can be replaced by current username. 

![image](https://user-images.githubusercontent.com/7645818/40757534-8d5d6636-64bb-11e8-8c64-4756ca01b410.png)

**Comment by liulex** [comment]
history_dir=%LOCALAPPDATA%

or

history_dir=C:\Users\%USERNAME%\AppData\Local
