### ISSUE TITLE
什么时候增加滚动截屏？

### ISSUE THREAD

**Issue by ghost** [Snipaste/feedback#905]
什么时候可以增加滚动截屏功能啊，加上这个基本上就完美了

**Comment by ernsky** [comment]
这个很实用。。。

**Comment by yu13740000** [comment]
滚动截屏确实很实用，目前浏览器加插件，插件过多影响浏览器的流畅性，如果这软件带滚动截屏，带来的便捷性不言而喻，任何电脑只要下载这软件立刻就能使用，也不用去到处找插件安装了。但是尊重作者的决定，估计难度也挺大。

**Comment by Rictusempra** [comment]
@yu13740000 那么 可以考虑F12的截屏或者Firefox内置的截图
如果希望这个软件实现 不装扩展也是不可能的

**Comment by eione-github** [comment]
能在一个软件上实现基本上常用的功能是最好不过了，不然还要装其他软件，有些功能还重复的

**Comment by EricFy** [comment]
@Rictusempra 参考mac上一个Xnip的app，可以手动滚动截屏，也是十分的方便啊

**Comment by Loftrina** [comment]
@Rictusempra 我刚想提出一个增加识别网页内容的功能的请求，看到这句还是算了

**Comment by nizongdai** [comment]
滚动截屏好像都是要在浏览器上装插件才可以

**Comment by zxh326** [comment]
关于滚屏截屏支持讨论 #19
