### ISSUE TITLE
贴的图与任务栏有重合，任务栏区域闪烁

### ISSUE THREAD

**Issue by endimirion** [Snipaste/feedback#908]
贴了一张图，把贴图移动，使之覆盖到任务栏上，会出现任务栏和贴图交替置顶的情况，现象为任务栏闪烁

电脑环境：
win10 x64
版本1.16.2

**Comment by StarryVoid** [comment]
有GIF么？没有复现成功
贴图移动时默认不覆盖在任务栏上，只有鼠标点击后才会覆盖在任务栏
以及你是否存在程序在不停地激活任务栏?

**Comment by endimirion** [comment]
我这边贴图默认覆盖在任务栏上的，其他程序都是直接被任务栏覆盖。没有装特别的软件会频繁激活任务栏
[视频地址](http://47.98.140.191:8080/pics/snipasteflash.mp4)
