### ISSUE TITLE
不知道能否实现截取图片背景透明？

### ISSUE THREAD

**Issue by yu13740000** [Snipaste/feedback#909]
![xw5 qgzsodu i2qcnd8s0o](https://user-images.githubusercontent.com/39992903/41041614-1b8e2fce-69d2-11e8-976e-3593e1c01b09.png)
# 这只是制作一个图片样例，实际使用场景不一定全是这样的，这样的截图实例可以通过其他软件能实现背景透明编辑，当然比较繁琐，需要截图保存到软件中再编辑，所以还是喜欢作者软件截图的便捷性，现实使用中，多次截图钉图重合后再截图，如果能有这个背景透明功能觉得很好用，更加便捷、高效率！背景可以通过拾取单色颜色背景来选择。

**Comment by StarryVoid** [comment]
png背景通道颜色也已经在Pro版支持调整。

**Comment by liulex** [comment]
抱歉，无法实现。
