### ISSUE TITLE
希望截图中的标注的图形、箭头、线段可以反复编辑

### ISSUE THREAD

**Issue by Townjack** [Snipaste/feedback#911]
1.目前发现在截图中标注的文本框编辑完成右键退出编辑后，可以再次点选文字进行编辑，但是图形或者箭头不能反复编辑
2.箭头、图形是否也可以实现标注完成后，可以灵活多次选择进入编辑
谢谢！

**Comment by NJingZYuan** [comment]
> 1.目前发现在截图中标注的文本框编辑完成右键退出编辑后，可以再次点选文字进行编辑，但是图形或者箭头不能反复编辑
> 2.箭头，图形是否也可以实现标注完成后，可以灵活多次展示进入选择编辑
> 谢谢！

再建议一个功能，如果能实现，将会很完美：
除了以上两个增加功能的建议外
3.建议在绘制箭头、图形、文字时能够自动追踪已绘制的以上元素，这样可以作为参照，方便对齐。目前好像没有这个功能，文字、图框等不容易对齐；谢谢！

**Comment by liulex** [comment]
@Townjack 这是专业版功能..
