### ISSUE TITLE
mac版本只截图不复制失效

### ISSUE THREAD

**Issue by allonli** [Snipaste/feedback#912]
已经设置只截屏不复制，但是它会自动做类似回车的确认操作。我不能进行标记。而且剪贴板中也没有内容。我录了一段小视频，这是录屏的文件：[录屏.zip](https://github.com/Snipaste/feedback/files/2087096/default.zip)

![image](https://user-images.githubusercontent.com/3733955/41193470-b8fc7572-6c3e-11e8-9f4b-28701622128c.png)

**Comment by liulex** [comment]
截图结束时有一个音效，是你在自定义的截图音效么？
另外，如果是执行截图并复制，剪贴板里会有内容吗？
