### ISSUE TITLE
希望增加贴图置顶、置底、上移一层和下移一层的贴图排序功能。

### ISSUE THREAD

**Issue by thomason-gh** [Snipaste/feedback#913]
Feature request?
* Wish a function that made a paste go top, go bottom, go up or go down a layer.

---

请求新功能？
* 希望增加贴图置顶、置底、上移一层和下移一层的贴图排序功能。
这一功能可以增加到在贴图上单击右键出现的菜单中。这个功能在屏幕上出现多个贴图时是很必要的，正常情况下鼠标一点一个贴图它就会置顶，如果它比较大就会盖住别的贴图，但如果我想让它作为背景呢，其它的贴图怎么再点也在它后面无法置顶。

**Comment by feijie825** [comment]
“贴图排序”的确是一项非常有用的功能！
有时会截取多张图（并标注），然后需要从第一张截图开始查看。但是，最先截取的图处于最底层，这时就需要使用鼠标拖动一遍所有的截图。

**Comment by liulex** [comment]
贴图作为窗口，无法特定的层级关系。

**Comment by thomason-gh** [comment]
好吧，层级排序的功能有难度我承认，不追求了。但windows不同窗口之间不是还有个alt+tab键可以预览缩略图切换置顶窗口吗？类似的功能也应该有一个，否则多贴图操作实在不方便。

**Comment by thomason-gh** [comment]
#希望增加贴图循环置顶的功能。
好吧，层级排序的功能有难度我承认，不追求了。但windows不同窗口之间不是还有个alt+tab键可以预览缩略图切换置顶窗口吗？类似的功能我觉得应该有一个，否则多贴图操作实在不方便。
就是说当有一张大贴图在最上面，下面还有被盖住的小贴图时，采取某种方式能让后面的贴图循环置顶。帮助里似乎有缩略图功能，但我的1.16.2（64bit）win7版似乎调不出来，因此不能判断这个缩略图是否是实现这一功能的一个解决方式。
