### ISSUE TITLE
Please update quazip5.dll because is vulnerable.

### ISSUE THREAD

**Issue by Wizmann** [Snipaste/feedback#918]
Accrodding to [this][1], the quazip you are using is vulnerable and should be update immediately to avoid potential attack.

[1]: https://github.com/snyk/zip-slip-vulnerability

**Comment by liulex** [comment]
Thanks for the info. I will update quazip on next release.
Quazip is only used for extracting the update package downloaded from Snipaste's server, so this vulnerability does not affect Snipaste.
