### ISSUE TITLE
无任何操作的情况下，贴图数量自动以每秒一张的速度增加

### ISSUE THREAD

**Issue by igwen6w** [Snipaste/feedback#919]
无任何操作的情况下，贴图数量自动以每秒一张的速度增加，很快内存就干了；
系统：win10
软件：x64 v1.16.2

**Comment by nizongdai** [comment]
我估计应该是你的快捷键卡住了吧。。。

**Comment by StarryVoid** [comment]
可以发一下你的snipaste日志么？日志级别 跟踪

**Comment by StarryVoid** [comment]
新版本 V2.2 尚未发现该BUG，并且此issues时间有些太久了。
