### ISSUE TITLE
希望可以设置方框或圆等线条为虚线

### ISSUE THREAD

**Issue by rebude** [Snipaste/feedback#92]
希望可以设置方框或圆等线条为虚线

**Comment by liulex** [comment]
虚线、点线、点虚线，都加了之后也许还有用户要求虚线之间的间距可控……
所以，我个人觉得不是很有必要加呢，大家点赞投票吧。

**Comment by rebude** [comment]
确实虚线的分类比较多，你考虑的也没错。建议加个虚线的初衷是可以在排版设置截图时会更美观。个人觉得就设置一个虚线，然后加一个调整间距的（像马赛克调整模糊程度的进度条一样）就够了。当然这纯属个人意见，尊重你的决定。

**Comment by StarryVoid** [comment]
个人看法这个可加可不加，如果你想要虚线可以用透明度的线条。

**Comment by satcon** [comment]
画 实线矩形或圆时，边框上可不可以不显示灰色虚线

**Comment by XHXIAIEIN** [comment]
重新请求希望能增加虚线的设置(或是单独一个画笔工具)
在许多时候对于标注信息来说非常有用

例如这是某截图工具的虚线
![Snipaste_2021-04-08_20-09-01](https://user-images.githubusercontent.com/45864744/114024142-497f3a80-98a6-11eb-96f1-80b1cce510b6.jpg)

**Comment by liulex** [comment]
![Snipaste_2021-04-08_23-19-18](https://user-images.githubusercontent.com/2010459/114052892-07afbd80-98c1-11eb-979c-350c5fe65ecc.png)

**Comment by XHXIAIEIN** [comment]
nice ! 看到了！
![Snipaste_2021-04-08_23-25-50](https://user-images.githubusercontent.com/45864744/114053715-c966ce00-98c1-11eb-8c9a-5b5383823280.png)
