### ISSUE TITLE
snipaste截全屏的时候会卡一下

### ISSUE THREAD

**Issue by juzi214032** [Snipaste/feedback#921]
snipaste截全屏的时候会卡一下，才会截图成功

**Comment by juzi214032** [comment]
是在设置了自动保存的情况下回卡顿，如果关闭自动保存就不会卡顿

**Comment by StarryVoid** [comment]
可以附带一下log日志么？日志级别是跟踪。

**Comment by juzi214032** [comment]
已经发现原因了，是【图像质量】那里设置为了0，应该是压缩消耗的时间吧，我现在改为-1就不会卡顿了。设置为0的时候卡顿时间在1秒钟左右。应该不会是我电脑配置低吧，小米笔记本pro

**Comment by liulex** [comment]
@juzi214032 商店版 2.0.1 有修复自动保存/快速保存的卡顿问题~
