### ISSUE TITLE
截图时增加1、2、3、4这种步骤标识

### ISSUE THREAD

**Issue by iwsbiwy** [Snipaste/feedback#922]
像图中的蓝色数字一样，选择后，点击会按顺序生成。
![1](https://user-images.githubusercontent.com/40462471/42120859-389c9a34-7c55-11e8-9229-16c400e2001d.png)

**Comment by zyxk** [comment]
这个不错，尤其是做教程或指导别人使用软件时。

**Comment by whaohao15463** [comment]
![snipaste_2018-07-04_09-33-26](https://user-images.githubusercontent.com/35392271/42252778-ec372258-7f70-11e8-81e1-7f21c13a4f7e.jpg)
强烈赞同，我现在是截图后再用iphotodraw后期加数字序号，有点麻烦；强烈期望在snipaste中实现。

**Comment by heartacker** [comment]
这个可以。

![snipaste_2018-07-22_10-32-41](https://user-images.githubusercontent.com/1876302/43041700-9815563a-8d9a-11e8-84a2-167834d1bbf4.png)
可以直接在文字加一个圈圈模式、

**Comment by wskia161** [comment]
这个功能，需求的人应该相当多，可惜目前还没有一个工具把这个做好用的

**Comment by StarryVoid** [comment]
Duplicate of #877
