### ISSUE TITLE
增加一个添加边框的功能按钮

### ISSUE THREAD

**Issue by nizongdai** [Snipaste/feedback#923]
在我们进行截屏的时候，下面有一个小的工具栏，里面有一些按钮可以添加文字，图形等功能，是否可以在这里增加一个“加边框”的按钮呢，点击这个按钮，可以自动的给这个截图加上一个特定颜色的边框，2-3个像素即可。因为有些截图会用于放到ppt或者是word文件中制作一些操作说明，没有边框的话会容易和周围的内容混淆，我目前的操作方法是使用添加图形的办法添加一个方框在边上，但是这样操作起来比较费力，而且当使用笔记本的touchpad的时候，很难精准定位边框。

Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by StarryVoid** [comment]
首先文字是支持外附边框，但是边框宽度固定。
图形没有外附边框。
看作者情况吧，，个人感觉需求不是很大。。

**Comment by nizongdai** [comment]
因为很多时候截屏是需要黏贴在其他地方，截屏之后，底色是白的，其他的文档底色也是白的，如果没有边框，黏贴上去之后很容易和背景混淆。

**Comment by liulex** [comment]
先贴图，然后选矩形标注，然后右键贴图。
