### ISSUE TITLE
截屏贴到屏幕功能与Windows资源管理器右键严重冲突

### ISSUE THREAD

**Issue by DagonDD** [Snipaste/feedback#924]
当将截屏贴到屏幕上时，在Windows资源管理器的左侧目录菜单中右键单击目录，资源管理器会闪退

**Comment by StarryVoid** [comment]
可以详细介绍一下此故障的操作流程么？
没有复现成功、

**Comment by DagonDD** [comment]
emm好像没有这种情况了。这期间电脑装了虚拟机等各种软件以及重启，好像是没有这种问题了。谢谢;)
