### ISSUE TITLE
能不能增加取色器功能，对于非设计专业人员有时候想找配色真的很难

### ISSUE THREAD

**Issue by Pinnsvin** [Snipaste/feedback#925]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by IamXiaRui** [comment]
不是已经有了这个功能了吗？   

截图 ->  鼠标移动到想取色的地方  -> 按 C 复制颜色  -> 贴图查看所取颜色的各种值

**Comment by StarryVoid** [comment]
此功能已经有了。快捷键C是取色，取色后贴图即可显示颜色信息
请issues发布者自行关闭本issues
