### ISSUE TITLE
【严重影响功能】Mac 版本截图无法输入中文

### ISSUE THREAD

**Issue by IamXiaRui** [Snipaste/feedback#927]
**无论是搜狗输入法，还是系统自带的简体拼音输入法都无法输入中文**

[录制了一段视频](http://www.iamxiarui.com/wp-content/uploads/2018/07/QQ20180711-100551-HD.mp4)

* Snipaste 1.16.2-beta 版本
* macOS  Sierra 10.13.5 版本

已经查阅已有的 issue ，但发现并未解决

联系方式：QQ 956420744

**Comment by zgr0629** [comment]
同楼主，希望尽快修复。目前只能先复制，然后编辑的时候粘贴进去。

**Comment by zgr0629** [comment]
@IamXiaRui 看了一下已往的issues，发现有人说重启就会好，我试过，已解决，很神奇

**Comment by qxs7** [comment]
中文输入问题，在给 贴图 二次截图填完文字说明是 100% Bug 重现。

**Comment by libukai** [comment]
@qxs7 我也是一样，二次编辑100%重现

**Comment by xuoutput** [comment]
确实影响使用
