### ISSUE TITLE
无法抓取开启e10s（多进程）特性的Firefox窗口中的页面元素

### ISSUE THREAD

**Issue by pm2kjiagm** [Snipaste/feedback#928]
1. 环境：Windows 8.1 / Firefox (Waterfox) 56
2. 设置：Firefox开启了e10s（多进程浏览）
3. 状况：无法抓取开启了e10s的Firefox窗口中之界面元素，而未开启的窗口则可正常抓取
4. 复现：如以下视频所示
https://www.youtube.com/watch?v=B4Vwdbw9tVw

**Comment by liulex** [comment]
感谢你的描述。
元素检测依赖于 Accessibility 特性，我搜索了一下，似乎是 Firefox 的 e10s 和 Accessibility 有兼容问题，不能共存：
![snipaste_2018-07-13_00-55-00](https://user-images.githubusercontent.com/2010459/42647804-90025994-8637-11e8-85f1-fc17e1aed89b.png)

**Comment by pm2kjiagm** [comment]
收到，那看来这个是没太好的办法了。感谢2位。
