### ISSUE TITLE
【新功能请求】让屏幕贴图不会在所有桌面完全相同地出现

### ISSUE THREAD

**Issue by bluove** [Snipaste/feedback#930]
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它

![image](https://user-images.githubusercontent.com/38500778/42720752-fd0148ec-875f-11e8-98a3-bdf741f95886.png)
如图，当我贴一个图在屏幕上，其它的桌面也会出现完全相同的贴图。
1. 其它软件界面，都可以自由地在不同桌面移动，而且只会出现在同一个工作桌面下。Snipaste的贴图是否要遵从“win10多工作桌面的基本精神”更好呢？
2. 当我在第一个桌面处理文档类文件，贴了三张相关贴图A/B/C；在第二个工作桌面处理code工作，贴了三张贴图D/E/F。我希望A/B/C只出现在第一个工作桌面，D/E/F只出现在第二个工作桌面。
- 当然可以用贴图组来间接实现啦，但是每次切换工作桌面都要换一下贴图组，很麻烦的。而且，明明一张贴图，却要永久占据全部桌面，比独立软件界面还要厉害，这样感觉不太好。

【win10，64位，神州战神笔记本】

**Comment by StarryVoid** [comment]
这个的确有一定的需求。@liule

**Comment by YXH-YXH** [comment]
遇到同样的需求，准备提出，发现已有，来插个眼

**Comment by liulex** [comment]
2.2.2 专业版将支持。
