### ISSUE TITLE
关于快捷键设定的一点小bug。

### ISSUE THREAD

**Issue by nonozone** [Snipaste/feedback#931]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---
这个bug出现了好几次，好不容易才确定。

最近我把snipaste的截图键设定为PrtSc，鼠标穿透设定为 ！，对，一个感叹号，然后就出现以下问题：
1 每次重启，会提示PrtSc快捷键被占用，需要重新设定。但是设定的时候，并没有提示这个快捷键被占用。
2 每次设置！为鼠标传统快捷键之后，过一段时间，我的键盘就抠不出1这个数字了！但是感叹号可以。  这个问题出现了好几次，我还以为是自己的键盘坏了，以前要重启才可以。但是我刚刚又重新如此这般设置了快捷键，又无法输入1了。
我联想到刚刚设定了快捷键，才想到可能跟这个有关，于是我把snipaste的快捷键恢复默认，立马可以输入1了。

我的键盘是poker2，小键盘。

谢谢。软件不错，不过在windows10 64下，会偶尔崩溃。

**Comment by liulex** [comment]
1. <kbd>PrtSc</kbd> 的问题，应该是系统启动时有其他软件在 Snipaste 之前抢占了 <kbd>PrtSc</kbd> 了（比如 OneDrive），但它之后又释放掉了……所以表现是系统启动时 Snipaste 无法注册 <kbd>PrtSc</kbd> 但之后重新设定又可以注册。
2. <kbd>!</kbd> 的问题，确实是个 bug，下版本修复~

**Comment by liulex** [comment]
需要注意的是，bug 修复之后，如果你设了 <kbd>!</kbd>，那你也是任何时候都无法输入 <kbd>!</kbd> 这个符号的……

**Comment by cloudw233** [comment]
> 1. PrtSc 的问题，应该是系统启动时有其他软件在 Snipaste 之前抢占了 PrtSc 了（比如 OneDrive），但它之后又释放掉了……所以表现是系统启动时 Snipaste 无法注册 PrtSc 但之后重新设定又可以注册。
> 
>     2. ! 的问题，确实是个 bug，下版本修复~

感谢，原来是OneDrive的问题导致快捷键占用，解决了我的困惑
