### ISSUE TITLE
【新功能】Windows Ink支持

### ISSUE THREAD

**Issue by Bimos** [Snipaste/feedback#933]
windows ink是windows提供的一个触控笔的接口。surface等电脑的触控笔绘制都是通过它实现的。
不作特殊适配的情况下，surface pen的效果跟鼠标是一样的，因此现在在贴图上标注的时候，我需要首先点击画笔，然后用触控笔标注。标完以后，再点画笔取消。
希望能够支持这个接口，以适配触控笔。例如：

- 检测到笔尖自动切入画笔
- 检测到橡皮自动切入橡皮
- 笔尖/橡皮离开自动切回指针。
- 支持墨迹工具栏InkToolbar

当然，InkToolbar这东西我个人觉得不好用...

这里有一些资料。
https://docs.microsoft.com/zh-cn/windows/uwp/design/input/ink-walkthrough
https://github.com/Microsoft/Windows-tutorials-inputs-and-devices/tree/master/GettingStarted-Ink
我看了一下，QT对这个东西好像没有很好的支持，所以可能开发、测试的工作量还比较大。
这是一个基于Qt的项目加入了Windows Ink支持
https://drawpile.net/news/windows-ink-experimental/

**Comment by septs** [comment]
Replaced by #1261
