### ISSUE TITLE
【新功能请求】贴图同步到所有桌面 | image stay on all desktops

### ISSUE THREAD

**Issue by iYukai** [Snipaste/feedback#934]
希望**mac OS**版能增加一个允许“贴图固定在所有桌面”的选项，即即使切换桌面也不需要重新调出贴图。
——
I hope that **mac OS version** can add one option that allows "image stay on all desktops". that is, even if I switch desktops, I don't need to recall the image.

**Comment by StarryVoid** [comment]
建议issues发布者写一下是mac版本。。
windows版本已经有鼠标穿透了。

**Comment by AzazelX5** [comment]
这个功能是不是已经实现了？  现在贴图会贴到所有桌面，能否添加一个开关，只贴到当前桌面，有时候并不希望贴到所有桌面。或者能拖动到其它桌面也行。

**Comment by septs** [comment]
@AzazelX5  https://github.com/Snipaste/feedback/issues/934#issuecomment-514473874 请合并到 #930 讨论
