### ISSUE TITLE
Excel調整欄寬時截圖,螢幕涷結不能使用系統

### ISSUE THREAD

**Issue by zach14c** [Snipaste/feedback#936]
发现了 bug？
Steps to reproduce:
1. Open Excel
2. 拖曳欄與欄之間的seperator, 按 F1 截圖
3. 螢幕涷結
![snipaste-excel-dragcolumn-freeze](https://user-images.githubusercontent.com/4789373/42857794-0bae97c0-8a7e-11e8-984c-fa446b33c051.png)

**Comment by StarryVoid** [comment]
@zach14c office365复现成功，并且是snipaste独有。

**Comment by liulex** [comment]
2.0 版已修复。
