### ISSUE TITLE
【bug反馈】win7 贴图功能

### ISSUE THREAD

**Issue by Airmour** [Snipaste/feedback#939]
### 复现步骤
1. 选中图片`Ctrl + C `复制图片，按`F3`贴图，双击销毁贴图。
2. 右键图片 > 编辑 > 裁剪图片，`Ctrl + S `保存图片，关闭画图。
3. 然后重复步骤1 ，bug出现，贴出的图片还是修改前的图片
### 临时解决办法
* 重命名图片

**Comment by liulex** [comment]
双击只是关闭贴图，销毁是 <kbd>Shift</kbd> + <kbd>Esc</kbd> 或右键菜单选销毁。
销毁再贴出就不会取到旧图片了。
