### ISSUE TITLE
【新功能请求】希望增加surface pen快捷键的支持

### ISSUE THREAD

**Issue by patrickwangqy** [Snipaste/feedback#940]
比如按下surface上面的按钮可以进入截屏状态

**Comment by WenLexiao** [comment]
surface pen 按键的接口都没有开放吧，无法支持的。
不过笔的按钮可以设置为打开 .exe应用，所以可以编译一个 .exe程序，发送相应的截图快捷键就可以了。
我也有这个需求，所以刚用 autohotkey 编译了相应的程序，需要的话可以联系我。

**Comment by patrickwangqy** [comment]
可以呀，请提供下这个工具，谢谢

**Comment by WenLexiao** [comment]
[发送相应快捷键.zip](https://github.com/Snipaste/feedback/files/2299062/default.zip)
![snipaste_2018-08-18_09-55-30](https://user-images.githubusercontent.com/25920332/44294642-f8714100-a2cc-11e8-89a0-858a706acf82.png)

**Comment by patrickwangqy** [comment]
谢谢大佬

**Comment by KazamaSion** [comment]
解决步骤：
1. 创建一个快捷键，设置目标和启动目录如下（以商店版为例，桌面版可自行修改路径）
- Target: `%LOCALAPPDATA%\Microsoft\WindowsApps\Snipaste.exe snip`
  - 不要遗漏最后的`(空格) snip`
- Start in: `%LOCALAPPDATA%\Microsoft\WindowsApps`
2. 进入笔设置项，选择“启动经典应用”，然后指定刚才的那个快捷键
3. 完成

完成设置后就不要移动或更名快捷键了，不然会失效的。
注：该特性需要 Snipaste 2.x 及其以上版本中的“[命令行](https://docs.snipaste.com/zh-cn/command-line-options)”特性。
