### ISSUE TITLE
【新功能请求】截图后自动贴图 Auto paste after snipped

### ISSUE THREAD

**Issue by kailoke** [Snipaste/feedback#941]
需求：
         我想一键截图后，贴图自动出现在截图区域，就像stuna一样
使用场景：
         我的大量使用场景均是截图后立即需要贴图出现屏幕上，现在没有设置可以满足需求
建议：
![image](https://user-images.githubusercontent.com/38420687/43240688-4996dcf8-90ca-11e8-9cae-9011d7cccae2.png)
1.全局快捷键新增操作方式：截图后自动贴图
2.使用快捷键后，进入截图模式，截图完成后自动进行贴图

**Comment by liulex** [comment]
专业版满足你：
![snipaste_2018-07-26_23-33-20](https://user-images.githubusercontent.com/2010459/43272359-5dc2194c-912c-11e8-8c09-76bbadd37da1.png)
或
![](https://user-images.githubusercontent.com/2010459/42233899-69930c36-7f25-11e8-8938-ff27f4595014.png)

**Comment by lyqflnh** [comment]
mac版需求加1, 这样就可以完全替代snappy了.
