### ISSUE TITLE
超级截图能不能增加“截屏”功能。

### ISSUE THREAD

**Issue by ulpyuxa** [Snipaste/feedback#943]
超级截图后，希望能再调整选框的大小。所以看能否增加截屏功能。现在的超级截图只有截屏并贴图，截屏并复制两个功能。

**Comment by StarryVoid** [comment]
可以直接使用自定义截图
如果需要自定义截图然后自动贴图，你可以使用添加新命令手动做一个命令出来然后敷于快捷键

**Comment by septs** [comment]
See #1085
