### ISSUE TITLE
[Bug report] 触发角与超级截屏

### ISSUE THREAD

**Issue by sankoshine** [Snipaste/feedback#944]
专业版中，触发角不启用的情况下，超级截屏的快捷键「Win+鼠标左键拖拽」失效。

不清楚这是 bug 还是 feature。

**Comment by StarryVoid** [comment]
@sankoshine 此Bug已修复，请等待下个版本

**Comment by liulex** [comment]
2.0.1 [已修复](https://github.com/Snipaste/feedback/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97)，商店正在审核中。
