### ISSUE TITLE
[Bug Report] ` (backtick) to toggle cursor does not work on non-US keyboard layout

### ISSUE THREAD

**Issue by pedrogarcia** [Snipaste/feedback#945]
The shortcut key to toggle cursor is in a different location in non US Keyboards (such as the Brazilian ABNT2 layout, which is the default in my country, for example). 

In versions before 2.0 It worked by pressing shift+` multiple times, which is how you type this symbol on the keyboard, but now it does not work anymore.

Please, provide a way to change the cursor toggling shortcut or change the default shortcut to a more international friendly shortcut. 

Thanks.

**Comment by liulex** [comment]
You can also use <kbd>!</kbd>.

**Comment by pedrogarcia** [comment]
That works. 

It would be helpful to have it showing in the hover menu as well. 
Barring this, the issue can be closed. 


![snipaste_2018-07-27_23-02-06](https://user-images.githubusercontent.com/2473545/43351952-2ab7dbde-91f1-11e8-8150-a05bbd0235b3.png)

**Comment by liulex** [comment]
Thanks for point it out. I will improve the hover tip.
