### ISSUE TITLE
【新功能请求】希望能增加禁用其它快捷键的快捷键

### ISSUE THREAD

**Issue by LostAkiba** [Snipaste/feedback#947]
目前正在使用的一些软件的内置快捷键会与Snipaste的产生冲突。而用鼠标去托盘区禁用快捷键始终感觉不太方便呢……

**Comment by liulex** [comment]
专业版支持：
![snipaste_2018-07-30_21-38-38](https://user-images.githubusercontent.com/2010459/43400678-ee84f94c-9440-11e8-8d9b-f347feef367b.png)
