### ISSUE TITLE
【问题】Mac上用触控板缩放贴图太过灵敏

### ISSUE THREAD

**Issue by Emrys365** [Snipaste/feedback#951]
如图，在使用触控板缩小贴图的时候，图片大小会有一些的回弹，而且稍微滑动一点就缩放比较剧烈。

![pic.gif](https://i.loli.net/2018/08/04/5b6543c50c542.gif)
----
系统版本：High Sierra 10.13.6
软件版本：1.16.2-Beta

**Comment by ZhaoDingfan** [comment]
是的我也想report这个问题，我的问题是图片缩放过于灵敏并且在触控板上进行缩小操作的时候会不受控制地变大。
