### ISSUE TITLE
2.0的桌面版大概要什么时候可以推出，需要管理员权限启动

### ISSUE THREAD

**Issue by yym0924** [Snipaste/feedback#954]
有些窗口只能管理员权限运行的Snipaste才方便截
商店版没办法设置以管理员权限启动

**Comment by StarryVoid** [comment]
2020年之前。。具体根据作者抽取时间把加密授权模块写好的时间决定🌚
你可以做个计划任务，然后手动管理员模式启动

**Comment by yym0924** [comment]
@StarryVoid 计划任务这个只能用在桌面版上，商店版我试了没法弄……

**Comment by Riajyuu** [comment]
@yym0924 使用listary等带有explorer hook的软件检索给出路径即可

**Comment by yym0924** [comment]
@Riajyuu 我知道的，不可以的，商店的即使找到了对应的可执行文件也没法通过计划任务执行。运行结果会显示拒绝访问的。

**Comment by liulex** [comment]
即将更新的 2.1.1 会支持商店版以管理员权限开机启动~ :rose:

**Comment by yym0924** [comment]
![image](https://user-images.githubusercontent.com/23615020/47142119-c6905100-d2f4-11e8-9906-b0cefe03687a.png)
![image](https://user-images.githubusercontent.com/23615020/47142496-91d0c980-d2f5-11e8-89bd-62d91eccc25b.png)
![image](https://user-images.githubusercontent.com/23615020/47142538-a8772080-d2f5-11e8-9e81-59431eb88e73.png)


@liulex

**Comment by liulex** [comment]
谢谢及时的反馈！真的有问题，待我今晚回去再更一版……\_(:з」∠)\_

**Comment by liulex** [comment]
@yym0924 再次更新试一下~

**Comment by yym0924** [comment]
> @yym0924 再次更新试一下~

嗯嗯，可以啦！😄
