### ISSUE TITLE
#希望增加贴图循环置顶的功能。

### ISSUE THREAD

**Issue by thomason-gh** [Snipaste/feedback#956]
请求新功能？

#希望增加贴图循环置顶的功能。
参考已关闭问题＃913
好吧，层级排序的功能有难度我承认，不追求了。但windows不同窗口之间不是还有个alt+tab键可以预览缩略图切换置顶窗口吗？类似的功能我觉得应该有一个，否则多贴图操作实在不方便。

就是说当有一张大贴图在最上面，下面还有被盖住的小贴图时，采取某种方式能让后面的贴图循环置顶。

而现在没有这个功能时，就只能把大贴图移位，亮出小贴图再点击小贴图，置顶，把小贴图移到大贴图上面相应位置，再截图，如有其它小贴图，再重复多次，非常麻烦。

帮助里似乎有缩略图功能，但我的1.16.2（64bit）win7版似乎调不出来，因此不能判断这个缩略图是否是实现这一功能的一个解决方式。

**Comment by StarryVoid** [comment]
缩略图能实现你所需要的功能，将图片缩小后就能看到小贴图了。唯一可能就是你多层覆盖的时候需要一张一张缩略图
在 首选项 控制 能修改缩略图的快捷键。

**Comment by liulex** [comment]
我平时大量使用贴图，不觉得循环置顶这个能帮到我什么。
Windows 的窗口无法赋予其具体的层级，只有置底/置顶/普通，除非将所有贴图聚集到一个窗口中，如 [PureRef](https://www.pureref.com/) 这个软件。如果你常常对贴图进行排序的需求，它应该更适合你。

如果想在 Snipaste 将被大贴图挡住的小贴图显出出来，可以用专业版对指定贴图取消”保持最上“的功能，这时候会给贴图窗口关联任务栏图标，方便激活任意贴图：
![default](https://user-images.githubusercontent.com/2010459/46908255-e6b9bc00-cf52-11e8-9df4-8e85e8f2971b.png)
