### ISSUE TITLE
截图中方框的边框太细了可否加粗

### ISSUE THREAD

**Issue by 345161974** [Snipaste/feedback#958]
如下是QQ截图的方框边框：

![qq 20180815102358](https://user-images.githubusercontent.com/3973297/44128394-58b26daa-a075-11e8-8bc2-0888f8ab6e0d.png)

然后下面是Snipaste的方框效果：

![snipaste_2018-08-15_10-24-31](https://user-images.githubusercontent.com/3973297/44128412-6b472b0e-a075-11e8-870d-cd7c9677c4e8.jpg)

能不能提供一个粗细的设置项啊？否则看着太细了。

**Comment by Dy64** [comment]
![20180817211624](https://user-images.githubusercontent.com/35034348/44268050-f07cb700-a262-11e8-8c6e-7f36c90d0e5f.png)

**Comment by StarryVoid** [comment]
普通版可以按1或2调整笔画粗细，并且用滚轮也可以调整笔画粗细
专业版支持更多的默认笔画粗细。

**Comment by RandyCh** [comment]
需要按著ctrl鍵滑動滾輪 調整筆觸大小
