### ISSUE TITLE
MacOS F1截图后直接粘贴到微信聊天框体积过大

### ISSUE THREAD

**Issue by moqimoqidea** [Snipaste/feedback#959]
1. 经测试微信截图和 MacBook 自带截图全屏截图后直接粘贴到微信聊天框大概 200K 左右，而 Snipaste F1 截图为30M 左右。
2. 输出的图片质量怎么设置？ 1 表示自动设置，0 表示最低质量，100 表示最高质量。设定此参数为 0，未有改善。

**Comment by TTTPOB** [comment]
@moqimoqidea 等修复吧粘进去的是tiff格式，目前好像无解，然后你搜一搜这个issue好像有人提过了

**Comment by moqimoqidea** [comment]
嗯，我看到上一个人提到回复说是格式的问题。我这次也就补充完整数据。如果重复的话可以关掉我这个 issue ，麻烦了。

**Comment by TTTPOB** [comment]
@moqimoqidea 我不是管理员啦看到有闲回一下。。。作者好像说近期会更新mac版
