### ISSUE TITLE
把文字和图片混合复制,再粘贴成图片以后,背复制的图片会重复出现2次

### ISSUE THREAD

**Issue by SayoYuuki** [Snipaste/feedback#960]
**复制:**
![snipaste_2018-08-17_14-51-19](https://user-images.githubusercontent.com/42461987/44252013-37e85080-a22d-11e8-9c6a-4fc9b9342d2f.png)

**粘贴成图片以后:**
![snipaste_2018-08-17_14-51-23](https://user-images.githubusercontent.com/42461987/44252017-3d459b00-a22d-11e8-8dc7-2e2d080e66c5.png)

**Comment by StarryVoid** [comment]
![11](https://user-images.githubusercontent.com/20756365/44378086-4044d200-a532-11e8-8d32-9536b19d36bb.jpg)
没能复现成功。
