### ISSUE TITLE
截图模式下按ctrl暂时改变鼠标速度

### ISSUE THREAD

**Issue by 11zi** [Snipaste/feedback#962]
* 在截图的时候常常想要精准的拉取到某个像素点上  
* 但是此时识别不出页面元素, 鼠标速度又太快

![image](https://user-images.githubusercontent.com/28333452/44318330-eaa3f300-a467-11e8-8131-80ca98d4d325.png)

但是我注意到这个时候按ctrl没有任何效果!  
也就是说....能不能添加"在按ctrl的时候减缓鼠标速度"这个功能...

**Comment by TTTPOB** [comment]
@11zi WASD可以像素级移动不妨一试
