### ISSUE TITLE
获取颜色代码,能改成#FF0000的方式吗?  RGB 不方便.

### ISSUE THREAD

**Issue by eluotao** [Snipaste/feedback#963]
我经常用到获取颜色代码,每次都要装两个软件,因为截图这个颜色获取 基本对我是摆设..
获取到的都是RGB   并不是想要的#开头的颜色代码.

希望作者尽快更新.

**Comment by StarryVoid** [comment]
@eluotao 请自己按C获取到颜色后 按下贴图键贴出。

**Comment by eluotao** [comment]
并不能复制  没有C方便.  只能对照着自己再打出来.

**Comment by StarryVoid** [comment]
@eluotao 你大概是不会在新贴图上右键 复制FF0000么？

**Comment by eluotao** [comment]
知道了  多谢 终于搞懂了.

**Comment by StarryVoid** [comment]
@StarryVoid 如果还是想懒一下，专业版支持你一键获取hex🌚

**Comment by liulex** [comment]
额。。首选项里设置一下就好了，不用先贴图，也不用专业版。

**Comment by eluotao** [comment]
确实可以.
