### ISSUE TITLE
Win10系统下全局快捷键f1没有反应

### ISSUE THREAD

**Issue by llilililin** [Snipaste/feedback#965]
戴尔按fn＋f1没法截图

**Comment by llilililin** [comment]
因为键盘f1-f12同时要控制亮度和音量
加fn才是f1，之前可以用，但是今天试了一直不行

2018-08-25 

yolin_492 



发件人：Sion Kazama <notifications@github.com>
发送时间：2018-08-25 16:00
主题：Re: [Snipaste/feedback] Win10系统下全局快捷键f1没有反应 (#965)
收件人："Snipaste/feedback"<feedback@noreply.github.com>
抄送："llilililin"<yolin_492@163.com>,"Mention"<mention@noreply.github.com>

@llilililin 你为什么要按 fn 呢。

**Comment by llilililin** [comment]
emmmmm，退出虚拟机就可以截图了

**Comment by liulex** [comment]
部分窗口不响应快捷键是管理员权限问题吧：https://docs.snipaste.com/zh-cn/troubleshooting
