### ISSUE TITLE
为什么官网打不开了，还能在哪里下载

### ISSUE THREAD

**Issue by csupidan** [Snipaste/feedback#968]
官网打不开，有其他的下载链接吗

**Comment by StarryVoid** [comment]
@csupidan 如果是微软可以下载微软商店版

**Comment by MandyCh** [comment]
我是在360软件管家里面下载的

**Comment by KazamaSion** [comment]
任何第三方下载源是不能保证内容有无被篡改的。

**Comment by StarryVoid** [comment]
@MandyCh 请稍微从官网下载，不要使用**软件助手**软件管家之类等其他下载点

**Comment by 3473664996** [comment]
在吗 官网又 GG 了 502 好像是网关无了

**Comment by stevenzhu25** [comment]
> 在吗 官网又 GG 了 502 好像是网关无了

海外没问题
