### ISSUE TITLE
保存的文件名乱码

### ISSUE THREAD

**Issue by zongsheng-zhao** [Snipaste/feedback#969]
保存的文件名是乱码
![image](https://user-images.githubusercontent.com/23008201/44697499-9b387500-aaae-11e8-8a74-311407ffff34.png)
![image](https://user-images.githubusercontent.com/23008201/44697554-e5215b00-aaae-11e8-8397-d4f83ab11e7a.png)
Snipaste版本1.16.2
Snipaste语言设置：English（在简体中文下也是同样的问题）
操作系统，最新的windows10家庭版，版本号1803，语言设置：中文（zh-Hans-HK），地区设置：香港，首选语言中文，见下图：
![image](https://user-images.githubusercontent.com/23008201/44697667-595bfe80-aaaf-11e8-8be7-87d53a867d9c.png)

**Comment by liulex** [comment]
只有 Snipaste 有这种情况？

**Comment by zongsheng-zhao** [comment]
我用的某个visual studio插件也出现了一部分的数字乱码，但是其他软件都没有问题。我把windows显示语言调成英文后这个问题也会消失。会不会是windows的某个API用的不是很严谨，所以在某些版本的win10下会有显示上的问题？类似C++的undefined behavior

**Comment by liulex** [comment]
我使用了你截图的设置也无法重现哦……
用的是 Qt 封装的接口，不存在使用不正确的原因，
只有尝试更新系统版本了或乱调系统设置了 \_(:з」∠)\_

**Comment by liulex** [comment]
已修复，会在下一次更新包含。

**Comment by zongsheng-zhao** [comment]
感谢！方便分享是什么导致的这个问题吗？这个问题我在其他软件上也遇到过一两次，想看看能否有所帮助

**Comment by liulex** [comment]
@zongsheng-zhao 
在 `简体-香港` 这个区域格式下，`QLocale::system().zeroDigit()` 这个接口返回的是 `〇`，即 `0` 是 `〇`.
Qt 之后对其他数字的处理就更直接了，`1` 是 `〇` + 1，即 `〈`；`2` 是 `〇` + 2，即 `〉`……
大概算是 Qt 的 bug……

**Comment by YouTing-198** [comment]
把电脑的区域格式修改为中国大陆即可，他们的日期格式和作者（大陆）的不一样
