### ISSUE TITLE
能不能增加记号笔自由路径涂色

### ISSUE THREAD

**Issue by chariothy** [Snipaste/feedback#979]
请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282
记号笔现在只能画直线，能不能增加自由路径涂色？我们截图时经常需要在一个区域涂色。谢谢！

**Comment by StarryVoid** [comment]
你可以使用画笔，其实记号笔就是一个alpha通道由255改为128的普通画笔

**Comment by septs** [comment]
Duplicate of #477
