### ISSUE TITLE
贴图无法去除，也无法销毁

### ISSUE THREAD

**Issue by cai23511** [Snipaste/feedback#980]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282
有一个贴图无法去除，也无法销毁，暂时处理方法是隐藏贴图，但是如果新出来贴图，之前的这个一直停留在屏幕固定位置的贴图仍然又出现了
---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by liulex** [comment]
误触了鼠标穿透功能，详见全局快捷键设置。

**Comment by aNewContent** [comment]
https://github.com/aNewContent/puremvcstudy/blob/master/Snipaste_2020-11-13_10-36-15.png
设置了全局鼠标穿透，关闭穿透后现在成这样子啦。excel底—snipaste截图—右击excel展示。
所以我现在如何才能恢复正常使用呢。怎么清理掉这个截图。一定要更新么。

**Comment by Montwx** [comment]
Find the software used to create this sticker. For example, I was using Adobe Illustrate at that time. Reopen that software. Then place the mouse on the edge of the sticker to zoom in and out. Then press Esc, or F1,F3 shortcuts to delete it. (the previous software may not need to be reopened either. The key point is that you can zoom in and out of the texture by placing the mouse on the edge of the texture.

**Comment by Montwx** [comment]
> https://github.com/aNewContent/puremvcstudy/blob/master/Snipaste_2020-11-13_10-36-15.png 设置了全局鼠标穿透，关闭穿透后现在成这样子啦。excel底—snipaste截图—右击excel展示。 所以我现在如何才能恢复正常使用呢。怎么清理掉这个截图。一定要更新么。

No, detailed can see my comments
