### ISSUE TITLE
复制的图片贴图后编辑文字无法输入逗号句号等符号

### ISSUE THREAD

**Issue by xinchenjingtu** [Snipaste/feedback#982]
重现步骤：
1.复制一张图片
2.快捷键贴图
3.在贴图上右键选择标注
4.选择文本编辑
5.输入，。——_,.等符号
6.完

windows7系统，64位
版本号如下：
![image](https://user-images.githubusercontent.com/31204263/45274788-94b4ef00-b4eb-11e8-9575-8ee2e9e8cb5d.png)

英文状态下可以输入，中文状态下无法输入，字体微软雅黑，手心输入法
![image](https://user-images.githubusercontent.com/31204263/45331897-00f12a80-b5a0-11e8-8063-6b0a39607758.png)
![image](https://user-images.githubusercontent.com/31204263/45331905-15cdbe00-b5a0-11e8-8111-0b907ff5ba0b.png)

**Comment by StarryVoid** [comment]
咨询一下你的默认选择字体和输入法

**Comment by xinchenjingtu** [comment]
字体微软雅黑，手心输入法，具体看上图

**Comment by liulex** [comment]
see #165
