### ISSUE TITLE
截图之后, 标注的时候, 比如画红框, 有瞄点, 看不准红框的具体位置, 很麻烦

### ISSUE THREAD

**Issue by tty5** [Snipaste/feedback#983]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 建议修改一下

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by StarryVoid** [comment]
具体位置可以按Alt查看坐标

**Comment by tty5** [comment]
参考微信截图的界面, 很舒服, 就差这个了

**Comment by tty5** [comment]
没得搞吗

**Comment by tty5** [comment]
估计看来没反应了

**Comment by Geeyun-JY3** [comment]
至少 V2 的近期版本（2.8.8 微软商店版）实测任意标注的边缘定位锚点被拖动时都会隐藏。现在应该是没有标注的边缘定位锚点会遮挡的问题。
