### ISSUE TITLE
笔记本自带屏幕设置为副屏幕，扩展屏幕为主屏幕时截图位置偏移

### ISSUE THREAD

**Issue by Martinzzyy** [Snipaste/feedback#988]
笔记本电脑
Windows7
笔记本自带屏幕设置为副屏幕，扩展屏幕设置为主屏幕
这时候再截图，位置会往右边偏移很严重
基本上笔记本自带屏幕截不到，扩展屏显示内容为自带屏幕上的内容，扩展屏上原来的内容往右偏移

**Comment by peiqianggao** [comment]
+1，带扩展屏幕时，电脑休眠前可正常单独截两个屏幕，电脑休眠唤醒后，扩展屏幕就截不了图了，重新插拔 HDMI 线也无效，只能重启电脑。

**Comment by Martinzzyy** [comment]
@liulex 可能是我版本的问题，我刚才看了一下，是1.0（2016.07.27）的版本
