### ISSUE TITLE
macbook 截图后粘贴到邮件系统中，竟然是 tiff，并且根本无法修改这个格式

### ISSUE THREAD

**Issue by wenxq** [Snipaste/feedback#990]
发现了 bug？
* 使用 QQ截图之类的粘贴到邮件中，发送最终是 png，而 snipaste 奇葩的很，相应的文件存储配置为 png，实际截图拷贝到 邮件中竟然是 tiff，导致其他人，很多都看不到图片内容，还不能修改这个格式，现在看起来暂时只能弃用

**Comment by stevenzhu25** [comment]
@wenxq 默认粘贴也是png的....您可能需要查一下您的剪贴板...

**Comment by stevenzhu25** [comment]
@liulex

**Comment by kimonoki** [comment]
试了下mac自带mail中确实是tiff格式

**Comment by liulex** [comment]
重复 #881 #959
