### ISSUE TITLE
Windows10下Snipaste偶尔启动较慢

### ISSUE THREAD

**Issue by cooper1x** [Snipaste/feedback#991]
```
[General]
as_admin=true
copy_without_sharp=true
hex_color=true
start_on_boot=true
startup_fix=true
language=zh_cn
first_run=false
**process_priority=3**

[Snip]
ask_for_confirm_on_esc=false

[Update]
include_beta=true

```
上面我把`process_priority=3`加到配置里面，比之前虽说有些改观，但是还是会出现偶尔几秒钟才触发截图功能的问题。
相比最常见的QQ截图和微信截图，缺从来没发生过这个情况。
顺便提个小建议，橡皮擦建议可以设置为两个，一个是擦除画笔，另一个是擦书截图的内容

**Comment by liulex** [comment]
#498 有过讨论，在 2.x 版本有改善。
擦除截图是什么操作？直接用画笔涂白？

**Comment by olivegogo** [comment]
win7也有这个现象,貌似是间隔很久启动截图框的时候会慢几秒,然后就好一段时间(截图框可以快速显示)

**Comment by olivegogo** [comment]
win7也有这个现象,貌似是间隔很久时间启动截图框的时候会慢几秒,然后就好一段时间(截图框可以快速显示)
