### ISSUE TITLE
希望添加贴图可以旋转的功能

### ISSUE THREAD

**Issue by Youngtiny** [Snipaste/feedback#993]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by 52Heartz** [comment]
同希望增加贴图旋转功能，比如下面这张图片，扫描版的PDF文件，其内容不是水平的，如果能支持旋转1度或者2度就好了。目前只支持旋转90度的倍数。希望可以加上，谢谢！
![snipaste_20180929_110328](https://user-images.githubusercontent.com/16707379/46240282-8fa2db80-c3d7-11e8-886e-294a37b63ec2.png)

**Comment by liulex** [comment]
重复 #478
