### ISSUE TITLE
snipaste 是不是停止更新了

### ISSUE THREAD

**Issue by silloy** [Snipaste/feedback#998]
snipaste 是不是停止更新了，windows和mac 版本一直是1.16.2, 请问有更新计划吗

**Comment by stevenzhu25** [comment]
@silloy Microsoft Store版已经更新至2.1
桌面版还在开发中

**Comment by secoba** [comment]
> snipaste 是不是停止更新了，windows和mac 版本一直是1.16.2, 请问有更新计划吗

希望大牛能解决下mac下的snipaste，复制粘贴到office后，文档变得异常大 -   -
